### ISSUE TITLE
Darksky forecast date format

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#1]
The Darksky forecast date format is currently US i.e. M/D Could there please be an option to change that to D/M for those of us down in the colonies using dd/mm/yy   :)

**Comment by poblabs** [comment]
I've had this one on my list to mirror the way weewx's built in methods are done. Just haven't gotten around to it. Will take a look at it though!

**Comment by poblabs** [comment]
Making headway on this. It will require a few custom label options (different than Extras). 

Not sure the best approach. 

e.g.
1 variable for all "Long dates" (December 22, 2018, 10:19 PM EST) 
1 variable for all "short dates" (Dec 12/22)
and a couple variables in between for the mixed dates. 

Or 1 variable for each time placement. Like "records_page" for all dates on records page. And "earthquake" specific to the earthquake box. and "darksky_header" specific to the darksky bar, and "last_updated" for the last updated time. 

Thoughts?

**Comment by poblabs** [comment]
Some progress though. 

![image](https://user-images.githubusercontent.com/3484775/50527731-299e2100-0ab8-11e9-8073-134e91010a19.png)

**Comment by sgrayban** [comment]
I like short dates but I'll take whatever comes my way !

**Comment by 41south** [comment]
If you're splitting it into 2 options I like the sound of the first one - long or short as appropriate

1 variable for all "Long dates" (December 22, 2018, 10:19 PM EST)
1 variable for all "short dates" (Dec 12/22)
and a couple variables in between for the mixed dates.

**Comment by poblabs** [comment]
I can split it into as many options that makes sense without hopefully
overwhelming users.

I might have to take inventory of all the dates and see if I can
consolidate into an easy transformation.

**Comment by 41south** [comment]
Yeah agree that less is more - the only one I saw that was "wrong" (for us colonials) was the Darksky forecast date format. My records page and all of of the charts/graphs look just fine

**Comment by poblabs** [comment]
I figure if I'm going to offer a way to localize one section of time, I might as well try for all of it and have a default format (which weewx offers built in).

**Comment by 41south** [comment]
True, that does make sense and should keep it easy and consistent 👍

**Comment by poblabs** [comment]
There's so many dates. MQTT timestamp, darksky, earthquake, sunrise/sunset, record snapshot, and the records page alone has 3 or 4 different formats for a date. Most of it I can leave alone, I think it really is the Month/Day that was messing you up.

I keep flip flopping in my head to do a "long_date" "short_date" and do my own best guess at what makes sense. 

Or doing "earthquake_timestamp", "mqtt_timestamp", "records_page_timestamp"....

**Comment by poblabs** [comment]
According to the weewx developer thread I posted earlier, it's suggested I just let weewx handle all the dates as part of the built-in system. That's going to change some of the look and feel - hopefully not too bad

**Comment by poblabs** [comment]
I've been making a lot of progress with removing the hard-coded time and date formatting. Now most everything respects the station's locale. Still some work to go, but I am closing this issue because the DarkSky forecast formatting is resolved in the latest commit

There are a lot of changes that have been uploaded in the last few days. If you want to test your best bet is to backup the skins folder, download the Master ZIP file from this repo and upload the files to their proper homes. 

It's still beta for the next couple of days, so let me know if you encounter any problems!
