### ISSUE TITLE
ReportEngine throws error if earthquake is enabled.

### ISSUE THREAD

**Issue by KasturiNagarWeather** [poblabs/weewx-belchertown#10]
Hi,

I get below errors if I enable earthquake:

![image](https://user-images.githubusercontent.com/36511283/45255410-c15def00-b3a3-11e8-8da5-8ad3745e3369.png)

My latitude is 13N and longitude 77.665

Regards,
Praveen

**Comment by poblabs** [comment]
This is due to there being no earthquake data for your lat/long. Not sure if it's because of a USGS.gov limitation or just no earthquakes. I don't know USGS's historical data available, but I'll update the skin to catch this error and just display "No earthquake data available" in it's place.

**Comment by poblabs** [comment]
While this fixes the issue of no data being available, I'd suggest changing your `earthquake_maxradiuskm` setting to 5000 or something.
