### ISSUE TITLE
Unable to change Rain label

### ISSUE THREAD

**Issue by bjcatlin** [poblabs/weewx-belchertown#100]
I've just started trying out the new 1.0rc7 branch, and I am really liking how flexible this new version is.  Great Job!

I've run in to one small issue with the way that I present my site.  I've been changing instances of the word "Rain" to "Precipitation" since my weather station heats the rain bucket in the winter and measures the water content of the snowfall.  I've been able to easily do this using skin.conf on version 1.0rc7 except for the Rain label in the current conditions at the top of the page (just above the sun and moon info).  I can't seem to find where that one can be changed.

**Comment by poblabs** [comment]
There are two places. We are working on the [documentation ](https://github.com/poblabs/weewx-belchertown/wiki/Translation-and-Localization-of-the-Belchertown-Skin)for this, and [the charts](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation) too. 

To change the text on the page above sun and moon, it would be a label override within weewx.conf. Here's an example:

```
[StdReport]
    [[Belchertown]]
        [[[Extras]]]
            ...your_extra_options ...
        [[[Labels]]]
            [[[[Generic]]]]
                rain = Precip.
```

![image](https://user-images.githubusercontent.com/3484775/56231586-d511b800-604c-11e9-8a5e-96786c716fc1.png)

To change the label in the charts, it would be a chart override - so in your custom graphs.conf, under the rain chart you would add the name option, like below:

```
    [[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Precipitation Total
```

![image](https://user-images.githubusercontent.com/3484775/56231814-5701e100-604d-11e9-9f59-04b3b930588f.png)

**Comment by poblabs** [comment]
For the Records page, there's more weewx.conf label overrides you'll have to do. For example:

```
[StdReport]
    [[Belchertown]]
        [[[Extras]]]
            ...your_extra_options ...
        [[[Labels]]]
            [[[[Generic]]]]
                records_rain_records                = Precip Records
                records_highest_daily_rainfall      = Highest Daily Precip
                records_highest_daily_rainrate      = Highest Daily Precip Rate
                records_month_high_rainfall         = Month with Highest Total Precip
                records_total_rainfall              = Total Precip for
                records_consec_days_with_rain       = Consecutive Days With Precip
                records_consec_days_without_rain    = Consecutive Days Without Precip
```

You can find all of these labels within skin.conf. But we add them to weewx.conf so they'll survive upgrades. 

Hope this helps

**Comment by bjcatlin** [comment]
That is PERFECT!  Thank you very much.  Didn't know about the whole label override thing...until now.

**Comment by poblabs** [comment]
@bjcatlin That's because I added it last week to make it easier 😄 Let me know if you come across anything else since you're testing out the development track!

**Comment by bjcatlin** [comment]
OK, found an issue with the "rain = precipitation" label override...  While it does change the Rain to Precipitation in the current conditions, it ALSO changes it in the 8-day forecast icons.  So instead of it saying that tomorrow's forecast is for Rain, it says that it is for Precipitation.

Is there any way to seperate the two?

**Comment by bjcatlin** [comment]
Trying to add a screenshot...

**Comment by poblabs** [comment]
You can paste the screenshot with CTRL+V if i you can copy it. Or you can drag and drop the saved image into this text box. 

![image](https://user-images.githubusercontent.com/3484775/56248245-6eed5b00-6075-11e9-99f6-e30f296556dd.png)

**Comment by poblabs** [comment]
Good catch - I must be able to separate it, let me take a look at this one in a little bit!

**Comment by poblabs** [comment]
@bjcatlin This should be all set if you want to try it out. There was a conflict with the built-in weewx `"rain"` label, and the one I added. 

You need to update the `skins/Belchertown/skin.conf`, and the `skins/Belchertown/js/belchertown.js.tmpl` files. You can download the development zip file again and just update those 2 files.

This adds a new label for the DarkSky forecast called `darksky_rain`, so if you want to override that then you would add the label override to your weewx.conf as discussed above. 

Restart weewx once you've updated those two files and it should be back in business for you.
