### ISSUE TITLE
Adding history

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#101]
Hi,

I'm using niculskin https://gitlab.com/ngulden/niculskin for several years, but unfortunatly, there's no more update since two years now. And now, it looks not very modern skin.

Your skin is very modern and has a very good design. But there's only a thing missing is history like this :

http://newall-wx.gen.nz/history.html in english.

Here's mine in french : http://meteo.payrastre.fr/history.html

I also can help you to do a french version of your skin. I use 0.9 and i do some french translations here : http://meteo.payrastre.fr/belchertown

I see you change format in 1.00 so i can help you on this new version.

Thanks your work.

Olivier.

**Comment by olpayras** [comment]
I worked on history feature. I do an include file named history.inc that i added in reports/index.html.tmpl. You can include in future revision here or anywhere. I used module from Bootstrap skin. So you have to put history.inc in bin/user directory. After that, you should change the skin.conf . 

Changes :

### Skin.conf
```
[CheetahGenerator]
   This section is used by the generator CheetahGenerator, and specifies
   which files are to be generated from which template.

    search_list_extensions = user.belchertown.getData, user.historygenerator.MyXSearch
```

```

[HistoryLabels]

    [[history_tables]]
        title     = History
        min_temp  = Minimum Temperature
        max_temp  = Maximum Temperature
        avg_temp  = Average Temperature
        rain      = Rainfall
        rain_days = Days of rain
        uv_max    = UV Index Max
        
###############################################################################

[HistoryReport]

    #
    # Settings for the HTML month/year colour coded summary table generator
    #

    # minvalues, maxvalues and colours and fontColours should contain the same number of elements.
    #
    # For example,  the [min_temp] example below, if the minimum temperature measured in
    # a month is between -50 and -10 (degC) then the cell will be shaded in html colour code #0029E5.
    #
    # colours = background colour
    # fontColours = foreground colour [optional, defaults to black if omitted]

    # Default is temperature scale
    minvalues = -50, -10, -5, 0,  5, 10, 15, 20, 25, 30, 35
    maxvalues = -10, -5,   0, 5, 10, 15, 20, 25, 30, 35, 60
    colours =   "#0029E5", "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
    fontColours =   "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF"
    monthnames = Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    # Restrict the size of the table by ignoring everything before startdate
    # Specify in unix epoch time. e.g. 1325376000 is 1-Jan-2012
    #startdate = 1325376000

    # The Raspberry Pi typically takes 15+ seconds to calculate all the summaries with a few years of weather date.
    # refresh_interval is how often in minutes the tables are calculated.
    refresh_interval = 60

    [[min_temp]]
        obs_type = outTemp                 # obs_type can be any weewx reading
        aggregate_type = min               # Any of these: 'sum', 'count', 'avg', 'max', 'min'

        summary_column = true
        summary_heading = Min

    #
    # Can also use these aggregate_types:  'max_ge', 'max_le', 'min_le', 'sum_ge' to count days
    # where an observation is ge: greater of equalto, or le: lessthan or equal to a threshold value
    # To specify this threshold, use: aggregate_threshold = [value], [units]
    #
    # e.g Specify temperature threshold of 20C:  aggregate_threshold = 20, degree_C
    #

    [[max_temp]]
        obs_type = outTemp
        aggregate_type = max

        summary_column = true
        summary_heading = Max

    [[avg_temp]]
        obs_type = outTemp
        aggregate_type = avg

        summary_column = true
        summary_heading = Avg

    [[rain]]
        obs_type = rain
        aggregate_type = sum

        minvalues = 0, 25, 50, 75, 100, 150   # Override default temperature colour scheme with rain specific scale
        maxvalues = 25, 50, 75, 100, 150, 1000
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total

    [[rain_days]]
        obs_type = rain
        units = Days                        # Override default table units label
        aggregate_type = sum_ge
        aggregate_threshold = 1, mm
        minvalues = 0, 6,  12, 18, 24, 30   # Override default temperature colour scheme with rain specific scale
        maxvalues = 6, 12, 18, 24, 30, 200
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total

    [[uv_max]]
        obs_type = UV
        aggregate_type = max
        minvalues = 0, 2, 4, 6,  8, 10, 12, 15
        maxvalues = 2, 4, 6, 8, 10, 12, 15, 50
        colours = "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total
```
### reports/index.html.tmpl

After #include "page-header.inc", add  

```
#if os.path.exists("history.inc")
                    #include "history.inc"
                #end if


```
Joigned the modified files.

[history.zip](https://github.com/poblabs/weewx-belchertown/files/3104741/history.zip)

**Comment by HoracioDos** [comment]
Hi
This is a cool feature. I've been doing it almost the same in a different way. As NOAA reports are not very meaningful for me, I replaced them with some stats reports (same text files with different data and layout) and I use them for GNUPlot data input to generate heatmaps.
![heatmap](https://user-images.githubusercontent.com/4549674/56658399-f0924980-6670-11e9-95dd-63035dd7dc21.png)
[stats-2019-04.txt](https://github.com/poblabs/weewx-belchertown/files/3112162/stats-2019-04.txt)

**Comment by olpayras** [comment]
Yes, nice .

I've forked [this](https://github.com/olpayras/weewx-belchertown/tree/patch-2) if you wanna try history inserted in reports. It can be inserted everywhere, juste put #include history.inc where you want in the code.

Here's a [preview](http://www.payrastre.fr/weewx/belchertown/reports/)

**Comment by HoracioDos** [comment]
Hello Olivier
I like these tables very much and It's easier to merge as they included into reports. I didn't check history.py but I would like to ask if "Days of Rain" are dates or they are the sum of days that rained in a month. For example, in January 2018. Did it rain 21 days in that month?
Thanks in advance!

**Comment by olpayras** [comment]
Hello HoracioDos,

Happy to ear, that you like this feature. It really rained 21 day on january 2018 if i based on NOAA reports [here](http://www.payrastre.fr/weewx/belchertown/NOAA/NOAA-2018-01.txt). It was 22 days, cause it seems that day Under 1mm or 0.1 inches are not Added.

**Comment by HoracioDos** [comment]
Wow! I don't know about the weather in your region, but I guess that climate change is not a joke for you. Thanks for your answer.

**Comment by poblabs** [comment]
Hi, thanks for your effort on this. I'm going to close this out for the time being!

**Comment by olpayras** [comment]
I keep a branch with this feature, if you want to add it on a further version you can use my fork.
