### ISSUE TITLE
Page autorefresh

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#102]
Hello Pat.
I added this line in header.html.tmpl to auto refresh the webpage every 5 minutes. 
`<meta http-equiv="refresh" content="300">`
I've disabled mqtt websockets because I will be uploading everything to a web hosting service. Will you consider something like this? I know that there several methods to do it but I don't know where it should the best place to add this feature. Perhaps It may be an ajax function and some $Extras tags to control it.
Thanks in advance.

**Comment by HoracioDos** [comment]
I moved auto refresh function to index.html.tmpl and I added a new config tag webpage_autorefresh in Belchertown Extras. It seems to work fine.
```
<script type="text/javascript">
     #if $Extras.has_key("mqtt_websockets_enabled") and $Extras.mqtt_websockets_enabled == '0'
         #if $Extras.has_key("webpage_autorefresh") and $Extras.webpage_autorefresh != '0'
             function autoRefreshPage()
             {
               window.location = window.location.href;
             }
             setInterval('autoRefreshPage()', $Extras.webpage_autorefresh);
         #end if
     #end if
</script>
```

**Comment by biltmorelaker** [comment]
@HoracioDos Just to let you know, I upload all of my WeeWX output to a web hosting service. I run a Raspberry Pi in my home connected to my Davis Vantage Vue console. WeeWX creates the web pages on the Pi and I use Rsync within WeeWX to upload those files to my web hoster. I run MQTT with no issues. in fact I am running the MQTT Mosquitto broker on the hoster as well as having the hoster publish my web pages at https://wx.kutzenco.com. Why do you think you can't use MQTT?
phil

**Comment by poblabs** [comment]
I would probably leverage a JavScript timer, and `ajaxweewx();` to update the values without a page refresh. I'll have to look into adding this at a later time

**Comment by HoracioDos** [comment]
Hi @biltmorelaker!
This is how I tested. Perhaps I've made a mistake but I think that the auto refresh request is still valid.
1) I changed raspberry pi ip address to "localhost" in weewx.conf to avoid any problems in the destination machine.
belchertown_root_url = http://localhost 
2) I synched everything with sftp extension to another computer.
3) When I checked the copy I got a message "Cannot connect to MQTT broker" or something like that. As I disliked this message and I would prefer to avoid opening Mqtt Broker to the Wan I removed websocket config.

**Comment by HoracioDos** [comment]
> I would probably leverage a JavaScript timer, and `ajaxweewx();` to update the values without a page refresh. I'll have to look into adding this at a later time

Thanks for considering this request.

**Comment by biltmorelaker** [comment]
@HoracioDos 
First, I think you need to set belchertown_root_url to the url of the web page you're copying files to rather than to the Raspberry Pi that created those pages. If you don't I think you'll have issues navigating the Belchertown pages through the menu.

Second, it sounds like your MQTT broker is running on your Raspberry Pi. I understand why you don't want to open the broker to the internet. But there are external MQTT brokers that you could use (instead of running our own) that you can have your Pi upload MQTT data to. See https://github.com/poblabs/weewx-belchertown#mqtt-brokers. If you use a password, it should be safe for your Pi to publish your MQTT data to the external broker (at least as safe as it is for you to sftp web pages to your web hoster).

That's not to say a request for updating without MQTT isn't valid. Just there is a way for you to use MQTT if you like by leveraging an external broker.

**Comment by HoracioDos** [comment]
> @HoracioDos
> First, I think you need to set belchertown_root_url to the url of the web page you're copying files to rather than to the Raspberry Pi that created those pages. If you don't I think you'll have issues navigating the Belchertown pages through the menu.

You are right, as far as I can remember something like that happened when I tested. I didn't buy the domain yet, so I was investigating how to config everything to do it right.

> Second, it sounds like your MQTT broker is running on your Raspberry Pi. I understand why you don't want to open the broker to the internet. But there are external MQTT brokers that you could use (instead of running our own) that you can have your Pi upload MQTT data to. See https://github.com/poblabs/weewx-belchertown#mqtt-brokers. If you use a password, it should be safe for your Pi to publish your MQTT data to the external broker (at least as safe as it is for you to sftp web pages to your web hoster).

Again, you are right. I will check this. Thanks for the tip. Do you know much outbound traffic it could generate from local to the external broker?

> That's not to say a request for updating without MQTT isn't valid. Just there is a way for you to use MQTT if you like by leveraging an external broker.

I apologize If I was rude. English is not my mother language and I'm still learning to express myself properly.
Thanks for taking the time and effort to offer your comments!

**Comment by HoracioDos** [comment]
Hello Phil
I forgot to ask. What's your hosting provider?
Thanks!

**Comment by biltmorelaker** [comment]
@HoracioDos  You were not rude at all! And your English is very good.

I don't really know the traffic MQTT publishing generates. It would depend upon how often a LOOP is generated. On my system (a Davis Vantage Vue) LOOPs are generated every 2.5 seconds. I imagine that the total traffic from MQTT is quite a bit less than the sftp data traffic which is generated every ARCHIVE interval (every 5 minutes for my setup). @poblabs may have a guess.

I am using Digital Ocean. I rent 1 "droplet" (https://www.digitalocean.com/products/droplets/) from them which runs both my MQTT broker and my NGINX web server on Ubuntu Linux. Cost is USD 5/month plus an extra USD 1/month for backup capability. So the total is USD 6/month.

If you decide to use them (they have been very reliable for me, there is a link on @poblabs web blog here (https://obrienlabs.net/setup-kiosk-ubuntu-chromium/) near the end of his article that gives you a discount of the first couple of months for free and gives some financial credit to Pat (we need to support him for all of his hard work on the Belchertown skin 😃!)

Good luck whether you go with MQTT or use another way to refresh your web page and let us know when your website is online.

phil

**Comment by HoracioDos** [comment]
Hello Phil.
Thanks for your detailed answer. I see that you opted for the smallest droplet and your site works fine with it. I should estimate the right sizing for an additional wordpress site. (My wife wants to open a small yoga studio). Also an influxdb and grafana servers would be very convient for me. I'll keep in mind how to reward Pat. 
Thanks again!

**Comment by poblabs** [comment]
Good to go with this option. New Extras option `webpage_autorefresh` and readme updated with the description. Thanks!

**Comment by HoracioDos** [comment]
This a Go-live test. I must enable https asap.
http://climacolegiales.ddns.net

**Comment by poblabs** [comment]
Looks good but you have mqtt enabled. Set that to 0 to enable the page auto
refresh. They both don't work at the same time.

**Comment by HoracioDos** [comment]
Auto Refresh is already off. 
I don't fully understand how reload_hook_images works. I have an inc file "index_hook_after_forecast.inc" which shows two satellite images from other site. They are refreshed every 10 minutes, so I would like to refresh these images too.

**Comment by poblabs** [comment]
Oh ok I thought you wanted auto refresh on. I can't view your MQTT because it's on your LAN and I don't have access to it. But the page looks good! 

`WebSocket connection to 'ws://192.168.1.41:9001/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

The [reload_hook_images looks in the index_hook*.inc files](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L589-L607), and if there's an `img src=` present, it'll reload those images. This was a way to have radar JPG update without having to do `website_autorefresh`.

**Comment by poblabs** [comment]
I like this section. Maybe I will do this as a built in feature? What code did you use for it?

```
El día tiene 10:30:03 horas de luz.
Hoy es 1m 38s más corto que ayer.
```

**Comment by HoracioDos** [comment]
Hello Pat

> Oh ok I thought you wanted auto refresh on. I can't view your MQTT because it's on your LAN and I don't have access to it. But the page looks good! 

I'ḿ not sure what I want to do yet. if I want mqtt or not.  

> The [reload_hook_images looks in the index_hook*.inc files](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L589-L607), and if there's an `img src=` present, it'll reload those images. This was a way to have radar JPG update without having to do `website_autorefresh`.

So It suits for my needs. When I tested I saw some kind of orange lightning where images should be. I'll test it again.

> El día tiene 10:30:03 horas de luz.
> Hoy es 1m 38s más corto que ayer.

Thanks! I took the code from Tom's Seasons skins (cheetah script) and hooked into index.html.tmpl. it is not very elegant but it works. I attached 3 files. If you like something else, feel free to grab it from my fork. It 's always synched against your repo. I also found a very interesting website about pyephem with a lot of astronomy examples. I liked the Analemma very much
https://github.com/HoracioDos/weewx-belchertown
https://chrisramsay.co.uk/posts/2017/03/fun-with-the-sun-and-pyephem/

My new weather station finally arrived and I'll start to tinker the old one. I'm looking for the best place to install them. Urban geography doesn't help at all.
[daylight.zip](https://github.com/poblabs/weewx-belchertown/files/3166909/daylight.zip)

**Comment by HoracioDos** [comment]
Hello Phil!
I followed your advice and I set weewx to upload data to hive public broker a few minutes ago. Now I don't understand how it works, there are not client id or user and password settings. There should be a lot "weather/loop" topics. When the skin connects to the broker, how does it choose the correct topic? What am i missing?
Thanks!

**Comment by biltmorelaker** [comment]
@HoracioDos Please post the [[MQTT]] section of your weewx.conf file (make sure to remove any sensitive information there). As you know, I'm running my own broker on Digital Ocean, but I'll try to setup on Hive on my lab instance and see if I can give you settings that work.

**Comment by HoracioDos** [comment]
Hello Phil.
It seems to be working automagically. Is it so simple? How does the client make to connect to the proper topic?

```
 Mqtt settings
        server_url = mqtt://broker.hivemq.com:1883/
        topic = weather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        enable = True

Belchertown settings
            mqtt_websockets_enabled = 1
            mqtt_websockets_host = broker.hivemq.com
            mqtt_websockets_port = 8000
            mqtt_websockets_ssl = 0
            mqtt_websockets_topic = weather/loop
            disconnect_live_website_visitor = 900000
```

**Comment by poblabs** [comment]
It's a lot of magic that I put in there 😄 

There's 2 parts to how it works:

`weewx-mqtt` extension by mwall publishes your data as a JSON packet to the MQTT broker. You publish to `topic = weather`. The extension adds `/loop` because you use `binding = loop`. 

Then Belchertown uses JavaScript to connect to MQTT Broker on **Websockets** and subscribes to the topic you define in the `mqtt_websockets_topic = weather/loop`. 

Then after that it's all jQuery to update the website.

**Comment by biltmorelaker** [comment]
Pat magic, as he says.

The only thing I suggest you do if you wish to continue using HiveMQ as your broker is change the name of topic from `weather `to  something like `HoracioDosweather`. Right now, if someone else publishes to weather, that data will mix with yours and the skin will download that data as well.

---

So the MQTT settings could be:
`topic = HoracioDosweather`

and then the Belchertown settings would be:
`mqtt_websockets_topic = HoracioDosweather/loop`

It's pretty unlikely that anyone other than you  would publish to HoracioDosweather.

**Comment by HoracioDos** [comment]
That's what I was wondering! The penny dropped when I read your example! I didn't understand how the client could identify my own topic from other "weather" topics. It was so obvious! I will create a topic with a dummy mac address name. It should be quite unique.
Thank you very much!
