### ISSUE TITLE
Barometer yaxis management on graphs

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#106]
Hello!
I would like to share and issue and maybe a feature proposal. 

Currently my barometer graphs shows about 20 labels on yaxis (996.12, 996.48.....1002.60 mbar), even original Belchertown website currently shows ~12 labels from 29.88 to 30.10 inhg. 

That 's a lot and slightly weird (not round numbers).

Moreover, in case of stable pressure over the day, the axis will adapt and kind of zoom in.
It' s maybe not very interesting to show this way because the curve looks noisy and at 1st look does not show if absolute value is high or low. It may be better to use a wider scale, showing a more flat curve. 

So I wonder if:
- could we limit the number of divisions on yaxis? 8 or 10 may be enough? 
- I have seen highcharts propose a so called "softmin/softmax" option. 
It may be nice way to fix a "standard" scale (let's say 970-1030mbar) but still allows the graph to adapt if values gets out of this range. 

Best regards,

**Comment by poblabs** [comment]
Remind me, are you on the development version 1.0?

**Comment by 41south** [comment]
I had a go at setting some axis max and mins but it does break the axis
numbers in weird places. I set 840 min and 1040 max and the bottom line
comes up as 787.50 and the top at 1102.5

**Comment by poblabs** [comment]
Yeah Highcharts will auto-detect the resolution of the yAxis based on the data in the chart. I had a request a long time ago that [barometer should be a 0.01 resolution](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L1079-L1083), which explains why you see it in such fine detail. 

My thought is to add a `yAxis_tickInterval` option to the graphs.conf so that you can specify `yAxis_min`, `yAxis_max` and `yAxis_tickInterval` which should satisfy everyone? It's a hard job to do 😄

**Comment by 41south** [comment]
Sound like a reasonable idea to me :)

**Comment by bonjour81** [comment]
Hi!
To answer the questions from beginning, yes I use 1.0 development version (I think downloaded from one day ago).

Tick interval seem a good way to solve the issue :).

If you have a little time, you may have a look to those "soft" limits option available in highcharts. I find interesting to set reasonable limits for most situations that will expend if some day the barometer get extremely high or low. It could be nicer than setting superwide hard limits. 
What do you think about it?

**Comment by poblabs** [comment]
I will add the tick interval when I can. 

Also, Highcharts should be set on soft limits right now for min and max on y axis. So for example take my chart below. It shows the high and the low of the data within the window. All charts do this unless you specify a yAxis_min or a yAxis_max in the chart options. 

![image](https://user-images.githubusercontent.com/3484775/56657662-a1dfb200-6666-11e9-8bcd-071a440d805b.png)

**Comment by bonjour81** [comment]
Maybe I missed something but, is it already possible to set for example barometer scale on 970mbar / 1030mbar but still make sure the scale will expand if barometer get above or below this? (it's rare to exceed thos limits at my place, but can happen). 

It's what I understood to be softmin/softmax limits from highcharts ([https://api.highcharts.com/highcharts/yAxis.softMax](https://api.highcharts.com/highcharts/yAxis.softMax))

The point of such scale would be to see at a glance if barometer is high or low, even if the value is stable for the day. With "automatic scaling", a stable barometer during a day will lead to a very short range scale of a few mbar.

This may be useful for other values, like temperature.

Let me know if I'm too confusing :-)

**Comment by poblabs** [comment]
This makes sense, and it's making me see that maybe I need to change the layout of graphs.conf. 

Instead of adding every yAxis feature ever, I think I can make it just as dynamic as the series data. But it will be a breaking change for anyone who has the skin installed now. 

I'll do some testing and update this when I have something worth sharing.

**Comment by bonjour81** [comment]
If I can make an humble suggestion (from someone that cannot fully understand what's in the python code :-) maybe it's easy to say).
It could just be added a couple of keyword for graphs.conf: what about adding  yaxis_softmin & yaxis_softmax in addition to yaxis_min, yaxis_max ?
This offers a lot a combinations for example, humidity or "ISS Receive stat"  could  use yaxis_max = 100 and yaxis soft_min = 30 ? 

Regarding breaking change...well people who are playing with development branch, it's a tacit agreement that things can change (at least from my side).

**Comment by poblabs** [comment]
I did not do the breaking change. There was too much to alter to make my original thought work. I may do it later but not now. 

So I added 3 new options, `yaxis_tickinterval`, `yaxis_softmin`, `yaxis_softmax`.

The `yaxis_tickinterval` can be applied to any chart, but if it is not applied to barometer, then barometer will default to 0.01 to satisfy past request for that level of accuracy. 

I think this is all set now. Here's some example code for graphs.conf, and the output. 

## Tick interval on temperature:

```
    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
            yaxis_tickinterval = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/56842449-08c9ba80-6863-11e9-837b-eb95cd8c16b5.png)

## The rest are barometer tickinterval and softmin softmax

```
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            yaxis_tickinterval = 0.1
```

![image](https://user-images.githubusercontent.com/3484775/56842210-40cffe00-6861-11e9-8a19-548dc7772173.png)


```
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            yaxis_tickinterval = 0.01
            yaxis_softmin = 29.7
            yaxis_softmax = 30.0
```

![image](https://user-images.githubusercontent.com/3484775/56842243-7b399b00-6861-11e9-96e2-c48794d84a57.png)


```
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            yaxis_tickinterval = 0.05
            yaxis_softmin = 29.40
            yaxis_softmax = 30.10
```

![image](https://user-images.githubusercontent.com/3484775/56842319-12065780-6862-11e9-90e2-abfbd853a061.png)

**Comment by bonjour81** [comment]
perfect! I'll try today!

**Comment by bonjour81** [comment]
@poblabs  Infact, I'm not sure the soft   limits works?
On your last example (just above this message), I would expect the graph to show 29.4 & 30.1 has min and max on yaxis, while it show 29.6 to 30.05.

I experience same on my side: I set softmin 970  softmax 1030 but current graph shows 1026-1030 (to fit the current curve).

**Comment by poblabs** [comment]
Verify your yaxis values change when you remove softmin/softmax and re-run wee_reports. 

I can tell the values are passed to the charts because the values change when i change them - so the options are working, but perhaps softmin and softmax are not what you are looking for

**Comment by bonjour81** [comment]
I have done a few tests, playing in the belchertown.js file.
for my tests, I have set in graphs.conf:
```
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            yaxis_tickinterval = 2
            yaxis_softmin = 990
            yaxis_max = 1040
```
display is: 
![test1](https://user-images.githubusercontent.com/24415431/56850122-4b8ca080-68fe-11e9-9e63-8e7f364a9498.png)

Then, If modified the belchertown.js as following:
```

// Some charts may require a defined soft min/max on the yAxis
//                options.yAxis[this_yAxis].softmin = s.yaxis_softmin ? s.yaxis_softmin : null;
                options.yAxis[this_yAxis].softmin = 990;
                options.yAxis[this_yAxis].softmax = s.yaxis_softmax ? s.yaxis_softmax : null;
```
=> No change

then I change softmin to softMin (as stated in highchart doc):
(I tested [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/softmin-softmax/) that softMax works, but not softmax.
```
                // Some charts may require a defined soft min/max on the yAxis
//                options.yAxis[this_yAxis].softmin = s.yaxis_softmin ? s.yaxis_softmin : null;
                options.yAxis[this_yAxis].softMin = 990;
                options.yAxis[this_yAxis].softmax = s.yaxis_softmax ? s.yaxis_softmax : null;
```

It does work better:
![test2](https://user-images.githubusercontent.com/24415431/56850151-c5248e80-68fe-11e9-864f-c6e31123b26e.png)

So I set back to original, only change "softMin" instead of "softmin":
```
                // Some charts may require a defined soft min/max on the yAxis
                options.yAxis[this_yAxis].softMin = s.yaxis_softmin ? s.yaxis_softmin : null;
                options.yAxis[this_yAxis].softmax = s.yaxis_softmax ? s.yaxis_softmax : null;

```
And I'm back to 1st graph (not working)...here I don't understand why?

**Comment by poblabs** [comment]
Try this? Replace those lines with this:

```
if ( s.yaxis_softmin ) {
    options.yAxis[this_yAxis].softMin = s.yaxis_softmin;
}

if ( yaxis_softmax ) {
    options.yAxis[this_yAxis].softmax = s.yaxis_softmax;
}
```

Update graphs.conf, restart weewx, then run wee_reports.

**Comment by poblabs** [comment]
Oh I just noticed you are using max, not softmax. Is that desired?

**Comment by bonjour81** [comment]
yes, I play with max and softmin ...it's just for testing and see behavior of both. At the end, I plan to use only soft values.

Funny, I had same idea as you :-) (to try `if ( s.yaxis_softmin )` ) 
but no working...I output s.yaxis_softmin on log and it does show 990. 

I tested this: 

```
 if (s.yaxis_softmin) {
                    console.log("s.yaxis_softmin:[" + s.yaxis_softmin +"]");
                  options.yAxis[this_yAxis].softMin = parseInt(s.yaxis_softmin);
                }
```

and it does works!

**Comment by poblabs** [comment]
Oh I see. It's a string so being ignored? Ok try this:

```
                options.yAxis[this_yAxis].softmin = s.yaxis_softmin ? parseInt(s.yaxis_softmin) : null;
                options.yAxis[this_yAxis].softmax = s.yaxis_softmax ? parseInt(s.yaxis_softmax) : null;
```

**Comment by bonjour81** [comment]
it works fine with a very little modification !

```
options.yAxis[this_yAxis].softMin = s.yaxis_softmin ? parseInt(s.yaxis_softmin) : null;
options.yAxis[this_yAxis].softMax = s.yaxis_softmax ? parseInt(s.yaxis_softmax) : null;

```
just replaced softmin by softMin, softmax by softMax

**Comment by poblabs** [comment]
Ah I only had a small typo in the options. softMin and softMax. I will update it.
