### ISSUE TITLE
graphs.conf is not considered if skin directory is not Belchertown

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#107]
Hi!
I would like to report a minor issue/bug.
I have currently setup 2 times "Belchertown" skin in parallel.
one in:
`/etc/weewx/skin/Belchertown`
an other in:
`/etc/weewx/skin/Belchertown_www`

1st one is genuine development branch, used on my local server (where weewx run).
2nd is my working skin where I currently translate to french (this one is uploaded and available online).

As far as I understood from reading the code, the path to `graphs.conf` seems hardcoded in `belchertown.py`
Consequence is :
- whatever I modify in `/etc/weewx/skin/Belchertown/graphs.conf` affect both skins
- whatever I modify in `/etc/weewx/skin/Belchertown_www/graphs.conf` never show up...

It could be an extremely minor issue if it affects only development setups like mine currently.
But it's maybe slightly less minor in case some like to have a local skin (only for home use) and a public skin (internet hosted) with different charts.
For example graphs about inside temp, battery status etc...may be considered for private use on local server, but not interesting to publish on internet.

**Comment by poblabs** [comment]
@bonjour81 Try that latest commit linked above of `belchertown.py` in the development branch. I think it fixes this. In my test I used the following with successful results. 

```
    [[Belchertown]]
        skin = Belchertown
        HTML_ROOT = /var/www/html/btownwx
        [[[Extras]]]
            belchertown_root_url = http://weewxlab/btownwx

    [[Belchertown_www]]
        skin = Belchertown_www
        HTML_ROOT = /var/www/html/belchertown_www
        [[[Extras]]]
            belchertown_root_url = http://weewxlab/belchertown_www
```

For some reason I was using the `config_dict` and not the `skin_dict` to tell me where the files live. Using the `skin_dict` should be pretty reliable for multiple Belchertown installations. 

Please test and re-open this if it's still an issue. Thanks!

**Comment by bonjour81** [comment]
Works perfectly !! thanks!

I can support for the wiki and prepare a short explanation if you like ?
