### ISSUE TITLE
Issue with Barometer reading in mbar in live

### ISSUE THREAD

**Issue by KasturiNagarWeather** [poblabs/weewx-belchertown#11]
Hi Pat,

The barometer reading in live display is wrong. When the page first loads it displays the right value for fraction of second then goes wrong. When it is displaying from archive record before going live it displays right.

My barometer reading is actually 1016 (verified in both console and MQTT spy). Raw pressure around 915. Altitude of my station 930m. The live display wrongly shows 1022.

Not sure why it goes wrong. Some altitude correction going wrong?

Station : http://bedi.co.in:15000/pc-aws/weather/belchertown/

Regards,
Praveen

**Comment by poblabs** [comment]
Could be. I think the skin is using altimeter's readings as opposed to barometer. There's [3 types of pressure readings available](https://github.com/weewx/weewx/wiki/Barometer,-pressure,-and-altimeter). I might have to add a variable for the station owner to select which one they want to show.

**Comment by 41south** [comment]
Good spotting - same issue here

**Comment by poblabs** [comment]
Closed. Feel free to update to the latest commit.
