### ISSUE TITLE
Page fails to load when no earthquake data available

### ISSUE THREAD

**Issue by bjcatlin** [poblabs/weewx-belchertown#111]
It appears that when no recent earthquake data is available, the jQuery line in index.html responsible for displaying earthquake info is failing.  The line results in this:

jQuery(".earthquake-time").html( moment.unix( No recent earthquake data available! ).format( 'LLL' ) );

Since that appears to be an invalid argument to moment.unix, I'm thinking we need to have something in there to capture text versus a date/time.

skin 1.0rc7

**Comment by poblabs** [comment]
Ah this is a result of the new translation effort I'm working on. Interesting catch! I'll see if I can patch this tonight.

**Comment by poblabs** [comment]
@bjcatlin Give this a try when you can. Updated skins/Belchertown/skin.conf, skins/Belchertown/index.html.tmpl and bin/user/belchertown.py.

**Comment by poblabs** [comment]
Closing, please re-open if this is still a problem

**Comment by bjcatlin** [comment]
This did not fix the problem.  I dove in deeper to the problem, and I think that I've come up with a good solution.  The version below adds quotes in several places, as moment seems to really have a problem without them.  I've also added an else statement so that when there is no earthquake data, the proper message is displayed.  NOTE: The quotes in the moment.unix line do need to be there, even though the line shouldn't be executed when there is no earthquake data, but it still dies without the quotes for some reason...

index.html.tmpl (around line 40):

            if ( moment.unix( "$earthquake_time" ).isValid() ) {
                // Check that the time is the time (number) and not the "no earthquake available" wording
                jQuery(".earthquake-time").html( moment.unix( "$earthquake_time" ).format( 'LLL' ) );
            } else {
                jQuery(".earthquake-time").html( "$earthquake_time" );
            }

**Comment by poblabs** [comment]
Thanks for doing more research on this! I'll take a look at it soon and run some tests. (working on another commit right now that I want to finish first).

**Comment by bjcatlin** [comment]
Thank you very much!  I've done one more modification to pull in the date format from skin.conf, so this might be better code:

index.html.tmpl (around line 40):

            if ( moment.unix( "$earthquake_time" ).isValid() ) {
                // Check that the time is the time (number) and not the "no earthquake available" wording
                jQuery(".earthquake-time").html( moment.unix( "$earthquake_time" ).format( "$obs.label.time_earthquake" ) );
            } else {
                jQuery(".earthquake-time").html( "$earthquake_time" );
            }

**Comment by poblabs** [comment]
Ok I think this one is fixed now for sure. Your updates tested well for me with and without earthquake data within the radius. Thanks for the research and updated code!
