### ISSUE TITLE
gapsize seems not working on some graphs ?

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#113]
Hello!
I played a bit with gapsize, because some of my sensors emits slower than weewx record interval.
For example, my rain sensor emits only when some rain worth to be reported (no rain, no emission).
My wind sensors emits information regarding battery voltage or solar panel every 10 minutes.

I set gapsize big enough on those graphs, expecting the gaps to be filled.
It does works on rain, but does not work on my electrical data, I was not able to figure out why.

Here is my graphs.conf if needed,but I reported the relevant section below.
(I renamed graphs.conf to txt so that github allows to upload)
[graphs.conf.txt](https://github.com/poblabs/weewx-belchertown/files/3141735/graphs.conf.txt)

gapsize works fine:
```
    [[chart3]]
        title = Précipitations
        type = line
        gapsize = 90000000   # 27h
        [[[rainRate]]]
            yAxis = 1
	    zindex = 2
            color = black
            lineWidth = 0
            type = line
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                    lineWidthPlus = 0
        [[[rainTotal]]]
            zindex = 1
            name = Total pluie
	    type = area
	    #aggregate_interval = 3600
	    #aggregate_type = sum
            color = "#14c2f5"
```

Gapsize seems not working:

```
    [[chart6]]
        title = Etat batteries
        type = spline
        gapsize = 90000000
        [[[WVbat]]]
            name = Batterie (ane.)
            yaxis_min = 0
            yaxis_max = 8
            #color = "#8d4653"
        [[[Vbat]]]
            name = Batterie (T/H)
            yaxis_min = 0
            yaxis_max = 8
            #color = "#8d4653"
        [[[WVsolar]]]
            yaxis_min = 0
            yaxis_max = 8
            #color = "#7ccf53"
            name = Volt. solaire (Ane.)
        [[[Vsolar]]]
            yaxis_min = 0
            yaxis_max = 8
            #color = "#7ccf53"
            name = Volt. solaire (T/H)
        [[[WIsolar]]]
            name = Courant solaire (Ane.)
	    zindex = 2
	    #color = "#8085e9"
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 300
            [[[[marker]]]]
                enabled = true
        [[[Isolar]]]
            name = Courant solaire (T/H)
	    #zindex = 2
	    #color = "#8085e9"
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 300

```

I added markers in WIsolar so the points are visible.

working:
![gapsize1](https://user-images.githubusercontent.com/24415431/57136115-08be4300-6dac-11e9-8cfd-76f645f59a1e.png)
not working (I would expect the small triangle markers to be connected).
![gapsize2](https://user-images.githubusercontent.com/24415431/57136118-0a880680-6dac-11e9-8af7-a203f4a823da.png)

**Comment by poblabs** [comment]
Gap size needs to match the interval between your points. Anything outside of that interval will not show.

**Comment by bonjour81** [comment]
maybe I misunderstood how gapsize works....but
for daily records (homepage graphs), I assume the aggregate internal is the weewx record interval.
If gapsize shall match this, how can I "hide" some gaps if a sensor miss one or a few records ?

infact, I'm not sure to understand what is gapsize job if it's same as agreggate interval ?

**Comment by poblabs** [comment]
Have a look at this ticket and it's history. It may help you understand? https://github.com/poblabs/weewx-belchertown/issues/48

This may also help you: https://api.highcharts.com/highstock/plotOptions.area.gapSize

The job of gapsize is to show a gap if the distance between two plots is greater than the gapsize. 

So if the archive interval, or aggregate interval is set to 5 minutes, we set gapsize to 5 minutes since we are expecting a plot every 5 minutes. If the distance between plots is more than 5 minutes, it shows the gap. The gap indicates data was lost. 

For example, you suffer a power outage and your station is down for 60 minutes. Then the charts will show the gap to indicate there was no data. Why was there no data? You had a power outage.

**Comment by poblabs** [comment]
Gap size is chart-wide and not for each sensor. So if you have sensors that report at odd intervals, then you will need to put them onto another chart so that gapsize will work.

**Comment by bonjour81** [comment]
Ahhh I think I understood..
it your _gapsize_ same as highcharts gapsize parameter ?

Infact I was thinking it was what is called "connectNulls" in highcharts.
if yes, sorry for my confustion !!

**Comment by poblabs** [comment]
Yep, it's the same as highcharts 😃

**Comment by bonjour81** [comment]
I have made a quick reading of #48 (that's a very long discussion! :-)  ). it seems both discussions are related.
I have to re-read more carefully :)

But ok, I think I misunderstood completely the role of gapsize.
What I was looking for is "connectNulls".  (https://api.highcharts.com/highcharts/plotOptions.series.connectNulls).

May I suggest to add connectNulls options available for graphs.conf ?

**Comment by michaelundwd** [comment]
@bonjour81
 
As the guy who raised #48, let me summarise the discussion for you.  What happened previously was that the timescale became non-linear if there was a gap in the readings.  Time tick-marks (horizontal axis) would disappear but the curve would be continuous.  The changes that Pat made overcame that and inserted a gap in the curve with all the time tick-marks present.

You are right that the two points are related - you want the gap bridged, still retaining the linear time-scale.

HTH

**Comment by poblabs** [comment]
I just pushed the update for connectNulls. It defaults to false, so you have to specify it to true. 

Here's my test. Top chart shows my gapSize. Bottom chart has the same gapSize, but connectNulls is enabled so the line is connected.

![image](https://user-images.githubusercontent.com/3484775/57467913-73123000-7251-11e9-9230-b261cdeee1ef.png)

To add connectNulls, use it at the top of the graph group like:

```
[day]
    title = Today
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000
    connectNulls = true
```

Please give it a test and close this if you're all set!

**Comment by olpayras** [comment]
That's a good idea, I tried it on last release 1.0rc8.4, also working if we put connectNull = true in global charts default. I have to do that because sometimes my weather station doesn't record anything for some hours or minutes on multiple sensors.

**Comment by poblabs** [comment]
Sorry, `connectNulls = true` won't be a global default. Thanks for #48 and the work done there, the Highcharts are now in line with weewx's default charts. 

The gap is intentional to show **missing data** such as your sensors not sending data. 

If you want to show a line between the missing points, `connectNulls` is now available!

Take a look at the Seasons skin and how it handles gaps. 

![image](https://user-images.githubusercontent.com/3484775/57570606-e773dd00-73d1-11e9-8c69-22061e25bbd1.png)

Compared to Highcharts with gapsize.

![image](https://user-images.githubusercontent.com/3484775/57570626-1c802f80-73d2-11e9-8b98-ff2f4ad4e216.png)

**Comment by poblabs** [comment]
Closing this since connectNulls is working pretty good for me during my tests!

**Comment by bonjour81** [comment]
Hi! Sorry, I have been a bit busy, but I made a few tests last hours, all is fine.
For example, my sensor sending battery voltage every 10min (so missing some weewx records) is now well displayed on charts. 
Thank you!
