### ISSUE TITLE
MQTT changing units

### ISSUE THREAD

**Issue by jmceara** [poblabs/weewx-belchertown#114]
Hi.
I just upgraded to latest dev version (1.0rc8) and it's great, i'm using new graphs, all working!
One small thing: MQTT is changing units. When report is generated (static page), all unit's are fine (i've changed in "Units", "Groups" to metrics, all items). But when MQTT connects and get first data, all data on middle panel switch to US units. My RAW data is in US format (from sensors and in database), but for display everything is set to metrics.

```
[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx
        skin = Belchertown
        enable = true
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_degree_day = degree_C_day
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_speed = meter_per_second
                group_speed2 = meter_per_second2
                group_temperature = degree_C
        [[[Extras]]]
            footer_copyright_text = jonis.com.br
            forecast_enabled = 1
            darksky_secret_key = XXXX
            darksky_units = ca
            earthquake_enabled = 0
            twitter_enabled = 0
            twitter_owner = PatOBrienPhoto
            site_title = Estação Meteorológica
            graphs_page_header = Gráficos - Clima
            reports_page_header = Relatórios
            records_page_header = Histórico
            about_page_header = Sobre esta estação
            googleAnalyticsId = UA-845106-16
            belchertown_root_url = http://weather.jonis.com.br
            mqtt_websockets_enabled = 1
            mqtt_websockets_host = XXX
            mqtt_websockets_topic = "weather/#"
            mqtt_websockets_port = 9001
            
            highcharts_graph_6 = humidityplot
            manifest_name = "Jonis Weather station"

```

What am I missing? or it's really a bug?

![weather1](https://user-images.githubusercontent.com/3300517/57156837-5db28700-6db5-11e9-8067-1c8c2ebba7ae.png)

**Comment by HoracioDos** [comment]
Hello!
How MQTT extension is sending data the broker? Is unit_system = METRIC or US?

**Comment by biltmorelaker** [comment]
Take a look at this GitHub repositiory: https://github.com/weewx/weewx/wiki/mqtt
Hopefully that will help you.

It has this example for adjusting MQTT units

> This configuration will use the METRIC unit system for all observations, whether the database is METRIC, METRICWX, or US:
> 
> [StdRESTful]
>     [[MQTT]]
>         unit_system = METRIC
> 
> This configuration will specialize the units of outTemp and the units, format, and name of inTemp:
> 
> [StdRESTful]
>     [[MQTT]]
>         unit_system = METRICWX
>         [[[inputs]]]
>             [[[[outTemp]]]]
>                 units = degree_F             # use F instead of C
>             [[[[inTemp]]]]
>                 units = degree_F             # use F instead of C
>                 format = %.2f                # use two decimal places of precision
>                 name = inside_temperature    # use label other than inTemp
>             [[[[windSpeed]]]]
>                 units = knot                 # use knots instead of meter_per_second
> 
> The observation outTemp will be converted to degrees F and uploaded as outTemp_F. The observation inTemp will be converted to degrees F and uploaded as inside_temperature with 2 decimal places of precision. Since the unit_system is METRICWX, other temperatures (if they exist) will use degrees C. For example extraTemp1 will be uploaded as extraTemp1_C. The observation windSpeed will be converted to knots and uploaded as windSpeed_knot.

**Comment by jmceara** [comment]
`unit_system = METRICWX`

This was working fine in latest stable version of belchertown.

**Comment by biltmorelaker** [comment]
Remember, the MQTT extension publishes WeeWX data to the broker. The Belchertown skin subscribes to the broker and reads what the broker sends out.

**Comment by jmceara** [comment]
No, there's something wrong.
I've changed my MQTT settings to just 'METRIC' and problem persist.
This is the output of my MQTT service (subscrible data):


`{"windGust_kph": "2.46930118422", "heatindex_C": "37.0185106199", "dewpoint_C": "22.3349798914", "windSpeed_kph": "0.965937813264", "outHumidity": "54.6", "humidex_C": "42.3335766808", "UV": "0.69", "rainRate_cm_per_hour": "0.0", "barometer_mbar": "1011.46286275", "dateTime": "1556909458.0", "windDir": "0.0", "VIS": "386.0", "altimeter_mbar": "1015.34786806", "pressure_mbar": "951.390402722", "windchill_C": "32.7", "extraTemp1_C": "54.5", "appTemp_C": "37.3922009395", "outTemp_C": "32.7", "usUnits": "16.0", "cloudbase_meter": "1840.42056779"}`

As you can see, it's correct in metric......but skin still showing in US (again, only for MQTT! not for static generated data).....and only for middle box, in the center of page.....big temperature number still in "C (metric)".

**Comment by jmceara** [comment]
Another thing: values looks fine (in metric)! Just unit descript after value looks wrong (in US, in this case).

**Comment by HoracioDos** [comment]
That's weird! Pat made a change in station observations recently. Perhaps there is a bug in there. Did you change your locale in weewx.conf and see what happens? 
belchertown_locale = "pt_BR.UTF-8"

You can try more observations in weewx.conf. Check first if you have them available in your Data Base. 
station_observations = "barometer", "visibility", "cloudbase", "dew point", "out Humidity", "rainWithRainRate", "UV", "radiation"

**Comment by HoracioDos** [comment]
Hi.
Locale should not matter but that was the only difference I found if you have everything else configured correctly. I have this setting different from yours.
mqtt_websockets_topic = weather/loop

**Comment by biltmorelaker** [comment]
Hmm. As @HoracioDos says, Pat recently changed the way the station observation "cell" is populated to give users the ability to change the observations displayed. I know that he specifically worked on the formatting. It could well be something there is causing the issue that @jmceara  is seeing. But @HoracioDos isn't seeing the same behavior?

**Comment by HoracioDos** [comment]
I had not realized that websockets config was not enabled!! Palm face!!. If it were a snake I would be dead right now. I can confirm the bug! But the most interesting part is that everything is fine except for barometer and rain. I set them in hPA, mm and mm/h and now it shows mbar, cm and cm/h. I can see both labels when I refresh the page. I have none of this settings in weewx.conf or skin.conf

**Comment by 41south** [comment]
I wonder if this is related to an issue I had way back with metric units and MQTT. 

[https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099](url)

**Comment by poblabs** [comment]
Don't subscribe to `#`. This is bad practice. Change this so it's `mqtt_websockets_topic = "weather/loop"`

**Comment by poblabs** [comment]
1.0rc8 brings a change that allows you to modify the station observations section. Which is the section in question. This section gets its labels from weewx, and the weewx_data.json. Yours is at http://weather.jonis.com.br/json/weewx_data.json and you can see your `station_observations` --> `unit_labels` shows barometer as inHg. 

Have you set everything to metric in skin.conf and weewx.conf? Specifically within weewx.conf under `[StdReport]` --> `[[Defaults]]` --> `[[[Units]]]` --> `[[[[Groups]]]]` ?

**Comment by HoracioDos** [comment]
Hello Pat.
I defined [[[[Groups]]]] under [[Defaults]] and under [[Belchertown]]. They are the same in both sections.

```
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter    # Options are 'foot' or 'meter'
                group_degree_day = degree_C_day    # Options are 'degree_F_day' or 'degree_C_d$
                group_direction = degree_compass
                group_moisture = centibar
                group_percent = percent
                group_pressure = hPa    # Options are 'inHg', 'mmHg', 'mbar', or 'h$
                group_radiation = watt_per_meter_squared
                group_rain = mm    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = mm_per_hour    # Options are 'inch_per_hour', 'cm_per_hour$
                group_speed = km_per_hour    # Options are 'mile_per_hour', 'km_per_hour$
                group_speed2 = km_per_hour2    # Options are 'mile_per_hour2', 'km_per_hou$
                group_temperature = degree_C    # Options are 'degree_F' or 'degree_C'
                group_uv = uv_index
                group_volt = volt
                group_distance = km
```

**Comment by poblabs** [comment]
@HoracioDos Is yours broken too? My initial reply was for @jmceara 

I've tested this change on a few different locales with metric and my testing was successful.

**Comment by HoracioDos** [comment]
When I updated to Rc8 today I didn't check live updates and everything seemed to be fine. I don't feel happy giving bad news! Do you want me to test something?

**Comment by poblabs** [comment]
@HoracioDos Nope if you are working then we are good! 😄 

@jmceara See my previous reply to make sure your Metric settings are all good! Let me know

**Comment by HoracioDos** [comment]
Look at this. is it ok?
    "station_observations": {
```
        "current": {"barometer": "1053,0 hPa", "visibility": "10,99 km", "cloudbase": "405 metros", "dewpoint": "-3,6 \u00b0C", "outHumidity": "80%", "rainWithRainRate": "", "UV": "0,0", "radiation": "0 W/m\u00b2"},
        "rounding": {"barometer": "1", "visibility": "", "cloudbase": "0", "dewpoint": "1", "outHumidity": "0", "dayRain": "2", "rainRate": "2", "rainWithRainRate": "", "UV": "1", "radiation": "0"},
        "unit_labels": {"barometer": " mbar", "visibility": "km", "cloudbase": " metros", "dewpoint": " \u00b0C", "outHumidity": "%", "dayRain": " cm", "rainRate": " cm/hr", "rainWithRainRate": "", "UV": "", "radiation": " W/m\u00b2"},
        "trend": {"pressure": "up"}
```

**Comment by poblabs** [comment]
Hmm, not it is not ok. I quickly see you are set to use hPa, but the label is mbar. I will look at this

**Comment by jmceara** [comment]
> 1.0rc8 brings a change that allows you to modify the station observations section. Which is the section in question. This section gets its labels from weewx, and puts them inside weewx_data.json so they can be used in the skin. Yours is at http://weather.jonis.com.br/json/weewx_data.json and you can see your `station_observations` --> `unit_labels` shows barometer as inHg, rain as inches, etc. So you haven't set a skin to metric somewhere.
> 
> Your mqtt is fine. It's your skin settings, or weewx global settings.
> 
> Have you set everything to metric in weewx.conf? Specifically within weewx.conf under `[StdReport]` --> `[[Defaults]]` --> `[[[Units]]]` --> `[[[[Groups]]]]` ?

Yep, all set under [StdReport]!!


```
[[Defaults]]

        [[[Units]]]

            # The following section sets what unit to use for each unit group.
            # NB: The unit is always in the singular. I.e., 'mile_per_hour',
            # NOT 'miles_per_hour'
            [[[[Groups]]]]

                group_altitude = meter    # Options are 'foot' or 'meter'
                group_degree_day = degree_C_day    # Options are 'degree_F_day' or 'degree_C_day'
                group_pressure = mbar    # Options are 'inHg', 'mmHg', 'mbar', or 'hPa'
                group_rain = mm    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = mm_per_hour    # Options are 'inch_per_hour', 'cm_per_hour', or 'mm_per_hour'
                group_speed = km_per_hour    # Options are 'mile_per_hour', 'km_per_hour', 'knot', or 'meter_per_second'
                group_speed2 = km_per_hour2    # Options are 'mile_per_hour2', 'km_per_hour2', 'knot2', or 'meter_per_second2'
                group_temperature = degree_C    # Options are 'degree_F' or 'degree_C'

```

**Comment by poblabs** [comment]
I am able to replicate the bug. Let me work on it

**Comment by poblabs** [comment]
@jmceara @HoracioDos I just pushed an update. Please replace your `bin/user/belchertown.py` file [with this one](https://raw.githubusercontent.com/poblabs/weewx-belchertown/9f612b3fcf0f19e6da52a701e4095e242f9d7725/bin/user/belchertown.py), restart weewx and run `sudo wee_reports` to force a page generation. 

Let me know if its fixed for you (it is for me)

**Comment by poblabs** [comment]
Just pushed another update, so please [replace belchertown.py with this one](https://raw.githubusercontent.com/poblabs/weewx-belchertown/development/bin/user/belchertown.py) and restart weewx.

**Comment by HoracioDos** [comment]
Hello Pat. I've noticed this morning. I pulled everything. It works as it should with websockets enabled.
Now I'm fixing new titles for "All" button in graphs.
Thanks!

**Comment by jmceara** [comment]
Everything working as expected now! Tks! :)
