### ISSUE TITLE
Some comments on new graphs tags.

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#115]
I found that highcharts_homepage_graphgroup = "day" doesn't disable homepage graphs when you click "ALL" button. It shows both (homepage and day graphs) from graphs.conf in graphs page.
So I removed homepage section from graphs.conf and now it looks like to your site. Is it the correct behaviour? I think that homepage graphs should be disabled if they are set to: "day", "week", "month" or "year".
Could you please remove uppercase in every title word?
Thanks

**Comment by poblabs** [comment]
If you're on the Graphs page and you're on the All page, it will show you everything that is inside your graphs.conf. If you look at mine at https://belchertownweather.com/graphs/?graph=all and scroll all the way to the bottom you can see my About page graph listed there too. 

So do you mean that if you have `highcharts_homepage_graphgroup = "day"`, it is showing you the day group twice? I do not experience that on my site (see link above).

I want to be able to show all graphs on All page because on homepage graphs you could have "Last 25 Hours", but on Day graphs you could have "Since Midnight". So they could in fact be different graphs. 

Yes, I am going to update the titles a little more in a future commit. I will make the homepage graphs use the title from that graph group too. That way all graphs and settings are coming from graphs.conf.

**Comment by HoracioDos** [comment]
Hello Pat.
Thanks for making it more clear. I think I understand better the concept behind "all" button.
> So do you mean that if you have highcharts_homepage_graphgroup = "day", it is showing you the day group twice? I do not experience that on my site (see link above).
My [homepage] graphs were same as [day] graphs. I had both sections in graphs.conf  As both graphs were showed, they looked like duplicated and one of them should be hidden if I set highcharts_homepage_graphgroup = "day"
Just to be clear. Do you have  homepage and day sections in graphs.conf and only one of them is showed?

**Comment by poblabs** [comment]
My graphs.conf only has 1 [day] section and no [homepage]. Then I set `highcharts_homepage_graphgroup = day`, and both Day is on my home page and Day is also on the Graphs page. Does this help?

**Comment by HoracioDos** [comment]
Yeap. Same as mine. Thanks!

**Comment by poblabs** [comment]
Ok cool, close this if you're all set!

**Comment by poblabs** [comment]
@HoracioDos the uppercase title case is removed now

**Comment by HoracioDos** [comment]
Very nice new graphs features! I'm already trying yesterday, last_week, last_month and last_year

**Comment by HoracioDos** [comment]
Something for Wiki.
If you add a new graph with a time_length like "last_year" and there are no records for that period you'll get an error in Belchertown generator. Remove that section from graphs.conf to avoid messages.

```
May 06 09:06:48 PiWeewx weewx[32500]: reportengine: Caught unrecoverable exception in generator 'user.belchertown.JsonGenerator'
May 06 09:06:48 PiWeewx weewx[32500]:         ****  None
May 06 09:06:48 PiWeewx weewx[32500]:         ****  Traceback (most recent call last):
May 06 09:06:48 PiWeewx weewx[32500]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
May 06 09:06:48 PiWeewx weewx[32500]:         ****      obj.start()
May 06 09:06:48 PiWeewx weewx[32500]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
May 06 09:06:48 PiWeewx weewx[32500]:         ****      self.run()
May 06 09:06:48 PiWeewx weewx[32500]:         ****    File "/usr/share/weewx/user/belchertown.py", line 1035, in run
May 06 09:06:48 PiWeewx weewx[32500]:         ****      output[chart_group][plotname]["series"][line_name]["data"] = self._getObservationData(observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length)
May 06 09:06:48 PiWeewx weewx[32500]:         ****    File "/usr/share/weewx/user/belchertown.py", line 1078, in _getObservationData
May 06 09:06:48 PiWeewx weewx[32500]:         ****      windSpeedUnitLabel = self.skin_dict["Units"]["Labels"][windSpeedUnit]
May 06 09:06:48 PiWeewx weewx[32500]:         ****    File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
May 06 09:06:48 PiWeewx weewx[32500]:         ****      val = dict.__getitem__(self, key)
May 06 09:06:48 PiWeewx weewx[32500]:         ****  KeyError: None
May 06 09:06:48 PiWeewx weewx[32500]:         ****  Generator terminated
```

**Comment by biltmorelaker** [comment]
Thanks for catching that. Maybe Pat can make a change to catch that condition and just display a blank graph, otherwise the warning will be added to the wiki.

**Comment by poblabs** [comment]
Good catch! Let me see how to catch that. I've also thought about changing that from "last_year" to "history_year" then a new option for "ago" so that you can do last year, 2 years ago, etc. Same thing with yesterday, last week and last month. The option to specify "ago" so you could do 2 months ago instead of just last month. 

I'll see if I can make both of those updates later today

**Comment by poblabs** [comment]
What do you guys think about changing skin.conf `graph_page_graphgroup_buttons` option and making it a graphs.conf option `show_on_graphs_page = true` for each graph group? That way the its easier to control which graphs appear and one place to control it. 

I keep finding myself adding and removing graphs and having to also change my skin options. Kind of a hassle already :)

**Comment by biltmorelaker** [comment]
I like that! That way you won’t need to change skin.conf (and risk upgrade override) or change weewx.conf and require a weewx restart to make those changes.

**Comment by poblabs** [comment]
Ok cool, I'll work on that. 

I'm not able to replicate the problem here though. I don't have data in my database for 5 years ago, but when I do `time_length = year_ago` and `time_ago = 5` I still get empty graphs. 

Every so often I am getting this error but haven't traced it back. It is different than the other one reported. So still looking into it

**Comment by HoracioDos** [comment]
It sounds all good! Skin.conf is much cleaner now and It will be even more I guess. About "ago" periods, all these changes totally beyond of what I could ever expected. Adding and removing options is a very small trouble compared to all the features you are adding, but I understand you completely, when you go back and forth while coding and testing new ideas, It takes a lot of energy.
I can upload my weewx database to the cloud so you can test with this data set.

**Comment by poblabs** [comment]
I am making more changes now which will allow you to have graphs for a specific day, month or year. So even more `time_length` options and supporting options to make it work. Hope to commit soon for testing. 

Below is a screenshot of a `year_specific` option for 2016 graphs. 😃 

Zip your database and drag & drop it here and I will use it to test with. Also send your graphs.conf option which is failing. That will help, Thanks!


![image](https://user-images.githubusercontent.com/3484775/57229229-8d46d680-6fe3-11e9-8427-1672bc75cb22.png)

**Comment by HoracioDos** [comment]
Hello! 
That's cool. As far as I can see, Highcharts also allows heatmaps. Are them available in Belchertown?
I would be very interesting to create a heatmap for a specific period.
These are the files. Let me know if you need something else.
[wee.zip](https://github.com/poblabs/weewx-belchertown/files/3148458/wee.zip)
[last_year_graphs.conf.txt](https://github.com/poblabs/weewx-belchertown/files/3148466/last_year_graphs.conf.txt)
Thanks!

**Comment by poblabs** [comment]
Heatmaps aren't supported right now because the data so far has been charted as linear. How do you plan on using it?

**Comment by HoracioDos** [comment]
Ok I understand. We can make linear graphs only. I had in mind something like you have already seen here: http://www.payrastre.fr/weewx/belchertown/reports/
I've made my own text reports and I used them as data input for GNUplot to plot heatmaps. Then I wanted to code a simple user service in python to do a system call for GnuPlot.
https://github.com/poblabs/weewx-belchertown/issues/101#issuecomment-486202527
I think heatmaps are a whole different ballgame. Perhaps next time.

**Comment by poblabs** [comment]
Linear graphs like area, spline, line, scatter and the windrose. Heatmap is interesting but I don't know much about it yet. Will need to research for maybe next time

**Comment by poblabs** [comment]
Pushed more ways to make historical graphs. Also tried to document it quickly in the wiki. It could use more content but I didn't have much time. https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#to-graph-days-ago

**Comment by poblabs** [comment]
@HoracioDos I am able to replicate your problem even with the new graphs code below. It has to do with windRose chart. I will need a little more time to debug it. 

```
[last_year]
    # Chart Timespan Defaults
    title = Last Year
    button_text = Last Year
    type = spline
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    time_length = year_ago
    time_ago = 1
```

**Comment by HoracioDos** [comment]
I'm glad that you found it but you don't need to hurry. I'll buy you more coffee.

**Comment by poblabs** [comment]
@HoracioDos Just pushed a fix I think. The wind rose was the problem, so I am checking to see if it's empty and if so just show an empty wind rose. It is working for me now with your test database you sent me. Can you try it?

For the wind average error. I'm not sure about that one. The tag `$hour.windspeed.avg.raw` is a built in weewx tag and not one of mine. So maybe there is problem that if there is no wind, this tag is unavailable.

**Comment by HoracioDos** [comment]
Tom answered me an hour go. Correct tag is $hour.windSpeed.avg.raw with S capital letter. Palm face!! I don't why this report doesn't show errors everytime I delete this text report and let weewx to generate it again. Any way, I'll sync asap and I'll keep you informed.

**Comment by HoracioDos** [comment]
Hello Pat
I synched a few minutes ago. Yesterday fails now. I'll be absent for a few hours. If you make a new fix I'll test it later.
```
May 07 13:17:04 PiWeewx weewx[30140]: reportengine: Caught unrecoverable exception in generator 'user.belchertown.JsonGenerator'
May 07 13:17:04 PiWeewx weewx[30140]:         ****  invalid literal for int() with base 10: 'yesterday'
May 07 13:17:04 PiWeewx weewx[30140]:         ****  Traceback (most recent call last):
May 07 13:17:04 PiWeewx weewx[30140]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
May 07 13:17:04 PiWeewx weewx[30140]:         ****      obj.start()
May 07 13:17:04 PiWeewx weewx[30140]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
May 07 13:17:04 PiWeewx weewx[30140]:         ****      self.run()
May 07 13:17:04 PiWeewx weewx[30140]:         ****    File "/usr/share/weewx/user/belchertown.py", line 970, in run
May 07 13:17:04 PiWeewx weewx[30140]:         ****      (minstamp, maxstamp, timeinc) = weeplot.utilities.scaletime(plotgen_ts - int(time_length), plotgen_ts)
May 07 13:17:04 PiWeewx weewx[30140]:         ****  ValueError: invalid literal for int() with base 10: 'yesterday'
May 07 13:17:04 PiWeewx weewx[30140]:         ****  Generator terminated
```

**Comment by poblabs** [comment]
`yesterday`, `last_week`, `last_month` and `last_year` were removed in favor of `days_ago` and `time_ago`. So for yesterday you would use this config:

```
[yesterday]
    # Chart Timespan Defaults
    title = Yesterday
    button_text = Yesterday
    time_length = days_ago
    time_ago = 1
    gapsize = 300000

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
```

notice the `time_length = days_ago`, then you specify how many days ago with `time_ago = 1`

This is more flexible than `yesterday` because now you can do days_ago with time_ago 2, 3, 10, 30 for that single day chart. 

There's also `weeks_ago`, `months_ago` and `years_ago`. Same thing applies where you use `time_ago` to specify how far back you want to graph.

**Comment by HoracioDos** [comment]
Ok. My mistake. I'll try them later

**Comment by poblabs** [comment]
Sounds good. I also made a change just now which removed `graph_page_graphgroup_buttons` from skin.conf, and adds new graphs.conf option `show_button` to show the graph button on the Graphs page. Here is an example:

```
[homepage]
    # Chart Timespan Defaults
    title = Today
    show_button = true
    button_text = "Homepage"
```

**Comment by 41south** [comment]
Hi Pat

Does this now open up the ability to add a set of graphs such as AQI that
have their own page and button on the graphs pages? So one could have
Today-Week-Month-Year-Current AQI etc

Cheers
Colin

**Comment by poblabs** [comment]
If I understand correctly, you could do that with a new chart group. Then show the chart group using `show_button`. For example:

```
[current_aqi]
    show_button = true
    button_text = "Current AQI"
    time_length = today
    gapsize = 300000
    title = "Current AQI"

    [[chart1_for_current_aqi_or_something]]
        ....

    [[chart2_for_current_aqi_or_something]]
        ....
```

So this will show the "Current AQI" chart group button next to the Today-Week-Month-Year buttons. 

You can also rename the buttons. So if you don't like "Today" you can add or change `button_text = Day` and it'll change the button text. 

Does this help?

**Comment by 41south** [comment]
Sounds perfect to me and certainly opens up a whole new world of charting
possibilities :)

Thanks!
Colin

**Comment by HoracioDos** [comment]
Woohoo! Everything is fine. What kind of evil graph will I do? I don't know yet!

**Comment by poblabs** [comment]
Looks like everything is working now! Closing again. You can re-open if you find any bugs or issues.
