### ISSUE TITLE
Temp and Humidity issue --- Maybe

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#116]
When adding Humidity to the Temperature Graph, the scaling for the y axis does not scale properly.  My setting for the graph are as follows:

[[chart1]]
        title = Temperature and Humidity
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple
        [[[outHumidity]]]
            yAxis = 1
            yaxis_max = 100
            color = "#91e8e1"

Maybe I have something incorrect or It does not scale as I think it should.
![Temp and Humdity graph](https://user-images.githubusercontent.com/48191231/57269050-e8181680-7053-11e9-9941-71ff3e78a17b.png)

**Comment by poblabs** [comment]
Is your reference to scaling due to the y axis showing 120% for the max? As oppose to being the max for the specific observation? I'm seeing that too on my test site. I'm not sure why it's doing it. If you remove all the other observations, then the scaling works - so I wonder if this is a limitation with Highcharts and all the other line type data? This could be a little outside of my knowledge of highcharts and how many line series you can have at once across the y axis? Not sure.  

I was able to get it to work by changing humidity to an area type chart. See config below and screenshot. 

```
[test]
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.

    [[chart1]]
        title = Temperature and Humidity
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple
        [[[outHumidity]]]
            type = area
            yAxis = 1
            yaxis_max = 100
            color = "#91e8e1"
```

![image](https://user-images.githubusercontent.com/3484775/57324139-476a3b00-70d5-11e9-9c31-d4e553af7081.png)

**Comment by poblabs** [comment]
I guess I'm not too sure what's going on. If you take this chart below as an example, it's working with 2 y axis and they are all line charts. Difference is the number of observations. 3 on mine vs. 5 on yours. 

```
    [[solarRadGraph]]
        title = Solar Radiation and  UV Index
        [[[radiation]]]
           name = Solar Radiation
           zIndex = 1
           color = "#ffc83f"
        [[[maxSolarRad]]]
            name = Theoretical Max Solar Radiation
            color = "#f7f2b4"
            y_label = "W/m2"
        [[[UV]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 14
            color = "#90ed7d"
            y_label = "UV"
            name = UV Index
            zIndex = 2
```

![image](https://user-images.githubusercontent.com/3484775/57324991-10952480-70d7-11e9-8abc-45a0a0dceb5c.png)

Difference is the number of observations. 3 on mine vs. 5 on yours. 

So let's keep adding. 

```
    [[solarRadGraph]]
        title = Solar Radiation and  UV Index
        [[[radiation]]]
           name = Solar Radiation
           zIndex = 1
           color = "#ffc83f"
        [[[maxSolarRad]]]
            name = Theoretical Max Solar Radiation
            color = "#f7f2b4"
            y_label = "W/m2"
        [[[UV]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 14
            color = "#90ed7d"
            y_label = "UV"
            name = UV Index
            zIndex = 2
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
        [[[outHumidity]]]
```

![image](https://user-images.githubusercontent.com/3484775/57325143-610c8200-70d7-11e9-8410-3734d6d7dbba.png)

You'll notice my y axis label is messed up (which is a known problem with my generator - it's best to keep the same units on the same axis), but the scaling remains the same. 

I guess I'm a bit lost on this one. I'll keep thinking about it

**Comment by poblabs** [comment]
Ah, think I just stumbled onto it. Define the `yaxis_min = 0` and it seems to have cleared it up. 

```
[test]
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.

    [[chart1]]
        title = Temperature and Humidity
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple
        [[[outHumidity]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 100
            color = "#91e8e1"
```

![image](https://user-images.githubusercontent.com/3484775/57325408-f0b23080-70d7-11e9-9c72-604baf1ae58a.png)

**Comment by Stormtracker017** [comment]
The actual coding works. I restarted the config several times last night and the graph would update but the humidity scale was wrong.  So this evening I cleared the cache, now the scale reads correctly.  Sometimes that cache gets me.

**Comment by poblabs** [comment]
Ok cool. Since I had experienced it myself without a cache issue I thought it might have been the yaxis_min needing to be there. Anyways if you're all set I'll close this! Glad it's resolved.

**Comment by bdwilson** [comment]
I'm still seeing this.. perhaps something wrong on my end, but I've set yaxis_min to 0.

https://bubba.d.pr/KFmCsR

    [[chart1]]
        title = Outdoor
        [[[outTemp]]]
            zIndex = 1
            name = "Temperature"
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple
        [[[outHumidity]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 100
