### ISSUE TITLE
 it misses the time display and forecasts

### ISSUE THREAD

**Issue by salinois** [poblabs/weewx-belchertown#118]
hi every body,

 since some days , I had this with skin "Belchertown"; it is ok with skin "Seasons".
it misses the time display and forecasts and graphs on home page !!!
![Capture](https://user-images.githubusercontent.com/50419294/57393800-2b919280-71c4-11e9-8190-f4bbaedab321.JPG)

an idea, the logs are corrects for Belchertown

Patrick

my website => http://jurassikpat.ddns.net/weewx/belchertown

**Comment by poblabs** [comment]
Hi Patrick 

Your update time is missing and your forecast is missing and your Earthquake is missing. 

Are there any errors in your syslog? 

Are there any permission problems with saving the files to your website folder?

Did you make changes to the skin?

**Comment by salinois** [comment]
logs are ok:
May  8 19:15:40 raspberrypi weewx[20129]: copygenerator: copied 0 files to /var/www/html/weewx/belchertown
May  8 19:16:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:16:00 CEST (1557335760) to database 'weewx.sdb'
May  8 19:16:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:16:00 CEST (1557335760) to daily summary in 'weewx.sdb'
May  8 19:16:21 raspberrypi weewx[20129]: cheetahgenerator: Generated 14 files for report Belchertown in 3.74 seconds
May  8 19:16:21 raspberrypi weewx[20129]: copygenerator: copied 1 files to /var/www/html/weewx/belchertown
May  8 19:16:39 raspberrypi weewx[20129]: cheetahgenerator: Generated 4 files for report Highcharts_Belchertown in 18.26 seconds
May  8 19:16:39 raspberrypi weewx[20129]: copygenerator: copied 0 files to /var/www/html/weewx/belchertown
May  8 19:17:01 raspberrypi CRON[22057]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  8 19:17:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:17:00 CEST (1557335820) to database 'weewx.sdb'
May  8 19:17:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:17:00 CEST (1557335820) to daily summary in 'weewx.sdb'
May  8 19:17:21 raspberrypi weewx[20129]: cheetahgenerator: Generated 14 files for report Belchertown in 3.67 seconds
May  8 19:17:21 raspberrypi weewx[20129]: copygenerator: copied 1 files to /var/www/html/weewx/belchertown
May  8 19:17:39 raspberrypi weewx[20129]: cheetahgenerator: Generated 4 files for report Highcharts_Belchertown in 18.75 seconds
May  8 19:17:39 raspberrypi weewx[20129]: copygenerator: copied 0 files to /var/www/html/weewx/belchertown
May  8 19:18:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:18:00 CEST (1557335880) to database 'weewx.sdb'
May  8 19:18:17 raspberrypi weewx[20129]: manager: Added record 2019-05-08 19:18:00 CEST (1557335880) to daily summary in 'weewx.sdb'

I did not change on the skin !!!
do you can acces on my website ?

patrick

**Comment by poblabs** [comment]
I can access your site, but since your `belchertown_root_url` is a 192.168.0.211 address I cannot access that so it doesn't load everything for me. 

I think I see what's wrong. It is a bug that I fixed just last week. 

You have no earthquakes near you, which makes your website stop working. 

Change this in your skin.conf. 

`earthquake_maxradiuskm = 1000` to make it a larger kilometer radius. 

Then run `sudo wee_reports` and see if it helps?

**Comment by salinois** [comment]
I modified the weewx.conf, it is better ?

patrick

**Comment by poblabs** [comment]
Yes I can view your site now. But the earthquake problem is still there. You can change your option `earthquake_maxradiuskm = 1000` to make it a larger kilometer radius and restart weewx and see what happens.

**Comment by salinois** [comment]
good, but me now, I can't access by local address !!! ( pb apache maybe )

see my conf in weewx.conf, I don't use skin.conf

[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Belchertown
        [[[Extras]]]
           belchertown_root_url = "http://jurassikpat.ddns.net/weewx/belchertow$
           logo_image = "http://jurassikpat.ddns.net/weewx/belchertown/images/i$
           footer_copyright_text = BelchertownWeather.com
           forecast_enabled = 1
           darksky_secret_key = "efda1220fc2427b996f6fe34a1b350d4"
           darksky_units = "auto"
           darksky_lang = "fr"
           forecast_stale = 3540
           forecast_alert_enabled = 1
           earthquake_enabled = 1
           earthquake_maxradiuskm = 1000
    [[Highcharts_Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Highcharts_Belchertown

but before this works very good !!!

patrick

**Comment by poblabs** [comment]
You can put it back to local access.

Did you change earthquake setting I mentioned?

**Comment by salinois** [comment]
yes , I changed earthquake but inside weewx.conf, I can do it, yes ?
patrick

**Comment by poblabs** [comment]
yes change your earthquake_maxradiuskm = 1000 to 2000 or something

**Comment by poblabs** [comment]
It is working now! 

The permanent fix will be in version 1.0. 

You can change back to your original `belchertown_root_url`


![image](https://user-images.githubusercontent.com/3484775/57414138-f20d5700-71c4-11e9-9df4-732bebb91dda.png)
