### ISSUE TITLE
'upgrading' from development releases 

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#121]
Is there anything written about upgrading from the previous development releases to the newer ones, or eventually the 1.0 release?

**Comment by poblabs** [comment]
If you are on development release now you can just copy the files manually
to their place and restart weewx to get the new features.

Nothing documented officially for development to development upgrade.

The 1.0 release will be the same method of you're already on development.
If not then you'll follow the upgrade wiki guide to remove the skin and
install clean.

**Comment by poblabs** [comment]
Closing this for now. If you're still stuck feel free to re-open

**Comment by olpayras** [comment]
Also you can download the .zip file from github and use  wee_extension --install <filename.zip> where filename is the file you downloaded previoulsy. But be carefull, that will overwrite all skin files. So if you have customised some files you need to backup them first.

**Comment by slvrscoobie** [comment]
ok, so I just did this from an older development release to todays and now a lot of stuff is broken. 
I deleted the skin directly, used the install method - downloaded the development release zip and installed. copied over the older skin and graphs .conf and now its a mess lol 
![Screen Shot 2019-05-28 at 5 34 45 PM](https://user-images.githubusercontent.com/13274298/58514059-e7fcc980-816e-11e9-9634-a1625c37e01b.png)

**Comment by slvrscoobie** [comment]
May 28 17:40:23 raspberrypi weewx[4945]: reportengine: Running report 'Belchertown'
May 28 17:40:23 raspberrypi weewx[4945]: reportengine: Found configuration file /etc/weewx/skins/Belchertown/skin.conf for report 'Belchertown'
May 28 17:40:23 raspberrypi weewx[4945]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown.getData']
May 28 17:40:23 raspberrypi weewx[4945]: manager: Daily summary version is 2.0
May 28 17:40:23 raspberrypi weewx[4945]: reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
May 28 17:40:23 raspberrypi weewx[4945]:         ****  'station_observations'
May 28 17:40:23 raspberrypi weewx[4945]:         ****  Traceback (most recent call last):
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
May 28 17:40:23 raspberrypi weewx[4945]:         ****      obj.start()
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
May 28 17:40:23 raspberrypi weewx[4945]:         ****      self.run()
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
May 28 17:40:23 raspberrypi weewx[4945]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
May 28 17:40:23 raspberrypi weewx[4945]:         ****      ngen += self.generate(section[subsection], gen_ts)
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
May 28 17:40:23 raspberrypi weewx[4945]:         ****      ngen += self.generate(section[subsection], gen_ts)
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
May 28 17:40:23 raspberrypi weewx[4945]:         ****      default_binding)
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
May 28 17:40:23 raspberrypi weewx[4945]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/share/weewx/user/belchertown.py", line 652, in get_extension_list
May 28 17:40:23 raspberrypi weewx[4945]:         ****      station_observations = self.generator.skin_dict['Extras']['station_observations']
May 28 17:40:23 raspberrypi weewx[4945]:         ****    File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
May 28 17:40:23 raspberrypi weewx[4945]:         ****      val = dict.__getitem__(self, key)
May 28 17:40:23 raspberrypi weewx[4945]:         ****  KeyError: 'station_observations'
May 28 17:40:23 raspberrypi weewx[4945]:         ****  Generator terminated
May 28 17:40:23 raspberrypi weewx[4945]: copygenerator: copied 2 files to /var/www/html/weewx/belchertown
May 28 17:40:23 raspberrypi weewx[4945]: manager: Daily summary version is 2.0
May 28 17:40:26 raspberrypi weewx[4945]: sdr: MainThread: lines=[]

**Comment by HoracioDos** [comment]
Hello @slvrscoobie
Upgrading from development takes a lot of effort from Pat to support it. Did you follow these instructions?
Please execute these steps and make a backup first. Then I can help you from a fresh start.

**Comment by poblabs** [comment]
It looks like you didn't update the bin/user/belchertown.py file. Can you confirm that it is the latest? Also don't forget to restart weewx since belchertown.py is only read upon weewx startup.

**Comment by slvrscoobie** [comment]
> It looks like you didn't update the bin/user/belchertown.py file. Can you confirm that it is the latest? Also don't forget to restart weewx since belchertown.py is only read upon weewx startup.
> 
> Also looks like your skin.conf doesn't have the station_observation settings. So that file may have been missed on your update too. Looks like a bad install to me. I'd try it again with those instructions just to be sure. 
> 
> skin.conf is also only read upon a weewx startup so it's critical to restart weewx after you install the skin. 
I did the 'install -- weewx extension' however i didnt uninstall it that way, i just deleted the old skin folder so maybe that screwed up belchertown.py
and also, i copied the old Skin.conf over as a backup, I guess I need to use the new one, and then manually copy the edits over..?

**Comment by slvrscoobie** [comment]
reinstalled from 0, added the edits by hand, back in business.

**Comment by poblabs** [comment]
@slvrscoobie Perfect! The trick with the development version is that a lot of things can change in 1 commit, so sometimes its best to do exactly what you just did. Have a backup of your settings. Delete everything and start over again. Apply your settings and restart weewx.
