### ISSUE TITLE
Current Station Obs Question

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#122]
Just want to know  how to remove the comma when 1000 is display.  I have "Auto" selected for locale in the skin config. Also where do you change the label radiation to solar?
![current obs](https://user-images.githubusercontent.com/48191231/57577207-22145e80-7440-11e9-9b27-6376989efbe5.png)

**Comment by HoracioDos** [comment]
Look for radiation [[Defaults]] [[[Labels]]] in weewx.conf and change it to solar. 
`radiation = Solar`
In [[Defaults]] [[[[StringFormats]]]] you can find how watt_per_meter_squared  is formated.
`watt_per_meter_squared = %.0f`
I'm a beginner in python. Try this but I'm not sure if it works.
`watt_per_meter_squared = %4d`

**Comment by Stormtracker017** [comment]
Thanks...Now the Current Station Obs displays Solar.  The `watt_per_meter_squared = %4d ` display 4 digits after the decimal point i.e. 72.0754.  I'm trying to learn python.

**Comment by HoracioDos** [comment]
That happens because the radiation value is a float type. I don't know if is possible to format it as integer or string in weewx.conf

**Comment by poblabs** [comment]
Are you using the MQTT Websockets or no?

You guys are close. Based on [the code here you can see that the comma to separate the grouping of the thousands and hundreds is defined by "popular" locale settings](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L740-L745), but is mostly specific to the pressure and cloudbase. 

Currently no option to override it, you'd have to edit this line to add `|| thisElementClass == "radiation"` at the end of the line.

**Comment by Stormtracker017** [comment]
Yes using MQTT Websockets.  Edited the line of code in belchertown.js.tmlp, now waiting for a sunny day.
