### ISSUE TITLE
Formatting in graphs

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#124]
Hi Pat

Couple of questions relating to the attached pics;

1. The bottom timeline is 24hr format but the hover time is am/pm, can the hover time be changed to 24hr also?

2. I've just added a new Air Quality chart, when I hover over the chart any numbers over 999 have a space, so 1234 is showing 1 234. This used to happen on the barometer chart but was fixed some time ago. Screen shots of both attached for clarity
The numbers in the database do not have the space. Here is my test tag line in my about page
**Test AQM data ... CO2 level is 1165 ppm, AQM2.5 is 2.1 μg/m³, AQM10.0 is 6.0 μg/m³, Air Quality Index is 8**
 
![Screen Shot 2019-05-14 at 1 50 49 PM](https://user-images.githubusercontent.com/1725001/57665381-b99bcc00-764f-11e9-9b0a-807170667c4f.png)
![Screen Shot 2019-05-14 at 1 50 18 PM](https://user-images.githubusercontent.com/1725001/57665386-bf91ad00-764f-11e9-82f6-5b51f4b21770.png)

**Comment by poblabs** [comment]
1. This should follow your locale. Do you have the latest development installed? 

2. Yeah this was fixed. It's not doing it in your barometer, only your aqm data? This may require a special override. It's hard to track which locales use no comma, use a comma, or use a period to delineate the group separator for thousands and hundreds.

**Comment by 41south** [comment]
I'm on RC7, what files do I need to update to the latest - or just do a complete install if there are no breaks?

Correct just aqm has the space in it

**Comment by olpayras** [comment]
Install a full release dont break anything. Just keep a backup of skin.conf if you have done a translation, if not, even graphs.conf won't be rewritten. just the .example files but you shouldn't use them.

**Comment by poblabs** [comment]
Let me see if I can replicate this to narrow it down.

**Comment by poblabs** [comment]
olpayras is right - you can download the latest Development zip file then copy the files up to your server. I just pushed 1.0rc9. 

https://github.com/poblabs/weewx-belchertown/archive/development.zip

I'll still look into this issue though. I think it's related to [this section within the chart tooltip helper function](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L210-L213). I'm still not sure how to make it user customizable - this section is making a lot of assumptions.

**Comment by poblabs** [comment]
Thinking I might remove the barometer static definition for no comma and making this a graphs.conf override. Based on the documentation for `[Highcharts.numberFormat()](https://api.highcharts.com/class-reference/Highcharts#.numberFormat)`, something like the below would work. 

```
[day]
    title = Today
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000
    
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            decimals = 2
            decimalPoint = "."
            thousandsSep = ""
```

Let me work on this and let you know when it's ready for testing.

**Comment by 41south** [comment]
Ah yes, that looks like it would be great way to fix it. Let me know when
it's ready for testing

**Comment by poblabs** [comment]
Think I've got this sorted now, but I want to sleep on it. I'll look to commit it tomorrow with an example code on how to use it.

**Comment by poblabs** [comment]
Just an update here on item 1, it has to do with the new time format labels. See #126 for the updated config which will fix it.

**Comment by poblabs** [comment]
As I continue to push more and more things to graphs.conf, I wonder if it makes sense to have the tooltip date time format as an option in graphs.conf. This way each graph can have customized tooltips in case the user doesn't want to use one of the 3 pre-defined ones that I have in the labels.

**Comment by poblabs** [comment]
Yes I think I might do that. I really like the idea of everything graphs related lives in the graphs.conf. 

I'll update this

**Comment by poblabs** [comment]
Colin, couple of updates in that last commit which I think will fix your issues here. It requires a bit more graphs.conf configs, but once you have them set they should be good to go. 

### Item 1 - tooltip date time formatting
I moved this to graphs.conf. It uses moment.js' string format to convert the time into a display format you like. The formats are here at https://momentjs.com/docs/#/parsing/string-format/. 

Add `tooltip_date_format` to the graph group, and define the time format you want. LLL in the example below is locale aware and will adjust the day and months around based on locale. For example in my locale it will show `May 15 2019 9:00 AM` as an example. 

![image](https://user-images.githubusercontent.com/3484775/57779527-3c766280-76f4-11e9-81a4-bdb07e2b70ae.png)

```
[day]
    # Chart Timespan Defaults
    title = Today
    show_button = true
    button_text = Today
    time_length = today
    tooltip_date_format = "LLL"
    gapsize = 300000

    [[chart1]]
        title = Temperature
        ..........
```

You can also specify per-chart date time overrides. So if you wanted different formats for each chart it's possible. Here's an example. Every graph will get "LLL" as a formatting, except the temperature chart because it has changes in `tooltip_date_format` within it's chart config. 

![image](https://user-images.githubusercontent.com/3484775/57779301-d4278100-76f3-11e9-8f9e-306b3360b45e.png)

```
[day]
    tooltip_date_format = "LLL"

    [[chart1]]
        title = Temperature
        tooltip_date_format = "ddd"
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
    
    [[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
```

---

### Item 2 - number formatting

The number formats (decimals, decimal point and thousands separator) are defined by the locale on your system. If you want to do an override for a specific graph observation you can use the `numberFormat` option for that observation. 

Here you can see I'm defining 5 decimals, using `.` as the decimal point and `,` as the thousands separator. The tooltip hover, and the y axis labels are updated.

![image](https://user-images.githubusercontent.com/3484775/57779035-5794a280-76f3-11e9-9de9-e98ee3e62ba0.png)

```
[day]
...graph group options...
    [[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"
            [[[[numberFormat]]]]
                decimals = 5
                decimalPoint = "."
                thousandsSep = ","
```

In this example, I am letting weewx define how many decimals (since decimals is not explicitly defined here), and will have the `,` for the decimal point and nothing for the thousands separator. 

![image](https://user-images.githubusercontent.com/3484775/57779133-8579e700-76f3-11e9-8fef-2c36d6f8c303.png)

```
[day]
...graph group options...
    [[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"
            [[[[numberFormat]]]]
                decimalPoint = ","
                thousandsSep = ""
```

**Comment by poblabs** [comment]
I'm going to copy these explanations to the wiki as well - let me know if they make sense and if they work for you!

**Comment by 41south** [comment]
OK so to get 24 hr time with the same date format I tried

tooltip_date_format = "LL H HH"

But that doesn't work, what did I miss in the formatting?

**Comment by 41south** [comment]
In fact I just tried tooltip_date_format = "LL" and that was ignored too by the looks, it should have given me Month name, day of month, year according to the doc you referenced

**Comment by 41south** [comment]
Whoops - might need the new Belchertown.py :) Wait one while I do that

**Comment by poblabs** [comment]
Have you updated to the latest version? I pushed a few updates today to get
that time formatting to work.

**Comment by 41south** [comment]
Yep just updated to rc9.1 and it's working, I just need to work out the format. "LLH HH" looks strange and "LL H HH" seems to ignore the time part.

**Comment by poblabs** [comment]
Drop the LLLL if you don't want locale aware. Just use hhh or mm/DDD I
think.

Typically the LLL or LL or LTS are used on their own.

**Comment by poblabs** [comment]
If I were to guess what your charts would look like it would be the below:

Notice the tooltip_date_format is LLLL which means `Thursday, September 4 1986 8:30 PM` in my locale, and it should mean `Thursday, 4 September 1986 20:30` in your locale.

Also notice under barometer I have the number format. I also don't have your data for the last 2 charts but they should be easy to figure out once you get going. 

No need to restart weewx when adjusting graphs.conf. Just save and run wee_reports. 

```
[homepage]
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000
    title = Today's Charts
    tooltip_date_format = "LLLL"

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[dewpoint]]]
        [[[appTemp]]]

    [[chart2]]
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        [[[rainTotal]]]
            name = Rain Total
        [[[rainRate]]]
            yAxis = 1
            
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            [[[[numberFormat]]]]
                decimals = 2
                decimalPoint = "."
                thousandsSep = ""
            
    [[solarRadGraph]]
        title = Solar Radiation and  UV Index
        [[[radiation]]]
           name = Solar Radiation
           zIndex = 1
           color = "#ffc83f"
        [[[maxSolarRad]]]
            name = Theoretical Max Solar Radiation
            color = "#f7f2b4"
            y_label = "W/m2"
        [[[UV]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 14
            color = "#90ed7d"
            y_label = "UV"
            name = UV Index
            zIndex = 2

YOUR BATTERY MONITOR CHART HERE

YOUR AIR QUALITY CHART HERE
Within air quality you'll want the same as barometer
            [[[[numberFormat]]]]
                decimals = 2
                decimalPoint = "."
                thousandsSep = ""
```

**Comment by 41south** [comment]
Hmm, nope that didn't work. I'm looking for 'Thursday 16 May 2019 20:15' (with or without the colon, prefer with so it doesn't look like a year). LLLL just gives me what I have - still with the am/pm suffix. According do the guide 24hr time is 'H HH'?

**Comment by poblabs** [comment]
Ok forget the locale aware and go long hand with it then. 😄 It can get confusing but here's what I'd do for that format, with explanation below. 

`dddd DD MMM HH:mm`

Explanation:

`dddd` gives you full day, like Saturday. `ddd` would give you short day name like Sat

`DD` would give you the day as a number with a leading 0, like 05. If you want just 5 it would be `D`

`MMM` gives you the short name of the month like "Jan". If you want "January" it'd be `MMMM`

`HH` is the hour in 24 hour format with a leading 0, like 02. If you don't want the leading 0 it would be `H`.

`mm` is the minute with a leading 0, like 08. If you don't want the leading 0, use `m`.

**Comment by 41south** [comment]
Ok so yes that certainly fixes the space in the AQM chart :)

Righto, I'll drop that in. Does some sort of time format need applying to all charts? You may have this as a chart wide default that I don't have yet but it seems to be defaulting to this on other charts with nothing set.
![Screen Shot 2019-05-16 at 12 07 01 PM](https://user-images.githubusercontent.com/1725001/57817438-6fdbee80-77d3-11e9-86c3-03f2c7272fcc.png)

**Comment by poblabs** [comment]
Yes, needs to be applied to every chart group (e.g. `[day]`, `[week]`, `[month]`, `[year]`). Define it at the top of the group settings, like this for example:

```
[day]
    tooltip_date_format = "dddd DD MMM HH:mm"

.... everything else here ...
```

**Comment by 41south** [comment]
Cool that works great and I see how the formatting works now so thanks for that. And in fact I can make it a global default by putting it up in that first section above the chart group stanzas

**Comment by poblabs** [comment]
Ah you're right, it can go into global defaults too. 

Honest question, because I'm sure this will come up quite a bit. How best can I explain this so it can be a wiki item?

**Comment by poblabs** [comment]
Looks good now! 

![image](https://user-images.githubusercontent.com/3484775/57817787-04503d80-774f-11e9-9511-205deb5a7277.png)

**Comment by 41south** [comment]
Actually I'm not sure the global thing works, I put it in there and the charts went back to that long default, I may need to play a bit more but for now I've just added it to each chart stanza.

I think how you explained it to me just back a few posts was ideal, pictures and example are worth a thousand words as they say.

**Comment by 41south** [comment]
Just need to go back and fix the Baro now (take that space out). And one last question - I promise!

What was the trick to making the Baro scale down the left just 1 decimal place the same as the tooltips and main Baro reading?
![Screen Shot 2019-05-16 at 12 24 19 PM](https://user-images.githubusercontent.com/1725001/57817864-8daa5300-77d5-11e9-8d88-27acfd388b15.png)

**Comment by 41south** [comment]
Never mind - it just happened when I fixed the tooltip issue and specified 1 deciaml point, they must both be the same?

**Comment by poblabs** [comment]
Ok I updated the wiki a little bit for the [chart time formats](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#tooltip-date-time-formatting). Comments appeciated for more clarity. I have a feeling there'll be a lot of questions in my future, so the wiki will be the first stop for a lot of people. 

The y axis labels are tied to the new numberFormat option. So if you use only 1 decimal there, it should update the labels to match the 1 decimal. Try that first to see if it'll help you out. 

Here's my silly example with 9 decimals, just to prove it out

```
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            [[[[numberFormat]]]]
                decimals = 9
                decimalPoint = "."
                thousandsSep = ","
```

![image](https://user-images.githubusercontent.com/3484775/57818060-5776c000-7750-11e9-9b15-213727a26aeb.png)

**Comment by 41south** [comment]
Perfect - thanks heaps!

**Comment by 41south** [comment]
And the Wiki stuff looks perfect, there will be a lot of reading for folks to do. One of the 'double edged swords' of ultimate configurability so I guess the more of us long term users who understand it and can help explain.answer questions the better.

**Comment by poblabs** [comment]
Good stuff! 

Close this one out if you're all set after getting more familiar with it. Let me know if there's any other questions!

**Comment by 41south** [comment]
I have one or 2 about ticks (I think? in relation to the scale of a graph particularly for the barometer) but I'll search back through the other issues and see if I can read my way though it.

Closing this one out.

**Comment by poblabs** [comment]
@41south your homepage chart group isn't setup with the time formatting either. It's still the very long default format.

**Comment by 41south** [comment]
Um, no they've all defaulted back somehow, was just posting about that, very strange

**Comment by poblabs** [comment]
Interesting. Typically you don't have to restart weewx for graphs.conf to take effect - but have you restarted weewx since installing the new `belchertown.py` file?

**Comment by 41south** [comment]
Ah, no I haven't will try that

**Comment by poblabs** [comment]
That'll do it

**Comment by 41south** [comment]
Done 👍
