### ISSUE TITLE
Update to rc9 "broke" graphs

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#125]
Not sure what's happened here, after the update from rc7 to rc9 I have this on the graphs page rather than Day, Week, Year
Did I need to update graphs.conf in some way?
![Screen Shot 2019-05-15 at 1 47 23 PM](https://user-images.githubusercontent.com/1725001/57743209-3d20f000-7718-11e9-800e-5af177e98e66.png)

**Comment by poblabs** [comment]
Your graphs are working for me, maybe clear your cache? 

You are missing the buttons. You will need to add this to each graph group. 

```
    show_button = true
    button_text = Today
```

Full example:

```
[day]
    # Chart Timespan Defaults
    title = Today
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
```

![image](https://user-images.githubusercontent.com/3484775/57743274-5ed79400-7692-11e9-90e9-5df355bdb31b.png)

**Comment by poblabs** [comment]
Take a look at the graphs.conf.example, too. That should be updated. Rename your graphs.conf to something like graphs.old, then run wee_reports. It should generate all the default graphs for you. Then you can compare the changes to your existing graphs.conf.

**Comment by 41south** [comment]
Ah ok, didn't realise that needed adding. I've done quite a bit of work in graphs.conf so if that's all that's missing I'll go with that. Or is there more that I will need for future updates?

**Comment by poblabs** [comment]
I think majority else should be ok. I've added a bunch more like the xaxis grouping (see the other issue for examples). But get yourself to a working state again and then expand. Documentation should be coming soon too

**Comment by 41south** [comment]
Cool thanks. Things are moving so fast it's hard to keep up :) I know I've seen some features that want to incorporate, but going back now and finding them could take some sleuthing

**Comment by poblabs** [comment]
Yeah, once I fix your decimal issue I think it'll slow down. Then it'll just be documenting, and a wide array of sample graph configs.

**Comment by 41south** [comment]
And missing a bunch of stuff from here too
![Screen Shot 2019-05-15 at 2 04 53 PM](https://user-images.githubusercontent.com/1725001/57743752-765a5f80-771a-11e9-808c-b8f3a1195d57.png)

**Comment by poblabs** [comment]
That's another feature. Added to give more control. Take a look at skin.conf, `    station_observations = "barometer", "dewpoint", "outHumidity", "rainWithRainRate"`. Ships with 4 by default. Feel free to add any observation names here that are in the database. They should update automatically when you have MQTT Websockets enabled. 

`rainWithRainRate` is a special one that shows the rain, and rainrate on the same line. 

So to add UV, it would be:

`station_observations = "barometer", "dewpoint", "outHumidity", "rainWithRainRate", "UV"`

If you want UV first, just move it up to the front. 

`station_observations = "UV", "barometer", "dewpoint", "outHumidity", "rainWithRainRate"`

and so on. 

Best to copy this to your weewx.conf, under Belchertown Extras.

**Comment by 41south** [comment]
Yeah I keep everything in weewx.conf now, let me see if I can pop that other stuff back in. Ok off to sort that :)

How do I get rid of the ALL graphs?

**Comment by poblabs** [comment]
skin.conf, `graph_page_show_all_button = 1`

Set to 0

**Comment by 41south** [comment]
Righto, just about back to "normal". Trying to remember what I had in station_observations now lol.

**Comment by poblabs** [comment]
Take a look at my site. Think the defaults before had also UV and
radiation.

**Comment by 41south** [comment]
Sorted, thanks Pat!

Closing
