### ISSUE TITLE
Darksky forecast date format revisited

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#126]
Now I may be going a little crazy but I'm sure this was previously 'fixed'? #1  The Darksky forecast date format is back in the US M/d standard, I'm sure given my locale it was d/M
![Screen Shot 2019-05-15 at 5 25 31 PM](https://user-images.githubusercontent.com/1725001/57750571-e2e35780-7736-11e9-9ece-204937944714.png)

**Comment by HoracioDos** [comment]
Hello.
Check this keyword. It should work for you
`time_darksky_forecast_date = ddd DD/M`

**Comment by poblabs** [comment]
HoracioDos is right. In previous versions I was trying out auto detect with the locale of weewx to set the time format, but I was getting requests from people who didn't want their weather station in their locale. So the auto detection wasn't effective. So I moved it all to user controlled options. 

All the time and date settings are in skin.conf, under [Labels] --> [Generic] --> moment.js (they all being with time_). You can move these to weewx.com with an example below.

Take a look [at the moment.js string formats section](https://momentjs.com/docs/#/parsing/string-format/) to find the one you like. There's some locale aware versions as well under Locale. 

As a quick fix, you can set `time_darksky_forecast_date = ddd DD/M` like Horacio mentioned. 

```
    [[Belchertown]]
        skin = Belchertown
        HTML_ROOT = /var/www/html/btownwx
        [[[Extras]]]
            ...
            my_extras_here
            ...
        [[[Labels]]]
            [[[[Generic]]]]
                rain = My custom rain label override
                time_darksky_forecast_date = ddd DD/M
                
```

As an update to your issue #124, to change the formatting of the graphs date, time it would be these options:

```
        time_charts_tooltip_default             = "LLLL"
        time_charts_tooltip_day                 = "LLL"
        time_charts_tooltip_month_year          = "dddd LL"
```

**Comment by 41south** [comment]
Thank you gents, working a treat. Closing

**Comment by 41south** [comment]
Whoops, something is forcing the date/time format back to a default of some sorts? See below
![Screen Shot 2019-05-16 at 12 47 31 PM](https://user-images.githubusercontent.com/1725001/57818651-e5968900-77d8-11e9-9ad6-2683febbaeba.png)

**Comment by 41south** [comment]
Sorry - wrong issue reopened I think :/
