### ISSUE TITLE
No Issue --- Custom Content  Refresh Time Question

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#129]
Pat
Where would I change the refresh time for the custom content  ?  Example: The custom content changes appx every 30 minutes, so I don't want to hit the server every 5 minutes looking for updates.

**Comment by Stormtracker017** [comment]
Pat
Where would I change the refresh time for the custom content? Example: The custom content changes appx every 30 minutes, so I don't want to hit the server every 5 minutes looking for updates.

**Comment by poblabs** [comment]
Right now only the images within the custom content are refreshed. Images are "easy" to find and refresh. Refreshing text within the custom content becomes difficult because when it's all compiled it becomes 1 unified HTML file. And since I can't control what you put in there, I have no idea what to refresh it with (unlike the station observation, or forecast, etc. I know what the content is reliably, so I can code it to be refreshed). That's the challenge with the custom content. 

What's in your custom content? Is it weewx tags or images or?

**Comment by Stormtracker017** [comment]
I have some satellite loop images being displayed. Maybe at a later date, web cam images but placed in an additional custom hook.

**Comment by poblabs** [comment]
If they're images, then you can set the skin.conf option `reload_hook_images` to 1 to enable it. Then it'll reload those images everytime an archive packet is received on MQTT. If you're not using MQTT, then you'll need to use `webpage_autorefresh` to refresh the page on a set interval.

**Comment by Stormtracker017** [comment]
Okay. I'm using MQTT, so images are being refreshed every five minutes.  Is there a way to change the refresh rate to every 30 minutes (6 archive periods) for certain custom hooks?  If it can be done, maybe this could be a future enhancement, after 1.0 is released.

**Comment by poblabs** [comment]
Right now it's explicitly called during the archive period for all of the hook inc sections. I wonder if this is a bad approach to begin with? Maybe I should just set a normal timer of 5 minutes, which could be changed to any time wanted?

**Comment by Stormtracker017** [comment]
Setting a timer might be a way to go, it would allow the user set their refresh as they see fit.  Could you have a total of four timers; one for each hook inc secs?

**Comment by poblabs** [comment]
I could. Is there value in that extra overhead for all 4 sections?

**Comment by Stormtracker017** [comment]
My thinking is if you have a webcam image which is updated every 5 minutes in one hook and Satellite image(s) that are update every 30 minutes in another hook.  If you have an option in the skin to enable/disable (default = disable) the timers for each hook inc section, which will allow the user the choice of using or not using the refresh timers.

**Comment by poblabs** [comment]
I guess they'll just have some super long variable names. Example:

`reload_hook_images_after_station_info` maybe? try to truncate them a little bit

**Comment by Stormtracker017** [comment]
I think you can truncate them.  Add a definition prior, so the user would know what each acronym means. Example
 
after_station_info = asi
after_forecast = af
after_snapshot = as
after_charts = ac

reload_images_hook_asi
reload_images_hook_af
reload_images_hook_as
reload_images_hook_ac

**Comment by poblabs** [comment]
@Stormtracker017 Just updated this request. Give it a try when you have some time. In my testing it seemed to work, but I don't have a webcam or anything *real* to test with so let me know. 

3 files are updated in that last commit, but if you haven't updated in a while it might be best to grab a fresh copy of everything and restart weewx after you've configured the new options.

**Comment by Stormtracker017** [comment]
Pat
I setup two hook inc sections: one for a Webcam images -- refresh every 10 minutes and one Satellite Images -- refresh every 30 minutes.  So far these images are being refreshed at the rates that were set. This setup is with the latest development files running on weewx version 3.9.1.
