### ISSUE TITLE
WMR300 station stops sending data with the extension activated.

### ISSUE THREAD

**Issue by juanantoniomosquera** [poblabs/weewx-belchertown#13]
After 1 week of testing this extension I verified that when the extension is activated weewx stops receiving data after approximately 3 hours. The log (with debug) shows no errors. If I deactivate the extension, weewx works correctly for hours.

**Comment by juanantoniomosquera** [comment]
i dont know... but.... if disable your extension all OK... i am sorry... logs not help

**Comment by poblabs** [comment]
Again, I didn't write WMR300

But if you open the WMR300.py file in `bin/weewx/drivers`, and change these to all be `= 1`, then restart weewx - what do you see?

https://github.com/weewx/weewx/blob/master/bin/weewx/drivers/wmr300.py#L791-L796

Maybe post the results in the weewx user forum?

**Comment by juanantoniomosquera** [comment]
They have updated the driver of the station and the error is solved. I do not understand why it failed only with the Belchertown extension enabled. Thank you.

https://groups.google.com/forum/#!topic/weewx-user/jUF4J6tRxPU
