### ISSUE TITLE
ordinal compass translations not translated after mqtt refreshing datas

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#131]
Hi Pat,
When mqtt websockets refresh datas, the ordinal compass lost translations.

**Comment by poblabs** [comment]
On which section of the page?

**Comment by norecords** [comment]
In the wind table
`<span class="curwinddir"></span>`

**Comment by norecords** [comment]
At the moment I solved it by modifying line 130 in /usr/share/weewx/user/belchertown.py
`ordinate_names = default_ordinate_names`
to
`ordinate_names = weeutil.weeutil.option_as_list(self.generator.skin_dict['Units']['Ordinates']['directions'])`

**Comment by poblabs** [comment]
Interesting, and thanks for the fix. It should have gotten it from the default list in the Python file as a backup measure in-case someone deletes the skin.conf Units > Odinates > directions. I'll do a bit more testing

**Comment by poblabs** [comment]
I'm not able to replicate this.... it is in this section right?

![curwinddir](https://user-images.githubusercontent.com/3484775/58041276-b1d3a000-7b05-11e9-9971-3f59765eea50.gif)

**Comment by poblabs** [comment]
Ok I see why... I think. Let me do more testing

**Comment by norecords** [comment]
Yes this is the right section.
I was thinking about somethings like this.

**Comment by poblabs** [comment]
@norecords Please undo your `belchertown.py` changes and update your `belchertown.js.tmpl` file with the one I just committed. it should have the translations now in the MQTT updates. Please let me know!

**Comment by norecords** [comment]
done and it's working. Translations is now updated.

**Comment by poblabs** [comment]
Great news!

**Comment by olpayras** [comment]
Don't work for me :( Which files should we change ? Files used are in my History-feature branch. I do a merge from your development branch

**Comment by poblabs** [comment]
@olpayras For the wind direction compass, the ordinals are in weewx.conf. Since weewx.conf already contains the ordinals, it doesn't make sense for me to duplicate them in skin.conf. 

Here you can see where in weewx.conf here: https://github.com/weewx/weewx/blob/master/weewx.conf#L320

Technically, everything from skin.conf should be in somewhere within weewx.conf since skin.conf gets overwritten on updates. So the more I can use from weewx.conf, the safer we are.

**Comment by olpayras** [comment]
Thanks for reply. I've begun to put all my translations in weewx.conf. Thats working fine and will reduce risk of mistakes.
