### ISSUE TITLE
CSS switch doesn't remained

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#133]
@poblabs 
when I switch css style with the toggle button it doesn't remained on page change.
Console output:
`Theme: Toggle button changed belchertown.js:49:13`
`Theme: Changing to light belchertown.js:318:9`
`Theme: toggle override clicked. belchertown.js:323:13`
`Theme: sessionStorage.getItem('theme') was previously: dark belchertown.js:324:13`
`Theme: sessionStorage.getItem('theme') is now: dark belchertown.js:330:13`
Don't know why the theme is finally stored as dark.

**Comment by poblabs** [comment]
Is your site public? Can I take a look?

**Comment by norecords** [comment]
Of course
[here](https://meteo.correns.org)

**Comment by poblabs** [comment]
I see why. The toggle override only works in `auto` mode. You have `dark` mode set. 

This makes me wonder if it should work for all modes. light, dark and auto?

**Comment by norecords** [comment]
In my sense it should do, because it's even better if visitor can switch in his prefered css style :)

**Comment by poblabs** [comment]
Ok I think so too now that I use it. When I first put it in, it was for auto mode only, but if user wants dark mode all the time, then they should be able to do that. I will update it

**Comment by poblabs** [comment]
@norecords Give that latest `belchertown.js` a try and let me know?

**Comment by norecords** [comment]
Work like a charm. Thanks a lot Pat.
I fall in love with your theme ^^

**Comment by poblabs** [comment]
Thank you! Glad you like it!
