### ISSUE TITLE
Not an issue but a question - add observations to station_observation table

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#134]
On my personal site i'd like to custom this box by putting some personal sensors like UV and Visibility :
![Capture](https://user-images.githubusercontent.com/49792600/58183606-e4b99780-7caf-11e9-89bd-8bb2f0dc170c.JPG)

I Don't find where ? On previous versions i think it was in index.html.tpml but i didnt find them ?

**Comment by poblabs** [comment]
In skin.conf, under Extras look at station_observations setting, just add "UV", and "visibility" to the end.

**Comment by olpayras** [comment]
Thanks for you quick reply, I am trying that.

**Comment by olpayras** [comment]
Yes works fine, i close the issue.
