### ISSUE TITLE
How to pack weewx-belchertown skin. Help-Wanted

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#135]
Hello Pat
Is there a special way to pack the skin for deploying with wee_extension? Is it a simple tgz file?
I want to create a development environment in my notebook and I would like to install the skin without copying the files manually. 
Thanks!

**Comment by poblabs** [comment]
The way this repository is laid out is how it would be packaged. Everything within install.py has to be in place for it to work. I think install.py is mostly OK for now, except that it has the wrong version numb er. 

So you would just zip it in a tar.gz and then `wee_extension --install`.

For example:

```
wget https://github.com/poblabs/weewx-belchertown/archive/development.tar.gz

sudo wee_extension --install development.tar.gz
```

**Comment by HoracioDos** [comment]
Excelent!!!

**Comment by poblabs** [comment]
Installing development onto your notebook as a development environment will help me with any bugs that may be there from install.py and that all files are copied automatically. Especially the new celestial.inc file

**Comment by HoracioDos** [comment]
I'm glad if I can help you. I'm a little tired to tweak into production. I also need to create some history for graphs, so my notebook will create "old records" faster than the Pi

**Comment by 41south** [comment]
Wee_exyension will install the development zip file with no changes, it
doesn't need to be tar.gz or anything. That's how I've always done it.

Colin

**Comment by poblabs** [comment]
This is true so long as you have the package `unzip` installed on your system I believe. Either method could work though!

 

Sent from mobile

**Comment by HoracioDos** [comment]
Hello Pat
I've installed the development branch using wee_extensions. (No customs applied) in a new dev environment. Everything seems to be in the right place. Weewx is creating one year of history records. Standard report didn't run yet. I'll keep you informed if there's something  strange.
