### ISSUE TITLE
Winrun load with miles and refresh in km after mqtt reload

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#138]
@poblabs 
HI Pat,
I enabled today appTemp and windrun.
windrun load in miles and refresh in km without unit as you can see [here](https://meteo.correns.org )
in the station observations section.

**Comment by poblabs** [comment]
What do you have set for the `group_distance` value?

**Comment by HoracioDos** [comment]
Hello @norecords
You must set group_distance = km. in weewx.conf or skin.conf if you've enabled Windrun.

**Comment by norecords** [comment]
Ok I haven't set group_distance to km, now it's loading with km, but after mqtt refresh the unity km doesn't appear.
Thanks you for answers.

**Comment by poblabs** [comment]
Oh I have never tried windrun in the station observations. I will try that today and see if I can get the units to show.

**Comment by norecords** [comment]
It seems that the value returned by mqtt is also rounded.

**Comment by poblabs** [comment]
The rounding is because if it's not defined in the weewx_data skin file then it defaults to the rounding. I'll work on this.  Also as a sidenote you shouldn't subscribe to `#`, but rather the `loop`... so `correns/live/loop`

**Comment by poblabs** [comment]
Oops, I mean to say this:

You had to set this: 
`group_distance = km`

But you also have to set the rounding for `km` under `[[[[StringFormats]]]]` in weewx.conf. It is missing by default. 

This is a weewx setting not a Belchertown setting.

**Comment by poblabs** [comment]
Ok, looks like there's a few things missing. This should all have been in the weewx core settings - looks like they may have missed it?

I've added them to the skin.conf as a band-aid, but they should live in the weewx.conf. It's the group_distance setting, the rounding setting, and the unit label setting. You can see those changes in the latest skin.conf. 

This is working for me now, please try it out.

**Comment by norecords** [comment]
I've got changed values has you said and update 
It's working perfectly great. Good job Pat !
I've get it under the wind-table section in index.html.tmpl
Thanks you.
