### ISSUE TITLE
yAxis labels cannot be hidden

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#139]
There should be a way to hide the yAxis labels in a config option.  Something like `show_yaxis_label = false`

This would allow the user to avoid empty `()` on the yaxis for custom observations (like lightning in my case)

**Comment by poblabs** [comment]
Pretty big challenge with 2 axis and multiple observations across them

**Comment by 41south** [comment]
Why would you need to hide them? Even empty ones look fine but I've also
just used a text label when I felt it necessary

**Comment by poblabs** [comment]
Good question. I might be overthinking this one. 

I had a situation where my lightning sensor had a y label of `()`. Which means that weewx can't find the unit or label for it which makes sense since it's not a standard weewx observation. 

I guess what I could do is just make a small update of `if can't find observation unit then don't do ()`...

**Comment by 41south** [comment]
I have the same with the AQI index in my new AQM charts, doesn't bother me
too much or I could just put a manual "Index" label there

**Comment by poblabs** [comment]
Latest push fixes a bug I had in there and adds a bit more control to the yAxis labels. 

Here's what will go in the wiki:

yAxis label is defined top down. Meaning the last observation in the group will override the others. 

### No yAxisLabel override defined

In this example there are no `yAxisLabel` overrides defined, so the yAxis label is taken from the last observation in the group which is dewpoint. 

```
[homepage]
    # Chart Timespan Defaults
    show_button = false
    button_text = Homepage
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/58375972-8c8fc900-7f2d-11e9-9388-2227d1a9a3a3.png)

### yAxis Label Override At The Top

Since we have defined a `yAxisLabel` at the top of the graph group, it will be used instead of any of the observation labels. 

```
[homepage]
    # Chart Timespan Defaults
    show_button = false
    button_text = Homepage
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.

    [[chart1]]
        title = Temperature
        yAxisLabel = "Example Label At The Top (°F)" 
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/58375980-b34dff80-7f2d-11e9-8bfa-b3626b74311b.png)

### Multiple yAxis Labels defined but not for the last observation

If you have multiple `yAxisLabel`s defined, the bottom one in the group will win - even if that bottom observation does not have a yAxisLabel defined. Because it's top down, the last observation will win the label. Take this example which has 3 defined, yet the output is for Dew Point. That's because Dew Point's default label is applied. 

To fix this, specify a yAxisLabel for dewpoint that would be what you want for the yAxis label. 

```
[homepage]
    # Chart Timespan Defaults
    show_button = false
    button_text = Homepage
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.
    
    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
            yAxisLabel = "yAxisLabel inside temperature"
        [[[windchill]]]
            yAxisLabel = "yAxisLabel inside windchill"
        [[[heatindex]]]
            yAxisLabel = "yAxisLabel inside heatindex"
        [[[dewpoint]]]
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/58376033-d7f6a700-7f2e-11e9-9277-1e4c480febe5.png)

### Multiple yAxis Labels defined for all observations

As with the example above, we add the yAxisLabel to the last observation and now that label is what becomes the label for the yAxis. 

```
[homepage]
    # Chart Timespan Defaults
    show_button = false
    button_text = Homepage
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.
    
    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
            yAxisLabel = "yAxisLabel inside temperature"
        [[[windchill]]]
            yAxisLabel = "yAxisLabel inside windchill"
        [[[heatindex]]]
            yAxisLabel = "yAxisLabel inside heatindex"
        [[[dewpoint]]]
            yAxisLabel = "yAxisLabel inside dewpoint"
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/58376046-2dcb4f00-7f2f-11e9-951f-4d83a4a94dc1.png)

### Removing (or setting) a yAxis label

If you want to remove the yAxis label all together, you can set the yAxisLabel at the top of the chart group to be blank. Take this example below:

```
[homepage]
    # Chart Timespan Defaults
    show_button = false
    button_text = Homepage
    time_length = today
    gapsize = 300000
    title = Today Since Midnight.

    [[chart1]]
        title = Temperature
        yAxisLabel = ""
        [[[outTemp]]]
            name = Temperature
            zIndex = 1
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
```

![image](https://user-images.githubusercontent.com/3484775/58376158-a9c69680-7f31-11e9-8027-82c74129b6b8.png)



### An unknown observation and it's label

This will have NO yAxis label since `lightning_strikes` and `avg_distance` are not a known built-in weewx observation - so there's no label or unit label. 

Setting the yAxis label is easy! Just see one of the examples above. 

```
    [[lightninggroupby]]
        title = Lightning Strikes This Year
        time_length = year
        xaxis_groupby = month
        xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'

        [[[lightning_strikes]]]
            name = Lightning
            type = column
            stacking = normal
        [[[avg_distance]]]
            name = Average Distance
            type = column
            stacking = normal
```

![image](https://user-images.githubusercontent.com/3484775/58376141-2dcc4e80-7f31-11e9-8779-ea7726ebcbed.png)

**Comment by 41south** [comment]
Nice!
