### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by mash55** [poblabs/weewx-belchertown#14]
Is this the right place to ask for help? (New weewx user with issues generating graphs)

**Comment by poblabs** [comment]
Hey there, yes this is one way to help. (I think I got your email but I haven't read it yet). It's been a busy few days for me, so I can try to help soon. There's a few people using the skin now, so you may be able to get a quicker head start on the [weewx user forums](https://groups.google.com/forum/#!forum/weewx-user). Be sure to remove your API keys and other sensitive information. 

If nobody helps soon (1 day or so), then I should be freed up again to help out.

**Comment by mash55** [comment]
OK, thanks... you can disregard my email since I played around with the skin today and got a better understanding how it works (no live update (MQTT) yet). So here my problem... I am running the reports but no graphs show up on the Website. 
weewx.conf (excerpt):
```
[[Highcharts_Belchertown]]
        HTML_ROOT = /var/weewx/reports/belchertown
        skin = Highcharts_Belchertown
    [[Belchertown]]
        HTML_ROOT = /var/weewx/reports/belchertown
        skin = Belchertown
        [[[Extras]]]
            logo_image = http://schnizer.net/wx_banner.png
            footer_copyright_text = mashNET - schnizer.net
            earthquake_enabled = 1
            earthquake_maxradiuskm = 1000
            earthquake_stale = 10800
            highcharts_enabled = 1
            forecast_enabled = 1
            darksky_secret_key = *********************************
            mqtt_enabled = 0
            radar_html = bla bla
```

Attached the syslog output - can't see any issues.
[Syslog_Output.txt](https://github.com/poblabs/weewx-belchertown/files/2413358/Syslog_Output.txt)

Result on Website: http://schnizer.net/belchertown/

Appreciate any pointers on what I am doing wrong.

**Comment by 41south** [comment]
Hi and welcome to the group! Have you configured the skin.conf in both Belchertown and Highcharts_Belchertown?

**Comment by mash55** [comment]
Thanks for your reply and the welcome. So far I left the skin.conf file alone. My understanding is that I can overwrite the settings in the weewx.conf file. I did have the 'highcharts_enable=1' setting in the 'Belchertown' report but not in the 'Highcharts_Belchertown' report. Adding the setting did not solve the issue. Here my weewx.conf settings again:
---------------------------------------------------------------------------
[[Highcharts_Belchertown]]
        HTML_ROOT = /var/weewx/reports/belchertown
        skin = Highcharts_Belchertown
        highcharts_enabled = 1
    [[Belchertown]]
        HTML_ROOT = /var/weewx/reports/belchertown
        skin = Belchertown
        highcharts_enabled = 1
        [[[Extras]]]
            logo_image = http://schnizer.net/wx_banner.png
            footer_copyright_text = mashNET - schnizer.net
            earthquake_enabled = 1
            earthquake_maxradiuskm = 1000
            earthquake_stale = 10800
            highcharts_enabled = 1
            forecast_enabled = 1
            darksky_secret_key = **************************
            mqtt_enabled = 0
-----------------------------------------------------
I was aware of the HTML_Root issue. Both reports defined in the weewx.conf file do include the correct HTML_Root directory (see above).
Still puzzled...

**Comment by 41south** [comment]
Not sure if this will help
![screen shot 2018-09-26 at 5 11 52 pm](https://user-images.githubusercontent.com/1725001/46058487-74ee1e00-c1af-11e8-986d-4f347174976d.png)

**Comment by mash55** [comment]
That helps indeed - thanks. I can now say that the reports are generated and transferred. It seems to be related to the PATH issue you mentioned earlier. The json files are generated under the belchertown directory. The link to the graphs is pointing to the root - eventhough I defined HTML_Root in the weewx.conf file for both reports (BElchertwon and Highcharts_belchertown). Next I will try remove the standard reports from the config and let everything under root dir. I could live with that, but would prefer to understand why these links are pointing to the wrong place.

**Comment by mash55** [comment]
There is another variable (belchertown_root_url="") in the skin.conf. Adding this does indeed copy the files to the correct location. It does not solve the issue of the links (HOME/GRAPHS/RECORDS/REPORTS/ABOUT). I am now generating the reports under root, works for me. Off to understand/implement MQTT.
Thanks again for your help

**Comment by poblabs** [comment]
Hey guys. Sorry im pretty behind. that variable you found is not in a
release yet so you must be using the master Branch off of GitHub. so if
you're using the master Branch off of GitHub and something's not working
then I'll need to fix it. Almost as if your beta testing for me. :)

I'm still a couple days behind I have some other priority projects that I'm
working on with my real job. hopefully I can find a spare half an hour or
an hour to get caught up.

Sent via mobile

**Comment by 41south** [comment]
Glad you got it working. I have MQTT working if you get stuck

**Comment by poblabs** [comment]
I also just put together a set-up guide for MQTT on my blog at
https://obrienlabs.net

Hopefully it can get you started...

**Comment by mash55** [comment]
> Hey guys. Sorry im pretty behind. that variable you found is not in a release yet so you must be using the master Branch off of GitHub. so if you're using the master Branch off of GitHub and something's not working then I'll need to fix it. Almost as if your beta testing for me. :)

Oh, so where/how do I download a non BETA release. Don't really need the additional confusion due to BETA status until I understand the system better.

**Comment by poblabs** [comment]
Go to the main page of this GitHub repository and then click the word
releases. Then you can see where to download the releases from.

**Comment by mash55** [comment]
Got it, thanks a bunch (and also for the MQTT tutorial... will be back soon ;)

**Comment by psuchuck** [comment]
Hello,

Hope you don’t mind me joining this conversation.   I had the same problem with the graphics not showing up correctly.   Right now I can get my graphics in the Belchertown directory, but not where I really need it in the dirtory above it.    How would I do this?

Thanks,

Chuck

**Comment by mash55** [comment]
just remove the [[Standard]] report and point the HTML_ROOT of the [[Highcharts_Belchertown]] report to the location you want the report in.
Hope this helps
Matt

**Comment by psuchuck** [comment]
Thank you Matt, got it.

**Comment by poblabs** [comment]
Hi everyone - just checking in. I think we're all set in this support thread now? If so I'll close it out.

**Comment by psuchuck** [comment]
Yes, thank you.
