### ISSUE TITLE
No module named config

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#140]
Pat
Downloaded and installed the latest development files; received the following errors:

No module named config.
highcharts_show_apptemp

[belchertown lastest dev errors.txt](https://github.com/poblabs/weewx-belchertown/files/3219842/belchertown.lastest.dev.errors.txt)

[skin.conf.txt](https://github.com/poblabs/weewx-belchertown/files/3219843/skin.conf.txt)

**Comment by poblabs** [comment]
What version of weewx are you using?

Looks like you may have installed the **master** version and not the **development** version? Based on this error here, `KeyError: 'highcharts_show_apptemp'` this key does not exist in the 1.0 development beta version. 

Also, you should delete the old Highcharts skins as that's old and may be conflicting? Check this on information https://github.com/poblabs/weewx-belchertown/wiki/Upgrading-to-Belchertown-skin-1.0

**Comment by Stormtracker017** [comment]
Pat
I re-downloaded the zip file from the development branch. I followed the directions provided and still get the No module named config error:

May 25 21:55:21 raspberrypi weewx[6249]: manager: Daily summary version is 2.0
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
May 25 21:55:21 raspberrypi weewx[6249]:         ****  No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Traceback (most recent call last):
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      obj.start()
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
May 25 21:55:21 raspberrypi weewx[6249]:         ****      self.run()
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 155, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      self.initExtensions(gen_dict[section_name])
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 197, in initExtensions
May 25 21:55:21 raspberrypi weewx[6249]:         ****      class_ = weeutil.weeutil._get_object(x)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1132, in _get_object
May 25 21:55:21 raspberrypi weewx[6249]:         ****      mod = __import__(module)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/user/belchertown.py", line 35, in <module>
May 25 21:55:21 raspberrypi weewx[6249]:         ****      from weeutil.config import search_up
May 25 21:55:21 raspberrypi weewx[6249]:         ****  ImportError: No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Generator terminated
May 25 21:55:21 raspberrypi weewx[6249]: copygenerator: copied 2 files to /home/weewx/public_html
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Unable to instantiate generator user.belchertown.JsonGenerator
May 25 21:55:21 raspberrypi weewx[6249]:         ****  No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Traceback (most recent call last):
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 220, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      obj = weeutil.weeutil._get_object(generator)(
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1132, in _get_object
May 25 21:55:21 raspberrypi weewx[6249]:         ****      mod = __import__(module)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/user/belchertown.py", line 35, in <module>
May 25 21:55:21 raspberrypi weewx[6249]:         ****      from weeutil.config import search_up
May 25 21:55:21 raspberrypi weewx[6249]:         ****  ImportError: No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Generator ignored
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Running report Belchertown
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Found configuration file /home/weewx/skins/Belchertown/skin.conf for report Belchertown
May 25 21:55:21 raspberrypi weewx[6249]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown.getData']
May 25 21:55:21 raspberrypi weewx[6249]: manager: Daily summary version is 2.0
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
May 25 21:55:21 raspberrypi weewx[6249]:         ****  No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Traceback (most recent call last):
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 239, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      obj.start()
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 273, in start
May 25 21:55:21 raspberrypi weewx[6249]:         ****      self.run()
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 155, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      self.initExtensions(gen_dict[section_name])
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 197, in initExtensions
May 25 21:55:21 raspberrypi weewx[6249]:         ****      class_ = weeutil.weeutil._get_object(x)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1132, in _get_object
May 25 21:55:21 raspberrypi weewx[6249]:         ****      mod = __import__(module)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/user/belchertown.py", line 35, in <module>
May 25 21:55:21 raspberrypi weewx[6249]:         ****      from weeutil.config import search_up
May 25 21:55:21 raspberrypi weewx[6249]:         ****  ImportError: No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Generator terminated
May 25 21:55:21 raspberrypi weewx[6249]: copygenerator: copied 2 files to /home/weewx/public_html/belchertown
May 25 21:55:21 raspberrypi weewx[6249]: reportengine: Unable to instantiate generator user.belchertown.JsonGenerator
May 25 21:55:21 raspberrypi weewx[6249]:         ****  No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Traceback (most recent call last):
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 220, in run
May 25 21:55:21 raspberrypi weewx[6249]:         ****      obj = weeutil.weeutil._get_object(generator)(
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1132, in _get_object
May 25 21:55:21 raspberrypi weewx[6249]:         ****      mod = __import__(module)
May 25 21:55:21 raspberrypi weewx[6249]:         ****    File "/home/weewx/bin/user/belchertown.py", line 35, in <module>
May 25 21:55:21 raspberrypi weewx[6249]:         ****      from weeutil.config import search_up
May 25 21:55:21 raspberrypi weewx[6249]:         ****  ImportError: No module named config
May 25 21:55:21 raspberrypi weewx[6249]:         ****  Generator ignored

First time I forgot to delete the files within the bin\user folders.

**Comment by poblabs** [comment]
Strange. Nothing jumps out at me right away. It looks like it can't find a
weewx module.  What version of weewx? Did you make any other changes before
the reinstall?

**Comment by Stormtracker017** [comment]
Was just looking at that. weewx version 3.8.2  I did not make any changes.

**Comment by Stormtracker017** [comment]
On this Pi, I upgrade from Belchertown v0.9.1 to the latest development skin.

**Comment by poblabs** [comment]
I haven't tested the skin with weewx 3.8.2 yet. There could be a function inside that'll only work with 3.9.1 - that could be the problem. 

To confirm, you've cleaned up all the old Belchertown skins and Highcharts subskin and settings, then restarted weewx?

**Comment by Stormtracker017** [comment]
Yes, I cleaned up all the old information pertaining to Belchertown and Highcharts.  Then restarted Weewx.

**Comment by poblabs** [comment]
I just installed a fresh weewx 3.8.2 and I am able to replicate this error. 

I will see if there is a work around for legacy versions, but if not this may mean you'll have to upgrade to the latest version of weewx.

Let me do some investigation on the error

**Comment by Stormtracker017** [comment]
If there is a work around great.  If planning to use Belchertown 1.0 skin, maybe just put a minimum version requirement for weewx of 3.9.1 or greater.

**Comment by poblabs** [comment]
The more I peel back the layers on this onion, the more it's realized that weewx 3.9.1 is needed. The more I remove functions, the more others popup as being "missing". So I'll have to put in that warning somewhere. 

I assume your other system that you had 1.0 on was a weewx 3.9.1 system?

**Comment by Stormtracker017** [comment]
Pat 
My other RPI is running weewx version 3.9.1 with Belchertown Skin version 1.0rc9.2.  I'm going to upgrade this RPI from Weewx 3.8.2 to version 3.9.1. Then re-install the latest development files.  Then will test out the refresh timers for the inc files.  You can close this issue.

**Comment by poblabs** [comment]
Sounds good! I've put in the warning too so others who are on 3.8.2 will get a warning.
