### ISSUE TITLE
MQTT doesnt work when https active on my site

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#142]
I try to secure my site, changing value belchertown_root_url = http://meteo.payrastre.fr by belchertown_root_url = https://meteo.payrastre.fr and now site doesn't catch mqtt datas. When i come back, mqtt work again. Any idea ?

On my dev site unsecure that's works... http://www.payrastre.fr/weewx/belchertown/ it's same mqtt datas from meteo.payrastre.fr port 9001 topic is weather

**Comment by poblabs** [comment]
If I recall correctly  Your MQTT needs to be behind ssl as well. Otherwise
your browser will block it for mixed secure sources.

**Comment by olpayras** [comment]
Thanks for this fast reply Pat.

You're surely right. I didn't think to that. I'll try this tomorrow cause it's late here. Also will try with edge at work, perhaps its more permissive ?  No have windows here...

**Comment by poblabs** [comment]
FYI - this is exactly what's wrong. You need to switch to a secure MQTT server if you want HTTPS. 

Not sure if Edge will work - it's a secure/non-secure JavaScript CORS restriction I think. 

![image](https://user-images.githubusercontent.com/3484775/58441085-0c906d00-80ad-11e9-94b8-652f1d944a80.png)

**Comment by poblabs** [comment]
Going to close this since it's not a Belchertown skin problem. I think once you get your MQTT broker setup with SSL, you'll be in business.  😃

**Comment by olpayras** [comment]
At work now, on edge it's the same. I'm going to put SSL on mqtt server. Perhaps, we should had this information to the readme, that if the site is ssl, mqtt sould be ssl too.

**Comment by olpayras** [comment]
That's good now, my site is having real datas and with ssl enabled.
