### ISSUE TITLE
Darkmode is activated before sunset

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#144]
Hello Pat
Something weird is going on. Darkmode is activated before sunset.  Can you verify if some previous change could affect this behaviour.
Thanks!

**Comment by norecords** [comment]
Hi there,
I can reproduce the same @HoracioDos  dark mode is activated also few minutes before sunset.
Cheers.

**Comment by 41south** [comment]
I understood dark mode was activated in the same hour as sunset, so it may
be before of after actual sunset?

**Comment by HoracioDos** [comment]
In my case, It is at least half an hour before sunset and I don't get romantic! LOL

**Comment by poblabs** [comment]
Only way to best tell what's going on is to turn on belchertown_debug, then open the Chrome Developer tools and see what the output is for "Auto Theme" logging. 

![image](https://user-images.githubusercontent.com/3484775/58515404-b2f27600-8172-11e9-9bc6-cdfe1303f859.png)

**Comment by poblabs** [comment]
To make sure we all understand: dark mode is activated when the hour of sunset is present. So if sunset is 19:50, dark mode will be enabled at 19:00:01 as an example.

**Comment by HoracioDos** [comment]
Excellent! It allows us to do a triage first before  opening an issue. Thanks!

**Comment by poblabs** [comment]
I tried to put a lot of good information in the Chrome debugger 😃

**Comment by poblabs** [comment]
What was the issue?

Side note: To turn on JavaScript debugging it is a lot of effort to change skin.conf, restart weewx, run a wee_reports. I think I will make a URL variable to enable it. Like http://192.168.x.x/?debug=true that way we can run quick debug help. I will commit that thanks to this issue 👍

**Comment by HoracioDos** [comment]
It was about 5:30 PM or earlier today and dark mode was activated. My sunset time is 5:52 PM. I thought it was too early to be triggered.
