### ISSUE TITLE
About.inc not generating correctly

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#146]
I edited the about.inc.example as I wished, and then saved it as about.inc. I stopped and restarted weewx, but it was still the old about.inc. 
I read though the about/index.html and noticed its an if statement, so i deleted the about.inc.example. Stopped / started weewx, nothing still the old page. 
Oh! the page is probably there. Deleted everything in the weewx html folder. let it regenerate everything. Still! old about.inc
Deleted the about folder, left everything else, stop/start weeex, now I get a folder, but no file inside. not sure whats going on. 
Deleted the entire www/weewx/belchertown folder, let it rebuild, again. builds about folder but its empty. checked the file name about.inc

**Comment by poblabs** [comment]
Interesting. In my personal setup I have the about.inc.example AND the about.inc. The page is rendering the about.inc as part of the page generation. 

To make sure - are you letting weewx run a report generation via wee_reports or an archive period? A start/stop doesn't re-create the website immediately. That just reloads all the configs. There's still a delay for the page to be created and copied. You can see that in your syslog with something like

```
May 28 19:41:57 weewxlab wee_reports[25975]: Belchertown Extension: version 1.0rc9.3
May 28 19:41:58 weewxlab wee_reports[25975]: copygenerator: copied 32 files to /var/www/html/belchertown
```

**Comment by slvrscoobie** [comment]
no i have a 2 min archive interval, so i just wait the 2 minutes to let it recreate everything through the report generation. 
doh, just read the log, and noticed I dont have your battery status in mine, so it failed on finding that data... now it works!

**Comment by poblabs** [comment]
Ah ha, that'll do it! Glad you caught it

**Comment by olpayras** [comment]
Yes mine sometimes fails when it can't catch battery values. I have some log errors. I think my Rpi is a bit overcharged, cause running weewx, mqtt, domoticz, and an opentherm Gateway… I think I sould buy another just for weather datas.
