### ISSUE TITLE
style different after mqtt refresh

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#147]
@poblabs 
Hi Pat,
I don't know if it happened before, but on page load, °C is big and after mqtt refresh it's in small.
I saw in console that after refreshing a new class is loaded: 
`<sup class="tempsup"> °C</sup>`
![issue-belchertown](https://user-images.githubusercontent.com/12499787/58632012-a9891b00-82e4-11e9-80db-d89602f0e5a3.jpg)

**Comment by poblabs** [comment]
Yes this is because [in skin.conf there's no `sup` for degree_C](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/skin.conf#L371) (nor degree_F either) because this would affect all the degree_C. But in the MQTT code it adds the `sup`.
