### ISSUE TITLE
MQTT and live data

### ISSUE THREAD

**Issue by the-butterfry** [poblabs/weewx-belchertown#150]
Searching through the issue history here I see relevant topic here. But unfortunately, i'm able to tick all the boxes that you guys covered over in #16 and still no connection.

I'm having no trouble getting Realtime weather data from websocket it appears. I can see the loop flowing through when I subscribe to my topic. The part I'm wondering about, is your skin.conf file. In your tutorial, you never mention changing the websocket port to 9001 after enabling websockets within mosquitto. I think this is the intent of the 'mqtt_websockets_port' line right? Ok, I did that.

Still debugging here.. not sure why your skin isn't picking up the live feed. ACLs seem correct - login to publish works, ports 1883 and 9001 open on mosquitto start.. 

Can you validate for me when you hit refresh on weewx frontend that you get a corresponding log entry for websockets connection with 'tail -f /var/log/mosquitto/mosquitto.log'. the only connections I'm seeing is onto 1883, not my websockets port.

**Comment by the-butterfry** [comment]
GAHHH!! stupid mosquitto. it got me again. another full reboot and it started flowing. Guess you can't emphasize that enough. Don't trust your configs, reboot to get mosquitto working after config changes.

**Comment by poblabs** [comment]
Awesome! Glad that helps. 

Side note: I just released version 1.0, so since you're in the thick of it, go ahead and upgrade 😃  Version 1.0 has a lot better debugging info, as well as awesome chart control. You can read about it here: https://github.com/poblabs/weewx-belchertown/releases

**Comment by the-butterfry** [comment]
I've worked with mosquitto for years, seems I never learn. i'll upgrade this afternoon congrats!
I've got one other struggle with Belchertown that i'll take up in another issue too. I'm trying to get it to play nice with hassio/HA's iframe feature so I can display this on the main Lovelace frontpage. I saw somewhere you mentioned you use HA too... more later

**Comment by poblabs** [comment]
Yep I do use HA, but my lovelace skills are so severely lacking. Mostly I'm just running default lovelace. I've been more focused on the Belchertown 1.0 then I have with hass! Guess I need to spend some time with it? The iframe would be neat - hadn't ever thought of that.

**Comment by the-butterfry** [comment]
![image](https://user-images.githubusercontent.com/37050797/58751880-ff330400-8459-11e9-99c6-ed88f1d87d0a.png)
it's pretty nifty.. the trick is getting both inside and outside URLs to work. I seem to only be able to get one or the other working. Part of it is the way you do your links in belchertown. if I proxy or port forward through the internal IP url, you can't hit the site outside of HA.. and visa versa. I'm about to give it another go later with my personal setup, since I have a proper router and reverse proxy sitting out on the edge. I've tried it with one hand tied behind my back using my friends house with their ISP issued modem thing and hassio reverse proxy manager addon.

**Comment by poblabs** [comment]
Yeah the `belchertown_root_url` is a pain but it's a necessary evil since I'm trying to have pretty urls (e.g. site/about, site/graphs) rather than "ugly urls" with `.html`.
