### ISSUE TITLE
Upgrade to 1.0 - Locale bug (?)

### ISSUE THREAD

**Issue by the-butterfry** [poblabs/weewx-belchertown#151]
I just tried to upgrade to 1.0. this is the output of a manual wee_reports run

`Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 127, in get_extension_list
    system_locale_js = system_locale.replace("_", "-") # Python's locale is underscore. JS uses dashes.
AttributeError: 'NoneType' object has no attribute 'replace'
`

**Comment by poblabs** [comment]
Yeah looks like a locale bug. On your command line, type `locale`, what does it output?

**Comment by the-butterfry** [comment]
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

**Comment by poblabs** [comment]
A little different than mine (see below) - wonder if that's whats going on. To confirm while I try this on my own, have you removed all the old skin files before installing this?

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by the-butterfry** [comment]
yep, step by step. all else when smoothly

**Comment by the-butterfry** [comment]
It's odd, I've explicitly set the local as en_US.UTF-8. not sure where all the C is coming from.
This is rasbian stretch btw

**Comment by poblabs** [comment]
Sometimes locales like to be problems 😃 C is the default locale if your override wasn't applied. I just don't know how to switch mine to C, so I have a little research to do. When you run `sudo dpkg-reconfigure locales`, C isn't an option in the list, but is an option as a default but it doesn't look like it applies it.

**Comment by poblabs** [comment]
For giggles, in skin.conf change `belchertown_locale = "auto"` to `belchertown_locale = "en_US.UTF-8` and restart weewx, then run `sudo wee_reports` and see if there's any errors in syslog.

**Comment by the-butterfry** [comment]
yeah, if I knew how to make it stick, or where it's pulling it from i'd change it manually.

I see that auto there in the extension around 127... this should bypass that check.... and yeap that let it finish.

**Comment by poblabs** [comment]
Ok cool. Glad it works, but still a problem. I was able to get C to stick by unchecking everything, setting C in the default screen then rebooting. But.... it compiled for me with no problems. More research to do. 

```
root@weewxlab:~# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

```
Jun  1 18:26:01 weewxlab wee_reports[1623]: Belchertown Extension: version 1.0
Jun  1 18:14:15 weewxlab wee_reports[1623]: copygenerator: copied 32 files to /var/www/html/belchertown
```

**Comment by the-butterfry** [comment]
you still have .UTF-8 though. mine was just straight up C

**Comment by poblabs** [comment]
You also have a LANGUAGE set, and I don't. 

I'm working on an Ubuntu VM. Maybe I need to get a Pi setup and try it that way.

**Comment by the-butterfry** [comment]
even the little Pi Zero W would be a fine fit I think. in it's final iteration i'll be moving the weewx setup over to one I think. Just too many web services running on this 3b+. your skin doesn't like to be run on non standard ports where I have to use a reverse proxy to get to it. Especially in that iframe of HA where it's running on the same server and rendering the iframe on a different port.. 

that said, it's looking great! congrats on a really clean and well organized little skin.

**Comment by poblabs** [comment]
Thanks! It's been a lot of work - always more to do but I'm pretty happy with the 1.0 release. 

A word of caution on the Pi Zero - early on chart generations were taking a long time (some were upwards of 5 minutes). Not enough horsepower. Since then, everything's been re-written and some very bad code was found and deleted. So it might be a lot better - but if you find that chart generation is slow, the Pi Zero could be why.

**Comment by the-butterfry** [comment]
ahh interesting.. is there multiple threads in chart generation? yeah the 3b+ is a few hundred MHz faster.. but if generation isn't multi-threaded that would be the only real advantage to a full (heh) Pi.

**Comment by poblabs** [comment]
Chart generation isn't threaded (at least I don't think so). Weewx itself runs threads but as far as I understand it, the StdReport runs each report one after the other. Then Cheetah does its job on doing **a lot** of duplicated effort to output the html 😃  In 0.9 I made some changes to the Chart code, but Cheetah still made the charts 4 times (if i recall correctly). In 1.0 I moved the charts to its own Generator, and Cheetah only calls that generator once. So I think it should be a lot better. Feel free to give it a try on the Pi Zero (I don't have one) - I'll be curious how it does!

**Comment by biltmorelaker** [comment]
I've been running all of the V1 release candidates on a pi zero W on my production instance (https://wx.kutzenco.com) with no issues! I'll be installing the final V1.0 shortly and expect no problems.

**Comment by HoracioDos** [comment]
V1 works fine and all previous rc run perfectly in raspberry pi modeling b. Even if generate a lot of graphs and you have to ftp everything to a web hosting provider like I do.

**Comment by the-butterfry** [comment]
cool, thanks for the info guys.. i'll report back in a different thread so others can find it with my results.

**Comment by HoracioDos** [comment]
if you need more horsepower you always have the chance to overclock the pi with raspi-config

**Comment by poblabs** [comment]
@HoracioDos and @biltmorelaker if you're on Raspberry Pi, can you run `locale` on the command line and paste the results?

**Comment by poblabs** [comment]
Here's a Pi of mine and it's locale (I never touched it so it defaulted to England's locale). Still it has something and not just `C`. 

```
pi@garagepi:~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by HoracioDos** [comment]
```
LANG=en_IE.UTF-8
LANGUAGE=
LC_CTYPE="en_IE.UTF-8"
LC_NUMERIC=es_AR.UTF-8
LC_TIME="en_IE.UTF-8"
LC_COLLATE="en_IE.UTF-8"
LC_MONETARY=es_AR.UTF-8
LC_MESSAGES="en_IE.UTF-8"
LC_PAPER=es_AR.UTF-8
LC_NAME=es_AR.UTF-8
LC_ADDRESS=es_AR.UTF-8
LC_TELEPHONE=es_AR.UTF-8
LC_MEASUREMENT=es_AR.UTF-8
LC_IDENTIFICATION=es_AR.UTF-8
LC_ALL=
```

**Comment by HoracioDos** [comment]
I never use C.UTF-8. I always choose lang_country.UTF-8

**Comment by poblabs** [comment]
I guess I'm trying to figure out if this is a bug, or if I need to update the error to say "C not supported, please select another locale" or something.

**Comment by HoracioDos** [comment]
> .... if I need to update the error to say "C not supported, please select another locale" or something...
I guess it would be the best for now until you can investigate further

**Comment by the-butterfry** [comment]
wish i knew how it got there. I dug all around on this pi to find C in locale files and nada

**Comment by biltmorelaker** [comment]
Here's mine:

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by poblabs** [comment]
I don't know how you set it either, but I'm at least able to replicate it. 

```
root@weewxlab:~# LC_ALL=C
root@weewxlab:~# LANG=C
root@weewxlab:~# export LC_ALL LANG
root@weewxlab:~# locale
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

root@weewxlab:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 127, in get_extension_list
    system_locale_js = system_locale.replace("_", "-") # Python's locale is underscore. JS uses dashes.
AttributeError: 'NoneType' object has no attribute 'replace'
```

So now I can work on fixing it and/or putting up a message that says to use another locale.

**Comment by the-butterfry** [comment]
What happens when you set it back? Does it take? I believe I tried all that and it wouldn’t stick. Or maybe I didn’t....

**Comment by poblabs** [comment]
@the-butterfry Try this attached file below. Copy it to your `bin/user` folder - overwriting the other one. Set `belchertown_locale` back to auto in skin.conf, restart weewx and try a `sudo wee_reports`. You should get an alert in syslog about unable to find locale, but the skin should complete without error. 

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/3244360/belchertown.zip)

**Comment by poblabs** [comment]
No it won't stick that way - it'll only persist for my session. That's all I needed to figure out what was happening. A proper way to set locale on the Pi would be through the `raspi-config`, go through the settings and then reboot.

**Comment by poblabs** [comment]
That last test belchertown.py won't work. It's breaking the MQTT Websockets. So instead try this version. 

Basically if locale can't be found then force en_US. This *probably* isn't a fail safe idea either, but let's try it out. 

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/3244367/belchertown.zip)

**Comment by Stormtracker017** [comment]
Pat
Here is info from rpi running V1.0

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by the-butterfry** [comment]
I did originally run the raspi-config to set locale (and 10 times later to try to fix it).. I’m out getting dinner atm, but I’ll try it on the pi in question when I get home

**Comment by the-butterfry** [comment]
@poblabs that worked. Set `belchertown_locale` back to auto with the new file and wee_reports ran fine.

**Comment by ebonzl** [comment]
Hi there, just upgraded - am getting the same error, but I am running on a Pi hardware with OpenWRT as the OS (long story, but a rock solid configuration for my setup here) 

Unfortunately OpenWRT doesn't have a locale command. - so am unable to see what the output is, however your workaround of setting "en_US.UTF-8" works for me also. 

Am in NZ running metric, no side effects I can see so far..

**Comment by poblabs** [comment]
Thanks guys, I'll commit this with the en_US as the fallback default.
