### ISSUE TITLE
[StdArchive]  - archive interval now required

### ISSUE THREAD

**Issue by ebonzl** [poblabs/weewx-belchertown#152]
After upgrading to v1.0 was receiving this error when manually running wee_reports:

Using configuration file /home/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/home/weewx/bin/weewx/reportengine.py", line 300, in start
    self.run()
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/home/weewx/bin/user/belchertown.py", line 131, in get_extension_list
    archive_interval_ms = int(self.generator.config_dict["StdArchive"]["archive_interval"]) * 1000
  File "/usr/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'archive_interval'

I use the HP1000 driver, as the hardware supports logging, I have always had the following lines remmed out in the [Std_Archive} section of weewx.conf:

# If the station hardware supports data logging then the archive interval
 # will be downloaded from the station. Otherwise, specify it (in seconds).
    # archive_interval = 300

I enabled the archive interval line , and restarted weewx, and the error went away.

Not sure if this is a bug really, but wasn't required in the older versions - I am also unsure how having it enabled affects my datalogger - so far all seems OK

Just thought I would let you know if anyone else brings this up

**Comment by poblabs** [comment]
Thanks! It's required for the gapsize, but I can (and should have) made it optional. (e.g. if no archive interval, then just use 300 as a default). I'll try something out and have you test it if you dont mind?

**Comment by poblabs** [comment]
I was able to replicate this myself by commenting out the archive_interval. So now the update I pushed uses 300 seconds for a fallback if archive_interval is removed. 

So, to try this out copy the contents of this file to your user/bin/belchertown.py file, put your weewx.conf back to your normal and restart weewx. You should be all set now

https://raw.githubusercontent.com/poblabs/weewx-belchertown/development/bin/user/belchertown.py

**Comment by ebonzl** [comment]
Yep that seems to have done the job

Much obliged :)
