### ISSUE TITLE
Investigate a potential method to remove belchertown_root_url

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#155]
If I specify `.` as the `href` in a URL, it'll work for the home page. Once you're on a sub page (like graphs, about, records, etc.) the `.` in the href will break because the file doesn't live in that directory. 

So using some Cheetah code, perhaps I can specify `.` for links when on the homepage and `..` for for links when on sub pages. 

Example: 

When on homepage:
`<script type='text/javascript' src='./js/belchertown.js?1559565644'></script>`

When on sub page use:
`<script type='text/javascript' src='../js/belchertown.js?1559565644'></script>`

**Comment by poblabs** [comment]
I have a working prototype of the skin without the `belchertown_root_url`. This gives the skin more flexibility in where you install it without having to explicitly define the url. 

### Considerations:
* The determination of using `.` vs. `..` in the links relies on the URL page name (e.g. /about). This is hard coded and if there's a typo somewhere, the links will break. 
    * If adding new pages, this array will need to be updated. 
    * If adding pages under pages, this complexity changes and those links will need to become `../..`. Something to keep in mind for future. 
* Certain aspects, like the Facebook/Twitter share buttons will need to rely on a new social setting in Extras for the URL. 

After 1.0.1 releases, I'll push this to the 1.1 development branch for testing.

**Comment by 41south** [comment]
My site has 2 url's - 41south.net.nz and 41south.nz Both appear to work well with the 1.1b2 release

**Comment by poblabs** [comment]
Great news!

**Comment by the-butterfry** [comment]
awesome! looking forward to trying it out. I was away for the weekend and the SD card on the Pi Zero started going corrupt. Starting over :/

**Comment by poblabs** [comment]
Great news! For what it's worth, the station_url isn't used by the skin anymore except for the mobile version "Add to Homescreen" option. 

I may even try the HA config as well 😄

**Comment by biltmorelaker** [comment]
It works for me - yay!
I am, though, experiencing a minor anomaly. I have NGINX running on my weewx pi. When I browse to the site being served on the pi, my Windy plot looks like this:
![Screenshot_2019-06-13 Biltmore Lake, NC Weather Conditions](https://user-images.githubusercontent.com/44727343/59446298-39dc5b00-8dcf-11e9-94d3-9d31297852d4.png)

These same files are being rsynced to my Digital Ocean hosted web page where I am also running NGINX. But looking at the site on Digital Ocean, my Windy plot looks like this:
![Screenshot_2019-06-13 Biltmore Lake, NC Weather Conditions(1)](https://user-images.githubusercontent.com/44727343/59446465-8cb61280-8dcf-11e9-92a1-89419a97ad52.png)

Notice the blue dot enclosed in a white circle that Windy puts in for my current location. It is offset (ever so slightly) in the two plots. Any idea why?

**Comment by poblabs** [comment]
No, no idea on that one. Look slike a windy thing since I’m not styling that dot. Anything inside the iframe (windy.com), stays inside the iframe.

**Comment by norecords** [comment]
@poblabs  v 1.1b2 works like a charm :)

**Comment by poblabs** [comment]
Closing this - thanks everyone for the feedback! If you find a new issue with it please let me know
