### ISSUE TITLE
Performance observations on RPi Zero W

### ISSUE THREAD

**Issue by the-butterfry** [poblabs/weewx-belchertown#156]
In #151 there was a ot discussion about performance on the smaller RPi Zero W. I set up a dedicated 'W' to try it out. The only thing it's doing is running a dual wifi hotspot, intercepting (pcap sniff), publishing and running weewx/Belchertown. 

There is certainly a performance hit vs a full RPi.. but nothing that is too much for it. When reports run the CPU will load up, and takes ~45s to run a full wee_reports run.  I think as with all Pi's, a high performance SD card is a must. Otherwise, here's the htop, notice the load averages are fairly stable.
![image](https://user-images.githubusercontent.com/37050797/58820681-1c95d880-85e8-11e9-95a7-1d98be19562c.png)

**Comment by poblabs** [comment]
Closing this since it's not an issue - but really a reference we can look back on in future if needed! Thanks for the information!
