### ISSUE TITLE
Daily Charts not displaying lines 

### ISSUE THREAD

**Issue by SeattlePaulus** [poblabs/weewx-belchertown#158]
Just loaded version 1.0 of the belchertown skin with Weewx 3.9.1.  The issue that I am having is that all the graphs for the daily weather do not show any of the lines for the data.  The value points are available when tracing over the graphs but no underlying lines.  When I look at the same charts in Week, Month and Year the lines are displayed properly.  I am using the default config data.

**Comment by poblabs** [comment]
A link to your site would be helpful. My guess is the default gapsize of 300 seconds doesn't match your archive_interval from weewx.conf. 

1. What is your URL?
2. What is your weewx.conf archive_interval?

**Comment by SeattlePaulus** [comment]
The gapsize was the issue, changed this parameter to the one being used and now the graphs are displaying correctly. 

http://24.17.52.89/Weather/burien/ <http://24.17.52.89/Weather/burien/>

Thanks

Paul

**Comment by poblabs** [comment]
Great, glad it's working!

**Comment by djdunc** [comment]
Hi, i am having the same issue on site http://drdunc.duckdns.org/weewx/ (1.0.1 Belchertown and Weewx 3.9.1 running on an Intel Edison with Debian). I have checked weewx.conf for archive_interval which is 300 and checked the graphs.conf which has gapsize = 300000 for daily reports. Any other places to look?

**Comment by poblabs** [comment]
@djdunc Your reports look to be 30 minute intervals. If you hover your mouse over, you'll see the points are 30 minutes apart. 

So you will need to change your gapsize to 30 minutes in milliseconds, or 1800000

**Comment by djdunc** [comment]
Ah many thanks - I was looking in the wrong place! I have changed the report interval on the Vantage hardware from 30 to 5 mins using your wee_device --set-interval utility. And thanks for the great support as always!

**Comment by mgraupe** [comment]
Hello. 
I am having the same issue (running WeeWX version: 5.1.0; Belchertown Skin Version: 1.3.1; with Debian 1:6.12.34-1+rpt1~bookworm on a raspberry pi), i.e., the daily charts not displaying lines even though the data is there (noticeable when hovering with the mouse). 
The gapsize parameter in graphs.example.conf is set to 300, which is correct as the points are in the day plot are spaced by 5 min (and I saw that gapsize is not given in minutes).
Is that the correct file where to change the gapsize? Anything else I should pay attention to?

Thanks in advance. 
Best, 
Michael
