### ISSUE TITLE
xaxis_groupby graphs show wrong month if date is day/month?

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#159]
I'm not sure who owns https://wwx.centratus.com/weewx/ but I happened to see data for the Average Climatological Values for This Year chart show data for July. It's not July yet so this doesn't make sense. 

What does make sense is this website is using day/month format. Today is the 7th day of the month (for NZ). So is it using the day as the month when xaxis_groupby charts date format is in dd/mm?

**Comment by 41south** [comment]
Good catch! It's happened on my site too, data in July

**Comment by poblabs** [comment]
Which chart of yours shows July? They all look like June right now.

**Comment by 41south** [comment]
Haha, whoops, too little sleep. I looked at the date in my NOAA reports and
read it as the month, doh! As you were.

**Comment by poblabs** [comment]
Ok cool, no problem. I think it's only affecting the xaxis_groupby charts (which came out around 1.0rc8 I think)

**Comment by poblabs** [comment]
hmm, using the `tooltip_date_format = "DD/MM"` didn't change anything. Setting locale to NZ didn't change anything. 

I'm not able to replicate this. So I am thinking this is a problem with that site's database since their data is showing 7 values (one for each month). 

Because there's 7 data points in their chart data, this doesn't appear to be a tooltip, a locale or a time formatting issue. 

```
        "data": [
          12.600000381469718,
          9.69999980926513,
          9.4,
          4.199999809265142,
          4.19999980926515,
          1.7999999523162755,
          18.000000000000014
        ],
```

I'm going to say False Alarm for now.
