### ISSUE TITLE
Areaspline YAxis scale graph

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#161]
Hello Pat
I can't find a way to make the amplitude bigger between max, avg and min barometer observation if plot type = areaspline. If I set type = spline, all lines are automatically scaled and everything is nice and easy, but I have a lot of trouble with Y Axis scale for areaspline. I already used softmin/max, tickinterval, but nothing seems to work fine.
```
[[chart5]]
        title = Presión Barométrica
        type = areaspline
        [[[barometer_max]]]
            name = Presión Barométrica Máxima
            observation_type = barometer
            aggregate_type = max
            color = "#B2DF8A"
            yaxis_min = 1000.0
            yaxis_max = 1040.0
            fillOpacity = 0.5
        [[[barometer]]]
            observation_type = barometer
            aggregate_type = avg
            color = "#BECC00"
            yAxis_tickInterval = 0.01
            yaxis_min = 1000.0
            yaxis_max = 1040.0
            fillOpacity = 0.5
        [[[barometer_min]]]
            name = Presión Barométrica Mínima
            observation_type = barometer
            aggregate_type = min
            color = "#7CB5EC"
            fillOpacity = 0.5
            yaxis_min = 1000.0
            yaxis_max = 1040.0
```
![image](https://user-images.githubusercontent.com/4549674/59070358-d6af6d80-8890-11e9-8ecd-c8578879bdd1.png)

**Comment by poblabs** [comment]
I don't know what you mean by amplitude. Can you show example of a working one? I may not know the answer to this one either, but I can read the highcharts documentation when I have time (couple days?).

**Comment by HoracioDos** [comment]
Hello Pat
> Can you show example of a working one? 

Do you refer to this:
https://www.highcharts.com/demo/areaspline
or to this: 
https://climacolegiales.com.ar/graphs/?graph=month
Forget about time, I can wait all the time you need.

**Comment by poblabs** [comment]
Ok I will take a look at those

**Comment by poblabs** [comment]
I just thought, have you tried your yaxis tickinterval setting? Try
something like 0.01? To make the yaxis ticks farther apart?

**Comment by HoracioDos** [comment]
I already tried yAxis_tickInterval = 0.01
When you have time, look at this spline plot.(No Y Axis Min/Max, no tick interval). Everything is fine. If want to do the same with areaspline I can't get the same.
```
    [[chart5C]]
        title = Presión Barométrica
        type = spline
        [[[barometer_max]]]
            name = Presión Barométrica Máxima
            observation_type = barometer
            aggregate_type = max
            color = "#B2DF8A"
        [[[barometer]]]
            aggregate_type = avg
            color = "#BECC00"
        [[[barometer_min]]]
            name = Presión Barométrica Mínima
            observation_type = barometer
            aggregate_type = min
            color = "#7CB5EC"
```
![image](https://user-images.githubusercontent.com/4549674/59071410-dca74d80-8894-11e9-9c93-8fa52de870ba.png)

**Comment by poblabs** [comment]
The lines look the same to me except the area is filled in... ? I must be
missing something

**Comment by HoracioDos** [comment]
Same plot with areaspline as above (No Y Axis Min/Max, no tick interval). There must be something with the stacking option.
```
    [[chart5D]]
        title = Presión Barométrica
        type = areaspline 
        [[[barometer_max]]]
            name = Presión Barométrica Máxima
            observation_type = barometer
            aggregate_type = max
            color = "#B2DF8A"
            stacking = "normal"
        [[[barometer]]]
            aggregate_type = avg
            color = "#BECC00"
            stacking = "normal"
        [[[barometer_min]]]
            name = Presión Barométrica Mínima
            observation_type = barometer
            aggregate_type = min
            color = "#7CB5EC"
            stacking = "normal"
```
![image](https://user-images.githubusercontent.com/4549674/59072088-a0c1b780-8897-11e9-9924-53f04a3a0cbf.png)

**Comment by poblabs** [comment]
I still feel like this image as a `line` looks right.  Right?

![image](https://user-images.githubusercontent.com/4549674/59071410-dca74d80-8894-11e9-9c93-8fa52de870ba.png)

Now if you fill in the area beneath the line, you use `areaspline` right? That's what this looks like exactly. Same chart but with fill

![image](https://user-images.githubusercontent.com/4549674/59070358-d6af6d80-8890-11e9-8ecd-c8578879bdd1.png)


Is your concern about the 3 lines or is your concern how high the yaxis is using areaspline (e.g 1041)? 

I have seen area charts do some weird things with the height of the yaxis

**Comment by HoracioDos** [comment]
> Is your concern about the 3 lines or is your concern how high the yaxis is using areaspline (e.g 1041)?

That's right, I can't make better. I don't expect you can fix everything. I'll stick to graphs that work.
Thanks again!

**Comment by poblabs** [comment]
Well if we can replicate it in jsfiddle, then we can ask the Highcharts developers. 

So the issue is the high yaxis?

**Comment by HoracioDos** [comment]
Yes, Look at the Y axis when the plot is spline. It's perfectly fine. There is no need to set Y Axis min or max. It seems that area and areaspline always need a prefined Y Axis minimum. If it's not set, it starts from 0. Also tick interval doesn't work in these graph types.

**Comment by poblabs** [comment]
@HoracioDos I think i have replicated this in this jsfiddle found here. can you take a look to see if it's accurate? https://jsfiddle.net/obrienlabs/pjs3xm40/

If so we can use this to play with settings. You update the JavaScript on the bottom left, then click Run at the top. 

I see you are setting a yaxis max to 1040, so this is why it is showing 1040. but if you remove 1040, it stays at 1040. 

I agree, if you remove y axis min, then it goes to 0 - this could be how the area charts are designed to work?

**Comment by HoracioDos** [comment]
> I agree, if you remove y axis min, then it goes to 0 - this could be how the area charts are designed to work?

Your implementation works just like jsfiddle does. I was mistaken because I expected a different behavior from HighCharts. It could take the lowest and highest value from the data serie and adjust Y axis accordingly if no min or max axis value is defined.

**Comment by poblabs** [comment]
I think I may have found it [in this forum post](https://www.highcharts.com/forum/viewtopic.php?t=37873):

```
plotOptions: {
    areaspline: {
        threshold: null
    }
}
```

Updated jsfiddle here: https://jsfiddle.net/obrienlabs/pjs3xm40/7/

No y axis min, no y axis max and it looks like what I think you want?

![image](https://user-images.githubusercontent.com/3484775/59104555-e0bc8500-88ff-11e9-9ec4-97f9d9a592f5.png)

**Comment by HoracioDos** [comment]
> No y axis min, no y axis max and it looks like what I think you want?

This is exactly what I want!!! So  `threshold: null` is the missing property that I needed.
I can't thank you enough for taking the time to solve it

**Comment by poblabs** [comment]
I think i might need to set this as a belchertown.js default. When I try the below config it doesn't work because it's interpreting the null to be a string "null". This makes the areaspline turn into a line. 

```
    [[chart11]]
        title = Temperature
        type = areaspline
        [[[barometer_max]]]
            zIndex = 1
            observation_type = barometer
            aggregate_type = max
            threshold = null
        [[[barometer]]]
            threshold = null
        [[[barometer_min]]]
            observation_type = barometer
            aggregate_type = min
            threshold = null
```

![image](https://user-images.githubusercontent.com/3484775/59105427-e7e49280-8901-11e9-836d-e2c65306a901.png)

**Comment by poblabs** [comment]
This worked for me. @HoracioDos try it and let me know?

`softThreshold = 1` which sets it to true. 

https://jsfiddle.net/obrienlabs/pjs3xm40/12/

```
    [[chart11]]
        title = Temperature
        type = areaspline
        [[[barometer_max]]]
            zIndex = 1
            observation_type = barometer
            aggregate_type = max
            softThreshold = 1
        [[[barometer]]]
            softThreshold = 1
        [[[barometer_min]]]
            observation_type = barometer
            aggregate_type = min
            softThreshold = 1
```

![image](https://user-images.githubusercontent.com/3484775/59105705-82dd6c80-8902-11e9-83ca-f1da5cdb469e.png)

**Comment by poblabs** [comment]
Not sure I trust the reliability on this. So I will make it a default belchertown.js setting for areaspline

**Comment by HoracioDos** [comment]
Hello Pat
It works!! Also for `type = area` plots. I don't know why I can't get the same colors as yours. Did you set some opacity control somewhere? 
```
    [[chart5]]
        title = Presión Barométrica
        type = areaspline
        [[[barometer_max]]]
            zIndex = 1
            name = Presión Barométrica Máxima
            observation_type = barometer
            aggregate_type = max
            color = "#9DC8F1"
            softThreshold = 1
        [[[barometer]]]
            observation_type = barometer
            aggregate_type = avg
            color = "#596372"
            softThreshold = 1
        [[[barometer_min]]]
            name = Presión Barométrica Mínima
            observation_type = barometer
            aggregate_type = min
            color = "#82CA7B"
            softThreshold = 1
```
![image](https://user-images.githubusercontent.com/4549674/59107777-bbd00e00-890f-11e9-884f-0c48bda28fb2.png)
```
    [[chart5B]]
        title = Presión Barométrica
        type = area
        stacking = "normal"
        [[[barometer_max]]]
            zIndex = 1
            name = Presión Barométrica Máxima
            observation_type = barometer
            aggregate_type = max
            color = "#9DC8F1"
            softThreshold = 1
        [[[barometer]]]
            aggregate_type = avg
            color = "#596372"
            softThreshold = 1
        [[[barometer_min]]]
            name = Presión Barométrica Mínima
            observation_type = barometer
            aggregate_type = min
            color = "#82CA7B"
            softThreshold = 1
```
![image](https://user-images.githubusercontent.com/4549674/59107820-d86c4600-890f-11e9-92fd-eb244602c5f9.png)

**Comment by poblabs** [comment]
No I didn't set opacity control. Those screenshots those were using the default colors from Highcharts. I wonder if the black layer is making it look like a fuller opacity?

You can see in this fiddle I set the `fillOpacity: 1` for each series and it makes them look different. So I think the black layer may be playing tricks on our eyes?

https://jsfiddle.net/obrienlabs/pjs3xm40/13/

**Comment by HoracioDos** [comment]
I set `fillOpacity = 1` for each series and I removed al zIndex. If I use zIndex, it should be for every series and it must be set it in order  It looks quite good!! Thanks for color selection! LOL!
![image](https://user-images.githubusercontent.com/4549674/59109684-e15f1680-8913-11e9-9a12-8889a8603e2c.png)

**Comment by HoracioDos** [comment]
I removed makers from area and areaspline. Now they are hardly visible when they are disabled.
![image](https://user-images.githubusercontent.com/4549674/59114127-e1afdf80-891c-11e9-81d0-a3cbcc55a4da.png)

**Comment by poblabs** [comment]
Hmm.. they shouldn't be there at all on area or areaspline. 

![image](https://user-images.githubusercontent.com/3484775/59114327-f2f4ee00-8914-11e9-985a-2abdf142ff9f.png)

**Comment by HoracioDos** [comment]
I guess that I removed marker `enabled = false` after your commit. I'll roll back to your latest belchertown.js.tmpl

**Comment by HoracioDos** [comment]
That's right. My mistake. No markers at all now. I think it would good to add threshold property to area plots.
```
                    area: {
                        lineWidth: 2,
                        gapSize: '',
                        gapUnit: 'value',
                        marker: {
                            enabled: false,
                            radius: 2
                        },
                        threshold: null,
                        softThreshold: true
                    },
```

**Comment by poblabs** [comment]
Done!
