### ISSUE TITLE
Grammatical correction in almanac

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#162]
Total daylight | 9 hours, 18 minutes, 20 seconds53 seconds less_than_yesterday
-- | --

The underscores in less_than_yesterday should probably be removed

**Comment by 41south** [comment]
And also I believe that the term in here should be Elevation, not altitude?
![image](https://user-images.githubusercontent.com/1725001/59087030-a1ba1e00-8957-11e9-909d-e085f2dd209b.png)

**Comment by HoracioDos** [comment]
Hello @41south
I think It is a typo due to copy & paste. 
I had the same doubt about altitude. I think that altitud is the arc lenght and elevation is the degree angle.

**Comment by poblabs** [comment]
@41south @HoracioDos I updated the less_than_yesterday, thanks for that. 

For the Elevation, unsure on the correct terminology. The Almanac popup is borrowed (forked) from the [default weewx Seasons skin](https://github.com/weewx/weewx/tree/master/skins/Seasons). Tom and mwall built that one - so I'm leaning on their judgement as to the right word to use. Here's where it is in the Seasons skin:

https://github.com/weewx/weewx/blob/master/skins/Seasons/celestial.inc#L84-L85

**Comment by 41south** [comment]
Ok, I stand corrected, as strange as it sounds altitude is correct.

altitude:
the angular distance of a celestial body above or below the horizon
<http://asa.usno.navy.mil/SecM/Glossary.html#horizon>, measured along the
great circle passing through the body and the zenith
<http://asa.usno.navy.mil/SecM/Glossary.html#zenith>. Altitude is 90° minus
the zenith distance
<http://asa.usno.navy.mil/SecM/Glossary.html#zenith-distance>.

**Comment by poblabs** [comment]
Ok cool, at least we have some context on why the weewx folks picked that word! 😄 Closing this one now. Typo will be fixes in 1.0.1 release.
