### ISSUE TITLE
Translation of observation label

### ISSUE THREAD

**Issue by kalju** [poblabs/weewx-belchertown#164]
Hi,

Can not find anywhere the label pictured below to translate. Can somebody point it out for me? 

Thanks in advance.

<img width="412" alt="Screenshot 2019-06-07 at 23 21 39" src="https://user-images.githubusercontent.com/31128780/59131683-b4464e80-897b-11e9-967d-65f182d4a99d.png">

**Comment by poblabs** [comment]
Hi @kalju, this comes from DarkSky if I recall correctly. You'll want to specify your locale in DarkSky's format  in skin.conf's `darksky_lang` setting. Restart weewx once you've made that change. 

To force a download of the DarkSky information, go to your HTML directory, open the JSON folder and delete the darksky_forecast.json file, then wait for an archive period to pass for the skin to download a new copy.

**Comment by poblabs** [comment]
You can find the language options here: https://darksky.net/dev/docs

Search for language to find the section in their docs since there is no table of contents.

**Comment by kalju** [comment]
Hi @poblabs,

Changed _lang=[language]_ to _lang=et_ as per their documentation. Fixed the translation.
Thanks for the tip :-)
However,  as a result the DarkSky link to forecast `https://darksky.net/details/59.0431,24.5276/2019-6-9/si12/et` results now with error.

As far as I can understand (and I'm by no means developer) their documentation requires the usage of both _lang_ and _units_ 

Quote: 

> Note that units in the summary will be set according to the units parameter, so be sure to set both parameters appropriately

Using either `units` value `si` or `auto` results with error as above.

**Comment by poblabs** [comment]
What units will you be using so I can try and test this?

**Comment by kalju** [comment]
I'm using `si` units

https://darksky.net/details/59.0431,24.5276/ redirects to https://darksky.net/forecast/59.0289,24.4497/si12/en

**Comment by poblabs** [comment]
Interesting. My skin was linking you to `/si12/et`, but DarkSky wanted you at `/si12/en`. So I guess the end isn't the locale? Or they don't support the `/et` locale for daily forecasts? Hmm.

Does this work for you? https://darksky.net/details/59.0289,24.4497/2019-6-8/si12/en

**Comment by kalju** [comment]
Probably they do not support `et` for daily forecasts. Which is weird since changing to `et` fixed problem with the initial issue that I started the thread about :-)

**Comment by poblabs** [comment]
Yeah that is weird. Now I don't know what I should link to since I have no control on what their website does or doesn't do.

**Comment by kalju** [comment]
The link https://darksky.net/details/59.0289,24.4497/2019-6-8/si12/en works. Although the time and date formats are obviously wrong (`us`)

**Comment by poblabs** [comment]
That'll be acceptable for you, but for Spanish (example) they'll want the `/es` locale. 

If you have the Developer Key, I think it might make sense for you to email them asking for the daily forecast in the `et` locale. See if they will fix their website.

**Comment by kalju** [comment]
So now we know that not all supported languages are actually supported :-D
Well, since we can not do much atm let's close the issue.

**Comment by poblabs** [comment]
@kalju I agree. I think if you are using DarkSky and you have the developer key, it may make sense to contact them through your DarkSky portal to ask why `/et` doesn't work on daily forecast pages

**Comment by kalju** [comment]
@poblabs I've been looking for information about DarkSky developer key but found nothing. Could you point out where I can find it. I would talk to them about /et forecast pages.
Thanks in advance.

**Comment by poblabs** [comment]
If your site is showing the daily forecast link, then you have the darksky api key. If not, there's info on it here: https://github.com/poblabs/weewx-belchertown#darksky-api-optional and you can contact them through your developer login on their website.

**Comment by kalju** [comment]
Hi,

Already sent email describing the problem.
We will see :-)

/BRGDS

Kalju

---------------------------------------------------
What you can do, or dream you can, begin it: 
Boldness has genius, power and magic in it.
                                             — Goethe —

**Comment by kalju** [comment]
Got reply from Dark Sky:

"Our website does not support all the languages that our API does.”

Oh, well...

/BRGDS

Kalju

---------------------------------------------------
What you can do, or dream you can, begin it: 
Boldness has genius, power and magic in it.
                                             — Goethe —

**Comment by poblabs** [comment]
Wow! Hopefully they fix that
