### ISSUE TITLE
Issue with rain total when MQTT enabled

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#165]
On my wmr200 station, i activated MQTT to have real time datas. All is ok, but not rain. Rain total is overwritten by MQTT data. You can have a preview today [here](https://meteo.payrastre.fr). Total rain today is 1.0mm and not 0.1mm

**Comment by poblabs** [comment]
Interesting. I see you're running 1.0.1b4 so you're up to date. Can you update your skins/Belchertown/js/belchertown.js.tmpl with this latest one so I can see your MQTT messages in debug?

https://raw.githubusercontent.com/poblabs/weewx-belchertown/ce9e4761cf551ed98f41d58872c45b914656b98c/skins/Belchertown/js/belchertown.js.tmpl

Restart weewx, and let an archive interval pass for the update file to work. Let me know when that's done and I'll take a look again

**Comment by olpayras** [comment]
That's done.

**Comment by poblabs** [comment]
Looks like the value is wrong in your MQTT. MQTT is sending cm, but you want mm. 

You may want to check your MQTT configuration that you're using the right units?

`{"dayRain_cm": "0.1016"`

**Comment by 41south** [comment]
Pat does sound similar to my initial rain problem, where I had to make
changes to MQTT to get rain in mm?

**Comment by poblabs** [comment]
@41south I think so. The MQTT Metric settings use cm, right? So you did an override specific to rain? Are you talking about your fix from this issue? https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099

**Comment by 41south** [comment]
Yeah that's the one, not sure if that will help

**Comment by olpayras** [comment]
Yes right, i applied this to my MQTT section like it was written on #23 comment.

```
[[[inputs]]]
[[[[dayRain]]]]
name = dayRain_mm
units = mm
[[[[rainRate]]]]
name = rainRate_mm_per_hour
units = mm_per_hour
```

and now, it's allright. Thanks @poblabs & @41south.

I close this issue

**Comment by poblabs** [comment]
Great! Thanks @41south for the insight - I had forgotten about that one

**Comment by 41south** [comment]
Glad I could help, it doesn't come up very often as it's that slightly strange (well in some quarters!) combination of metric weather and rain in mm. Worth documenting in the Wiki perhaps or as an FAQ?
