### ISSUE TITLE
Images not reloading

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#166]
For some reason this isn't working for me

```
reload_hook_images = 1
            reload_images_radar = 300
            reload_images_hook_asi = 300
            reload_images_hook_af = -1
            reload_images_hook_as = -1
            reload_images_hook_ac = -1
```

Neither my radar image or the graphic in the ASI appear to load every 5 minutes. Is there a dependency that I missed?  I'm still on 1.0.1b3, I've got these settings in my weewx.conf [[[Extras]]]

**Comment by poblabs** [comment]
Both items are because of the way they are on your site. 

1. The radar isn't an image (like a jpg, gif or png). It's an iframe embed from windy.com. Windy's usually pretty good about refreshing this themselves automatically. 
2. The other item in the ASI, is also an iframe embed controlled by an external source. Right now iframe's don't have an automatic refresh option (only images do). I think I can add an iframe refresh though.

**Comment by 41south** [comment]
Ah right, no problems at all, if they don't work the way I have it set up I'll remove that again. I just saw it and thought it would be a good feature for a tablet I have running continuously. The Windy image definitely doesn't update without a refresh. Definitely one for down the bottom of the to-do list!

**Comment by poblabs** [comment]
I can add an iframe reload tomorrow that you can test out in the 1.1 beta build if you want!

**Comment by 41south** [comment]
Sounds great, I'm always up for a bit of beta testing :)

**Comment by poblabs** [comment]
I just pushed this change to the development branch. So this would mean installing 1.1 beta 1 to your system when you're ready. Same rules apply - have a backup and let me know how it goes 😃

**Comment by 41south** [comment]
Updated and running, will let you know how it looks

**Comment by 41south** [comment]
I can confirm that this is working for the Windy map. Will monitor my other embedded graphic in the ASAI section to see if that updates overnight

**Comment by 41south** [comment]
Morning Pat, both of the images are reloading fine. Many thanks for that update.
