### ISSUE TITLE
On sites with longer LOOP interval, the REC payload timestamp is more noticeable. 

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#169]
On sites where the LOOP interval is spaced out longer, the REC packet's timestamp can make the site look like it jumped back in time. This is because the archive packet (or REC) typically has a slightly older timestamp than the LOOP. 

Look into hiding the timestamp of the MQTT REC packet so that on sites which have longer LOOP intervals, this odd-ball timestamp isn't shown in the header.

**Comment by poblabs** [comment]
@olpayras I just updated a fix for the MQTT REC packet timestamp as mentioned in the user forum here: https://groups.google.com/d/msg/weewx-user/XwCNfrm6GRk/pUFUb0xfAgAJ

I have tested it on my development page. Give it a try and let me know!

**Comment by olpayras** [comment]
Thanks a lot Pat. I installed development branch on my dev [site](http://www.payrastre.fr/weewx/belchertown) and this is connected to my mqtt broker, so I can reproduce the error. But, it's the same :( event with the last commits from dev branch.

**Comment by poblabs** [comment]
@olpayras You don't have the latest belchertown.js.tmpl installed, so the update I committed isn't there. Replace it with this one: 

https://raw.githubusercontent.com/poblabs/weewx-belchertown/6e33e8d1b9a53065fa38343a3869a550ff7be48b/skins/Belchertown/js/belchertown.js.tmpl

**Comment by olpayras** [comment]
Ok, that's done, I ve restarted weewx. Next update in 2 mns.

**Comment by olpayras** [comment]
Looks good now. Thanks a lot.

**Comment by poblabs** [comment]
Great news!
