### ISSUE TITLE
Customize Windy

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#170]
Hello All,

Perhaps the question has already been asked, but how can we customise the windy Iframe in belchertown Skin.

I'd like Something like i see on @41south site.

![Capture](https://user-images.githubusercontent.com/49792600/59341132-996f3380-8d07-11e9-84d2-a9c781e921ce.JPG)

Thanks for your help.

**Comment by 41south** [comment]
You do this by selecting the options you want in the generator on the Windy
site.

https://embed.windy.com/embedmake.html

On that page select what you want to see and then copy the URL. Hope that
helps.

Colin @41south

**Comment by poblabs** [comment]
@olpayras Once you have your link ready how you want it, you can place it into the `radar_html` section of your Extras and it should override the default radar

**Comment by olpayras** [comment]
Thanks a lot, I am applying that now.
