### ISSUE TITLE
cheetahgenerator (No JSON object could be decoded)

### ISSUE THREAD

**Issue by the-butterfry** [poblabs/weewx-belchertown#171]
Just noticed this on report generation: this is a very stock install, I haven't expaneded the DB or anything more than the default. Seems to happen on every full report run

Jun 12 14:41:07 weather weewx[415]: copygenerator: copied 5 files to /var/www/html/weewx
Jun 12 14:41:08 weather weewx[415]: Belchertown Extension: version 1.0.1
Jun 12 14:41:08 weather weewx[415]: reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun 12 14:41:08 weather weewx[415]:         ****  No JSON object could be decoded
Jun 12 14:41:08 weather weewx[415]:         ****  Traceback (most recent call last):
Jun 12 14:41:08 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
Jun 12 14:41:08 weather weewx[415]:         ****      obj.start()
Jun 12 14:41:08 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
Jun 12 14:41:08 weather weewx[415]:         ****      self.run()
Jun 12 14:41:08 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
Jun 12 14:41:08 weather weewx[415]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jun 12 14:41:08 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
Jun 12 14:41:09 weather weewx[415]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
Jun 12 14:41:09 weather weewx[415]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
Jun 12 14:41:09 weather weewx[415]:         ****      default_binding)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
Jun 12 14:41:09 weather weewx[415]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/share/weewx/user/belchertown.py", line 636, in get_extension_list
Jun 12 14:41:09 weather weewx[415]:         ****      eqdata = json.load( read_file )
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/lib/python2.7/json/__init__.py", line 291, in load
Jun 12 14:41:09 weather weewx[415]:         ****      **kw)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Jun 12 14:41:09 weather weewx[415]:         ****      return _default_decoder.decode(s)
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Jun 12 14:41:09 weather weewx[415]:         ****      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jun 12 14:41:09 weather weewx[415]:         ****    File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Jun 12 14:41:09 weather weewx[415]:         ****      raise ValueError("No JSON object could be decoded")
Jun 12 14:41:09 weather weewx[415]:         ****  ValueError: No JSON object could be decoded
Jun 12 14:41:09 weather weewx[415]:         ****  Generator terminated
Jun 12 14:41:09 weather weewx[415]: copygenerator: copied 31 files to /var/www/html
Jun 12 14:41:18 weather weewx[415]: restx: MQTT: Published record 2019-06-12 14:41:00 PDT (1560375660)

**Comment by poblabs** [comment]
Looks like a problem with earthquake data. Any errors in syslog from an
hour or two ago about failed to download earthquake data or failed to save
earthquake data?

**Comment by the-butterfry** [comment]
Here's the first occurrence I found.
Jun 12 11:57:03 weather weewx[1198]: reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun 12 11:57:03 weather weewx[1198]:         ****  No JSON object could be decoded
Jun 12 11:57:03 weather weewx[1198]:         ****  Traceback (most recent call last):
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
Jun 12 11:57:03 weather weewx[1198]:         ****      obj.start()
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
Jun 12 11:57:03 weather weewx[1198]:         ****      self.run()
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
Jun 12 11:57:03 weather weewx[1198]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
Jun 12 11:57:03 weather weewx[1198]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
Jun 12 11:57:03 weather weewx[1198]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
Jun 12 11:57:03 weather weewx[1198]:         ****      default_binding)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
Jun 12 11:57:03 weather weewx[1198]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/share/weewx/user/belchertown.py", line 636, in get_extension_list
Jun 12 11:57:03 weather weewx[1198]:         ****      eqdata = json.load( read_file )
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/lib/python2.7/json/__init__.py", line 291, in load
Jun 12 11:57:03 weather weewx[1198]:         ****      **kw)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Jun 12 11:57:03 weather weewx[1198]:         ****      return _default_decoder.decode(s)
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Jun 12 11:57:03 weather weewx[1198]:         ****      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jun 12 11:57:03 weather weewx[1198]:         ****    File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Jun 12 11:57:03 weather weewx[1198]:         ****      raise ValueError("No JSON object could be decoded")
Jun 12 11:57:03 weather weewx[1198]:         ****  ValueError: No JSON object could be decoded
Jun 12 11:57:03 weather weewx[1198]:         ****  Generator terminated
Jun 12 11:57:03 weather weewx[1198]: copygenerator: copied 2 files to /var/www/html

**Comment by poblabs** [comment]
Is there an earthquake.json in your html directory json subfolder?

**Comment by the-butterfry** [comment]
yup, should I delete it and try reports again?
![image](https://user-images.githubusercontent.com/37050797/59392742-96873980-8d2d-11e9-96bb-4d068d54b9c0.png)

**Comment by the-butterfry** [comment]
That cleared the error after deleting and re running

**Comment by poblabs** [comment]
Ok cool. I wonder why it wasn't able to get it before. Maybe the source on usgs had an error when your system grabbed it?

**Comment by the-butterfry** [comment]
I shoulda saved it.. if it crops up again i'll rename and compare. thx again
