### ISSUE TITLE
Last 3 days chart question

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#176]
Hello Pat.
I created this chart today and I don't understand why it shows observations only for June, 15. It should show the last 3 days, from today 18th to 15th. Is it correct? 
```
[last3days]
    # Chart Timespan Defaults
    title = "Ultimos 3 días"
    show_button = true
    button_text = "Ultimos 3 días"
    time_length = days_ago
    time_ago = 3
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000
 to get milliseconds. Standard is 5 minutes
    # aggregate_interval = 3600

    [[chart2]]
        title = Precipitación
        type = line
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Precipitación Acumulada
```
![image](https://user-images.githubusercontent.com/4549674/59681370-2b64b980-91aa-11e9-916e-7630317f581c.png)
I replaced `time_length = days_ago` with `time_length = 259200` and I disabled `time_ago = 3` and It seems to work fine. Please help me to understand. If I use time_go option. It goes back to that value and then the last 90000 seconds are shown.

**Comment by poblabs** [comment]
The `days_ago` will graph that day ago. So if you want to graph the 3rd day ago you would use this option. 

if you want to graph "the last 3 days", then you would want to use `time_length = 259200` where 259200 is 3 days in seconds. (86400 seconds in 1 day, multiply by 3). 

Does this help?


```
[last3days]
    title = "Ultimos 3 días"
    show_button = true
    button_text = "Ultimos 3 días"
    time_length = 259200
    gapsize = 300000

    [[chart2]]
        title = Precipitación
        type = line
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Precipitación Acumulada
```

**Comment by HoracioDos** [comment]
Thanks Pat. That's what I've done.
