### ISSUE TITLE
xaxis_groupby = day plot question.

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#177]
Hello Pat
I want to plot daily max rain from the last 7 days.  Does `xaxis_groupby = day`  work?
```
    [[chart3]]
        title = Totales Precipitación - Ultimos 7 días
        type = column
        xaxis_groupby = day
        aggregate_type = max
        aggregate_interval = 86400 # 1 day
        time_length = 604800
        [[[rainTotal]]]
            name = Precipitación Acumulada

```
![image](https://user-images.githubusercontent.com/4549674/59687045-1e989380-91b3-11e9-9036-99d77e608f84.png)

**Comment by poblabs** [comment]
No, day is not setup - I must have missed that in 1.0. I can add it to the 1.1 beta and you can test it? I will try to commit that tonight.

**Comment by poblabs** [comment]
Actually just committed it real quick before I went offline. Try the new belchertown.py file in the development branch and let me know

![image](https://user-images.githubusercontent.com/3484775/59881343-55baa080-937d-11e9-826f-485a3e45e20d.png)

**Comment by HoracioDos** [comment]
Hello Pat. 
I'll try it now and I'll report back.
Thanks!

**Comment by HoracioDos** [comment]
Perfect!!
![image](https://user-images.githubusercontent.com/4549674/59928094-5a7e6380-9414-11e9-9bed-a9080e6c71ed.png)
