### ISSUE TITLE
Allow for records.inc to fit into existing records table

### ISSUE THREAD

**Issue by dseibel** [poblabs/weewx-belchertown#178]
Would it be possible to and records.inc included in the html template so that when you create new table entries they look like part of the existing table?

I tried testing the following in records.inc (could add anything but I just tried with temp as a quick test):

```<div class="row records-table">
    <table class="table-striped">
        <tbody>
            <tr>
                <td class="records-header" colspan=5>$obs.label.records_temperature_records</td>
            </tr>
            <tr>
                <td colspan=1> </td>
                <td class="records-header-year" colspan=2>$current.dateTime.format("%Y")</td>
                <td class="records-header-alltime" colspan=2>$obs.label.records_all_time</td>
            </tr>
            <tr>
                <td>$obs.label.records_high_temp</td>
                <td class="leftborder">$year.outTemp.max</td>
                <td><span id="year-outtemp-max-ts"></span></td><!-- moment.js -->
                <td class="leftborder"><span id="at-outtemp-max-ts"></span></td><!-- moment.js -->
                <td>$alltime.outTemp.max</td>
            </tr>
            <tr>
                <td>$obs.label.records_low_temp</td>
                <td class="leftborder">$year.outTemp.min</td>
                <td id="year-outtemp-min-ts"></td><!-- moment.js -->
                <td class="leftborder" id="at-outtemp-min-ts"></td><!-- moment.js -->
                <td>$alltime.outTemp.min</td>
            </tr>
        </tbody>
    </table>
</div>
```

and the output is disjointed:

![image](https://user-images.githubusercontent.com/8311761/59732859-1e2ae780-9209-11e9-9e55-2691e59f68b4.png)

I could update the actual index.html.tmpl file to make it look consistant but that of course could easily get wiped out in the next update.

Would be nice to be able to just add the existing table html setup you have and then have those new entries appear at the bottom of the exsiting table entries.

**Comment by dseibel** [comment]
So looks like a couple of things need to be updated:

I added this near the bottome of the index.html.tmpl file:

```
                            </tr>
                            #end if
                            #end if

                            #include "records_table.inc"
                        </tbody>
                    </table>
```
then put this in the records_table.inc file (testing with some power stats I have):

```
<script type="text/javascript">
    var moment_locale = "$system_locale_js";
    moment.locale(moment_locale);

    jQuery(document).ready(function() {

      jQuery("#year-consumedPower-max-ts").text( moment.unix($year.consumedPower.maxtime.raw).format( "$obs.label.time_records_page_full_date" ) );
      jQuery("#at-consumedPower-max-ts").text( moment.unix($alltime.consumedPower.maxtime.raw).format( "$obs.label.time_records_page_full_date" ) );

      jQuery("#year-consumedPower-min-ts").text( moment.unix($year.consumedPower.mintime.raw).format( "$obs.label.time_records_page_full_date" ) );
      jQuery("#at-consumedPower-min-ts").text( moment.unix($alltime.consumedPower.mintime.raw).format( "$obs.label.time_records_page_full_date" ) );


    });
</script>



            <tr>
                <td class="records-header" colspan=5>$obs.label.records_energy_records</td>
            </tr>
            <tr>
                <td colspan=1> </td>
                <td class="records-header-year" colspan=2>$current.dateTime.format("%Y")</td>
                <td class="records-header-alltime" colspan=2>$obs.label.records_all_time</td>
            </tr>
            <tr>
                <td>$obs.label.records_high_consumed_power</td>
                <td class="leftborder">$year.consumedPower.max</td>
                <td><span id="year-consumedPower-max-ts"></span></td><!-- moment.js -->
                <td class="leftborder"><span id="at-consumedPower-max-ts"></span></td><!-- moment.js -->
                <td>$alltime.consumedPower.max</td>
            </tr>
            <tr>
                <td>$obs.label.records_low_consumed_power</td>
                <td class="leftborder">$year.consumedPower.min</td>
                <td id="year-consumedPower-min-ts"></td><!-- moment.js -->
                <td class="leftborder" id="at-consumedPower-min-ts"></td><!-- moment.js -->
                <td>$alltime.consumedPower.min</td>
            </tr>
```

I was hoping that I could put records_energy_records, records_high_consumed_power etc in the weewx.conf file under     [[Belchertown]] [[[Extras]]] but no such luck, can put them in the skin.conf and they should work.

End up with this (formating looks ok and fits in nicely):

![image](https://user-images.githubusercontent.com/8311761/59734171-985d6b00-920d-11e9-9720-1b46cd81a97c.png)

**Comment by poblabs** [comment]
Very cool solution which made me wonder - should the entire table content of this page be in an `.inc` file? Then it can be added/edited/reordered as deemed fit?

It would get long with the amount of JS work up front for the time localization, but it would also make it easier for anyone (maybe you?) who wants their custom observations in a different area rather than last?

**Comment by dseibel** [comment]
That is probably a better idea actually.  You already have all the code in the existing `index.html.tmpl` file so really just moving that into an `.inc` file.  For the default user there is nothing to change it will look the same, but if someone wants to modify it then they could go ahead and do that.  Only issue I guess would be if you wanted to update that `.inc` file in a later version but you could just make a specific note of that.

So if the above is the case I can modify the pull request.  Then I think the only thing missing that would be nice is the ability to put custom header names in `weewx.conf` instead of `skin.conf` which could be added later.

**Comment by poblabs** [comment]
Yeah thats the problem are updates. Anything inside records.inc will get erased on any skin upgrade. That's why there's the `.inc.example`, but I don't think the records page should be an "example" file. 

Custom header names can go in weewx.conf. Skin.conf contains "the defaults" and then in weewx.conf they get overridden.

**Comment by dseibel** [comment]
What I was meaning by custom headers was for the example above the records_energy_records, records_high_consumed_power, records_low_consumed_power entries need to be added to skin.conf.  When I put them in weewx.conf they don't get used (or I haven't got it to work)

**Comment by poblabs** [comment]
There's 3 approaches here for your headers:

1. Since you're customizing the page, no need to use an `$obs.label` - just put the header text you want 😃 

2. If you want to use the `$obs.label` without changing skin.conf, just add them to weewx.conf under [StdReport] --> [[Defaults]] --> [[[Labels]]] --> [[[[Generic]]]]

3. If you want to add them to skin.conf, then you can do that in skin.conf under [Labels] --> [[Generic]] which can then get added to the [[Belchertown]] skin options inside of weewx.conf.

**Comment by dseibel** [comment]
I have a feeling I am over complicating it ;-)  the first option is probably the easiest to do with my PR especially since the `.inc` file is all custom content anyways!

**Comment by wwray** [comment]
I too am  interested in customizing the records table with new observations without having the changes overwritten on a skin upgrade. Just throwing my 2 cents in for this feature :)

**Comment by poblabs** [comment]
@wwray Yeah, I'm not so sure there's a way to do this based on how weewx operates and how it upgrades skins. I may have to close this issue as a "can't implement". Suppose you could just have a backup of the file and copy in your changes if you every upgrade

**Comment by wwray** [comment]
maybe something to suggest for weewx skin upgrades. I'm not too sure how it all works, I'm still learning lots. Do you have any suggestions other than the above to add custom items to the records table?

**Comment by dseibel** [comment]
@poblabs Did you have a chance to check out my PR?  I just made a small change to the index.html.tmpl file and a bit of formatting to have the records.inc file included.  Since you don't overwrite the records.inc file with updates...they should be preserved.

This is what is looks like on my site: [https://magpie.dantine.ca/weewx/records/](https://magpie.dantine.ca/weewx/records/)

**Comment by poblabs** [comment]
Closing this issue since the PR has been merged. Thanks!
