### ISSUE TITLE
Sun Records --- Question

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#179]
How can I have a Highest UV Record, if I don't have a sensor for UV and the the database is a "Null" value? Should it be a zero?

![sun records](https://user-images.githubusercontent.com/48191231/59816067-ae8c2980-92e8-11e9-9a81-cb2831e364e1.png)

**Comment by poblabs** [comment]
Did you figure this one out? Something with your sensor sending wrong values?
