### ISSUE TITLE
Adding / to end of URL's

### ISSUE THREAD

**Issue by jeffreycentex** [poblabs/weewx-belchertown#181]
One problem I had to correct was to add / to the end of records, graphs, etc.  (i.e., to make the url http://localhost/graphs/ instead of http://localhost/graph).

I've corrected everything manually on my side, but future updates might break things.  Just a suggestion.

**Comment by poblabs** [comment]
Hi there, Couple questions: 

1. What was broken that made you update it?
2. What version are you on? The 1.1 beta right now gets rid of the `belchertown_root_url` which may be part of your issue?

This was covered previously in this issue, https://github.com/poblabs/weewx-belchertown/issues/35, but I think with the removal of the `belchertown_root_url` a lot of these headaches go away.

**Comment by poblabs** [comment]
Any update on this one?
