### ISSUE TITLE
RPI Kiosk Mode Issue

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#182]
I'm having an issue with the Pi Kiosk Mode.   It opens up fine in the kiosk mode but:
1. Does not switch over to "dark" mode.
2. Displays Barometer value in "inHg" and the label is "mbar". Note main web page display the Barometer displays correctly in "mbar".
3. Several items from the main page are missing like Dewpoint, Solar, Visibility, and Cloudbase.

In the skin .config file I did set  "pi_kiosk_bold = "true"".  Do I need to change something else?

General Question:  If we recieve alerts from DarkSky, do they appear in the Kiosk Mode?

**Comment by biltmorelaker** [comment]
The Pi Kiosk display is designed to be shown on an Adafruit 3.5" touch screen with a resolution of 480x320. See Pat's blog article (https://obrienlabs.net/setup-raspberry-pi-kiosk-chromium/) on setting this up. There are some issues in setting the resolution on the latest version of Adafruit's display. If you have an issue doing that, let me know and I'll provide more information. Here is what my display looks like on that display. 

![wx kutzenco com](https://user-images.githubusercontent.com/44727343/60180652-858afd80-97ee-11e9-9891-abafde527a73.png).
Regarding dark mode - make sure you have the latest (beta) version from the "development" branch of the GitHub repository. Dark mode is set for "Auto" by default. You can set it to pi_theme = "light", pi_theme = "dark" or pi_theme = "auto" in weewx.conf. (Make sure to restart weewx or reload weewx.conf after changing weewx.conf.

**Comment by biltmorelaker** [comment]
Whoops. I accidentally closed this. Reopening.

**Comment by poblabs** [comment]
The mbar/inHg issue is interesting. Is your site public? I'd like to take a look. 

Admittedly the Pi page was a little left behind in the big 1.0 upgrade since my focus was on the charts. So like @biltmorelaker said, the new beta development version brings that back up to speed with the rest of the skin. So I'm thinking that's probably contributing to the barometer issue. 

Item 3. the Pi page is a very slimmed down version, so those other items are missing on purpose - real estate is an extreme premium here. See the screenshot above 😄 

DarkSky alerts will not show - again, screen real estate is the problem. 

I suggest upgrading to the latest development version of the skin. it might help you out.

**Comment by Stormtracker017** [comment]
As of right now, my site is on my LAN. I did update the skin to 1.1b3 and it fixed the switching between light and dark modes. I understand about the real estate.  Thinking about switching to a 10 inch display. 

The Kiosk still displays the Barometer value in "inHg" and the label is "mbar".
![Web page and Kiosk Current Obs](https://user-images.githubusercontent.com/48191231/60227338-f8cb5880-985c-11e9-8700-0dfbeb6705de.png)

Here are my settings in the weewx.conf 
 [[MQTT]]
        ......
       [[[inputs]]]
            [[[[barometer]]]]
                units = mbar

and my settings in the skin.conf 
[Units]
    # This section is for managing the selection and formatting of units.  
    [[Groups]]
        ......
        group_pressure     = mbar   
        .....

**Comment by poblabs** [comment]
@Stormtracker017 I'm confused now since your screenshot looks like the normal website - not the Pi page. So in your screenshot, it looks like the main page is wrong? `1017.0 mbar`?

**Comment by Stormtracker017** [comment]
Sorry for the confusion, you are correct, the screenshot is the normal website which display the pressure in the correct format.  The Kiosk displays the wrong value '30.07" but the label "mbar" is correct.

**Comment by poblabs** [comment]
What do you have set for `unit_system` under `[MQTT]`? Is it `unit_system = METRIC`?

**Comment by poblabs** [comment]
Update your Pi page to the latest one in the development branch. The changes make the station observation table match the one on the homepage. So the data should be in sync. Let me know.

**Comment by Stormtracker017** [comment]
The unit_system is set to US.  The updated file resolved the issue. Thanks

**Comment by poblabs** [comment]
Great news. 

Since you're on US units, the MQTT label is still barometer_inHg, but the value of this is in mbar. So the old file was using doing the right thing. What should  have been done was also adding a name field like this:

```
 [[MQTT]]
        ......
       [[[inputs]]]
            [[[[barometer]]]]
                name = barometer_mbar
                units = mbar
```

But I made the update in the file to ignore the mqtt label and *basically* trust the units.

**Comment by biltmorelaker** [comment]
@poblabs, Looks like commit 88173b changed the MQTT connected message (line 584)

from: 
> Connected. Received _[date, time]_

to: 
> Connected to weather station live. Data received _[date, time]_

This wraps that message on the top line on the pi display and pushes down the rest of the display.
Can you shorten that message again?

**Comment by Stormtracker017** [comment]
In the skin.conf, I changed "mqtt_websockets_connected   = Connected to weather station live. Data received" to  "mqtt_websockets_waiting     = Connected. Waiting for data."

**Comment by biltmorelaker** [comment]
To be clear, I am suggesting a change only for the pi display (in pi/index.html.tmpl). Not for the Belchertown home page.

**Comment by poblabs** [comment]
Thanks. This change was in response to a recent request in #104. I'll make an update for the Pi page headers which will be shorter and able to be translated using a label. I'll commit that shortly.

**Comment by poblabs** [comment]
All set in latest commit!

**Comment by biltmorelaker** [comment]
Perfect. All better now. Thanks @poblabs!
