### ISSUE TITLE
help with Mqtt

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#183]
So I moved to the 1.1 dev off the old 1.0 dev and i decided to try to use MQTT instead of auto refreshing every 2 minutes. 
However, I think im missing something, it could be belchertown, it could be mqtt server, not sure, but i figured id start here. 
relevent settings in WeeWx conf: 

```
[[MQTT]]
        server_url = mqtt://pi:replaceme@localhost:1883/
        topic = weather
        unit_system = US
        binding = loop
```

And Skin.conf 

```
# MQTT Websockets defaults
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "slvrscoobie.synology.me"
    mqtt_websockets_port = 1883
    mqtt_websockets_ssl = 9001
    mqtt_websockets_topic = "weather"
    disconnect_live_website_visitor = 1800000
```

Im completely unsure how to test these without just going to my website and looking. 
My Pi is running WeeWx And my webserver 
Weewx seems to be publishing updates : 

```
raspberrypi weewx[8456]: restx: MQTT: Published record 2019-07-02 18:34:36 EDT (1562106876)
Jul  2 18:34:41 raspberrypi weewx[8456]: restx: MQTT: Published record 2019-07-02 18:34:37 EDT (1562106877)
Jul  2 18:34:41 raspberrypi weewx[8456]: restx: MQTT: Published record 2019-07-02 18:34:38 EDT (1562106878)
```

website says "Failed connecting to the weather station. Please try again later!"

Thoughts?

**Comment by poblabs** [comment]
Let's try a few things. 

1. Update your weewx.conf MQTT settings with 

```
        binding = archive, loop
        aggregation = aggregate
```

Then update this:

```
mqtt_websockets_port = 9001
mqtt_websockets_ssl = 0
```

I am assuming you're not using SSL on your Pi, so try it with the above. 

Did you follow my guide on setting up MQTT? If so then 9001 should be the port you used.

**Comment by slvrscoobie** [comment]
Yup, that was the one I followed. 
I added both to my firewall, but after the update, start/stop, still 'failed to connect'? 
I get this from your 'check' command 
pi@raspberrypi:~ $ sudo netstat -tulpn | grep 1883
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      8613/mosquitto      
tcp6       0      0 :::1883                 :::*                    LISTEN      8613/mosquitto      
pi@raspberrypi:~ $ sudo netstat -tulpn | grep 9001
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      8613/mosquitto  
I dont think its supposed to be 0.0.0.0 ... 
myconfig.conf reads:
  GNU nano 2.7.4                                         File: /etc/mosquitto/conf.d/myconfig.conf                                                    

persistence false

# mqtt
listener 1883
protocol mqtt

# websockets
listener 9001
protocol websockets

allow_anonymous true
password_file /etc/mosquitto/passwd

acl_file /etc/mosquitto/acl

and acl file: 
# Allow anonymous access to the sys
topic read $SYS/#

# Allow anonymous to read weather
topic read weather/#

# weewx readwrite to the loop
user pi
topic weather/#

See anything amiss?

**Comment by Stormtracker017** [comment]
Did you restart your RPI?  I had issues until I restarted my RPI.

**Comment by slvrscoobie** [comment]
Honestly. No.
Wouldn’t have thought that would be an issue, it’s not windows lol

**Comment by slvrscoobie** [comment]
And I’m back. Reboot didn’t fix it. Still not connecting

**Comment by ShadowsFriend** [comment]
If it stays on "connected. Waiting for data" changing the "weather" in 
`mqtt_websockets_topic = "weather"`
to "weather/loop" or "weather/#" might help. The updates get published to "weather/loop" and you will not get them by only subscribing to "weather". At least that was the case for me.

**Comment by poblabs** [comment]
Don't subscribe to `weather/#`, or any of the `#` topics. The `#` is a special topic that will show you **everything**. Using `#` is great for troubleshooting, but not really anything else. With Belchertown and weewx subscribing to `#` can result in unexpected results. Best to keep Belchertown subscribed to `weather/loop`. 

> I dont think its supposed to be 0.0.0.0 ... 

This is fine, it means it's listening on all interfaces which is what you want. 

---

**The good news is I can connect to your Websocket server, and I see weewx data.** 

So there might be something wrong with your Belchertown weewx.conf settings. Can you confirm you made the changes I suggested in this reply (and restarted weewx after making them)? https://github.com/poblabs/weewx-belchertown/issues/183#issuecomment-507900992

Using an MQTT Websocket test utility I connected to your Websocket server, subscribed to `weather/loop` and I see the data below. 

![image](https://user-images.githubusercontent.com/3484775/60590015-ea9f9f80-9d68-11e9-983a-aa2fad66af9f.png)

**Comment by slvrscoobie** [comment]
Yup those are the changes i made (sans weather/loop, i only had weather, but i just changed, and restarted ) - I still only get connected. waiting for data. 
Skin.conf settings: 
# MQTT Websockets defaults
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "slvrscoobie.synology.me"
    mqtt_websockets_port = 9001
    mqtt_websockets_ssl = 0
    mqtt_websockets_topic = "weather/loop"
    disconnect_live_website_visitor = 1800000

WeeWx.conf
[[MQTT]]
        server_url = mqtt://pi:mypassword@localhost:1883/
        topic = weather
        unit_system = US
        binding = archive, loop
        aggregation = aggregate
[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Belchertown
        [[[Extras]]]
            forecast_enabled = 1
            darksky_secret_key = 772e57b99e4df40dd65ad16eb0ed1953
    
Now that I look at it, i bet  server_url = mqtt://pi:mypassword@localhost:1883/ is supposed to be 9001 isnt it?

**Comment by poblabs** [comment]
> Now that I look at it, i bet server_url = mqtt://pi:mypassword@localhost:1883/ is supposed to be 9001 isnt it?

No, 9001 is for Belchertown to connect to. Leave the 1883 in place since it's working (proven by my screenshot above). 

Is your site public? We may need to run Belchertown in debug mode to see if that offers any hints.

**Comment by slvrscoobie** [comment]
Yup should be public, slvrscoobie.synology.me/weewx/belchertown

**Comment by slvrscoobie** [comment]
#idontknow 
i turned on debug mode, restarted weewx, and boom, connected and live...
weird.  Ill let you know if anything changes.

**Comment by poblabs** [comment]
Appears to be working just fine for me. 

![image](https://user-images.githubusercontent.com/3484775/60593556-073fd580-9d71-11e9-977f-385a8108ecbe.png)

**Comment by poblabs** [comment]
Good timing! Ok, try turning off debug mode, restart again and see if it stays?

**Comment by slvrscoobie** [comment]
Still working - only issue is after a while it stops and say disconnected. I deleted the keep_live=1800000 cause i just use it for myself so i just want it to always be live, restarted but still disconnects.. ideas? change keep live to 300000000 and have it auto-refresh every 30?

**Comment by poblabs** [comment]
I'm remote right now. Check the front page README for that option. it tells
you how to disable the timeout.

**Comment by slvrscoobie** [comment]
oh man, I just saw this in the readme.
Note: I did not write the MQTT extension, so please direct any questions or problems about it to the user forums.
sorry! should have taken this to the forums first. Also should have known setting to 0 would disable to disconnect. 
Thanks! should be all set for now.

**Comment by poblabs** [comment]
That's ok this particular issue was a Belchertown configuration issue so no
problem there.

Glad you're all set now!

**Comment by twistedgrim** [comment]
@poblabs 

Looking through this issue helped me out. It might help to update the documentation for MQTT setup with examples more like this. Im a noobie with MQTT so wasn't quite sure how the topic worked and I had it set to weather/loop when it needed to be weather.

**Comment by bleekerk** [comment]
After days of fiddling around, reading forum posts, testing, pulled my hair out, trial and error for getting MQTT working... This morning I read a comment to forward port 9001 in the router to the RPi, but still no solution. And now, in the wind on terrace # 3 with a nice drink, I thought hoho, aftre forwarding 9001 on incoming trafiic to the RPi, the mqtt_websockets_host in the skin.conf must be set to the external IP! And yes, it's working OK on LAN ass well as WAN! The last issue is to resolve the date and time issue of the update:) (http://oentsjerk.eu/)
