### ISSUE TITLE
Can't get site updating in realtime.

### ISSUE THREAD

**Issue by tenbyboy** [poblabs/weewx-belchertown#188]
I love Belchertown and have it working nicely on my [website:] (http://www.tenby-weather.co.uk)

I'd like to get the realtime updates working via MQTT and understand I need to use websockets. I've followed the guide and here is what I have in my weewx.conf:

```
[[MQTT]]
        server_url = mqtt://test.mosquitto.org:8081
        topic = tenbyweather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate

    [[Belchertown]]
        HTML_ROOT = /var/www/html/weewx
        skin = Belchertown
        [[[Extras]]]
            belchertown_root_url = http://www.tenby-weather.co.uk
            # logo_image = "https://belchertownweather.com/images/content/btownwx-logo-slim.png"
            footer_copyright_text = tenby-weather.co.uk
            forecast_enabled = 1
            #darksky_secret_key = "your_key"
            earthquake_enabled = 1
            site_title = Tenby Upper Hill Park weather station
            #twitter_enabled = 1
            #webpage_autorefresh = 15000
            mqtt_enabled = 1
            mqtt_host = test.mosquitto.org
            mqtt_port = 8081
            mqtt_ssl = 1
            mqtt_topic = tenbyweather/#
```

And my skin.conf:

```
    #MQTT Websockets defaults
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "test.mosquitto.org"
    mqtt_websockets_port = 8081
    mqtt_websockets_ssl = 1
    mqtt_websockets_topic = "tenbyweather"
    disconnect_live_website_visitor = 1800000
```

My topic seems to be getting published:
`restx: MQTT: Published record 2019-07-22 11:44:44 BST (1563792284)`

However, if I use:
`mosquitto_sub -h test.mosquitto.org -p 1883 -t tenbyweather`

It finds nothing and therefore, my website can't update dynamically.

I've tried different combinations of port etc but still no joy. Have I got my syntax correct? Do I need MQTT stuff in both weewx.conf and skin.conf?

Thanks in advance for your help.

**Comment by poblabs** [comment]
Hi, glad you like the skin! 

Subscribing to `#` is generally a bad idea. It's used for troubleshooting but nothing else really. So first I would change `mqtt_topic = tenbyweather/#` to `mqtt_topic = tenbyweather/loop`. Restart weewx.

Then try with `mosquitto_sub -h test.mosquitto.org -p 1883 -t tenbyweather/loop` or since we're troubleshooting try with `mosquitto_sub -h test.mosquitto.org -p 1883 -t tenbyweather/#`

Everything else looks ok though. If nothing works after that change, then try another mqtt broker. (Who knows what mosquitto.org is doing on the test server.)

**Comment by tenbyboy** [comment]
@poblabs Thanks for the quick reply - it's much appreciated!!

I'll give that a go and let you know how I get on.

**Comment by poblabs** [comment]
Ah, I see another issue after visiting their website. Try this. 

```
[[MQTT]]
        server_url = mqtt://test.mosquitto.org:1883
        topic = tenbyweather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
```

We have to change the port to 1883. Weewx will send MQTT payload as normal MQTT, then the skin gets it from Websockets. 

Restart weewx after those changes, and try that.

**Comment by poblabs** [comment]
And lastly I also see this. Not quite as important but worth a cleanup:

> Do I need MQTT stuff in both weewx.conf and skin.conf?

The items in skin.conf are preferred to live in weewx.conf. So essentially they are a copy of each other. Weewx.conf's settings will always win if there's a conflict. This ensures that on skin upgrades no settings are lost since skin.conf gets overwritten on upgrades.

So once you get this all working, I'd suggest copying all the `mqtt_websockets_` items from skin.conf to the weewx.conf Belchertown Extras section (and you can delete the old `mqtt_` items if you are using skin version 1.0 or higher since I renamed them for more clarity)

**Comment by poblabs** [comment]
Looks like you're making progress. 

Output of `mosquitto_sub -h test.mosquitto.org -p 1883 -t tenbyweather/loop` shows me 

```
{"cloudbase_meter": "120.913069728", "outHumidity": "98.0", "pressure_mbar": "1004.70396416", "rain_cm": "0.0", "maxSolarRad": "871.26116613", "barometer_mbar": "1014.18938968", "dewpoint_C": "17.8888888889", "windGust_kph": "16.5601909201", "heatindex_C": "18.2222222222", "dayRain_cm": "0.07874", "inDewpoint_C": "17.7118420718", "altimeter_mbar": "1014.08005371", "windchill_C": "18.2222222222", "appTemp_C": "18.6652579327", "outTemp_C": "18.2222222222", "humidex_C": "24.1537451853", "rain24_cm": "0.07874", "hourRain_cm": "0.0", "inTemp_C": "21.7222222222", "windSpeed_kph": "11.8769882401", "usUnits": "16.0", "txBatteryStatus": "0.0", "UV": "0.0", "dateTime": "1563799153.0", "windDir": "176.0", "inHumidity": "78.0", "radiation_Wpm2": "122.34"}
```

You have a typo in your Belchertown config somewhere which is preventing it to connect to the broker though.

**Comment by tenbyboy** [comment]
Ah yes that's good news that it's finally publishing the topic. So I suppose now it's just a case of finding out where the typo is and sorting that and then tidying up the installation - i.e moving the [MQTT] stuff to weewx.conf.

Do you think the typo is in the [[Belchertown]] section?

**Comment by tenbyboy** [comment]
I have moved that section out of skin.conf, so it is all now in weewx.conf. This is the latest which is also still publishing:

[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx
        skin = Belchertown
        [[[Extras]]]
            belchertown_root_url = http://www.tenby-weather.co.uk
            # logo_image = "https://belchertownweather.com/images/content/btownwx-logo-slim.png"
            footer_copyright_text = tenby-weather.co.uk
            forecast_enabled = 1
            #darksky_secret_key = "your_key"
            earthquake_enabled = 1
            site_title = Tenby Upper Hill Park weather station
            #twitter_enabled = 1
            #webpage_autorefresh = 15000

            #MQTT Websockets defaults
            mqtt_websockets_enabled = 1
            mqtt_websockets_host = "test.mosquitto.org"
            mqtt_websockets_port = 8081
            mqtt_websockets_ssl = 1
            mqtt_websockets_topic = "tenbyweather"
            disconnect_live_website_visitor = 1800000

            mqtt_enabled = 1
            mqtt_host = test.mosquitto.org
            mqtt_port = 8081
            mqtt_ssl = 1
            mqtt_topic = tenbyweather/loop


I can't see any typos though. Any ideas where else I should be looking?

**Comment by poblabs** [comment]
Hmm, not sure where the typo is. I was able to get it to work for me with these settings:

weewx.conf:

```
[StdReport]
    [[Belchertown]]
        ... truncated ...
        [[[Extras]]]
            ... your other extras here ...
            mqtt_websockets_enabled = 1
            mqtt_websockets_host = "test.mosquitto.org"
            mqtt_websockets_port = 8081
            mqtt_websockets_ssl = 1
            mqtt_websockets_topic = "tenbyweather/loop"
```

Remove the other mqtt_ items you have under Belchertown Extras and use the ones above. 

Restart weewx. 

My test site showed me the below screenshot.

Try the above settings out. 


![image](https://user-images.githubusercontent.com/3484775/61634313-0d81ed00-ac5f-11e9-9844-2f871c235ab4.png)

**Comment by tenbyboy** [comment]
I've done that but still not updating for me: www.tenbyweather.co.uk  . weewx.conf not looks like:

 [[MQTT]]
        server_url = mqtt://test.mosquitto.org:1883
        topic = tenbyweather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
        #retain = true

  [[Belchertown]]
        HTML_ROOT = /var/www/html/weewx
        skin = Belchertown
        [[[Extras]]]
            belchertown_root_url = http://www.tenby-weather.co.uk
            # logo_image = "https://belchertownweather.com/images/content/btownwx-logo-slim.png"
            footer_copyright_text = tenby-weather.co.uk
            forecast_enabled = 1
            #darksky_secret_key = "your_key"
            earthquake_enabled = 1
            site_title = Tenby Upper Hill Park weather station
            #twitter_enabled = 1
            #webpage_autorefresh = 15000


            mqtt_websockets_enabled = 1
            mqtt_websockets_host = "test.mosquitto.org"
            mqtt_websockets_port = 8081
            mqtt_websockets_ssl = 1
            mqtt_websockets_topic = "tenbyweather/loop"

Wonder what the difference is between your's and mine?

**Comment by tenbyboy** [comment]
Cancel my last! I gave it one more refresh and it seems to have started working now!

Thanks a lot for your help @poblabs and thanks for a GREAT skin :)

**Comment by poblabs** [comment]
Great news!

Last bit I noticed is that your skin is in US units until MQTT kicks in then it flips to Metric. You may want to re-apply the [Belchertown Metric units section](https://github.com/poblabs/weewx-belchertown#using-metric) to your weewx.conf Belchertown section.
