### ISSUE TITLE
Feature Request: Add Weather Alerts

### ISSUE THREAD

**Issue by Zimerhonzl** [poblabs/weewx-belchertown#19]
If possible, use the same DarkSky query as forecast to display data["alerts"] (see https://darksky.net/dev/docs) to display at top of current conditions (maybe light red or other differentiating background).  My PHP and HTML skills are there, unfortunately I don't have the familiarity with jQuery to process the information correctly.

**Comment by poblabs** [comment]
These 2 commits add this feature: https://github.com/poblabs/weewx-belchertown/commit/b3883dbd67a2b4d5368961e2479631f7de86e128 and https://github.com/poblabs/weewx-belchertown/commit/cac70b881e99ddd54eea017d37fcdf3866d97541

To upgrade and test it out, download the latest [index.html.tmpl here](https://raw.githubusercontent.com/poblabs/weewx-belchertown/master/skins/Belchertown/index.html.tmpl), and the latest [styles.css here](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/style.css). 

Place them into your `skins/Belchertown` folder and restart weewx. Wait for an archive interval for the site to get updated.

Anytime there is an alert in DarkSky it'll show the alert below the timestamp (see screenshot below) with a snippet of what the alert is. Clicking the link will take you to the source of the alert. 

If you have the MQTT background updates enabled, and the alert clears it'll disappear without the need to reload the page. 

![alert_concept](https://user-images.githubusercontent.com/3484775/50456853-684fa200-0925-11e9-99b9-77c55fdbe881.jpg)

**Comment by poblabs** [comment]
Which reminds me I need to add an option to show that bar if MQTT is disabled. I'll have to make another update later today.

**Comment by poblabs** [comment]
Non-MQTT alerts fixed in https://github.com/poblabs/weewx-belchertown/commit/d9679039d7236ea67e3f78c70f431f8c74b52ac4

**Comment by Zimerhonzl** [comment]
Thanks!  My station is too slow to make MQTT worth while, so I appreciate the latter fix!

**Comment by poblabs** [comment]
No problem! I just added another commit with the alerts disabled by default. You can find those details here https://github.com/poblabs/weewx-belchertown/commit/a725478cb294dcb22c3628a731f5cc4b48d68333. Best to grab index.html.tmpl, skin.conf, and bin/user/belchertown.py and replace them all. In weewx.conf under the skin options add `forecast_alert_enabled = 1` to enable it then restart weewx.
