### ISSUE TITLE
Future Enhancement -- Ver. 2.0

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#190]
Don't know if this would be possible, but near real time graphing capabilities by using the loop data.

**Comment by poblabs** [comment]
Not a bad idea and I haven't actually thought about it. Off hand I'm not sure if it's possible with the current setup. 

The graphs are formed on the archive interval. Not to say I can't make an option for them to form on every MQTT LOOP message though.

Initial reaction would be that it could look weird since on initial page load before MQTT, they'll show archive graph data.

Technically speaking I'd have to open each graph on MQTT payload receipt and append a value to the series. Some research to be done here. 

Might need to make this an option to opt-in for. Something to think about for sure.

**Comment by bctrainers** [comment]
This is possible within weewx using a plugin to store the data to a second SQL table. `raw.py` can be used in this event. I'm not much of a coder, but have detailed it on my [blog here](https://potatoforinter.net/77/raw-py/).

Excerpt from my blog:

weewx.conf to include the following

```
[Raw]
     data_binding = raw_binding
     data_limit = 0
```

And `raw.py` that is located at: `/usr/share/weewx/user/raw.py`

```
import syslog
import time
import weeutil.weeutil
import weewx
import weewx.engine
import weewx.manager
from weewx.engine import StdService

VERSION = "0.4.1-lh-bc"

#
# 2015-12-28 Modified by Luc Heijst to work with weewx version 3.3.1
# 2019-01-15 Minor tweak by Brett C to persist data... for a long time.
#

if weewx.__version__ < "3":
    raise weewx.UnsupportedFeature("weewx 3 is required, found %s" % weewx.__version__)

schema = [
    ('dateTime', 'INTEGER NOT NULL UNIQUE PRIMARY KEY'),
    ('usUnits', 'INTEGER NOT NULL'),
    #('interval', 'INTEGER NOT NULL DEFAULT \'1\''),
    ('barometer', 'REAL'),
    #('pressure', 'REAL'),
    #('altimeter', 'REAL'),
    ('inTemp', 'REAL'),
    ('outTemp', 'REAL'),
    ('inHumidity', 'REAL'),
    ('outHumidity', 'REAL'),
    ('windSpeed', 'REAL'),
    ('windDir', 'REAL'),
    #('windGust', 'REAL'),
    #('windGustDir', 'REAL'),
    ('rainRate', 'REAL'),
    ('rain', 'REAL'), # rain, was: dayRain
    ('dewpoint', 'REAL'),
    ('windchill', 'REAL'),
    ('heatindex', 'REAL'),
    #('rxCheckPercent', 'REAL'),
    ('dayET', 'REAL'), # ET
    ('radiation', 'REAL'),
    ('UV', 'REAL'),
    ('extraTemp1', 'REAL'),
    ('extraTemp2', 'REAL'),
    ('extraTemp3', 'REAL'),
    ('soilTemp1', 'REAL'),
    ('soilTemp2', 'REAL'),
    ('soilTemp3', 'REAL'),
    ('soilTemp4', 'REAL'),
    ('leafTemp1', 'REAL'),
    ('leafTemp2', 'REAL'),
    ('extraHumid1', 'REAL'),
    ('extraHumid2', 'REAL'),
    ('soilMoist1', 'REAL'),
    ('soilMoist2', 'REAL'),
    ('soilMoist3', 'REAL'),
    ('soilMoist4', 'REAL'),
    ('leafWet1', 'REAL'),
    ('leafWet2', 'REAL'),
    ('txBatteryStatus', 'REAL'),
    ('consBatteryVoltage', 'REAL')]
    #('hail', 'REAL'),
    #('hailRate', 'REAL'),
    #('heatingTemp', 'REAL'),
    #('heatingVoltage', 'REAL'),
    #('supplyVoltage', 'REAL'),
    #('referenceVoltage', 'REAL'),
    #('windBatteryStatus', 'REAL'),
    #('rainBatteryStatus', 'REAL'),
    #('outTempBatteryStatus', 'REAL'),
    #('inTempBatteryStatus', 'REAL')i

def get_default_binding_dict():
    return {'database': 'raw_mysql',
            'manager': 'weewx.manager.Manager',
            'table_name': 'raw',
            'schema': 'user.raw.schema'}

class RawService(StdService):

    def __init__(self, engine, config_dict):
        self.config_dict = config_dict
        super(RawService, self).__init__(engine, config_dict)
        syslog.syslog(syslog.LOG_INFO, "raw: service version is %s" % VERSION)

        d = config_dict.get('Raw', {})
        self.dataLimit = int(d.get('data_limit', 24))

        # get the database parameters we need to function
        self.binding = d.get('data_binding', 'raw_binding')
        self.dbm = self.engine.db_binder.get_manager(data_binding=self.binding, initialize=True)

        # be sure schema in database matches the schema we have
        dbcol = self.dbm.connection.columnsOf(self.dbm.table_name)
        dbm_dict = weewx.manager.get_manager_dict(
            config_dict['DataBindings'], config_dict['Databases'], self.binding)
        memcol = [x[0] for x in dbm_dict['schema']]
        if dbcol != memcol:
            raise Exception('raw: schema mismatch: %s != %s' % (dbcol, memcol))

        self.lastLoopDateTime = 0
        self.lastPrunedDateTime = 0
        self.bind(weewx.NEW_LOOP_PACKET, self.newLoopPacket)

    def prune_rawdata(self, dbm, ts, max_tries=3, retry_wait=10):
        """remove rawdata older than data_limit hours from the database"""
        sql = "delete from %s where dateTime < %d" % (dbm.table_name, ts)
        for count in range(max_tries):
            try:
                dbm.getSql(sql)
                syslog.syslog(syslog.LOG_INFO, 'raw: deleted rawdata prior to %s' % weeutil.weeutil.timestamp_to_string(ts))
                break
            except Exception, e:
                syslog.syslog(syslog.LOG_ERR, 'raw: prune failed (attempt %d of %d): %s' % ((count + 1), max_tries, e))
                syslog.syslog(syslog.LOG_INFO, 'raw: waiting %d seconds before retry' % retry_wait)
                time.sleep(retry_wait)
        else:
            raise Exception('raw: prune failed after %d attemps' % max_tries)

    def newLoopPacket(self, event):
        packet = event.packet
        prune_period = 300
        # It's possible for records with duplicate dateTimes - this occurs when an archive packet
        # is processed since the LOOP packets are queued up and then returned immediately when
        # looping resumes, coupled with the fact that for Vantage Pro consoles the dateTime value is
        # added by weewx. So, for database storage, skip the duplicates until we get a new one to
        # avoid a duplicate key error, but publish them all to redis regardless.
        dateTime = packet['dateTime']
        if dateTime != self.lastLoopDateTime:
            self.dbm.addRecord(packet)
            self.lastLoopDateTime = dateTime
        if dateTime > (self.lastPrunedDateTime + prune_period):
            if self.dataLimit is not 0:
                ts = ((dateTime - (self.dataLimit * 3600)) / prune_period) * prune_period  # preset on 5-min boundary
                self.prune_rawdata(self.dbm, ts, 2, 5)
            self.lastPrunedDateTime = dateTime
```

I figure something like above could be integrated into Belchertown's data collection process for extremely high-resolution graphs. 

My Davis Vantage Pro2+ outputs loop data every 1.5s/2s. All added to the raw table in a weewx_rapid DB since January. The table has 11 million rows, and polling the entire database table for all data takes about 30 seconds now on 1Gbps ethernet (the SQL daemon seems to cap out at 675Mbps). So using SQL sanity options in the query would be very wise (last, first, limit, date span limits).

**Comment by poblabs** [comment]
Looks interesting and your `raw.py` approach looks similar to [Tom's approach with WeeRT](https://github.com/tkeffer/weert-js). He's using InfluxDB which is much better for timeseries database data than MySQL would. [His demo site is here](http://threefools.org:3000/). 

I'm not sure something like this makes sense for Belchertown though. A lot of the Belchertown users are on Raspberry Pi's and I get frequent comments on how slow it takes to generate simple JSON. I'm not sure I want to entertain a plugin like this with more external dependencies as part of a skin package.

To keep it skin-based only, my thought here is that the LOOP data is available through MQTT (no matter what station you're using). So I could use this MQTT payload data to expand the chart in real time potentially. Keep the Archive data as the pre-loading chart data in an effort to remain as high speed as possible. Then once MQTT connects, just append the data to the chart series. 

I've got a few non-Belchertown projects in flight right now, so I may have to defer this one out a few weeks but it sounds like an interesting project to get more tightly integrated with MQTT Websockets.

**Comment by Stormtracker017** [comment]
Thanks for thinking about this future enhancement. Yes the user should have an option to opt-in if they choose to do so. I see only near real-time graphs on the main page using the loop data. The graphs on the graph page should still use archived data for historical purposes.

**Comment by digitalurban** [comment]
Just noted this and it’s a great idea - it would be so nice to see a real-time mqtt graph...

**Comment by digitalurban** [comment]
Just to add - I have a realtime graph from MQTT using the mqttw31.js script - just a quick example here:

[](http://www.finchamweather.co.uk/mqtthighcharts_windgust.html)

Is it possible to integrate such a realtime script into the skin, so the background colours etc match the page?

Andy
