### ISSUE TITLE
Not sure if Belchertown - Rain levels?

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#191]
We were getting some serious rain today, so I checked my page, and it said 'Light Rain' - my WeeWx was reporting 1.82in/hr. Seems pretty serious - but is this a Belchertown calculation or a weewx calculation?

**Comment by poblabs** [comment]
Something like "Light rain" is from dark sky forecasts. And is only updated
at the interval you set in extras settings. See readme for more info on
forecast update intervals.

**Comment by slvrscoobie** [comment]
Ahhh ok. Mines set to 5 or 10 min but maybe it wasn’t picking up the rainfall. I figured it wasn’t the skin calculating it. Thanks :)
