### ISSUE TITLE
wind rose for other time intervals

### ISSUE THREAD

**Issue by windymel** [poblabs/weewx-belchertown#193]
Would it be possible to extend the wind rose so that it works for longer time intervals than one day? I'm really interested to use it to look and weekly, monthly, and yearly trends also. However, it seems that it always plots data for the current day only.

**Comment by poblabs** [comment]
Yes you can set the time spans for the wind rose. Just use [the time_length option](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#time_length).

You can specify the time_length at the top of the graph group so it applies to all graphs within the group, or you can specify it for a specific observation within the group. 

Here I've applied time_length to just the windRose for this example. Today's wind is pretty mild, but you can see how it changes for this month's wind. 

```
[homepage]
    ...normal homepage chart options here...

    [[windrosechart]]
        title = Wind Rose
        time_length = month
        [[[windRose]]]
```

![windrose1](https://user-images.githubusercontent.com/3484775/63649969-794dee80-c712-11e9-9b6f-6f9242b024a7.jpg)
