### ISSUE TITLE
Radial Chart Issues (weatherRange columnrange)

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#195]
Hello Pat
Thanks for this new radial chart. Is there a way to set the tickInterval. I tried both (x and y) and it didn't worked.
```
    [[chart2]]
        title = Radial 2019
        time_length = year
        css_class = "weatherRadial"
        [[[weatherRadial]]]
            xAxis_tickInterval = 0.1
```
![Radial2019](https://user-images.githubusercontent.com/4549674/63689362-20e52280-c7e0-11e9-8dc7-12dd4ac92efc.png)

**Comment by poblabs** [comment]
No not yet. It's very new and more custom than I thought. It needs more
work before fully ready.

Curious, why set the tick interval? The ideas to show the temperature range
columns for one full day over the course of a week, month or year. What
would the tick show?

**Comment by HoracioDos** [comment]
Hello Pat.
mmm You made me doubt about this. I rephrase my question. How can I set less decimal values in this chart? For example. I would like to show low temp = 13,8 and not 13,89999999
Thanks!

**Comment by poblabs** [comment]
Ah yes. That is part of what I need to clean up. The decimals are not being
rounded yet. Soon!

**Comment by poblabs** [comment]
Can you paste your translation labels so i can try to replicate the
encoding?

On the months and their names... Hmm. That's automatically generated by
highcharts. I'll have to look into it. When does your database start? May?

**Comment by poblabs** [comment]
You need to upgrade the dark CSS file too. That was updated recently.

Right now the outTemp is hard coded into the chart because the database
lookup is looking up specific values. I will have to see if there is a way
to make it not hard coded.

**Comment by poblabs** [comment]
What's the link to your site again?

**Comment by HoracioDos** [comment]
It looks perfect now!! Thanks again!
![Radial2019](https://user-images.githubusercontent.com/4549674/63940880-c7c7f980-ca40-11e9-8fb3-4654094c8304.png)

**Comment by poblabs** [comment]
Good news! Also @HoracioDos the labels are being tricky for me. It has to do with the 30 day tick interval on the xAxis. No matter what if I set it lower or higher it doesn't work. 

So maybe the first group is better? Letting Highcharts own the labels and not Belchertown?

Some examples I'm seeing in my testing:

### No xAxis tickinterval and no xAxis label. Highcharts owns the labels. 

Maybe this is the best option? The date formatting looks a little off though. 

![image](https://user-images.githubusercontent.com/3484775/63942265-62bdd500-ca3b-11e9-8603-122de7d2cd4e.png)

![image](https://user-images.githubusercontent.com/3484775/63942298-7a955900-ca3b-11e9-9ad1-90b6d8fc866f.png)

---

### No xAxis tickInterval

This looks bad

![image](https://user-images.githubusercontent.com/3484775/63942217-40c45280-ca3b-11e9-8cfe-6abed1cd62af.png)

**Comment by poblabs** [comment]
Hmm, maybe we need the xAxis tickInterval. Because here's that chart, larger, and it gets ugly without it. 

So I think this may mean if you have less than 30 days of info on the chart, you will not have that month label. 

The data will be there but not the label. 


![image](https://user-images.githubusercontent.com/3484775/63944616-e083df80-ca3f-11e9-993e-4cd9233590a1.png)

**Comment by poblabs** [comment]
I'm expanding this request to add a few more options

* New option for `polar = true` to allow certain charts to be a circle (like windrun or the weather radial)
* Allow different observation types to be charted into the weather radial

I could use your help test. I will try to commit something later today. 


Some samples:

## Weather Radial with `polar = false`
![image](https://user-images.githubusercontent.com/3484775/63972317-7b97ac00-ca76-11e9-9ac1-305958ef39c7.png)


## Weather Radial with `windSpeed` and `polar = true`

![image](https://user-images.githubusercontent.com/3484775/63972377-9d912e80-ca76-11e9-9ece-658a9e463079.png)

**Comment by HoracioDos** [comment]
Hello Pat.
I had a feeling that this issue wasn't going to rest quietly when I opened it. LOL! I feel like a prophet! Just a joke!
I'm perfectly OK with xAxis tick Interval and no month name for an incomplete period.
New features are realy cool!!

**Comment by poblabs** [comment]
Just pushed some updates. More to go, but I think what I have so far is working and allows some flexibility. 

The options are: 

* `polar`: true or false. True creates the circle chart
* `radial_type`: the archive observation to chart

Some chart examples and output:

## Column range chart with outTemp and temperature custom coloring
```
[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial"
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            polar = false
            radial_type = outTemp
```

![image](https://user-images.githubusercontent.com/3484775/63988587-06929980-caab-11e9-8432-d61712bd3a60.png)

## Column range polar chart (circle) with outTemp and temperature custom coloring

```
[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial"
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            polar = true
            radial_type = outTemp
```

![image](https://user-images.githubusercontent.com/3484775/63988609-1e6a1d80-caab-11e9-8beb-52df89605c75.png)


## Column range polar chart with color red defined, and windSpeed graphed

```
[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial"
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            polar = true
            radial_type = windSpeed
            color = red
```

![image](https://user-images.githubusercontent.com/3484775/63988629-3772ce80-caab-11e9-82e8-8305a9c4b7d0.png)

## Column range chart with windGust graphed and no polar, and no color which uses the default colors from graphs.conf

```
[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial"
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            polar = true
            radial_type = windGust
```

![image](https://user-images.githubusercontent.com/3484775/63988717-9df7ec80-caab-11e9-8513-9dcf75188f93.png)

**Comment by HoracioDos** [comment]
I'll try them asap. I think that people with solar panels will love this charts. It seems to be ideal to show charging efficiency.

**Comment by Stormtracker017** [comment]
Looks nice Pat....Are the color ranges hard coded into code or can it be option in the graph.conf file?

**Comment by poblabs** [comment]
@Stormtracker017 They are hardcoded and match the temperature colors represented on the front page.

**Comment by poblabs** [comment]
Here's outside temperature with a color override to orange. 

```
[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial1"
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            polar = true
            radial_type = outTemp
            color = orange
```

![image](https://user-images.githubusercontent.com/3484775/64050079-fb8c4780-cb44-11e9-96eb-fb99c0c9f7a4.png)

**Comment by Stormtracker017** [comment]
Is there a way right now to do Zones in the code?

**Comment by poblabs** [comment]
What do you mean by zones?

**Comment by Stormtracker017** [comment]
If a point "value" falls within a zone, you can change the color that the value represent.  You  can have multiple zones within a plot.

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/color-zones-simple/

**Comment by poblabs** [comment]
@Stormtracker017 No, zones are implemented (doing these columnranges was challenging enough).

**Comment by poblabs** [comment]
Another big update to test! You have to download the entire development package again since I have updated a lot in a lot of files! 

But with the charts, there's a big update in https://github.com/poblabs/weewx-belchertown/commit/b101183c6a5476a44416a67d5386a03f4bdf3fd7 which allows you to control the chart height and width. Just place the height, or width of the chart right in the chart options. 

If height and width are not defined then the charts will be their same default sizes

For example:

```
[day]
    title = Today since Midnight
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000

    [[chart1]]
        width = "100%"
        height = "600px"
        title = Temperature
        [[[outTemp]]]
            name = Temperature
```

And here's the output of **my own** front page with some mixed size graphs. 

![image](https://user-images.githubusercontent.com/3484775/64070821-864e6e80-cc39-11e9-84da-68b8ff734758.png)

**Comment by Stormtracker017** [comment]
With this update we can do columnrange graphs?

**Comment by poblabs** [comment]
@Stormtracker017 Yeah, it's a special chart type for Belchertown because each columnrange requires some specific x, y coordinates and the min/max. So it's not as easy as doing `type = columnrange`. So instead it's a separate observation type (sort of like rainTotal). 

I've tried multiple observations per columnrange chart and it looked cluttered, so for now I'm doing 1 observation per chart for columnrange. 

If you're charting outTemp, then it gets colored based on the temperature color scale within the skin. Otherwise the colors are default and/or from the `color` option. 

**Note**: I'm still tweaking it. The current name for the observation is weatherRadial. I need to change that to weatherRange in the very near future (possibly this afternoon). 

You can see this on the front page of https://belchertownweather.com too. 

Here's an example config:

```
[year]
    # Chart Timespan Defaults
    title = This Year
    show_button = true
    button_text = Year
    tooltip_date_format = "dddd LL"
    type = spline
    time_length = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000
    
    [[chartTestName]]
        title = Temperature Range This Year
        tooltip_date_format = "LL"
        [[[weatherRadial]]]
            radial_type = outTemp
```

![image](https://user-images.githubusercontent.com/3484775/64076065-f38bef00-cc8d-11e9-90b8-b9e53da4a00b.png)

**Comment by poblabs** [comment]
If you want your columnrange to look a little more interesting, add `polar = true` to turn it into a radial. 

I also added new option of `height = "600px" to increase the readability of the radial.

```
[year]
    # Chart Timespan Defaults
    title = This Year
    show_button = true
    button_text = Year
    tooltip_date_format = "dddd LL"
    type = spline
    time_length = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000
    
    [[chartTestName]]
        title = Temperature Range This Year
        tooltip_date_format = "LL"
        height = "600px"
        [[[weatherRadial]]]
            polar = true
            radial_type = outTemp
```

![image](https://user-images.githubusercontent.com/3484775/64076098-3a79e480-cc8e-11e9-8472-b5f9a7157c1d.png)

**Comment by poblabs** [comment]
Alright, if you update to the latest version, `weatherRadial` is now called `weatherRange`, so you'll need to update your graphs.conf file

**Comment by HoracioDos** [comment]
Hello Pat
I'm sorry for the delay. I've got a new job and I'm not as much available as I used to be.
I applied the latest commits and I found this error about encoding in about page. It looks very weird.
```
Sep 14 12:10:51 PiWeewx weewx[5142]: cheetahgenerator: Generate failed with exception '<type 'exceptions.UnicodeDecodeError'>'
Sep 14 12:10:51 PiWeewx weewx[5142]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
Sep 14 12:10:51 PiWeewx weewx[5142]: cheetahgenerator: **** Reason: 'ascii' codec can't decode byte 0xc3 in position 1150: ordinal not in range(128)
Sep 14 12:10:51 PiWeewx weewx[5142]: ****  Traceback (most recent call last):
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Sep 14 12:10:51 PiWeewx weewx[5142]: ****      fd.write(str(compiled_template))
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
Sep 14 12:10:51 PiWeewx weewx[5142]: ****      rc = getattr(self, mainMethName)()
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 104, in respond
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1685, in _handleCheetahInclude
Sep 14 12:10:51 PiWeewx weewx[5142]: ****      file=file)
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 772, in compile
Sep 14 12:10:51 PiWeewx weewx[5142]: ****      settings=(compilerSettings or {}))
Sep 14 12:10:51 PiWeewx weewx[5142]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1708, in __init__
Sep 14 12:10:51 PiWeewx weewx[5142]: ****      source = unicode(source)
Sep 14 12:10:51 PiWeewx weewx[5142]: ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1150: ordinal not in range(128)
```
I know you are busy but don't forget to update the wiki about weatherRadial change to weatherRange.

**Comment by poblabs** [comment]
Hi Horacio. Have you updated all files? Or just a few? I made some updates to make the skin weewx 4 ready, which has encoding in it. 

If you did not update all files, please try that and restart weewx when you can. Then let me know.

**Comment by HoracioDos** [comment]
I updated only the files which were affected by development commits since August 31. I'll sync everything and I'll let you know about it. I'll look for any hidden control character in about.inc just in case too.

**Comment by HoracioDos** [comment]
Hello Pat.
I found the problem. I inserted again these lines in belchertown.py that were removed by this commit.
https://github.com/poblabs/weewx-belchertown/commit/06017be003d107407b9edf3575029de64f2f1a40
```
reload(sys)
sys.setdefaultencoding("utf-8")
```
Almost every text is taken from weewx.conf but I still have some hardcoded text in the about page. 
Everything is normal now. No alerts!

**Comment by poblabs** [comment]
@HoracioDos Congrats on the new job btw!

Those 2 lines won't be supported in Python 3 or weewx 4, so they had to be removed. What we should do is try to fix what is wrong without them. 

At the top of your about.inc add this line:

```
#encoding UTF-8
```

and remove those lines you added. Restart weewx and try again?

**Comment by HoracioDos** [comment]
Excellent!! Problem solved.
Thanks!

**Comment by poblabs** [comment]
Great news! I'll get that added to all the files

**Comment by poblabs** [comment]
I have updated the wiki to include [the `weatherRange` observation](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#the-weatherrange-observation), the [polar option](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#polar), and the [width](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#width) and [height](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#height) options. I am closing this issue as I think everything is resolved now.
