### ISSUE TITLE
Weather Warnings - duplicated or triplicated.

### ISSUE THREAD

**Issue by hindsight2021** [poblabs/weewx-belchertown#197]
Hey there,

Wondering if anyone may know what would cause the weather warnings to populate in duplicate, sometimes triplicate form - since day one, every weather warning will always show up at least duplicated.

The only setting I've applied is enabling the weather warnings in /etc/weewx/weewx.conf - it's only there once in the config file.

Image:

![image](https://user-images.githubusercontent.com/54675389/63948068-6eff5d80-ca4e-11e9-8cf0-0107729bc146.png)

Thanks for any guidance/suggestions!

Regards,
MB

**Comment by poblabs** [comment]
This comes up every now and then and it's not anything to do with the skin, but everything to do with DarkSky. You'll have to contact them to find out what's going on with your lat/lon and those alerts. Sometimes it has something to do with your location to other counties or alert boundaries. All of those links may be separate URLs too. 

What's the link to your site? I can look at your DarkSky data file and double check that.

**Comment by hindsight2021** [comment]
Hey, don't mind the site, it's very (very) much under construction - still
working on getting MQTT communicating over TLS, so bare with me.

That makes sense it would come from Darksky as opposed to the skin, I
couldn't find any lines which could attribute a duplicate/triplicate
warning.

https://kingsclear-studios.com

Appreciate it!

MB

**Comment by poblabs** [comment]
Just took a look at your DarkSky JSON data file, and it's showing the 6 alerts. So the skin is "doing it's job" displaying the data it's given. 

I agree, 6 alerts for only 2 or 3 real alerts is overkill. It happens to me too. I guess I've come to ignore it 😃 

I'm not sure what DarkSky's formula is on identifying that but you should be able to email them from your DarkSky account to find out what's going on.

**Comment by hindsight2021** [comment]
Awesome, that is exactly the lead I needed, thank you for your time on this!
___________________________

Kingsclear Studios
Fredericton, New Brunswick
1(506)-803-9496

**Comment by poblabs** [comment]
You're welcome. I'd just send them the sample URL from your developer page, at the very bottom are the "alerts" array and you can use that to ask them why you have 6 of them.  If you get a good answer let me know. Maybe I'll add it to the FAQ for the skin! Good luck!

**Comment by hindsight2021** [comment]
Hey,

Any chance you're using a depreciated API from Darksky? Just spitballing :)

I found this:
https://status.darksky.net/2017/05/12/bug-fixes-current-conditions-alerts.html

" The API would occasionally report duplicate severe weather alerts for
some locations. This is because several of our sources for severe weather
alerts organize alerts by region, may report the same alert for multiple
regions, and these regions may occasionally overlap. Our system now detects
this and filters out the copies."

Do you know where I find find the API call for this data? I can provide it
to Darksky and get them to look into that part.

___________________________

Kingsclear Studios
Fredericton, New Brunswick
1(506)-803-9496

**Comment by poblabs** [comment]
hmm. I don't think so?

If you go to your developer page at DarkSky and it says "Sample API Call", it has a link like this: https://api.darksky.net/forecast/<my_key_here>/37.8267,-122.4233

I'm taking [that API link, substituting your key within the brackets, adding in the local units, language and location flags, then doing a download of that file, saving it locally](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py#L503-L514), and using that file for your website visitors so you don't hit the API rate limit (and start getting billed for the overages). 

That link you sent doesn't necessarily say I have to switch to anything different, it just says:

> Our system now detects this and filters out the copies.

So I think for the skin, it's doing what it should be doing. 


For reference, the DarkSky data is saved to your weewx's HTML directory's Belchertown `/json/` folder in darksky_forecast.json. Then at the bottom is the "alerts" section.

**Comment by poblabs** [comment]
You may want to save a copy of the `darksky_forecast.json` file because it will get overwritten every `forecast_stale` interval (Belchertown defaults this stale interval to 59 minutes). So if you're going to chase them down, you may want to reference to point-in-time forecast data by having that file saved.

**Comment by hindsight2021** [comment]
Thank you!
___________________________

Kingsclear Studios
Fredericton, New Brunswick
1(506)-803-9496

**Comment by hindsight2021** [comment]
Hi there,

sorry to bother - but I've debugged this issue to the best of my ability,
and I'm not sure where else to turn.
Not the same issue as before - currently my MQTT connection unexpectedly
closes, and I cannot figure out why.

I followed the procedure to add new sensors, and they're being picked up
without issue via site/MQTT, but now, there is something going on with
belchertown.js and it causes my MQTT connection to force itself closed, and
it throws different properties (sensor errors) in various browser consoles
(Chrome, FF, Edge).

such as:

2 September 2019, 17:51:06: mqtt Connection Lost: AMQJS0005E Internal
error. Error Message: Cannot read property 'windSpeed' of undefined, Stack
trace: TypeError: Cannot read property 'windSpeed' of undefined
    at https://kingsclear-studios.com/js/belchertown.js?1567457455:713:147
    at Array.forEach (<anonymous>)
    at HTMLSpanElement.<anonymous> (
https://kingsclear-studios.com/js/belchertown.js?1567457455:700:27)
    at Function.each (
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:2573)
    at w.fn.init.each (
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:1240)
    at update_current_wx (
https://kingsclear-studios.com/js/belchertown.js?1567457455:696:50)
    at k.onMessageArrived (
https://kingsclear-studios.com/js/belchertown.js?1567457455:656:5)
    at k._receiveMessage (
https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:517
)
    at k._receivePublish (
https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:71
)
    at k._handleMessage (
https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:47:379
)

This time is shows "windSpeed" other times it will show other various
sensors/properties.

Any hints as to what's going on?

Site: kingsclear-studios.com
JS: kingsclear-studios.com/js/belchertown.js

Thanks a million!
MB
___________________________

Kingsclear Studios
Fredericton, New Brunswick

**Comment by poblabs** [comment]
Moving this to a new issue

**Comment by poblabs** [comment]
Actually, I can't open it on your behalf. Can you open a new issue for tracking?

**Comment by hindsight2021** [comment]
Hey, just. Small update I thought I would share, seems they recognize it’s a localization issue, needing to be patched - for general info :)

Cheers,
MB

> From: Dark Sky Developer Support <developer@darksky.net>
> Date: September 5, 2019 at 8:42:33 PM ADT
> To: Kingsclear Studios 
> Subject: Re: API/Duplicate Weather Alerts
> 
> Hi,
> 
> Apologies for the delay in response on your issue. Thank you for taking the time to write in!
> 
> I see what you mean, it's still occuring. It seems that the alerts are just different enough in their description that we let the duplicates slipped through the cracks (the issue resolved had to do with 1:1 text matching alerts which is much easier to resolve). I'll pass this issue along and we'll try to address it as soon as we find an appropriate approach to recognizing duplicates with slightly different descriptions.
> 
> 
> Take care,
> Antoniya Statelova 
> 
> The Dark Sky Company

___________________________
"Sent from my mobile device"
