### ISSUE TITLE
Column Table Time Format Issue Maybe

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#198]
I have been working with data labels for columns and noticed that the time format that data is being display is UTC.  This could be an issue with my conf, but different graphics without labels are displaying correctly. Also having an issue with yaxis min and max.

[Temperature_Data] 
        
       title = Monthly High / Lows
       show_button = true 
       button_text = "Temperature"
       
       [[Temp_Sort_By_Month]]
       
          type = column
          tooltip_date_format = "dddd LL"
          time_length = year
          aggregate_interval = 86400 # 1 day
          gapsize = 86400000
          xaxis_groupby = month
          xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
          yAxisLabel = Temperature ( °F )
          yaxis_min = -30
          yaxis_max = 130
          
          [[[outTemp]]]
          
             name = Temperature (Max)
             aggregate_type = max
             
            
             [[[[dataLabels]]]]
       
                 enabled = true
                 format = '{y:.1f}'
              
             [[[[[style]]]]]
               
                  color = "#808080"
                  fontSize = 8px
                  fontWeight = normal
                  textOutline = false
            
         [[[outTemp_min]]]
         
            name = Temperature (Min)
            observation_type = outTemp
            aggregate_type = min
            
           [[[[dataLabels]]]]
       
               enabled = true
               format = '{y:.1f}'
              
              [[[[[style]]]]]
               
                   color = "#808080"
                   fontSize = 8px
                   fontWeight = normal
                   textOutline = false
              
        [[[dewpoint]]]
            name = Dewpoint (Max)
            aggregate_type = max
            
            [[[[dataLabels]]]]
       
              enabled = true
              format = '{y:.1f}'
              
              [[[[[style]]]]]
               
                   color = "#808080"
                   fontSize = 8px
                   fontWeight = normal
                   textOutline = false
                   
         [[[dewpoint_min]]]
            name = Dewpoint (Min)
            observation_type = dewpoint
            aggregate_type = min
            
            [[[[dataLabels]]]]
       
              enabled = true
              format = '{y:.1f}'
              
              [[[[[style]]]]]
               
                   color = "#808080"
                   fontSize = 8px
                   fontWeight = normal
                   textOutline = false

Thanks
Rich
![Monthly High Low Temps](https://user-images.githubusercontent.com/48191231/64071242-e64a1280-cc43-11e9-93af-aa17390a7d40.png)

**Comment by poblabs** [comment]
Were you able to resolve this?

**Comment by Stormtracker017** [comment]
Pat

No I did not resolve this issue, if it is an issue.  It seems to happen at
the end of the month when UTC switches over to the next month.  I won't be
around during that timeframe this month to verify this issue.  I will look
to see if it is a issue next month.

Thanks
Rich
