### ISSUE TITLE
syntax problem : dewpoint

### ISSUE THREAD

**Issue by f4gqk** [poblabs/weewx-belchertown#199]
Hello,

I use the utf8 encoding and I translated my page on the weewx.conf file.

But I have an error concerning the dew point:

www.roverch.fr/weather/Belchertown

<a href="http://zupimages.net/viewer.php?id=19/35/l7bq.jpg"><img src="https://zupimages.net/up/19/35/l7bq.jpg" alt="" /></a>

I find an extra character.

How to remove it ??

Thank you
Sébastien

**Comment by poblabs** [comment]
Can you provide more detail like a link to your site and the version number?

Also your language there's not much for me to go on here

**Comment by poblabs** [comment]
I see you edited your post, but I am not able to reach that website. Is that the correct link?

**Comment by f4gqk** [comment]
My Website is : <a href="http://www.roverch.fr/weather/Belchertown">

WeeWX version: 3.9.2
Belchertown Skin Version: 1.0.1

In skin.conf 

` [[Labels]]
        # This section sets a label to be used for each type of unit.

        centibar          = " cb"
        cm                = " cm"
        cm_per_hour       = " cm/hr"
        degree_C          =  " Â°C"
        degree_F          =  " Â°F"
        degree_compass    =   Â°
`

**Comment by poblabs** [comment]
I'm confused. You have `" Â°C"` in your `degree_C`. That is what the website is showing. 

So what is wrong?

![image](https://user-images.githubusercontent.com/3484775/64079112-8ee28b80-ccb1-11e9-97f2-bfab6350184e.png)

**Comment by f4gqk** [comment]
Yes on my skin.conf file I have 

> 
 degree_C          =  " Â°C"

>

**Comment by poblabs** [comment]
And that is what is showing on the webpage. Can you explain what is wrong? I am confused.

**Comment by f4gqk** [comment]
My web page shows what is on the picture above.

Â°C 

I find the same syntax in the skin.conf file


when I execute the following command : 

> tail -f 

> /var/log/messages

I have the following error

> UnicodeDecodeError:` 'utf8' codec can't decode byte 0xb0 in position 4: invalid start 

> byte

**Comment by poblabs** [comment]
Can you remove the `Â` from your skin.conf?

**Comment by f4gqk** [comment]
when I edit the file skin.conf the file my web page is no longer updated every 10 minutes

**Comment by poblabs** [comment]
Removing that A character would not break that functionality.

I'm not sure why that character is there to begin with.

It might make sense to remove everything and reinstall the skin.

I've never seen this before so I'm very confused.

**Comment by poblabs** [comment]
You have some other issues going on. 

Your forecasts are not loading. 

The forecasts not loading is breaking your website. 

Look in your syslog or your HTML Directory to find out why the forecast file is not downloading. 

Again, I need more information. 

Full log traces, full configurations, something other than `Â`. 

If it's easier to troubleshoot en francais, maybe @olpayras can help us.

**Comment by olpayras** [comment]
If there's a syntax error in a file, cheetahgenerator doesn't produce the page. Can you zip your /etc/weewx folder and attach it to you next post, it will be easier for me to check what happen.

**Comment by f4gqk** [comment]
my file was in / home

It's serious or not?

I need to put it in / etc?

You can load my weewx.zip file here:

http://dl.free.fr/k8wLlGxhA

thanks

**Comment by olpayras** [comment]
It depends how you install weewx. I think you have installed weewx manually, not by using your linux distribution repository.

I just download you file. Quickly, I edit your weewx.conf file, and there's an encoding trouble so all commas have erroneous transcription, so UTF8 convertor cannot translate them in readable caracters. I'll tell you more tomorrow. But can you already tell me which editor you use ?

**Comment by olpayras** [comment]
I think you used a windows text editor like notepad. It translates all unicode in DOS format wich isn't the same than unix like. I advise you to edit your text file with notepad++ which doesnt convert but keep original file or use a linux/unix editor. You shouldn't have troubles using this method.

**Comment by f4gqk** [comment]
Oui Olivier,

J'ai pris en compte le soucis de problème, j'utilisais nano ( depuis quelques jours )  et maintenant notepad+++ Auparavant l'éditeur WinSCP ( donc pas bon ). 


Quand on reprend la première image pour illustrer le problème, on a une erreur de syntaxe à droite dans le cadre. Alors qu'a gauche, on retrouve des températures en degré celsius et là il y a pas de problème.

J'ai remplacer "°C" par "degré pour tester ça fonctionne.

C'est la partie "Stations Observations" qui pose problème dans skin.conf

**Comment by olpayras** [comment]
Effectivement je crois que l'éditeur de Winscp que je ne n'utilise pas pour cette raison fait un peu ce qu'il veut...

Tu n'as pas à modifier skin.conf. Personnellement toute ma traduction est dans weewx.conf. Le mieux dans ton cas, sinon on va pas trouver, c'est de repartir les fichiers originaux et de refaire ta traduction uniquement dans weewx.conf. Par contre weewx.conf n'étant pas un fichier de configuration dynamique, il te faut relancer weewx une fois le fichier modifié si tu veux voir les modifications apparaitre.

Au final pour éviter tout problème lié à des caractères malformés, vérifie dans nano qu'ils soient correctement transcris.

La seule chose que tu auras à modifier dans **skin.conf** s'il reste des accents malformés c'est cette ligne :

`encoding = html_entities`

à remplacer par :

`encoding = utf8`

**Comment by f4gqk** [comment]
Merci à vous.

J'ai tout réinstallé et cela fonctionne très bien. J'ai fait l'erreur d'utiliser WinSCP qui m'a modifié mon fichier de base et crée des erreurs.
