### ISSUE TITLE
Truncate reading at Highchart cursor points

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#2]
Readings at the the cursor points on some Highcharts can be up to 16 digits after the decimal place, making for very long and not very useful numbers. Can these be truncated to perhaps 2 decimal places to make readings more meaningful.

May now only be a problem on /Graphs weekly rainfall

**Comment by poblabs** [comment]
I've noticed this too, and I'm not quite a highcharts expert. Some options I've tinkered with haven't fixed it but I'll keep seeing what I can figure out

**Comment by 41south** [comment]
You fixed the majority of these sometime after 0.1 release, I think this is the last one that is long

**Comment by poblabs** [comment]
Fixed in https://github.com/poblabs/weewx-belchertown/commit/15d5da817b8640a3e7a73f312bfda5e7c7f35399
