### ISSUE TITLE
MQTT/JS errors all of a sudden, was working fine.

### ISSUE THREAD

**Issue by hindsight2021** [poblabs/weewx-belchertown#200]
Hi there,

sorry to bother - but I've debugged this issue to the best of my ability, and I'm not sure where else to turn. Currently my MQTT connection unexpectedly closes, and I cannot figure out why. It was working flawlessly the week before, using mosquitto broker, and is still publishing now.

I followed the procedure to add new sensors (wiki), and they're being picked up without issue via site/MQTT, but now, there is something going on with belchertown.js and it causes my MQTT connection to force itself closed, and it throws different properties (sensor errors) in various browser consoles (Chrome, FF, Edge).

such as:

2 September 2019, 17:51:06: mqtt Connection Lost: AMQJS0005E Internal error. Error Message: Cannot read property 'windSpeed' of undefined, Stack trace: TypeError: Cannot read property 'windSpeed' of undefined
    at https://kingsclear-studios.com/js/belchertown.js?1567457455:713:147
    at Array.forEach (<anonymous>)
    at HTMLSpanElement.<anonymous> (https://kingsclear-studios.com/js/belchertown.js?1567457455:700:27)
    at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:2573)
    at w.fn.init.each (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:1240)
    at update_current_wx (https://kingsclear-studios.com/js/belchertown.js?1567457455:696:50)
    at k.onMessageArrived (https://kingsclear-studios.com/js/belchertown.js?1567457455:656:5)
    at k._receiveMessage (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:517)
    at k._receivePublish (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:71)
    at k._handleMessage (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:47:379)

This time is shows "windSpeed" other times it will show other various sensors/properties.

Any hints as to what's going on?

Site: kingsclear-studios.com
JS: kingsclear-studios.com/js/belchertown.

I’m just not quite sure how to debug this error further, I’m sure it’s my fault 😁

Thanks a million!
MB
___________________________

**Comment by poblabs** [comment]
I see the error and I see the line of code it's not happy with, but I don't get why it's happening. I'll try and replicate it.

**Comment by hindsight2021** [comment]
Appreciate your help, I was blindsided by this one. I was so close to being done - finally. Haha.

 I reverted to a backed up copy of weewx.conf, but it had no effect on the issue, strangely.
MB

**Comment by poblabs** [comment]
I'm able to replicate this, and I'm have no idea what's going on 😃  I'm going to need some time with it after my kid goes to bed.

**Comment by hindsight2021** [comment]
No worries, thanks for your expertise, I owe you a coffee (or two) depending where this leads haha!

**Comment by poblabs** [comment]
The only way (so far) that I've replicated this was on my 1.1 beta site. 

I see you're running 1.0.1. Did you have 1.1 beta installed at some point?

**Comment by hindsight2021** [comment]
Not to my knowledge.
This was my first ever install.

**Comment by poblabs** [comment]
Ok, let me spin up a vanilla virtual machine, install fresh and see what happens.

**Comment by hindsight2021** [comment]
I was playing around, and I found an old copy of index.html I saved earlier
from an attempt to test some customization's in sandbox, and amazingly - it
still connects without error - I suspect the answer may lie in these two
index.html files, hmm...

https://kingsclear-studios.com/testindex/

something to work with for now if that helps!

___________________________

Kingsclear Studios
Fredericton, New Brunswick803-9496

**Comment by poblabs** [comment]
That may help, but viewing the website will strip some code out. Can you instead zip them up, maybe like index_broken.html.tmpl and index.html.tmpl and drag and drop them here?

![image](https://user-images.githubusercontent.com/3484775/64136109-3e585480-cdbd-11e9-9309-47dad199deec.png)

**Comment by poblabs** [comment]
I also notice that your lightning data on your homepage doesn't have `rounding` information available. I suspect that's the problem, we need to update your weewx.conf with that data, but I wanted to try and test that theory.

**Comment by hindsight2021** [comment]
Finally got around to it - unusually busy tonight.

Attached are labelled as the index file working when used, and the one not working when used which is my main index.html for the skin at: kingsclear-studios.com

my working index.html is in my sandbox (of course): kingsclear-studios.com/testindex

[index_Files.zip](https://github.com/poblabs/weewx-belchertown/files/3567365/index_Files.zip)

Cheers!

**Comment by poblabs** [comment]
Thanks, this looks like the parsed html from Cheetah though, which is missing raw code that I may need. 

Did you edit the raw code, or the processed html in the HTML dir?

(For example, the line `update_outtemp_C( "14.9" );` is processed, because [it should say](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L39-L43):
```
#if $unit.unit_type.outTemp == "degree_F"
            update_outtemp_F( "$current.outTemp.formatted" );
            #else
            update_outtemp_C( "$current.outTemp.formatted" );
            #end if
```
I'm just trying to find the exact changes you made to the raw code)

Aside from that though; the 2 files look very similar except for the slight changes in logo, forecast and temperature.

**Comment by hindsight2021** [comment]
I may have, by accident... I’ll take a look, thanks!

**Comment by poblabs** [comment]
No worries. For what it's worth I'm not able to replicate this on a fresh weewx install, with a fresh Belchertown 1.0.1 install. So it's probably something you changed 😃 (especially since it's working for you)

**Comment by hindsight2021** [comment]
Oddly enough, I connected to the site this AM, and the MQTT processing
resumed on its own.
I did not make any changes yet, was just in the process of investigating
when it seemed to revert.

Those code gremlins....

Thanks for your help!
I think this can be closed for now.

Regards,
MB
___________________________

Kingsclear Studios
Fredericton, New Brunswick

**Comment by poblabs** [comment]
Strange indeed but I'll take it as a small win (for now)! If it happens again, re-open this issue through the website and we can dig in again.
