### ISSUE TITLE
 Missing graphics

### ISSUE THREAD

**Issue by f4gqk** [poblabs/weewx-belchertown#201]
Hello,

On my home page, Highcharts graphics no longer appeared.
Nothing is displayed.

It was done in two stages 👍
- At the beginning, we were at the end of August and the last synchronization was on August 4th
- and then nothing more than the option highcharts_enabled = 1

thanks

Traduction : 

Bonjour,

Sur ma page d'accueil, les graphiques Highcharts n’appairaient plus.
Rien n'est affiché.

Cela s'est fait en deux temps 👍 
- Au début, on était à la fin du mois d’Août et la dernière synchronisation datait du 4 août
- et ensuite plus rien malgré que l'option highcharts_enabled = 1

merci

**Comment by norecords** [comment]
Hi, 
Do you made some upgrade, what version of Belchertown and weewx do you use ?
What the logs files say ?
Can you post some logs, can we reach your station by url ?

Best regards.

Salut,
As-tu fait une mise à jour, quelle version de Belchertown et de weewx utilises-tu ?
Peux-tu poster des évenements de ton journal, et a quelle adresse pouvons-nous voir ta station ?
(c'est un peu court comme explications..)

Cordialement.

**Comment by norecords** [comment]
aux vues de ton report #199 
tu dois avoir un sacré problème de syntax/encodage de caractère ...
Je pense que tu devais reprendre ton installation depuis le début avec un éditeur de texte qui tienne la route ;)

**Comment by f4gqk** [comment]
Merci à tous.

C'est résolu. J'ai tout réinstallé. Merci à toi et à Olivier
