### ISSUE TITLE
Update every hour

### ISSUE THREAD

**Issue by f4gqk** [poblabs/weewx-belchertown#202]
I reinstalled all my system weewx and belchertown.

Since the web update is done every hour or so, where as before it was every ten minutes.

The problem is not only about belchertown but also about my other skin:

other skin: http://roverch.fr/weather/

belchertown skin:

http://roverch.fr/weather/Belchertown/

Is there a parameter that manages this update on weewx.conf for example ???

Thanks

Sébastien

**Comment by poblabs** [comment]
What is your `archive_interval` in weewx.conf set to?

**Comment by f4gqk** [comment]
Hi,

archive_interval in weewx.conf is 300 

Sébastien

**Comment by poblabs** [comment]
Strange. This might be another one to ask on the user forums. I am not sure.

**Comment by poblabs** [comment]
Closing
