### ISSUE TITLE
 change values ​​in BDD

### ISSUE THREAD

**Issue by f4gqk** [poblabs/weewx-belchertown#203]
Is there a tool to change values ​​in the database?

`datetime - min - mintime - max - maxtime - sum - count - wsum - sumtime `

I would like to change the value

appTemp added recent with the WindChill value felt that day.

Temp : 41.7°C
Wind : 22 km/h
WindChill : 47,5 °C

Thanks

**Comment by poblabs** [comment]
This is not a Belchertown skin issue. Please ask this in the [weewx-user forums](https://groups.google.com/forum/#!forum/weewx-user)

I'd like to keep this GitHub site focused on Belchertown only.
