### ISSUE TITLE
Plots don't load on first visit to homepage

### ISSUE THREAD

**Issue by windcrusader** [poblabs/weewx-belchertown#204]
I have an issue where the plots on the homepage don't show up the first time the site loads. If I then go into the graphs page, and then back to the homepage, the graphs load.

I'm not sure if this is a browser issue, or a server issue, or an issue with the skin. Thought I'd log here to see if you have seen this before and know what the fix is.

My site is at:
https://mpyc.nz/weather/

**Comment by poblabs** [comment]
Have not seen this before. They loaded for me straight away though.

**Comment by windcrusader** [comment]
What browser do you use? I’ve been seeing the issue with Safari and Chrome.

**Comment by poblabs** [comment]
On my phone I was on Android and using Chrome. 

On my PC I am using Chrome & Firefox and they loaded fine. They were a bit slow to load for me (maybe 1.5 seconds) but I am attributing that to you being in New Zealand.

**Comment by poblabs** [comment]
On my phone I was on Android and using Chrome.

On my PC I am using Chrome & Firefox and they loaded fine. They were a bit slow to load for me (maybe 1.5 seconds) but I am attributing that to you being in New Zealand (opposite side of the world from my location).

**Comment by windcrusader** [comment]
Hmmm, seems to be isolated to a Safari browser issue. Maybe a javascript block or something. I’ll keep investigating.

**Comment by poblabs** [comment]
Your site loads graphs on Safari for me as well. No issues. 

Does [my site](https://belchertownweather.com/go/belchertown) load graphs for you on first visit?

**Comment by poblabs** [comment]
Any luck?

**Comment by windcrusader** [comment]
No, it still happens fairly consistently but I don’t know why. I had a friend also report the same thing, but it seems isolated to New Zealand at this stage as you can’t replicate.

**Comment by steepleian** [comment]
Brad,
Have you tried installing Highcharts locally rather than making remote
calls to the Highcharts servers? This would remove the factor of your
geographical location being a cause.

Highcharts is free to use for non-commercial use (
https://shop.highsoft.com/noncomform)

Ian

**Comment by poblabs** [comment]
Ian, good idea and worth a try. 

@windcrusader For a very quick test, you can download these files and add them to your public_html folder directly, then change the path in the header.html.tmpl file to make the link. 

Do you also have trouble loading @41south's site? http://41south.net.nz/ He is in NZ, and his charts also work for me without issue.

**Comment by steepleian** [comment]
Pat,
They work for me here fine (in France on vacation).

**Comment by windcrusader** [comment]
Hi all,

I will see if having the files locally makes a difference. The 41 South
site graphs loaded first time.

Brad

**Comment by windcrusader** [comment]
One other difference of my site is that I'm not using the forecasts - could
that play a role somehow?

Brad.

**Comment by poblabs** [comment]
No, I wouldn't think so based on the fact that they are loading for me (on first visit), and on 2nd visit for you. If there was a conflict because forecasts was disabled, then I'd expect them to not load at all.

**Comment by poblabs** [comment]
Is this still an issue for you?

**Comment by poblabs** [comment]
Closing as this has gone idle.
