### ISSUE TITLE
extratemp1 not being converted to Celsius

### ISSUE THREAD

**Issue by wwray** [poblabs/weewx-belchertown#205]
Hi there, I really like your new version of the skin. I've been using it for a while and was really excited to see customizable charts in v1.0

I'm having a little wierd problem tho. My site is http://www.wraynet.com and the last chart is my tower sensors (acurite) that measure inside temperature. The inTemp one is converted to C but the extratemp1 is displaying in F. You can see weewx converts it correctly on the default skin http://www.wraynet.com/weewx/

Any thoughts? Thanks!

**Comment by poblabs** [comment]
Glad you're enjoying the skin. Haven't seen this one before. I'll have to see if I can replicate it somehow to see what's happening. Can you share your graphs.conf config for the `Inside Temps` chart?

**Comment by wwray** [comment]
Thanks for the reply. Here it is..


     [[chart6]]
 title = Inside Temps
 [[[inTemp]]]
     name = Inside Temprature downstairs
     color = blue
  [[[extratemp1]]]
      name = Garage temp
      color = yellow

**Comment by norecords** [comment]
hi wwray,
you have a capital error, extraTemp is with T
```
  [[chart6]]
    title = Inside Temps
    [[[inTemp]]]
      name = Inside Temprature downstairs
      color = blue
    [[[extraTemp1]]]
      name = Garage temp
      color = yellow
```

**Comment by wwray** [comment]
That was the problem thanks! I had to restart weewx to get the change to take. I appreciate the help!

**Comment by norecords** [comment]
Normally with graphs.conf modification you don't have to restart weewx, just wait for the next archive or run `wee_reports`
Glad to ear that your problem is solved.
Cheers
