### ISSUE TITLE
belchertown.py error on wee_reports

### ISSUE THREAD

**Issue by billlariv** [poblabs/weewx-belchertown#206]
I am not getting belchertown running on my pi.  I am currently getting an error we I run wee_reports.  I guess that is why I have no files being created in my belchertown directory.  I am getting the following error on wee_reports.

root@WEEWX:/etc/weewx# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 976, in run
    minstamp, maxstamp = archiveDaySpan( self.timespan.stop )
TypeError: 'NoneType' object is not iterable

**Comment by poblabs** [comment]
Please attach your database to this issue

**Comment by billlariv** [comment]
[wholebackup-1497830683.sql.gz](https://github.com/poblabs/weewx-belchertown/files/3655317/wholebackup-1497830683.sql.gz)

**Comment by poblabs** [comment]
Which version of the skin are you using? It'll say in the syslog when it runs. Or view the source of your website and it'll be at the bottom of the page.

**Comment by billlariv** [comment]
Well the site doesn't load the skin, but the compressed file is 1.0.1.

**Comment by billlariv** [comment]
I am trying to run it in parallel with the Seasons skin, so using a sub directory for belchertown.  The web pages are never created, so thought this may be the issue.

**Comment by poblabs** [comment]
No, there's something in the database that I need to account for. Haven't had the time to catch it yet but will update you when I think I have something. Probably a day or so

**Comment by billlariv** [comment]
I am using Acurite WX Station with interceptor extension.  Not sure if that helps, but want to give as much info as I can to help.

**Comment by billlariv** [comment]
root@WEEWX:/etc/weewx# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 976, in run
    minstamp, maxstamp = archiveDaySpan( self.timespan.stop )
TypeError: 'NoneType' object is not iterable
root@WEEWX:/etc/weewx# ls /var/www/weewx/belchertown/
about                     favicon.ico  images  json  pi       reports     style.css

**Comment by poblabs** [comment]
Using your database, I'm not able to replicate your exact error; although I did get a new error. 

Your database did not include the archive summary tables. Such as archive_day_outTemp, archive_day_outHumidity, and so on. Do you want to run another full backup including those tables and I can try again?


Here's the error not related to your issue which I received, which I'll work on a fix for. 

```
Sep 27 00:19:44 btown206 wee_reports[8326]: Belchertown Extension: version 1.0.1
Sep 27 00:19:44 btown206 wee_reports[8326]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
Sep 27 00:19:44 btown206 wee_reports[8326]: cheetahgenerator: **** Ignoring template /home/weewx/skins/Belchertown/json/weewx_data.json.tmpl
Sep 27 00:19:44 btown206 wee_reports[8326]: cheetahgenerator: **** Reason: a float is required
Sep 27 00:19:44 btown206 wee_reports[8326]: ****  Traceback (most recent call last):
Sep 27 00:19:44 btown206 wee_reports[8326]: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 332, in generate
Sep 27 00:19:44 btown206 wee_reports[8326]: ****      fd.write(str(compiled_template))
Sep 27 00:19:44 btown206 wee_reports[8326]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Sep 27 00:19:44 btown206 wee_reports[8326]: ****      rc = getattr(self, mainMethName)()
Sep 27 00:19:44 btown206 wee_reports[8326]: ****    File "_home_weewx_skins_Belchertown_json_weewx_data_json_tmpl.py", line 1216, in respond
Sep 27 00:19:44 btown206 wee_reports[8326]: ****  TypeError: a float is required
Sep 27 00:19:45 btown206 wee_reports[8326]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
Sep 27 00:19:45 btown206 wee_reports[8326]: cheetahgenerator: **** Ignoring template /home/weewx/skins/Belchertown/js/belchertown.js.tmpl
Sep 27 00:19:45 btown206 wee_reports[8326]: cheetahgenerator: **** Reason: a float is required
Sep 27 00:19:45 btown206 wee_reports[8326]: ****  Traceback (most recent call last):
Sep 27 00:19:45 btown206 wee_reports[8326]: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 332, in generate
Sep 27 00:19:45 btown206 wee_reports[8326]: ****      fd.write(str(compiled_template))
Sep 27 00:19:45 btown206 wee_reports[8326]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Sep 27 00:19:45 btown206 wee_reports[8326]: ****      rc = getattr(self, mainMethName)()
Sep 27 00:19:45 btown206 wee_reports[8326]: ****    File "_home_weewx_skins_Belchertown_js_belchertown_js_tmpl.py", line 145, in respond
Sep 27 00:19:45 btown206 wee_reports[8326]: ****  TypeError: a float is required
Sep 27 00:19:45 btown206 wee_reports[8326]: cheetahgenerator: Generated 12 files for report Belchertown in 1.43 seconds
Sep 27 00:19:45 btown206 wee_reports[8326]: copygenerator: copied 31 files to /home/weewx/public_html/belchertown
```

**Comment by billlariv** [comment]
[full_wee.tar.gz](https://github.com/poblabs/weewx-belchertown/files/3660380/full_wee.tar.gz)

**Comment by billlariv** [comment]
getting the following now when I run wee_reports.
root@WEEWX:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 285, in get_extension_list
    at_outTemp_max_range_max_tuple = (at_outTemp_max_range_query[3], outTemp_unit, 'group_temperature')
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by billlariv** [comment]
weewx.conf 
    [[Highcharts_Belchertown]]
        HTML_ROOT = /var/www/weewx/belchertown
        skin = Highcharts_Belchertown

    [[Belchertown]]
        HTML_ROOT = /var/www/weewx/belchertown
        skin = Belchertown
        enable = true
        theme = dark

        [[[Extras]]]
            forecast_enabled = 1
            darksky_secret_key = mykeyhere
            darksky_units = auto
            darksky_lang = en

**Comment by poblabs** [comment]
Thanks. It's all related to your database. I'll try your new update.

**Comment by poblabs** [comment]
You new database is giving me the same error I have. I'm not yet able to replicate your error, but I do have another one to fix. I'll keep looking.

**Comment by poblabs** [comment]
Strange. Still not able to replicate your error after fixing a fringe `NoneType` error I was seeing. Belchertown loaded your database fine, and even charted for me. 

What's your lat/lon?

What version of weewx are you on?

Your error is this:
```
minstamp, maxstamp = archiveDaySpan( self.timespan.stop )
TypeError: 'NoneType' object is not iterable
```

Which indicates it can't find your start of day and end of day. I'm a bit lost on this one right now.

![image](https://user-images.githubusercontent.com/3484775/65735452-7ba2c000-e0a5-11e9-8e92-e084b8008804.png)

**Comment by poblabs** [comment]
Is this still an issue for you?

**Comment by billlariv** [comment]
I gave up.  thanks for the help.
