### ISSUE TITLE
Invisible graph lines

### ISSUE THREAD

**Issue by oliveres** [poblabs/weewx-belchertown#208]
Hi, on my site is graph lines invisible, but if I move mouse over graph, I see that data are ok.

<img width="615" alt="Snímek obrazovky 2019-10-05 v 22 55 53" src="https://user-images.githubusercontent.com/31700240/66260760-6a536500-e7c3-11e9-952e-cbc5e2ce8a21.png">

**Comment by poblabs** [comment]
Take a look at adjusting your [gapSize setting](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#gapsize).

**Comment by oliveres** [comment]
It works! Thank you.
