### ISSUE TITLE
weatherRange, weatherRadial

### ISSUE THREAD

**Issue by ZXant** [poblabs/weewx-belchertown#209]
Pat

Trying to reproduce Temperature Range as in Belchertown Weather website. Tried the following as posted in Graph Wiki:

[weatherRadialGraphGroup]
    title = Temperature Range Radial
    show_button = true
    button_text = Weather Radial
    time_length = year

    [[radialChartName]]
        title = This Year
        css_class = "weatherRadial"
        [[[weatherRange]]]
            range_type = outTemp

But upon 'wee_reports", gets "NoColumnError: no such column: weatherRange" error.

As the above, tried many combinations of "weatherRange vs weatherRadial", as there are some mix information (as even mentioned in another post that "will rename" as Range might be better suitable).

Must somehow expand Database to include "weatherRange", or update to more recent commit? (using released skin vs-1.0.1).

Thanks,
Xant

**Comment by poblabs** [comment]
As mentioned in the wiki that weather range observation type is only
available in version 1.1.

if you want to try it out feel free to upgrade to the development branch.

**Comment by ZXant** [comment]
Ops.... yes, you did mention. Apologies for missing note, as not noted in reference to development branch. Will try. Thx
