### ISSUE TITLE
All Time Rain Records Wrong after Data Import

### ISSUE THREAD

**Issue by bh314** [poblabs/weewx-belchertown#21]
Installed weeWX & Belchertown, collected data for a few hours, and everything looked good.  I then stopped weeWX and imported CSV data from 2009 to present.  Most of the All Time Records looked okay except for Rain.  "Month with Highest Total Rainfall" lists July 2009 (second month of imported data) as 29.25 in.  "Total Rainfall for" lists 2009 as 161.51 in.  Analyzing the data with Excel before importing, shows that July 2009 should be 2.92 in.  Also, 2009 total should be around 8 in.  The NOAA Reports generated by Belchertown show July 2009 as 2.92 in and 2009 total rain as 8.38.

**Comment by bh314** [comment]
I replaced the belchertown.py file and was initially getting errors (something about station_url).  I then made sure I had updated all files since the .7 release and the errors went away.  Unfortunately, the All Time Rain Records do not seem to have updated to correct values.  It has run for several hours and I have also run wee_reports a few times.  Please let me know if there is anything I can do to help debug the problem (log files, etc.).

**Comment by poblabs** [comment]
@bh314 To confirm, you're seeing this section as wrong? 

![image](https://user-images.githubusercontent.com/3484775/48318601-2ff04080-e5d1-11e8-8ad1-1646b8b5052b.png)

**Comment by bh314** [comment]
![rain](https://user-images.githubusercontent.com/44651754/48319525-b9554200-e5d4-11e8-9a80-156bc4f7caa4.png)
These two rain records are the ones that I know are wrong.

**Comment by poblabs** [comment]
I just made commit https://github.com/poblabs/weewx-belchertown/commit/b8704980121db85924de01b7cd1045d8e9984e4c can you check it out? Re-download the `belchertown.py` file, place it into your `user/bin` folder, restart weewx and see what happens?

I have a feeling it'll fix the "Month with Highest Total Rainfall" but not "Total Rainfall For" (because I didn't see your box screenshot until after I committed. 

https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py

**Comment by bh314** [comment]
Yes, your latest update does fix the "Month with Highest Total Rainfall".  However, as you suspected, the "Total Rainfall for" is not yet fixed.  Thanks for your work on this really great software!

**Comment by poblabs** [comment]
@bh314 Can you confirm if you are on MySQL or SQLite? I just realized I made that commit for MySQL (by mistake) but it fixed the your "Month with Highest Total Rainfall" issue?

**Comment by bh314** [comment]
I am using MySQL.  I just updated again with your most recent commit but the "Total Rainfall For" is not fixed yet.

**Comment by poblabs** [comment]
I just pushed commit https://github.com/poblabs/weewx-belchertown/commit/2588c9ec6b9907b878141fe77e2463055d67d765 which should fix it. I'm using a [weewx-provided function to get most of the all time stats](http://www.weewx.com/docs/customizing.htm#defining_new_tags). It seems the "rainiest year" is broken. I'll have to raise this to the weewx folks, but in the meantime I "patched it" by just querying for the data myself. 

In my 2 lab systems the data matches the NOAA reports now. 

To fix:

1. Download this file to `bin/user` replacing the other: https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py
2. Download this file to `skins/belchertown/records` replacing the other: https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/records/index.html.tmpl

Let me know if it works for you

![image](https://user-images.githubusercontent.com/3484775/48323725-8ecaaf80-e5fb-11e8-8c2b-e818fc84de9a.png)

**Comment by poblabs** [comment]
Actually, hang on. I forgot I need to handle conversions. Let me update that quickly.

**Comment by poblabs** [comment]
Ok, https://github.com/poblabs/weewx-belchertown/commit/e9fd41661ff6f91f8d8965ccc4ca9e70f0d1e69b fixes that. Same instructions as https://github.com/poblabs/weewx-belchertown/issues/21#issuecomment-437735769 just with the updated files.

**Comment by bh314** [comment]
Yes, that does seem to have fixed both rain All Time records now.  Thanks again.

**Comment by poblabs** [comment]
Great news, thanks for testing it out. You can keep your files in place, I'm planning on releasing 0.8 soon which will include these fixes if you choose to upgrade. The Releases page will have the upgrade package when it's ready. https://github.com/poblabs/weewx-belchertown/releases
