### ISSUE TITLE
either my Weatherstation or maxSolarRad delivers wrong Value

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#211]
Hi,

I activated maxSolarRad yesterday. Today I noticed that somehow the actual solar radiation doesnt fit to the maxSolarRad.

Any ideas what could be wrong?

Br,
Johannes

**Comment by poblabs** [comment]
This is a weewx question. You're better to ask on the user forums. I would
verify you have the pyephem software installed. Instructions are on the
weewx.com user guide.
