### ISSUE TITLE
GRAPHS --> ALL is showing "Today" twice

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#212]
Hi, 

I was adopting today the graphs.conf.
I have there the sections "homepage", "today", "yesterday",...

Homepage and Today are looking the same, but I think I need both of them because if I remove "homepage" then I am getting an error. If I remove "today" then I am missing "Today" in Graphs.

But If I keep both and click on "ALL" Graphs, I see the graphs for today twice.

Br,
Johannes

**Comment by poblabs** [comment]
Check that your graphs.conf doesn't have a `[today]` and `[homepage]` section with the same information. 

If you want to remove one or the other, adjust your skin.conf setting for `highcharts_homepage_graphgroup`. Check [General Options](https://github.com/poblabs/weewx-belchertown#general-options) for details on this setting.
