### ISSUE TITLE
Realtime MQTT updates not connecting from web page

### ISSUE THREAD

**Issue by taylormia** [poblabs/weewx-belchertown#214]
I've been running weewx for more than a year but new to your skin - and love it. You can check out my page here: https://weather.sathy.us which uses an nginx reverse proxy.

Everything works on the skin except for the realtime MQTT update. I get a "Socket error on client weewx_xxxxxx, disconnecting" error in the Mosquitto log

I have connected with a local websockets client to the local broker and can see the published topic. See the detail here:
[https://imgur.com/a/5kM94Ve](url)
There are no firewalls on the broker or weewx severs.

Here are the conf and log files:
https://pastebin.com/TRmfnaNT

I hope you can help. Thanks

**Comment by poblabs** [comment]
Hi, glad you like the skin. Your website is using https, your websockets broker also has to be secure. Once you have that sorted with your hostname, or your reverse proxy or however you're managing that, then you'll need to enable the [`mqtt_websockets_ssl`](https://github.com/poblabs/weewx-belchertown#mqtt-websockets-for-real-time-streaming-options) option.

```
mqttws31.min.js:36 Mixed Content: The page at 'https://weather.sathy.us/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://10.10.10.25:9001/mqtt'. This request has been blocked; this endpoint must be available over WSS.
```

**Comment by poblabs** [comment]
I'm also assuming `10.10.10.25:9001` is an internal IP of yours? If so, you'll want to change that so it's accessible outside of your home. You could [use a public broker](https://github.com/poblabs/weewx-belchertown#use-a-public-broker) (which would solve for the secure websockets error you have), or [setup dynamic dns](https://www.duckdns.org/) and port forward 9001 to your internal machine.

**Comment by taylormia** [comment]
Thanks. I will work on this. Do you believe that the socket errors on the broker are due to the websockets not using ssl?

**Comment by poblabs** [comment]
Right now I 100% believe that yes. The error I pasted above is the debug output from Chrome where Chrome says it is blocking the connection

**Comment by taylormia** [comment]
Do both the MQTT port 1883 and websockets port 9001 have to use SSL or only the websockets?

**Comment by poblabs** [comment]
Only websockets 9001

**Comment by taylormia** [comment]
ty. will report back

**Comment by taylormia** [comment]
Just wanted to let you know that I got the issue fixed. I set up a Mosquitto broker that uses websockets in my internal home lab and made the port available via SSL through an nginx reverse proxy. Here's a link that helped me with the nginx.conf section to get the websockets port proxied with SSL: https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-configure-nginx-for-websockets/

Also since the proxy is  SSL i.e. port 443, this is the port used in the websockets section of the weewx.conf Belchertown section:

           mqtt_websockets_enabled = 1
           mqtt_websockets_host = proxied.host.name
           mqtt_websockets_port = 443
           mqtt_websockets_ssl = 1
           mqtt_websockets_topic = "weewx/loop"

Btw, the socket errors have considerably reduced but I still get a few of them now and then. 
Thanks again for a great skin!

**Comment by poblabs** [comment]
Great news! I can confirm your site is working for me as well!

**Comment by taylormia** [comment]
Thanks. Now on to customizing the About This Weatherstation page. 
Quick question - is there any way to dynamically be able to display on demand the units on the web pages in Metric or US. Some of my website visitors reside in countries where the metric system is used and others where the US units are required. I know I can configure the pages to show either Metric or US.

**Comment by poblabs** [comment]
Not at this time. It's on my list of things to implement, but given the current way the skin works, I haven't found a smooth way to do it yet.
