### ISSUE TITLE
Footer Disclaimer text not centered/justified on page

### ISSUE THREAD

**Issue by taylormia** [poblabs/weewx-belchertown#215]
When viewing the main page in Chrome, my footer disclaimer text is shown on the right of the page next to the the theme credit text instead of being centered or justified. Here's a screenshot. How can I change this?
https://imgur.com/9VJU1sZ

**Comment by poblabs** [comment]
I'm version 1.0.1 it is not centered. In version 1.1 coming out soon it is
centered.

**Comment by taylormia** [comment]
ok. thanks. looking forward to 1.0.1

**Comment by poblabs** [comment]
If you'd like to beta test, you can. It's in the [development branch](https://github.com/poblabs/weewx-belchertown/tree/development). Download the zip and copy the files to their proper homes, overwriting everything. Restart weewx when done and of course always have a backup. 

1.1 beta is what's running [on my website](https://belchertownweather.com/) now.

**Comment by taylormia** [comment]
I will try that.  I like your About this Weatherstation page but have no HTML skills to do my own version. Can you share your about.inc file, so I can customize it with my own info. Thanks

**Comment by poblabs** [comment]
Here you go. I made it generic so your site didn't get indexed on Google as mine. 

[about.zip](https://github.com/poblabs/weewx-belchertown/files/3732139/about.zip)


If you don't want to chart the rx stats, just remove these 3 lines:

```
<script type='text/javascript'>showChart("about");</script>

            <div id="rxchart" style="margin-top:30px;"></div>
            <div id="rxchartyear" style="margin-top:30px;"></div>
```

**Comment by taylormia** [comment]
Thanks !!

**Comment by taylormia** [comment]
In the development version zip file there is an "assets" folder. Where does this directory go? I have a "bin" folder in the root directory. Is this whee the "bin" folder in the zip file goes?
Another question: Which skin are you using for your default skin at https://belchertownweather.com/weewx. My default skin looks different.

**Comment by poblabs** [comment]
you can delete assets, thats for github. the other files go according to how you installed the theme. 

in fact what you should do is download the development zip file, then run `wee_extension --install development.zip` like you did for the first time you installed it. 

I'm using the Seasons skin from 3.9.2
