### ISSUE TITLE
WeeWx / Belchertown stopped working after archive_interval change

### ISSUE THREAD

**Issue by oliveres** [poblabs/weewx-belchertown#216]
Hi, I have similar issue as "belchertown.py error on wee_reports #206". Everything works fine, but today, I was modified archive interval in Vantage Pro 2 via wee_device --set-interval=5 and in weewx.conf chandged archive_interval from 1800 to 300. After Raspberry reboot, there was some errors in report generation. I made some debugging, clearing Davis memory, deleting database, but nothing help. I put archive_interval back to 1800 but error remains.

_wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 976, in run
    minstamp, maxstamp = archiveDaySpan( self.timespan.stop )
TypeError: 'NoneType' object is not iterable
root@raspberrypi:/etc/weewx#_ 

**If I disable your skin, I get error "cannot find start time" in syslog:**

_Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template NOAA/NOAA-YYYY.txt.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template NOAA/NOAA-YYYY-MM.txt.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template simple.txt.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template index.html.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template celestial.html.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template telemetry.html.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template tabular.html.tmpl: cannot find start time
Oct 15 23:31:35 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template statistics.html.tmpl: cannot find start time
Oct 15 23:31:36 raspberrypi wee_reports[555]: cheetahgenerator: Skipping template rss.xml.tmpl: cannot find start time_

**Comment by poblabs** [comment]
1. Take a backup of your weewx installation. 
2. Then run `wee_extension --uninstall Belchertown`
3. Then restart weewx

When it comes back up, is it still broken after an archive interval? 

There may be something else going on that you should report to the user forums. 

For example, `rss.xml.tmpl` and `statistics.html.tmpl` are not Belchertown files - so I am not sure what is happening.

**Comment by oliveres** [comment]
Belchertown uninstalled, WeeWx uninstalled, then reinstalled, It works now with basic skin again.

**Comment by poblabs** [comment]
Ok that is strange but good it is working. Can you reinstall Belchertown
and see if that works?
