### ISSUE TITLE
Minor bugs on v-1.1b7

### ISSUE THREAD

**Issue by ZXant** [poblabs/weewx-belchertown#217]
Pat

Minor bugs noted in v-1.1b7

1) Mobile shortcut
"Saving shortcut to Home screen on Mobile" it's not working

2) Highcharts
Y axis labels not showing in Graphs (as it can be noticed even at official Belchertown weather website).

Both issues works fine on released version 1.01, but not in Development branch.

Best, Xant

**Comment by poblabs** [comment]
Can you provide more of an example on item two? not all y-axis labels will
show because then they will overlap. Only the last observation in a chart
group will show the y-axis label.

**Comment by ZXant** [comment]
Think Graph labels was showing even at Belchertown weather website before (https://belchertownweather.com/), but not anymore. Please, verify.

Same thing in my case. Y labels were showing prior to update, but no longer.

**Comment by poblabs** [comment]
I will look. Can you add my website to your mobile phone? I was able to do it. What isn't working for you?

**Comment by ZXant** [comment]
Mobile save Belchertown Weather to mobile home screen works! Please, disregard #1, as Im going back to drawing board to figure-out what's going on my side... or site!.

#2 still persist.

Best, Xant

**Comment by taylormia** [comment]
I just installed 1.1b7 and also noticed that the Y-axis labels are not showing in any of the graphs. See screenshots here: https://imgur.com/MiPueRp and here: https://imgur.com/4RZLr5n

**Comment by poblabs** [comment]
Interesting. I'll take a look at this as soon as I can

Thanks for testing

**Comment by ZXant** [comment]
Issue #2/Highcharts Y-axis labels seems to be a common occurrence, and to be verified.

Issue #1/Mobile shortcut seems an unusual (and maybe local) occurrence. Not just that, but also browser vs OS related. Notes on this issue:

 - Yes, I changed "station#.png" images to reflect my website logo (all sizes), but reversed back and still difficulties.
 - Saving Belchertown website to Mobile Home works at all browser/OS combination (which may indicate a local occurrence, not a generic Skin problem).
 - Samsung A70 Pie9 and Chrome produce the following result for my weather website shortcut (image in attach, phone snapshot)
 - Same phone, but different browser (Firefox), produce correct shortcut
 - iPad with Safari browser produce correct shortcut

Please disregard issue #1 for now, as it can be a local issue (and not a common occurrence)

![image](https://user-images.githubusercontent.com/53246705/67015612-c58b2e80-f0c4-11e9-8959-5ea3d3c75104.png)

**Comment by poblabs** [comment]
@ZXant @taylormia thanks for reporting this. Its resolved now. You can download the development zip again and update to the latest version

**Comment by taylormia** [comment]
Just want to confirm that the Y-axis labels are back with the fixed version. Thanks!!

**Comment by ZXant** [comment]
Also to confirm that Y-axis labels are fixed. Thanks!

But update introduced a new "minor" (which was driving me nuts, till figured out):

**yAxis_min** and **yAxis_max** now case sensitive (no longer yaxis_min or yaxis_max)

Please, update Chart Wiki accordingly.

**Comment by poblabs** [comment]
This is covered already. You can see that here: https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#yaxis_min-and-yaxis_max

Also, it's noted as a breaking change here: https://github.com/poblabs/weewx-belchertown/blob/development/changelog

**Comment by ZXant** [comment]
Acknowledged already fixed in Charts Wiki notes, but Wiki still a mix (specially in Chart Examples). As the following:

    [[windplt]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 2
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0

**Comment by poblabs** [comment]
It's now updated

**Comment by ZXant** [comment]
Verified!

That was fast....

**Comment by ZXant** [comment]
Not sure if a HighCharts issue, but by placing Y-Label to the Right side (yAxis = 1), the word "Values" shows on the Left side.

![image](https://user-images.githubusercontent.com/53246705/67125156-28aebb00-f1c2-11e9-858c-c1b636c212fb.png)

**Comment by poblabs** [comment]
Paste your graphs.conf config

Can you set something else to y-axis 0?

**Comment by ZXant** [comment]
It seems consistent. If you place label as yAxis = 1 'Left side' and nothing on the 'Right side', the word "Values" shows up.

Also to note, Charts Wiki still mixed for "y_label" vs "yAxis_label".
