### ISSUE TITLE
Allow an indicator when station has been offline and data are stale

### ISSUE THREAD

**Issue by tomdotorg** [poblabs/weewx-belchertown#218]
Having just had a few issues recently with network and power, each of which knocking my station offline, I noticed that my Belchertown skin does not provide any kind of visual indicator to let a user know that the conditions they are looking at are 12+ hours old.

I think it would be good to be able to set a threshold of time after which we tell users that the data are old.

**Comment by poblabs** [comment]
I recently experienced this as well so it's on my list. What I struggle with is a nice way to show that. When you use the MQTT Websockets the status bar is taken over by the MQTT server providing the `dateTime` field. I suppose I could prepend that line with "Last Updated: MM/DD/YYYY HH:SS" then clear that once MQTT provides the `dateTime`? Too many characters in that line also affect mobile visitors too. Thoughts?

**Comment by tomdotorg** [comment]
I love the idea of letting users know when the info on the page was last updated when the MQTT connection is inactive or when there has been an amount of time since we last had an archive record come in.

Thanks for looking at this!

**Comment by tomdotorg** [comment]
Come to think of it, maybe the text always shows 'as of: ' and we give them the MQTT or most recent raw or archive?

**Comment by poblabs** [comment]
Not a bad idea. Will be a breaking change to those who have translated the skin, but I can put that in the changelog. Need to think of a good presentation for it.

**Comment by poblabs** [comment]
This is committed now to development and will be in the release for 1.1
