### ISSUE TITLE
mistake for time_length = day_ago in chart's wiki

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#219]
Hi Pat,
Today I wanted to add charts for yesterday period and I followed the [wiki](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#time_length) 
 time_length = day_ago
but getting an error on charts generation, so I searched with keyword yesterday in the documentation and found [time scales](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#to-graph-days-ago) that have time_length = day**s**_ago value and charts are generated correctly.
That maybe confusing.

**Comment by poblabs** [comment]
I've fixed this now, thanks! I also saw weeks, months and years_ago were wrong so I fixed them too.
