### ISSUE TITLE
Feature request: wind gust dots

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#22]
Not sure if you are still actively working on this Pat (sure hope so). Is it possible to change the current 'wind gust' graph to dots rather than lines? The lines tend to clutter the look a bit I think, probably an easy fix if you know where to look. Wind speed as a line is fine

**Comment by poblabs** [comment]
Yep, still planning on working on it. I've had a few changes lately which caused me to take a step back from my hobbies. Hoping to get back on it soon and will take a look at this!

**Comment by poblabs** [comment]
I took a 5 minute stab at this.... If this is what you're looking for, it's an easy manual change - but notice the hover text shows a grid coordinate and not the speed. Might take more time to figure out how to override that text. 🤔 

To play around with it, in `user/skins/belchertown/js` edit the `highcharts-dayplots.js.tmpl` and the `week`, `month`, `year` files too. At the bottom you'll see:

`optionsWind.series[1] = seriesData[0].windplot.series.windGust;`

Right below that line add:

`optionsWind.series[1].type = 'scatter';`

Then restart weewx and you should get dots on the next archive interval. 

![image](https://user-images.githubusercontent.com/3484775/48141722-73694880-e279-11e8-8cac-225869ba9c04.png)

**Comment by poblabs** [comment]
If you want to change the thickness of the dots, find the big block that begins with `var optionsWind= {`, then inside that block you'll see `plotOptions`.... replace that whole thing with this:

```
        plotOptions: {
            line: {
                lineWidth: 2,
                marker: {
                    enabled: false
                }
            },
            series: {
                marker: { radius: 2 },
            }
        },
```

Then update the `radius` to something you'd like. The radius of 2 matches the wind direction plot. 

All of this would have to be in a weewx options format for public consumption but if you wanted to tinker on it now, give it a try. 

Still unsure how to change the hover text with a shared plot. Initial tests didn't work.

**Comment by 41south** [comment]
Nice, thanks again for the help.

**Comment by 41south** [comment]
This works great, I think it cleans up the graph a lot. As you say just the hover txt to sort.

**Comment by 41south** [comment]
Happy to close this, no longer required on my part 👍  The clutter I had was actually caused by the data - which is now sorted

**Comment by poblabs** [comment]
Just an update that in skin 1.0 I've re-written the entire charting system, and today I was able to get the 2 observations types to co-exist on a chart. 

The popup information "tooltip" doesn't show the wind direction until you explicitly hover over it, but I think it looks great! There's even 2 yAxis for the different observation units. 

![image](https://user-images.githubusercontent.com/3484775/54495485-9ad0c180-48ba-11e9-9b1c-b3882391954b.png)

**Comment by 41south** [comment]
Excellent, thanks very much for your work on this

**Comment by poblabs** [comment]
I think I mixed your request with another one. The screenshot above shows wind speed and wind gust as line charts and the dots show wind direction. So 3 observations one 1 chart.

Your specific request - as I understand it - is to have wind speed as line, and wind gust as dots. You can achieve that as well with the below config when skin version 1.0 is released.

```
        [[[windchart]]]
            title = Wind Speed / Gust
            [[[[windGust]]]]
                type = scatter
            [[[[windSpeed]]]]
                zIndex = 1
```

![image](https://user-images.githubusercontent.com/3484775/54499434-17c66000-48e8-11e9-83ee-dfde3a4f29d9.png)

**Comment by poblabs** [comment]
And here's what it would look like if you chose "area" as the type of chart for windSpeed. 

```
        [[[windchart]]]
            title = Wind Speed / Gust
            [[[[windGust]]]]
                type = scatter
            [[[[windSpeed]]]]
                type = area
                zIndex = 1

```

![image](https://user-images.githubusercontent.com/3484775/54499526-527cc800-48e9-11e9-85df-abb41f4ec167.png)
