### ISSUE TITLE
Skin set to Metric, but forecast shows inch

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#221]
Hi,

I have set the skin to Metric, but the forecast shows inch for the expected rain.

Br,
Johannes

**Comment by poblabs** [comment]
Have you set the units correctly under dark sky settings for skin.conf?

Instructions are in the readme

**Comment by ebnerjoh** [comment]
It was set to "auto", I have set now "de". I need to wait for the next rain forecast to check.

Br,
Johannes

**Comment by poblabs** [comment]
de may be the language. Check the readme for units. I think you may want si
or ca.

**Comment by ebnerjoh** [comment]
Of course.
I will test with ca, as I want to have km/h for windspeet.

Br,
Johannes

**Comment by poblabs** [comment]
Is this still an issue or have settings the units worked for you?

**Comment by ebnerjoh** [comment]
Hi,

Yes, I still have this issue. 

I can see Darksky-Settings in "skin.conf" and "weewx.conf". Am I right, that "weewx.conf" has priority over "skin.conf"?

In "weewx.conf" I have this settings:

> forecast_enabled = 1
> darksky_secret_key = 459769240c57b952f4c080b82f40dac7
> darksky_units = "si"
> darksky_lang = "de"
> forecast_alert_enabled = 0

I tried units with si and ca, but the forecast for snow is always in inch.

Br,
Johannes

**Comment by poblabs** [comment]
It's been a while, and weewx and the skin have gone through a few updates. If you update to the latest version do you still have this problem?

**Comment by ebnerjoh** [comment]
Hi, yes, so far it looks good!
