### ISSUE TITLE
Mobile Shortcut not rendering on Android

### ISSUE THREAD

**Issue by taylormia** [poblabs/weewx-belchertown#222]
On my Galaxy S10e phone running Android 9 - when I use the Add to Home Page shortcut for my weather page, I get these images when selecting the shortcut on both Chrome and the built in Samsung browser. I get the same results on an older Galaxy Note 4 running Android 6. I don't have the problem using the  Add to Home Page shortcut on my iPad. Also, when browsing the weather page on the S10e and Note 4, the page shows up properly. I'm using version 1.1b7 of the skin.

https://imgur.com/V4EGHmA
https://imgur.com/7YHZTlu

Any ideas?

**Comment by poblabs** [comment]
Are you still having this issue? Can you send me your website so I can try to add it to my homescreen? Any errors in the syslog?
