### ISSUE TITLE
Pi kiosk in dark mode?

### ISSUE THREAD

**Issue by c0r3dump3d** [poblabs/weewx-belchertown#223]
Hi, It is possible to put the kiosk pi in dark mode?

Thank you.

**Comment by poblabs** [comment]
Yes, in the 1.1 version there will be. Use skin option `pi_theme`. You can [upgrade to the beta now and test it out](https://github.com/poblabs/weewx-belchertown/tree/development). Download the [development tar file](https://github.com/poblabs/weewx-belchertown/archive/development.tar.gz) and install it exactly like how you'd install the regular release. Make sure you have a backup of everything before you upgrade! 

There's also [a lot of other changes that you can review here](https://github.com/poblabs/weewx-belchertown/blob/development/changelog). Most noteably would be the removal of the `belchertown_root_url `🎉

**Comment by c0r3dump3d** [comment]
Thank you, I will try!!!
