### ISSUE TITLE
8 Day forecast, wrong start date (Timezone issue?)

### ISSUE THREAD

**Issue by aganet** [poblabs/weewx-belchertown#225]
Hi, When I visit the template from a PC different timezone, the 8 Day forecast is correct but the days are wrong. The first Date is the past Date. 

User with PC with the same timezone with weewx is correct. 
User with PC in UK time see the proper forecast but the days are starting from the past day. 

Is something I can fix ? or is a code issue?

Regards

**Comment by poblabs** [comment]
Can you share an example? Send me a site to look at. Screenshots? In early versions of the skin there were timezone issues but all should be resolved if you're on 1.0.1 or the 1.1 beta.

**Comment by aganet** [comment]
Hi You can check it on my website  http://aganet.gr/weewx/weather/aganet/
I'm using the 1.0.1 version.

**Comment by aganet** [comment]
<img width="1223" alt="Screenshot 2019-11-13 at 06 34 12" src="https://user-images.githubusercontent.com/11410743/68739008-ac03d680-05df-11ea-8757-90febee9f9d3.png">
In this Screenshot check the current date and the start date. Is from a PC having UTC time.

**Comment by poblabs** [comment]
Can you upgrade your skin to the [development version](https://github.com/poblabs/weewx-belchertown/tree/development)and see if this problem still exists?
