### ISSUE TITLE
Average climatological issues

### ISSUE THREAD

**Issue by bdwilson** [poblabs/weewx-belchertown#226]
First off, thank you for this skin and the work you've put into it. I love the new graphing pieces in 1.x and have tried to copy the ones in your examples - I've also seen in your docs that some new things are coming in 1.1 that will be great! 

Here's my issue. I have the following configured, however we're into November and I don't see any data. Is this by design (i.e. data is only computed after the month ends), or is something off in my setup? Thanks!

<pre>
[[avgclimatethisyear]]
        title = "Average Climatological Values for This Year"
        type = spline
        time_length = year
        aggregate_type = max
        aggregate_interval = 86400 # 1 day
        gapsize = 86400000
        xaxis_groupby = month
        xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        [[[outTemp]]]
            zIndex = 2
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            zIndex = 2
        [[[rainTotal]]]
            name = Rain Total
            type = column
            yAxis = 1
            zIndex = 0
            color = "#268bd2"
</pre>
![image](https://user-images.githubusercontent.com/317946/68708801-753bab00-0562-11ea-9dea-248089e1cac2.png)

**Comment by poblabs** [comment]
It should calculate every time the skin is generated on the archive intervals. Below you can see mine is showing November. 

Likely something is hung up somewhere and your graphs haven't been generating. What does your syslog show for errors?

![image](https://user-images.githubusercontent.com/3484775/68709132-10cd1b80-0563-11ea-9a09-062b0aee567e.png)

**Comment by bdwilson** [comment]
No errors. 

<pre>
Nov 12 19:03:23 weewx weewx[4254]: imagegenerator: Generated 14 images for SeasonsReport in 1.64 seconds
Nov 12 19:03:23 weewx weewx[4254]: copygenerator: copied 0 files to /var/www/html/weewx
Nov 12 19:03:23 weewx weewx[4254]: cheetahgenerator: Generated 1 files for report Hubitat in 0.08 seconds
Nov 12 19:03:26 weewx weewx[4254]: cheetahgenerator: Generated 11 files for report Belchertown in 2.78 seconds
Nov 12 19:03:26 weewx weewx[4254]: copygenerator: copied 2 files to /var/www/html
</pre>

Other graphs appear fine (minus the pool where that sensor is offline)

![image](https://user-images.githubusercontent.com/317946/68721236-bdb59180-057f-11ea-8152-da65848d88d0.png)

**Comment by poblabs** [comment]
What's the link to your site?

**Comment by bdwilson** [comment]
https://weather.bubba.org

**Comment by poblabs** [comment]
Not sure honestly at this distance. Everything seems fine in your debugs. You're set to 1 minute archive intervals, I don't know if that has something to do with it. You're sure no other errors exist pre and post the snippet you pasted from syslog? I'm a bit lost.

**Comment by bdwilson** [comment]
Nope, I stopped it and started and here's full syslog:

<pre>
Nov 12 19:44:27 weewx systemd[1]: Stopped LSB: weewx weather system.
Nov 12 19:44:34 weewx systemd[1]: Starting LSB: weewx weather system...
Nov 12 19:44:34 weewx weewx[15495]: engine: Initializing weewx version 3.9.2
Nov 12 19:44:34 weewx weewx[15495]: engine: Using Python 2.7.16 (default, Apr  6 2019, 01:42:57) #012[GCC 8.2.0]
Nov 12 19:44:34 weewx weewx[15495]: engine: Platform Linux-4.19.66-v7+-armv7l-with-debian-10.1
Nov 12 19:44:34 weewx weewx[15495]: engine: Locale is 'en_GB.UTF-8'
Nov 12 19:44:34 weewx weewx[15495]: engine: pid file is /var/run/weewx.pid
Nov 12 19:44:34 weewx weewx[15484]: Starting weewx weather system: weewx.
Nov 12 19:44:34 weewx systemd[1]: Started LSB: weewx weather system.
Nov 12 19:44:34 weewx weewx[15499]: engine: Using configuration file /etc/weewx/weewx.conf
Nov 12 19:44:34 weewx weewx[15499]: engine: Loading station type SDR (user.sdr)
Nov 12 19:44:34 weewx weewx[15499]: sdr: MainThread: driver version is 0.58
Nov 12 19:44:34 weewx weewx[15499]: sdr: MainThread: sensor map is {'windDir': 'wind_dir.0038.Acurite5n1Packet', 'windSpeed': 'wind_speed.0038.Acurite5n1Packet', 'outTemp': 'temperature.0038.Acurite5n1Packet', 'outHumidity': 'humidity.0038.Acurite5n1Packet', 'rain_total': 'rain_total.0038.Acurite5n1Packet', 'inTemp': 'temperature.3969.AcuriteTowerPacket', 'inHumidity': 'humidity.3969.AcuriteTowerPacket', 'extraTemp1': 'temperature_probe.0BF1.Acurite00275MPacket', 'extraTemp2': 'temperature.0BF1.Acurite00275MPacket', 'extraTemp3': 'temperature.021A.AcuriteTowerPacket', 'extraHumid1': 'humidity.021A.AcuriteTowerPacket'}
Nov 12 19:44:34 weewx weewx[15499]: sdr: MainThread: deltas is {'rain': 'rain_total'}
Nov 12 19:44:34 weewx weewx[15499]: sdr: MainThread: startup process 'rtl_433 -M utc -F json -G'
Nov 12 19:44:34 weewx weewx[15499]: engine: StdConvert target unit is 0x1
Nov 12 19:44:34 weewx weewx[15499]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=software, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Nov 12 19:44:34 weewx weewx[15499]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Nov 12 19:44:34 weewx weewx[15499]: engine: Archive will use data binding wx_binding
Nov 12 19:44:34 weewx weewx[15499]: engine: Record generation will be attempted in 'hardware'
Nov 12 19:44:34 weewx weewx[15499]: engine: Using archive interval of 60 seconds (specified in weewx configuration)
Nov 12 19:44:34 weewx weewx[15499]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Nov 12 19:44:34 weewx weewx[15499]: manager: Starting backfill of daily summaries
Nov 12 19:44:34 weewx weewx[15499]: restx: StationRegistry: Registration not requested.
Nov 12 19:44:34 weewx weewx[15499]: restx: Wunderground: Posting not enabled.
Nov 12 19:44:34 weewx weewx[15499]: restx: PWSweather: Posting not enabled.
Nov 12 19:44:34 weewx weewx[15499]: restx: CWOP: Posting not enabled.
Nov 12 19:44:34 weewx weewx[15499]: restx: WOW: Posting not enabled.
Nov 12 19:44:34 weewx weewx[15499]: restx: AWEKAS: Posting not enabled.
Nov 12 19:44:34 weewx weewx[15499]: restx: ThingSpeak: service version is 0.6
Nov 12 19:44:34 weewx weewx[15499]: restx: ThingSpeak: desired unit system is US
Nov 12 19:44:34 weewx weewx[15499]: restx: ThingSpeak: Data will be uploaded using api_key XXXXXXXXXXXXH7OB
Nov 12 19:44:34 weewx weewx[15499]: engine: Starting up weewx version 3.9.2
Nov 12 19:44:34 weewx weewx[15499]: engine: Starting main packet loop.
Nov 12 19:45:23 weewx weewx[15499]: bmp280a: found pressure value of 29.9764583893 mbar
Nov 12 19:45:23 weewx weewx[15499]: manager: Added record 2019-11-12 19:45:00 EST (1573605900) to database 'weewx.sdb'
Nov 12 19:45:23 weewx weewx[15499]: manager: Added record 2019-11-12 19:45:00 EST (1573605900) to daily summary in 'weewx.sdb'
Nov 12 19:45:24 weewx weewx[15499]: restx: ThingSpeak: Published record 2019-11-12 19:45:00 EST (1573605900)
Nov 12 19:45:28 weewx weewx[15499]: cheetahgenerator: Generated 8 files for report SeasonsReport in 4.45 seconds
Nov 12 19:45:30 weewx weewx[15499]: imagegenerator: Generated 14 images for SeasonsReport in 1.71 seconds
Nov 12 19:45:30 weewx weewx[15499]: copygenerator: copied 5 files to /var/www/html/weewx
Nov 12 19:45:30 weewx weewx[15499]: cheetahgenerator: Generated 1 files for report Hubitat in 0.20 seconds
Nov 12 19:45:30 weewx weewx[15499]: Belchertown Extension: version 1.0.1
Nov 12 19:45:39 weewx weewx[15499]: cheetahgenerator: Generated 11 files for report Belchertown in 8.17 seconds
Nov 12 19:45:39 weewx weewx[15499]: copygenerator: copied 31 files to /var/www/html
</pre>

**Comment by poblabs** [comment]
Hmm yeah I'm a bit lost on this one. Remove this line from your avg climate details, and restart weewx. The labels will be gone, but does the data show up?

`xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'`

**Comment by bdwilson** [comment]
Ahhh

![9DA59E6B-6DD4-4B80-92FC-41E40EEE686E](https://user-images.githubusercontent.com/317946/68726190-b649b480-058e-11ea-9efa-87bf82536799.jpeg)

**Comment by poblabs** [comment]
There it is. Your database starts in February. So remove the Jan from the
labels and it'll match up.

This type of graph isn't smart enough to know when the database starts. It
relies on you giving it that info.

Next year you can begin the graph with Jan.

**Comment by bdwilson** [comment]
Thank you!
