### ISSUE TITLE
Some erros in dev version

### ISSUE THREAD

**Issue by c0r3dump3d** [poblabs/weewx-belchertown#227]
Hi, I'm trying to use the dev version of weewx-belchertown but after install in weewx 3.9.2 I have theses errors:

`****  Traceback (most recent call last):
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Nov 16 13:38:17 meteoot weewx[7826]: ****      fd.write(str(compiled_template))
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
Nov 16 13:38:17 meteoot weewx[7826]: ****      rc = getattr(self, mainMethName)()
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "cheetah__etc_weewx_skins_Belchertown_json_weewx_data_json_tmpl_1573907597_31_72969.py", line 132, in respond
Nov 16 13:38:17 meteoot weewx[7826]: ****  NotFound: cannot find 'github_version'
Nov 16 13:38:17 meteoot weewx[7826]: restx: MQTT: Published record 2019-11-16 13:38:18 CET (1573907898)
Nov 16 13:38:17 meteoot weewx[7826]: ****  Traceback (most recent call last):
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Nov 16 13:38:17 meteoot weewx[7826]: ****      fd.write(str(compiled_template))
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
Nov 16 13:38:17 meteoot weewx[7826]: ****      rc = getattr(self, mainMethName)()
Nov 16 13:38:17 meteoot weewx[7826]: ****    File "cheetah__etc_weewx_skins_Belchertown_js_belchertown_js_tmpl_1573907598_93_26967.py", line 132, in respond
Nov 16 13:38:17 meteoot weewx[7826]: ****  NotFound: cannot find 'graphpage_titles'
`

**Comment by poblabs** [comment]
You have some old files that didn't get upgraded. Looks like maybe the
belchertown.py file.

Probably best to uninstall Belchertown using the wee_extension command.
Then reinstall the development version using wee_extension. Restart weewx
when done.

Have a backup of everything just in case.

I say again; backup everything just in case

**Comment by c0r3dump3d** [comment]
Hi, thank you for quick answer, I've used these command in order to update:

`wee_extension --uninstall Belchertown`

`wee_extension --install development.tar.gz `

**Comment by poblabs** [comment]
did you make sure the configurations stayed in weewx.conf then Restarted
weewx ?

**Comment by c0r3dump3d** [comment]
Sorry I didn't restarted weewx, but now  have other error:

` ****  Traceback (most recent call last):
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Nov 16 13:54:17 meteoot weewx[24555]: ****      fd.write(str(compiled_template))
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
Nov 16 13:54:17 meteoot weewx[24555]: ****      rc = getattr(self, mainMethName)()
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 104, in respond
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1685, in _handleCheetahInclude
Nov 16 13:54:17 meteoot weewx[24555]: ****      file=file)
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 772, in compile
Nov 16 13:54:17 meteoot weewx[24555]: ****      settings=(compilerSettings or {}))
Nov 16 13:54:17 meteoot weewx[24555]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1708, in __init__
Nov 16 13:54:17 meteoot weewx[24555]: ****      source = unicode(source)
Nov 16 13:54:17 meteoot weewx[24555]: ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 625: ordinal not in range(1`

**Comment by poblabs** [comment]
Your about.inc or records.inc files need to be updated. take a look at the
example files at the first line has a word that says "encoding" copy and
paste that to your existing files and try again.

**Comment by c0r3dump3d** [comment]
Ok, that's right!! A last error, I don't see the image with the weather conditions

![Captura de pantalla_2019-11-16_14-08-05](https://user-images.githubusercontent.com/5602401/68993632-7fb7b680-087a-11ea-9c6f-3cb7ab7ddcf2.png)

**Comment by poblabs** [comment]
Do you have dark sky forecast enabled?

**Comment by c0r3dump3d** [comment]
Nice!!!, thank you very much for your help
