### ISSUE TITLE
Date picker for custom graph ranges?

### ISSUE THREAD

**Issue by petercoxphoto** [poblabs/weewx-belchertown#228]
It would be very useful to be able to pick a specific date or range and generate graphs based on that from the web page. 

Is this something that's feasible?

**Comment by poblabs** [comment]
Hi, sorry not feasable with the way weewx works. Most users don't have direct access to their database from the internet, so I've created the skin with that in mind. On every archive run the date range is selected from the graphs.conf and a static JSON file is created which contains the chart data. 

If you know a specific time frame you want to chart, and don't mind it being a static timeframe, then you can use the beta version of the skin and the [`timespan_specific`](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#to-graph-a-specific-time-span) option. 

This does not provide a dynamic way to change the charts though - just a way to chart your favorite day or a [significant weather event like this one on my website](https://belchertownweather.com/graphs/?graph=2019bombcyclone).
