### ISSUE TITLE
Rain group by hour

### ISSUE THREAD

**Issue by c0r3dump3d** [poblabs/weewx-belchertown#229]
Hi, It's possible to group the rain data for graph rain by hour,  xAxis_groupby  = hour?

**Comment by poblabs** [comment]
Not currently, but it could be added to the 1.1 beta skin if you'd like to try it? It seems like it could be a lot of data unless you're only using it on a day graph group?

**Comment by poblabs** [comment]
I just added the ability to group the xAxis by hour. Feel free to try it out using the 1.1 development skin. 

```
    [[hourtest]]
        title = "Hourly Rain"
        xAxis_groupby = hour
        [[[rainTotal]]]
            name = Rain Total
            type = column
            color = "#268bd2"
```

![image](https://user-images.githubusercontent.com/3484775/69501296-a3f64180-0ed1-11ea-9b8c-1a24f181fbcc.png)

**Comment by c0r3dump3d** [comment]
Thank you very much, I will try!!
