### ISSUE TITLE
Metric rainfall

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#23]
This may have already been addressed in the issue #8 but I'm just sorting out the rain gauge side of my station and note that the reading are out by a factor of 10 - skin shows 0.28mm of rain instead of 2.8mm and the rain rate is similar for the rate 0.56 instead of 5.6

Possibly other down-stream issues with that too

If it's already in a fix then please just close :)

**Comment by 41south** [comment]
Good question, I did a new install from zip a couple of weeks back so possibly not. What's the best way to grab that?

**Comment by poblabs** [comment]
You can download the master zip file of this repository by clicking on the download link in the photo below. Then just copy/paste the files in skins and bin/user to their respective locations. Then restart weewx. 

Have a backup just in case!

![image](https://user-images.githubusercontent.com/3484775/48748879-6881c100-ec46-11e8-8bfe-d53e9bff8997.png)

**Comment by 41south** [comment]
Any changes in the conf files Pat or can I keep the existing ones?

**Comment by 41south** [comment]
Also no rain showing here and the max rain rate doesn't add up with the graph - but not worried too much about that yet - probably connected to the other issues?
![screen shot 2018-11-20 at 6 39 17 pm](https://user-images.githubusercontent.com/1725001/48753649-a4269480-ecf3-11e8-9d76-7b8b0e7c10fa.png)

**Comment by poblabs** [comment]
> Any changes in the conf files Pat or can I keep the existing ones?

I think the only change was the renaming of `disconnect_live_visitor` to `disconnect_live_website_visitor`

> Will it work to just do a wee_extension --install over the top of the existing files?

Yeah if you download the zip in full, you can do a wee_extension on top of the existing. Or you can manually place the files. Either method will work

> probably connected to the other issues?

That section of rain info comes from the built-in weewx `$day.rain.sum` which is updated every archive interval. If this isn't working, is it showing up on the defaut weewx skin? 

Once we iron out this issue I think I'll release 0.8.

**Comment by 41south** [comment]
The data isn't on the default skin either Pat so it's not a skin issue. I'll have to ask the Weewx folk how to fault find that one.

**Comment by 41south** [comment]
Correct. But MQTT data does show year rain etc, just not day rain again
![screen shot 2018-11-21 at 9 32 21 am](https://user-images.githubusercontent.com/1725001/48801134-729fde80-ed70-11e8-8d11-982a637c692e.png)
{"windSpeed10_kph": "1.60934800001", "monthET": "0.0", "leafWet1_count": "0.0", "cloudbase_meter": "885.524542612", "leafTemp1_C": "0.0", "extraTemp3_C": "0.0", "outHumidity": "63.0", "pressure_mbar": "1006.86157083", "rain_cm": "0.0", "extraTemp5_C": "0.0", "dayET": "0.0", "maxSolarRad": "628.683982598", "barometer_mbar": "1007.55206889", "yearRain_cm": "1.2200000003", "extraTemp2_C": "0.0", "soilTemp3_C": "0.0", "consBatteryVoltage_volt": "0.0", "dewpoint_C": "9.16689196608", "insideAlarm": "0.0", "extraTemp6_C": "0.0", "dateTime": "1542745812.0", "sunset": "1542711600.0", "sunrise": "1542711600.0", "extraAlarm5": "0.0", "leafTemp3_C": "0.0", "heatindex_C": "16.2222222222", "dayRain_cm": "0.140000000035", "stormRain_cm": "0.0", "forecastIcon": "0.0", "leafWet3": "0.0", "outsideAlarm2": "0.0", "windSpeed_kph": "0.0", "forecastRule": "0.0", "rainAlarm": "0.0", "stormStart": "943873200.0", "altimeter_mbar": "1007.25403243", "soilTemp4_C": "0.0", "windchill_C": "16.2222222222", "extraTemp4_C": "0.0", "appTemp_C": "16.0478831748", "outTemp_C": "16.2222222222", "extraAlarm1": "0.0", "extraAlarm2": "0.0", "extraAlarm3": "0.0", "extraAlarm4": "0.0", "soilMoist4_centibar": "0.0", "extraAlarm6": "0.0", "extraAlarm7": "0.0", "extraAlarm8": "0.0", "humidex_C": "17.1253519855", "soilTemp2_C": "0.0", "soilLeafAlarm2": "0.0", "rain24_cm": "0.0", "extraHumid7": "49.0", "soilTemp1_C": "0.0", "soilMoist2_centibar": "0.0", "hourRain_cm": "0.0", "inTemp_C": "20.5", "soilLeafAlarm4": "0.0", "trendIcon": "-1.0", "leafWet2_count": "0.0", "soilLeafAlarm3": "0.0", "usUnits": "16.0", "soilLeafAlarm1": "0.0", "leafWet4": "0.0", "leafTemp2_C": "0.0", "soilMoist1_centibar": "0.0", "yearET": "0.0", "txBatteryStatus": "1.0", "monthRain_cm": "0.0", "soilMoist3_centibar": "0.0", "UV": "4.2", "rainRate_cm_per_hour": "3.47999999732", "extraTemp1_C": "0.0", "outsideAlarm1": "0.0", "leafTemp4_C": "0.0", "inHumidity": "50.0", "inDewpoint_C": "9.71342800982", "radiation_Wpm2": "695.0", "extraTemp7_C": "20.0", "windGust_kph": "0.0"}

**Comment by poblabs** [comment]
Ok then yeah I think this might be something going on in weewx itself.

**Comment by 41south** [comment]
Agree, however this is still an issue unless you've already sorted it? Note the 0.14mm rainfall that should be 1.4mm

Barometer	1007.15 mbar 
Visibility	14.97 km
Dew Point	8.2 °C
Humidity	62.0%
Rainfall	0.14 mm 0.00 mm/hr
UV	1.10
Solar	119.00 W/m²

**Comment by poblabs** [comment]
Were you able to upgrade to 0.8rc2?

**Comment by 41south** [comment]
Yes did that last night, no change to this issue

**Comment by poblabs** [comment]
Ok, we can test a few things shortly. This is wrong in the live data or
right when the page loads or both?

**Comment by 41south** [comment]
Rainfall says 0 at page load then shows 0.14 when live data starts

**Comment by poblabs** [comment]
I think I got it now. Sorry have been moving from PC to mobile and back again. 

0 at page load would be weewx's problem.

0.14 when live data starts is my problem.

Let me look into it

**Comment by 41south** [comment]
Yeah I assume that the 0 at load is related to the whole 'no rainfall' issue. Looking at the raw data from my station I see there is "rain" and "dayRain". The "rain" is 0.00 and the "dayRain" is 0.140 (assume both are CM) so I guess the missing rain data is the issue and I think it's my WeatherDuino station not Weewx.

You are using dayRain for the live data?

**Comment by poblabs** [comment]
Yeah, using `dayRain` because `rain` is when there's a bucket tip, so it usually only comes up in MQTT when it needs to. `dayRain` would be what I'm after and I think it only gets updated on archive intervals. 

Specifically here's the section I'm using to update it, which is coming from weewx core as well. In that I'm not doing any math on it, I'm just displaying the value from MQTT.

https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L557-L568

Your MQTT is showing `"dayRain_cm": "0.140000000035"`, so it would default to the centimeter which I think it right - but your label shows mm which gives it the appearance of being wrong. 

I'm using `$unit.label.rain` to show the mm next to rain. Can you paste your skin options for the metric conversions?

**Comment by 41south** [comment]
You mean this?

group_degree_day   = degree_C_day         # Options are 'degree_F_day' $
        group_direction    = degree_compass
        group_moisture     = centibar
        group_percent      = percent
        group_pressure     = mbar                 # Options are 'inHg', 'mmHg',$
        group_radiation    = watt_per_meter_squared
        group_rain         = mm                 # Options are 'inch', 'cm', or $
        group_rainrate     = mm_per_hour        # Options are 'inch_per_hour', $
        group_speed        = km_per_hour        # Options are 'mile_per_hour', $
        group_speed2       = km_per_hour2       # Options are 'mile_per_hour2',$
        group_temperature  = degree_C             # Options are 'degree_F' or '$
        group_uv           = uv_index
        group_volt         = volt

**Comment by 41south** [comment]
Makes sense, how do I change that, just add it in the [[MQTT]] section I posted above?

**Comment by 41south** [comment]
I tried append_units_label = False, that results in no rain showing al all, but all other data looks ok at first glance

**Comment by poblabs** [comment]
I'm not 100% solid with metric. Sounds like you want metric everything but
the rain is considered metricwx?

**Comment by 41south** [comment]
Yeah, I use a bit of a combination, as I think is certainly popular down this way, where rain is in mm and wind is km/h
From the wiki;
The difference between METRICWX, and METRIC is that the former uses mm instead of cm for rain, and m/s instead of km/hr for wind speed.

**Comment by poblabs** [comment]
Makes sense. I just didn't have them memorized :) 

Might be another one for the user forums. mwall created weewx-mqtt so he may have a way to override certain observations with the unit you want. I didn't see anything in the wiki - and I haven't dug into the code yet.

**Comment by 41south** [comment]
So changing MQTT to METRICWX fixes the rain - but what will it break?

**Comment by poblabs** [comment]
Potentially your wind? Unless you update the group unit in the skin
settings to match km/hr

Which you may already have in place.

**Comment by 41south** [comment]
Yes, it is - but doesn't that just mean that I'm getting meters per second numbers with a k/ph label the same as rain was doing?

**Comment by 41south** [comment]
Is it possible to put a calculation in the web page to say something along the lines of- if MQTT units = METRIC and Group_rain = mm then rainDaily = rainDaily * 10?
Easy to write I know :)

**Comment by poblabs** [comment]
Sorry if I'm being a bit daft - for someone who uses imperial this can get confusing quick 😃 

|   | METRIC | METRICWX | 41south |
|---|---|---|---|
| RAIN | cm | mm | mm |
| WIND | km/hr | m/s | km/h |

So based on this table, you're looking for **METRICWX for RAIN** and **METRIC for WIND**?

I think we'll have a bad flip/flop here and we won't get a 100% match, because if you put `weewx-mqtt` into METRICWX that'll make your WIND m/s. 

My initial idea was to do that and then change your skin options to use `group_wind = km_per_hour`, but then it'll do the math very wrong because it won't convert correctly. 

I may be surprised though and I think it's worth a shot. Put MQTT into `METRICWX`, then in your skin options set `group_wind = km_per_hour`, restart weewx and see what happens. 

If that fails then I think it might make sense to see if there's a way in `weewx-mqtt` to override certain observations at the extension level, instead of the skin level (easier to code I think).

**Comment by 41south** [comment]
Ok, from the group emails, this sorted both the rainDay and rainRate

[[MQTT]]
        #This section is for the MQTT service setup
        server_url = mqtt://192.168.20.121:1883/
        topic = weather/41south
        unit_system = METRIC
        binding = loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        [[[inputs]]]
                [[[[dayRain]]]]
                        name = dayRain_mm
                        units = mm
                [[[[rainRate]]]]
                        name = rainRate_mm_per_hour
                        units = mm_per_hour

**Comment by 41south** [comment]
And ....... closed 🥇

**Comment by poblabs** [comment]
Great news! Glad this worked out - I had a suspicion it was what you needed.
