### ISSUE TITLE
Climate graph

### ISSUE THREAD

**Issue by Chema76** [poblabs/weewx-belchertown#232]
Hi
For some time now I want to make a climate graph that represents the temperatures on one axis and the precipitation on the opposite axis.
My intention is that the axis of precipitation increases twice as much as the axis of temperatures.
The graph I want should be similar to the one attached.
Any ideas?

thank you

![imagen](https://user-images.githubusercontent.com/45130728/70315735-8652a180-181a-11ea-8d05-8094c051dd86.png)
image credits: climatedata.org [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)]

**Comment by norecords** [comment]
@Chema76 
I think what you want is this : [Average Climate Values Chart](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#average-climate-values-chart)

**Comment by Chema76** [comment]
Thank you for your help but I already have that option in my template; what I am looking for is that the axes have the numbering according to my first post, as seen on the image attached.

**Comment by norecords** [comment]
in this case you can set yAxis_min and yAxis_max
```
[[[outTemp]]]
            yAxis_min = 0
            yAxis_max = 140
```
and you should have a graph similar of what you want.
