### ISSUE TITLE
Forecast on main page does not match Darksky daily details.

### ISSUE THREAD

**Issue by dgunnell** [poblabs/weewx-belchertown#233]
Daily Forecast display wind, rain % change does not match Darksky Daily forecast details.  Wind and rain % changes MUCH higher tan daily details which match when compared to other weather services for my area.

**Comment by dgunnell** [comment]
Did some research and the json data coming back from Darksky is providing incorrect forecast and current conditions for my area.  Suggestion would be to use another service as an option such as NOAA json weather forecast data which at least for my area is accurate.

**Comment by poblabs** [comment]
Noaa data isn't as easy to parse as dark sky. You could contact dark sky
with the problem and they can fix it (they use noaa data by the way).

Pull request are welcome if you have a solution.
