### ISSUE TITLE
Moon icon inverse

### ISSUE THREAD

**Issue by ZXant** [poblabs/weewx-belchertown#234]
Pat

I've been adopting "Dark Theme" for most applications, and even leaving Dark Theme "On" as standard for my WX page.

The underneath is a snapshot:

![image](https://user-images.githubusercontent.com/53246705/70728307-2a32c600-1ccf-11ea-9891-e748c51c4b9f.png)

Shouldn't Moon icon been in reverse color for Dark Theme?

Best, Xant

**Comment by norecords** [comment]
I think it can be solved by switching "alt" to "normal" icons.
`<div class="wi wi-moon-alt-first-quarter northern-hemisphere"></div>`
to 
`<div class="wi wi-moon-first-quarter northern-hemisphere"></div>`
when in dark mode...

**Comment by michaelundwd** [comment]
Just updated to v 1.1 and using the dark theme.  I was hoping this had been fixed, but my new moon (and yours!)  is still coming out as a full one (www.lordshipweather.uk.  Have I missed something?
BTW generate has cut the load from my venerable pi down to <10% from 60 - nice work.
Michael

**Comment by poblabs** [comment]
Those are actually the right icons. If you view source, you'll see that it's the icon name. 

Today the moon is showing as "new", and the icon it's using is `wi wi-moon-alt-new`. 

The font I'm using to show these can be [found here](https://erikflowers.github.io/weather-icons/).

**Comment by poblabs** [comment]
Well, I suppose it could be up for debate. I'm using `wi-moon-alt-new` and there also exists a `wi-moon-new`. Hmm

**Comment by michaelundwd** [comment]
Thanks for the info.  I tried using the moon icons without the alt by modifying index.html.tmpl and waiting for the next report loop.  In dark theme, it briefly flashed the dark new moon, but then reverts to the bright one.  Is there something else I should have modified?

**Comment by michaelundwd** [comment]
I've done some further investigation and modified the Belchertown.js.tmpl file to use wi-moon-new etc and it gave me the results I was looking for, but of course has ruined the light mode (that I never use).  Switching the theme just changes the dark to light pixels and vice versa.
This is the mod Xant suggested, but it is way beyond my coding skills to make the changes automatic.  I leave it to you and others to decide if that is what you want....
