### ISSUE TITLE
Wrong record value

### ISSUE THREAD

**Issue by Chema76** [poblabs/weewx-belchertown#236]
Hi,
I must say that I am excited about this template. Great job. Today I have observed that the total precipitation values ​​that appear in the records do not match the values ​​that appear in the reports or in the graph, see attached images. Has it happened to someone else?

thanks for your generous help
![Imagen 1](https://user-images.githubusercontent.com/45130728/71152837-d3317180-2237-11ea-9061-53741b506af8.png)
![Imagen 2](https://user-images.githubusercontent.com/45130728/71152838-d3ca0800-2237-11ea-9665-50b5a17f6ab4.png)
![Imagen 3](https://user-images.githubusercontent.com/45130728/71152839-d3ca0800-2237-11ea-973e-3a3ff34eda85.png)

**Comment by poblabs** [comment]
Which version of the skin are you using? In the [development version](https://github.com/poblabs/weewx-belchertown/tree/development) I think this was fixed. Please re-open if you are on development version and see this issue.
