### ISSUE TITLE
KIOSK Enhancement - Forecast

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#237]
Hi,

Would it be possible to create a second page in the PI Format with the Forcast section and reference via a small button to the forecast?

Br,
Johannes

**Comment by norecords** [comment]
As you read in this issue #231 
the pi kiosk is not in active development so it 's all to you if you want to add or modify the code.

**Comment by poblabs** [comment]
I could possibly add something like this but the challenge would still remain on how to flip between those pages. That would be outside the ability of the skin

**Comment by trdischat** [comment]
One option would be to open the two pages in two tabs of the chromium browser, then tab back and forth between them. I think I have seen guides on setting up an rPi kiosk with a couple of lines of code that causes the browser to continuously flip between the two tabs on a preset time interval; e.g., maybe 30 seconds.

**Comment by poblabs** [comment]
[Yep, my own website talks about a script that'll open tabs in kiosk mode, then auto-switch between them](https://obrienlabs.net/setup-raspberry-pi-kiosk-chromium/). Right now a Pi-focused forecast page doesn't exist though.
