### ISSUE TITLE
Frequent Update of MQTT

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#238]
Hi, I have a strange issue recently. I think it is not related to the skin, but maybe someone has an idea.

I have a poll interval of 1 minute and I am publishing the values to MQTT and displaying them via websocket.

Normally the values are changing in the "poll intervall" every 1 minute. But sometimes it seem weewx is sending multiple messages (3) in a short timeframe (couple of seconds).

Any ideas?

**Comment by ebnerjoh** [comment]
Hi,

I am one step ahead. It is, as already asumed, not the SKIN, but also not the WeeWX Installation.

I am running an OnPrem MQTT Brooker. But because I do not want to expose my Brooker to the World I am cloning the MQTT Message from WeeWX via NodeRed and forwarding them to ECLIPSE MQTT.

In the weewx.conf I am setting the mqtt attributes for the SKIN to Eclipse MQTT. I think this worked fine.

Now I have the following expericene: my internal MQTT Message is forwarded to Eclipse and eclipse is starting to reply back every 2 seconds alternating with the correct value und then with an incorrect value....

Br,
Johannes
Now I was able

**Comment by ebnerjoh** [comment]
I changed for the time beeing to my internal MQTT Broker, but as I do not want to expose it to the internet it is only working internally.

I am looking for a MQTT Broker, who offers Websocket on 443 so that it is also working when accessed from corporate networks where only 443 is opened.

**Comment by norecords** [comment]
hi, you use one of this list.
[public_brokers](https://github.com/mqtt/mqtt.github.io/wiki/public_brokers)
