### ISSUE TITLE
PI Kiosk: Image of Weather Status not updated

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#239]
Hi,

I noticed this morning, that my PI Kiosk was showing "cloudy" although the weather was clear.
Then I checked on the webpage and there it showed correctly "clear". Everything else was identically.

After restart of the PI the Icon changed from "cloudy" to "clear".

Br,
Johannes

**Comment by ebnerjoh** [comment]
Hi,

I was able to trace down the issue a little bit.

If using MQTT with the Kiosk Mode then the Values are correctly updated, but not the Weather Icon.

If I disable MQTT, then the Kiosk Mode is not update anymore at all, the values stays the same until the next manual reload or reboot.

The main page is correctly updated.

Br,
Johannes

**Comment by ebnerjoh** [comment]
If I check the source code of the full blown website I can find:

`

// Reload the page on an interval for updated data. This is for non-mqtt websocket websites
--
  | function autoRefreshPage() {
  | window.location = window.location.href;
  | }
  | setInterval('autoRefreshPage()', 60000);

`

But if I check the source code of the /pi then I cannot find the refresh part.

**Comment by ebnerjoh** [comment]
Dear @poblabs 

Would it be possible to combine "MQTT" together with "RefreshPage" to get the Weather Icon updated although using MQTT?

Br,
Johannes

**Comment by ebnerjoh** [comment]
Something I noticed: The text below the icon is updating correctly, only the icon it self is not updating.

Br.
Johannes

**Comment by poblabs** [comment]
Are you using the development version? I think this is fixed in that version

**Comment by ebnerjoh** [comment]
Yes, I am using the Dev-Version from ~ 2weeks ago

**Comment by poblabs** [comment]
Ok I will take a look at this when I can.

**Comment by poblabs** [comment]
Are you using MQTT?

**Comment by ebnerjoh** [comment]
Yes, I am using MQTT

Am Do., 5. März 2020 um 15:58 Uhr schrieb poblabs <notifications@github.com

**Comment by poblabs** [comment]
Strange, it should be updating the icon if an update is available when MQTT has an archive interval. The section below is for those not using MQTT. I will add it to the Pi page though for consistency. I'll do some more testing. 

```
        function autoRefreshPage() {
            window.location = window.location.href;
        }
        setInterval('autoRefreshPage()', $Extras.webpage_autorefresh);
```

**Comment by poblabs** [comment]
Found it. A typo on a missing img ID. Please update to the latest development version for the fix. Thanks!

**Comment by ebnerjoh** [comment]
Hi,

It is working now! Many thanks!

Br,
Johannes


Am Do., 5. März 2020 um 16:25 Uhr schrieb poblabs <notifications@github.com
