### ISSUE TITLE
  Stop update Stop update 

### ISSUE THREAD

**Issue by kan6526** [poblabs/weewx-belchertown#243]
debian10 , ubuntu server  /var/log/syslog

Jan 13 15:25:59 ubuntu weewx[1946]: manager: Added record 2020-01-13 15:25:00 CST (1578900300) to database 'weewx.sdb'
Jan 13 15:25:59 ubuntu weewx[1946]: manager: Added record 2020-01-13 15:25:00 CST (1578900300) to daily summary in 'weewx.sdb'
Jan 13 15:26:00 ubuntu weewx[1946]: restx: MQTT: Published record 2020-01-13 15:25:00 CST (1578900300)
Jan 13 15:26:00 ubuntu weewx[1946]: cheetahgenerator: Generated 8 files for report SeasonsReport in 0.87 seconds
Jan 13 15:26:01 ubuntu weewx[1946]: imagegenerator: Generated 14 images for SeasonsReport in 0.56 seconds
Jan 13 15:26:01 ubuntu weewx[1946]: copygenerator: copied 0 files to /var/www/html/weewx
Jan 13 15:26:02 ubuntu weewx[1946]: cheetahgenerator: Generated 11 files for report Belchertown in 0.95 seconds
Jan 13 15:26:02 ubuntu weewx[1946]: copygenerator: copied 2 files to /var/www/html/weewx/belchertown
Jan 13 15:26:02 ubuntu kernel: [246139.472702] show_signal_msg: 9 callbacks suppressed
Jan 13 15:26:02 ubuntu kernel: [246139.472707] python[3907]: segfault at 78 ip 000055c6f0b7d7c5 sp 0000000000000078 error 4 in python2.7[55c6f0a8b000+300000]

**Comment by poblabs** [comment]
I don't know what I'm supposed to be looking at. Please provide more detail of what is wrong. Everything here looks fine.

**Comment by kan6526** [comment]
--------/var/log/syslog---------------
Jan 13 15:26:02 ubuntu kernel: [246139.472702] show_signal_msg: 9 callbacks suppressed
Jan 13 15:26:02 ubuntu kernel: [246139.472707] python[3907]: segfault at 78 ip 000055c6f0b7d7c5 sp 0000000000000078 error 4 in python2.7[55c6f0a8b000+300000]

stop update chart

**Comment by poblabs** [comment]
How is this related to the Belchertown skin? I'm not sure what this is referencing. Doesn't look weewx or Belchertown related. Looks like it's something with your machine and Python.
