### ISSUE TITLE
Highcharts credits link very sensitive on mobile scrolling

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#247]
Hello Pat,
I would like to share an issue I face with the skin and a possible solution (maybe you have better idea).
I use a lot the website from mobile...and as right-handed, scrolling with thumb on right side on the my phone screen.
When scrolling in graphics area, there is this "highcharts" link that seems extremely sensitive and gets unintentionally clicked when scrolling on it.

Here is a screenshot of graphics as it appears on my phone, with "Highcharts.com" credit link on right:
![signal-attachment-2020-02-13-104511](https://user-images.githubusercontent.com/24415431/74422118-60670000-4e4e-11ea-9350-3a790da60e2a.jpeg).

I discovered on highcharts API that this credit link can be customized:
https://api.highcharts.com/highcharts/credits

It seems it can be disabled or aligned differently.
I'm not sure "disable" is fair or even allowed for free use of highcharts, but align left would be a nice work around and push the link away from my thumb in most situation.

It would be great to make this option possible with Belchertown skin (choosing left or right, so left or right handed can choose best for them).

Maybe it's feasible as explained here: 
https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#almost-every-highcharts-series-options-are-accepted
But I didn't figured out how...and I'm not sure it's possible this way: these credits options are not at series data option level.

**Comment by poblabs** [comment]
@bonjour81 This should be all set now. Download the latest Development version and add this to your graphs.conf. 

The credits are global options, so they go right at the top of the graphs.conf 

```
credits = "Your custom text here. Delete this line if you don't want custom text"
credits_url = "Your custom link here. Delete this line if you don't want a custom link"
credits_position = '{"align": "left", "x": "15"}'
```

**Comment by poblabs** [comment]
Wiki is updated. Closing this

**Comment by bonjour81** [comment]
Hi! I forget to say: thank you !! it works perfectly !! :+1: 
link is moved, I no more load highchart webpage while scrolling my graphs
