### ISSUE TITLE
Specific day in history

### ISSUE THREAD

**Issue by jendrush** [poblabs/weewx-belchertown#249]
Than you for the amazing software! Maybe this isn't best place to ask this, but i didn't find solution. Is it possible to choose specific day to see the data? We have Today, Yesterday, Week, Month etc., but how to check for example september 3 2019 data?

**Comment by norecords** [comment]
Hi @jendrush 
see the wiki..
[Time Scales for Charts](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#time-scales-for-charts)

**Comment by jendrush** [comment]
Thank you for link. This is of course solution, but i thought about something in UI, similar to Weather Underground.

**Comment by poblabs** [comment]
Nothing in the ui exists for something like this because of the way the skin works with weewx how it exports data as text files (not directly connected to a database).
