### ISSUE TITLE
Using UV Index on observation table

### ISSUE THREAD

**Issue by kacnje** [poblabs/weewx-belchertown#252]
I'm preparing a new website with Belchertown skin. 
I have tried many things, but they didn't work. 
I'm using Vantage Vue without UV Index. But I know that Darksky can return this information. 
Can I use this UV Index on observation table on Belchertown skin? Maybe even cloudbase?

And one more thing - as someone already written here - it would be very nice if we can use Darksky forecast only for icons (near temperature) and for extra information (UV index, visibility, cloudbase), but WITHOUT the forecast itself. It really isn't good for our part of Europe (and biggest complain is how they choose icon for forecast). 

Any suggestion?

**Comment by poblabs** [comment]
cloudbase can be setup using a custom observation from weewx. [An example can be found here](https://groups.google.com/forum/#!msg/weewx-user/kQZvc6UpLtA/kjbSDNazIwAJ). If you get stuck this is a good question for the user forums.

Getting UV from darksky is not possible right now.

I have no suggestion on the icon use only for darksky. You could fork the skin and edit the javascript files to suite your needs

**Comment by kacnje** [comment]
Thank you.
