### ISSUE TITLE
Feature Req: Improved Mobile layout

### ISSUE THREAD

**Issue by mattmon** [poblabs/weewx-belchertown#253]
First of all, thanks for creating this skin - it's the best available for WeeWX, IMO.

The page layout for Desktop and tablet use is awesome, there's a ton of information at your fingertips.

Though, the mobile layout is seriously lacking in data density compared to other skins.
![compare](https://user-images.githubusercontent.com/924673/75806045-d072f280-5d37-11ea-94a0-814a9b13a42a.jpg)

It would be great to have a reworked layout for mobile devices in a future release.

**Comment by steepleian** [comment]
A Belchertown/Weather34 hybrid, now that is something I have got to see :-)

As I am the maintainer of the WeeWX version of the Weather34 template, you
might be amused to know that I use Belchertown as my go-to mobile skin!

Ian

**Comment by poblabs** [comment]
@mattmon Thanks, glad you like the skin 😄 I'm a one man shop with a family and full-time job. PRs are welcome for any improvements you can work on!

**Comment by mattmon** [comment]
I might try adding the highcharts [windbarb chart](https://www.highcharts.com/demo/windbarb-series/dark-unica).
![highcharts-wind-barbs](https://user-images.githubusercontent.com/924673/77212342-fcc29900-6ac3-11ea-8945-bd57dcebb756.jpeg)

**Comment by poblabs** [comment]
That would be great!

**Comment by mattmon** [comment]
Forgive me for going a little off topic...

The townspeople here have really been enjoying your skin for our [weather station](https://pioneer.town/weather)!
We're in a rural, mountainous area where hyper local weather has been a pretty big deal for us.

Thanks again for all your hard work!

**Comment by poblabs** [comment]
Thats awesome! Glad to hear it has an impact!
