### ISSUE TITLE
WeeWX 4.0.0b13, Belchertown 1.1b9 fails with ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by bburton** [poblabs/weewx-belchertown#254]
WeeWX 4.0.0b13 fresh install
Python 3.6
Belchertown 1.1b9

Mar  1 05:20:22 broadcast weewx[10728] INFO user.belchertown: version 1.1b9
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****  max() arg is an empty sequence
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/reportengine.py", line 197, in run
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      obj.start()
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/reportengine.py", line 280, in start
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      self.run()
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/cheetahgenerator.py", line 150, in run
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/cheetahgenerator.py", line 220, in generate
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/cheetahgenerator.py", line 220, in generate
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/cheetahgenerator.py", line 309, in generate
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      default_binding)
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/weewx/cheetahgenerator.py", line 376, in _getSearchList
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****    File "/home/weewx/weewx-4.0.0b13-py36/bin/user/belchertown.py", line 475, in get_extension_list
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****      at_days_with_rain = max( zip( at_days_with_rain_output.values(), at_days_with_rain_output.keys() ) )
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****  ValueError: max() arg is an empty sequence
Mar  1 05:20:22 broadcast weewx[10728] ERROR weewx.reportengine:         ****  Generator terminated
Mar  1 05:20:22 broadcast weewx[10728] INFO weewx.reportengine: Copied 32 files to /home/weewx/weewx-4.0.0b13-py36/public_html/belchertown

Note that previously, I had installed 1.1b8 along with a fresh install of WeeWX 4.0.0b12 and there was no issue.

**Comment by poblabs** [comment]
Are you able to attach your database? I'm running 4.0.0b14 without issues
but I think there's something in your database with rain that I need to
account for.

**Comment by bburton** [comment]
I'm a noob at WeeWX and SQLite. I do know SQL but not familiar with SQLite and tools, etc. to know how to connect and run queries.

In any case, it seems the ```at_rain_query``` on line 458 was not returning anything which caused the problem. 

However, when I change lines 475 and 476:
```python
        at_days_with_rain = max( zip( at_days_with_rain_output.values(), at_days_with_rain_output.keys() ) )
        at_days_without_rain = max( zip( at_days_without_rain_output.values(), at_days_without_rain_output.keys() ) )
```
to the following lines, there's no issue:
```python
        at_days_with_rain = 0
        if len(at_days_with_rain_output) > 0:
            at_days_with_rain = max( zip( at_days_with_rain_output.values(), at_days_with_rain_output.keys() ) )
        at_days_without_rain = 0
        if len(at_days_without_rain_output) > 0:
            at_days_without_rain = max( zip( at_days_without_rain_output.values(), at_days_without_rain_output.keys() ) )
```
I'm about to upgrade to 4.0.0b14. If it would be helpful to do a clean install, I'll try again with that.

**Comment by poblabs** [comment]
Ok cool. I can add this as a patch to the development branch shortly and then you can test with a clean install

**Comment by poblabs** [comment]
I took your patch and adjusted it for the skin and the records page presentation. I pushed it to the development branch. Please re-download the development branch and install it and give it a test when you can.

**Comment by poblabs** [comment]
Let me know your results

**Comment by bburton** [comment]
Copied bin/user/belchertown.py and skins/Belchertown/reports/index.html.tmpl into my 4.0.0b13 install and it's working fine.
