### ISSUE TITLE
Version 1.1b9 displays broken icon if forecast is not enabled

### ISSUE THREAD

**Issue by bburton** [poblabs/weewx-belchertown#255]
In version 1.1b9 on the main page, the current observation icon to the left of the temperature displays as a broken link if the skin.conf setting ```forecast_enabled = 0``` to disable forecasts. 

In looking into this, it seems the variable ```current_obs_icon``` is only set to a non-blank value in bin/user/belchertown.py when forecast is enabled, otherwise, it's blank.

The simple fix is to only display the &lt;img/&gt; tag when forecast has been enabled. On line number 176 of index.html.tmpl, change:
```html
<img id="wxicon" src="$relative_url/images/$current_obs_icon">
```
to:
```html
#if $Extras.has_key("forecast_enabled") and $Extras.forecast_enabled == '1'
<img id="wxicon" src="$relative_url/images/$current_obs_icon">
#end if
```

**Comment by poblabs** [comment]
Great catch! Thanks! Just modified the file and pushed the commit. All set now 😄
