### ISSUE TITLE
Translate title possible ?

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#257]
Hi, 

I want to translate the title of website when use a browser like this  : 
![image](https://user-images.githubusercontent.com/61891683/76252468-17397e80-6249-11ea-9ccb-729cb33151ce.png)
But I don't saw a parameter on configs to change it, it is possible today ?

Also, when I want to change the title chart, it doesn't work (by using credits and credits_url parameter).

My global default of graphis.conf : 

Global Chart Defaults
These are fallback options that charts will use if an option is not defined. 
aggregate_type = None
time_length = 90000 # Last 25 hours
type = line
colors = "#7cb5ec, #b2df8a, #f7a35c, #8c6bb1, #dd3497, #e4d354, #268bd2, #f45b5b, #6a3d9a, #33a02c"
tooltip_date_format = "LLL"
credits = "Weather of Drealine"
credits_url = "https://weather.drealine.com"

**Comment by poblabs** [comment]
Yes everything should be translatable. You change it in the skin options under weewx.conf not in graphs.conf. Information [is in the readme of the skin](https://github.com/poblabs/weewx-belchertown#translating-the-skin).
