### ISSUE TITLE
Branch development - Time not show properly

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#258]
Hi,

I've installed a development zip to Weewx.

But 2 things work not properly.

- The time at the header (MQTT) show a time with caracters (format problem ?) I use the UTC+1.
- I've a white picture near of temperature, but I read that you fixed it on your commits by remove the if function.

Thank for you reply.

**Comment by poblabs** [comment]
Please provide a link to your site and screenshots

**Comment by Drealine** [comment]
https://weather.drealine.com

![image](https://user-images.githubusercontent.com/61891683/76523043-fd29b700-6467-11ea-80ac-f0821c70c314.png)
![image](https://user-images.githubusercontent.com/61891683/76523064-074bb580-6468-11ea-91dc-a0e6f123b9cd.png)

**Comment by poblabs** [comment]
I have never seen this before. I would recommend deleting and reinstalling the skin. There are quite a few things that do not look like they installed correctly.

**Comment by Drealine** [comment]
Still nothing by delete : 

- Folder html
- belchertown.py
- Delete skins folder

The problem appear when enable MQTT for time. You can view the default skins at the moment on my website.

**Comment by Drealine** [comment]
The problem can be appear by installing zip file using wee_extensions ?

**Comment by poblabs** [comment]
I don't know. I haven't seen this before. Run this:

* `wee_extension --uninstall Belchertown`
* Delete everything out of your HTML folder
* `wget https://github.com/poblabs/weewx-belchertown/archive/development.tar.gz`
* `wee_extension --install development.tar.gz`
* `service weewx restart`

**Comment by Drealine** [comment]
Same problem. I deleted files attached to Belchertown and follow your instructions

In debug mode on Google Chrome is see this : 

![image](https://user-images.githubusercontent.com/61891683/76541137-6539c680-6483-11ea-9455-676545289cc6.png)

It's normal ?

**Comment by Drealine** [comment]
I suggest for the white image to check if forecast = 0 and forecast = 1.
On your commit, the if function is disable and the image is automaticly show. 
#if $Extras.has_key("forecast_enabled") and $Extras.forecast_enabled == '1'
                                        <img id="wxicon" src="$relative_url/images/$current_obs_icon">
                                        #end if

**Comment by poblabs** [comment]
I'm still confused. The forecast_enabled is in your skin.conf. If you want to change the value of this option, it should be done in weewx.conf under skin settings. 

Here I have set it to 0 in weewx.conf

```
    [[Belchertown]]
        HTML_ROOT = public_html/btownwx
        skin = Belchertown
        [[[Extras]]]
            theme = auto
            site_title = Belchertown Weather
            forecast_enabled = 0
```

Here is the result. 

No image, no blank image, no div, nothing. The commit you referenced is working as designed. 

It was only show the image if the option exists AND is set to 1. 

![image](https://user-images.githubusercontent.com/3484775/76623797-7e398a80-650a-11ea-9f35-9244d1077da3.png)

**Comment by poblabs** [comment]
Your website looks fine to me.

![image](https://user-images.githubusercontent.com/3484775/76624913-97433b00-650c-11ea-9289-26c9b1725f02.png)

**Comment by Drealine** [comment]
I downgraded to v1.0.1 so it's ok for the moment.
I not tested with put the parameter on weewx.conf.

But the hour still showing a wrong value when MQTT is enabling
I can pushing out the v1.1.1 on my server

**Comment by poblabs** [comment]
The hour showing wrong may be because of a bad timezone setting in your config somewhere? 

As you can see, MQTT sends the time as unix epoch. The JavaScript converts it to your timezone using UTC offset. 

```
{"cloudbase_meter": "854.347800205", "outHumidity": "65.3", "pressure_mbar": "1012.76710666", "rain_cm": "0.0", "maxSolarRad": "363.970780047", "barometer_mbar": "1020.89443824", "dewpoint_C": "5.5", "windGust_kph": "17.7028280001", "heatindex_C": "11.2222222222", "dayRain_cm": "0.0", "inDewpoint_C": "9.21476743797", "altimeter_mbar": "1020.78192636", "windchill_C": "10.2222222222", "appTemp_C": "9.49908889102", "outTemp_C": "11.7777777778", "windGustDir": "234.0", "humidex_C": "11.7777777778", "rain24_cm": "0.0", "hourRain_cm": "0.0", "inTemp_C": "18.7777777778", "windSpeed_kph": "6.43739200004", "usUnits": "16.0", "txBatteryStatus": "0.0", "rainRate_cm_per_hour": "0.0", "dateTime": "1584110981.0", "windDir": "244.0", "inHumidity": "53.8"}
```

Here is your latest update: `"dateTime": "1584110981.0"`

Verify the time is correct on your weewx server

**Comment by Drealine** [comment]
I upgraded to v1.1.1. You can visit my website : https://weather.drealine.com. The problem is not the timezone but it showing letters on the time (problem convert ?)

And also, I set forecast_enabled = 0 on weewx.conf but like you can see on my website, the blank image already appear.

**Comment by Drealine** [comment]
My sking.conf and graphs.conf [](url)
[graphs.txt](https://github.com/poblabs/weewx-belchertown/files/4330232/graphs.txt)
[skin.txt](https://github.com/poblabs/weewx-belchertown/files/4330233/skin.txt)

**Comment by poblabs** [comment]
No blank image here. Your site looks exactly how it should with forecast_enabled = 0

Try clearing your cache and cookies.

I will look into the time showing letters. This is strange.

![image](https://user-images.githubusercontent.com/3484775/76633822-b72e2b00-651b-11ea-8a85-e0a378611004.png)

**Comment by Drealine** [comment]
Thank for your reply.
On the homepage no problem, but if you go to another page like Graphs, you can see the blank image. : https://weather.drealine.com/graphs/

**Comment by poblabs** [comment]
Ah yes, you are right, I see that and I will fix that. 

Give me some time to look at your time issue. I haven't seen this before

**Comment by poblabs** [comment]
Are you using Python 2 or Python 3?

**Comment by Drealine** [comment]
The weewx that I've installed use Python 2.7 when I check /var/log/syslog.
Why ? 
If it's the version, it is possible to force weewx to use python > 3 ?

**Comment by poblabs** [comment]
If you use Python 3 then you need to use weewx 4 beta. So you can stay how you are now unless you want to upgrade everything.

I am looking to test this with Python 2.7 so I can fix it.

**Comment by Drealine** [comment]
Ok, I try this on the WE. 
You used Weewx 4? 

I've also more informations on syslog :

**Comment by poblabs** [comment]
Yes I am using weewx 4, and Python 3. If you run into trouble with weewx you need to ask on the user forums since it is being actively developed.

**Comment by Drealine** [comment]
Allright thank you.
Errors that show on logs can help you ?

**Comment by poblabs** [comment]
Yes, did you delete items out of skin.conf? You should be able to leave skin.conf alone and manage the skin from weewx.conf

Advise you to reinstall skin.conf, restart weewx

**Comment by poblabs** [comment]
I have installed Python 2, and weewx 3.9.2 and Belchertown skin 1.1b9 and I am not able to reproduce the error of the time. This is very strange. I am also using the French locale and it is not happening. 

![image](https://user-images.githubusercontent.com/3484775/76643428-60c8e880-652b-11ea-9b70-727140e9bba3.png)

---

Have you made any changes to the skin files? I see a lot of errors in your console debug log.

![image](https://user-images.githubusercontent.com/3484775/76643486-7ccc8a00-652b-11ea-8258-e5a32b6a3446.png)

**Comment by Drealine** [comment]
Finally, I edit the new skin.conf and the time show perfectly. I don't understand why ... Maybe that when I erase the skin.conf file with my skin.conf (v1.0.1 of Belchertown), some parameters disapears.

**Comment by Drealine** [comment]
For blank image, I wait to fix it on your differents commits. See you soon and thank you for your disponibility :)

**Comment by poblabs** [comment]
You're welcome. I just pushed a commit for the fix of the blank images on the other pages if forecast_enabled = 0
