### ISSUE TITLE
Install issues 0.8rc3

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#26]
Hi Pat

Just did an in place upgrade of the latest downloaded zip file and the file index_custom_hooks.inc.example wasn't created. I also can't see the version number in the footer?

Are the instructions for creating the custom pages on Github yet? I couldn't see them.

The chart customisation appears to work well, thanks :)

**Comment by 41south** [comment]
It's in the zip file ok, but didn't get created on the /skins/Belchertown directory

**Comment by poblabs** [comment]
I always forget that when I add new files, I need to add them to the installer. I even have it written down to do it and still, I forget 😄  Should be all set now.

Still haven't worked on a way to hook in custom pages. Or do you mean adding custom information to the index.html page?

**Comment by 41south** [comment]
Sorry meant using the custom areas not pages  - * 4 Custom rows now available on index page for you to customize content. Check the readme on GitHub for more info on how to use these areas.

But I can't find anything about using them in the readme on Github. 

I've used one to add some lightning info at the bottom of my index page 👍

**Comment by poblabs** [comment]
Closing - let me know if you have other issues 😄
