### ISSUE TITLE
Branch development - Somes problems

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#260]
Hi Pat,

Once again Drealine. I've 2 problems  
- I'm not able to translate with the parameter on skin.conf moon_phases.
- I've set a radar html but still not reload when I keep on my website. I set this on my skin.conf : reload_images_radar = 30

Thank you,

**Comment by poblabs** [comment]
Hi Drealine, 

1. moon_phases is translated in weewx.conf. Search for `moon_phases` then restart weewx when done. 
2. I'll load your website and watch this to see what is wrong. I will update you

**Comment by poblabs** [comment]
I just committed a slightly different method of updating the image. Please download the commit updates, or the whole development branch again, restart weewx and see if the radar image updates. 

I did notice that it doesn't update until about every 5 or 10 minutes in testing

**Comment by Drealine** [comment]
Hi,

Thank you very well for your answer. The reload radar work very well :) 

For Moon Phases, the translate work also but something happen 1 min after you stay on my website, the phase of the Moon indicate "L". On log, the bug appear when it generate files because I've set archive interval to 1min. 

I don't know if it's an issue of the skin or Weewx.

**Comment by Drealine** [comment]
I'm not sure but I've a third question, it is possible to translate the risk when a city have a warning ? I supposed that depend to the API Darsky

![image](https://user-images.githubusercontent.com/61891683/76686255-5df8f100-661a-11ea-9144-e79cf8f2070b.png)

**Comment by Drealine** [comment]
> Hi,
> 
> Thank you very well for your answer. The reload radar work very well :)
> 
> For Moon Phases, the translate work also but something happen 1 min after you stay on my website, the phase of the Moon indicate "L". On log, the bug appear when it generate files because I've set archive interval to 1min.
> 
> I don't know if it's an issue of the skin or Weewx.

Restart weewx resolve the problem normaly, if you can check that the problem not appear also.

**Comment by poblabs** [comment]
Everything looks good including the radar!
