### ISSUE TITLE
Request - Branch Developement

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#262]
Hi Pat,

I would like to ask if it possible to translate the risk when a city have a warning ? I supposed that depend to the API Darsky.

Like this : 
![76686255-5df8f100-661a-11ea-9144-e79cf8f2070b](https://user-images.githubusercontent.com/61891683/76701916-cb159080-66c5-11ea-856d-bd44b9a85141.png)

**Comment by poblabs** [comment]
Yes that would be from DarkSky, not me. You could reach them in your portal to ask how to translate it.
