### ISSUE TITLE
Add support for paho-mqtt 'path' option

### ISSUE THREAD

**Issue by mattmon** [poblabs/weewx-belchertown#264]
Would be great to have additional options for paho-mqtt exposed in skin.conf.

For example:

```
mqtt_websockets_client = "belchertown"
mqtt_websockets_path = "/ws"
```

I have both hacked into my installation.
Setting the client id makes troubleshooting mosquitto logs much easier.

Setting the websocket path is necessary if you want to keep everything on a single port.

Here's an example nginx config:
```
root /var/www/html;

# serve weewx static content
  location /weewx {
    try_files $uri $uri/ =404;
  }

# proxy websocket to mosquitto  
  location /ws {
     proxy_pass http://127.0.0.1:9001;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_read_timeout 86400;
  }
```

Should note that this can also be accomplished with mosquitto alone using the http_dir config directive.

**Comment by poblabs** [comment]
I'm under the impression that the client id needs to be unique. Is this not true? If you had 5 people on your weather website all with the same client id wouldn't that cause a problem?

I'm wondering about your other option too. Not everyone is savvy enough to do or understand the single port or nginx configs, whats the benefit here for the broader audience?

**Comment by mattmon** [comment]
That's true, so you'd not want it set for 'production' use.

Though many projects use paho-mqtt's default id, being able to change this made troubleshooting my installation easier. 

The path option and proxying means only exposing a single port... and it's nginx, not mosquitto.

Slightly increased config complexity nets a greatly reduced attack surface.
Seems like benefit enough to me :-)

**Comment by FutureCow** [comment]
@mattmon 

can you describe how you did the "hacked into my installation" thing?

I also have a problem getting more ports exposed to the internet. It's a big network over here where multiple ports are already used and the network manager is not keen on exposing more port. So an option to have the mqtt path on the same machine would me nice. Also better for safety?

@poblabs 
Do you think the problem with the same id's still stands? I want to use this in "production"
