### ISSUE TITLE
How to add external observation?

### ISSUE THREAD

**Issue by mattmon** [poblabs/weewx-belchertown#265]
I recently added a Purple Air Quality sensor to WeeWX using [weewx-purpleair](https://github.com/bakerkj/weewx-purpleair) and [weewx-aqi](https://github.com/jonathankoren/weewx-aqi).

The sensor readings and aqi calculations are in separate databases.

I can add air quality observations to the templates using statements like:

`$current($data_binding='aqi_binding').aqi_pm2_5
$aqi($current($data_binding='aqi_binding').aqi_pm2_5_category).category`

Though, I'd like to have it within the observation table on the first row.

Can you give me any guidance on how to get air quality into the observations table generated by belchertown.py?

**Comment by norecords** [comment]
I think you have to follow this : 
[Adding a new observation type to the WeeWX database](https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database)

**Comment by mattmon** [comment]
The AQI observations already exist and I can display them elsewhere in the template without problem.

I'm looking for specific guidance on how to add an unsupported observation type to to the         "Get Current Station Observation Data" portion of belchertown.py

**Comment by poblabs** [comment]
@mattmon It's been a busy few months - sorry for the delay. If you're looking to add something to the station_observations table (where you reference "Get Current Station Observation Data"), I'm pretty sure you can add it to the station_observation variable. 

If your observations are in a different database binding, then you need to specify it like this (based on your example):

`station_observations = "barometer", "dewpoint", "outHumidity", "rainWithRainRate", "aqi_pm2_5(data_binding=aqi_binding)"`

Auto-updates with MQTT labels may get tricky though with the current setup.

**Comment by sjthespian** [comment]
I can confirm that @poblabs comment above is correct. I added weewx_purple to my system a week ago and just updated my weewx.conf go add:
```
            station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, pm2_5, radiation
```
and under Generic:
```
                pm2_5 = AQI PM 2.5
```
Which gives me:
<img width="313" alt="Screen Shot 2020-09-10 at 09 25 38" src="https://user-images.githubusercontent.com/1789285/92762713-b4d05080-f347-11ea-8533-af6b1b9e11c0.png">

**Comment by poblabs** [comment]
Thanks for confirming @sjthespian ! I'll close this issue as it appears to be working.
