### ISSUE TITLE
Darksky has joined Apple.

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#268]
By Adam Grossman on March 31, 2020.
Today we have some important and exciting news to share: Dark Sky has joined Apple.

Website
Weather forecasts, maps, and embeds will continue until July 1, 2020. The website will remain active beyond that time in support of API and iOS App customers.

API
Our API service for existing customers is not changing today, but we will no longer accept new signups. The API will continue to function through the end of 2021. As part of this transition, use of Dark Sky by Apple is subject to the Apple Privacy Policy, which can be found at apple.com/privacy.

The Dark Sky Team

**Comment by biltmorelaker** [comment]
So, this will immediately impact new Belchertown users (that don't currently subscribe to the Darksky API) and want to use the Darksky forcecasts. Plus, if you look at the announcement on [https://blog.darksky.net/](url), you'll see that 

> Weather forecasts, maps, and embeds will continue until July 1, 2020. The website will remain active beyond that time in support of API and iOS App customers.

I believe that means that the "Daily Forecast" links under each day of the 8 day forecast will stop working on July 1, 2020 even for those who are current API subscribers.

😭

**Comment by poblabs** [comment]
For existing Belchertown users, we're OK. [For new users, they're not OK](https://belchertownweather.com/about/#isso-36). 

Existing Belchertown API key holders will get updates until 2021:

> API
>
>Our API service for existing customers is not changing today, but we will no longer accept new signups. The API will continue to function through the end of 2021.

So I have to look for something else. OpenWeatherMap seems like the next best choice but their free tier only offers a 5 day forecast I think - and I don't know if it's available world wide.

**Comment by themoosman** [comment]
api.weather.gov has 7 days but is US only.

https://www.weather.gov/documentation/services-web-api

**Comment by norecords** [comment]
I'm using this service for my mobile app :
[https://www.yr.no/artikkel/information-about-the-free-data-1.6810075](https://www.yr.no/artikkel/information-about-the-free-data-1.6810075)
but it's in xml format, here is an exemple for my location
[https://www.yr.no/place/France/Provence-Alpes-C%C3%B4te_d%E2%80%99Azur/Correns/forecast.xml](https://www.yr.no/place/France/Provence-Alpes-C%C3%B4te_d%E2%80%99Azur/Correns/forecast.xml)

**Comment by poblabs** [comment]
Pretty good discussion going on [in this thread here on the weewx user forums](https://groups.google.com/forum/#!topic/weewx-user/m_47lX0fsIM). 

What my plan is right now is to release 1.1 as it is right now, then work on 1.2 with OpenWeatherMap. 

yr.no is a close second, but they don't support unit conversions or language translations.

**Comment by biltmorelaker** [comment]
At [this link](https://groups.google.com/d/msg/weewx-user/2UEdWiZpTd0/rzJE2aQ0AwAJ) on the weewx-user forum,  galfert points out that Aeris Weather has an API that is free for those who upload to PWSWeather. It looks to be quite complete and even includes Alerts. Hopefully it would be a better replacement for the Darksky API than OWM. @poblabs what do you think?

**Comment by poblabs** [comment]
I think it's worth checking out. Especially since weewx users can send their data to pwsweather easily since it's built in.

**Comment by biltmorelaker** [comment]
Hmm. This may have been a false alarm. I signed up for an Aeris account linked to my PWSweather account. But when I go to the API site with that account, they only offer a 30 day free trial. After that there is a monthly or annual cost for the API subscription. Not sure if I'm missing something.

I posted this info on the weewx-user forum and will update this "Issue" here if I get more info.

**Comment by poblabs** [comment]
@biltmorelaker Looks like it may be free so long as your weewx is sending "quality data to pwsweather.com monthly". Here's what my account says for billing. 

![image](https://user-images.githubusercontent.com/3484775/80237520-db0c8280-862a-11ea-9db7-8256618cbe79.png)

**Comment by biltmorelaker** [comment]
@poblabs I think you are correct about the billing, but also correct about alerts only available for US and Canada. I had seen other countries mentioned, but those were probably for forecasts.

**Comment by poblabs** [comment]
@biltmorelaker This API seems to include more data than OWM which is great. However it'll take 3 API calls per period to get all that data (current observations, forecast, alerts). A little more work to parse it all together. Plus they don't support translations, so I have to work on the [coded weather data](https://www.aerisweather.com/support/docs/api/reference/weather-codes/) and provide the translation labels. So a bit of work to investigate.

**Comment by george-crum** [comment]
This looks like a possible darksky replacement too https://www.visualcrossing.com/weather-data-editions

**Comment by poblabs** [comment]
Right now the plan is to use Aeris Weather which is implemented in the development version of the skin. You can get a free API key with them by uploading your station data to their pwsweather.com site (which is integrated into weewx core itself)
