### ISSUE TITLE
Strange extraTemp1 values in records-table.inc

### ISSUE THREAD

**Issue by wwray** [poblabs/weewx-belchertown#269]
Hi Pat, thanks again for all the amazing work you've done on this skin.  I'm having an odd issue with my records page @ https://www.wraynet.com/records/  I'm running the newly released 1.1 (yay!)

I've added into the records-table.inc file 3 other data columns: extraTemp1, inHumidity, and extraHumid1

The other two work fine, but the extraTemp1 is showing a max of 128.6C which I believe would indicate a fire in my garage. 

I've looked at my weewx database and the max value for extraTemp1 is 94.2 which I believe is in F. The min is 44.4 and the record low is showing as 1.9C  

Any help you could provide would be most appreciated. Happy Easter!

Will

**Comment by wwray** [comment]
Hi Pat, congrats on the newborn! I figured it out, it was a bad value in the archive_day_extraTemp1 table. I rebuilt it using wee_database --rebuild-daily --date=YYYY-mm-dd and now there are more reasonable values. Thanks !

**Comment by poblabs** [comment]
Great! Glad you figured it out!
