### ISSUE TITLE
Forecast Table Wraps

### ISSUE THREAD

**Issue by weswitt** [poblabs/weewx-belchertown#27]
I'm seeing an issue where the 8 day forecast table wraps the 8th day onto a new row. I only see this in Firefox and Chrome on Linux. Seems OK on Windows.

Is this a skin bug or an issue on my end? What can we do to debug this?

**Comment by poblabs** [comment]
Every browser has their quirks, and I try to accommodate them all. Chances are the row might be off by 1 pixel which is making those Linux browsers a bit unhappy, but OK on Windows. 

Try this:

In [skins/Belchertown/style.css around line 1972](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/style.css#L1972) will be the width for those boxes. It's set to `148px`. Try changing to `145px`, save and restart weewx. Then force a site generation with wee_reports and see if that helps. 

Removing 3 pixels should help, but hopefully doesn't make it feel weighted wrong. Or maybe that's just my OCD?

**Comment by weswitt** [comment]
Thanks so much. That fixed the problem.
