### ISSUE TITLE
Defaults Units group_pressure Set to hPA Belchertown 1.1 Shows InHg Value Using MQTT

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#270]
I'd like to show pressure in hPa and have changed the group_pressure in weewx.conf to hPa
`group_pressure = hPa    # Options are 'inHg', 'mmHg', 'mbar', or 'hPa'`
The Belchertown skin shows this once when the page is generated.
When an MQTT packet arrives, the pressure value is in inHg while the unit label does continue to show hPa.

Is there a way to show the value that I want?

**Comment by poblabs** [comment]
Yes you need modify the MQTT extension settings. You have to set the units to what you want and the name has to be set to the observation_unit. 

Take a look at this for some insight: https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099

**Comment by gary-hammer** [comment]
Excellent! Thanks for the catch Pat, I didn't know I could configure the MQTT extension on a granular basis.
