### ISSUE TITLE
Error writing forecast file

### ISSUE THREAD

**Issue by tomdotorg** [poblabs/weewx-belchertown#271]
Running weewx 4.0.0b18 in a Docker image. When writing the forecast file, I am getting the following exception:

Apr 13 20:55:04 weewx-deployment-vt-dev-8675b5598c-tll6n weewx[27] INFO user.belchertown: version 1.1
Apr 13 20:55:04 weewx-deployment-vt-dev-8675b5598c-tll6n weewx[27] INFO weewx.restx: MQTT: Published record 2020-04-13 20:55:05 EDT (1586825705)
Apr 13 20:55:05 weewx-deployment-vt-dev-8675b5598c-tll6n weewx[27] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Apr 13 20:55:05 weewx-deployment-vt-dev-8675b5598c-tll6n weewx[27] ERROR weewx.reportengine:         ****  Error writing forecast info to /home/weewx/public_html/belchertown/json/darksky_forecast.json. Reason: [Errno 2] No such file or directory: '/home/weewx/public_html/belchertown/json/darksky_forecast.json'

This seems to be after weewx has written its own html.

**Comment by poblabs** [comment]
I haven't run this in docker, so I'm not sure entirely. Do you have the volume mapped correctly?

**Comment by hoetzgit** [comment]
at the first time the file does not exist

**Comment by tomdotorg** [comment]
OK, I will let it run longer this time and report back. Thanks.

**Comment by tomdotorg** [comment]
@hoetzgit - correct! Letting it run for a second report cycle did the trick, so that error that implies it was unable to *write* the forecast json file is really trying to say it couldn't find it in the first place I guess.
This is on line 601 of belchertown.py - I am not a Python expert so I am not sure how one would fix this. I guess the open with wb+ will throw an exception if the file doesn't exist..

**Comment by hoetzgit** [comment]
Before opening the file, it must be checked whether the file exists, then the error would have been rectified.

**Comment by tomdotorg** [comment]
I can play around with it and submit a PR if nobody else wants to. @poblabs what do you think?

**Comment by poblabs** [comment]
I'd love a PR! My time has been stretched thin with a newborn.

**Comment by tomdotorg** [comment]
@poblabs I think my petty annoying error message is more important than your newborn. I'll see what I can do in the next few days.

**Comment by tomdotorg** [comment]
I can't seem to reproduce this, even by ssh'ing into the container and  running the open command manually. Python 3.6.9. I am inclined to forget about this since it does not seem to affect function.

**Comment by hoetzgit** [comment]
After an initial installation, the file does not yet exist. After the file was generated for the first time, the error is fixed. Everything works fine.

**Comment by tomdotorg** [comment]
I'm gonna submit a PR just because I want to have it work on one archive interval instead of two.
