### ISSUE TITLE
Update to Weewx 4.0

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#273]
Hi,

I just update Weewx to the version 4.0 but I've errors to generate files : 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

I'm French so I've this letters : é,à,ù. The problem appear when I put this letters on graphs.conf for the title on HighCharts. The problem doesn't appear when I use the default conf.

**Comment by Drealine** [comment]
`Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 1302, in run
    yAxis_label = name + " (" + unit_label.strip() + ")"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)`

**Comment by poblabs** [comment]
Can you share your yaxis label for this graph? My guess is it has french characters in it, so I need to work on a patch for this.

**Comment by Drealine** [comment]
[graphs.txt](https://github.com/poblabs/weewx-belchertown/files/4497531/graphs.txt)

I've uploaded my graphs.conf init with Weewx 3.9 that work's well.

**Comment by poblabs** [comment]
This is helpful. I will need some time to work on this. Are you using Python 2 or Python 3?

**Comment by Drealine** [comment]
I'm using python2 for the moment.

**Comment by poblabs** [comment]
Try this belchertown.py file. Place it in your bin/user folder and restart weewx. See if it fixes it? If so I'll commit it to the master branch. 


[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4503781/belchertown.zip)

**Comment by Drealine** [comment]
Hi @poblabs 
It work very well. You can push it to master branch.
