### ISSUE TITLE
Cheetahgenerator fail after update from 1.0.1 to 1.1

### ISSUE THREAD

**Issue by jantoni** [poblabs/weewx-belchertown#275]
Hi

I have a problem with Belchertown 1.1 after updated from 1.0.1

This is the log afert Weewx is started

> Apr 26 09:51:42 localhost weewx[1798]: engine: Initializing weewx version 3.9.2
> Apr 26 09:51:42 localhost weewx[1798]: engine: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
> Apr 26 09:51:42 localhost weewx[1798]: engine: Platform Linux-5.4.20-sunxi-armv7l-with-debian-10.3
> Apr 26 09:51:42 localhost weewx[1798]: engine: Locale is 'en_US.UTF-8'
> Apr 26 09:51:42 localhost weewx[1798]: engine: pid file is /var/run/weewx.pid
> Apr 26 09:51:42 localhost weewx[1787]: Starting weewx weather system: weewx.
> Apr 26 09:51:42 localhost weewx[1802]: engine: Using configuration file /etc/weewx/weewx.conf
> Apr 26 09:51:42 localhost weewx[1802]: engine: Loading station type Vantage (weewx.drivers.vantage)
> Apr 26 09:51:43 localhost weewx[1802]: engine: StdConvert target unit is 0x1
> Apr 26 09:51:43 localhost weewx[1802]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
> Apr 26 09:51:43 localhost weewx[1802]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
> Apr 26 09:51:43 localhost weewx[1802]: engine: Archive will use data binding wx_binding
> Apr 26 09:51:43 localhost weewx[1802]: engine: Record generation will be attempted in 'software'
> Apr 26 09:51:43 localhost weewx[1802]: engine: Using archive interval of 300 seconds (software record generation)
> Apr 26 09:51:43 localhost weewx[1802]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
> Apr 26 09:51:43 localhost weewx[1802]: manager: Starting backfill of daily summaries
> Apr 26 09:51:43 localhost weewx[1802]: restx: StationRegistry: Station will be registered.
> Apr 26 09:51:43 localhost weewx[1802]: restx: Wunderground-RF: Data for station IMADRIDR2 will be posted
> Apr 26 09:51:43 localhost weewx[1802]: restx: PWSWeather: Data for station JANTONI will be posted
> Apr 26 09:51:43 localhost weewx[1802]: restx: CWOP: Data for station EA4TN will be posted
> Apr 26 09:51:43 localhost weewx[1802]: restx: WOW: Data for station 454086484 will be posted
> Apr 26 09:51:43 localhost weewx[1802]: restx: AWEKAS: Data will be uploaded for user jantoni
> Apr 26 09:51:43 localhost weewx[1802]: restx: WeatherCloud: service version is 0.11
> Apr 26 09:51:43 localhost weewx[1802]: restx: WeatherCloud: Data will be uploaded for id=f3ae348cde14312d
> Apr 26 09:51:43 localhost weewx[1802]: restx: Windy: version is 0.6
> Apr 26 09:51:43 localhost weewx[1802]: restx: Windy: Data will be uploaded to https://stations.windy.com/pws/update
> Apr 26 09:51:43 localhost weewx[1802]: engine: Starting up weewx version 3.9.2
> Apr 26 09:51:43 localhost weewx[1802]: engine: Clock error is 4.81 seconds (positive is fast)
> Apr 26 09:51:43 localhost weewx[1802]: engine: Starting main packet loop.
> 

And, then in the record generation, it failed with the message 

> Apr 26 09:55:16 localhost weewx[1802]: manager: Added record 2020-04-26 09:55:00 UTC (1587894900) to database 'weewx.sdb'
> Apr 26 09:55:16 localhost weewx[1802]: manager: Added record 2020-04-26 09:55:00 UTC (1587894900) to daily summary in 'weewx.sdb'
> Apr 26 09:55:16 localhost weewx[1802]: restx: WeatherCloud: Published record 2020-04-26 09:55:00 UTC (1587894900)
> Apr 26 09:55:16 localhost weewx[1802]: restx: StationRegistry: Published record 2020-04-26 09:55:00 UTC (1587894900)
> Apr 26 09:55:21 localhost weewx[1802]: cheetahgenerator: Generated 10 files for report SeasonsReport in 5.36 seconds
> Apr 26 09:55:23 localhost weewx[1802]: imagegenerator: Generated 14 images for SeasonsReport in 1.54 seconds
> Apr 26 09:55:23 localhost weewx[1802]: copygenerator: copied 5 files to /var/www/html/weewx/davis1
> Apr 26 09:55:23 localhost weewx[1802]: Belchertown Extension: version 1.1
> Apr 26 09:55:26 localhost weewx[1802]: cheetahgenerator: Generate failed with exception '<type 'exceptions.UnicodeDecodeError'>'
> Apr 26 09:55:26 localhost weewx[1802]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
> Apr 26 09:55:26 localhost weewx[1802]: cheetahgenerator: **** Reason: 'ascii' codec can't decode byte 0xc3 in position 96: ordinal not in range(128)
> Apr 26 09:55:26 localhost weewx[1802]: ****  Traceback (most recent call last):
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
> Apr 26 09:55:26 localhost weewx[1802]: ****      fd.write(str(compiled_template))
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
> Apr 26 09:55:26 localhost weewx[1802]: ****      rc = getattr(self, mainMethName)()
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 104, in respond
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1685, in _handleCheetahInclude
> Apr 26 09:55:26 localhost weewx[1802]: ****      file=file)
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 772, in compile
> Apr 26 09:55:26 localhost weewx[1802]: ****      settings=(compilerSettings or {}))
> Apr 26 09:55:26 localhost weewx[1802]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1708, in __init__
> Apr 26 09:55:26 localhost weewx[1802]: ****      source = unicode(source)
> Apr 26 09:55:26 localhost weewx[1802]: ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 96: ordinal not in range(128)
> Apr 26 09:55:35 localhost weewx[1802]: cheetahgenerator: Generated 10 files for report Belchertown in 11.82 seconds
> Apr 26 09:55:35 localhost weewx[1802]: copygenerator: copied 31 files to /var/www/html/weewx
> Apr 26 09:55:45 localhost weewx[1802]: ftpgenerator: ftp'd 73 files in 10.13 seconds

Everything worked fine with Belhertown 1.0.1

I updated it with the next command:

> sudo wee_extension --install weewx-belchertown-release-1.1.tar.gz

About page is not generated, and Month and year graphics are not generated too

My website is:

https://jantoni.es/meteo

**Comment by jantoni** [comment]
The page

**Comment by jantoni** [comment]
https://jantoni.es/meteo/about/

was the last generated with 1.0.1

**Comment by poblabs** [comment]
You need to add this to the top of about.inc

#encoding utf-8

**Comment by jantoni** [comment]
It works, thanks

`
Apr 26 10:55:16 localhost weewx[1802]: manager: Added record 2020-04-26 10:55:00 UTC (1587898500) to database 'weewx.sdb'
Apr 26 10:55:16 localhost weewx[1802]: manager: Added record 2020-04-26 10:55:00 UTC (1587898500) to daily summary in 'weewx.sdb'
Apr 26 10:55:17 localhost weewx[1802]: restx: WeatherCloud: Published record 2020-04-26 10:55:00 UTC (1587898500)
Apr 26 10:55:18 localhost weewx[1802]: cheetahgenerator: Generated 10 files for report SeasonsReport in 2.38 seconds
Apr 26 10:55:20 localhost weewx[1802]: imagegenerator: Generated 14 images for SeasonsReport in 1.52 seconds
Apr 26 10:55:20 localhost weewx[1802]: copygenerator: copied 0 files to /var/www/html/weewx/davis1
Apr 26 10:55:24 localhost weewx[1802]: cheetahgenerator: Generated 11 files for report Belchertown in 4.54 seconds
Apr 26 10:55:24 localhost weewx[1802]: copygenerator: copied 2 files to /var/www/html/weewx
Apr 26 10:55:31 localhost weewx[1802]: ftpgenerator: ftp'd 40 files in 6.07 seconds`
