### ISSUE TITLE
Column Graph + Stacking Normal not working

### ISSUE THREAD

**Issue by ChrisM510** [poblabs/weewx-belchertown#276]
Hi,

I have an issue where stacking is not working for my lightning data.  If I remove "stacking = normal" I can at least get side-by-side columns, but with the stacking active, one column is behind the other:

    [[Lightning]]
        title = Lightning
        type = column
        [[[Lightning_Strikes]]]
            name = Lightning
            yAxis = 0
            yAxis_tickInterval = 1
            yAxis_label = "Strike Count"
            stacking = normal
        [[[strike_distance]]]
            name = Average Distance
            yAxis = 1
            yAxis_label = "Distance (miles)"
            stacking = normal

Image 1: https://ibb.co/hmJJdtQ  (Hover over Lightning heading)
Image 2: https://ibb.co/bQmyYXD  (Hover over Average Distance heading)
Image 3: https://ibb.co/nRsCB3y  (No mouse hover)

Any ideas?  Is something wrong, or am I doing something incorrect?

**Comment by poblabs** [comment]
Looks like the average distance is "on top" of the strike count. Try setting `zIndex = 1` to the strikes section. This will pull it on top of the distance. Or you can flip-flop the two observations to change the order.
