### ISSUE TITLE
Value format highcharts - Year Interval

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#277]
Hi,

Values show in highchart with metric value are like this : 

![image](https://user-images.githubusercontent.com/61891683/80955207-2e3abe00-8dff-11ea-8818-6fdf26f8647b.png)

00,00 for example. It is possible to include a format value in your future release like 00,0 ?

**Comment by poblabs** [comment]
Format values are already there. What do you want it to say?

**Comment by Drealine** [comment]
In system metric, wind gust is in this format 00,0 km/h. In graphs.conf I put this :+1: 

`[[chart1]]
        title = "Moyenne pour l'année 2020 (Vent Moy et Rafale)"
        time_length = year
        [[[windSpeed]]]
            name = "Vent Moy"
            type = area
            aggregate_type = avg
            zIndex = 0
            color = "#FFE900"
            [[[[numberFormat]]]]
                decimalPoint = "."
                thousandsSep = ""
                decimals = 1`

But still to 00,00 km/h.
