### ISSUE TITLE
Data won't load below hook

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#28]
Created an index_hook_after_station_info.inc file and no other page information would load below the hook, not sure if this also applies to 'after_snapshot', will check

**Comment by poblabs** [comment]
Within your `index_hook_after_station_info.inc` is it possible you have a closing tag missing? Like a `</div>`?

**Comment by 41south** [comment]
Ah could be, this is the code in it

<iframe id="widget-iframe" width="300px" height="167px"
 src="https://services.metservice.com/weather-widget/widget?params=white|small|portrait|days-3|classic&loc=lyall-bay&type=urban" allowtransparency="true" style="border:none" />

**Comment by poblabs** [comment]
Close with an `</iframe>`, restart weewx and run wee_reports or wait for an archive interval to see

**Comment by 41south** [comment]
Bingo, sorted, thanks. That was a cut and paste from a widget generator with a problem in it :)

Closing
