### ISSUE TITLE
Aeris Weather icon mapping in 1.2b3

### ISSUE THREAD

**Issue by hoetzgit** [poblabs/weewx-belchertown#280]
Hi @poblabs, please change the icon mapping in these two files:

**belchertown.js.tmpl**

from:
	"sunny": "partly-cloudy-day",
	"sunnyn": "partly-cloudy-night",
to:
	"sunny": "clear-day",
	"sunnyn": "clear-night",

**belchertown.py**

from:
	"sunny": "partly-cloudy-day",
	"sunnyn": "partly-cloudy-night",
to:
	"sunny": "clear-day",
	"sunnyn": "clear-night",

Thank you.

**Comment by poblabs** [comment]
All set, thanks for the help!
