### ISSUE TITLE
Barometer switches units when MQTT data arrive

### ISSUE THREAD

**Issue by uajqq** [poblabs/weewx-belchertown#281]
I’ve been using the skin for a while on weewx 4 beta, now (smoothly) updated to weewx 4.0.0. On both versions of weewx, I’ve been having a persistent issue where the pressure initially shows as millibars, but as soon as MQTT data are received, it switches to displaying the pressure in inHg (though the label still says mbar). Graphs are still showing correct mbar unit. mbar unit is set in both weewx.conf and skin.conf. Is this a bug or do I have a configuration option wrong?

I’m using [ambientweatherapi](https://github.com/themoosman/weewx-ambientweatherapi-json) to generate the LOOP packets, but weewx should be interpreting those values based on my preferred units, right? I could convert the units at the level of the driver I suppose, but that seems unnecessarily hack-y.

Thank you!

**Comment by poblabs** [comment]
Not a bug, you need to configure your MQTT plugin to send the units you're expecting. Not a skin problem, but the MQTT plugin problem. See this issue for tips: https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099
