### ISSUE TITLE
Unicode decode error in about.inc

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#282]
Hi Pat,

I think there's the same issue than #273 on about.inc. When I put a é à è  in a worrd on it, here's what kind of error i have.

```
May 11 15:40:30 srvmeteo weewx[5864] ERROR weewx.cheetahgenerator: Generate failed with exception '<type 'exceptions.UnicodeDe
codeError'>'
May 11 15:40:30 srvmeteo weewx[5864] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/i
ndex.html.tmpl
May 11 15:40:30 srvmeteo weewx[5864] ERROR weewx.cheetahgenerator: **** Reason: 'ascii' codec can't decode byte 0xc3 in positi
on 4105: ordinal not in range(128)
```

When I remove any é à è in about.inc text, all is ok.

Thanks for all.

Olivier.

**Comment by poblabs** [comment]
Add this to the top of about.inc

`#encoding UTF-8`

**Comment by olpayras** [comment]
Wow so quick reply, Thanks I got this line before but probably when i changed my hardware, i forgot to put it again.

Thanks again.
