### ISSUE TITLE
Add custom HTML below current temperature High/Low?

### ISSUE THREAD

**Issue by bburton** [poblabs/weewx-belchertown#283]
Would like the ability to add extra HTML after the temperature observation cell below the High/Low values without having to patch index.html.tmpl with each skin release. For example:
```html
<div class="stn-high-low"><!-- water temp -->
      <div class="feelslike">Water: $current.extraTemp1</div>
</div>
```

I tried adding this to skin.conf:
```html
temperature_extra_html = '<div class="stn-high-low"><div class="feelslike">Water: $current.extraTemp1</div></div>'
```
Then, in index.html.tmpl about line 208 (as of 1.2b3):
```html
#if $Extras.has_key('temperature_extra_html') and $Extras.temperature_extra_html != ''
$Extras.temperature_extra_html
#end if
```
However, this doesn't work as Cheetah doesn't evaluate the ```$current.extraTemp1``` already in a string.

Any thoughts about how to support a generic way to add custom HTML below the temperature High/Low values?

Thanks for consideration of this feature.
-Bill

**Comment by poblabs** [comment]
Adding things like this has come up quite a bit and it brings me back to my Wordpress development days where everything had a "hook". A hook is basically an anchor which you can "hook" custom items to.

I tried to replicate that with some of the hooks already in the skin. Perhaps I need to add more hooks. Let me think about this one

**Comment by poblabs** [comment]
Because hooks are dynamic, it makes it hard for me to guess every configuration everyone will have. So the the problem is that hooks aren't updated automatically with MQTT. Perhaps there's a way to help with triggering this but I haven't thought of a way yet.

**Comment by poblabs** [comment]
Perhaps hook files can be pure HTML and can live in a `/hooks` subfolder. Then on weewx archive interval, JS can grab the content of that HTML and inject it into the `div` containing the hook. That would update the information. 

This could be doable. Limitation here would be that the hooks aren't updated on LOOP packet, only ARCHIVE REC packets.

**Comment by bburton** [comment]
I wasn't considering live updates as I don't (yet) use MQTT. In any case Archive REC is fine. The only data that I can think that would need LOOP packets is wind speed and direction and that is already covered.

In thinking about this further, could this work in a similar manner to the `$Extras.station_observations` definition except that it would be for extra temperatures? Maybe `$Extras.extra_temperatures`. Previously I used the station_observations adding `extraTemp1` and it worked just fine. However, having extra temperatures below the outdoor temperature makes more sense the way the grid is organized.

**Comment by poblabs** [comment]
It could, but I get side-requests a lot for adding custom info to every part of the page. So my thought is to add a section at the bottom of every section that allows you to put in custom html by way of a hook file.

**Comment by ArendPWS** [comment]
Still working on this. Have it up and running here (with MQTT support), but I guess it isn't something for the average user to implement it the way I did. One has to know how to do some coding. I solved the issues in my previous pull request  #357. All my code now goes into "index_hook_after_station_info.inc" and don't use the  option "reload_images_hook_asi = -1" in skin.conf. The code module just gets included and does its job. The extra label for the main temperature reading is now also added dynamically including CSS. Discovering how to do this, opened up a lot of new possibilities on changing existing elements on the homepage.

Putting code in all four existing hooks at the same time (with MQTT support) might be another challenge.

The problem I am facing now is how to create a custom/extended weewx_data.json.tmpl. I thought maybe the same idea could be implemented as is currently used for graphs.conf with graphs.conf.example being the default. That solution wouldn't require any additional coding in my extension, but it would require a change in Belchertown code.
For the moment I just make sure I have a backup of my modified weewx_data.json.tmpl and copy it back after a Belchertown update.

**Comment by ThePeePs** [comment]
Just a thought, as I've been setting up, and customising a new index page, if the weewx_data.json file could have all the current data in it without any formatting or html (ie: almanac) people would be able to use any and all data that is being collected by weewx.  If I get some time in the coming weeks I'll make a PR for the weewx_data.json.tmpl file

**Comment by poblabs** [comment]
@ThePeePs Interesting idea. Looking forward to a PR. You'd also have to update all elements which rely on the formatting, too.
