### ISSUE TITLE
unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator' with 1.2b3

### ISSUE THREAD

**Issue by martenhinrichs** [poblabs/weewx-belchertown#284]
Following Error occur in running wee_reports . I dont have anything changed.

May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****  list indices must be integers or slices, not str
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      obj.start()
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      self.run()
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      default_binding)
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 862, in get_extension_list
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****      current_obs_summary = aeris_coded_weather( data["current"][0]["response"]["ob"]["weatherPrimaryCoded"] )
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****  TypeError: list indices must be integers or slices, not str
May 13 11:50:19 wetter weewx[5082] ERROR weewx.reportengine:         ****  Generator terminated
May 13 11:50:19 wetter weewx[5082] INFO weewx.reportengine: Copied 2 files to /var/www/html

**Comment by poblabs** [comment]
Are you using aeris forecasts?

**Comment by martenhinrichs** [comment]
Yes

**Comment by poblabs** [comment]
Please provide a copy of your forecast.json as an attachment and your
website

**Comment by martenhinrichs** [comment]
Website address are https://gw.martenhinrichs.de

**Comment by martenhinrichs** [comment]
[forecast.zip](https://github.com/poblabs/weewx-belchertown/files/4621429/forecast.zip)
Her the forecast.json as zip

**Comment by martenhinrichs** [comment]
ok i see my location does not more exist......
https://wx.aerisweather.com/local/de/rostock/forecast/YYYY/MM/DD
thats currious

**Comment by martenhinrichs** [comment]
ok solved by myself. seems to bee that aerisweather had no forecast data for my location. Now my Location Forecast Data again visible. I also had to remove the forecast.json file.
