### ISSUE TITLE
Feature Enhancement: Average and Record High/Low Temperature

### ISSUE THREAD

**Issue by tim273** [poblabs/weewx-belchertown#285]
I was wondering if it would be possible to add the average and record high/low temperature for a given day, along with some other daily records.  Maybe similar to the Almanac pop up?

**Comment by poblabs** [comment]
Do you mean in a graph? Or on the records page?

**Comment by tim273** [comment]
I was thinking more on the lines of the climatological average, like when you watch the weather on TV the say the "normal" or "average" temperature for the day is 60 (for example) but it was actually 72.  It would be data you'd have to get from the NWS or some other outside source.

**Comment by poblabs** [comment]
Currently I'm only getting this data from DarkSky (which is going away) and from Aeris Weather (in the development version). You're right, they'd have to provide that data - which neither does at this point. You could reach out to them to see if it's possible though! If they add it, then I can also add it to the skin
