### ISSUE TITLE
Feature Request: Tides?

### ISSUE THREAD

**Issue by blulite** [poblabs/weewx-belchertown#286]
Any thoughts about adding tide information?      Think about that weather forecast on TV.    Those of us on the coast get a tide forecast as part of the weather forecast.

**Comment by poblabs** [comment]
Hmm interesting. This could probably be done if there's a weewx extension that supports it, then you can just add the extension output to the skin. This is probably better asked on the weewx forums!

**Comment by trobnc** [comment]
I have xtides as part of the forecast extension. Wasn't sure how to get information from the forecast extension into Belchertown? This is from the html.tmpl file for tides:

```
#if $varExists('forecast')

<h1>Tides</h1>
<p>
#set $tides = $forecast.xtides
#if len($tides) > 0
  #for $tide in $tides
$tide.event_ts $tide.hilo $tide.offset<br/>
  #end for
#else
Tide forecast is not available.
#end if
</p>

#else

<p>The forecast search list extension is not installed.</p>

#end if
```
