### ISSUE TITLE
Bad displaying NOAA Reports

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#289]
Hi Pat,

Hope you are well, I don't know if it has been reported, or perhaps have a bad configuration, but since i update to weewx 4.0 and belchertown 1.1 also tried last dev version 1.2b3, noaa is displayed like this :

![Capture](https://user-images.githubusercontent.com/49792600/82909466-9e091800-9f69-11ea-82c2-1d1c5ad54542.PNG)

I dont understand what happened ?

Have you an idea ?

Here's my website : https://meteo.payrastre.fr 

Have a nice day.

Olivier.

**Comment by poblabs** [comment]
No, not sure. Any changes to your Apache? Does the NOAA folder have the correct permissions?

You could try to delete everything in your public_html and let weewx recreate everything.

**Comment by poblabs** [comment]
This actually may be a problem with weewx itself. See this thread and a potential fix in 4.1.1 https://groups.google.com/forum/#!topic/weewx-user/uPQhZ5GmmMA

**Comment by olpayras** [comment]
Good news. Thanks a lot for this information. I'll check that on 4.1.1 when available.

I close this issue,

**Comment by olpayras** [comment]
I think I've find what was the trouble. When I updated to 4.0.0 I didn't change the source update so my RPI was using python2 version. I changed that, and re-install all the software and there's no more trouble.

**Comment by f4gqk** [comment]
Hello,

Even though you're French like me. I'll speak to you in English.

how did you manage to change the python version? Where do you give him the information ???

**Comment by olpayras** [comment]
73 f4gqk,

You should change your apt repo from your linux distribution.

If you use debian or raspbian on a RPI, you should apply this : http://weewx.com/docs/debian.htm

Olivier.

**Comment by f4gqk** [comment]
I updated the repo.

Reinstall Weewx and it works.

Thanks olpayras

Olivier, I have often taken an example from your site:
https://meteo.payrastre.fr


Your "reports" page is not bad.

Where is this HTML page generated ???? To customize it ?????

Thanks

Sebastien

**Comment by f4gqk** [comment]
hello olivier,

I am interested in the style of your paintings on the "reports" page.

With the different values.

This "reports" page is generated by which file on weewx ???

Then I put the variable that interests me ....

style and example:

$month.outTemp.max...............

my email address is my username @ my username .fr if you want to exchange.

Thanks

**Comment by olpayras** [comment]
Hi Sebastien,

Sorry for the delay. I Think your question can interest some other people. So, you can find here my repo for History Feature. I updated it last 1.2 revision today. I didn't tried v1.2 cause my test environnement is broken. You should try it but not on production environnement.
