### ISSUE TITLE
Sunradiation

### ISSUE THREAD

**Issue by DarthWeber** [poblabs/weewx-belchertown#290]
Hi, that skin looks very great - thanks so far !

Since i am totally new to weewx - i setup my davis vantage pro2 plus with radiation, ET and uv - i am overwhelmed. It was not a big deal to install weewx and also this great skin works out-of-the-box.

My question: I managed to include ET and radiation in the box left to the radar with the station_observations tag in the skin.conf - but what do i need to include that nice wind rose and radiation graph with actual and max solar radiation ? Could someony explain to to a newbie with experencied STRG-C and STRG-V knowledge ?

many thanks,
tom

**Comment by poblabs** [comment]
Check out the [graphs wiki](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation), it has the specific examples you're looking for. 

There's a lot there, so digest it slowly - there is no rush. 

Basically to add a wind rose you'll edit your graphs.conf to add the [windRose] observation. Same with the ET and radiation graphs.
