### ISSUE TITLE
webpage went down.

### ISSUE THREAD

**Issue by finna82** [poblabs/weewx-belchertown#291]
Hello pat, everything have worked perfectly since September, but today something happened. I made a fresh install off weewx 3.9.2.1 and used my backup files.
then i got this:

```
May 31 20:14:18 raspberrypi weewx[11296]: imagegenerator: Generated 14 images for SeasonsReport in 0.81 seconds
May 31 20:14:18 raspberrypi weewx[11296]: copygenerator: copied 0 files to /var/www/html/weewx
May 31 20:14:18 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:18 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/json/weewx_data.json.tmpl
May 31 20:14:18 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:18 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:18 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:18 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:18 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:18 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:18 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_json_weewx_data_json_tmpl.py", line 1217, in respond
May 31 20:14:18 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: restx: Wunderground-RF: Published record 2020-05-31 20:14:18 CEST (1590948858)
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 93, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
May 31 20:14:19 raspberrypi weewx[11296]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 100, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/graphs/index.html.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_graphs_index_html_tmpl.py", line 114, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
May 31 20:14:19 raspberrypi weewx[11296]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 100, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/reports/index.html.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_reports_index_html_tmpl.py", line 135, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
May 31 20:14:19 raspberrypi weewx[11296]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 100, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/records/index.html.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_records_index_html_tmpl.py", line 1104, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
May 31 20:14:19 raspberrypi weewx[11296]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 100, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/index.html.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_index_html_tmpl.py", line 665, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
May 31 20:14:19 raspberrypi weewx[11296]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 100, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/js/belchertown.js.tmpl
May 31 20:14:19 raspberrypi weewx[11296]: cheetahgenerator: **** Reason: a float is required
May 31 20:14:19 raspberrypi weewx[11296]: ****  Traceback (most recent call last):
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May 31 20:14:19 raspberrypi weewx[11296]: ****      fd.write(str(compiled_template))
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May 31 20:14:19 raspberrypi weewx[11296]: ****      rc = getattr(self, mainMethName)()
May 31 20:14:19 raspberrypi weewx[11296]: ****    File "_etc_weewx_skins_Belchertown_js_belchertown_js_tmpl.py", line 146, in respond
May 31 20:14:19 raspberrypi weewx[11296]: ****  TypeError: a float is required
May 31 20:14:20 raspberrypi weewx[11296]: cheetahgenerator: Generated 4 files for report Belchertown in 1.38 seconds
May 31 20:14:20 raspberrypi weewx[11296]: copygenerator: copied 2 files to /var/www/html/weewx
May 31 20:14:20 raspberrypi weewx[11296]: restx: MQTT: Published record 2020-05-31 20:14:21 CEST (1590948861)
```

**Comment by poblabs** [comment]
What version of the skin are you running? You may have to upgrade to the latest

**Comment by finna82** [comment]
i`am running 1.01 but have tried and updated again now to 1.1 to see, but it is the same error.

**Comment by poblabs** [comment]
Your errors aren't giving me much to go on right now other than "a float is required". Did you have a database corruption or something? You can try to attach your database here and I can try and replicate this when time allows

I assume this is valid:

Python 2
weewx 3.9.1
Belchertown 1.1

**Comment by finna82** [comment]
yes, something happened today. first I had problem with a extension. [https://groups.google.com/forum/#!topic/weewx-user/RmsNuIDkeGw](url)
deleted the extension I had problem with. and got this problem.
[weewx.sdb.zip](https://github.com/poblabs/weewx-belchertown/files/4708213/weewx.sdb.zip)

**Comment by poblabs** [comment]
I'm at a bit of a loss. I just installed a virtual machine with Python 2, weewx 3.9.2 and Belchertown 1.1. I then ran wee_reports and it compiled fine without issue.

Can you share your graphs.conf? Your full belchertown config? Everything? Make sure to remove any passwords or secret forecast keys.


![image](https://user-images.githubusercontent.com/3484775/83367020-642c7d00-a380-11ea-85ed-44c5a128aefd.png)

**Comment by poblabs** [comment]
I forgot to mention that the graphs attached in my previous reply are from your attached database

**Comment by finna82** [comment]
hello and good morning. Here are the other files
[usr.zip](https://github.com/poblabs/weewx-belchertown/files/4710513/usr.zip)
Yesterday i installed everything again,weewx .4 and belchertown 1.1. With a new database,  then everything worked. but if i put in the old database i got the error again. so maybe its something wrong with the data :(

**Comment by poblabs** [comment]
Take a backup of your database and save it somewhere, then run these commands on your database. Maybe there is a problem with the daily tables

`wee_database --drop-daily`

Then

`wee_database --rebuild`

Then restart weewx and see if the skin will work?

**Comment by finna82** [comment]
did not work :( got this:
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****  argument of type 'NoneType' is not iterable
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      obj.start()
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      self.run()
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      default_binding)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 836, in get_extension_list
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      obs_output = getattr(current, obs)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/tags.py", line 457, in __getattr__
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 71, in get_scalar
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      return xtype.get_scalar(obs_type, record, db_manager)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/wxservices.py", line 252, in get_scalar
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      return getattr(self, method_name)(obs_type, record, db_manager)
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/wxservices.py", line 274, in calc_cloudbase
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****      if 'outTemp' not in data or 'outHumidity' not in data:
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****  TypeError: argument of type 'NoneType' is not iterable
Jun  1 19:47:21 raspberrypi weewx[10404] ERROR weewx.reportengine:         ****  Generator terminated
Jun  1 19:47:21 raspberrypi weewx[10404] INFO weewx.reportengine: Copied 31 files to /var/www/html/weewx/

**Comment by poblabs** [comment]
Ok this looks better. Take cloudbase out of your skin.conf options

**Comment by finna82** [comment]
got this:
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****  argument of type 'NoneType' is not iterable
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      obj.start()
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      self.run()
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      default_binding)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 836, in get_extension_list
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      obs_output = getattr(current, obs)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/tags.py", line 457, in __getattr__
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 71, in get_scalar
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      return xtype.get_scalar(obs_type, record, db_manager)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/wxservices.py", line 252, in get_scalar
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      return getattr(self, method_name)(obs_type, record, db_manager)
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/wxservices.py", line 274, in calc_cloudbase
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****      if 'outTemp' not in data or 'outHumidity' not in data:
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****  TypeError: argument of type 'NoneType' is not iterable
Jun  1 21:11:19 raspberrypi weewx[14169] ERROR weewx.reportengine:         ****  Generator terminated
Jun  1 21:11:19 raspberrypi weewx[14169] INFO weewx.reportengine: Copied 31 files to /var/www/html/weewx/

**Comment by poblabs** [comment]
Still giving an error on cloudbase. Did you also remove it from your weewx.conf [Belchertown] section?

**Comment by finna82** [comment]
¨Now i removed it, and it worked! :D thank you very much. whats the problem with cloudbase?

**Comment by poblabs** [comment]
Not sure but based on the error message above, I think somewhere in your database you have a NULL value for outTemp and/or outHumidity?

**Comment by finna82** [comment]
I would not know. Guess something happend when this crt extension crashed everything in the first place, because i live north of the artic circle. But thank you very much for getting it to work again.

**Comment by poblabs** [comment]
You're welcome, and thanks for the coffee!

**Comment by poblabs** [comment]
Paste your latest copy of your database, I'll take a 2nd look at it to see if there's any NULLs that would affect cloudbase.

**Comment by finna82** [comment]
the least i can do for spending your time. 
[weewx.sdb.zip](https://github.com/poblabs/weewx-belchertown/files/4713189/weewx.sdb.zip)

**Comment by poblabs** [comment]
Your database has outTemp and outHumidity correctly. So I'm confused too. If you stop weewx, and [run weewxd directly](http://www.weewx.com/docs/usersguide.htm#running), let it run until you see a REC packet. Then stop it and check your logs and paste the last few LOOP and REC packets here. I wonder that'll help figure out why cloudbase isn't working for you?

**Comment by finna82** [comment]
REC:    2020-06-01 23:04:00 CEST (1591045440) altimeter: 30.196587590200732, appTemp: 50.959119733804286, barometer: 30.193, beaufort: 2, cloudbase: 1621.9800705394098, consBatteryVoltage: 3.92, dateTime: 1591045440, dayET: 0.0, dayRain: 0.0, dewpoint: 48.3156876896266, ET: 0.0, extraAlarm1: 0.0, extraAlarm2: 0.0, extraAlarm3: 0.0, extraAlarm4: 0.0, extraAlarm5: 0.0, extraAlarm6: 0.0, extraAlarm7: 0.0, extraAlarm8: 0.0, forecastIcon: 6.0, forecastRule: 44, heatindex: 54.7, highOutTemp: 54.7, humidex: 56.24479761512614, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0.0, inTemp: 78.7, interval: 1, leafWet4: 0.0, lowOutTemp: 54.7, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 79.0, outsideAlarm1: 0.0, outsideAlarm2: 0.0, outTemp: 54.7, pressure: 30.008068635663413, rain: 0.0, rainAlarm: 0.0, rainRate: 0.0, rxCheckPercent: 100.0, soilLeafAlarm1: 0.0, soilLeafAlarm2: 0.0, soilLeafAlarm3: 0.0, soilLeafAlarm4: 0.0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.7, windDir: 292.5, windGust: 9.0, windGustDir: 270.0, windrun: 0.1, windSpeed: 6.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796
LOOP:   2020-06-01 23:04:17 CEST (1591045457) altimeter: 30.196597712282898, appTemp: 51.608954983599276, barometer: 30.193, beaufort: 2, cloudbase: 1545.5912203423898, consBatteryVoltage: 3.92, dateTime: 1591045457, dayET: 0.0, dayRain: 0.0, dewpoint: 48.65179863049349, extraAlarm1: 0, extraAlarm2: 0, extraAlarm3: 0, extraAlarm4: 0, extraAlarm5: 0, extraAlarm6: 0, extraAlarm7: 0, extraAlarm8: 0, forecastIcon: 6, forecastRule: 44, heatindex: 54.7, humidex: 56.39226369697063, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0, inTemp: 78.7, leafWet4: 0.0, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 80.0, outsideAlarm1: 0, outsideAlarm2: 0, outTemp: 54.7, pressure: 30.008078706108044, rain: 0.0, rainAlarm: 0, rainRate: 0.0, soilLeafAlarm1: 0, soilLeafAlarm2: 0, soilLeafAlarm3: 0, soilLeafAlarm4: 0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.7, windDir: 288.0, windGust: 7.0, windGustDir: 273.0, windSpeed: 5.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796

REC:    2020-06-01 23:06:00 CEST (1591045560) altimeter: 30.196597712282898, appTemp: 50.48241698359927, barometer: 30.193, beaufort: 2, cloudbase: 1545.5912203423898, consBatteryVoltage: 3.92, dateTime: 1591045560, dayET: 0.0, dayRain: 0.0, dewpoint: 48.65179863049349, ET: 0.0, extraAlarm1: 0.0, extraAlarm2: 0.0, extraAlarm3: 0.0, extraAlarm4: 0.0, extraAlarm5: 0.0, extraAlarm6: 0.0, extraAlarm7: 0.0, extraAlarm8: 0.0, forecastIcon: 6.0, forecastRule: 44, heatindex: 54.7, highOutTemp: 54.8, humidex: 56.39226369697063, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0.0, inTemp: 78.7, interval: 1, leafWet4: 0.0, lowOutTemp: 54.7, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 80.0, outsideAlarm1: 0.0, outsideAlarm2: 0.0, outTemp: 54.7, pressure: 30.008078706108044, rain: 0.0, rainAlarm: 0.0, rainRate: 0.0, rxCheckPercent: 98.22916666666667, soilLeafAlarm1: 0.0, soilLeafAlarm2: 0.0, soilLeafAlarm3: 0.0, soilLeafAlarm4: 0.0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.7, windDir: 292.5, windGust: 11.0, windGustDir: 292.5, windrun: 0.11666666666666667, windSpeed: 7.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796
LOOP:   2020-06-01 23:06:17 CEST (1591045577) altimeter: 30.194599769049507, appTemp: 52.172223983599274, barometer: 30.191, beaufort: 1, cloudbase: 1545.5912203423898, consBatteryVoltage: 3.92, dateTime: 1591045577, dayET: 0.0, dayRain: 0.0, dewpoint: 48.65179863049349, extraAlarm1: 0, extraAlarm2: 0, extraAlarm3: 0, extraAlarm4: 0, extraAlarm5: 0, extraAlarm6: 0, extraAlarm7: 0, extraAlarm8: 0, forecastIcon: 6, forecastRule: 44, heatindex: 54.7, humidex: 56.39226369697063, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0, inTemp: 78.7, leafWet4: 0.0, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 80.0, outsideAlarm1: 0, outsideAlarm2: 0, outTemp: 54.7, pressure: 30.006090955390583, rain: 0.0, rainAlarm: 0, rainRate: 0.0, soilLeafAlarm1: 0, soilLeafAlarm2: 0, soilLeafAlarm3: 0, soilLeafAlarm4: 0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.7, windDir: 293.0, windGust: 6.0, windGustDir: 282.0, windSpeed: 4.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796
LOOP:   2020-06-01 23:06:18 CEST (1591045578) altimeter: 30.194602720146285, appTemp: 51.17093366066432, barometer: 30.191, beaufort: 2, cloudbase: 1546.1973609741906, consBatteryVoltage: 3.92, dateTime: 1591045578, dayET: 0.0, dayRain: 0.0, dewpoint: 48.74913161171356, extraAlarm1: 0, extraAlarm2: 0, extraAlarm3: 0, extraAlarm4: 0, extraAlarm5: 0, extraAlarm6: 0, extraAlarm7: 0, extraAlarm8: 0, forecastIcon: 6, forecastRule: 44, heatindex: 54.8, humidex: 56.53528170939137, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0, inTemp: 78.7, leafWet4: 0.0, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 80.0, outsideAlarm1: 0, outsideAlarm2: 0, outTemp: 54.8, pressure: 30.00609389143223, rain: 0.0, rainAlarm: 0, rainRate: 0.0, soilLeafAlarm1: 0, soilLeafAlarm2: 0, soilLeafAlarm3: 0, soilLeafAlarm4: 0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.8, windDir: 275.0, windGust: 6.0, windGustDir: 282.0, windSpeed: 6.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796
LOOP:   2020-06-01 23:06:20 CEST (1591045580) altimeter: 30.194602720146285, appTemp: 49.481126660664316, barometer: 30.191, beaufort: 3, cloudbase: 1546.1973609741906, consBatteryVoltage: 3.92, dateTime: 1591045580, dayET: 0.0, dayRain: 0.0, dewpoint: 48.74913161171356, extraAlarm1: 0, extraAlarm2: 0, extraAlarm3: 0, extraAlarm4: 0, extraAlarm5: 0, extraAlarm6: 0, extraAlarm7: 0, extraAlarm8: 0, forecastIcon: 6, forecastRule: 44, heatindex: 54.8, humidex: 56.53528170939137, inDewpoint: 52.997535428189664, inHumidity: 41.0, insideAlarm: 0, inTemp: 78.7, leafWet4: 0.0, maxSolarRad: None, monthET: 0.0, monthRain: 0.0, outHumidity: 80.0, outsideAlarm1: 0, outsideAlarm2: 0, outTemp: 54.8, pressure: 30.00609389143223, rain: 0.0, rainAlarm: 0, rainRate: 0.0, soilLeafAlarm1: 0, soilLeafAlarm2: 0, soilLeafAlarm3: 0, soilLeafAlarm4: 0, stormRain: 0.0, sunrise: 1593323760.0, sunset: 1593323760.0, txBatteryStatus: 0, usUnits: 1, windchill: 54.8, windDir: 275.0, windGust: 9.0, windGustDir: 275.0, windSpeed: 9.0, windSpeed10: 6.0, yearET: 0.0, yearRain: 25.4173226796

**Comment by poblabs** [comment]
Hmm - Ok, that looks normal like it should. Try adding `cloudbase` back to your station_observatiosn again and restart weewx and see if you get that error again?

**Comment by finna82** [comment]
hehe, then it went down again with the same error. well its working now, so don`t think about it :)
