### ISSUE TITLE
graph precipitation

### ISSUE THREAD

**Issue by Chema76** [poblabs/weewx-belchertown#293]
Hello, 
I recently installed Belchertown 1.1 and WeeWX 4.1.1, but for some reason my precipitation graph looks like the image I attached. As you can see today that I am writing is June 4 but the graph extends several days beyond.
The code in graphs.conf is this:

```
[week]
    title = " Últimos siete días"
    show_button = true
    button_text = "Semana"
    time_length = week
    tooltip_date_format = "LLLL"
    aggregate_type = max
    aggregate_interval = 3600 # 1 hour
    gapsize = 3600000 # 1 hour in milliseconds
  
       [[chart1]]
        title = Precipitación
           [[[rainTotal]]]
               name  = Precipitaci  n total
               type = column
               color = "#268bd2"
            [[[rainRate]]]
                yAxis = 1
                type = column
```
               
![Captura](https://user-images.githubusercontent.com/45130728/83748784-fffd0800-a662-11ea-9225-1fe64ccd4cc5.PNG)

**Comment by poblabs** [comment]
This is because you have defined `    time_length = week` so it's graphing the whole week.
