### ISSUE TITLE
Social sharing documentation

### ISSUE THREAD

**Issue by tbluegator** [poblabs/weewx-belchertown#294]
Hey Pat,

Thank you so much for this beautiful skin - it's an amazing improvement over the WeeWX default, I've really enjoyed getting it set-up.

This is just a note on potentially improving the documentation for Social Options:

That section of the documentation only mentions facebook_enabled, twitter_enabled, twitter_owner, and twitter_hashtags and does not directly address that those go in different sections of the config file. After understanding a little bit more about the structure of the skin, I found the additional options for social_share_html and twitter_text in the skin.conf file and was able to copy those over and get everything working. Just thought it might be helpful to mention the other settings in the "Social Options" section and the need to put some in 'Extras' and some in 'Labels'

Thanks again for the great skin - sent some coffee your way!
Trey

**Comment by poblabs** [comment]
Appreciate that and the suggestions! I'll work on getting these updated

**Comment by poblabs** [comment]
The readme has been updated in development and will get rolled into the master when the release is published. Thanks again!
