### ISSUE TITLE
Pi Extension is showing outdated Values when Wheaterstation isnt working anymore

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#295]
Hi, when my weatherstation isnt working anymore but Weewx and MQTT is still up, then the "Browser Version" of Belchertown Extension is showing NA but the Pi Version is showing the last received value.

I suggest that Pi should also show NA instead an old value

**Comment by poblabs** [comment]
I've made a bunch of updates to the Pi page in the development branch in recent days. I think all the MQTT items have initial values now and will show NA if needed - just like the main page. 

Can you upgrade and see if this is still an issue for you?

**Comment by ebnerjoh** [comment]
Hi,

Yes, I will test and let you know.

Br,
Johannes

Am Di., 23. Juni 2020 um 20:14 Uhr schrieb poblabs <notifications@github.com

**Comment by ebnerjoh** [comment]
Hi,

I tested now and I had a case where the Weatherstation was not sending
anything to Weewx anymore. On the Webportal I am seeing NA, but on the PI
it is showing the old value and only NA when I restart the PI.

Br,
Johannes

Am Di., 23. Juni 2020 um 21:32 Uhr schrieb Ebner, Johannes <
johannes@familie-ebner.at>:

**Comment by poblabs** [comment]
Which field showed NA?

**Comment by ebnerjoh** [comment]
at least temperature.

but maybe also wind speed and direction.

Von meinem iPhone gesendet
