### ISSUE TITLE
Darksky no longer available

### ISSUE THREAD

**Issue by tfede37** [poblabs/weewx-belchertown#296]
Darksky is no longer accepting subscriptions so no way to activate forecasts.
DS website is stating that "they will support till 2021 end".
Does your skin support other forecast data suppliers ?

FT

**Comment by poblabs** [comment]
Yes, the [development version of the skin](https://github.com/poblabs/weewx-belchertown/tree/development) uses Aeris Weather which requires you to send data to pwsweather.com. The readme in the development should have everything you need to get started.
