### ISSUE TITLE
Aggregation period issues

### ISSUE THREAD

**Issue by Zimerhonzl** [poblabs/weewx-belchertown#297]
Upgraded to the newest version of Belchertown from the original release.  Using a custom include with yesterday's data points.  While $yesterday.dateTime.format("%B %d, %Y") shows the correct information, none of the weather information does so (i.e.: $yesterday.outTemp.max); instead showing the information for today.  I also tried $day($days_ago=2).outTemp.max and received the same information.  Worked in original extension.

**Comment by Zimerhonzl** [comment]
It is in index.html.tmpl.  I've pasted the third row below, the code is the
bottom section (in place of earthquake)

              
                <div class="row eq-stats-row">
                    #if $Extras.has_key('earthquake_enabled') and
$Extras.earthquake_enabled == '1'
                    <div class="col-sm-9 stn-quick-stats">
                    #else
                    <div class="col-sm-12 stn-quick-stats">
                    #end if

                        
                        <div class="row">
                            <div class="snapshot-records-text">
                                $obs.label.weather_snapshots <a
href="$relative_url/records">$obs.label.weather_snapshots_link</a>
                            </div>

                            <div class="col-sm-6 stn-quick-stats">
                                <div class="stats-title">
                                    <span
class="snapshot-records-today-header"></span>
                                </div>
                                <table>
                                    <tr>

<td><b>$obs.label.snapshot_high:</b></td>    <td><span
class="dailystatshigh">$day.outTemp.max</span></td>

<td><b>$obs.label.snapshot_low:</b></td>    <td><span
class="dailystatslow">$day.outTemp.min</span></td>
                                    </tr>
                                    <tr>

<td><b>$obs.label.snapshot_today_avg_wind:</b></td>    <td><span
class="dailystatswindavg">$day.wind.avg</span></td>

<td><b>$obs.label.snapshot_today_high_wind:</b></td>        <td><span
class="dailystatswindmax">$day.wind.max</span></td>
                                    </tr>
                                    <tr>

<td><b>$obs.label.snapshot_today_rain:</b></td>    <td><span
class="dailystatsrain">$day.rain.sum</span></td>

<td><b>$obs.label.snapshot_today_rainrate:</b></td>    <td><span
class="dailystatsrainrate">$day.rainRate.max</span></td>
                                    </tr>
                                </table>
                            </div>

                            
                            <div class="col-sm-6 stn-quick-stats
border-left">
                           <div class="col-sm-6 stn-quick-stats
border-left">
                                <div class="stats-title">
                                    <span
class="snapshot-records-month-header"></span>
                                </div>
                                <table>
                                    <tr>

<td><b>$obs.label.snapshot_high:</b></td>    <td><span
class="monthstatshigh">$month.outTemp.max</span></td>

<td><b>$obs.label.snapshot_low:</b></td>    <td><span
class="monthstatslow">$month.outTemp.min</span></td>
                                    </tr>
                                    <tr>

<td><b>$obs.label.snapshot_month_avg_wind:</b></td>    <td><span
class="monthstatswindavg">$month.wind.avg</span></td>

<td><b>$obs.label.snapshot_month_high_wind:</b></td>        <td><span
class="monthstatswindmax">$month.wind.max</span></td>
                                    </tr>
                                    <tr>

<td><b>$obs.label.snapshot_month_rain:</b></td>        <td><span
class="monthstatsrain">$month.rain.sum</span></td>

<td><b>$obs.label.snapshot_month_rainrate:</b></td>    <td><span
class="monthstatsrainrate">$month.rainRate.max</span></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                        <div class="col-sm-3 earthquake-container
border-left">
                            <div class="snapshot-records-text">
                                 Yesterday in Review
                            </div>
                            <div class="stn-quick-stats">
                                 <div class="stats-title">
                                      $yesterday.dateTime.format("%B %d,
%Y")
                                 </div>
                                 <table>
                                     <tr>
                                          <td><b>High:</b></td>
                                          <td colspan="3"><span
class="dailystatshigh">$day(days_ago=2).outTemp.max</span> &nbsp; at &nbsp;
$yesterday.outTemp.maxtime</span></td>
                                     </tr>
                                     <tr>
                                          <td><b>Low:</b></td>
                                          <td colspan="3"><span
class="dailystatslow">$yesterday.outTemp.min</span> &nbsp; at &nbsp;
$yesterday.outTemp.mintime</span></td>
                                     </tr>
                                     <tr>
                                          <td><b>Rain:</b></td>
 <td><span class="dailystatsrain">$yesterday.rain.sum</span></td>
                                          <td><b>Wind:</b></td>
 <td><span class="dailystatswind">$yesterday.wind.max</span></td>
                                     </tr>
                                 </table>
                                </div>
                        </div>
                </div>

**Comment by poblabs** [comment]
It's working for me on the latest development version of the skin. 

Do you have any errors in your syslog that may indicate an error elsewhere?

![image](https://user-images.githubusercontent.com/3484775/84332876-15d76500-ab5c-11ea-880e-e5a8d850d9b9.png)

**Comment by Zimerhonzl** [comment]
No errors.  I just did a refresh on the page and noticed it show the
correct information for a split second, then replaced the data with today's
information.  Is there javascript, AJAX or some other language that may be
overwriting the data?  If I pull up the page source it shows the correct
data in the straight HTML, but that's not what shows on the page.

**Comment by Zimerhonzl** [comment]
It looks like maybe the span class is overwriting the information??

**Comment by Zimerhonzl** [comment]
I changed the span class on each of the data points and now it is reporting
correctly.  I could not find what was causing it to be overwritten when
searching for that specific class though.  Thanks for the help.

**Comment by poblabs** [comment]
Glad you got it working. Some things you could try as well:

1) [Use custom.css](https://github.com/poblabs/weewx-belchertown#custom-css) to manipulate the span without losing changes on skin upgrades
2) [Use a hook `.inc` file](https://github.com/poblabs/weewx-belchertown#add-custom-content-to-the-front-page) to position this custom data so you don't lose changes on skin upgrades.
