### ISSUE TITLE
No more DarkSky APIs

### ISSUE THREAD

**Issue by JasonArtz** [poblabs/weewx-belchertown#298]
Hello,
This is a really nice skin, thank you!  I just discovered it and am working on implementing it, but unfortunately DarkSky says they aren't taking signups for new APIs anymore.  Are there any alternatives for forecasts?  I have a windy api and also weather underground.
Thanks agian!

**Comment by poblabs** [comment]
Yes, download and check out the [readme for the development branch](https://github.com/poblabs/weewx-belchertown/tree/development) which uses Aeris Weather's API
