### ISSUE TITLE
belchertownMETAR

### ISSUE THREAD

**Issue by GarryALockyer** [poblabs/weewx-belchertown#299]
Please see belchertownMETAR on github to view an extension (based on metargenerator) to retrieve aviation weather METARs and TAFs and display them within your Belchertown skin.  Your feedback is welcomed.

Thanks for your most excellent skin!

Regards,

Garry

**Comment by poblabs** [comment]
Looks interesting! Do you have it running on a website I could look at?

**Comment by GarryALockyer** [comment]
lockyer.ca/weather/OsoyoosLakeNorthEast

Regards,

Garry Lockyer
C: +1.250.689.0686
H: +1.250.495.5343
E: Garry@Lockyer.ca
