### ISSUE TITLE
About page is overwritten on upgrades

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#3]
The about.inc is overwritten on upgrades

@41south I'm thinking about this issue. Do you think it makes sense to delete the about.inc from the package and instruct users to create their own during install? 

This would prevent overwriting issues, but would require users to create the file.

**Comment by 41south** [comment]
Can the about.inc be included in the archive but not included with the installer - that way the user could just copy it from the archive folder post install and it won't be overwritten during an upgrade. 
The same issue also applied to records.inc file?

**Comment by poblabs** [comment]
Yeah that could work I think - as it's documented how to do it. I can do some testing.

**Comment by poblabs** [comment]
[I've updated the README with how to create or edit these files](https://github.com/poblabs/weewx-belchertown#customizing-about-page-and-records-page) to alter the content on these pages. Right now I think this is the best way to prevent them from being overwritten on upgrades.
