### ISSUE TITLE
Forecast data problem

### ISSUE THREAD

**Issue by JasonArtz** [poblabs/weewx-belchertown#300]
Hello,
I set up an aeris account and it's working, but I get this error when I run wee_reports (or wait for an archive interval):

```
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 861, in get_extension_list
    raise Warning( "Error downloading forecast data. Check the URL in your configuration and try again. You are trying to use URL: %s, and the error is: %s" % ( forecast_url, error ) )
Warning: Error downloading forecast data. Check the URL in your configuration and try again. You are trying to use URL: https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=mysecretcodehere, and the error is: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
```

If I try to go to that URL in the error message (with the correct secret code), it works -- or looks like it works.  I see data with forecast information.

Any ideas?  

website is www.ak7v.com

Thanks

**Comment by poblabs** [comment]
First time I'm seeing this. Let me do some research and see if I can come up with something for you to test out

**Comment by poblabs** [comment]
Which version of Python are you using?

**Comment by JasonArtz** [comment]
Python 2.7.6

**Comment by poblabs** [comment]
So far what I'm finding is that this error isn't related to the skin, but to your system. Perhaps it needs to be updated? 

If you run this command, does the same error come up (`SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`)?

`https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=mysecretcodehere`

**Comment by JasonArtz** [comment]
I get a different error:

artzja@artzja-ThinkCentre-M58p /var/www/weewx/json $ wget https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcodehere
[1] 3938
[2] 3939
[3] 3940
[4] 3941
[5] 3942
[2]   Done                    format=json
artzja@artzja-ThinkCentre-M58p /var/www/weewx/json $ --2020-06-12 13:54:05--  https://api.aerisapi.com/forecasts/34.36159,-117.65018?
Resolving api.aerisapi.com (api.aerisapi.com)... 13.225.146.93, 13.225.146.42, 13.225.146.13, ...
Connecting to api.aerisapi.com (api.aerisapi.com)|13.225.146.93|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-06-12 13:54:05 ERROR 400: Bad Request.


[1]   Exit 8                  wget https://api.aerisapi.com/forecasts/34.36159,-117.65018?
[3]   Done                    filter=day
[4]-  Done                    limit=7
[5]+  Done                    client_id=5Y75EL1n376AeswmEmGc1
artzja@artzja-ThinkCentre-M58p /var/www/weewx/json $

**Comment by JasonArtz** [comment]
Tried again with "-d" option if it helps:

artzja@artzja-ThinkCentre-M58p /var/www/weewx/json $ sudo wget -d https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secret
[1] 4383
[2] 4384
[3] 4385
[4] 4386
[5] 4387
artzja@artzja-ThinkCentre-M58p /var/www/weewx/json $ DEBUG output created by Wget 1.15 on linux-gnu.

URI encoding = ‘UTF-8’
--2020-06-12 14:03:20--  https://api.aerisapi.com/forecasts/34.36159,-117.65018?
Resolving api.aerisapi.com (api.aerisapi.com)... 13.225.146.93, 13.225.146.66, 13.225.146.42, ...
Caching api.aerisapi.com => 13.225.146.93 13.225.146.66 13.225.146.42 13.225.146.13
Connecting to api.aerisapi.com (api.aerisapi.com)|13.225.146.93|:443... connected.
Created socket 3.
Releasing 0x000000000243f650 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x000000000243f9a0
certificate:
  subject: /CN=*.aerisapi.com
  issuer:  /C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
X509 certificate successfully verified and matches host api.aerisapi.com

---request begin---
GET /forecasts/34.36159,-117.65018? HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: api.aerisapi.com
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 400 Bad Request
Content-Type: application/json;  charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 12 Jun 2020 20:43:38 GMT
Server: nginx/1.17.10
Pragma: public
X-Cacheaction-Stored: action__error_error_c86cf95ccd2a72fb288392b8592017e1 ttl 1200
Expires: Fri, 12 Jun 2020 21:03:38 GMT
Cache-Control: public,max-age=1200,s-maxage=1200
X-Cache: Error from cloudfront
Via: 1.1 c9cf34e325f403e993adb63735f5db29.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LAX3-C4
X-Amz-Cf-Id: 9FPM-Yl63magDi0-iYipbl9guSoiX8yeJwMLl35KDql4ElrJjf-v9A==
Age: 1179

---response end---
400 Bad Request
Registered socket 3 for persistent reuse.
URI content encoding = ‘utf-8’
Skipping 144 bytes of body: [{"success":false,"error":{"code":"invalid_client","description":"A valid \"client_id\" and \"client_secret\" were not provided."},"response":[]}] done.
2020-06-12 14:03:20 ERROR 400: Bad Request.


[1]   Exit 8                  sudo wget -d https://api.aerisapi.com/forecasts/34.36159,-117.65018?
[2]   Done                    format=json
[3]   Done                    filter=day
[4]-  Done                    limit=7
[5]+  Done                    client_id=5Y75EL1n376AeswmEmGc1

**Comment by JasonArtz** [comment]
If I go to the address in my browser, it appears to work:

![image](https://user-images.githubusercontent.com/66756993/84546315-f5232280-acb5-11ea-9125-5b7ac5005b7a.png)

**Comment by poblabs** [comment]
Is your browser and weewx on the same machine?

If not try that wget command on your weewx machine. You're missing
something on the system. What kind of operating system are you using?
Ubuntu? Raspberry Pi?

**Comment by poblabs** [comment]
Oops just saw you tried the wget.

Try again with the URL encapsulated in quotes. The & symbols mess wget up
unless they are in quotes.

**Comment by JasonArtz** [comment]
Using quotes with wget worked, and I get a file with the name of the URL and it's full of what looks like weather data.  Here's the result of the wget:

artzja@artzja-ThinkCentre-M58p ~ $ wget -d "https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcode"
DEBUG output created by Wget 1.15 on linux-gnu.

URI encoding = ‘UTF-8’
--2020-06-12 15:59:50--  https://api.aerisapi.com/forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcode
Resolving api.aerisapi.com (api.aerisapi.com)... 13.225.146.42, 13.225.146.66, 13.225.146.93, ...
Caching api.aerisapi.com => 13.225.146.42 13.225.146.66 13.225.146.93 13.225.146.13
Connecting to api.aerisapi.com (api.aerisapi.com)|13.225.146.42|:443... connected.
Created socket 3.
Releasing 0x00000000014e8a20 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00000000014e8d70
certificate:
  subject: /CN=*.aerisapi.com
  issuer:  /C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
X509 certificate successfully verified and matches host api.aerisapi.com

---request begin---
GET /forecasts/34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcode HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: api.aerisapi.com
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Content-Type: application/json;  charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 12 Jun 2020 22:59:06 GMT
Server: nginx/1.17.10
Pragma: public
X-Aeris-Auto: 0
X-Cacheaction-Stored: action__forecasts_index_8ddeb5c0d9dce75e85632351ae0e00ab ttl 1200
Expires: Fri, 12 Jun 2020 23:19:06 GMT
Cache-Control: public,max-age=1200,s-maxage=1200
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Expose-Headers: Content-Length,Content-Range
X-Cache: Hit from cloudfront
Via: 1.1 bc161f8df9d7f93222b6ee0772bc41dc.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LAX3-C4
X-Amz-Cf-Id: KeivC82eRynI2oaxbXUVNsGHUMZvxTLPKEar2qjzNNh2oU4hZQGzaA==
Age: 41

---response end---
200 OK
Registered socket 3 for persistent reuse.
URI content encoding = ‘utf-8’
Length: unspecified [application/json]
Saving to: ‘34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcode’

    [ <=>                                                                                                         ] 12,655      --.-K/s   in 0.001s  

2020-06-12 15:59:50 (17.1 MB/s) - ‘34.36159,-117.65018?&format=json&filter=day&limit=7&client_id=5Y75EL1n376AeswmEmGc1&client_secret=secretcode.1’ saved [12655]


I am using Linux Mint and it's running on an old Lenovo ThinkCentre.  Same computer weewx is running.

Thanks,
Jason

**Comment by JasonArtz** [comment]
I got forecasts to work by changing the "https://api.aerisapi.com/etc..." calls to "http://"  (removed the s)

I assume this is bad practice but it works -- probably leaves my secret key exposed -- perhaps it gives someone wiser than me a clue as to what's wrong with my system, though?  

Thanks,
Jason
www.ak7v.com
