### ISSUE TITLE
DarkSky API shutting down

### ISSUE THREAD

**Issue by magimat** [poblabs/weewx-belchertown#301]
Following apple acquisition, Darksky is no longer accepting new API registration and will be shutting down at the end of 2021.

Are you planning on using a new API service for forecast?    I'm very interested in your skin, but I can't register for a new DarkSky API :(

**Comment by poblabs** [comment]
Yes, please use the [development version of the skin](https://github.com/poblabs/weewx-belchertown/tree/development). The readme has the instructions on how to setup Aeris API

**Comment by magimat** [comment]
awesome, thanks!
