### ISSUE TITLE
Feels Like Temp (AppTemp) Does not appear on Pi page until after archive interval.

### ISSUE THREAD

**Issue by JagerSprinkles** [poblabs/weewx-belchertown#303]
On the Pi page the feelslike DIV is empty until an archive interval occurs. 
I use a 15 minute archive interval so this causes the data to be missing for a little bit when I refresh the page.

I am using the development version 1.2b5 currently.

Please see the screenshots showing the page before and after an archive interval.

Please let me know if you require any more details or information.

Before archive
![before archive](https://user-images.githubusercontent.com/6476475/85071938-3e77e400-b186-11ea-9171-67628c1f1bb1.jpg)
![feelslike Div empty](https://user-images.githubusercontent.com/6476475/85071831-1a1c0780-b186-11ea-89dd-1e869dc1ca15.png)

After archive
![feelslike appears after archive interval](https://user-images.githubusercontent.com/6476475/85071830-19837100-b186-11ea-833f-06231c4cdb4b.png)

**Comment by poblabs** [comment]
This could be because your station does not provide that observation in the
loop. can you verify your loop has apparent temperature?

**Comment by poblabs** [comment]
FYI - I have AppTemp in my loop and it shows up right as I'm connected to my broker (you can verify at https://belchertownweather.com/pi) 

So I do not believe this to be a problem with the skin. 

Here's a gif of my Pi during a page refresh (thats why it's a little jumpy), but once it connects I get feels like (aka AppTemp)

![feelslike](https://user-images.githubusercontent.com/3484775/85080573-8c491800-b197-11ea-8621-4fdfe4bc3168.gif)

**Comment by poblabs** [comment]
Also the Pi page uses the same AJAX engine as the main page. I'm willing to bet you don't have AppTemp on your main page until an archive period too?

**Comment by JagerSprinkles** [comment]
I just checked and I do not have AppTemp in my loop, this would explain why it does not load in until an archive period. Definitely not an issue with the skin since that's how its designed. 

However the AppTemp is always there on the main page, it just does not update with the MQTT packets, I'll have to look into modifying the template pull the data the same way the main page does.

Thank you for confirming its not an issue with the skin.

**Comment by poblabs** [comment]
No problem - I just took a look again, and you're right - it shows up on the main page straight awayy because it's getting that data from the weewx page generation (see below). 

```
#if $current.appTemp.has_data
<div class="feelslike">$obs.label.feels_like: $current.appTemp</div><!-- AJAX -->
#end if
```

I'll add that to the pi page now so you have it on initial load.

**Comment by JagerSprinkles** [comment]
Yep, I just saw the same thing, thank you!

**Comment by poblabs** [comment]
All set! Grab the latest skins/Belchertown/pi/index.html.tmpl and run a wee_reports or let an archive interval pass and it should be there for you on initial page load.
