### ISSUE TITLE
I install the Skin 1.1 first to test

### ISSUE THREAD

**Issue by nady2804** [poblabs/weewx-belchertown#304]
Hello, 
This shin looks very nive and i choose it because they have a windrose i guess.
But i fon't see any information in the .conf files regarding windrose plot.

How can i enable the windrose graph?
can anybody help.

many thx Manfred

**Comment by Brezentrager** [comment]
The information you are looking for is documented in the Chart Documentation:
https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation

There is also a support forum for such kind of questions available (where support via the community is typically quicker):
https://groups.google.com/g/weewx-user

Best regards,
Manfred

**Comment by poblabs** [comment]
Closing issue since @Brezentrager explained it well. Thank you!
