### ISSUE TITLE
Issue in Belchertown.js when setting the locale to de_CH.UTF-8

### ISSUE THREAD

**Issue by Brezentrager** [poblabs/weewx-belchertown#305]
Hi Pat,
when setting the locale to de_CH.UTF-8 the Belchertown.js breaks.

In line 507 (of the final belchertown.js which is sent to the webspace) there's the setting for the thousand-separator. In Switzerland this is a '
So line 507 turns into:
       thousandsSep: '''

... and this line crashes.

Manfred

**Comment by poblabs** [comment]
Line 507 is different for me in the compiled belchertown.js file, but I just pushed a commit to where I think you're referring to. Can you try it out?

**Comment by Brezentrager** [comment]
The user reported back that the fix works!

The issue can be closed. Thanks!
