### ISSUE TITLE
Graphs Wiki has some out of data formatting in examples

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#306]
The one that stood out was my solar graph example, it now uses the wrong format for the axis labels. This may be true also of other older examples but I haven't done a thorough check :)

**Comment by poblabs** [comment]
Do you have a working example you can share?

**Comment by 41south** [comment]
This is the one that originally got my attention when trying to sort out the yAxis label problem, it's my solar graph example with old y_label entries

`[[solarRadGraph]]
    title = Solar Radiation and  UV Index
    [[[radiation]]]
       name = Solar Radiation
       zIndex = 1
       color = "#ffc83f"
    [[[maxSolarRad]]]
        name = Theoretical Max Solar Radiation
        type = area
        color = "#f7f2b4"
        y_label = "W/m2"
    [[[UV]]]
        yAxis = 1
        yAxis_min = 0
        yAxis_max = 14
        color = "#90ed7d"
        y_label = "UV"
        name = UV Index
        zIndex = 2`

**Comment by poblabs** [comment]
Ah, and `y_label` has been renamed to `yAxis_label`, right?

**Comment by 41south** [comment]
Yes indeed :)

**Comment by poblabs** [comment]
Good catch, I'll get those edited!
