### ISSUE TITLE
yAxis_label_unit 

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#307]
I've beaten my head against a brick wall with this one. I can't seem to get the yAxis_label_unit to work as per the Wiki. According to the Wiki
```
yAxis_label_unit
In version 1.0 and 1.0.1 this was yAxisLabel_unit
You can specify a custom unit label for the yAxis label. For example, a value of yAxis_label_unit = "W/m2" will put the "W/m2" inside the yAxis label's parenthesis.
```

But in my AQM charts I have 
```
[AQM]
        show_button = true
        button_text = AQM
        time_length = today
        [[chart1]]
          title = Air Quality Data CO2
          [[[AQICO2]]]
                name = CO2 level (Inside)
                [[[[numberFormat]]]]
                decimals = 0
                decimalPoint = "."
                thousandsSep = ""
        [[chart2]]
          title = Air Quality Index
           [[[AQIIndex]]]
                name = Air Quality Index
                [[[[numberFormat]]]]
                decimals = 0
        [[chart3]]
          title = Dust Concentraion
            [[[AQI25]]]
                name = PM 2.5
                [[[[numberFormat]]]]
                decimals = 1
            [[[AQI100]]]
                name = PM 10
                yAxis_label = "Dust Concentration"
                yAxis_label_unit = "ug/m3"
                [[[[numberFormat]]]]
                decimals = 1
```

And it will not display the units. The label itself works fine

**Comment by poblabs** [comment]
The `yAxis_label_unit` is intended to go at the top of the grouping, with the title and such., but it doesn't seem to be working correctly. So I'll have to test and patch this

**Comment by poblabs** [comment]
It's actually working. I just need to update the documentation so it's a bit clearer on how it works. Here's an example:

```
    [[chart1]]
        title = Temperature
        name = Test
        yAxis_label_unit = "ug/m3"
        [[[outTemp]]]
```

![image](https://user-images.githubusercontent.com/3484775/85406614-0ed32e00-b530-11ea-9b29-1f181d6d608e.png)

**Comment by poblabs** [comment]
I'm actually going to see if I can change this behavior so that `yAxis_label` and `yAxis_label_unit` can work together since `name` is used as part of the legend (see my test screenshot with all the Test Test Test's)

**Comment by poblabs** [comment]
I think it's working now. I'll update the development branch and the wiki examples. 

```
    [[chart1]]
        title = Temperature
        yAxis_label = "Test yAxis Label"
        yAxis_label_unit = "test unit here"
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
```

![image](https://user-images.githubusercontent.com/3484775/85408753-ee58a300-b532-11ea-9b07-47867747d585.png)

**Comment by 41south** [comment]
Ok I'll update and try it again. I tried moving it to the top without an update and it still didn't work

`[[chart3]]
          title = Dust Concentration
          yAxis_label = "Dust Concentration"
          yAxis_label_unit = "ug/m3"
            [[[AQI25]]]
                name = PM 2.5
                [[[[numberFormat]]]]
                decimals = 1
            [[[AQI100]]]
                name = PM 10`

**Comment by poblabs** [comment]
You'll need to download the latest development branch and restart weewx.

**Comment by 41south** [comment]
Excellent - thanks!

**Comment by 41south** [comment]
Done and confirmed working

Cheers
