### ISSUE TITLE
js/belchertown.js.tmpl typo for uk2 forecast_units (version 1.2b6)

### ISSUE THREAD

**Issue by James-76** [poblabs/weewx-belchertown#308]
Hello

Just trying out your new code to see how it works with aeris, which is very well!   Found a minor typo on line 929 where it is uk instead of uk2 therefore temperatures are being displayed in F.

```
// Determine temperature units
if ( ( "$Extras.forecast_units" == "ca" ) || ( "$Extras.forecast_units" == "uk" ) || ( "$Extras.forecast_units" == "si" ) ) {
    minTemp = data["forecast"][0]["response"][0]["periods"][i]["minTempC"];
```

James

**Comment by poblabs** [comment]
Sweet, thanks for pointing that out! Just updated it in the development branch
