### ISSUE TITLE
Formatting on iPad

### ISSUE THREAD

**Issue by uajqq** [poblabs/weewx-belchertown#309]
The forecast section displays on two lines when viewed on my iPad, despite my iPad being much higher resolution than my computer monitor. I forked the repo and changed the width of the iPad forecast columns to match the desktop forecast columns in style.css, which fixes this issue for me. Could the desktop forecast column width (165px) be made the default for the iPad format?

**Comment by poblabs** [comment]
Sure can you provide the section you forked it with?

**Comment by uajqq** [comment]
I opened a pull request with the change.
