### ISSUE TITLE
Weather Record Snapshot day doesn't update "on archive interval" change

### ISSUE THREAD

**Issue by biltmorelaker** [poblabs/weewx-belchertown#31]
The current day under "Weather Record Snapshots" on the main page (see attached screenshot)
doesn't update automatically on archive intervals. The data in that block does update on archive intervals, but you need to refresh the page to get the day to change if you leave the website up overnight. I'm not sure if the current month in that block also has the same issue.

![inkedscreenshot_2018-12-28 biltmore lake nc weather conditions_li](https://user-images.githubusercontent.com/44727343/50524194-70811c00-0aa2-11e9-810a-cc303257e033.jpg)

**Comment by poblabs** [comment]
Should be all set now!

**Comment by biltmorelaker** [comment]
Thanks. I'll give it a try. If I have any other issues, I'll let you know.

**Comment by poblabs** [comment]
Thanks. I also just made another change in https://github.com/poblabs/weewx-belchertown/commit/a83b4ff26364b865b07be54683048e7949902353 to update the month name if the site rolls into a new month too. Forgot about that yesterday.

**Comment by biltmorelaker** [comment]
I'm grabbing that one now. Thanks.
