### ISSUE TITLE
Graph With formular date to date

### ISSUE THREAD

**Issue by ardefy** [poblabs/weewx-belchertown#310]
Hi,

I want to do a possibility of graph with a formular date to date 

is there a source code to do that?

Best regards

**Comment by poblabs** [comment]
Have you checked the wiki? I think you're looking for this option. 

[To graph a specific timespan](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#to-graph-a-specific-time-span)
