### ISSUE TITLE
Aeriswether Forecast Question

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#312]
Hello Pat!
How are you? I hope that you and your family are fine. It has been a long time since I had the time to toy with my weather station again. As the raspberry pi SD card has been failing for months, I decided to change it and I've updated weewx to its final version and I've applied your skin from development branch.
I have a few questions about Aerisweather forecast implementation. I didn't find the correct value for "forecast_units" key to retrieve temperature values in metric system and not imperial. (forecast_units="metric"). 
Am I doing something wrong or it's not implemented yet?
I began to translate forecast codes into spanish and I think there might be a problem with the intensity codes in other languages that are not english. These words are adjectives so it's fine if they are before a noun in english but in other languages like spanish they should be after the noun. Also we have the gender issue, because a noun can be male or female and the adjective should be male or female too to match them. I don't know if there is an easy solution for that. I think we as users might consider not to translate at all or if you can create some new keywords to join intensity + weather codes into one unique keyword and then we can translate them as a phrase so we can avoid words order and gender problems.
The good part is that Aerisweather map service is great!!! Check this out! This is simple example of them.  
![2020-06-23 19 46 36 climacolegiales com ar 86d96c967a8e](https://user-images.githubusercontent.com/4549674/85473903-4c64a500-b58a-11ea-90c3-49ed14fb6c2c.png)

**Comment by 41south** [comment]
This might fix your 'units' problem I have just been through the same :)

https://github.com/poblabs/weewx-belchertown/tree/development#forecast-options
https://github.com/poblabs/weewx-belchertown/tree/development#forecast-units

**Comment by HoracioDos** [comment]
Lol!! When you've tried everything and nothing worked, read the instructions!

**Comment by 41south** [comment]
Haha, that was my problem too!

**Comment by poblabs** [comment]
Glad you guys figured that out! 

@HoracioDos Hmm, I'm not sure how to handle the intensity codes since [Aeris gives them to me in that way](https://www.aerisweather.com/support/docs/api/reference/weather-codes/). I don't have a way to reverse their verb order or gender.

**Comment by HoracioDos** [comment]
Don't worry Pat! . I think I can live without intensity codes.
```
forecast_intensity_code_VL = ""
forecast_intensity_code_L = ""
forecast_intensity_code_H  = ""
forecast_intensity_code_VH = ""
```

**Comment by HoracioDos** [comment]
Hello Pat!
I forgot to mention that Aeris Weather forecast dates seem to be ignoring belchertown locale keyword. Dates are in month/day format as you can see above but I've set `belchertown_locale = es_AR.UTF-8`
Thanks in advance

**Comment by poblabs** [comment]
Hello @HoracioDos a lot of things had to change with Aeris. The date format now follows the label in skin.conf called `time_forecast_date`.

**Comment by HoracioDos** [comment]
Grrr!! I was so sure that I copied all new keywords from skinf.conf file (development branch) . I'm getting old. :-(
Thank you very much!

**Comment by poblabs** [comment]
No worries! 😄

**Comment by ijg** [comment]
Hello,  I'm having the same issue with units.  I've tried everything but the forecast keeps appearing in US.  There are 2 links at the top of this thread that may have helped but they are both dead.

Thank you.

Ig.
www.ajaxweather.com

**Comment by WiggyToo** [comment]
> Hello @HoracioDos a lot of things had to change with Aeris. The date format now follows the label in skin.conf called `time_forecast_date`.

Just what I needed having updated to 1.3.1 - thanks @poblabs
