### ISSUE TITLE
Improved alignment on homepage

### ISSUE THREAD

**Issue by Brezentrager** [poblabs/weewx-belchertown#314]
Hi Pat,
this is a suggestion for an improved alignment of items on the main page.
In case there is a reason for how you have structured this section on the page, please ignore my suggestion.

This is your page:
<img width="345" alt="Bildschirmfoto 2020-06-25 um 19 11 37" src="https://user-images.githubusercontent.com/8404725/85767412-48668d80-b718-11ea-92d1-9bea9eb6bbb6.png">

And this is my page (with aligned vertical dividing lines for temp and wind. Also the forecast icon and the wind compass are better aligned):
<img width="345" alt="Bildschirmfoto 2020-06-25 um 19 11 50" src="https://user-images.githubusercontent.com/8404725/85767861-bca13100-b718-11ea-8410-5634b2d90304.png">

The change that I made is a quite simple one to the index.html.tmpl
I've changed this section to col-sm-6

                           
                            <div class="weather-obs-top">
                                <div class="row temp-observation">
                                    <div class="col-sm-6 current_obs_top">
                                        #if $Extras.has_key("forecast_enabled") and $Extras.forecast_enabled == '1'
                                        <img id="wxicon" src="$relative_url/images/$current_obs_icon">
                                        #end if
                                    </div>
                                    <div class="col-sm-6 current_temp">
                                        <div class="outtemp_outer"><span class="outtemp">$current.outTemp.formatted</span><sup class="outtempunitlabelsuper">$unit.label.outTemp</sup></div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 current-obs-container">
                                        <div class="current-obs-text">
                                            $current_obs_summary
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        #if $current.appTemp.has_data
                                        <div class="feelslike">$obs.label.feels_like: $current.appTemp</div>
                                        #end if
                                        <div class="stn-high-low">
                                            <table class="stn-high-low-table">
                                                <tbody>
                                                    <tr>
                                                        <td class="stn-high-low-table-title">$obs.label.highest_temperature</td>
                                                        <td class="stn-high-low-table-title border-left">$obs.label.lowest_temperature</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="high">$day.outTemp.max</td>
                                                        <td class="border-left low">$day.outTemp.min</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

**Comment by poblabs** [comment]
Your changes seem to have made a bigger difference then intended 😄 

Probably a bad paste to Github?  Do you want to attach your index.html.tmpl so I can check it out?

![image](https://user-images.githubusercontent.com/3484775/85772368-c318b400-b6ea-11ea-938a-74dcb8ea9069.png)

**Comment by Brezentrager** [comment]
Ah ... you are right. I did some more changes, but they were stored in the custom.css file - so I forgot about them :(

Attached both files.

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4833091/belchertown.zip)

**Comment by poblabs** [comment]
I think it looks good. Not quite lined up on my site, but close enough (this is probably due to the text). 

Do you want to submit a PR? Or just want me to merge this?

![image](https://user-images.githubusercontent.com/3484775/85777148-59e76f80-b6ef-11ea-84cb-013eae670e7d.png)

**Comment by Brezentrager** [comment]
Would be great if you could merge it. I'm not very experienced with PR on Github.

**Comment by poblabs** [comment]
All set! Thanks for the coffee too! ☕

**Comment by Brezentrager** [comment]
Found the reason for the not 100% exact alignment.
Those two changes (setting the column width to 50%) to the style.css fixed it on my site:

.wind-table td {
        text-align:center !important;
        width:50%;
}

.stn-high-low-table td {
        text-align:center;
        width:50%;
}

I haven't seen any negative effects of those changes. Should hopefully also work with 3-digit temperatures in °F.

**Comment by poblabs** [comment]
Looks good here! 

![image](https://user-images.githubusercontent.com/3484775/85909111-3a7f3e00-b7e6-11ea-88e9-122d865f10ea.png)

**Comment by 41south** [comment]
Nice work gents 👍
