### ISSUE TITLE
Feature Request: Min/Max Bar Graph when min & max are different fields

### ISSUE THREAD

**Issue by jbellanca** [poblabs/weewx-belchertown#315]
I have lightning distance in 3 fields in WeeWx:
  1. Average Distance = lightning_distance - average distance of all strikes in the loop period
  2. Minimum Distance = signal7 - closest strike distance of all strikes in the loop period
  3. Maximum Distance = signal8 - furthest strike distance of all strikes in the loop period

I'd like a way to graph them with a floating column (similar to the radial), with the top of the bar for each step on the x-axis to come from the max distance, and the bottom of the bar to be the min distance. Then I'd put a dot for the average within the bar.

Kind of like you can see here:
[https://www.techrepublic.com/blog/windows-and-office/an-easy-technique-for-creating-a-floating-column-chart-in-excel/](url)

I've tried this, which gets me part of the way there. If I could (1) make the bars not stacked on top of each other, but overplayed instead, and (2) set the minimum bar to the background color, that would make it work.

    [[LightningDistance]]
        title = Lightning Strikes
        type = column
        [[[signal7]]]
            name = Closest
            stacking = normal
            aggregate_type = min
        [[[signal8]]]
            name = Furthest
            stacking = normal
            aggregate_type = max

**Comment by poblabs** [comment]
This is one of the challenges of the skin - adding new charts which Highcharts supports but translating it in a way that makes sense with the skin. I wonder if I have to create a new chart type (unique to belchertown) in the same light as the radial chart. That way you can specify min as 1 observation, max as another, then have the skin do the average plot? Then we need to determine how to best customize it for colors, other observations, etc. 

Not sure how else to handle this one other than a custom new chart type that gets translated behind the scenes?

**Comment by poblabs** [comment]
This might need to be even more generic. I think it would have to be something like this? 

Would need a lot of testing across all the timespans available. 

Hmm...

```
[[graphname]]
  title = graph title
  [[[columnRange]]]
    min = outTemp (the observation for the min)
    max = outTemp (the observation for the max)
    avg = outTemp (the observation for the average)
    avg_
```

**Comment by poblabs** [comment]
Actually, weatherRange is already half way there. Perhaps that's all that needs to be tweaked. Right now you specify the observation for the weatherRange:

```
        [[[weatherRange]]]
            range_type = outTemp
```

But maybe we define it like I mentioned above, and this becomes the new "default" for the weatherRange outTemp:

```
        [[[weatherRange]]]
            range_min = outTemp
            range_max = outTemp
            range_avg = outTemp
```

The rest of the weatherRange code would do the rest of the work. 

So in your case, it would potentially look like this:

```
        [[[weatherRange]]]
            range_min = signal7
            range_max = signal8
            range_avg = lightning_distance
```

The only catch now is that the average is used to color the range, not show it as an observation. My goal would be to re-use code, so I'll need to keep brainstorming.

**Comment by jbellanca** [comment]
i got a little closer with this:

    [[LightningDistance]]
        title = Lightning Strikes
        type = column
        grouping = false
        [[[signal7]]]
            name = Closest
            aggregate_type = min
        [[[signal8]]]
            name = Furthest
            aggregate_type = max
        [[[lightning_distance]]]
            name = Average
            aggregate_type = avg
            type = line
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0

Found the "grouping" flag from the Highcharts documentation, but it doesn't quite make them overlap, oddly. Will play with it more. And couldn't find a way to say "use the background color" (esp. when there's a light/dark mode!) It does put the right dot in for average, though, now.
