### ISSUE TITLE
Aeris Weather Alerts Europe

### ISSUE THREAD

**Issue by grebleem** [poblabs/weewx-belchertown#318]
It looks like Aeris is now supporting alerts for Europe:
[Alerts Endpoint: New European Alerts and Polygon Support](https://www.aerisweather.com/blog/2020/06/17/alerts-endpoint-new-european-alerts-and-polygon-support/)

It would be great if this can be implemented.

Thanks,
Bastiaan

**Comment by poblabs** [comment]
Closing in favor of tracking in #352. You can follow updates there
