### ISSUE TITLE
Wind-rose not spinning on MQTT updates

### ISSUE THREAD

**Issue by grebleem** [poblabs/weewx-belchertown#319]
On my test server and my main site the wind-rose is not responding anymore to the MQTT packages. The 'winDir' in the /loop is updated every 2.5 s.

On this site version 1.2b6 is installed
[https://meteo-otterlo.nl](https://meteo-otterlo.nl)

On my test site the latest development branch is installed.

What can be the problem?

**Comment by poblabs** [comment]
What do you mean by spinning? The chart is only updated upon archive
interval. The wind rose is not a real time observation (no spinning or
anything). Take a look at my site for an example.
https://belchertownweather.com

**Comment by grebleem** [comment]
I mean the red arrow showing the current wind direction. It was working for days, but now it stopped working. Speed and Gust is updated normally.

**Comment by poblabs** [comment]
Ohh that wind rose. Not the graph. Hmm not sure I'll take a look at your
site

**Comment by poblabs** [comment]
I can't quite connect the dots yet. Your debug is showing a windDir value. Your javascript `rotateThis()` works manually in the JS console. I'm not sure why the two aren't happening on the site. Do you have any errors in your syslog?

**Comment by poblabs** [comment]
I added a new debug inside of `rotateThis()`, can you upgrade your `skins/Belchertown/js/belchertown.js.tmpl` to the latest development version? I want to see if this function is even being called from your site (as it appears it isn't)

**Comment by poblabs** [comment]
I figured it out. Your MQTT packet has a typo in it. Take a look at this:

```
MQTT: {"dateTime": "1593476027.0", "windSpeed_kph": "1.609344", "winDir": "223.0", "windGust_kph": "8.04672", "windGustDir": "360.0", "rain_cm": "0.0", "rainRate_mm_per_hour": "0.0", "beaufort_count": "0.0", "maxSolarRad_Wpm2": "0.0", "hourRain_cm": "0.0", "rain24_cm": "0.0", "dayRain_mm": "0.0", "usUnits": "16.0"}
```

Your wind direction is in the packet as `winDir`. It is missing a "d", needs to be `windDir`.

**Comment by grebleem** [comment]
Thanks a lot! That did the trick.
