### ISSUE TITLE
Weather Conditions

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#32]
https://github.com/poblabs/weewx-belchertown/blob/41b1fa7a297b44bd77ceb5af01420c8fb20453fb/skins/Belchertown/index.html.tmpl#L633

Don't you think that using "Weather Conditions" showing on the index file is rather redundant ? People already come to see the weather conditions right ? Just looks odd when you are browsing other links that don't have it. Of course that's just my opinion.

**Comment by poblabs** [comment]
I don't think this is really an issue of something broken. If you want to change it because it's redundant for you, feel free to change it.
