### ISSUE TITLE
wee_reports runs in failure with haysChart 

### ISSUE THREAD

**Issue by martenhinrichs** [poblabs/weewx-belchertown#321]
Hi,

i have a problem with the new

   [[chart7]]
        [[[haysChart]]]

Installed is Version 1.2b6

Failure:

`root@wetter:/etc/weewx/skins/Belchertown# wee_reports 
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/user/belchertown.py", line 2089, in get_observation_data
    (time_start_vt, time_stop_vt, obs_vt) = archive.getSqlVectors(TimeSpan(start_ts, end_ts), obs_lookup, aggregate_type, aggregate_interval)
  File "/usr/share/weewx/weewx/manager.py", line 452, in getSqlVectors
    aggregate_type, aggregate_interval)
  File "/usr/share/weewx/weewx/xtypes.py", line 91, in get_series
    raise weewx.UnknownType(obs_type)
weewx.UnknownType: haysChart

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 1632, in run
    series_data = self.get_observation_data(binding, archive, observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length, xAxis_groupby, xAxis_categories, mirrored_value, weatherRange_obs_lookup, wind_rose_color)
  File "/usr/share/weewx/user/belchertown.py", line 2091, in get_observation_data
    raise Warning( "Error trying to use database binding %s to graph observation %s. Error was: %s." % (binding, obs_lookup, e) )
Warning: Error trying to use database binding wx_binding to graph observation haysChart. Error was: haysChart.
`

**Comment by uajqq** [comment]
Can you post the entire graphs.conf section the Hays chart is in? Maybe it’s an issue with the default settings for that section.

**Comment by martenhinrichs** [comment]
As you wish. Because of the failure i commented the haysChart

`# Global Chart Defaults
# These are fallback options that charts will use if an option is not defined. 
aggregate_type = None
time_length = 90000 # Last 25 hours
type = line
colors = "#7cb5ec, #b2df8a, #f7a35c, #8c6bb1, #dd3497, #e4d354, #268bd2, #f45b5b, #6a3d9a, #33a02c"
tooltip_date_format = "LLL"

[homepage]
    # Chart Timespan Defaults
    title = "Homepage"
    show_button = true
    button_text = "Homepage"
    time_length = today
    tooltip_date_format = "LLL"
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000 to get milliseconds. Standard is 5 minutes

    [[chart1]]
        title = Temperatur
        [[[outTemp]]]
            zIndex = 1
            name = Temperatur
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple

    [[taupunkt]]
        title = Taupunkt
        subtitle = Gefühlte Schwüle ab ca. 17°C / Sehr Schwühl ab 20°C 
        [[[dewpoint]]]
            color = purple

    
    [[chart3]]
        # The combined Wind Chart works best in this configuration
        title = Wind Geschwindigkeit und Richtung
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            #aggregate_type = avg
            #aggregate_interval = 60
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
            type = area
    
    [[chart2]]
        title = Regen
        [[[rainRate]]]
            yAxis = 1
            type = area
        [[[rainTotal]]]
            name = Regen Total
    
    [[chart5]]
        title = Luftdruck
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            yAxis_tickInterval = 0.01

   [[chart4]]
    title = Wind Rose
    [[[windRose]]]

    [[chart6]]
        title = Temperatur Range dieses Jahr
        css_class = "weatherRadial"
        time_length = year
        [[[weatherRange]]]
            range_type = outTemp
            polar = true

#   [[chart7]]
#        [[[haysChart]]]
            
`

**Comment by poblabs** [comment]
Reinstall the development skin again. You're missing some important code.

**Comment by martenhinrichs** [comment]
Ok Thanks. Reinstall solved it.
