### ISSUE TITLE
Having trouble after adding soil temp and soil moisture

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#325]
Added in the feed from the soil sensor that I have and graphs stopped generating.
At first I thought it was config issue, but verified it's something about the data.  
The columns are in the default DB, so that shouldn't be it.

I saw that initially I had a tag off (spelled soiltemp wrong to start with) but figured that should have just failed in the WeeWX-MQTTSubscribe plugin (it wouldn't have mapped).   Just to confirm, I shut down weewx, moved DB to backup name, regenerated an empty DB (since I'm not "that" far in, I was willing to at least test via this).  Now I can't get any reports to generate.   The error I'm getting in syslog is :

Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****  'NoneType' object is not iterable
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****      obj.start()
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****      self.run()
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1223, in run
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****      minstamp, maxstamp = archiveDaySpan( timespan.stop )
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****  TypeError: 'NoneType' object is not iterable
Jul  6 11:34:24 piX86 wee_reports[715] ERROR weewx.reportengine:         ****  Generator terminated

If i try from command line, I get:

$ sudo wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 324, in get_extension_list
    at_outTemp_max_range_max_tuple = (at_outTemp_max_range_query[3], outTemp_unit, 'group_temperature')
TypeError: 'NoneType' object has no attribute '__getitem__'

So, I'm thinking that perhaps weewx doesn't "sum" up soil temp?   And perhaps you thought it would?  Thoughts?

**Comment by poblabs** [comment]
There's a `None` for a timestamp which is odd. Can you zip your database and attach here? I'm curious.

**Comment by earlthesquirrel** [comment]
[weewx.sdb.new.gz](https://github.com/poblabs/weewx-belchertown/files/4879996/weewx.sdb.new.gz)
[weewx.messedup.sdb.gz](https://github.com/poblabs/weewx-belchertown/files/4879997/weewx.messedup.sdb.gz)


FYI -- messed-up is the DB backup prior to deleting (I think the issue is there, but it seemed to be making it past it earlier... now after a restart I'm not sure it is). 

new is the one I just created which was generating the errors.

**Comment by poblabs** [comment]
Your database is missing `outTemp` values, so the skin is failing trying to build the temperature records. I assume you have a temperature sensor?

**Comment by earlthesquirrel** [comment]
Yes, have two.   And the soil temp, so 3.

**Comment by earlthesquirrel** [comment]
Take a look at the "messed up" db.
That one seems to be ingesting values still (though no idea why it would be any different -- that was the DB I recreated last week with the extra gas columns.   All I did after that was start feeding soilMoist1 and soilTemp1 values.   

With "very simple" graphs (copied the humidity one and changed value -- that's it) and no go.

**Comment by poblabs** [comment]
I'll take a look at the messed up db shortly. 

From the "new" DB, here's what I'm seeing which would explain the error. 

![image](https://user-images.githubusercontent.com/3484775/86614842-9766bb00-bf81-11ea-99ad-3023aa66ac13.png)

**Comment by earlthesquirrel** [comment]
FYI -- for testing, I manually run wee_reports.  
It "was" working a few min ago, but now back to the odd behavior.  No errors.
Output says:
```
$ sudo wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
$
```

But no update to web pages.

**Comment by earlthesquirrel** [comment]
Hmm, ok so let me try deleting the DB again.
There also is an update to WeeWX-MQTTSubscribe plugin but I'll do these one at a time.

**Comment by earlthesquirrel** [comment]
Well, now I'm utterly confused.

The graphs are working now.... and I know for a fact they weren't on Thursday (last time I had time to work on this...

Does wee_reports cause archiving?  (maybe it just didn't have enough time yet on new DB??)  

I know I waited a long time (30 min or more) on Thursday... (and today I've had a couple times where the day temp shows N/A... so would that be caused by updated data but nothing matching temp in latest time window?

**Comment by poblabs** [comment]
Nope, wee_reports does not cause archiving, it just generates the enabled reports from weewx.conf. Some reports will use the archive_day_* tables, while others will use archive only. Depends on the report. 

I'm seeing the same problem in your messed up database. outTemp is null which would cause those errors you pasted above. 

Looks like this is a driver problem (drivers are responsible for providing loop data, then weewx does the archiving based on weewx.conf's archive_interval value).

![image](https://user-images.githubusercontent.com/3484775/86617062-b31f9080-bf84-11ea-9282-c578fc11f855.png)

**Comment by earlthesquirrel** [comment]
Ok, well time to update the MQTT driver anyway.   I've gone back to the "messed up" DB as that at least was generating reports.  I did tweak how fast I was sending data (every 30 sec now, was every 15).  Some of the data sources would intermittently timeout (I think too fast of a polling for it)   30 sec is more that fine.... and seems so far to be keeping up better.

Thanks for the pointers.

One last question -- I'm slowly understanding which sections the various example graphs have to go into to get them to show data correctly (part of mentally internalizing your roll up section of documentation )

However I've not quite figured out where [[avgclimatethisyear]] should be to show correctly.   It is showing data for Jan and Feb (which makes no sense).  I have it in the "year" section, is that correct?

**Comment by poblabs** [comment]
You can put any graph, into any "time span" section you want. There's a lot of flexibility. 

In terms of the average climate chart, sadlt the `xAxis_categories` is not smart enough to know when your database starts. So if you don't have a database that starts in January, you need to edit the categories. Then next year expand it to the full year. 

e.g. `xAxis_categories = 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'`

If you wish to show the yearly average climate in the `[day]` section of your graphs (like how I have on my site belchertownweather.com), this would be the stanza. Notice how `time_length` overrides the time for this specific graph only within the day group. 

```
[day]
    title = Today since Midnight
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000


    [[avgclimatethisyear]]
        title = "Average Climatological Values for This Year"
        type = spline
        time_length = year
        aggregate_type = max
        aggregate_interval = 86400 # 1 day
        gapsize = 86400000
        xAxis_groupby = month
        xAxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        [[[outTemp]]]
            zIndex = 2
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            zIndex = 2
        [[[rainTotal]]]
            name = Rain Total
            type = column
            yAxis = 1
            zIndex = 0
            color = "#268bd2"
```

**Comment by earlthesquirrel** [comment]
Ah! so that's the "why"... ok, gotcha, will edit categories.  Thanks!
