### ISSUE TITLE
NestingError after updating files to latest weewx version 

### ISSUE THREAD

**Issue by uajqq** [poblabs/weewx-belchertown#326]
I just did a routine update to keep my weewx up to date (commit `e8a5015`) and now I keep getting this error in the logs. It looks like it’s related to skin.conf but I can’t imagine how. I haven’t made any changes to that file and line 539 looks fine. The skin seems to run okay despite this. Any ideas how to clear this?

```
weewx[8708] DEBUG weewx.reportengine: Running report 'Belchertown'
weewx[8708] DEBUG weewx.reportengine: Found configuration file /Users/Shared/weewx/skins/Belchertown/skin.conf for report 'Belchertown'
weewx[8708] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
weewx[8708] ERROR weewx.reportengine:         ****  Section too nested at line 539.
weewx[8708] ERROR weewx.reportengine:         ****  Traceback (most recent call last):

weewx[8708] ERROR weewx.reportengine:         ****    File "/Users/Shared/weewx/bin/weewx/reportengine.py", line 196, in run

weewx[8708] ERROR weewx.reportengine:         ****      obj.start()

weewx[8708] ERROR weewx.reportengine:         ****    File "/Users/Shared/weewx/bin/weewx/reportengine.py", line 281, in start

weewx[8708] ERROR weewx.reportengine:         ****      self.run()

weewx[8708] ERROR weewx.reportengine:         ****    File "/Users/Shared/weewx/bin/weewx/cheetahgenerator.py", line 131, in run

weewx[8708] ERROR weewx.reportengine:         ****      gen_dict = deep_copy(self.skin_dict)

weewx[8708] ERROR weewx.reportengine:         ****    File "/Users/Shared/weewx/bin/weeutil/config.py", line 242, in deep_copy

weewx[8708] ERROR weewx.reportengine:         ****      interpolation=old_dict.interpolation)

weewx[8708] ERROR weewx.reportengine:         ****    File "/usr/local/lib/python3.7/site-packages/configobj.py", line 1229, in __init__

weewx[8708] ERROR weewx.reportengine:         ****      self._load(infile, configspec)

weewx[8708] ERROR weewx.reportengine:         ****    File "/usr/local/lib/python3.7/site-packages/configobj.py", line 1318, in _load

weewx[8708] ERROR weewx.reportengine:         ****      raise error

weewx[8708] ERROR weewx.reportengine:         ****    File "<string>", line None

weewx[8708] ERROR weewx.reportengine:         ****  configobj.NestingError: Section too nested at line 539.

weewx[8708] ERROR weewx.reportengine:         ****  Generator terminated
```

**Comment by poblabs** [comment]
hmm, I've never seen this error before with weewx or the skin. Let's try the obvious stuff; Do you have any duplicate files? Did you restart weewx?

Interesting how skin.conf claims to be affected. Try re-installing that file from the dev branch?

**Comment by uajqq** [comment]
Pulled the latest development version and copied the file over. Running `diff` reports no differences between the files. Stopped and restarted and still the same issue. No duplicate files anywhere that I can see.

**Comment by poblabs** [comment]
Did you make any changes to - or upgrade - weewx itself?

**Comment by uajqq** [comment]
I updated weewx to the latest commit on the master branch, `e8a5015`

**Comment by uajqq** [comment]
...but actually, looking at the earlier commits, I notice `6e052d1` made some changes to the same region that seems to be throwing the errors. That might be part of the problem

**Comment by uajqq** [comment]
Sure enough, I reverted to `a3dca5a` and the error went away. Looks like something in `6e052d1` is causing the issue.

**Comment by poblabs** [comment]
Is that a weewx commit or a belchertown?

**Comment by uajqq** [comment]
weewx

**Comment by poblabs** [comment]
Sounds like an issue with weewx and not the skin?

**Comment by poblabs** [comment]
Closing this. If it's still a problem let me know. Seems to be something with the latest unreleased weewx version though. The skin only supports the released versions currently.
