### ISSUE TITLE
Moon Icons

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#328]
Pat
Have just installed the latest development version (for Aeris Weather) and edited belchertown.js.tpl to change the icons to match my dark settings (#234).  I noticed two things.
1 line 513 for case 6. The icon is wi-moon-alt-first-quarter; I think it should be wi-moon-alt-third-quarter
2 line 498 for case 1. Not sure why it is moon-alt-waxing-crescent-1; shouldn't it be moon-alt-waxing-crescent-3 to match the other icons?
Michael

**Comment by ddperso** [comment]
I'm agree with Michael
If you remove "-alt" from the icon's name in belchertown.js.tmpl 
 you have a right display in normal and dark mode 
![dark](https://user-images.githubusercontent.com/65628453/87856746-6a22f100-c921-11ea-80ff-146eb2f1cbc9.jpg)
![white](https://user-images.githubusercontent.com/65628453/87856748-6abb8780-c921-11ea-9445-f656777f0f73.jpg)

**Comment by poblabs** [comment]
Fixed in the latest rc3 version of belchertown.js.tmpl! Thanks!

**Comment by ArendPWS** [comment]
> I'm agree with Michael
> If you remove "-alt" from the icon's name in belchertown.js.tmpl
> you have a right display in normal and dark mode

Also removed the 'alt' keyword from the icons (in both index.html.tmpl and belchertown.js.tmpl). At the moment we have full moon here, now it looks much better (if you only use dark theme ;-) ).
