### ISSUE TITLE
Hays Chart is missing a time slot value

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#330]
The time does not (always) appear in the 11o'clock position. See attached picture.
![Screen Shot 2020-07-10 at 10 39 24 AM](https://user-images.githubusercontent.com/1725001/87097689-d5255580-c299-11ea-88ab-f2743e0e8d3b.png)

**Comment by poblabs** [comment]
Your chart is also skewed a bit. Midnight should be at the top. Probably
needs a timezone adjustment. I'll look when I can

**Comment by 41south** [comment]
Oh, yeah, good spotting! As far as I can tell "now" (the current time) is at the top at 11:30 local time it looks like this;
![Screen Shot 2020-07-10 at 11 35 25 AM](https://user-images.githubusercontent.com/1725001/87100863-8aa7d700-c2a1-11ea-9414-73a09176da27.png)

**Comment by steepleian** [comment]
I think the current time should be in a fixed position (in this case at the
top) as it reflects how a Hays chart works in reality with a fixed pen
position.

[image: Untitled.png]

**Comment by poblabs** [comment]
Strange, I'm able to replicate your skewed chart from your site debug, but I'm not able to replicate it from setting my timezone. So maybe it's not timezone but something else unique? I'll keep digging

**Comment by 41south** [comment]
It comes right at some stage between then and now;

![Screen Shot 2020-07-10 at 1 05 00 PM](https://user-images.githubusercontent.com/1725001/87105094-19225580-c2ae-11ea-9260-ec9acd9a9465.png)

**Comment by 41south** [comment]
Fixed by adding the correct time_length = today into graphs.conf

[[chart6]]
   time_length = today
   title = Hays Chart
         [[[haysChart]]]
