### ISSUE TITLE
Windrose Missing Data

### ISSUE THREAD

**Issue by weswitt** [poblabs/weewx-belchertown#331]
I have added to my graphs.conf:

[[roseplt]]
   title = Wind Rose
   [[[windRose]]]

I see the windrose on the page but there is no data displayed in the graph.  There is in fact live wind data as it is displayed actively in the "wind speed & direction" graph.

Is there some other required configuration needed to make the windrose graph work?

**Comment by weswitt** [comment]
i also see that the "wind speed & direction" graph is missing direction plots.

i know that weewx is getting winddir values as i verified that my driver is sending winddir loop packets. also i can see at the top of the page (to the left of the sun & moon) that the winddir is correctly displayed.  seems like something weird happening with wind direction in the graphs.

**Comment by poblabs** [comment]
No, that should be all you need. 

```
    [[windrosechart]]
        title = Wind Rose
        legend = true
        [[[windRose]]]
```

If you're missing direction plots, then the wind rose won't work either. 

Can you attach your database?

**Comment by weswitt** [comment]
my database is mysql. in what form should i post the data?

**Comment by poblabs** [comment]
If you can do a mysqldump that'd be fine. Then zip the .sql file here and I'll re-create it.

**Comment by weswitt** [comment]
[weewx-sdb.zip](https://github.com/poblabs/weewx-belchertown/files/4927802/weewx-sdb.zip)

actually this is a test system and i'm just using sqllite. here is the db.

**Comment by poblabs** [comment]
Ok cool, - even easier. 

Verify your test system is getting all the wind data. Your wind direction is NULL (missing) in the database

![image](https://user-images.githubusercontent.com/3484775/87593343-4f4e4380-c6b9-11ea-8167-0686f30d8831.png)

**Comment by weswitt** [comment]
that is very odd. i added logging to the driver and i can clearly see that a loop packet for "windDir" is generated about every 2 seconds. wonder why weewx would be dropping the packets?  is that frequency too high?

**Comment by poblabs** [comment]
It shouldn't be. Stop the weewx service and run weewx directly using `weewxd`, and look for the `REC:` archive packet. That will show you everything written to the database. Also the LOOP will show you the LOOP packets that are received - regardless of your driver's logging. 

Closing this as it's not skin related at this time.
