### ISSUE TITLE
Pi refuses to go into Dark Mode

### ISSUE THREAD

**Issue by funnelcloudservices** [poblabs/weewx-belchertown#332]
Heya! 

I've been using the theme for a few years now, fantastic work sir.  

I'm trying to integrate the smaller "Pi" version into my home dashboard and it works fine but refuses to turn to "dark" mode no matter what I try.  I've added the trailing ?theme=dark  and no go. Tried adding pi_theme = dark in the weewx.conf, tried forcing dark globally and only the main site does it, tried different browsers.  Is there some way I can force it via html or css?
Any thoughts or suggestions?

https://bexleyweather.com/pi/index.html

**Comment by poblabs** [comment]
Looks like you're using an old version of the skin at version 1.0.1. The released version is 1.1 and the beta of 1.2 is in release candidate (to be released soon). 

In 1.1, the Pi page undertook a lot of work, and in 1.2 some bug fixes. 

I'd suggest upgrading to 1.1 at least or trying the 1.2 release candidate. 

Take a backup of your current weewx setup, then install the development zip file using wee_extension --install like normal. Restart weewx and see if that helps. 

There's a lot of changes in 1.2. If you're not comfortable with that, at least upgrade to the current 1.1 release.

**Comment by funnelcloudservices** [comment]
Ahhh, sweet. thank you.  yeah I haven't updated it since I installed it.  Good point.  I should have thought of that dead first.

**Comment by poblabs** [comment]
I'd say try [1.1 first ](https://github.com/poblabs/weewx-belchertown/releases/tag/weewx-belchertown-1.1 )since that's the released version - should be an easy upgrade. 1.2 beta has quite a few breaking changes if you're willing to give that a try.

**Comment by funnelcloudservices** [comment]
That did in fact fix it, thank you sir.  I tried 1.2 but you are right, too many things to debug.  1.1 will work for me for now.
