### ISSUE TITLE
Almanac not function Open/Close

### ISSUE THREAD

**Issue by pgpaolo** [poblabs/weewx-belchertown#333]
Hi Pat, can you show me how to solve the problem of the almanac that won't open. Thank you

**Comment by poblabs** [comment]
Please provide a link to your website

**Comment by James-76** [comment]
If you are using the development 1.2b6 set up I had found the almanac page would not stay open.

It turn out to be an issue where I hadn't installed one of the latest html.tmpl files 

James

**Comment by pgpaolo** [comment]
I am using the development version.
I modified the templates to customize the interface, and
with the original version of the files the almanac is ko
My link is:
http://meteostz05013.ddns.net/
GP

**Comment by poblabs** [comment]
Remove this from your footer.html.tmpl, it's loaded twice in your website and it only needs to be loaded once. 

`<script type='text/javascript' src='//stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js'></script>`
