### ISSUE TITLE
"More detail" Almana disappeared in 1.2rc2

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#334]
Hi Pat
I have installed rc2 and the "more details" in Sun & Moon window has disappeared...
![details](https://user-images.githubusercontent.com/65628453/87790073-463bae80-c840-11ea-8dd0-62b31f3fccf3.jpg)

**Comment by poblabs** [comment]
make sure you've updated all files and then restart weewx

**Comment by ddperso** [comment]
Hi Pat

It's OK now, I have forgotten to restart weewx!!
1.2rc2 works perfectly

Didier
