### ISSUE TITLE
Add Last rain and Beaufort in skin

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#335]
Hi

Is it possible to add 2 functionnalities in the skin:

- Display the time since last rain and last rain (group https://groups.google.com/g/weewx-user/c/fH5I6iwNFtE), may be in station_observations 1 line with the 2 values

- Display in wind windows the beaufort value (0 to 12) and beaufort description (calm, storm...) (group https://groups.google.com/g/weewx-user/c/0WcJWl7gpDU) 

I don't know if it is difficult or not, but it will be interesting.

Many thank's Pat for your nice skin

Didier

**Comment by FutureCow** [comment]
@ddperso 

If you add this to skins/Belchertown/js/belchertown.js.tmpl:

`    // Beaufort METRICWX
    if ( data.hasOwnProperty("windSpeed_kph") ) {
        jQuery(".curbeaufort").html( parseFloat(parseFloat(data["beaufort_count"])).toLocaleString("$system_locale_js", {minimumFractionDigits: 0, maximumFractionDigits: 0}) );
    }`
You can use something like: $current.beaufort.toString in you pages to add the beaufort (only from 0-12 scale)

**Comment by poblabs** [comment]
Great solution! I'll close this out, thanks @FutureCow !
