### ISSUE TITLE
Dark Sky API Keys No Longer Available

### ISSUE THREAD

**Issue by ishelly404** [poblabs/weewx-belchertown#336]
Since being acquired by Apple, Dark Sky is no longer allowing new API signups since July 1 and is discontinuing the API in 2021.

https://blog.darksky.net/

Would it be possible to implement a different weather service?

Thanks,
Ian

**Comment by poblabs** [comment]
Yes the development branch uses Aeris Weather.

**Comment by ishelly404** [comment]
Thanks, I didn't realize that.
