### ISSUE TITLE
3 hourly forecast request

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#338]
In the temperate climate zone where I live in the UK, the weather frequently varies throughout the day.  It would be really useful if there could be a 3 hourly forecast to complement the current daily one (from aeris in the development version).  
I have just tried with a demo project that has given me 7 readings at 3 -hourly intervals that would nicely fit with the current 7 day forecast appearance-wise.  The current detail and symbols used for the 7 day forecast would be sufficient.
Perhaps extras could be extended to allow a choice of either 3-hourly or daily forecasts or both?
Is it possible? What does anyone think?

**Comment by poblabs** [comment]
Do you have the link on Aeris on where you can get the 3 hour forecast?

**Comment by FutureCow** [comment]
If you add /forecasts/seattle,wa?**filter=3hr**&limit=8& to your API call you will receive a 3-hour interval forecast

**Comment by michaelundwd** [comment]
Pat
Knowing you have been busy recently, I have been experimenting with a 3-hour (and 1-hour forecast).  You can see the preliminary results at lordshipweather.uk/hourly.  Work is still needed on the selection mechanism to show only one at a time, and you will see I have broken the formatting of the daily forecast.  
When I started Aeris were not doing a 1 hour forecast, so I used openweather, but they are now - shucks.  I will now the code to  use Aeris for the 1 hour too.  
It has taken me a lot of time to get this far, but then I have had to learn a lot of new tricks!  Will happily do a PR when it's a bit more stable.
Have made some related minor icon changes that I'll raise separately.
Michael

**Comment by poblabs** [comment]
@michaelundwd Interesting implementation! I like it! PR welcome! My only suggestion is the menu on the right of the forecast bar - I didn't realize that was a menu to flip between the 3 timescales. I wonder if we need to put a bullet or something in front of the word to make it a little more defined and separated?

**Comment by michaelundwd** [comment]
I quite agree. I wanted to make the menu a set of items like those in the header, but my HTML/CSS is not up to it!  I've waste more time on that than sorting the underlying code.
I'll do a PR when I have got the Aeris 1 hour forecast sorted and then we can address the selection mechanism.

**Comment by michaelundwd** [comment]
I now have now got a robust working version using aeris for 1, 3 and 24 hour forecast intervals that you can see at lordshipweather.uk/hourly.  There are three things outstanding.
1  It needs bringing up to 1.2 as I am still on1.2rc2.
2  I got rid of any darksky forecast code to make my life simple, so that needs re-introducing and the forecast code put into a maintainable state. More easily done if I upgrade to 1.2 first.
3  I have not addressed responsive mode issues yet.

I'm happy to do a PR or share the files.  Would you like me to go to 1.2 first?
I can't find a development branch to PR, only the master.
Michael

**Comment by poblabs** [comment]
Awesome! 

Version 1.3 will drop DarkSky so don't worry about that. 

You can do a PR against master for now - the official release for 1.2 won't change

**Comment by michaelundwd** [comment]
Thanks for the update on DarkSky.  I'll upgrade to 1.2, and then do a PR on the master.  It might be a couple of weeks before you see it.

**Comment by fvirgola80** [comment]
Good morning,
I'm new I introduce myself.
My name is Francesco and I just installed the fantastic new Belchertown skyn. I haven't set it as main for my site yet but this is the result https://www.meteocivitavecchia.it/weewx/belchertown/
I would say fantastic !!!
I'm curious how to add the forecast to 1 hour 3 hours and 24 as in http://lordshipweather.uk/hourly/
I have installed the 1.2 version of the skyn.
Could I have some help from you?
Thanks a lot and congratulations for the skyn

**Comment by fvirgola80** [comment]
I forgot .... when displaying the visibility sometimes I get this undefined instead of KM
Depends on what?
thanks a lot

**Comment by michaelundwd** [comment]
Hi Francesco
I'm working on getting the code aligned with release 1.2 and fully translatable and then there will be a pull request available.  It will be up to Pat whether to make it part of release 1.3.
Regards
Michael
http://lordshipweather.uk

**Comment by ChrisM510** [comment]
@michaelundwd  I am a total noob when it comes to github.  How can I take advantage of the changes you have made to get the 1/3/24 options for the forecast?  I upgraded to v1.2, but I don't understand how to get the changes you have made.  Thanks in advance!

**Comment by michaelundwd** [comment]
@ChrisM510 
I'm still testing with different locales, so I haven't issued the pull request for the changes yet.  When that happens you should be able to install the changes as it is based on release 1.2.  Not too long to wait I hope.
Michael

**Comment by michaelundwd** [comment]
Am closing this as 1hr and 3hr interval forecasts have now been merged into the master with #455
