### ISSUE TITLE
Windrose chart not showing

### ISSUE THREAD

**Issue by europacafe** [poblabs/weewx-belchertown#339]
I've just installed the latest version. Several months ago, I installed this skin on another Ubuntu 18.04. The windRose graph showed up when I add the windrose in the graphs.conf. Now I have another server running ubuntu 20.04, the skin is working fine, but when adding windRose graph in graphs.conf, it won't show up. I even tried copying that section of setup code from the working server. It still now show up.

**Comment by poblabs** [comment]
Whats the link to your site? Do you have wind data showing in the wind speed chart?

**Comment by europacafe** [comment]
Hi Pat,
It is still a local ip site for testing. It does have wind speed/direction data shown on the standard wind chart.

**Comment by poblabs** [comment]
I'm not sure I'll be able to help much since it's local. Check your syslog for errors, and try the [debug section](https://github.com/poblabs/weewx-belchertown/tree/development#how-to-use-debug) for any errors or hints. Also try to reinstall the skin making sure you have updated all files.

**Comment by europacafe** [comment]
Here is what displayed in syslog (still debug = 0):
`Jul 23 08:15:33 bthoven-3020M weewx[131052] INFO weewx.restx: MQTT: Published record 2020-07-23 08:15:00 +07 (1595466900)
Jul 23 08:15:33 bthoven-3020M weewx[131052] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.27 seconds
Jul 23 08:15:33 bthoven-3020M weewx[131052] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.16 seconds
Jul 23 08:15:33 bthoven-3020M weewx[131052] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Parsing failed with several errors.#012First error at line 71.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      obj.start()
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      self.run()
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 308, in generate
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      searchList = self._getSearchList(encoding, timespan,
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 208, in get_extension_list
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      chart_dict = configobj.ConfigObj(chart_config_path, file_error=True)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj.py", line 1229, in __init__
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      self._load(infile, configspec)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj.py", line 1318, in _load
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      raise error
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "<string>", line None
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  configobj.ConfigObjError: Parsing failed with several errors.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  First error at line 71.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Generator terminated
Jul 23 08:15:33 bthoven-3020M weewx[131052] INFO weewx.reportengine: Copied 2 files to /var/www/html/weewx/belchertown
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Parsing failed with several errors.#012First error at line 71.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      obj.start()
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      self.run()
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1050, in run
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      self.chart_dict = configobj.ConfigObj(chart_config_path, file_error=True)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj.py", line 1229, in __init__
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      self._load(infile, configspec)
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj.py", line 1318, in _load
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****      raise error
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****    File "<string>", line None
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  configobj.ConfigObjError: Parsing failed with several errors.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  First error at line 71.
Jul 23 08:15:33 bthoven-3020M weewx[131052] ERROR weewx.reportengine:         ****  Generator terminated
Jul 23 08:15:36 bthoven-3020M weewx[131052] INFO weewx.restx: MQTT: Published record 2020-07-23 08:15:20 +07 (1595466920)
Jul 23 08:15:39 bthoven-3020M weewx[131052] INFO weewx.restx: MQTT: Published record 2020-07-23 08:15:23 +07 (1595466923)
Jul 23 08:15:42 bthoven-3020M weewx[131052] INFO weewx.restx: MQTT: Published record 2020-07-23 08:15:26 +07 (1595466926)`

**Comment by europacafe** [comment]
With debug on
![image](https://user-images.githubusercontent.com/51871976/88246153-e02dac00-ccc3-11ea-93fe-f37b5c919474.png)

**Comment by Bug-Storm** [comment]
Hey, you need reinstall weewx and after belchertown 😉.. . I has same problem today that you 😎

**Comment by europacafe** [comment]
You mean installing the same latest version I already installed?

**Comment by Bug-Storm** [comment]
Yes ;) 

You are sure add this "
` [[chart5]]
    title = windrose
    [[[windRose]]]
        beauford0 = “#1278c8
        beauford1 = “#1fafdd
        beauford2 = “#71bc3c
        beauford3 = “#ffae00
        beauford4 = “#ff7f00
        beauford5 = “#ff4500
        beauford6 = “#9f00c5`

on Graphs.conf ??

**Comment by europacafe** [comment]
Yes, I added windRose in the graphs.conf; but it never showed up.

**Comment by Bug-Storm** [comment]
Maybe you have problems with the sdb... We needs know with what type data we need for create the windrose

**Comment by europacafe** [comment]
The problem has been solved by starting over the graphs.conf again from the graph template and adding windRose again. I may have done something wrong earlier. Thanks for every one for taking time to help.

**Comment by europacafe** [comment]
The problem has been solved by starting over the graphs.conf again from the graph template and adding windRose again. I may have done something wrong earlier. Thanks for every one for taking time to help.
