### ISSUE TITLE
2019 bug?

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#34]
Morning Pat, Happy New Year from NZ

I awoke to find this problem this morning. The charts/graphs look to be ok

Jan  1 10:55:29 raspberrypi weewx[9736]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****  'NoneType' object has no attribute '__getitem__'
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****  Traceback (most recent call last):
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      obj.start()
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      self.run()
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      default_binding)
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****    File "/usr/share/weewx/user/belchertown.py", line 297, in get_extension_list
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****      year_rainiest_month_tuple = (year_rainiest_month_query[1], rain_unit, 'group_rain')
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****  TypeError: 'NoneType' object has no attribute '__getitem__'
Jan  1 10:55:29 raspberrypi weewx[9736]:         ****  Generator terminated

The NOAA reports haven't generated and all the records for year/month/day seem to have stopped generating. MQTT data is ok I think

![screen shot 2019-01-01 at 10 53 45 am](https://user-images.githubusercontent.com/1725001/50568304-bbf23d80-0db4-11e9-94e6-2cdf8b704a5b.png)
![screen shot 2019-01-01 at 10 54 21 am](https://user-images.githubusercontent.com/1725001/50568305-bc8ad400-0db4-11e9-9efb-4d246fcc56aa.png)

**Comment by 41south** [comment]
Just an updated shot showing MQTT sorted (the server stopped too!) but current conditions icon still thinks it's night and record snapshots still in Dec.
![screen shot 2019-01-01 at 11 04 45 am](https://user-images.githubusercontent.com/1725001/50568345-43d84780-0db5-11e9-8b06-531f9f250d4b.png)

**Comment by monts351** [comment]
Hi Pat, been using this skin for a couple of weeks now, since getting a weather station. Really like your work. I've also got the 2019 error, although I don't use the MQTT side of things. my site is at https://weather.emkubed.com.au and is stuck at 11:55pm on the 31st of Dec.

Have checked and data is still being saved into the database.

pi@raspberrypi:~ $ sudo wee_reports 
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 297, in get_extension_list
    year_rainiest_month_tuple = (year_rainiest_month_query[1], rain_unit, 'group_rain')
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 297, in get_extension_list
    year_rainiest_month_tuple = (year_rainiest_month_query[1], rain_unit, 'group_rain')
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by poblabs** [comment]
This is a weird one. Let me see if I can fix it ASAP

**Comment by poblabs** [comment]
Would one of you guys be able to send me your database? Once I add mine to a test 2019 machine it adds rain to it (since it's raining right now). Yours are failing because (assuming) you have no rain yet in 2019

**Comment by 41south** [comment]
Done, hopefully

**Comment by poblabs** [comment]
Got it, thanks.

**Comment by sgrayban** [comment]
Eagerly waiting for git commit !! Although I have about 5 hours before the bug hits me....

**Comment by 41south** [comment]
Looks like the same/similar error, I only replaced the belchertown.py file

Jan  1 15:40:32 raspberrypi weewx[6484]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Jan  1 15:40:32 raspberrypi weewx[6484]:         ****  'forecast_alert_enabled'
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****  Traceback (most recent call last):
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      obj.start()
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      self.run()
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      default_binding)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/share/weewx/user/belchertown.py", line 469, in get_extension_list
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      forecast_alert_enabled = int( self.generator.skin_dict['Extras']['forecast_alert_enabled'] )
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****    File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****      val = dict.__getitem__(self, key)
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****  KeyError: 'forecast_alert_enabled'
Jan  1 15:40:33 raspberrypi weewx[6484]:         ****  Generator terminated
Jan  1 15:40:33 raspberrypi weewx[6484]: copygenerator: copied 22 files to /var/www/html/weewx/belchertown

**Comment by poblabs** [comment]
Different bug now that I fixed within the last few minutes. Let me email you an update for a test.

**Comment by 41south** [comment]
Tested and looks good

**Comment by poblabs** [comment]
Thanks for the testing! 

For those looking for the fix, [grab an updated copy of the `bin/user/belchertown.py` file](https://raw.githubusercontent.com/poblabs/weewx-belchertown/master/bin/user/belchertown.py) and place it into your `bin/user` folder and restart weewx.
