### ISSUE TITLE
Bug of Highcharts Barometer 

### ISSUE THREAD

**Issue by Bug-Storm** [poblabs/weewx-belchertown#340]
Hey Guys :) 

I've Belchertown v1.1 and weewx 4.1.1 

I've bug of the highcharts barometer

i've "`1&#8239;019` on highcharts , Because I don't know.

![chrome_VvPeP6Nwm2](https://user-images.githubusercontent.com/68688876/88275034-f8f68b80-ccdc-11ea-8b41-878c67b32856.png)

**Comment by Bug-Storm** [comment]
```
[[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"
            [[[[numberFormat]]]]
                decimalPoint = "."
                thousandsSep = "" 
```


Now it's ok , surely a bug on  
`  [[[[numberFormat]]]]
                decimalPoint = "."
                thousandsSep = "" `

**Comment by norecords** [comment]
thanks @Bug-Storm I had the same problem. It's happened only with METRIC barometer's datas.
I think you should reopen this issue.
