### ISSUE TITLE
2 small problems in last development skin

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#341]
Hi Pat
2 small problems:

- horizontal line too short between temp and wind windows (see snapshot)
- vertical line too short in case of no recent earthquake (see snaphot)
![ligne1](https://user-images.githubusercontent.com/65628453/88294228-4a624300-ccfc-11ea-9a21-88803b98e5ad.jpg)
![ligne2](https://user-images.githubusercontent.com/65628453/88294231-4afad980-ccfc-11ea-921f-ac69cfb709b1.jpg)

**Comment by poblabs** [comment]
Give the latest style.css file a try

**Comment by ddperso** [comment]
Thank's Pat
It's OK now with the new css file
