### ISSUE TITLE
MQTT units "undefined"

### ISSUE THREAD

**Issue by arnebjarne** [poblabs/weewx-belchertown#342]
Hi Pat.

I am having problems getting unit labels via MQTT to show up right on the page.
(without MQTT everything is ok)
![undefined](https://user-images.githubusercontent.com/833291/88483094-f195e300-cf65-11ea-837c-dcceb9b58b83.png)

MQTT data comming in are ie:

`
{"cloudbase_meter": "240.317076196", "outHumidity": "90.0", "pressure_mbar": "1003.55855756", "rain_cm": "0.0", "barometer_mbar": "1007.1", "rainRate_mm_per_hour": "0.0",.........
`

it looks like its around the code
./js/belchertown.js
`            // If this MQTT payload key begins with the name of the span class name, update the info. Can also use mqttdata.includes(thisElementClass) if weewx-mqtt changes in future
            if ( mqttdata.startsWith(thisElementClass) ) {
                html_output = parseFloat(parseFloat(data[mqttdata])).toLocaleString("en-US", {minimumFractionDigits: unit_rounding_array[thisElementClass], maximumFractionDigits: unit_rounding_array[thisElementClass], useGrouping: localeStringUseGrouping}) + unit_label_array[thisElementClass];`

and

`
function ajaxweewx() {
    // Relative URL
    jQuery.getJSON(get_relative_url() + "/json/weewx_data.json", update_weewx_data);
};

// Update weewx data elements
//var station_obs_array = "";
var unit_rounding_array = "";
var unit_label_array = "";
function update_weewx_data( data ) {
    belchertown_debug("Updating weewx data");
    
    // Check for updates
    var update_available = check_for_updates("1.1", data["version"]["github_version"]);
    belchertown_debug("Checking Update: update available: " + update_available + " (installed: 1.1 - new version: "+data["version"]["github_version"]+")");
    if ( update_available ) {
        jQuery(".updateavailable").show();
    }
    
    
    //station_obs_array = data["station_observations"];
    unit_rounding_array = data["unit_rounding"];
    unit_label_array = data["unit_label"];
`

HTML inspection of the code says
`<span class="barometer">1007.5undefined</span>`

and inspecting json/weews_data.json says

`
json/weewx_data.json:    "unit_label": {"ET": " mm", "visibility": "", "UV": "", "altimeter": " mbar", "altitude": " meters", "appTemp": " \u00b0C", "barometer": " mbar", "beaufort": "", "cloudbase": " meters",
`

so mbar should be defined for barometer.

Any idea why it fails

BR,
Bjarne

**Comment by Bug-Storm** [comment]
Looking on skin.conf [https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/skin.conf](url)
![chrome_e2B825xE6O](https://user-images.githubusercontent.com/68688876/88538441-a9cb9600-d00f-11ea-8df8-748e6ae4c9fd.png)
 
If you have the correct units

**Comment by arnebjarne** [comment]
I have these settings (since i wanted metrics)

`    [[Defaults]]

        [[[Units]]]

            # The following section sets what unit to use for each unit group.
            # NB: The unit is always in the singular. I.e., 'mile_per_hour',
            # NOT 'miles_per_hour'
            [[[[Groups]]]]

                group_altitude = meter    # Options are 'foot' or 'meter'
                group_degree_day = degree_C_day    # Options are 'degree_F_day' or 'degree_C_day'
                group_pressure = mbar    # Options are 'inHg', 'mmHg', 'mbar', or 'hPa'
                group_rain = mm    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = mm_per_hour    # Options are 'inch_per_hour', 'cm_per_hour', or 'mm_per_hour'
                group_speed = meter_per_second    # Options are 'mile_per_hour', 'km_per_hour', 'knot', or 'meter_per_second'
                group_speed2 = meter_per_second2    # Options are 'mile_per_hour2', 'km_per_hour2', 'knot2', or 'meter_per_second2'
                group_temperature = degree_C    # Options are 'degree_F' or 'degree_C'
`

and that is why the static page is OK.
See
![IMG_0282](https://user-images.githubusercontent.com/833291/88696012-fba11880-d102-11ea-89d4-9a3f112e58f1.PNG)
versus
![IMG_0283](https://user-images.githubusercontent.com/833291/88696031-00fe6300-d103-11ea-9622-12dc2109e3ec.PNG)

First picture is the static page before MQTT kicks in. Second picture is when MQTT data is beeing used.

I am not a java script programmer (but I can code python,perl,php,C) so I will try to add some debug code that dumps the content of

data["unit_label"];

I thinks this is where the problem is. Maybe the browsers (both Safari on my iPad or Firefox on my Windows cannot read /json/weewx_data.json for some reason.

**Comment by poblabs** [comment]
What's the link to your site? I'll take a look when I have some time in the
next day or so.

**Comment by poblabs** [comment]
Please also refer to the FAQ about mqtt units. Bullet item #2

https://github.com/poblabs/weewx-belchertown/tree/development#frequently-asked-questions

**Comment by arnebjarne** [comment]
The URL for my weather station is: [https://www.saltbaek.dk/weewx/reports/](https://www.saltbaek.dk/weewx/reports/)

**Comment by Bug-Storm** [comment]
Try install mqtt explorer and connect on your server "MS" and look what data you received 😉

**Comment by arnebjarne** [comment]
I wrote that in the first comment:

"MQTT data comming in are ie:

{"cloudbase_meter": "240.317076196", "outHumidity": "90.0", "pressure_mbar": "1003.55855756", "rain_cm": "0.0", "barometer_mbar": "1007.1", "rainRate_mm_per_hour": "0.0",.........

That looks ok to me ???

I added:

`    belchertown_debug("unit_label = " + data["unit_label"]);`

to the
function update_weewx_data

it does not show up in the firefox console when I access
https://www.saltbaek.dk/weewx/reports/?debug=true
(other debug statements do show. Is the update_weewx_data function used in code???

**Comment by arnebjarne** [comment]
and using debug shows MQTT data as well:

(prettyfied)
"MQTT":{
   "cloudbase_meter":"887.027806311",
   "outHumidity":"64.0",
   "pressure_mbar":"1002.66318254",
   "rain_cm":"0.0",
   "barometer_mbar":"1006.2",
   "rainRate_mm_per_hour":"0.0",
   "dewpoint_C":"10.3",
   "rainTotal":"2.69698",
   "rainBatteryStatus":"0.0",
   "forecast":"4.0",
   "uvLinkStatus":"1.0",
   "windGust_kph":"0.625856000501",
   "heatindex_C":"17.2",
   "outLinkStatus":"1.0",
   "inDewpoint_C":"12.1186104166",
   "outTempBatteryStatus":"0.0",
   "dayRain_mm":"2.6",
   "extraLinkStatus1":"0.0",
   "extraLinkStatus2":"1.0",
   "extraLinkStatus3":"1.0",
   "extraLinkStatus4":"1.0",
   "storm":"0.0",
   "windchill_C":"16.4",
   "altimeter_mbar":"1006.33215106",
   "appTemp_C":"17.0220995627",
   "outTemp_C":"17.2",
   "maxSolarRad_Wpm2":"10.1302456167",
   "humidex_C":"18.6306556821",
   "rain24_cm":"0.26312",
   "rainLinkStatus":"0.0",
   "extraHumid1":"64.0",
   "hourRain_cm":"0.0",
   "inTemp_C":"24.15",
   "windSpeed_kph":"0.447040000358",
   "usUnits":"16.0",
   "windLinkStatus":"0.0",
   "extraBatteryStatus2":"0.0",
   "extraBatteryStatus3":"0.0",
   "windBatteryStatus":"1.0",
   "extraBatteryStatus1":"0.0",
   "extraBatteryStatus4":"0.0",
   "extraTemp1_C":"17.2",
   "windDir":"67.5",
   "inHumidity":"47.0",
   "uvBatteryStatus":"0.0",
   "dateTime":"1595961511.0"
}

**Comment by arnebjarne** [comment]
Yayh. found the problem (not the solution)

if I change:
`    jQuery.getJSON("/json/weewx_data.json", update_weewx_data);`
to
`   jQuery.getJSON("https://www.saltbaek.dk/weewx/reports/json/weewx_data.json", update_weewx_data);`

it works!

I cannot say if its the security settings in the Apache package in the Synology package (Synology do harden Apache more than default...).

Is there anything to do about this?

**Comment by Bug-Storm** [comment]
Try open index.htlm of weewx and look if you have errors

**Comment by arnebjarne** [comment]
Weird

if i open https://www.saltbaek.dk/weewx/reports/index.html?debug=true
then it works

URL: Relative URL is: .
json to load = ./json/weewx_data.json

but if i open https://www.saltbaek.dk/weewx/reports/?debug=true
gives wrong get_relative_url() result.
maybe "working as expected" but annoying :-/

**Comment by arnebjarne** [comment]
ah. you have your own function

`function get_relative_url() {
    var sPath = window.location.pathname.replace(/\/$/, "");
    var pageName = sPath.substring(sPath.lastIndexOf('/') + 1);
    if ( pages.includes( pageName ) ) {
        var relative_url = "..";
    } else {
        var relative_url = ".";
    }
    belchertown_debug("URL: Relative URL is: " + relative_url);

    return relative_url;
}
`

**Comment by poblabs** [comment]
Interesting. You might be the first person to run this in a 2 level subdirectory (most use weewx or belchertown). I'll need to think about how to support that

**Comment by arnebjarne** [comment]
Sorry to break your code :-D

I'll do a temporary hack in
/etc/weewx/skins/Belchertown/js/belchertown.js.tmpl and set the URL without get_relative_url()

**Comment by poblabs** [comment]
In version 1.0 and previous, there was an option `belchertown_root_url` where you can specify your root URL. In your case that would be https://www.saltbaek.dk/weewx/reports/. 

I wonder if I should add that option back as a non-required option and within get_relative_url() check if it's defined and use that. If it's undefined then use the `relative_url` dots.

I'll play with that in the development branch over the next couple of days

**Comment by arnebjarne** [comment]
What might be handy.
My setup is:
A Raspberry Pi connected to the weather status with USB.
For security reasons I do not want the RPI exposed to the Internet (yeah, just call me a crazy old man), so I use the FTP copy in weewx to FTP the static Belchertown pages from the RPI to my Synology NAS's webserver (which I trust :D) and expose the Belchertown pages on my NAS's public webserver to the Internet

So from my point of view having your Belchertown skin to work 100% relative is optimal. In that way I can access the RPI locally on its own webserver if i want (i rarely do, only in case of debugging, I use my NAS from home or from the Internet).

**Comment by arnebjarne** [comment]
I have upgraded from v1.1 to v1.3 and now hit the same error again

Failed to load resource: the server responded with a status of 404 ()
/weewx/json/weewx_data.json:1  

where the correct URL should be /weewx/reports/json/weewx_data.json

I will redo the same hack again. Annoying though :)
