### ISSUE TITLE
Websockets Client Port

### ISSUE THREAD

**Issue by weswitt** [poblabs/weewx-belchertown#343]
I have a question about the MQTT WebSockets connection.

I have this configured and working fine on my home network.  Outside of my home the Belchertown skin cannot connect back to my MQTT server running on my home network.  I opened up port 9001 through my router's firewall but that does not seem to be enough.

In looking at the established connections when using this from within my home network I see this:

mosquitto  937            root   18u  IPv4  50598      0t0  TCP 192.168.1.176:9001->192.168.1.128:39890 (ESTABLISHED)

This tells me that the web client (Belchertown) is using a random port other than the 9001 port that Mosquitto is using.  What ports do I need to open up for this to work?

Thanks.

**Comment by poblabs** [comment]
9001 is all you need. Other high ports may be randomly assigned as with a lot of TCP connections. 

Did you change your `mqtt_websockets_host` for your home IP (and not 192.168.0.25)? If you're external, your client won't know what 192.168.1.128 is.

**Comment by weswitt** [comment]
yes:

mqtt_websockets_enabled = 1
mqtt_websockets_host = "192.168.1.176"
mqtt_websockets_port = 9001
mqtt_websockets_ssl = 0
mqtt_websockets_topic = "weather/weewx/loop"

192.168.1.128 is the ip address of the client (my phone in this case)

My router has port 9001 mapped appropriately.  In looking at my router's logfile i do not even see any connection attempts for port 9001

**Comment by poblabs** [comment]
So to confirm, your phone is off wifi, and you're "not home", but you want to check your weather station at home?

If so, you'll need to change `mqtt_websockets_host` to your public IP and not an internal IP for public devices (e.g. your phone off wifi) to access it

**Comment by weswitt** [comment]
awesome! that fixed it. i actually used my domain name for the mqtt_websockets_host and now it works everywhere. thanks for the help.

**Comment by poblabs** [comment]
Great news!
