### ISSUE TITLE
Live stats stop working

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#344]
Please see https://groups.google.com/forum/#!topic/weewx-user/Xx6MujRdpwg for the OP.

Basically jquery is crashing now when accessing the websocket url. It was working for years and just recently stopped working. I can connect to it via MQTTBox and subscribe to weather/weewx/loop topic and I see the data being sent.

Has something changed? I'm not the only one having this issue.

**Comment by poblabs** [comment]
> Has something changed?

I'm not sure based on the info you've provided here and on the forums.

1, Whats the version your site is running? 
2. Whats the URL to your site?
3. Are you using a self hosted mqtt broker? (Note: I am, and not having the problem identified)
4. If so, which broker?
5. What's [debug mode](https://github.com/poblabs/weewx-belchertown/tree/development#how-to-use-debug) show you for errors?

**Comment by sgrayban** [comment]
- Weewx 3.9.2
- http://www.nettletondistrict.com/Nettleton/
- Self hosted on a pi

Jul 28 13:28:49 weewx-pi weewx[31131]: restx: MQTT: service version is 0.18
Jul 28 13:28:49 weewx-pi weewx[31131]: restx: MQTT: binding to ['archive', 'loop']
Jul 28 13:28:49 weewx-pi weewx[31131]: restx: MQTT: topic is weather/weewx
Jul 28 13:28:49 weewx-pi weewx[31131]: restx: MQTT: desired unit system is US
Jul 28 13:28:49 weewx-pi weewx[31131]: restx: MQTT: data will be uploaded to mqtt://weewx:xxx@63.230.134.165:1883/
Jul 28 13:28:49 weewx-pi weewx[31131]: engine: Finished loading service user.mqtt.MQTT

**Comment by sgrayban** [comment]
MQTT debug shows this.

1595969173: Sending CONNACK to 1a3d7632-1e97-4bcc-9788-122069e85d3c (0, 0)
1595969173: Received PUBLISH from 1a3d7632-1e97-4bcc-9788-122069e85d3c (d0, q0, r0, m0, 'weather/weewx/loop', ... (656 bytes))
1595969173: Received DISCONNECT from 1a3d7632-1e97-4bcc-9788-122069e85d3c

**Comment by sgrayban** [comment]
When I connect with MQTTBox I see the subscription

1595969603: Received SUBSCRIBE from a74d0b5d-2384-4df2-9da0-903ec2bff4b11595969404481
1595969603:     weather/weewx/loop (QoS 0)

I'm not sure while loading the website I should get the same thing

**Comment by poblabs** [comment]
What about the belchertown debug?

**Comment by sgrayban** [comment]
I'm not sure what you need from the weewx logs for that.

**Comment by poblabs** [comment]
Please check out the debug section I linked. It's not a weewx.conf thing.

**Comment by sgrayban** [comment]
hmm not getting any debug info

**Comment by sgrayban** [comment]
All I can find is this

Connection closed before receiving a handshake response

**Comment by poblabs** [comment]
You're on version 0.9rc1, a lot has changed including newer MQTT libraries in 1.1 the latest release. I would advise to upgrade to the latest supported release.

**Comment by sgrayban** [comment]
I just upgraded and enabled debug
http://www.nettletondistrict.com/Spokane/?debug=true

The error I see is this...

mqttws31.min.js:36 WebSocket connection to 'ws://63.230.134.165:9001/mqtt' failed: Connection closed before receiving a handshake response
k._doConnect	@	mqttws31.min.js:36
k.connect	@	mqttws31.min.js:31
I.connect	@	mqttws31.min.js:65
connect	@	belchertown.js?1595980701:700
(anonymous)	@	?debug=true:159
l	@	jquery.min.js:2
c	@	jquery.min.js:2

**Comment by poblabs** [comment]
Interesting. I'm getting this and it's working fine for me in Chrome. 

```
MQTT: MQTT Connected. Subscribing.
```

![image](https://user-images.githubusercontent.com/3484775/88741565-fc8b7780-d10d-11ea-916e-dd816d4753ea.png)

**Comment by sgrayban** [comment]
wtf ??

**Comment by poblabs** [comment]
I have no idea - Try incognito mode, or clear your cache/cookies?

**Comment by poblabs** [comment]
Firefox worked for me as well

![image](https://user-images.githubusercontent.com/3484775/88741919-cef2fe00-d10e-11ea-8615-01d9466ee489.png)

**Comment by sgrayban** [comment]
How strange -- it just started happening on my end a few weeks ago and never had to use a incognito window

**Comment by poblabs** [comment]
Is it working in incognito? If so then maybe clear your cache and cookies?

**Comment by sgrayban** [comment]
Must have been a few things as I cleared all my cookies and browser data and its working now.... very strange
