### ISSUE TITLE
Darksky API ends in 4 days

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#345]
Darksky API to end Aug 1, 2020 -- https://blog.darksky.net/

Any plans to make a change to something else?

**Comment by poblabs** [comment]
Yes, the [1.2 version in the development branch](https://github.com/poblabs/weewx-belchertown/tree/development) supports Aeris Weather (requires you to upload your weewx data to pwsweather for a free Aeris account). The release candidate is pretty rock solid so far. Details are in the readme of the development branch

**Comment by sgrayban** [comment]
Hmm I see where you can signup but not how to get the free API at... All I see a subscription required.

**Comment by sgrayban** [comment]
nm -- finally found it via bunch of hidden links
