### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#346]
On my old site I hacked in code to support extra pages. For instance I create a page for my weather cam to be displayed. Is it easier to do this now or do I have to go in a hack the code each time I update your skin ?

**Comment by poblabs** [comment]
I haven't been able to think of a way to make it easy to add pages because of the number of dependencies that weewx has on the skin. It's something I think about frequently though!

**Comment by sgrayban** [comment]
I hacked mine in and it works. Maybe a HOWTO on it might be a good solution at least? I could write up the steps I took.

**Comment by poblabs** [comment]
The steps you use could be helpful for others if you want to write it up
I'll add it to the wiki

**Comment by sgrayban** [comment]
Ok I'll do that up tonight or tomorrow. Users will need to remember that some of those step will be over written when/if they upgrade your theme..

Maybe when you read my steps you will just incorporate those into the theme. I used my extra page to show my weather camera video/image.
