### ISSUE TITLE
Translate Alert_ effect DarkSky 

### ISSUE THREAD

**Issue by Bug-Storm** [poblabs/weewx-belchertown#347]
Hello Guys , it's problem translate Alert _effect of DarkSky ? Thanks 

![chrome_8IaFAnrAR4](https://user-images.githubusercontent.com/68688876/88821661-3cf8fd00-d1c3-11ea-8fd7-f95b7fa5922e.png)

**Comment by poblabs** [comment]
Duplicate of #352, closing. See updates there
