### ISSUE TITLE
No graphs or reports

### ISSUE THREAD

**Issue by GaRyu** [poblabs/weewx-belchertown#348]
Hey, I pulled the zip-file for development build and installed it just fine. Running weewx 4.1.1 and Belchertown 1.2rc2. I am running weewx on a Raspberry Pi with Raspbian.

I cannot get any graphs to show, neither are any reports visible on click. However, the reports are generated, there are links to each month with data and the text files are in the NOAA folder, they just don't show on the Reports page when clicked. Similarly, graphs should be working; there are no errors in debug mode (except "A Geolocation request can only be fulfilled in a secure context" which I assume should not affect graph generation), but the only visible thing generated are the buttons on the graphs page (which I can remove or change names of). 

I have tried disabling all other skins, clearing the contents of the html-folder, adding the graphs.conf file with just one single graph or the default examples all enabled, nothing I do appear to make any kind of difference. I get current temperature on the home page, the min-max-records page works fine with the table, but graphs and reports are empty on the site.

**Comment by poblabs** [comment]
Is your site public so I can look at it? Sounds like you need to check [your gapsize](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#gapsize)? Check the [readme ](https://github.com/poblabs/weewx-belchertown/blob/development/README.md) and [wiki ](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation)for all kinds of help and [debugging](https://github.com/poblabs/weewx-belchertown/blob/development/README.md#how-to-use-debug)

**Comment by GaRyu** [comment]
Interesting. I typed in my external address to copy-paste it to you and make sure I got it right (I have dynamic IP so it keeps changing; right now it's at http://83.255.105.195:8888/). When loading on this external IP the graphs show up fine. So it appears it is only when I use my LAN address (192.168.0.x) that the graphs are not showing. So that solves my problem, but I am curious why it would only work with the external IP since the other parts of the site load just fine locally?

**Comment by poblabs** [comment]
What's the path for your lan? could be related to a relative_url() setting. Try the debug link I sent and send what your browser's console says when trying your lan. I am assuming it's going to give you a 404 on the charts json files

**Comment by GaRyu** [comment]
No, there are no errors in the console, like I said originally. Nothing in syslog either. And all the standard skins work just fine with graphs etc. 

The page code to load graphs is `<a href="./graphs">View more here.</a>` which made me try to load http://192.168.0.5/graphs and lo and behold it works just fine. Still doesn't show on the home page for local, but does on external address.

**Comment by GaRyu** [comment]
Hold on. Sorry if what I am writing doesn't make sense, but it surely doesn't make sense to me. 

If I click on the link "View more here" on the homepage from 192... then I don't see any graphs. Type manually 192.../graphs and it works just fine, and if from that page I click on Home to get to the home screen I do see graphs. But load 192... directly, even reloading, the graphs are not there still. So I would have to go to the /graphs first and then click back to see a full home page.

Could it be some sort of caching issue?

**Comment by GaRyu** [comment]
![screen](https://user-images.githubusercontent.com/1911429/88931214-d46e5680-d27c-11ea-970f-6dc95c9ea682.jpg)
Above is working home page after going to 192.168.0.15/graphs and clicking Home.

Below is not working homepage after going to 192.168.0.15 directly.

![screen01](https://user-images.githubusercontent.com/1911429/88931299-ef40cb00-d27c-11ea-8f4e-b2cbcbc72997.jpg)

**Comment by poblabs** [comment]
I have some time to try and look at this again. Can you provide the link to your site so I can look at it again?

**Comment by GaRyu** [comment]
Sorry, we are currently in the process of moving to a new house, so I haven't had time to put the server online again yet. May take me a couple of weeks to get there. What's more, I will need to remake my network structure because the conditions are quite different in our new house, which may or may not have some influence on this problem. New routers across the board. Will get back to you once I get there.

**Comment by poblabs** [comment]
Going to close this as I get ready to release the 1.2. When you're ready - or if this is still an issue after upgrading to 1.2 - feel free to open it again or start a new issue thread.
