### ISSUE TITLE
Extending weewx schema

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#349]
In this section for UV charts -- https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#uv-and-solar-radiation

You mention you need to extend the db schema but you don't say how to do this and I haven't found any links on it either from that page or the main README

Did I miss it somehow?

**Comment by poblabs** [comment]
Yep, another page on the wiki. If you're using weewx 4's built-in extended schema these observations are now included

https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database

**Comment by sgrayban** [comment]
I read that but there is no info on the maxSolarRad

Is it simply adding this ? , ('maxSolarRad', 'REAL')

**Comment by poblabs** [comment]
Yep, and the weewx.conf stuff to init it. Don't forget a backup in case something goes wrong.

**Comment by sgrayban** [comment]
Just donated another $25 to you for your fine work and support :) Thanks!

**Comment by poblabs** [comment]
Thanks!
