### ISSUE TITLE
url errors

### ISSUE THREAD

**Issue by etamtlosz** [poblabs/weewx-belchertown#35]
I'm not sure if it's a skin or weewx issue.
My pi's port is forwarded in my router, but nothing else works but my index page. This loads nice, but as soon as I click one of the menu links, the server returns an error, because it defaults back to port 80, instead of 9812 as forwarded.
For example, my domain is http://ivcwx.duckdns.org:9812/ and it loads correctly. Graphs, Records, Reports, About links are correct, because are mapped to port 9812, but as soon as you click on them it redirects to the port 80.

**Comment by poblabs** [comment]
This seems like it's something on your router's end or the Pi's webserver end. Not with the Skin. 

Did you set `belchertown_root_url` with the special port? 

Is your router doing a port forward (NAT) or is this just on your DMZ or something?

**Comment by poblabs** [comment]
Something weird is going on with your network setup. I was able to load the page fine with styles and images. When I reload it, it fails.

**Comment by etamtlosz** [comment]
Router is a Linksys 1900ACS running openwrt. I have some other ports open as well, and I don't have such behaviors.
The URL in weewx.conf is set correctly -> belchertown_root_url = "http://ivcwx.duckdns.org:9812"
Regarding the styles you might have accessed the site while it was generating the reports.

**Comment by poblabs** [comment]
I did think about that, too. Site generation.

I'll do some testing on my lab system. At you running Apache or nginx for
web server?

**Comment by etamtlosz** [comment]
I'm running nginx.

**Comment by poblabs** [comment]
Have all the folders been copied to your www dir correctly?

Any errors in syslog?

Have you upgraded to skin version 0.8.2?

**Comment by etamtlosz** [comment]
I'm running 0.8.2. I've deleted the contents of www previously, to let the weewx regenerate it.
Syslog does not report any errors.
It's 1:15AM in NZ, I got to go to sleep.

**Comment by poblabs** [comment]
What about your nginx access or error log?

Can you paste your belchertown config?

Something is redirecting you back to Port 80. I'm thinking it's nginx but
need evidence.

**Comment by poblabs** [comment]
The skin should have created an about page an an about folder. If you installed with apt-get, this would be `/var/www/html/about`. If you installed with setup.py, it would be `/home/weewx/public_html`. Can you verify there's an index.html in that folder? 

If the file exists, then let's take the skin out of it. This URL should work. It is a direct call and no redirects are in place from any HTML from the skin: http://ivcwx.duckdns.org:9812/about 

If the file does not exist in the `about` folder, then there should be a weewx error in the syslog about a failure to generate or copy. Try running `sudo wee_reports` to see if that gives you any errors in console or in syslog. 

I really think if the `index.html` is in the `about` folder, then there's something going on with your NAT. 

How are you serving this web page? Is nginx listening on port 9812? Or are you doing a proxy pass?

(Side note: I see you've starred some Home Assistant repos, and am going to assume you're using it (I use it and I love it))... Are you using home assistant on the same Pi? There could be a conflict there with the nginx config? Just trying to throw more thoughts out there.

**Comment by etamtlosz** [comment]
nginx error log is not showing anything out of the ordinary:
```2019/01/02 12:30:40 [error] 567#567: *308 directory index of "/var/www/html/weewx/" is forbidden, client: 192.168.2.203, server: _, request: "GET /weewx/ HTTP/1.1", host: "192.168.2.241"
2019/01/02 12:31:03 [error] 567#567: *308 directory index of "/var/www/html/weewx/" is forbidden, client: 192.168.2.203, server: _, request: "GET /weewx/ HTTP/1.1", host: "192.168.2.241"
2019/01/02 12:31:05 [error] 567#567: *308 directory index of "/var/www/html/weewx/" is forbidden, client: 192.168.2.203, server: _, request: "GET /weewx/ HTTP/1.1", host: "192.168.2.241"
2019/01/02 12:31:05 [error] 567#567: *308 directory index of "/var/www/html/weewx/" is forbidden, client: 192.168.2.203, server: _, request: "GET /weewx/ HTTP/1.1", host: "192.168.2.241"
```

I'm customizing the skin via weewx.conf
```
        skin = Belchertown
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = meter_per_second2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                #group_speed = meter_per_second
                group_speed = km_per_hour

    [[Highcharts_Belchertown]]
        HTML_ROOT = /var/www/html/weewx/
        skin = Highcharts_Belchertown
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = meter_per_second2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                #group_speed = meter_per_second
                group_speed = km_per_hour

    [[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/
        skin = Belchertown
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = meter_per_second2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                #group_speed = meter_per_second
                group_speed = km_per_hour

    [[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/
        skin = Belchertown
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = meter_per_second2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                #group_speed = meter_per_second
                group_speed = km_per_hour
        [[[Extras]]]
            belchertown_root_url = "http://ivcwx.duckdns.org:9812"
            footer_copyright_text = "Zsolt Mate"
            forecast_enabled = 1
            darksky_secret_key = "********"
            earthquake_enabled = 1
            googleAnalyticsId = "UA-"
            site_title = "IVC WX"
```

about folder and folder content is there:
```
pi@raspberrypi:/var/www/html/weewx $ ls
about        graphs  index.html  json   NOAA  records  style.css
favicon.ico  images  js          neowx  pi    reports
```
```
pi@raspberrypi:/var/www/html/weewx/about $ ls
index.html
```
The source of the html files contains the correct links and ports.
Indeed, if I manually add the port to any link, the pages load and show correctly.

sudo wee_reports throws no errors.

weewx runs on port 80, but I didn't want to open port 80 on my router, so I forwarded it to 9812.

```
config redirect
        option target 'DNAT'
        option src 'wan'
        option dest 'lan'
        option proto 'tcp udp'
        option src_dport '9812'
        option dest_ip '192.168.2.241'
        option dest_port '80'
        option name 'ivcwx'
```

hassio runs on a different linux server, in docker, has nothing to do with the Pi running weewx. The weewx Pi is dedicated to weewx.

**Comment by poblabs** [comment]
Ok, so no conflict with hassio. Did you change something recently? When I tried http://ivcwx.duckdns.org:9812/about earlier it failed for me. Now it's working. 

I'm not sure why you keep getting referred back to port 80. The `href` links look correct, and when manually typing it in, it's working. 

![image](https://user-images.githubusercontent.com/3484775/50618074-8c2f5c80-0ebe-11e9-80ce-16f0d86e1e20.png)

Also, for your `weewx.conf` settings, you can do a little consolidation - you only need 1 `[[Belchertown]]`

I'm a bit puzzled by this. I'm home from work now, I need a few hours before I can test but let me see if I can try to emulate this as best I can.

**Comment by poblabs** [comment]
Ok, so clicking the link in the above reply does send me to port 9812, but then I'm sent to port 80. When I manually type it into the URL with port 9812 it works. Need to track down what's redirecting. 

Although right now it's outright failing again... (notice the port in the address bar is present)

![image](https://user-images.githubusercontent.com/3484775/50618176-1677c080-0ebf-11e9-99cc-25497d3c087b.png)

**Comment by poblabs** [comment]
Ok disregard. Port 9*18*2 vs. 9*81*2. 

9812 is working when manual. 

This is confusing 😃 

I just did a refresh of your page during archive interval, so there was no style.css that was loaded. But in doing so your `href` links on the ugly page were pointing to 98*21*. Do you have 9821 in your config somewhere?

**Comment by poblabs** [comment]
Screenshot of the "ugly page" during archive generation showing the wrong port....


![image](https://user-images.githubusercontent.com/3484775/50618347-22b04d80-0ec0-11e9-9ede-73d3a1233d3a.png)

**Comment by poblabs** [comment]
I'm able to replicate this and it's not **technically** a skin issue, it's an issue with nginx. NGiNX seems to be redirecting the URL when the trailing slash is omitted and you're on a non-standard port. [And it](https://serverfault.com/questions/759762/how-to-stop-nginx-301-auto-redirect-when-trailing-slash-is-not-in-uri) seems [there](https://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash) are [various](https://stackoverflow.com/questions/15555428/nginx-causes-301-redirect-if-theres-no-trailing-slash) fixes [for it](https://stackoverflow.com/questions/17422558/nginx-and-trailing-slash-with-proxy-pass). 

If you put the trailing slash on the URL, it'll work. This shows what I mean. Without the slash I get a 301 redirect. With the slash I get the 200 OK. 

```
root@weewx2019lab:/home/pat# curl -I http://ivcwx.duckdns.org:9812/about
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3
Date: Thu, 03 Jan 2019 01:39:08 GMT
Content-Type: text/html
Content-Length: 185
Location: http://ivcwx.duckdns.org/about/
Connection: keep-alive

root@weewx2019lab:/home/pat# curl -I http://ivcwx.duckdns.org:9812/about/
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 03 Jan 2019 01:39:12 GMT
Content-Type: text/html
Content-Length: 9228
Last-Modified: Thu, 03 Jan 2019 01:36:44 GMT
Connection: keep-alive
ETag: "5c2d672c-240c"
Accept-Ranges: bytes
```

What worked for me was to change my port forward from `9812 => 80` and instead set to `9812 => 9812`. Then have nginx listen on 9812 (just replace `80` with `9812` in your config and restart nginx). You can see in my test below it's still 301 redirecting, but with the trailing slash. Browsing the test site confirms.

```
root@weewx2019lab:/home/pat# curl -I http://btownissue35.duckdns.org:9812/about
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.0 (Ubuntu)
Date: Thu, 03 Jan 2019 02:09:14 GMT
Content-Type: text/html
Content-Length: 194
Location: http://btownissue35.duckdns.org:9812/about/
Connection: keep-alive
```

Since this nginx instance is strictly for your port forwarded weewx, this seems like it could be a viable solution for you.

**Comment by etamtlosz** [comment]
I had the wrong port in my weewx.conf station_url = http://ivcwx.duckdns.org:9821
I've corrected it, but it didn't fix the issue.

Changing the listen port in nginx fixed the issue.
Thanks for sorting this out. This could go into the readme as well, if someone is facing similar issues.
I still don't like the approach of the hardcoded address. But that's a weewx issue.

**Comment by poblabs** [comment]
I agree. The hard-coded URL is a Belchertown skin-specific setting and was a necessary step to get the skin to work on a diverse configuration of user devices and websites. It's purpose is to make sure the nav menu, JS, JSON, and CSS files all load without issue.

Every so often I toy with the idea in my head to see about getting rid of it, but the thought of breaking dozens of sites makes me reconsider 😃
