### ISSUE TITLE
Translate Alerts Aeris

### ISSUE THREAD

**Issue by FutureCow** [poblabs/weewx-belchertown#352]
Now that Aeris also support Alerts for Europe (which is already working nicely). I would like to be able to translate some of the Alerts.
Just like the forecast, also the alerts have pre defined codes:
https://www.aerisweather.com/support/docs/aeris-maps/reference/alert-types/
It would be nice to do the same as the other weather codes to have something like this in the conf:
forecast_alert_code_AW.WI.MN = Minor Wind
forecast_alert_code_AW.WI.MD = Moderate Wind
etc.
If it helps, I can make a full list of all the (US/EU) codes?

**Comment by ArendPWS** [comment]
Aeris alerts for Europe are now indeed working (High Temperature alert here as we speak). Your idea would be a nice addition.

**Comment by ddperso** [comment]
It is a good new for Europe!
The translation method of FutureCow is very interesting

**Comment by poblabs** [comment]
> If it helps, I can make a full list of all the (US/EU) codes?

That would be super helpful

**Comment by FutureCow** [comment]
Here you go
[Weather Alarm Translations.xlsx](https://github.com/poblabs/weewx-belchertown/files/5046905/Weather.Alarm.Translations.xlsx)

**Comment by poblabs** [comment]
Wow there's so many! skin.conf will be huge.

**Comment by FutureCow** [comment]
Yep... Just skip de US codes 😀

**Comment by Bug-Storm** [comment]
Hello.. I need help!
What I need add on skin. Conf and belchertown.js.tmpl? 

Beacause "forecast alert code" and" $obs. Forecast. Alert. Code"  need add where? 
Thanks

**Comment by Bug-Storm** [comment]
Heyy when you'll add forecast_alert_code on skin? 🤔

Thanks

**Comment by poblabs** [comment]
When time allows. This skin is a side project for me and I work on it when spare time allows.  😄 

Pull requests are welcome!!

**Comment by Bug-Storm** [comment]
> When time allows. This skin is a side project for me and I work on it when spare time allows. 😄
> 
> Pull requests are welcome!!

Yes, I understand, I try to change the berlchertown.Py, but I don't know if is correct:p 

![vncviewer_Lm1Nba94l2](https://user-images.githubusercontent.com/68688876/90752631-ee2d1780-e2d7-11ea-8950-659bdf07c75e.png)
![vncviewer_iahU86G26B](https://user-images.githubusercontent.com/68688876/90752641-f08f7180-e2d7-11ea-881b-98307b12e1aa.png)
![vncviewer_4JwO8McxPW](https://user-images.githubusercontent.com/68688876/90752651-f2f1cb80-e2d7-11ea-9f7f-76ff2cf42feb.png)

**Comment by poblabs** [comment]
All, I've pushed the new Aeris alert codes to the development branch. It's working for me on test USA data, please test it out - especially EU data. 

Please update your skin with **all files with the latest from development**, and restart weewx when done. You should be on 1.2rc3 when updated.

**Comment by Bug-Storm** [comment]
Ok thanks I'll test on my country 😉

**Comment by Bug-Storm** [comment]
> All, I've pushed the new Aeris alert codes to the development branch. It's working for me on test USA data, please test it out - especially EU data.
> 
> Please update your skin with **all files with the latest from development**, and restart weewx when done. You should be on 1.2rc3 when updated.

Hey i'm back, 

It's work , thanks again 
![0WHQpUm](https://user-images.githubusercontent.com/68688876/92998629-2280a600-f51b-11ea-8b76-f76c8e50b663.png)
