### ISSUE TITLE
Cannot generate graphs because start_ts or stop_ts is None

### ISSUE THREAD

**Issue by VonHirsch** [poblabs/weewx-belchertown#355]
I ran into an error:

![image](https://user-images.githubusercontent.com/3280180/89846231-a1667580-db4e-11ea-8d32-da95c2829c08.png)

I added the code to check if either start_ts or stop_ts is None, and if so continue, but that skips all the graphs =)

This is a new setup, weewx 4.1.1 + LaCrosse WS28xx

Thanks for a great theme!

**Comment by poblabs** [comment]
Interesting. The skin is usually called upon archive interval, and at that point a start timestamp, and stop timestamp would be available. Did you run wee_reports before an archive interval was written to the database?

**Comment by VonHirsch** [comment]
It's quite possible, I'll check into that, thanks for the tip!

**Comment by poblabs** [comment]
If your station ran overnight then you should have enough data in the database to generate the report (website). If not, re-open this issue, but I think you should be all set once you have data in the database.
