### ISSUE TITLE
Diffrence between graph and real time feel like temperature

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#356]
Hi

I have a difference between the real time temperature (feel like, or "ressenti" in french) and the graphique
May be I have made a mistake in graph.conf hereafter:
# Global Chart Defaults
# These are fallback options that charts will use if an option is not defined. 
credits = "Météo d'Auffargis (Highcharts)"
time_length = 90000 # Last 25 hours
type = line
colors = "#7cb5ec, #b2df8a, #f7a35c, #8c6bb1, #dd3497, #e4d354, #268bd2, #f45b5b, #6a3d9a, #33a02c"
tooltip_date_format = "LLL"
connectNulls = true

[homepage]
	# Chart Timespan Defaults
	title = "Depuis minuit"
	show_button = false
	button_text = ""  # graphique utilisé sur la page principale
	tooltip_date_format = "LLL"
	gapsize = 300 # This should be your archive_interval from weewx.conf
	aggregate_type = max
	aggregate_interval = 300
	time_length = today

	[[chart1]]
		title = Température
		type = spline
		[[[WindChill]]]
			color = "#33a02c"
			name = Froid ressenti
		[[[HeatIndex]]]
			color = "#dd3497"
			name = Chaleur ressentie
		[[[outTemp]]]
			color = "#b2df8a"
		[[[dewpoint]]]
			yAxis_label = ( °C )
			yAxis_tickInterval = 2
			yAxis_softMin = 0

Is it correct?
Many thanks

See attach files
![graph](https://user-images.githubusercontent.com/65628453/89875579-b8907c00-dbbd-11ea-82b1-8d5da006ff4a.jpg)
![temp](https://user-images.githubusercontent.com/65628453/89875580-b9291280-dbbd-11ea-8780-c00a17234c8e.jpg)

**Comment by Bug-Storm** [comment]
Ahh j'ai le même souci :/ ..i've same problem :/

**Comment by Bug-Storm** [comment]
Car le windchill ce n'est pas la même varible que celui de app.temp ;)  tu peux mettre " $current.apptemp" to "$current.windchill" ;) 

If beacause the windchill is  not same variable of the apptemp ;)  you need just change on index.html.tmpl "  " $current.apptemp" to "$current.windchill" ;)"

**Comment by ddperso** [comment]
The feel like indice is:

   - "windchill" if outTemp < 50F
   - "outTemp" if 50F < outTemp < 80F
   - "heatIndex" if 80F < outTemp

I don't know how is calculated appTemp used in belchertown.js.tmpl...

**Comment by Bug-Storm** [comment]
Try convert 50F to °C and change out_tempF to out_tempC and same chose off windchill and heatindex

**Comment by poblabs** [comment]
appTemp is calculated by weewx, not the Belchertown skin.

**Comment by ddperso** [comment]
Weewx does not apply official formulas?
#Bug-Storm
I try to uncomment  and change F to C, and comment appTemp, but it
doesn't work....


        // Feels like temp as defined by NOAA's "Apparent Temperature" at:
http://www.nws.noaa.gov/ndfd/definitions.htm
        if ( data["outTemp_C"] <= 10 ) {
            jQuery(".feelslike").html( "$obs.label.feels_like: " +
parseFloat(parseFloat(data["windchill_C"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: 1, maximumFractionDigits: 1}) + "
$unit.label.outTemp" );
        } else if ( data["outTemp_C"] >= 27 ) {
            jQuery(".feelslike").html( "$obs.label.feels_like: " +
parseFloat(parseFloat(data["heatindex_C"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: 1, maximumFractionDigits: 1}) + "
$unit.label.outTemp" );
        } else {
            jQuery(".feelslike").html( "$obs.label.feels_like: " +
parseFloat(parseFloat(data["outTemp_C"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: 1, maximumFractionDigits: 1}) + "
$unit.label.outTemp" );
        }
    }

    // Temperature C
    if ( data.hasOwnProperty("outTemp_C") ) {
        outTemp =
parseFloat(parseFloat(data["outTemp_C"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: unit_rounding_array["outTemp"],
maximumFractionDigits: unit_rounding_array["outTemp"]});
        get_outTemp_color( "degree_C", outTemp );
        jQuery(".outtemp").html( outTemp );
    }

    // Apparent Temperature US
//    if ( data.hasOwnProperty("appTemp_F") ) {
//        jQuery(".feelslike").html( "$obs.label.feels_like: " +
parseFloat(parseFloat(data["appTemp_F"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: unit_rounding_array["outTemp"],
maximumFractionDigits: unit_rounding_array["outTemp"]}) + "
$unit.label.outTemp" );
//    }

    // Apparent Temperature Metric
//    if ( data.hasOwnProperty("appTemp_C") ) {
//        jQuery(".feelslike").html( "$obs.label.feels_like: " +
parseFloat(parseFloat(data["appTemp_C"])).toLocaleString("$system_locale_js",
{minimumFractionDigits: unit_rounding_array["outTemp"],
maximumFractionDigits: unit_rounding_array["outTemp"]}) + "
$unit.label.outTemp" );
//    }

**Comment by poblabs** [comment]
I'm confused. You're showing 2 different things. 

weewx does the appTemp calculation. 

Your graphs do not use appTemp, but rather they are using windchill and heatindex. 

If you want appTemp, then use `[[[appTemp]]]` in the graphs.conf. 

The section you posted applies to MQTT and the translation label and number floating digits and is not a calculation. The calculation is already done in MQTT.

**Comment by poblabs** [comment]
Another important distinction is that you may need to enable appTemp to be tracked. https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database

**Comment by poblabs** [comment]
I also may direct you to the [weewx forums](https://groups.google.com/forum/#!forum/weewx-user) for help on this, as I don't think you're experiencing a skin issue at this time.

**Comment by ddperso** [comment]
Many thank's Pat
In my mysql database I have already archive_day_appTemp (and windRun), is
it necessary to apply Adding-a-new-observation-type-to-the-WeeWX-database
<https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database>
 ?

**Comment by poblabs** [comment]
No, if those tables and columns exist in the archive table, then you don't need to do anything. weewx will calculate them. Are you seeing data in those columns in the **archive** table?

**Comment by ddperso** [comment]
Yes, tables contain informations and i can use them in graphs

**Comment by poblabs** [comment]
So this issue is resolved?

**Comment by ddperso** [comment]
Yes
Thanks for information
