### ISSUE TITLE
Bad bearing for earthquake and vertical line too short

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#358]
Hi Pat
I have updated my site with your new repo 2 days ago
I have 2 small problems:

- In earthquake window, the vertical line between magnitude et distance is too short, this is due to km instead of miles (1 line)

I suggest you to add a <br>

                                    <span class="earthquake-distance">$earthquake_distance_away $earthquake_distance_label
                                    <br> $earthquake_bearing</span>

- The second problem is a bad bearing of recent earthquake

As you can see on the attached screenshot, the bearing is NO (North West) instead of ESE (the distance is correct)

![Earthquake](https://user-images.githubusercontent.com/65628453/90043376-51152200-dccc-11ea-99bc-583fcd351d97.jpg)
![bearing](https://user-images.githubusercontent.com/65628453/90043883-0d6ee800-dccd-11ea-9041-8f6051868971.jpg)

**Comment by biltmorelaker** [comment]
Interesting. I understand why the vertical line is short when the distance is on a single line and it seems your suggested fix will work. For me, the direction and distance though are correct. Maybe something in the calculation that causes the issue for locations on the East side of the Prime Meridian?

![image](https://user-images.githubusercontent.com/44727343/90046720-daadfb00-dc9e-11ea-8321-6b633c1d2052.png)
![image](https://user-images.githubusercontent.com/44727343/90046738-de418200-dc9e-11ea-90da-341eeee9033b.png)

**Comment by ddperso** [comment]
May be...

Le mer. 12 août 2020 à 19:28, biltmorelaker <notifications@github.com> a
écrit :

**Comment by poblabs** [comment]
Interesting. Can you post the lat/lon for your station and for the earthquake? 

I've borrowed the bearing code, so I'll have to see if there's something a little more accurate out there.

**Comment by ddperso** [comment]
My station:
    # Description of the station location
    location = "Auffargis, France"

    # Latitude in decimal degrees. Negative for southern hemisphere
    latitude = 48.700751
    # Longitude in decimal degrees. Negative for western hemisphere.
    longitude = 1.881646

Earthquake:
M 3.6 - 5 km S of Gramais, Austria

   - 47.213°N 10.529°E

**Comment by poblabs** [comment]
Whats the link to your site?

**Comment by ddperso** [comment]
Https://météo-auffargis.decoodt.eu
<Https://xn--mto-auffargis-bhbb.decoodt.eu>

**Comment by poblabs** [comment]
Can you update all files on your site to the latest? Example json/weewx_data.json.tmpl has not been updated and is missing information I need to help troubleshoot

**Comment by ddperso** [comment]
https://meteo-auffargis.decoodt.eu

**Comment by ddperso** [comment]
Strange, I have copied changed files (Jason, py , js...)
I check...

**Comment by poblabs** [comment]
Thanks. Just copy the latest weewx_data.json.tmpl file for now from development, restart your station and let it run an archive interval.

**Comment by ddperso** [comment]
Done (copy, restart weewx_service, wee_reports)
But always the same bearing....
[image: image.png]

**Comment by poblabs** [comment]
Bearing won't change yet. I needed to see some data in your weewx_data.json file. It's updated now, so I'll do some testing and let you know when to try a new version of files

**Comment by poblabs** [comment]
Ok give the latest commit a try. My testing with your station location, and the earthquake location shows the bearing at 101.17 degrees, or just East. 

I compared this against [this website](https://www.sunearthtools.com/tools/distance.php), which shows it as 104 degrees. 

104 degrees is East South East by 3 degrees. So it's very close to the line and probably within a margin of error. 

Let me know

**Comment by poblabs** [comment]
Update 2 files:

belchertown.py
skins/Belchertown/weewx_data.json.tmpl

restart weewx

**Comment by ddperso** [comment]
Perfect!
(I have added <br> between distance and bearing)

Thank's Pat
[image: image.png]
