### ISSUE TITLE
1.2rc2 Fails With local variable 'eq_distance_label' Error

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#359]
I installed 1.2rc2 today, restarted weewx 4.1.1,  waited for reports to run.
I had an error that stopped Belchertown skin from completing.
See attached file for the system log for this.
Happens every report run.
Rolled back to 1.2b6 and all is well.

I emptied the Belchertown skin directory before installing, so no older files were there.
I also emptied the output directory before running, no files there either.

Running Pop!_OS 20.04 LTS

[B1.2rc2.txt](https://github.com/poblabs/weewx-belchertown/files/5064943/B1.2rc2.txt)

**Comment by poblabs** [comment]
Silly question, but I'll ask it. Did you copy everything when you installed? All files (skin.conf/weewx_data.json.tmpl,etc?) That error leads me to believe something was missed.

**Comment by gary-hammer** [comment]
I used home/weewx/bin/wee_extension --install

**Comment by poblabs** [comment]
Did you restart weewx after upgrading?  If not, I'll check that out - should have worked. 

If you want to try the skin you can download the development zip file and copy the files to their respective locations and restart weewx

**Comment by gary-hammer** [comment]
Yes, that's what I did. 
Download the development zip, stop weewx, erase the Belchertown skin directory and the html output directory, install the skin, start weewx, wait for reports to run.

So, you'd like me to just copy the files and not use the weewx installer?

**Comment by poblabs** [comment]
Yes please

**Comment by gary-hammer** [comment]
I copied the files manually with no difference in the issue.

**Comment by gary-hammer** [comment]
I do not have earthquake enabled.

**Comment by poblabs** [comment]
> I do not have earthquake enabled.

Ah, that might be the bug there. I may have forced it into the skin without regard to whether or not earthquake is enabled. Let me look into it

**Comment by gary-hammer** [comment]
Let me change skin.conf to enable it.

**Comment by gary-hammer** [comment]
That is the case. I enabled earthquake in skin.conf and reports run fine.

**Comment by gary-hammer** [comment]
I'll leave it enabled until next rc. I just wanted to see if the new version made a difference for Firefox.
It does not. Still failed connection.

But that's a different issue.

**Comment by poblabs** [comment]
Just pushed a fix. It's in the belchertown.py file. Small oversight, thanks for testing it out! Works for me when earthquake is disabled now.
