### ISSUE TITLE
Day date label missing in xAxis weatherRadial graph for a month

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#360]
Hi

How do you display the day date in xAxis for a weatherRadial graph with a time_lenght = month?

I have written:
```
[month]
	# Chart Timespan Defaults
	title = "Ce mois"
	show_button = true
	button_text = "MOIS"
	type = spline
	time_length = month
	tooltip_date_format = "dddd LL"
	aggregate_type = max
	aggregate_interval = 86400 # 1 day
	gapsize = 86400 # 1 day in seconds

	[[chart1]]
		title = Température
        css_class = "weatherRadial"
        [[[weatherRange]]]
            range_type = outTemp
```

![graph](https://user-images.githubusercontent.com/65628453/90259563-86e01500-de4a-11ea-97bf-46107b61daf2.jpg)

**Comment by poblabs** [comment]
Not sure - [you could try playing with the tickInterval on the xAxis in this file](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/js/belchertown.js.tmpl#L1102-L1110) - but this may have adverse effects on your other charts.

**Comment by poblabs** [comment]
Oops - you want to [modify tickInterval in between these lines here](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/js/belchertown.js.tmpl#L1516-L1524), since this is the config specific to the weatherRange chart.
