### ISSUE TITLE
Is there something in the skin that controls this?

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#361]
Things have been going great using your skin and Weemx.

However, every once in a while I get a screen that looks like this:

![Screen Shot 2020-08-15 at 7 25 24 PM](https://user-images.githubusercontent.com/4523243/90323270-1a8a1200-df2d-11ea-83a1-ce55f03e1519.png)

Even though I know data has been coming in.   I've been digging around trying to sort out what might be causing this.
The data continues to show up on the graphs.  I just get this which looks like no data has come in...

I've been reading the wiki, etc. and just haven't either stumbled upon the setting that would control this, or read it and didn't mentally parse it correctly.    So I don't think I've got anything off... but not sure if this is a bug, or some config is off..

Any pointers you could share?

**Comment by poblabs** [comment]
The N/A typically comes from weewx when there's no data to show. Typically it doesn't show this though unless you restarted weewx and ran a wee_reports before an archive interval or something. 

You can try the [debug part of the site ](https://github.com/poblabs/weewx-belchertown/tree/development#how-to-use-debug)to see if the N/A or `None` is in the MQTT packets?
