### ISSUE TITLE
Report fails when label "station_observations " have international characters

### ISSUE THREAD

**Issue by ectatomma** [poblabs/weewx-belchertown#365]
Hi Pat,
When I translate (to Spanish) the label "station_observations" in weewx.conf to: 
`station_observations = "Barómetro", "Punto de rocío", "Humedad", "Precipitaciones"`

report generation fails with:

`Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 1176, in get_extension_list
    obs_output = getattr(current, obs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 3: ordinal not in range(128)`

Note that  u'\xf3 corresponds to "ó"

If I comment that line, report generation is OK.

Server: Raspberry-Pi Zero W
OS: Raspbian GNU/Linux 10 (buster)
WeeWX version: 4.1.1
Belchertown Skin Version: 1.2rc2
Station hardware: BYOWS2 - Raspberry Pi (Modified from BYOWS)

My weewx.conf is attached
[weewx.conf.tar.gz](https://github.com/poblabs/weewx-belchertown/files/5114221/weewx.conf.tar.gz)

**Comment by bdwilson** [comment]
FYI, your _station_observations_ variables should be things like outTemp, inTemp, rain, etc.  Don't put the translation there, put the variable from weewx.conf.

**Comment by ectatomma** [comment]
> FYI, your _station_observations_ variables should be things like outTemp, inTemp, rain, etc. Don't put the translation there, put the variable from weewx.conf.

Hi bdwilson, thanks for your advise.
 I'm following the instructions at [https://github.com/poblabs/weewx-belchertown#translating-the-skin](url), where it says "The skin uses the "default labels" for every text and title on the page. This allows you to translate, or simply just change the words to something else easily. You can either edit the [Labels] [[Generic]] section within skin.conf, or (preferred) copy these labels to your [Belchertown] skin settings within weewx.conf's"

In this case, "station_observations" is under [Labels] [[Generic]] at skin.conf. I copied "station_observations" from skin.conf to weewx.conf and changed the values to do the translation.

**Comment by bdwilson** [comment]
Yes, the default labels are under [StdReport] -> [[Labels]] -> [[[Generic]]]. This is where you'd put your translations, and you'll then use inTemp, outTemp, etc in your station_observations section. 

           [[[[Generic]]]]
                #barometer = Barometer
                dewpoint = Dew Point
                ET = ET
                heatindex = Heat Index
                inHumidity = Inside Humidity
                inTemp = Inside Temperature
                outHumidity = Humidity
                outTemp = Outside Temperature

**Comment by ectatomma** [comment]
Oh, I see my error now, thanks!!
