### ISSUE TITLE
station_observations for additional data beyond data bindings (i.e. $yesterday.rain.sum)

### ISSUE THREAD

**Issue by bdwilson** [poblabs/weewx-belchertown#366]
I noticed that with 1.1 you allow data bindings for station_observations.  I wanted to setup an observation for rain as of yesterday, and this did not work. Is there an easy way to be able to use additional variables like you can use in templates? Or can you configure things in weewx so that they are accessible to station_observations?  Thinking of some variables like this would be handy:

$yesterday.rain.sum
$span($day_delta=2).rain.sum
$span($day_delta=3).rain.sum
..

Thanks!

**Comment by poblabs** [comment]
The station observation box comes from MQTT. Since MQTT only provides the current or today values, that's what you get. I'm not the author of the MQTT extension. You could reach them and see if they can add what you're looking for? Then it might be possible.
