### ISSUE TITLE
Allow for optional alias for station_observations

### ISSUE THREAD

**Issue by tomdotorg** [poblabs/weewx-belchertown#367]
I use the soil moisture data entries which are called soilTemp1-4. I would like a way to include those values in station_observations for constant updating with loop records, but with a specified alias where I can insert something like 'Pond Temperature' for soilTemp4. I would like to provide there alias' in the station_observations line in weewx.conf.

See http://vtwx.tom.org/ for an example.
![image](https://user-images.githubusercontent.com/52498/91027567-43b03f80-e5ca-11ea-9a9a-bded0501ddd6.png)

**Comment by ArendPWS** [comment]
If I understand your question correctly: custom labels can be added/changed in weewx.conf. In your case e.g.:

[StdReport]
    [[Defaults]]
        [[[Labels]]]
            [[[[Generic]]]]
                soilTemp4 = Pond Temperature

I also have a question for you:

To get the soilTemp4 temperature into the Belchertown skin you needed to change weewx_data.json.tmpl? I am looking for a way to change/add data entries without needing to modify the original weewx_data.json.tmp. With each new release/update it will be overwritten, so I need to keep a backup of my json file and copy it back after an update. Maybe the way graphs.conf and graphs.conf.example are handled would be a solution to this (i.e. weewx_data.json.tmpl and weewx_data.json.tmpl.example). But maybe there are better solutions.

**Comment by Bug-Storm** [comment]
You need just look on the database if you have the correctly data, and after for to get the current data, you need to use `$current. soilTemp4`.
You don't need to change "weewx_data.json.tmpl" because the skin will get data directly from the database;)

**Comment by poblabs** [comment]
Changing the label as @ArendPWS mentioned should fix it up. restart weewx when done

**Comment by tomdotorg** [comment]
Perfect. Works great. Thanks @ArendPWS and @poblabs
