### ISSUE TITLE
Forecast fail

### ISSUE THREAD

**Issue by 56-miguelru** [poblabs/weewx-belchertown#368]
Hi.
I have a forecast problem. I use Aeris and Belchertown 1.2rc2. I have tried other versions of Belchertown skin with the same result. I have tried to solve it by checking configs and wiki without success. It must be something basic but ...
Without activating the forecast it works fine, as soon as I activate the forecast it produces a series of errors that I cannot solve.

Weewx.log:

 INFO user.belchertown: New forecast file downloaded to /var/www/html/weewx/belchertown/json/forecast.json
 ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
 ERROR weewx.reportengine:         ****  list indices must be integers or slices, not str
 ERROR weewx.reportengine:         ****  Traceback (most recent call last):
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
 ERROR weewx.reportengine:         ****      obj.start()
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
 ERROR weewx.reportengine:         ****      self.run()
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
 ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
 ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
 ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
 ERROR weewx.reportengine:         ****      default_binding)
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
 ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
 ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 979, in get_extension_list
 ERROR weewx.reportengine:         ****      current_obs_summary = aeris_coded_weather( data["current"][0]["response"]["ob"][$
 ERROR weewx.reportengine:         ****  TypeError: list indices must be integers or slices, not str
 ERROR weewx.reportengine:         ****  Generator terminated
 INFO weewx.reportengine: Copied 2 files to /var/www/html/weewx/belchertown

My website is: http://valhermosometeo.ddns.net:8000

**Comment by poblabs** [comment]
It looks like the error is cut off. Can you enable forecasts again and attach the log to this issue as a zip file?

**Comment by 56-miguelru** [comment]
Yes of course. I will do.
[weewx.zip](https://github.com/poblabs/weewx-belchertown/files/5136855/weewx.zip)

My website is: http://valhermosometeo.ddns.net:8000

**Comment by poblabs** [comment]
I see the problem. Aeris Weather says there is no current weather data available for your latitude and longitude (see output below). I have updated Belchertown skin to account for this error. 

You can reinstall the latest download of the development version of the skin which will fix this and give you the forecast. But you will not have current conditions available to you. 

I would contact Aeris through your account portal and ask them how they can provide weather data for your area. 

```
  "current": [
    {
      "success": true,
      "error": {
        "code": "warn_no_data",
        "description": "Valid request. No results available based on your query parameters."
      },
      "response": []
    }
```

`warn_no_data`
