### ISSUE TITLE
MQTT working on some browsers only

### ISSUE THREAD

**Issue by ituri** [poblabs/weewx-belchertown#369]
Hi,

I'm running weewx on my Raspberry Pi. For outside access rsync is copying the files to my Synology NAS where nginx is serving the pages. I'm using hivemq as the broker.
I've managed to get MQTT live updates somehow running. However, this doesn't work on all devices. Here's how it works/doesn't work:
Mac with Chrome:
- locally (i.e. http://192.168.8.5/weewx/belchertown): Working fine!
- externally (http://myweathersite.com, hosted on my Synology): No, stuck "Connecting..."

iPhone with Safari:
- externally: Fails directly, gives me a "Failed connecting to the weather station. Please try again later" error.
- locally: Working fine!

iPhone with Chrome:
- externally: Working fine!
- locally: Working fine too!

Do you have any ideas why it works on some devices while on others it doesn't? I thought about this being related to [this](https://github.com/poblabs/weewx-belchertown/issues/342) bug report but since it's working on some devices at least I think the error might be somewhere else.

**Comment by poblabs** [comment]
This is a weird one because it is working on some. 

The pattern seems that external fails the most. 

If you want to access it externally you need to set your MQTT websockets configuration to your external URL since you won't have access to 192.168.8.5 from outside the house. Have you tried this?

**Comment by ituri** [comment]
Sure! 

I think I have found the solution, though: I found another GitHub issue where you suggested that one needs to connect to websockets via SSL if the page itself is also served via SSL. I did that and now everything seems to be working fine!
(Well, except the long loading times of the test.mosquitto.org server but that's a different story)

**Comment by poblabs** [comment]
Great!
