### ISSUE TITLE
Feature Request: Android App-Like Experience

### ISSUE THREAD

**Issue by WhiteNoseThunderPants** [poblabs/weewx-belchertown#37]
A feature that I think would be nice to have is to have the website look more like an app on Android by utilizing a manifest.json file. The file seems pretty simple and it appears there is only one line of code needed for each page.

I'm going to attempt on my site and if it works properly, I'll submit a PR if this is something anyone else is interested in.

Here is information from Google about how to set it up for Chrome on Android, but should work in Firefox and possibly others https://developers.google.com/web/fundamentals/web-app-manifest/.

**Comment by poblabs** [comment]
Sounds interesting. Let me know your results. Might be easiest to pop it
into the header.html.tmpl?
