### ISSUE TITLE
Alert (Warning/Watch/Etc) Popup Opens, Then Closes

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#372]
Using Edge or Firefox when there is an alert shown, I click on the link and see something open center page. As soon as it populates, the window/popup closes.
Not shown in the task list from Edge, nor TAB, nor hovering over the taskbar icon for either browser.

Opening in 'Safe' mode has the same results.

Any idea?

WeeWX 4.1.1 Belchertown 1.2rc2

**Comment by poblabs** [comment]
You may have footer.html.tmpl loaded twice, or the bootstrap javascript loaded twice. This will open/close a popup window in this fashion. Make sure all files are exact as they are from the development branch

**Comment by gary-hammer** [comment]
Bingo! bootstrap was loaded twice.

Thanks Pat
