### ISSUE TITLE
Realtime clock delay 

### ISSUE THREAD

**Issue by RebeckaJohansson** [poblabs/weewx-belchertown#373]
I have my weewx and Belchertown skin with public site and all works perfect but i noticed that my realtime clock when connected dont read the seconds part correct. The realtime clock reads the seconds every 10 seconds.

The realtime clock updates every 10 seconds like a delay. 

I have my server on Raspberry pi 4 and have all localtime corrected so its only the skin thats delays in the real time clock. 

My site is myweatherserver.ddns.net

**Comment by poblabs** [comment]
The skin doesn't use a real time clock? Maybe weewx does? I have no idea what's wrong here. May be a question for the weewx forums. Also, make sure your graphs.conf isn't generating huge graphs, that'll show you down no matter what system you're on. 

[Check out tip #1](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#tips).

**Comment by RebeckaJohansson** [comment]
I dont know either haha. I just noticed it.
I have looked in all files but could not find something about clock part. 
I dont have much graphs more then the standard and the uv with solar graphs.

I will keep looking and see if i can find something

**Comment by poblabs** [comment]
Try a comment in the [weewx forums](https://groups.google.com/forum/#!forum/weewx-user). I think this might be weewx related and not skin related? Provide logs, weather station make/model, etc that can help out

**Comment by ArendPWS** [comment]
With real time clock you mean the time part of this message on top of your homepage?

Connected to weather station live. Data received 30 augusti 2020, 19:20:33

**Comment by RebeckaJohansson** [comment]
> With real time clock you mean the time part of this message on top of your homepage?
> 
> Connected to weather station live. Data received 30 augusti 2020, 19:20:33

..... 

Yes i mean that :)
I forgot to write that in my first text.

**Comment by RebeckaJohansson** [comment]
The seconds part of the clock only reloads every 10 seconds

**Comment by poblabs** [comment]
Oh! Good catch @ArendPWS, yes that is part of the skin. I thought you meant the archive interval when the skin is generated. 

The timestamp at the top is based off the epoch timestamp weewx sends over mqtt. Make sure your raspberry pi's time is correct. Also check the [debug mode](https://github.com/poblabs/weewx-belchertown/tree/development#how-to-use-debug), and see what it says for timestamp. That's what the skin is reading (this comes from weewx)

**Comment by ArendPWS** [comment]
That is the time when a new MQTT update is received. As far as I know: the intervals at which you receive this updates is determined by your weather station output speed (correct me if I am wrong). My weather station also outputs data about every 12 seconds.

**Comment by RebeckaJohansson** [comment]
My fault i didnt writed more specific first time. Sorry for that :) I can dubblecheck my Raspberry tomorrow and check debug mode and copy what its says in here to you. 
I will check my station too

**Comment by RebeckaJohansson** [comment]
i can find in wee_debug Load information

1 minute load average 0.04

and that my archive is set to 300 seconds

But nothing about if my Raspberry Pi clocksynk

**Comment by RebeckaJohansson** [comment]
but another timedate command says this 

Local time: mån 2020-08-31 09:56:59 CEST
Universal time: mån 2020-08-31 07:56:59 UTC
 RTC time: n/a
 Time zone: Europe/Stockholm (CEST, +0200)
System clock synchronized: yes
  NTP service: active
 RTC in local TZ: no

**Comment by poblabs** [comment]
The clock at the top of the page represents when your weather station last
sent data to weewx. It is not a clock of the current time.
