### ISSUE TITLE
How to change the last-rain return values

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#374]
Hi
I have installed the last-rain extension which give me 2 return values "last_rain" and "time_since_last_rain"

In the Github documentation, I can see:
Result is returned as a ValueHelper so standard Weewx formatting is available eg $last_rain.format("%d %m %Y")

Could you say me where I can defined this fomat? Is it in weewx.conf? or elsewhere?

Many thanks for your help

Didier

**Comment by poblabs** [comment]
Is this a custom extension? If so.. can you leave an issue with the developer of that extension? I'm not sure about `last-rain`'s formatting.

**Comment by ArendPWS** [comment]
You can find information on formatting here: [Weewx formatting](http://www.weewx.com/docs/customizing.htm#Formatting_examples)
