### ISSUE TITLE
(Only) Day graphs don't show data Plot Lines

### ISSUE THREAD

**Issue by alien8r** [poblabs/weewx-belchertown#375]
Mouse over data points show detailed data on All graphs (Day/Week/Month/Year) so we know the graphs are populated.
All graphs, Except Day, show plotted data in the graphs.
Day graphs show no plot lines at all.

**Comment by poblabs** [comment]
You need to set the gap size equal to your archive interval. Check the
charts wiki.

**Comment by alien8r** [comment]
Wish that worked. (This is on a wired Davis Pro+)
Had gapsize = 300000 which is 1000x of my archive_interval from weewx.conf, that's the recommendation in charts.conf.
Set it to 300 to match archive_interval, ran wee_reports and still no love, tried different powers of 10 to no effect.
Finally just set connectNulls true.

**Comment by poblabs** [comment]
What's the link to your website? Have you tried the debug mode that's in
the readme? What version of the skin are you using?

**Comment by alien8r** [comment]
Don't have a public site, sorry.
Running WeeWX version: 4.1.1 with Belchertown Skin Version: 1.1 (re-installed it after downloading it again the other day)

**Comment by arnebjarne** [comment]
I have the exact same problem. All daily graphs are blank unless you hoover over it with the mouse.
Weekly/Monthly/Yearly graphs works

It can be observed at https://www.saltbaek.dk/weewx/reports/graphs/

**Comment by poblabs** [comment]
Your day graphs are at 1 hour intervals so you need to set your gap size to
1 hour in milliseconds. Refer to the documentation for more information

**Comment by arnebjarne** [comment]
Hi Pat.

Could a feature request be that you read the
[StdArchive]
   archive_interval = 

from weewx.conf so we do not have to adjust it ourself? :)

**Comment by arnebjarne** [comment]
sudo cp /etc/weewx/skins/Belchertown/graphs.conf.example /etc/weewx/skins/Belchertown/graphs.conf

[day]
    gapsize = 3600000

sudo service weewx restart

fixed my problem :)

**Comment by poblabs** [comment]
That would be a good feature request but because of how weewx works, and the graphs.conf setup, the gapSize has to be manually set.
