### ISSUE TITLE
Max min not updating correctly

### ISSUE THREAD

**Issue by windymel** [poblabs/weewx-belchertown#376]
Hi Pat. Working off the latest dev branch it looks like the min/max dailies are not updating correctly. See my site for an example:
[https://mpyc.nz/weather/](url)

Everything else seems to be working fine.

I am getting a wee stack trace each time the skin runs:
`Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Belchertown/json/weewx_data.json.tmpl
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'github_version'
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 322, in generate
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Belchertown_json_weewx_data_json_tmpl.py", line 132, in respond
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'github_version'
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Belchertown/js/belchertown.js.tmpl
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'github_version'
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 322, in generate
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Belchertown_js_belchertown_js_tmpl.py", line 160, in respond
Aug 31 16:45:17 raspberrypi weewx[843] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'github_version'
Aug 31 16:45:17 raspberrypi weewx[843] INFO weewx.cheetahgenerator: Generated 9 files for report Belchertown in 1.27 seconds`

**Comment by poblabs** [comment]
Can you update all your files to the most recent? The error shows invalid key `github_version`, but that was removed in one of the commits, so I think you have a stale file or something?

**Comment by windymel** [comment]
Thanks Pat. I was just being lazy and not bothering to update all the skin files, just the main Python script. It's all sorted now after that.
