### ISSUE TITLE
MQTT publishing but website not connecting to server

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#378]
I recently had a DNS issue and since then ive noticed that MQTT isn't connecting to the server. Since I dont really understand how it works, Im hoping someone here can help? 
I get data from WeeWx and it publishes : restx: MQTT: Published record 2020-09-01 10:02:37 EDT (1598968957)
but when I go to my site : imagingphototech.com it says connecting then cannot connect. 
I feel like at some point, some .conf I added a hardcoded IP as the redirect from my server was fouling it up, but I checked the weewx.conf, skin.conf and mosquito.conf and I dont see anything. Ports are open, 1883, and 9001. 
Sep  1 10:07:49 raspberrypi weewx[19048]: restx: MQTT: service version is 0.19
Sep  1 10:07:49 raspberrypi weewx[19048]: restx: MQTT: binding to ['archive', 'loop']
Sep  1 10:07:49 raspberrypi weewx[19048]: restx: MQTT: topic is weather
Sep  1 10:07:49 raspberrypi weewx[19048]: restx: MQTT: desired unit system is US
Sep  1 10:07:49 raspberrypi weewx[19048]: restx: MQTT: data will be uploaded to mqtt://pi:xxx@localhost:1883/
Sep  1 10:07:49 raspberrypi weewx[19048]: engine: Finished loading service user.mqtt.MQTT
this all seemed to work until Sunday when I rebooted the router and lost my IP/DNS server which ive since fixed.

**Comment by slvrscoobie** [comment]
I think I figured it out. After changing the DNS I changed over to Cloudflare DNS too - which doesn't proxy 9001 :/ 
Great. Well thats Useless then.

**Comment by slvrscoobie** [comment]
yup - turned off the Proxied dns server and boom its working again.

**Comment by falkyre** [comment]
For Cloudflare, the proxied websockets are over port 80 or port 443 for SSL.  The ports you can use are listed here:  https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy but they suggest 80, 443 or port 8443 for websockets.  FYI, if you are using Traefik V2, the latest version (V2.2.10) breaks the ssl websocket.  There's a fix but it's not been pushed out yet.  I rolled back to V 2.2.8 and it's working again.
