### ISSUE TITLE
Unable to publish to MQTT broker over SSL on Mac

### ISSUE THREAD

**Issue by uajqq** [poblabs/weewx-belchertown#379]
I just transitioned my site to SSL and I'm having an issue publishing to MQTT on the remote broker via SSL. I've updated everything according to the how-to but weewx can't publish via MQTT over port 8883, and manually trying to publish from the client where weewx is running gives me the following error:

```
> mosquitto_pub -h <hostname>.com -p 8883 -t "weather/test" -m "hello" -u "<user>" -P "<password>"
Error: The connection was lost.
```

MQTT config file on the broker:

```
persistence false

allow_anonymous true
password_file /etc/mosquitto/passwd

acl_file /etc/mosquitto/acl

# Insecure mqtt to localhost only, and secure mqtt
listener 1883 localhost
listener 8883
certfile /etc/letsencrypt/live/<hostname>.com/cert.pem
cafile /etc/letsencrypt/live/<hostname>.com/chain.pem
keyfile /etc/letsencrypt/live/<hostname>.com/privkey.pem
protocol mqtt

# websockets
listener 9001
certfile /etc/letsencrypt/live/<hostname>.com/cert.pem
cafile /etc/letsencrypt/live/<hostname>.com/chain.pem
keyfile /etc/letsencrypt/live/<hostname>.com/privkey.pem
protocol websockets
```

Belchertown skin says "Connected," but just waits forever for an update, so I know websockets is working correctly. Ports 1883, 8883, and 9001 are open on the firewall. Am I missing something obvious?

**Comment by tomdotorg** [comment]
I have a similar situation. I installed LetsEncrypt via Certbot for one nginx virtual host. I did not do anything about mqtt. The ssl-enabled vhost works fine, but now mqtt is not being retrieved from the web page, although mqtt is still publishing and a command-line mqtt client can pick up the data over 9001/websockets. It's just the web page that is not updating.

**Comment by poblabs** [comment]
@uajqq Everything looks good from here best I can tell. Have you rebooted your mqtt server? You could also adjust this, and try publishing to 1883

`listener 1883 localhost` to `listener 1883` and restart mqtt service or host. 

---

@tomdotorg Once your site goes https, your need to use mqtt secure. You can't have a mixed environment. Thats why http works but not https.

**Comment by uajqq** [comment]
> Have you rebooted your mqtt server?

I did try both restarting the mosquitto service and rebooting the server, but no luck.

> You could also adjust this, and try publishing to 1883
> 
> `listener 1883 localhost` to `listener 1883` and restart mqtt service or host.

I just tried that, and I'm still getting a "The connection was lost" error.

Running `openssl s_client -connect <server>.com:8883 -showcerts` successfully connects and shows the certificates, so I know the ports are getting opened correctly.

I notice that if one uses `mosquitto_pub` to manually publish information, there is an available option to specify a certfile on the command line. When setting this up, I only installed certbot and the certificates on my remote server. I didn't install anything on my local machine, which runs weewx. Is that the issue I'm having?

**Comment by poblabs** [comment]
> Is that the issue I'm having?

Could be. Does your weewx config look like this? (this is mine). If not, adjust and restart weewx. 

```
    [[MQTT]]
        server_url = mqtt://username:password@hostname:8883/
        topic = weather/weewx
        unit_system = US
        binding = archive, loop
        aggregation = aggregate
        [[[tls]]]
            tls_version = tlsv1
            ca_certs = /etc/ssl/certs/ca-certificates.crt
```

**Comment by uajqq** [comment]
Ah okay, that's the issue then. My `/etc/ssl/certs/` directory is empty on the local machine. Do I need to copy the keys from the server to my local machine, or generate new keys on the local machine?

**Comment by poblabs** [comment]
it might be a little different for you machine - do you have `ca-certificates.crt` anywhere on your system?

Run this to find out? `sudo find / -name "ca-certificates.crt"`

**Comment by uajqq** [comment]
It looks like MQTT is looking for what amounts to the keychain on a Linux system, but MacOS has its own system keychain that can't be accessed in that manner (am I understanding that correctly?).

I've been Googling and it seems like some people get around this by exporting the keychain to a file and then pointing their program at that. I've been trying to do this--I've tried exporting the entire system keychain, the Let's Encrypt intermediate certificate, and the AAA root certificate, and pointed weewx at all of them, but no luck. Permissions seem to be set correctly. 

I'll update here if I ever figure it out, in case some other Mac user is having this problem too.

**Comment by poblabs** [comment]
An I didn't realize you were on a Mac. I have no experience with that. Good
luck!

**Comment by poblabs** [comment]
Closing this, but feel free to continue to update us on your progress!

**Comment by uajqq** [comment]
Okay, got it figured out. Might be a little clumsy:

1. Download the CA Certificate bundle from Mozilla, which has been collected here: https://curl.haxx.se/docs/caextract.html
2. Place that file anywhere. I put it in the weewx root.
3. Point the TLS stanza under MQTT at it, like so (example from my Mac). Note that specifying `tls_version = tlsv1` doesn't work for some reason, so it has to be left out: 

```
[[[tls]]]
    ca_certs = /Users/Shared/weewx/cacert.pem
```

And that fixes it!
