### ISSUE TITLE
Dark_logo

### ISSUE THREAD

**Issue by FutureCow** [poblabs/weewx-belchertown#380]
This PR: https://github.com/poblabs/weewx-belchertown/pull/302 added the possibility to add a dark skin logo. 
This is working fine when you use the dark <-> light button on the page. But when it's nighttime and the dark mode is activated automatically, it is using the light logo.

**Comment by poblabs** [comment]
@kwalkerk are you experiencing this behavior?

**Comment by FutureCow** [comment]
@poblabs: You can see it at my website: https://wolderwijdweer.nl/

**Comment by kwalkerk** [comment]
Just saw this, I’ll have to wait till tonight to see if I get that behavior.

**Comment by poblabs** [comment]
I can't seem to find the error, but I do see it on your site. Can you upgrade to the latest `skins/belchertown/js/belchertown.js.tmpl` file? I've added more debugging to see if I can make sense of it.

**Comment by kwalkerk** [comment]
I have replaced the file with the current one from GitHub

**Comment by poblabs** [comment]
Ok - I don't see it updated yet but I will keep trying

**Comment by poblabs** [comment]
Can you confirm you've updated it? Your website has gone through 3 archive intervals and it's still not there. Thanks

**Comment by FutureCow** [comment]
I've also updated my site, but it wil take some time before it's dark enough...

**Comment by kwalkerk** [comment]
How can I tell?  I definitely copied the file from the current GitHub release version

**Comment by poblabs** [comment]
Sorry, I think I'm looking at @FutureCow's site which hasn't been updated yet. @kwalkerk whats your website? 

You can tell by looking at /js/belchertown.js file in your HTML folder, and looking for `belchertown_debug("Theme: logo_image_dark is defined.");`

**Comment by kwalkerk** [comment]
my site:  http://squatleyweather.ddns.net/belcherwithflights/ <http://squatleyweather.ddns.net/belcherwithflights/> or http://squatleyweather.ddns.net <http://squatleyweather.ddns.net/>

The second one does not have the flightradar24 stuff

**Comment by poblabs** [comment]
Thanks. Neither of your sites has the new file either. [Double check you're downloading this one. ](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl)

**Comment by kwalkerk** [comment]
Just updated with the file from the link you sent

two sites:

1) http://squatleyweather.ddns.net/belchertown/ <http://squatleyweather.ddns.net/belchertown/>    - no flight radar
2) http://squatleyweather.ddns.net/belcherwithflights/ <http://squatleyweather.ddns.net/belcherwithflights/> = with flight radar

**Comment by poblabs** [comment]
Oops - Now your graphs aren't working at all 😄 You need to also update bin/user/belchertown.py [with this file here](https://github.com/poblabs/weewx-belchertown/blob/development/bin/user/belchertown.py), then restart weewx.

**Comment by kwalkerk** [comment]
Just did that, graphs still not working

**Comment by poblabs** [comment]
Did you restart weewx?

I just pushed a large commit, and updated the development to 1.2rc3, it may be worth updating **every file** again to be up to date.

**Comment by kwalkerk** [comment]
Yes.  Even rebooted the Pi. No joy

**Comment by poblabs** [comment]
Ok try updating everything again, all files, everything. With a restart. You should be on 1.2rc3 after.

Easiest way is to run

`wget https://github.com/poblabs/weewx-belchertown/archive/development.zip`

Then `wee_extension --install development.zip`

`service weewx restart`

**Comment by kwalkerk** [comment]
Have done that. Graphs still not working

**Comment by kwalkerk** [comment]
Rebooted Pi, graphs now working.  Don’t know if that helps debug the original issue :)

**Comment by FutureCow** [comment]
i also updated to rc3
https://wolderwijdweer.nl/

**Comment by poblabs** [comment]
Fixed! Thanks for the help. Update to the latest header.html.tmpl file, or re-download the development.zip file and re-installing. Restart weewx when done
