### ISSUE TITLE
How do i add wind gauges on my front page?

### ISSUE THREAD

**Issue by HyperDevil** [poblabs/weewx-belchertown#381]
How to i add wind rose / gauges on my front page?
I renamed graph.conf.example to graph.conf but i see no difference.

**Comment by poblabs** [comment]
You have to add the graphs too the file that you want. Check the wiki it
explains all of this

**Comment by HyperDevil** [comment]
Thanks that helped me a lott.
The wind rose now shows direction and speed for today, perfect!

Although the hayschar does not work:

`Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 1374, in run
    series_data = self.get_observation_data(binding, archive, observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length, xAxis_groupby, xAxis_categories, mirrored_value, weatherRange_obs_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 1827, in get_observation_data
    raise Warning( "Error trying to use database binding %s to graph observation %s. Error was: %s." % (binding, obs_lookup, e) )
Warning: Error trying to use database binding wx_binding to graph observation haysChart. Error was: haysChart.
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 1374, in run
    series_data = self.get_observation_data(binding, archive, observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length, xAxis_groupby, xAxis_categories, mirrored_value, weatherRange_obs_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 1827, in get_observation_data
    raise Warning( "Error trying to use database binding %s to graph observation %s. Error was: %s." % (binding, obs_lookup, e) )
Warning: Error trying to use database binding wx_binding to graph observation haysChart. Error was: haysChart.
`

Is there maybe a mapping missing of some sort?

**Comment by poblabs** [comment]
That chart requires you to be running the development version of the skin.
are you running the development version of the skin?

**Comment by HyperDevil** [comment]
Ok thanks i did not!
Also (off topic), the icon that shows the current weather (sun, clouded etc) is not present.
Is that related due to not having the prediction enabled or could there be something else wrong?

**Comment by poblabs** [comment]
You'll need to have forecasting enabled through Aeris or darksky
