### ISSUE TITLE
Apply Dark theme to Highcharts menu?

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#384]
The highcharts export menu works great, but with Dark theme enabled it is very hard to read. I have been looking at the css for the highcharts menu and found that the .highcharts-menu class is not present in belchertown-dark.min.css. I also don''t know if this can be implemented easily like the other Highcharts classes. It would be nice if the menu showed the same (inverted) colors like the tooltip.

![Highcharts menu wazig](https://user-images.githubusercontent.com/67259651/92491830-fa2f3980-f1f2-11ea-9075-9539577ba625.png)

**Comment by poblabs** [comment]
Should be all set in the last commit. Download the latest belchertown-dark.min.css from development. Thanks!

**Comment by ArendPWS** [comment]
Thank you Pat! Works great!
