### ISSUE TITLE
Pi Theme doesn't display "Feels Like" without MQTT

### ISSUE THREAD

**Issue by fleabearded** [poblabs/weewx-belchertown#385]
The Pi theme doesn't display the "Feels Like" temperature unless you enable MQTT.

**Comment by poblabs** [comment]
I don't think that's accurate. [If the appTemp has data, it's shown right on load.](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/pi/index.html.tmpl#L86-L88). Then if appTemp is in MQTT, it gets updated.

**Comment by poblabs** [comment]
I guess I should ask; which version of the skin are you running? What I pasted is from the 1.2 beta.

**Comment by fleabearded** [comment]
It was on 1.1. I updated to 1.2 last night with the release version and it's now displaying properly
