### ISSUE TITLE
Home page graphs

### ISSUE THREAD

**Issue by quinntj** [poblabs/weewx-belchertown#386]
Hello! This isn't so much a feature request I don't think.... but I'm trying to figure out how to get a graph, specifically the year temperature range graph to fill 2 graph spots on my home page... I can't seem to figure that out.
i.e. I'd like that on it's own row, instead of in column 1 of 2 in the existing row.

my page is here: http://weather.battle4heaven.com/arvada/

any assistance is greatly appreciated, this skin is amazeballs! Thank you for creating it!

**Comment by poblabs** [comment]
Specify the width and height you want. For example, here's my full size weatherRadial graph on belchertownweather.com

```
[day]
    title = Today since Midnight
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300
    [[weatherRangeChart]]
        title = Temperature Ranges for This Year
        time_length = year
        tooltip_date_format = "LL"
        width = "100%"
        height = "600px"
        [[[weatherRange]]]
            range_type = outTemp
```

![image](https://user-images.githubusercontent.com/3484775/92628063-41bcd080-f29a-11ea-9272-4386214aa158.png)

**Comment by quinntj** [comment]
Awesome! Thank you!!
