### ISSUE TITLE
Pressure displays in wrong units when MQTT is on

### ISSUE THREAD

**Issue by loudelatorre** [poblabs/weewx-belchertown#387]
**Describe the bug**
When live data starts coming in the barometer switches from 1017.2 mbar to 30.0 mbar.  Unit for pressure set to mbar in weewx.conf; all other units are set to US.

**Link to your website**
not online - this is going to be a kiosk type implementation

**Version of the skin you're using**
1.1

**To Reproduce**
Steps to reproduce the behavior: change group pressure to mbar; rest to us units

    [[Defaults]]
        
        [[[Units]]]
            
            # The following section sets what unit to use for each unit group.
            # NB: The unit is always in the singular. I.e., 'mile_per_hour',
            # NOT 'miles_per_hour'
            [[[[Groups]]]]
                
                group_altitude = foot    # Options are 'foot' or 'meter'
                group_degree_day = degree_F_day    # Options are 'degree_F_day' or 'degree_C_day'
                group_distance = mile    # Options are 'mile' or 'km'
                group_pressure = mbar    # Options are 'inHg', 'mmHg', 'mbar', or 'hPa'
                group_rain = inch    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = inch_per_hour    # Options are 'inch_per_hour', 'cm_per_hour', or 'mm_per_hour'
                group_speed = mile_per_hour    # Options are 'mile_per_hour', 'km_per_hour', 'knot', or 'meter_per_second'
                group_speed2 = mile_per_hour2    # Options are 'mile_per_hour2', 'km_per_hour2', 'knot2', or 'meter_per_second2'
                group_temperature = degree_F    # Options are 'degree_F' or 'degree_C'
            
The initial generated page will have the correct pressure in mbars but when MQTT updates begin it will change to pressure in inHg with the wrong unit displayed (mbar)

**Expected behavior**

Expect the current pressure update to retain the unit set at weewx.conf pressure group.

**Screenshots**

**Device Information (please complete the following information):**
 - Device: Raspberry Pi
 - OS: Raspberry Pi OS
 - Browser Chromium
 - Version 78.0.3904.108

**Additional context**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
This happens because your station_observation variable in skin.conf has barometer, but I'm pretty sure your MQTT extension is sending altimeter or pressure. Reference https://github.com/weewx/weewx/wiki/Barometer,-pressure,-and-altimeter

Chances are you want something other than barometer? If so you can update your skin.conf station_observation variable to show either pressure or altimeter. If you want barometer, then I think you'll need to adjust the MQTT extension settings as seen in https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099

**Comment by loudelatorre** [comment]
Yep.  That did it.  Added this at end of [[MQTT]]:

        [[[inputs]]]
                [[[[barometer]]]]
                        name = barometer_mbar
                        units = mbar

Sorry I didn't search the closed issues.  When I looked under issues it only showed open ones...

**Comment by poblabs** [comment]
No problem glad that did it
