### ISSUE TITLE
Some weather icon additions

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#388]
I discovered that 3 different weather conditions (mostly clear, partly cloudy and mostly cloudy) were generating the same icon.  As there is not room to display text with an hourly forecast (see #338), I have generated a mostly clear and mostly cloudy icon in both day and night versions.  See the attached images to see the effect.
I'm not sure how modifying these agrees with the permission you have to use the original icons I have modified.
I also discovered that Aeris were not using the equivalent of a mostly clear icon, and have raised that with them.  They say it will be fixed in the next release of their API.

Will do a PR for the icons, when I've cracked how to do it!

Michael

lordshipweather.uk

**Comment by michaelundwd** [comment]
Sorry, lost the images
![icons_new](https://user-images.githubusercontent.com/45148992/92626922-8a887f80-f2c2-11ea-96c0-1462c037d3a7.png)
![icons_original](https://user-images.githubusercontent.com/45148992/92626938-907e6080-f2c2-11ea-81b8-4750fd08ae72.png)

**Comment by poblabs** [comment]
This is amazing! I'd like you to get the credit so try the PR.  If you can't figure out a PR, you can attach them here and I'll merge them in. 

![image](https://user-images.githubusercontent.com/3484775/92628785-577ec580-f29b-11ea-9253-174deb8eca78.png)

**Comment by michaelundwd** [comment]
I'll try and do a PR; I have to learn it sometime!  Besides there are some dictionary changes as well.
Is there anything to stop us modifying these icons?
I think there are some more changes that could be made to extend the icon list for some of the other conditions.  Are you happy for me to have a go at that - after I've got the forecast working!
