### ISSUE TITLE
Layout on Chromebooks, etc. with 1200px width misaligns grid

### ISSUE THREAD

**Issue by bburton** [poblabs/weewx-belchertown#392]
**Problem description**

My Chromebook has a device width of 1200 pixels.  However, when viewing the latest development branch for 1.2, the formatting of the temperature grid is misaligned with some of the other observations to the right. In addition, the margins/padding are over an inch wide. Also, the Aeris forecasting splits to 5 days on one line and 2 days on the next.

**Screen shot**
![Belchertown 1200px width defect 2020-09-10](https://user-images.githubusercontent.com/173415/92846612-437bb680-f3b6-11ea-9f31-da9cd8605516.png)

**Version of the skin you're using**
1.2b3 through 1.2rc3 (9-Sep-2020)

**To Reproduce**
View site in Chome or Firefox Inspector on any desktop or laptop and adjust to 1200px wide.

**Expected behavior**
Site should be properly aligned with no wrapping at 1200px width.

**Device Information:**
 - Device: Samsung Chromebook
 - OS: ChromeOS 84.0.4147.110 (official Build) (32-bit)
 - Browser: Chrome
 - Version: 84.0.4147.110 (official Build) (32-bit)

**Proposed fix**
In style.css on line 839, change:
```css
@media only screen and (max-width: 1200px) {
```
to
```css
@media only screen and (max-width: 1196px) {
```
The problem was that when the browser width was exactly 1200px, the media query changed the max-width to 960px. With this change, the 960px max-width doesn't take effect until slightly less than 1200px. It seemed 1196px was needed as 1198 or so didn't work.

On my Chromebook, the skin now formats correctly with no margins or padding. I'm not noticing anything truncated on either side. Also tested in Firefox on desktop Linux by manually changing the width slowly to see the breakpoints take effect.

**Comment by poblabs** [comment]
Thanks for the proposed fix! I just tested it out and I don't see it acting any different like you've mentioned so I pushed the fix to development.
