### ISSUE TITLE
Bug Of Wind Rose beauford  "color" 

### ISSUE THREAD

**Issue by Bug-Storm** [poblabs/weewx-belchertown#395]
Hii 

i've the last developper skin!

Of the wind rose have a bug of the " beauford" option 

On Belchertown Chart Doc , the code for wind rose is
```[[roseplt]]
    title = Wind Rose
    [[[windRose]]]
        beauford0 = “#1278c8
        beauford1 = “#1fafdd
        beauford2 = “#71bc3c
        beauford3 = “#ffae00
        beauford4 = “#ff7f00
        beauford5 = “#ff4500
        beauford6 = “#9f00c5
```

but of the V 1.2rc3 the color is black 
![chrome_jP65pUU4Ru](https://user-images.githubusercontent.com/68688876/92944839-cb180280-f454-11ea-8c70-179c482d47d7.png)

the correct code is  

```[[roseplt]]
    title = Wind Rose
    [[[windRose]]]
``` 

without of beauford 
![chrome_KN0SjMQXUL](https://user-images.githubusercontent.com/68688876/92944984-f569c000-f454-11ea-8f4e-80c303e18bb3.png)

**Comment by poblabs** [comment]
Well the beauford's are missing the ending `"` which causes them to be black. If you wanted to change colors this is the right way to do it. I'll update the wiki doc to have the ending `"` after the colors. 

Without the beauford's you get the standard colors. This option exists for those who want non-standard colors.
