### ISSUE TITLE
Adjustment problem with new font

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#398]
Due to new font Roboto in 1.2 release, I have a small shift of feel-like info, in 2 lines instead of 1 line
Is it possible to enlarge feel-like info? or reduce padding left

Thanks
![shift](https://user-images.githubusercontent.com/65628453/92998708-bfdbda00-f51b-11ea-87f9-e8ebcb809a92.jpg)

**Comment by poblabs** [comment]
Whats the link to your site?

**Comment by ddperso** [comment]
https://meteo-auffargis.decoodt.eu

**Comment by ddperso** [comment]
but for the moment, I don't use Roboto font

**Comment by poblabs** [comment]
Can you set it back to roboto? I want to take a look at a solution

**Comment by ddperso** [comment]
Done

**Comment by ddperso** [comment]
Ooops....
After restarting my PC, the roboto font has changed in appearance! may be a cache effect of chrome...
Now it's OK 

Sorry, 
I close this issue
