### ISSUE TITLE
Use current theme color as background in chart export

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#402]
:bulb: **The Idea**
When exporting, the default background color of the chart is white in both themes. It would be nice if the color of the theme was used as background color when exporting. When using dark theme, charts with a dark background would look great!

**HELP WANTED**
Have been searching which styling rules would need to change to make this possible, but so far haven't been able to find the appropiate rules.

**Comment by poblabs** [comment]
Interesting idea! The exporter is highcharts code - not Belchertown code - but I wonder if there's a way to define it? I'll have to research.

**Comment by poblabs** [comment]
This might be something to test out. I'll give it a try https://stackoverflow.com/a/45966131/1177153

**Comment by poblabs** [comment]
For my future self:

```
$( ".highcharts-background" ).css( "fill" );
"rgb(42, 42, 43)"

$( ".highcharts-background" ).css( "fill" );
"rgb(255, 255, 255)"
```

**Comment by 41south** [comment]
Back to the future!

**Comment by ArendPWS** [comment]
> This might be something to test out. I'll give it a try https://stackoverflow.com/a/45966131/1177153

Already tried that one without success. This gets overruled by the styling in belchertown-dark.min.css? But maybe you find a way to get it to work. Styling is not my favorite thing :-).

**Comment by ArendPWS** [comment]
Found this option:

[Styled mode](https://api.highcharts.com/highcharts/chart.styledMode)

Adding this to var options in belchertown.js.tmpl.

chart: {
   renderTo: '',
   spacing: [5, 10, 10, 0],
   type: '',
   zoomType: 'x',
   styledMode: true
},

Resulted in the right background (Dark theme that is) when exporting:

![temperatuur (2)](https://user-images.githubusercontent.com/67259651/93006392-00f3de80-f55c-11ea-9e0d-f8ae9194dcf9.png)

But the lines in the chart among other things have gone missing. This would need a lot of new CSS being implemented?
In Light theme the charts are turned into a collection of black rectangles using this option.

**Comment by poblabs** [comment]
I don't think so. I think we use jQuery to grab the `fill` css property, then dynamically replace the export options. Something like this. 

in theme switcher:
```
var export_background = jQuery( ".highcharts-background" ).css( "fill" );
```

Then in the chart code:

```
exporting: {
  chartOptions: {
    chart: {
      backgroundColor: '#9E9E9E'
    }
  }
}
```

Not tested but I have time now to work on it.

**Comment by poblabs** [comment]
Not working like I had hoped. So far it seems like you have to re-draw the chart in order to change the background color. I might have to ask in the highcharts forums

**Comment by poblabs** [comment]
> This would need a lot of new CSS being implemented?

Yes it looks like it, and it also would ignore the color settings in graphs.conf. 

What I was able to get working was setting the export color of the chart on page load. So if you load the page in dark mode, the chart will export in dark mode. 

![temperature (1)](https://user-images.githubusercontent.com/3484775/93007292-55379800-f535-11ea-9c1e-d30c1aa6db86.png)

Still some color issues even with this option though. 

Would this be an acceptable work-around? 

Otherwise I'm starting to wonder if this isn't easily doable to switch them dynamically.

**Comment by ArendPWS** [comment]
I think we are getting close. Tried the "styledMode: true" option again.

chart: {
renderTo: '',
spacing: [5, 10, 10, 0],
type: '',
zoomType: 'x',
styledMode: true
},

But now also included the default highcharts.css in Belchertown style.css like this (putting it on top of that file):

![Adding highcharts css to belchertown style css](https://user-images.githubusercontent.com/67259651/93015109-029ec000-f5b7-11ea-98d4-04885b5fc848.png)

Export now looks like this:

![temperatuur (2)](https://user-images.githubusercontent.com/67259651/93015045-5eb51480-f5b6-11ea-89d6-a8e0a62730e5.png)

The problems now seem to be that the css of the chart titles is ignored when exporting and color support from graphs.conf is lost on the pages as you mentioned before.

On the other hand I noticed that the text/font in the export menu has somehow become more clear/better-looking.

![Screenshot met styledMode](https://user-images.githubusercontent.com/67259651/93015497-4646f900-f5ba-11ea-9fd7-00c086e88f9c.png)

**Comment by poblabs** [comment]
Styled chart would ignore the graphs.conf color settings so that's not a viable option

**Comment by ArendPWS** [comment]
> Styled chart would ignore the graphs.conf color settings so that's not a viable option

Yes, I guess it will not be of interest to most users. But I have been playing around with this setting and managed to get it to work the way I want. Maybe you could make it optional? To make it work, the two most important things to do are:

1. Remove the class .highcharts-title from belchertown-dark.min.css. This class was blocking new css and has no role in dark theme?
2. Add the styledMode: true to chart options. If this setting was optional in graphs.conf there would be no need to "hack" the code.

I have put all new required CSS in custom.css (HTML_ROOT).

Configuring graphs.conf is somewhat different now ofcourse, using classes instead of colors. So here is my example export of how it looks like now switching to styled mode using dark theme export:

![wind-speed-and-direction](https://user-images.githubusercontent.com/67259651/93081985-6e089080-f690-11ea-88d9-fd4b96a8a659.png)

**Comment by ArendPWS** [comment]
Have decided to stick with styledMode for now. Had to do a few other "hacks" to make the tooltips look good. Unless someone comes up with a better solution or a better solution will come along in the future, for now I think it's best to close this issue?
