### ISSUE TITLE
Is "extending database" still needed?

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#403]
Hi,

I installed now a complete new Weewx installation and I am wondering if 
https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database

is still needed?

I noticed the following line in weewx.conf

`schema = schemas.wview_extended.schema`

Br,
Johannes

**Comment by poblabs** [comment]
It all depends. If you're using weewx v4 extended then no you don't need to expand the database. Best way to check is open your database. Go to the archive table. And check the columns. If the observation you want is the name of a column then you don't need to do anything.
