### ISSUE TITLE
Show alert when forecast is disable

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#404]
:bulb: **The Idea**
Show the alert when `forecast_enabled = 0` and `forecast_alert_enabled = 1`
At the moment, not work.

**Comment by poblabs** [comment]
This isn't possible because the alert comes from the forecast. So it needs to be enabled to work

**Comment by Drealine** [comment]
If you make the process but not showing the forecast on website, is not possible ?

**Comment by poblabs** [comment]
You can hide the forecast row using the custom.css file and setting the
forecast element to display:none

**Comment by Drealine** [comment]
Thank's. It work.
