### ISSUE TITLE
Translation of Aeris alert comment

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#406]
Hi

Is it possible to translate (in franch for me) the comment of aeris alert?
if yes, where I can do it?
if not, how I can disable the hyperlink to avoid the comment window in english and french?

Thanks

My site: https://meteo-auffargis.decoodt.eu
Release 1.2

![aeris alert](https://user-images.githubusercontent.com/65628453/93140238-6671d780-f6e2-11ea-8cb8-5c15476ef378.jpg)

**Comment by poblabs** [comment]
Make sure your forecast_lang is correct. 

If you want to disable, set forecast_alert_enabled to 0

More details here: https://github.com/poblabs/weewx-belchertown#forecast-options

**Comment by ddperso** [comment]
forecast_lang = "fr" and the description of the alert is in english...
[image: image.png]

**Comment by poblabs** [comment]
You'll have to contact Aeris. The skin does not translate that

**Comment by ddperso** [comment]
In your documentation, it's only par darksky, but for aeris, I'm not sure
that it's possible, I read the aeris documentation and apparently only
english is available. But I am not a programmer....
I try to understand your program and I have not found the forecast_lang
parameter

Didier

**Comment by poblabs** [comment]
This page claims it can be translated into English, French and Spanish: https://www.aerisweather.com/support/docs/api/reference/endpoints/alerts/

And you're right! The `forecast_lang` is only on DarkSky - looks like I forgot Aeris. Let me add that

**Comment by poblabs** [comment]
Download this new belchertown.py file and replace it with what you have: https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py

Restart weewx

**Comment by ddperso** [comment]
I have an error during wee_reports, may be I have forgot something...

root@meteo:~# systemctl restart weewx.service
root@meteo:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in
_getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 899, in
get_extension_list
    forecast_alerts_url = "
https://api.aerisapi.com/alerts/%s,%s?&format=json&limit=%s&lang=%s&client_id=%s&client_secret=%s"
% ( latitude, longitude, forecast_alert_limit, forecast_lang,
forecast_api_id, forecast_api_secret )
UnboundLocalError: local variable 'forecast_lang' referenced before
assignment

**Comment by poblabs** [comment]
Nope that was my fault. 

Try again by downloading the new file, restart weewx

**Comment by ddperso** [comment]
It's better (no error) but always english + french in comment alert..
I have restarted my virtual machine but nothing change

**Comment by poblabs** [comment]
Screenshot?

**Comment by ddperso** [comment]
It's OK now !!!!!
May be an chrome cache effect...
Many thank's Pat

You can close this issue

![aeris](https://user-images.githubusercontent.com/65628453/93254021-ff165f00-f797-11ea-98db-499a93d9419e.jpg)

**Comment by poblabs** [comment]
Excellent!
