### ISSUE TITLE
Y-axis shows too many labels (ticks?) in barometer chart

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#408]
My weatherstation has a barometer with only 1 mbar/hpa accuracy/resolution (no decimals). After many attempts I have not succeeded getting the chart to display in a "normal" way. There are to many labels on the y-axis showing the pressure.

![barometer](https://user-images.githubusercontent.com/67259651/93328488-14cd6800-f81c-11ea-9959-e252bf86808e.png)

My graphs.conf for the barometer settings looks like this:

    [[chart4]]
        title = Barometer
        [[[barometer]]]
            yAxis_tickinterval = 0.5
            [[[[numberFormat]]]]
                decimals = 0
                thousandsSep = ""

I would like it to show something similar like the WeeWX Seasons chart :

![daybarometer](https://user-images.githubusercontent.com/67259651/93328987-ce2c3d80-f81c-11ea-9171-f9cc79c9804f.png)

Or something like Wunderground:

![Wunderground](https://user-images.githubusercontent.com/67259651/93329040-e3a16780-f81c-11ea-981f-5b7cc1978a58.png)

Why are there so many gridlines in the Highcharts barometer chart? Is this specific to this chart?

Is it possible that the reason for this behaviour has something to do with numberformatting performed by highcharts?

**Comment by poblabs** [comment]
Try changing your `yAxis_tickinterval = 0.5` to `yAxis_tickinterval = 1.0` and send me a screenshot

**Comment by ArendPWS** [comment]
First screenshot: yAxis_tickinterval = 1.0 decimals = 0

![barometer_interval_1_dec_0](https://user-images.githubusercontent.com/67259651/93368668-8faf7680-f84e-11ea-9870-5043561c61a1.png)

Second screenshot: yAxis_tickinterval = 1.0 decimals = 1

![barometer_interval_1_dec_1](https://user-images.githubusercontent.com/67259651/93368782-b40b5300-f84e-11ea-98f5-b42ece61ca04.png)

Anything I can think of that might be of help:

WeeWX 4.1.1
Belchertown 1.2 (latest master)
WeeWX database: target_unit = US

**Comment by ArendPWS** [comment]
Found what caused the problem.

Commenting out this part of belchertown.js.tmpl  makes the chart look normal.

Maybe this can be changed to support barometers with no decimal output?

                // Barometer chart plots get a higher precision yAxis tick
                if (s.obsType == "barometer") {
                    if ( typeof s.yAxis_tickInterval === "undefined" ) { 
                        // If no tick interval override, set 0.01 as default tick interval to satisfy an old request for this level of precision. 
                        options.yAxis[this_yAxis].tickInterval = 0.01;
                    }
                    // Define yAxis label float format if rounding is defined. Default to 2 decimals if nothing defined
                    if ( typeof s.rounding !== "undefined" ) {
                        options.yAxis[this_yAxis].labels = { format: '{value:.'+s.rounding+'f}' }
                    } else {
                        options.yAxis[this_yAxis].labels = { format: '{value:.2f}' }
                    }
                }



![barometer _ok](https://user-images.githubusercontent.com/67259651/93377940-043ce200-f85c-11ea-9bdb-8b42d7af1b40.png)

**Comment by poblabs** [comment]
Did you comment out the whole barometer section?

Does your weewx.conf have `mbar = %.1f` under `[[[[StringFormats]]]]`?

**Comment by ArendPWS** [comment]
**TEST 1: using original belchertown.js.tmpl:**

                // Barometer chart plots get a higher precision yAxis tick
                if (s.obsType == "barometer") {
                    if ( typeof s.yAxis_tickInterval === "undefined" ) { 
                        // If no tick interval override, set 0.01 as default tick interval to satisfy an old request for this level of precision. 
                        options.yAxis[this_yAxis].tickInterval = 0.01;
                    }
                    // Define yAxis label float format if rounding is defined. Default to 2 decimals if nothing defined
                    if ( typeof s.rounding !== "undefined" ) {
                        options.yAxis[this_yAxis].labels = { format: '{value:.'+s.rounding+'f}' }
                    } else {
                        options.yAxis[this_yAxis].labels = { format: '{value:.2f}' }
                    }
                }


WeeWX.conf:

            # The following section sets the formatting for each type of unit.
            [[[[StringFormats]]]]
                
                mbar = %.0f

Graphs.conf (just a clean barometer leaf, no other settings):

    [[chart4]]
        title = Barometer
        [[[barometer]]]

![barometer_weewx_conf_mbar_0f_graphs_conf_blank](https://user-images.githubusercontent.com/67259651/93452080-47d53180-f8d8-11ea-999d-8cf2351f0f02.png)

<hr />

**TEST 2: modified belchertown.js.tmpl (commented out "old request"):**

                // Barometer chart plots get a higher precision yAxis tick
                if (s.obsType == "barometer") {
                    /*if ( typeof s.yAxis_tickInterval === "undefined" ) { 
                        // If no tick interval override, set 0.01 as default tick interval to satisfy an old request for this level of precision. 
                        options.yAxis[this_yAxis].tickInterval = 0.01;
                    }*/
                    // Define yAxis label float format if rounding is defined. Default to 2 decimals if nothing defined
                    if ( typeof s.rounding !== "undefined" ) {
                        options.yAxis[this_yAxis].labels = { format: '{value:.'+s.rounding+'f}' }
                    } else {
                        options.yAxis[this_yAxis].labels = { format: '{value:.2f}' }
                    }
                }

WeeWX.conf:

            # The following section sets the formatting for each type of unit.
            [[[[StringFormats]]]]
                
                mbar = %.0f

Graphs.conf (just a clean barometer leaf, no other settings):

    [[chart4]]
        title = Barometer
        [[[barometer]]]

![barometer_weewx_conf_mbar_0f_graphs_conf_blank_modified_belchertown_js_tmpl](https://user-images.githubusercontent.com/67259651/93453949-9683cb00-f8da-11ea-8b3b-af377d325d77.png)
