### ISSUE TITLE
Wind speed and gust displayed as m/s when being km/h (using mosquitto and metric)

### ISSUE THREAD

**Issue by jhans1** [poblabs/weewx-belchertown#41]
Im using metric and when you first access the page (before mosquitto values are loaded) it shows the correct values for wind speed in m/s. When mosquitto/websocks is connected and values are loaded the wind speed is still displayed as m/s but it is actually km/h and therefore reads too high. 
My weather station is a WH1080 (FineOffset).

[https://www.landaasbygda.no](url)

**Comment by poblabs** [comment]
If it's fine without MQTT, and wrong with MQTT websockets, then the problem is with the weewx-mqtt extension. You need to tell that extension what values you want sent with certain observations. See this post: https://github.com/poblabs/weewx-belchertown/issues/23#issuecomment-440529099

**Comment by jhans1** [comment]
Thank you!
