### ISSUE TITLE
Cloud Base shows twice the unit

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#411]
Hi,

I changed from a cheap weatherstation to a davis weatherstation. So far it looks good with your skin but I have a very small issue with the unit for cloudbase. It shows twice the unit:

Cloud Base | 1285 meter, meters

![image](https://user-images.githubusercontent.com/46743596/93569625-17ea6480-f992-11ea-906f-e4bd277cd09c.png)

I am not sure if it is because of the Skin, Weewx or the Weatherlink Live of Davis.

Any ideas?

Br,
Johannes

**Comment by poblabs** [comment]
Link to your site?

**Comment by ebnerjoh** [comment]
wetter.familie-ebner.at

**Comment by poblabs** [comment]
Everything looks ok from here. Maybe it is a cache issue with your browser?

**Comment by ebnerjoh** [comment]
I am checking now, but indeed, the issue is gone. maybe it was really just a cache issue.
