### ISSUE TITLE
"Average Climatical Values" and "Rain Totals" showing Data in wrong month

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#413]
Hello,

I am running now my new Weewx Installation since last Friday. 

I noticed now that the "Average Climatical Values" and "Rain Totals" are showing the current values in January. 
Could this be because my Weewx Installation is configured with "Rainseasion starting in January"?

wetter.familie-ebner.at

![image](https://user-images.githubusercontent.com/46743596/93844564-d57c9c80-fc9d-11ea-9e1f-9e5f013a92c3.png)

![image](https://user-images.githubusercontent.com/46743596/93844573-e0373180-fc9d-11ea-9cca-1823d948054d.png)

![image](https://user-images.githubusercontent.com/46743596/93844579-ea593000-fc9d-11ea-9dc7-f0345703d650.png)

![image](https://user-images.githubusercontent.com/46743596/93844593-fa710f80-fc9d-11ea-8ee9-384969cf93f3.png)

Br,
Johannes

**Comment by poblabs** [comment]
Does your database start at January?

If not, you need to follow the wiki. 

https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#xaxis_categories

> You will need to give the right labels, and do not expect all output to start with January. For example, if you start a new database in June, then you would use xAxis_categories = 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'. **It is up to you to provide the right labels for the data you're expecting. **

**Comment by ebnerjoh** [comment]
This might be the issue as i started with a new Database last week.

I will check the config.

**Comment by ebnerjoh** [comment]
Thanks, that was the issue!
