### ISSUE TITLE
Grouping days into months

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#414]
I am not sure if this can be easiliy implemented. Created a new chart combining daily rain and total rain for a month in one chart:

![rain-january-2020](https://user-images.githubusercontent.com/67259651/93899227-62eadb80-fcf4-11ea-9f73-d5faf28d6038.png)

Using these entries in graphs.conf:

    type = column
    aggregate_interval = 86400 # 1 day

    [[January]]
        aggregate_type = sum
        title = Rain january 2020
        time_length = month_specific
        month_specific = 1
        year_specific = 2020
        [[[rain]]]
            color = "#7cb5ec"
            borderColor = "#7cb5ec"
            name = Daily
            zIndex = 1
        [[[rainTotal]]]
            color = "#b2df8a"
            type = line
            name = Cumulative
            yAxis = 1

My question: how can I create a similar chart for a year with months? Is it possible to group the days into months (xAxis_groupby didn't work). The aggregate_intervals have to be specified per month? How can I turn the chart below into a similar chart as shown above.

![rain-2020](https://user-images.githubusercontent.com/67259651/93901713-19e85680-fcf7-11ea-81d6-f82b63de4e9c.png)

**HELP WANTED**

**Comment by poblabs** [comment]
You want a year chart, but the data on the x-axis to show each and every day?

**Comment by ArendPWS** [comment]
> You want a year chart, but the data on the x-axis to show each and every day?

The x-axis should show the data combined into months. If that is possible?

**Comment by poblabs** [comment]
Sounds similar to this example chart: https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#average-climate-values-chart

Try this?

```
[rainDays]
    title = "Rain Days"
    show_button = true
    button_text = Rain Days
    type = spline
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400

    [[chart2020]]
        title = "Average Climatological Values for 2020"
        time_length = year_specific
        year_specific = 2020
        xAxis_groupby = month
        xAxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        [[[rain]]]
            color = "#7cb5ec"
            borderColor = "#7cb5ec"
            name = Daily
            zIndex = 1
        [[[rainTotal]]]
            color = "#b2df8a"
            type = line
            name = Cumulative
            yAxis = 1
```

**Comment by ArendPWS** [comment]
> Sounds similar to this example chart: https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#average-climate-values-chart
> 
> Try this?
> 

Thank you Pat but this gives a different result then my first (working) example with months and days. I already have tried different combinations for the year/months chart. Maybe it has something to do with xAxis_groupby not working with what I have in mind?

![average-climatological-v](https://user-images.githubusercontent.com/67259651/93908071-74d17c00-fcfe-11ea-83e7-88142729d2aa.png)

**Comment by ArendPWS** [comment]
The combination month/days works perfectly. But as mentioned before, I can't get the year/months combination to work. Any idea where I should look in the code to help find a possible solution for this?

**Comment by ArendPWS** [comment]
Perhaps I found a first clue to solve this? Using these entries in graphs.conf, using only columns as chart type gives an accurate result:

	[raintotals]
		title = "Rain Totals by Month"
		show_button = true
		button_text = "Rain Totals"
		type = area
		aggregate_type = sum
		#aggregate_interval = 86400 # 1 day
		#aggregate_interval = 604800 # 1 week
		aggregate_interval = 2629800 # the length of a nominal month
		time_length = year_specific
		year_specific = 2020

		[[rain2020totals]]
			title = "Rain 2020"
			[[[rain]]]
				color = "#7cb5ec"
				borderColor = "#7cb5ec"
				name = "Monthly"
				zIndex = 1
			[[[rainTotal]]]
				color = "#b2df8a"
				borderColor = "#b2df8a"
				name = "Cumulative"
				yAxis = 1

![rain-2020_only_columns](https://user-images.githubusercontent.com/67259651/94053987-4d041600-fddb-11ea-9b06-12d24a22662d.png)

However changing the chart type into lines or splines shows a strange result. The data is present in the chart, but not visible:

![rain-2020_only_lines](https://user-images.githubusercontent.com/67259651/94054142-88064980-fddb-11ea-8b64-4187e5c0ce9d.png)

**Comment by ArendPWS** [comment]
Problem solved. To make it work I had to add gapsize (which is/was not required for the month/days charts). Graphs.conf now looks like this:

	[raintotals]
		title = "Rain Totals by Month"
		show_button = true
		button_text = "Rain Totals"
		type = column
		tooltip_date_format = "MMMM YYYY"
		aggregate_type = sum
		aggregate_interval = 2629800 # the length of a nominal month
		time_length = year_specific
		year_specific = 2020
		gapsize = 2629800
		[[rain2020totals]]
			title = "Rain 2020"
			[[[rain]]]
				color = "#7cb5ec"
				borderColor = "#7cb5ec"
				name = "Monthly"
				zIndex = 1
			[[[rainTotal]]]
				type = line
				color = "#b2df8a"
				name = "Cumulative"
				yAxis = 1

![interim_result](https://user-images.githubusercontent.com/67259651/94145782-5b9e0c00-fe73-11ea-8914-098b82d5fdb0.png)


The xAxis_categories couldn't be used, to make the xaxis labels look nicer and use locale I had to create a custom formatter.
There are different ways to do this, I chose this solution for now (belchertown.js.tmpl):

	if (title === "Rain 2020") { // Only apply to chart with this title
		options.xAxis.labels = {
			formatter: function () {
				var shortMonth = moment.unix( this.value / 1000).utcOffset($moment_js_utc_offset).format( "MMM" ); // Get locale month name
				shortMonth = shortMonth.charAt(0).toUpperCase() + shortMonth.slice(1); // Turn first character into uppercase
				if (shortMonth.lastIndexOf(".") !== -1) {shortMonth = shortMonth.slice(0, -1);} // Remove trailing period when present
				return shortMonth;
			},
		}
	}

Final result:

![final_result](https://user-images.githubusercontent.com/67259651/94147778-0b747900-fe76-11ea-834c-6d0c8debda83.png)

**Comment by ArendPWS** [comment]
Closing this issue, no PR required.
