### ISSUE TITLE
7 day forecast is now only 4 days?

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#415]
This may or may not be a skin issue but it looks like the 7 day forecast has shrunk. Not sure if anyone else has the same issue?
![Screen Shot 2020-09-23 at 11 25 28 AM](https://user-images.githubusercontent.com/1725001/93947503-f9b8a600-fd8f-11ea-91d2-d01295d3cdad.png)

**Comment by biltmorelaker** [comment]
Hmmm. Still showing 7 days for me.

 
![image](https://user-images.githubusercontent.com/44727343/93948626-e6182b80-fd0c-11ea-84b1-1bc1ba569f70.png)


It's still 9/22 here in the eastern part of the US. Maybe a problem with the forecast for your area.

Phil

**Comment by 41south** [comment]
Could well be, I just updated from the b6 release to production 1.2 and
it's the same. I'll monitor it.

**Comment by 41south** [comment]
Down to 3 days forecast today, no errors in the logs that I can see.
Stranger and stranger

**Comment by jamie75** [comment]
I’m still on the development version  and have 7 days

**Comment by 41south** [comment]
This started on 1.2b6 so I'm not sure what's up. I've just deleted the json
file so will see what happens next update

**Comment by jamie75** [comment]
I’m on


   - Belchertown Skin Version: 1.2rc2

**Comment by 41south** [comment]
I think this is an Aeris Weather issue, using the api wizard on their website only returns 3 days as well.

I'll close this, I've logged a report with Aeris

{
    "success": true,
    "error": null,
    "response": [
        {
            "loc": {
                "long": 174.776,
                "lat": -41.287
            },
            "interval": "day",
            "periods": [
                {
                    "timestamp": 1600887600,
                    "validTime": "2020-09-24T07:00:00+12:00",
                    "dateTimeISO": "2020-09-24T07:00:00+12:00",
                    "maxTempC": 14,
                    "maxTempF": 57,
                    "minTempC": 12,
                    "minTempF": 54,
                    "avgTempC": 13,
                    "avgTempF": 56,
                    "tempC": null,
                    "tempF": null,
                    "maxFeelslikeC": 14,
                    "maxFeelslikeF": 57,
                    "minFeelslikeC": 13,
                    "minFeelslikeF": 56,
                    "avgFeelslikeC": 14,
                    "avgFeelslikeF": 56,
                    "feelslikeC": 13,
                    "feelslikeF": 56,
                    "maxDewpointC": 11,
                    "maxDewpointF": 52,
                    "minDewpointC": 10,
                    "minDewpointF": 49,
                    "avgDewpointC": 11,
                    "avgDewpointF": 51,
                    "dewpointC": 11,
                    "dewpointF": 52,
                    "maxHumidity": 89,
                    "minHumidity": 79,
                    "humidity": 89,
                    "pop": 0,
                    "precipMM": 0,
                    "precipIN": 0,
                    "iceaccum": null,
                    "iceaccumMM": null,
                    "iceaccumIN": null,
                    "snowCM": 0,
                    "snowIN": 0,
                    "pressureMB": 1004,
                    "pressureIN": 29.65,
                    "windDir": "NNW",
                    "windDirDEG": 343,
                    "windSpeedKTS": 19,
                    "windSpeedKPH": 35,
                    "windSpeedMPH": 22,
                    "windGustKTS": 21,
                    "windGustKPH": 39,
                    "windGustMPH": 24,
                    "windDirMax": "NNW",
                    "windDirMaxDEG": 343,
                    "windSpeedMaxKTS": 21,
                    "windSpeedMaxKPH": 39,
                    "windSpeedMaxMPH": 24,
                    "windDirMin": "NNW",
                    "windDirMinDEG": 331,
                    "windSpeedMinKTS": 12,
                    "windSpeedMinKPH": 23,
                    "windSpeedMinMPH": 14,
                    "windDir80m": "NNW",
                    "windDir80mDEG": 337,
                    "windSpeed80mKTS": 27,
                    "windSpeed80mKPH": 50,
                    "windSpeed80mMPH": 31,
                    "windGust80mKTS": 29,
                    "windGust80mKPH": 54,
                    "windGust80mMPH": 33,
                    "windDirMax80m": "NNW",
                    "windDirMax80mDEG": 339,
                    "windSpeedMax80mKTS": 29,
                    "windSpeedMax80mKPH": 54,
                    "windSpeedMax80mMPH": 33,
                    "windDirMin80m": "NW",
                    "windDirMin80mDEG": 326,
                    "windSpeedMin80mKTS": 22,
                    "windSpeedMin80mKPH": 40,
                    "windSpeedMin80mMPH": 25,
                    "sky": 24,
                    "cloudsCoded": "FW",
                    "weather": "Mostly Sunny",
                    "weatherCoded": [],
                    "weatherPrimary": "Mostly Sunny",
                    "weatherPrimaryCoded": "::FW",
                    "icon": "pcloudy.png",
                    "visibilityKM": 24.135,
                    "visibilityMI": 15,
                    "uvi": 5,
                    "solradWM2": 5318,
                    "solradMinWM2": 20,
                    "solradMaxWM2": 706,
                    "isDay": true,
                    "sunrise": 1600884383,
                    "sunset": 1600928366,
                    "sunriseISO": "2020-09-24T06:06:23+12:00",
                    "sunsetISO": "2020-09-24T18:19:26+12:00"
                },
                {
                    "timestamp": 1600974000,
                    "validTime": "2020-09-25T07:00:00+12:00",
                    "dateTimeISO": "2020-09-25T07:00:00+12:00",
                    "maxTempC": 14,
                    "maxTempF": 57,
                    "minTempC": 12,
                    "minTempF": 53,
                    "avgTempC": 13,
                    "avgTempF": 55,
                    "tempC": null,
                    "tempF": null,
                    "maxFeelslikeC": 14,
                    "maxFeelslikeF": 57,
                    "minFeelslikeC": 12,
                    "minFeelslikeF": 54,
                    "avgFeelslikeC": 13,
                    "avgFeelslikeF": 55,
                    "feelslikeC": 12,
                    "feelslikeF": 54,
                    "maxDewpointC": 10,
                    "maxDewpointF": 50,
                    "minDewpointC": 10,
                    "minDewpointF": 49,
                    "avgDewpointC": 10,
                    "avgDewpointF": 50,
                    "dewpointC": 10,
                    "dewpointF": 49,
                    "maxHumidity": 85,
                    "minHumidity": 77,
                    "humidity": 83,
                    "pop": 0,
                    "precipMM": 0,
                    "precipIN": 0,
                    "iceaccum": null,
                    "iceaccumMM": null,
                    "iceaccumIN": null,
                    "snowCM": 0,
                    "snowIN": 0,
                    "pressureMB": 1007,
                    "pressureIN": 29.75,
                    "windDir": "NW",
                    "windDirDEG": 324,
                    "windSpeedKTS": 18,
                    "windSpeedKPH": 33,
                    "windSpeedMPH": 20,
                    "windGustKTS": 21,
                    "windGustKPH": 38,
                    "windGustMPH": 24,
                    "windDirMax": "NNW",
                    "windDirMaxDEG": 327,
                    "windSpeedMaxKTS": 21,
                    "windSpeedMaxKPH": 38,
                    "windSpeedMaxMPH": 24,
                    "windDirMin": "NW",
                    "windDirMinDEG": 324,
                    "windSpeedMinKTS": 18,
                    "windSpeedMinKPH": 33,
                    "windSpeedMinMPH": 20,
                    "windDir80m": "NW",
                    "windDir80mDEG": 319,
                    "windSpeed80mKTS": 27,
                    "windSpeed80mKPH": 50,
                    "windSpeed80mMPH": 31,
                    "windGust80mKTS": 29,
                    "windGust80mKPH": 54,
                    "windGust80mMPH": 34,
                    "windDirMax80m": "NW",
                    "windDirMax80mDEG": 320,
                    "windSpeedMax80mKTS": 29,
                    "windSpeedMax80mKPH": 54,
                    "windSpeedMax80mMPH": 34,
                    "windDirMin80m": "NW",
                    "windDirMin80mDEG": 319,
                    "windSpeedMin80mKTS": 27,
                    "windSpeedMin80mKPH": 50,
                    "windSpeedMin80mMPH": 31,
                    "sky": 4,
                    "cloudsCoded": "CL",
                    "weather": "Sunny",
                    "weatherCoded": [],
                    "weatherPrimary": "Sunny",
                    "weatherPrimaryCoded": "::CL",
                    "icon": "sunny.png",
                    "visibilityKM": 21.0978,
                    "visibilityMI": 13.11,
                    "uvi": 5,
                    "solradWM2": 5434,
                    "solradMinWM2": 23,
                    "solradMaxWM2": 722,
                    "isDay": true,
                    "sunrise": 1600970680,
                    "sunset": 1601014827,
                    "sunriseISO": "2020-09-25T06:04:40+12:00",
                    "sunsetISO": "2020-09-25T18:20:27+12:00"
                },
                {
                    "timestamp": 1601060400,
                    "validTime": "2020-09-26T07:00:00+12:00",
                    "dateTimeISO": "2020-09-26T07:00:00+12:00",
                    "maxTempC": 14,
                    "maxTempF": 58,
                    "minTempC": 5,
                    "minTempF": 42,
                    "avgTempC": 10,
                    "avgTempF": 50,
                    "tempC": null,
                    "tempF": null,
                    "maxFeelslikeC": 14,
                    "maxFeelslikeF": 57,
                    "minFeelslikeC": 12,
                    "minFeelslikeF": 54,
                    "avgFeelslikeC": 13,
                    "avgFeelslikeF": 55,
                    "feelslikeC": 12,
                    "feelslikeF": 54,
                    "maxDewpointC": 11,
                    "maxDewpointF": 51,
                    "minDewpointC": 10,
                    "minDewpointF": 50,
                    "avgDewpointC": 10,
                    "avgDewpointF": 50,
                    "dewpointC": 10,
                    "dewpointF": 50,
                    "maxHumidity": 88,
                    "minHumidity": 78,
                    "humidity": 88,
                    "pop": 0,
                    "precipMM": 10.62,
                    "precipIN": 0.42,
                    "iceaccum": null,
                    "iceaccumMM": null,
                    "iceaccumIN": null,
                    "snowCM": 0,
                    "snowIN": 0,
                    "pressureMB": 1011,
                    "pressureIN": 29.85,
                    "windDir": "NNW",
                    "windDirDEG": 327,
                    "windSpeedKTS": 18,
                    "windSpeedKPH": 34,
                    "windSpeedMPH": 21,
                    "windGustKTS": 21,
                    "windGustKPH": 39,
                    "windGustMPH": 24,
                    "windDirMax": "NNW",
                    "windDirMaxDEG": 328,
                    "windSpeedMaxKTS": 29,
                    "windSpeedMaxKPH": 53,
                    "windSpeedMaxMPH": 33,
                    "windDirMin": "NNW",
                    "windDirMinDEG": 334,
                    "windSpeedMinKTS": 2,
                    "windSpeedMinKPH": 4,
                    "windSpeedMinMPH": 3,
                    "windDir80m": "NW",
                    "windDir80mDEG": 326,
                    "windSpeed80mKTS": 26,
                    "windSpeed80mKPH": 47,
                    "windSpeed80mMPH": 29,
                    "windGust80mKTS": 32,
                    "windGust80mKPH": 59,
                    "windGust80mMPH": 37,
                    "windDirMax80m": "NW",
                    "windDirMax80mDEG": 326,
                    "windSpeedMax80mKTS": 32,
                    "windSpeedMax80mKPH": 59,
                    "windSpeedMax80mMPH": 37,
                    "windDirMin80m": "NNW",
                    "windDirMin80mDEG": 336,
                    "windSpeedMin80mKTS": 23,
                    "windSpeedMin80mKPH": 43,
                    "windSpeedMin80mMPH": 27,
                    "sky": 27,
                    "cloudsCoded": "FW",
                    "weather": "Mostly Sunny",
                    "weatherCoded": [],
                    "weatherPrimary": "Mostly Sunny",
                    "weatherPrimaryCoded": "::FW",
                    "icon": "pcloudy.png",
                    "visibilityKM": 24.135,
                    "visibilityMI": 15,
                    "uvi": 5,
                    "solradWM2": 5385,
                    "solradMinWM2": 25,
                    "solradMaxWM2": 725,
                    "isDay": true,
                    "sunrise": 1601056977,
                    "sunset": 1601101288,
                    "sunriseISO": "2020-09-26T06:02:57+12:00",
                    "sunsetISO": "2020-09-26T18:21:28+12:00"
                }
            ],
            "profile": {
                "tz": "Pacific/Auckland",
                "elevM": 24,
                "elevFT": 79
            }
        }
    ]
}
