### ISSUE TITLE
xAxis using locale

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#416]
This is not a big deal for most users I guess. But I noticed that (all?) the charts default to using English short/long names for months and days on xAxis? Maybe this question has already been asked in the past, but I was just wondering if this could be easily changed to using locale. (Maybe make it optional?)

**HELP WANTED**

**Comment by ArendPWS** [comment]
Adding months, shortMonths, weekdays and shortWeekdays to the language section of Highcharts.setOptions in belchertown.js.tmpl makes it work. Moment.js provides the right day and month names. Now the day and month names should be displayed in local language on the X-Axis.

	Highcharts.setOptions({
		global: {
			//useUTC: false
			timezoneOffset: $highcharts_timezoneoffset
		},
		lang: {
			months: moment.months(),
			shortMonths: moment.monthsShort(),
			weekdays: moment.weekdays(),
			shortWeekdays: moment.weekdaysShort(),
			decimalPoint: "$highcharts_decimal",
			thousandsSep: "$highcharts_thousands"
		}
	});

**Comment by ddperso** [comment]
Thanks, perfect

**Comment by poblabs** [comment]
This has been merged, thanks!
