### ISSUE TITLE
Cloudbase unit label showing twice

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#418]
See here: https://groups.google.com/g/weewx-user/c/DFuG8xlQ0mU

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ArendPWS** [comment]
I assumed this is an "error" in weewx.conf i.e. something going wrong with the examples and that it should read:

                meter = " meter"  # You may prefer  " meters" or " metre".                
                day = " day" # or " days"
                hour = " hour" # or " hours"
                minute = " minute" # or " minutes"
                second = " second" # or " seconds"
                NONE = ""

But I guess I misunderstood?

**Comment by poblabs** [comment]
The fix is a good one, but it removes the plural. So I think the real fix is to find the cloudbase in the python and select the correct singular or plural from the list. I could probably look at this in a few days

**Comment by ArendPWS** [comment]
My pull request #419 solved this, but the changes could be simplified.

**Comment by ArendPWS** [comment]
@poblabs, this issue has already been solved, you merged my pull request.
