### ISSUE TITLE
Graphs will not appear

### ISSUE THREAD

**Issue by bdf0506** [poblabs/weewx-belchertown#42]
I can't get the graphs to appear when I install the skin. Graphs are enabled in skin.conf. 

```
[Extras]

    # General Site Defaults
    belchertown_root_url = "http://weewx.home/weewx/alt"
    logo_image = ""
    site_title = "My Weather Website"
    radar_html = ""
    footer_copyright_text = "My Weather Website"

    # Enabled by default since majority of the theme is wrapped around the charts
    highcharts_enabled = 1
    highcharts_graph_1 = "temperatureplot"
    highcharts_graph_2 = "windplot"
    highcharts_graph_3 = "rainplot"
    highcharts_graph_4 = "winddirplot"
    highcharts_graph_5 = "barometerplot"
    highcharts_graph_6 = "radiationplot"
    highcharts_show_windchill = 1
    highcharts_show_heatindex = 1
    highcharts_show_apptemp = 0
```

From the main weewx.conf file, I have these settings:

```
    [[Highcharts_Belchertown]]
        HTML_ROOT = public_html/alt
        skin = Highcharts_Belchertown
    [[Belchertown]]
        HTML_ROOT = public_html/alt
        skin = Belchertown
        [[[Extras]]]
           belchertown_root_url = "http://weewx.home/weewx/alt"
```

When I look in the public_html relative folder, I DO see js and json data that is generated, so these files exist:

/opt/weewx/public_html/alt/js/highcharts-dayplots.js
/opt/weewx/public_html/alt/json/day.json

In day.json i do in fact see data there. 

What else am I missing?

**Comment by poblabs** [comment]
Have you read the full readme with all bold character callouts? Did you set
the root URL in the skin options (which shouldn't be in skin.conf)?

**Comment by poblabs** [comment]
I was on mobile earlier, and now I'm on PC. I see you did set the root url based on the info you provided. I take it your site isn't available publicly?

Check the view source of your site. There should be a full URL in the `<head>` area that has `/js/highcharts-dayplots.js'` with the full URL to your site. It has to match. This is set by the root url - so make sure it is valid.

**Comment by bdf0506** [comment]
If I go directly to `http://weewx.home/weewx/alt/js/highcharts-dayplots.js` it simply shows the text in a browser window, so essentially the same thing if I were to cat out the file in linux. I am assuming in the browser it should be displaying javascript, but it is not. FYI I am using Chrome v71 on Win10 and Javascript is allowed.

And yes, my site for now is `http://weewx.home/weewx/alt`. If I go there, the main index page will load (from your skin), everything loads properly (including darksky) but the graphs section is completely blank.

**Comment by poblabs** [comment]
Can you post the errors from the JS console? See above reply for where to
find it

**Comment by bdf0506** [comment]
Nothing exciting. When I load `http://weewx.home/weewx/alt/index.html`, the only JS errors that are given are related to the radar map, nothing about the graphs.

When I go to the graphs page itself, no errors... yet I still see blank white pages. 

```
radar.js:8 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
l @ radar.js:8
(anonymous) @ radar.js:8
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
e.require @ embed2.js:9
(anonymous) @ radar.js:44
_mount @ embed2.js:53
(anonymous) @ embed2.js:53
Promise.then (async)
open @ embed2.js:53
(anonymous) @ embed2.js:81
open @ embed2.js:81
(anonymous) @ embed2.js:88
(anonymous) @ embed2.js:88
emit @ embed2.js:16
d @ embed2.js:49
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
a @ embed2.js:9
e.loadOrphanedModules @ embed2.js:9
embedMap @ embed2.js:114
(anonymous) @ embed2.js:114
radar.js:8 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
l @ radar.js:8
(anonymous) @ radar.js:8
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
(anonymous) @ embed2.js:9
a @ embed2.js:9
e.require @ embed2.js:9
(anonymous) @ radar.js:44
_mount @ embed2.js:53
(anonymous) @ embed2.js:53
Promise.then (async)
open @ embed2.js:53
(anonymous) @ embed2.js:81
open @ embed2.js:81
(anonymous) @ embed2.js:88
(anonymous) @ embed2.js:88
emit @ embed2.js:16
d @ embed2.js:49
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
a @ embed2.js:9
e.loadOrphanedModules @ embed2.js:9
embedMap @ embed2.js:114
(anonymous) @ embed2.js:114
2embed2.js:48 [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ embed2.js:48
l @ embed2.js:48
v @ radar.js:18
f @ radar.js:18
emit @ embed2.js:16
onopen @ radar.js:44
_open @ embed2.js:72
(anonymous) @ embed2.js:53
Promise.then (async)
open @ embed2.js:53
(anonymous) @ embed2.js:81
open @ embed2.js:81
(anonymous) @ embed2.js:88
(anonymous) @ embed2.js:88
emit @ embed2.js:16
d @ embed2.js:49
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
Promise.then (async)
(anonymous) @ embed2.js:49
a @ embed2.js:9
e.loadOrphanedModules @ embed2.js:9
embedMap @ embed2.js:114
(anonymous) @ embed2.js:114
```

**Comment by poblabs** [comment]
Hmm, ok. 

If the graphs don't show there's usually an error about why. 

What about the network tab - Switch to network tab, then reload the site. See if the dayplots.js file is a 404, 302, or something else than 200?

**Comment by bdf0506** [comment]
I'm at a loss here. Network tab shows 200 for dayplots.js.


```
Request URL: http://weewx.home/weewx/alt/js/highcharts-dayplots.js
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.60.216:80
Referrer Policy: no-referrer-when-downgrade
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 3025
Content-Type: application/javascript
Date: Sun, 13 Jan 2019 21:09:04 GMT
ETag: "5c6d-57f5d4e18bf77-gzip"
Keep-Alive: timeout=5, max=100
Last-Modified: Sun, 13 Jan 2019 21:06:42 GMT
Server: Apache/2.4.29 (Ubuntu)
Vary: Accept-Encoding
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: weewx.home
If-Modified-Since: Sun, 13 Jan 2019 21:06:42 GMT
If-None-Match: "5c6d-57f5d4e18bf77-gzip"
Referer: http://weewx.home/weewx/alt/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

**Comment by poblabs** [comment]
I'm at a bit of a loss too. On the user forums when something quirky like this happened before, the user deleted the entire contents of public_html, restarted weewx, waited for an archive interval (usually 5 mins) then cleared their Chrome cache and it magically started working. Give that a try?

**Comment by bdf0506** [comment]
Nope, no dice :(

**Comment by poblabs** [comment]
Any chance you can port forward temporarily so I can take a look? Maybe a 2nd set of eyes.

**Comment by bdf0506** [comment]
Yea i can make that happen. Will need to PM you with the info (dont believe you can PM on github), don't want to post that to github for the rest of the world.

**Comment by poblabs** [comment]
You can send me an email through https://patobrienmedia.com/ at the bottom is the contact form.

**Comment by poblabs** [comment]
Any luck on this after extending your database schema? I'm thinking this issue can probably be closed since that seems to be the root of the issues.

**Comment by poblabs** [comment]
Closing as I believe this to be a "one-off" issue with the database having a slimmed down schema.
