### ISSUE TITLE
Belchertown Ver. 1.2 Wind Rose Issue

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#420]
It seems the Wind Rose popup legend in dark mode does not contain the colors in Version 1.2.  It works as excepted in Version 1.1b3.

**Version 1.1b3**
![Wind Rose 1 13b](https://user-images.githubusercontent.com/48191231/94502210-a8fede00-01d1-11eb-8dbc-f61e3fb4c9aa.png)

**Version 1.2**
![Wind Rose Night 1 2](https://user-images.githubusercontent.com/48191231/94502268-c6cc4300-01d1-11eb-8209-95649f401961.png)

**Version 1.2**
![Wind Rose Day 1 2](https://user-images.githubusercontent.com/48191231/94502294-d8ade600-01d1-11eb-96c4-49439d19b2a6.png)

**Comment by ArendPWS** [comment]
Removing dark theme CSS from windrose span worked for me:

In file belchertown-dark.min.css removed this entry:

.highcharts-windRose span {color: #e0e0e3!important;}.dark

**Comment by Stormtracker017** [comment]
@ArendPWS: the file I'm using does not contain ".highcharts-windRose span {color: #e0e0e3!important;}.dark"

**Comment by ArendPWS** [comment]
> @ArendPWS: the file I'm using does not contain ".highcharts-windRose span {color: #e0e0e3!important;}.dark"

That's odd, it was present when I installed the latest (1.2) release. Removing that line from belchertown-dark.min.css 
solved the problem. I have no idea what else could be blocking those colors. Here is a screenshot from my page:

![Windroos kleuren](https://user-images.githubusercontent.com/67259651/95026395-499d4400-0691-11eb-8834-34e5ec01d787.png)

**Comment by ArendPWS** [comment]
@Stormtracker017 it is present in the latest release, you can check here:

[belchertown-dark.min.css](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/belchertown-dark.min.css)

**Comment by Stormtracker017** [comment]
@ArendPWS  When I searched for  .highcharts-windRose span {color: #e0e0e3!important;}.dark I did not find it. But searching just for windRose I found the line you where talking about.  Took it out and it fixed the issue.  Thanks
