### ISSUE TITLE
Charts Update on Home page interacts poorly with popups

### ISSUE THREAD

**Issue by whorfin** [poblabs/weewx-belchertown#423]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**Describe the bug**
"More Almanac Information" and any possible "weather alerts" are two standard popup panes on the Home page.
Both interact poorly when charts auto-refresh
"More Almanac Information" suddenly vanishes as if one hit the Close button
Reading a weather alert is more problematic - the pane suddenly vanishes, but the main web-page stays darked out and unresponsive after that until refreshed.
California is having lots of Red Flag days and other weather alerts, so this has become painfully obvious.

**Version of the skin you're using**
1.2

**To Reproduce**
From the Home page:
Click on a Weather Alert or "More Almanac Information"
wait a chart update interval
observe that the panes close without user interaction
If you had clicked a Weather Alert, observe that the home page is now greyed out and unresponsive until the browser is manually refreshed.

Note - I am using mqtt_websockets_enabled, and have _not_ set webpage_autorefresh

**Expected behavior**
Information panes should remain readable and focused to user until their close button is clicked.  At a minimum, auto-closing shouldn't render main page unusuable without manual refresh.

**Device Information (please complete the following information):**
latest Chrome browser on any desktop platform
latest Firefox browser on desktop shows same behavior

**Comment by poblabs** [comment]
This behavior is because the entire JavaScript containers are being refreshed behind the scenes, and the Bootstrap modal closes when the container is refreshed. I'm not sure I can override this behavior.

**Comment by whorfin** [comment]
Two quick, hopefully helpful, thoughts/questions
1. the behavior of "More Almanac Information" is preferable - at least when the modal closes, the page remains responsive, while the weather alert auto-close causes the main page to stay greyed-out and unresponsive.
2. Should everything be refreshed when webpage_autorefresh isn't set, defaulting to 0, which is supposed to mean "don't autorefresh"?  Is the home page special?  ...and could that maybe be configurable?

Cheers

**Comment by poblabs** [comment]
1. I'll have to run my own test on this - the underlying page shouldn't lock up. 

2. The front page is special when you use MQTT. All containers are updated via numerous AJAX calls. If you opt to not use MQTT then that's where `webpage_autorefresh` comes in, allowing those to still get their page to refresh when they don't want to setup MQTT.

**Comment by ArendPWS** [comment]
@whorfin

For almanac modal, find this line of code in belchertown.js.tmpl and comment out like this:

    //jQuery('#almanac').modal('hide');

The almanac modal will now stay open between intervals and the contents will be updated until the user closes the modal.

Alert modals are different, they are recreated after each interval. Keeping these open between intervals will be tough. Maybe a different approach on how they are created now might solve this and additionally would remove the problem of the screen lock. Perhaps Pat has some ideas on how to fix this.

**Comment by whorfin** [comment]
@ArendPWS Thanks for that tip, that solved the Almanac issue nicely
