### ISSUE TITLE
Trying to display webcam instead of windy radar

### ISSUE THREAD

**Issue by Distortionist** [poblabs/weewx-belchertown#426]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

            radar_html = "http://livingstonecove.ca:5550/?action=stream"
That is not working and only producing text in the radar spot.

**Link to your website (IMPORTANT)**

http://livingstonecove.ca

**Version of the skin you're using**

1.2

**To Reproduce**
1. Go to '...' livingstonecove.ca
2. Click on '....' NA

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/72505233/95462286-acbaff00-094d-11eb-8c9b-4fc3781fb4b7.png)

That is displayed instead of my webcam feed.

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by Distortionist** [comment]
I figured it out!

**Comment by mrneutron42** [comment]
I just tried the same thing and got the same result.
How did you fix it @Distortionist ?

**Comment by ms372591** [comment]
> I just tried the same thing and got the same result.
> How did you fix it @Distortionist ?

You can also look at this push it has 3 tabs. Courtesy of https://github.com/norecords/weewx-belchertown/commits?author=norecords. I have it on my site https://belcampmdweather.tech/weewx/belchertown/
https://github.com/norecords/weewx-belchertown/commit/7bbfe21f6f10a76bb96bb7ad6fefa7259a22d20c
