### ISSUE TITLE
Strange missing icon?

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#432]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

I'm seeing an unloaded image near the top left on graphs (and records pages) that wasn't there before.  I'm not sure what's triggering it...or what is not configured to load it.  This wasn't there before updating to 1.2.

**Link to your website (IMPORTANT)**
https://www.baugh.org/weewx/belchertown/graphs/

**Version of the skin you're using**

1.2
**To Reproduce**

Check out the link I posted.  it's under the multi-colored house icon.
I'm wondering if it's related to new forecast?   It is showing current temp up here now..
which I don't recall from before...

**Expected behavior**

Don't expect to see a unloaded icon...

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
That's a missing icon for the forecast conditions currently. It's not loading on your site at all - as if the data from the forecast is just missing. 

Who's your forecast provider?

**Comment by earlthesquirrel** [comment]
I just changed it to Aeris.

**Comment by earlthesquirrel** [comment]
I am seeing forecast data...

**Comment by earlthesquirrel** [comment]
Also, help me to understand -- What causes the "N/A" on the main page (under current conditions?). I know that sometimes there are hiccups in getting data, but shouldn't it just display the last readings?  Is some API from weewx not returning data?

**Comment by poblabs** [comment]
Yes I see forecast data too, but it looks like it's out of sync. Delete your public_html/belchertown/json/forecast.json file to generate a new one

N/A comes from weewx and usually means your LOOP isn't getting data for that observation. These instructions can help you try to debug what's going on https://github.com/weewx/weewx/wiki/Help!-Posting-to-weewx-user

**Comment by earlthesquirrel** [comment]
Ok, I removed it.  That generated an icon (at least as a start)

But no temp.

Then when it re-generated regularly it was gone again.

Let me try to stop the service completely and re-try...

**Comment by earlthesquirrel** [comment]
Ok, removing file, not just re-starting service but shutting id down.... waiting a sec, then restarting seems to have fixed it.  I have icons and temps there.

I'll check into the link about the loop.  I know that my system sometimes gets timeouts from the REST service behind the temperature sensors (I'm using a WIONode with temp sensor.. it's been a very stable, solid platform. (see : https://www.seeedstudio.com/Wio-Node.html ). I have 3 (soon to be 4) with multi-gas sensor, CO2, Temp-Humidity, Temp-Humidity-Pressure, and Dust sensors.   They've been running for a few years outside on my front porch (in small 3d printed cases).  Sometimes I get timeouts.... I've tried slowing down polling but I don't think it'll ever be 100%.... so trying to figure out bounds on "last loop packet with temp" vs "last loop packet".

**Comment by earlthesquirrel** [comment]
One follow up:

I have multiple DIFFERENT sensor platforms providing data.  They all report at different intervals.   Do you know what the "time range" on how many loop packets would have to go by that would cause it to drop the temp?    I'm thinking that's related to the root cause in some sense...

**Comment by earlthesquirrel** [comment]
Oh and one more thing :  

I've got a Geiger counter I'm about to add.   I'd like to have a "dial/gauge" display for "current counts, and current Siverts/per hour.  It's not really a graph, so I'm trying to figure out a good way to visualize it.  Have you seen any body use this skin with that sort of display?    Maybe that new graph... Hayes?  Or?

**Comment by areax99** [comment]
I have the same issue too. Aeris forecasts and icons have not been displayed for 24 hours. I do not know what happened. I deleted the forecast.json file and restarted weewx. I did a lot of testing, but I didn't solve the issue. Please help me!

**Comment by areax99** [comment]
I have fix now. Maybe it's an aeris problem.

**Comment by Distortionist** [comment]
> I have fix now. Maybe it's an aeris problem.

How did you fix it ? I have the same issue after deleting weewx html folder. It regenerated everything except the current forecast icon. I deleted forecast.json but the issue persists. I get no icon for the current forecast, and in the pages like graph, records, the top left tiny icon by the current temp is also missing.

Can someone help me get it going again? I thought when a new forecast icon is needed it will regenerate but it has not in over 12 hours.

**Comment by ArendPWS** [comment]
@Distortionist, have you tried a restart of weewx? What is your website?

**Comment by Distortionist** [comment]
> @Distortionist, have you tried a restart of weewx? What is your website?

Yes I have several times, I have been working on this for HOURS lol.  the website is http://livingstonecove.ca

What happened I got a weird UV reading long ago at 14, I deleted the record from the database and wiped out the html folder for weewx so it can rebuild everything, I was following instructions online, and it did fix everything and rebuild it all, except for the current condition icon missing from all the pages.

**Comment by ArendPWS** [comment]
In the debug console it shows: belchertown.js?1604068673:37 Forecast: Changing icon to undefined, that's not good  🙂
Will try to find the cause, can't promise I will find the solution.

**Comment by ArendPWS** [comment]
In skin.conf do you have these items in the forecast configuration? And does it contain the item forecast_aeris_use_metar = 1?

    # Forecast defaults
    forecast_enabled = 0
    forecast_provider = "aeris"
    forecast_api_id = ""
    forecast_api_secret = ""
    forecast_units = "us"
    forecast_lang = "en"
    forecast_stale = 3540
    forecast_aeris_use_metar = 1
    forecast_alert_enabled = 0
    forecast_alert_limit = 1
    forecast_show_daily_forecast_link = 0
    forecast_daily_forecast_link = ""

**Comment by Distortionist** [comment]
> In the debug console it shows: belchertown.js?1604068673:37 Forecast: Changing icon to undefined, that's not good 🙂
> Will try to find the cause, can't promise I will find the solution.

How did you reach the debug console??! Cool!



> In skin.conf do you have these items in the forecast configuration? And does it contain the item forecast_aeris_use_metar = 1?

I will check my skin.conf but I have them all set in weewx.conf. Here is my belchertown weewx.conf section :

` [[Belchertown]]
        skin = Belchertown
        HTML_ROOT = /var/www/html/weewx/belchertown
        [[[Extras]]]
            #  logo_image = ""
            forecast_enabled = 1
            forecast_provider = aeris
            forecast_api_id = 3TEpRtWjZ9JiQhLuFMfgC
            forecast_api_secret = bxGxtgMuLWuk2gqgZOS9e37r7hoH3HKQITx4yegZ
            forecast_units = ca
            forecast_alert_enabled = 1
            forecast_alert_limit = 5
            earthquake_enabled = 1
            earthquake_server = USGS
            #        twitter_enabled = 1
            theme = dark
            site_title = Livingstone Cove Weather Station
            #   station_observations = "barometer", "dewpoint", "outHumidity", "rainWithRainRate"
            manifest_name = Livingstone Cove Weather Station
            radar_zoom = 8
            radar_marker = 1
            #            radar_html = <iframe width="650" height="360" src="http://livingstonecove.ca/weatherhq.jpg" frameborder="0"></iframe>
            radar_html = <br><img src="http://livingstonecove.ca/weather.jpg" width="639" height="360">
            almanac_extras = 1
            highcharts_enabled = 1
            graph_page_show_all_button = 1
            graph_page_default_graphgroup = all
            webpage_autorefresh = 60000
            reload_hook_images = 1
            reload_images_radar = 1
            station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, visibility, cloudbase, UV, radiation
`

**Comment by Distortionist** [comment]
Hahaha, whoops. Sorry for the image :) Ill delete that section lol.

**Comment by areax99** [comment]
I fix it by going to the Aeris website and restarting Registered Apps.

**Comment by ArendPWS** [comment]
Ok, add forecast_aeris_use_metar = 1  to weewx.conf this is missing.

**Comment by Distortionist** [comment]
> forecast_aeris_use_metar = 1

I also was missing the forecast_lang = "en"

it never had them but I just added them and I am restarting as I type.

**Comment by Distortionist** [comment]
> I fix it by going to the Aeris website and restarting Registered Apps. As earlthesquirrel has been described

Thank you, I did log into Aeris yesterday and looked at it to make sure nothing changed when it stopped working, I did not notice anything, I will look for earthsquirrel's comment and see what it says.  I don't understand how deleting my html folder will cause that though.. it is very odd.

**Comment by ArendPWS** [comment]
Does this mean it is working now?

**Comment by Distortionist** [comment]
> I fix it by going to the Aeris website and restarting Registered Apps. As earlthesquirrel has been described



> Still no icon? That's weird. You did a full restart of weewx now?

I stopped weewx, deleted forecast.json, turned off the aeris app and back on again after a couple of minutes, and I just started weewx. I will give it some time to generate and do stuff.

**Comment by Distortionist** [comment]
> In the debug console it shows: belchertown.js?1604068673:37 Forecast: Changing icon to undefined, that's not good 🙂
> Will try to find the cause, can't promise I will find the solution.

How did you see that?  I don't even see it in my logs.

**Comment by ArendPWS** [comment]
> > In the debug console it shows: belchertown.js?1604068673:37 Forecast: Changing icon to undefined, that's not good 🙂
> > Will try to find the cause, can't promise I will find the solution.
> 
> How did you see that? I don't even see it in my logs.

Press Control+Shift+J

**Comment by Distortionist** [comment]
> > > In the debug console it shows: belchertown.js?1604068673:37 Forecast: Changing icon to undefined, that's not good 🙂
> > > Will try to find the cause, can't promise I will find the solution.
> > 
> > 
> > How did you see that? I don't even see it in my logs.
> 
> Press Control+Shift+J

Huh, how strange. I added 2 links in the config file yesterday, asside from removing that bad UV value and deleting the html. I wonder if I screwed it up. I am undoing the changes I did 1 by 1. I just added a link in the header and in about. See if that fixes it.

**Comment by areax99** [comment]
This line is omitted :<img id="wxicon" src="$relative_url/images/$current_obs_icon"> in index.html because $current_obs_icon is empty

**Comment by Distortionist** [comment]
> This line is omitted :`<img id="wxicon" src="$relative_url/images/$current_obs_icon">` in index.html because $current_obs_icon is empty

This is normal after deleting the html folder right? 
Oct 30 12:46:57 LivingstoneCove weewx[15108] INFO user.belchertown: version 1.2
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  Error writing forecast info to /var/www/html/weewx/belchertown/json/forecast.json. Reason: [Errno 2] No such file or directory: '/var/www/html/weewx/belchertown/json/forecast.json'
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 975, in get_extension_list
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      with open( forecast_file, 'wb+' ) as file:
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/weewx/belchertown/json/forecast.json'
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      obj.start()
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      self.run()
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      default_binding)
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 983, in get_extension_list
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****      raise Warning( "Error writing forecast info to %s. Reason: %s" % ( forecast_file, e) )
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  Warning: Error writing forecast info to /var/www/html/weewx/belchertown/json/forecast.json. Reason: [Errno 2] No such file or directory: '/var/www/html/weewx/belchertown/json/forecast.json'
Oct 30 12:47:05 LivingstoneCove weewx[15108] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by Distortionist** [comment]
I just undid EVERYTHING I touched, which shouldn't cause this, maybe the links, but it seems the same thing is happening. I still have no icon there. I will try restarting weewx so it starts with no errors and we will see.

**Comment by Distortionist** [comment]
I wonder if I can trick it. I can turn forecast off, nuke the html folder, let it regenerate everything, turn the forecast back on? That way it will do its thing when it is nukes without an error (I hope), then when I turn on the forecast it will just get a new json.
 Everything regenerated from my last attempt and it did not fix it. So I will try the above right now.

**Comment by Distortionist** [comment]
It generated with no errors, after I turned earthquake forecasting off too. I don't know if I am supposed to get any icons with it all off, I am presuming not. I don't not get a broken image icon anywhere anymore.
I shut weewx down after that, and I turned forecasting all back on.
 It downloaded a new forecast and populated my weewx page.

I still have no current condition icon, and a broken image picture on all the pages like graphs, reports, etc.

**Comment by Distortionist** [comment]
The broken image links to this "http://livingstonecove.ca/weewx/belchertown/images/" it is not giving it an image to load, just a path.

Also in there, there is an empty index.html file that only contains :

<html>
</html>

but I think that is normal, I see the same thing elsewhere.

**Comment by areax99** [comment]
Indeed. If you look in the page-header.inc file you will see the following line `<img id="wxicon" src="$relative_url/images/$current_obs_icon">`. $current_obs_icon vuol dire che è vuoto

**Comment by areax99** [comment]
I don't know how weewx generate this variable. I don't know Python

**Comment by Distortionist** [comment]
> Indeed. If you look in the page-header.inc file you will see the following line `<img id="wxicon" src="$relative_url/images/$current_obs_icon">`. $current_obs_icon it means is empty (it is a variable)

I do see that, it is in there. I don't know any programming either but if that is the broken line ill check to see what the $relative_url is reading its value from and fix it, or $current_obs_icon is broken, and I don't even know where to start with that one.

**Comment by Distortionist** [comment]
> forecast_enabled = 1
> forecast_provider = "aeris"
> forecast_api_id = ""
> forecast_api_secret = ""
> forecast_units = "us"
> forecast_lang = "en"
> forecast_stale = 3540
> forecast_aeris_use_metar = 1
> forecast_alert_enabled = 1
> forecast_alert_limit = 1
> forecast_show_daily_forecast_link = 0
> forecast_daily_forecast_link = ""

It is similar, some options are different, here is mine :

    # Forecast defaults
    forecast_enabled = 0
    forecast_provider = "aeris"
    forecast_api_id = ""
    forecast_api_secret = ""
    forecast_units = "us"
    forecast_lang = "en"
    forecast_stale = 3540
    forecast_aeris_use_metar = 1
    forecast_alert_enabled = 0
    forecast_alert_limit = 1
    forecast_show_daily_forecast_link = 0
    forecast_daily_forecast_link = ""



> Just caught up with this thread - have you also checked weewx.conf for forecast_aeris_use_metar = 1.
> Michael

Yes it was missing before but I added it, it was also inside skin.conf so it should have been using it, everything was working for weeks until I deleted the html folder, but maybe the image was stuck for a few days and I did not realize it. It has been cloudy for a week here.

**Comment by Distortionist** [comment]
I think somewhere along the way, we fixed it. It just updated to a sun out of the blue.

I believe it only updates when a change happens, if its gone it doesn't care, doesn't check for it, it just doesn't work for however long it takes for the current forecast to be different, then it changes.

For all I know it could have never been broken, just did not need to change the whole time till now.  I have no idea. I gave up a after the last changes I did, and i've been checking it constantly.  It only just decided to work.   I have no other explanation other than the one I gave.  I honestly think the whole thing was a waiting game. Nothing was particularly wrong, other than this behavior. It's probably a good idea to force an update of that icon each time weewx starts or generates scripts, or downloads a forecast. Maybe the last one is most appropriate then when someone deletes the forecast.json file it will regenerate it.

Anyway, Thank you guys, all of you for having the patience to troubleshoot this with me. I appreciate the help and think you guys are awesome.

**Comment by michaelundwd** [comment]
I agree the key is the reloading of the forecast.json file that is only done every hour, irrespective of how many times you restart weewx - you need to delete forecast.json as well.  That has caught me out a few times too.
Michael

**Comment by ArendPWS** [comment]
You didn't have forecast_aeris_use_metar = 1. If this item is missing it will never display an icon. After applying that fix it was a matter of waiting for the stale timer to pass time. 😉

**Comment by areax99** [comment]
Great...

**Comment by ArendPWS** [comment]
@poblabs, maybe there should be some kind of warning in the installation instructions to people who upgrade to check if the contents of their .conf files still matches with the latest added options?

**Comment by Distortionist** [comment]
> I agree the key is the reloading of the forecast.json file that is only done every hour, irrespective of how many times you restart weewx - you need to delete forecast.json as well. That has caught me out a few times too.
> Michael

I think it is more than that, I deleted forecast.json and waited for hours a few times. I think the only trigger is it noticing a change in the forecast, so if it was cloudy for a week, it would never change. That is what it seems unless I really did fix something, but I don't know what. I restored all the settings that I previously had.



> You didn't have forecast_aeris_use_metar = 1. If this item is missing it will never display an icon. After applying that fix it was a matter of waiting for the stale timer to pass time. 😉

Yes but I never had it to begin with and it was working fine, it is defined in skin.conf already, so if i did not have it in weewx.conf, it would have loaded it from skin,conf

**Comment by michaelundwd** [comment]
@poblabs,  An additional suggestion to @ArendPWS .  Instead of setting the icon to "" in belchertown.py, why not use a null icon eg  aeris na.png icon?  I'm quite happy to produce a similar one that matches the existing icon set.  I was thinking of enhancing them after I had sorted  the forecasts and could add it to the list.
![na](https://user-images.githubusercontent.com/45148992/97751310-009eab00-1aea-11eb-8bf3-d5d2709e2d61.png)

**Comment by ArendPWS** [comment]
@Distortionist 

Confusing, so hopefully get it right now:

 > I think it is more than that, I deleted forecast.json and waited for hours a few times. I think the only trigger is it noticing a change in the forecast, so if it was cloudy for a week, it would never change. That is what it seems unless I really did fix something, but I don't know what. I restored all the settings that I previously had.
> 

When I look at the code, a new forecast does not depend on the contents of the current forecast. If there is no forecast file at all, one will be downloaded. If a forecast file exists it depends on the time passed (forecast_stale = xxxx) if and when a new one will be downloaded.

            # Determine if the file exists and get it's modified time
            if os.path.isfile( forecast_file ):
                if ( int( time.time() ) - int( os.path.getmtime( forecast_file ) ) ) > int( forecast_stale_timer ):
                    forecast_is_stale = True
            else:
                # File doesn't exist, download a new copy
                forecast_is_stale = True
            
            # File is stale, download a new copy
            if forecast_is_stale:

> Yes but I never had it to begin with and it was working fine, it is defined in skin.conf already, so if i did not have it in weewx.conf, it would have loaded it from skin,conf

Yes you are right! That's the confusing part. If that setting (forecast_aeris_use_metar = 1) was already present in skin.conf the icon should have been loaded. But that would mean that something else was preventing this, Maybe someday the answer to this will pop up.
