### ISSUE TITLE
Cloudbase variable

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#433]
:bulb: **The Idea**

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 

Good morning,
I have recently installed the new Belchertown skin
https://www.meteocivitavecchia.it/weewx/belchertown/
Fantastic !!! I would like to know what kind of configuration I should enter to get the height of the clouds currently the configuration in the skin.conf is this
  # Station Observations. Special observation rainWithRainRate combines Daily Rain with Rain Rate in 1 line
     station_observations = "barometer", "dewpoint", "outHumidity", "rainWithRainRate", "visibility"
I also inserted the variable "cloudbse"
and in this part I have only translated into Cloudiness
# Extra Observation labels
         appTemp = Apparent Temp
         cloudbase = Cloud cover
         visibility = Visibility
         windrun = Wind Direction
in the home page appears Invalid observation ... where am I wrong?
Thank you

**Comment by poblabs** [comment]
This should work as you expected. Make sure you have the cloudbase label in the right location within weewx.conf

**Comment by fvirgola80** [comment]
Thanks so much for the reply Pat. Could you kindly tell me the area in weewx.conf where I can check?
thanks a lot

**Comment by poblabs** [comment]
Sure, check here https://github.com/poblabs/weewx-belchertown#translating-the-skin

**Comment by fvirgola80** [comment]
Thanks so much for the reply Pat. I show you the configuration of my weewx.conf maybe you can help me better
thanks a lot

 [[StandardReport]]
        # See the customizing guide to change the units, plot types and line
        # colors, modify the fonts, display additional sensor data, and other
        # customizations. Many of those changes can be made here by overriding
        # parameters, or by modifying templates within the skin itself.

        # The StandardReport uses the 'Standard' skin, which contains the
        # images, templates and plots for the report.
        skin = Standard
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = km_per_hour2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                group_speed = km_per_hour
    [[Inigo]]
        HTML_ROOT = public_html/
        skin = Inigo
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = km_per_hour2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_degree_day = degree_C_day
                group_temperature = degree_C
                group_speed = km_per_hour
    [[Belchertown]]
        HTML_ROOT = public_html/belchertown
        skin = Belchertown

**Comment by Stormtracker017** [comment]
In your skin config file did you add the cloud base variable?

# Station Observations. Special observation rainWithRainRate combines Daily Rain with Rain Rate in 1 line
    station_observations = "barometer", "dewpoint", "heatindex","outHumidity", "rainWithRainRate", "radiation", "visibility", "cloudbase"

As for the Extra Observation labels they look fine. 

In the weewx config file:

[StdWXCalculate]
    
    [[Calculations]]
        # How to calculate derived quantities.  Possible values are:
        #  hardware        - use the value provided by hardware
        #  software        - use the value calculated by weewx
        #  prefer_hardware - use value provide by hardware if available,
        #                      otherwise use value calculated by weewx
        
        pressure = prefer_hardware
        altimeter = prefer_hardware
        appTemp = prefer_hardware
        barometer = prefer_hardware
        beaufort = prefer_hardware
        cloudbase = prefer_hardware
        dewpoint = prefer_hardware
        ET = prefer_hardware
        heatindex = prefer_hardware
        humidex = prefer_hardware
        inDewpoint = prefer_hardware
        maxSolarRad = prefer_hardware
        rainRate = prefer_hardware
        windchill = prefer_hardware
        windrun = prefer_hardware

**Comment by fvirgola80** [comment]
Thanks for the response Stormtracker017, I tried to insert the cloudbase variable in the skin.conf and modified the weewx.conf but the problem persists. Invalid observation appears
