### ISSUE TITLE
How to set Belchertown as your homepage on your website?

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#434]
:bulb: **The Idea**

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 

Good morning,
I have recently installed the new Belchertown skin
https://www.meteocivitavecchia.it/weewx/belchertown/
Fantastic !!! I would like to know what kind of configuration I should enter to get the skin as the home page of my site.
The configuration in the weex.conf file is as follows
# This section specifies what reports, using which skins, to generate.

[StdReport]

    # Where the skins reside, relative to WEEWX_ROOT
    SKIN_ROOT = skins

    # Where the generated reports should go, relative to WEEWX_ROOT
    HTML_ROOT = public_html

    # The database binding indicates which data should be used in reports.
    data_binding = wx_binding

    # Each of the following subsections defines a report that will be run.

    [[SteelSeries]]
        skin = ss
        HTML_ROOT = public_html / ss
        [[[Units]]]
            [[[[Groups]]]]
                group_temperature = degree_C
                group_altitude = meter
                group_pressure = mbar
                group_rain = mm
                group_rainRate = mm_per_hour
                group_speed = km_per_hour

    [[Defaults]]
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_degree_day = degree_C_day
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_speed = km_per_hour
                group_speed2 = km_per_hour2
                group_temperature = degree_C

 [[StandardReport]]
        # See the customizing guide to change the units, plot types and line
        # colors, modify the fonts, display additional sensor data, and other
        # customizations. Many of those changes can be made here by overriding
        # parameters, or by modifying templates within the skin itself.

        # The StandardReport uses the 'Standard' skin, which contains the
        # images, templates and plots for the report.
        skin = Standard
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = km_per_hour2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_temperature = degree_C
                group_degree_day = degree_C_day
                group_speed = km_per_hour
    [[Inigo]]
        HTML_ROOT = public_html /
        skin = Inigo
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_speed2 = km_per_hour2
                group_pressure = mbar
                group_rain = mm
                group_rainrate = mm_per_hour
                group_degree_day = degree_C_day
                group_temperature = degree_C
                group_speed = km_per_hour
    [[Belchertown]]
        HTML_ROOT = public_html / belchertown
        skin = Belchertown

    [[FTP]]
        # FTP'ing the results to a webserver is treated as just another report,
        # albeit one with an unusual report generator!
        skin = Ftp

        # If you wish to use FTP, uncomment and fill out the next four lines.
        # Use quotes around passwords to guard against parsing errors.
 user =
        password =
        server = ftp.meteocivitavecchia.it
        path = /www.meteocivitavecchia.it/weewx

What should i change?
Thank you so much

**Comment by Bug-Storm** [comment]
Hii 

First  you need open the door on your router 
after you need install MQTT https://github.com/weewx/weewx/wiki/mqtt

and to create the SLL certificate  https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/ (Go to "Setup LetsEncrypt SSL certificate (optional)" ) 

And on Skin.conf u need change the config of the MQTT , 

```  [[MQTT]]
        server_url = mqtt://username:password@mqtt.hostname:port/
        topic = the/topic/to/publish/to
        unit_system = US
        binding = archive, loop
        aggregation = aggregate
        [[[tls]]]
            tls_version = tlsv1
            ca_certs = /etc/ssl/certs/ca-certificates.crt
 ```

**Comment by fvirgola80** [comment]
Thank you very much for the Bug-Storm answer, but I have not installed MQTT in the guide it says that it is not mandatory. I use the download via FTP and the belchetown page updates every 5 minutes. My problem is figuring out how to distinguish the weewx folder and insert belchetown directly with index.html

**Comment by Brezentrager** [comment]
Ciao,
not sure whether I understand your issue correctly. Are you trying to open your weather page by simple going to https://www.meteocivitavecchia.it ?

If so, can you just activate a re-direct (to the respective sub-folder) in the settings of your hosting provider?
So whenever someone opens https://www.meteocivitavecchia.it he in reality sees the content of the belchertown folder (https://www.meteocivitavecchia.it/weewx/belchertown).
 
That's how I do it.

**Comment by fvirgola80** [comment]
Thank you very much for the Brezentrager reply. I found a script to be able to redirect the Belchertown web page. I update you,
Thank you very much for the input

**Comment by fvirgola80** [comment]
Here is the script that redirects to the correct page
www.meteocivitavecchia.it.
Thank you so much
<?php
$url = "https://your new address";
if ($url) {
header("Location: $url", TRUE, 301);
} else
if($QUERY_STRING) {
header("Location: ".urldecode($QUERY_STRING));
}
else {
echo "Attenzione, l'URL è sbagliato";
}
?>

**Comment by fvirgola80** [comment]
"?php
$url = "https://your new address";
if ($url) {
header("Location: $url", TRUE, 301);
} else
if($QUERY_STRING) {
header("Location: ".urldecode($QUERY_STRING));
}
else {
echo "Attenzione, l'URL è sbagliato";
}
?"
