### ISSUE TITLE
Using weatherRadial css for month graphs

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#435]
:bulb: **The Idea**

weatherRadial graph is interesting for temperature graph; I use it for year but for month the Xaxis is empty

:hammer: **Breaking Feature**

Possibility to use weatheRadial graph for month graph (with Xaxis)
![Weatheradial](https://user-images.githubusercontent.com/65628453/96244308-2d10de00-0fa6-11eb-9439-ef0a01b29300.jpg)

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ddperso** [comment]
Perfect!!
Result:
[image: image.png]

Thank's a lot

**Comment by ddperso** [comment]
![image](https://user-images.githubusercontent.com/65628453/96333798-319fca00-106c-11eb-8aaf-a888ff57af49.png)

**Comment by poblabs** [comment]
This has been merged into the master branch. Thanks!
