### ISSUE TITLE
Fix for unpredictable (a)synchronous updates

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#436]
**What is the issue?**

This issue is about random (unpredictable) behaviour that sometimes may occur when the skin performs updates. It is caused by timing differences between calling the update functions ajaxweewx() and ajaxforecast(). Not every user will experience this behaviour, it depends on the configuration of the skin (and possibly hardware configuration).

The update function ajaxforecast() needs the function ajaxweewx() to perform its update first. Ajaxweewx() loads the weewx_data.json which in turn is used to populate the variables unit_rounding_array and unit_label_array. These last two variables are needed by ajaxforecast() to corrrectly display the visibility parameter.

When ajaxforecast() finishes its tasks before ajaxweewx() does, the visibility parameter will display "undefined" as its unit label hasn't been loaded yet. This is also true for the rounding on the visibility parameter.

At the moment there is no checking if the update functions are called in the right order.

**This issue was also mentioned here:**

I forgot .... when displaying the visibility sometimes I get this undefined instead of KM
Depends on what?
thanks a lot

_Originally posted by @fvirgola80 in https://github.com/poblabs/weewx-belchertown/issues/338#issuecomment-707647642

**How to reproduce:**

Because of its unpredictable behaviour it is difficult to reproduce the error. What may work is repeatedly refreshing the skin homepage. At some point the error may occur.

**How to solve:**
There are numerous ways in which this could be solved. I wrote a solution that will do the following:

1. Make sure ajaxweewx() finishes its tasks first and only then allow any other updates.
2. Catch any errors loading the json or errors in subsequent code.
3. Add the json contents to the debugging console when Belchertown debugging is enabled, this makes debugging much easier.

![JSON Console debugger voorbeeld](https://user-images.githubusercontent.com/67259651/96348384-9f69e700-10a8-11eb-832b-a6006bb84c33.png)

The core of this solution is a modified version of ajaxweewx():

	async function ajaxweewx() {
		resp = await fetch(get_relative_url() + "/json/weewx_data.json");
		if (!resp.ok) {
			throw new Error("HTTP error! Unable to load weewx_data.json");
		} else {	
			return await resp.json();
		}
	}

All further necessary changes are present in my PR.

Maybe it is a good idea to implement this kind of control/error handling to all functions where json loading is involved and display the contents of the jsons in the debugging console when debugging is enabled?

**Comment by gdt** [comment]
From the peanut gallery, 30 days seems overly aggressive for a stale bot to add a wontfix label.

**Comment by poblabs** [comment]
Pull requests are welcome! My time to work on this project has vanished
lately

**Comment by poblabs** [comment]
Updated to 90 days, and removed the `wontfix` label, and am using `stale` instead now

**Comment by ArendPWS** [comment]
This issue was solved with PR #533. Time to close.
