### ISSUE TITLE
the about page does not regenerate after the changes

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#438]
:bulb: **The Idea**

:hammer: **Breaking Feature**

Hello, after modifying the about.inc.example file in about.inc and inserting the html code, the web page no longer regenerates. Depends on what? thanks a lot

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ddperso** [comment]
Have you run wee_reports and refresh your web page?

Le dim. 18 oct. 2020 à 11:50, fvirgola80 <notifications@github.com> a
écrit :

**Comment by fvirgola80** [comment]
no

**Comment by ddperso** [comment]
try it

Le dim. 18 oct. 2020 à 11:56, fvirgola80 <notifications@github.com> a
écrit :

**Comment by fvirgola80** [comment]
You would be kind enough to show me the command I should use.
Thank you

**Comment by ddperso** [comment]
Under PUTTY, only type the command wee_reports

That's all
[image: image.png]

Le dim. 18 oct. 2020 à 12:03, fvirgola80 <notifications@github.com> a
écrit :

**Comment by fvirgola80** [comment]
Thanks a lot now it works

**Comment by ddperso** [comment]
Perfect!
You have to do that when you make a change in Belchertown folder
If you change weewx.conf, you have to run "systemctl restart weewx" before
"wee_reports"

You can close the issue.

Le dim. 18 oct. 2020 à 12:12, fvirgola80 <notifications@github.com> a
écrit :

**Comment by fvirgola80** [comment]
thanks a lot
