### ISSUE TITLE
 The index.html page in the about folder does not update

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#440]
:bulb: **The Idea**

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 

good evening,
i noticed that the index.html page is not updated.  https://www.meteocivitavecchia.it/weewx/belchertown/about/ In the upper left part where the weather data are reported they are not updated like the other pages.
What can it depend on?
Thank you

**Comment by poblabs** [comment]
Have you seen the readme? You must update the about.inc file.

**Comment by fvirgola80** [comment]
Good evening Pat,
to be honest i didn't read the redme.txt file.
Where can I find it?

**Comment by fvirgola80** [comment]
I created a new about.inc file in the /home/weewx/skins/Belchetown/about.in folder I restarted weewx by adding the code suggested by you.
What did I go wrong?

**Comment by poblabs** [comment]
I don't know. Please attach logs and debug information.

**Comment by fvirgola80** [comment]
ok

**Comment by fvirgola80** [comment]
Hi Pat,
I understood why the index.html web page in the about folder was not updated.
There were accenting characters. Replaced the result is obvious
https://www.meteocivitavecchia.it/weewx/belchertown/about/

thanks a lot
