### ISSUE TITLE
Master Version on github

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#441]
I have upgraded my live site to release 1.2 ( http://lordshipweather.uk ) and am now preparing a PR from my test site 
( http://lordshipweather.uk/hourly ) for the different forecasts.  However, when I download the master from github into GitHub desktop, belchertown.py is showing version 1.1, not 1.2.  Is this correct or am I doing something wrong?

Michael

**HELP WANTED**

**Comment by ArendPWS** [comment]
@michaelundwd 

Your fork is 1.1, create a new one?

**Comment by michaelundwd** [comment]
@ArendPWS 
Thanks, I was coming to the same conclusion - I'm still finding my way around this github stuff.
Michael
