### ISSUE TITLE
GeoNet only showing "No recent earthquake data available!"

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#449]
Pat

Just adding this in as an issue as it seems to have dropped off the radar :) I've tried the last update where you thought you had found the problem but the issue still remains.

Cheers

**Comment by 41south** [comment]
Just a little bump to see if there is any progress?

**Comment by 41south** [comment]
Hi, wondering if anyone has had a chance to look at this yet, still not working

**Comment by 41south** [comment]
Problem sorted by author of GeoNet modification 👍

**Comment by poblabs** [comment]
Great news! I've merged it into the master branch.
