### ISSUE TITLE
Progressive webapp 

### ISSUE THREAD

**Issue by JRaiml** [poblabs/weewx-belchertown#450]
Hello. Just installed Belchertown but if i add to homescreen and start i get this page.
What am i doing wrong?

Best Regards
Joacim
![Screenshot_20201029-082130](https://user-images.githubusercontent.com/27809320/97538751-38f69a00-19c1-11eb-9fa9-047a06d15fd2.jpg)

**Comment by thedayofcondor** [comment]
I can confirm - i get the same behaviour

**Comment by thedayofcondor** [comment]
From a quick hack - it seems that the problem is the start_url in manifest.json.

Settings `start_url:”/”` or even removing it entirely fixes the problem.

My setup is the skin installed in the root web folder and set as default.
