### ISSUE TITLE
How to make changes to front page?

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#460]
:bulb: **The Idea**

On the main page, in the section next to the current temp, etc. (where 
Barometer, Dew Point, Humidity, Rain are show)  It's not clear how to add or change
values there.   For example, I'd like to add AQI info there
(with the AQI plugin --https://github.com/jonathankoren/weewx-aqi )
and Indoor Temp/Humidity.   I read thru the graphs manual, but I didn't 
see anything pointed me towards this info. 

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 

If you can point me to files, etc. where I could make changes here, would be useful.
A Wiki page for this section would he be helpful.

**Comment by earlthesquirrel** [comment]
Any update/feedback?

**Comment by earlthesquirrel** [comment]
Anything?

**Comment by earlthesquirrel** [comment]
Do you see these Requests??

**Comment by poblabs** [comment]
I sure do. Reminder that I work on this in my free time. 

Having an infant and a toddler take up most of my free time. 

That's why it says:

```
HELP WANTED
If you have a fix for this, please submit a pull request against the development branch!
```

**Comment by earlthesquirrel** [comment]
Thanks — I understand ( special needs son adopted from Kyrgyzstan).   Could you point me towards the files where this is generated?  I’ll write up what I do, just need a starting point.  I appreciate all you do here!

**Comment by poblabs** [comment]
You'd have to edit the source file. Most of the front page stuff lives in the index.html.tmpl file. The auto-updating stuff is in belchertown.js.tmpl file. There's also [the "hook" areas ](https://github.com/poblabs/weewx-belchertown#add-custom-content-to-the-front-page)which may help you out too.

**Comment by earlthesquirrel** [comment]
Thanks!  I hadn't seen that "hooks" wiki page... missed that.
Will be checking the index.html.tmpl file... that is a helpful pointer!  Thanks!!
