### ISSUE TITLE
Angular Gauges for displaying information.

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#461]
:bulb: **The Idea**

I'd like to display an "Angular gauge" on the skin.
https://www.highcharts.com/docs/chart-and-series-types/angular-gauges

This would be useful for displaying current AQI and info from the 
Geiger Counter I've now got feeding into the system.   A "1/2" dial would
probably be best (with different colors for the various AQI info)

Might also be useful for other weather data for the "current" values.
I like text, personally, for most of that, but some folks might like gauges.

(for AQI and uSieverts/Hr a dial with colors is the best way to show info, IMHO)

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by earlthesquirrel** [comment]
Any update//feedback??

**Comment by uajqq** [comment]
Does the current gauge chart functionality do what you’re looking for? I didn’t add the default needle-type gauge because it didn’t really fit in with the overall aesthetic of the skin.

**Comment by earlthesquirrel** [comment]
Not really.  For the Geiger Counter info, some sort of needle gauge would be the best display, with perhaps a mileage type number underneath.  

Most recent info on a scaled dial ( ie green, yellow red somehow) is how it’s normally shown.
