### ISSUE TITLE
Aeris icon showerswn missing.

### ISSUE THREAD

**Issue by James-76** [poblabs/weewx-belchertown#462]
Hello

Whilst enjoying the excellent work done by @michaelundwd on my website, I've spotted that one of the Aeris Weather definitions is missing from user/belchertown.py
 
```
         "showers": "rain",
         "showersn": "rain",
         "showersw": "rain",
+        "showerswn": "rain",
         "sleet": "sleet",

```

and js/belchertown.js.tmpl

```
         "showers": "rain",
         "showersn": "rain",
         "showersw": "rain",
-        "showersw": "rain",
+        "showerswn": "rain",
         "sleet": "sleet",
```

Keep up the good work.

James

**Comment by michaelundwd** [comment]
Thanks for spotting this.  Rather than there being a missing entry in belchertown.py, it's a duplicate entry "showersw": "rain", in belchertown.js.tmpl.  
It's not doing any harm there, but should be tidied up at a suitable point.
Michael

**Comment by michaelundwd** [comment]
@James-76 
Have just has another more careful look at this one and I misunderstood the point you were making.  In addition to the duplicate showersw in belchertown.jst.tmpl, neither of the two files have showerswn (windy showers at night).  Looks like both files need an amendment to stop showerswn.png yielding an undefined.   I'll have a go when I have updated my test system with the latest merges; it's too far behind as it stands.
Michael

**Comment by James-76** [comment]
Correct I was just trying to show that showerswn was missing in both files and showersw was duplicated in one.

I can submit a pull to correct it now it has been merged with master since I've now worked how that all works.

**Comment by michaelundwd** [comment]
OK, thanks
Michael
