### ISSUE TITLE
Reports showing non-existent data

### ISSUE THREAD

**Issue by tomdotorg** [poblabs/weewx-belchertown#466]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

I just brought a new station online in mid-Nov with weewx at 4.2.0 and Belchertown skin at 1.2.

Classic weewx skin (http://whales-classic.tom.org) shows correctly that there are no data before 11/21. The Belchertown reports (http://whales.tom.org) shows sporadic data from April on.

**Link to your website (IMPORTANT)**

Above, but http://whales.tom.org and http://whales-classic.tom.org

**Version of the skin you're using**

1.2

**To Reproduce**

**Expected behavior**

I would expect the two skins to reflect the actual data in the database.

**Screenshots**

![image](https://user-images.githubusercontent.com/52498/100730733-7079ad00-3398-11eb-8026-b679263cb122.png)

![image](https://user-images.githubusercontent.com/52498/100730804-8a1af480-3398-11eb-9a44-9620275b6239.png)

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

several

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
Is this a new database? Delete the NOAA files and let weewx regen them and see what happens?

**Comment by tomdotorg** [comment]
@poblabs - no idea how the stray reports got there, but this worked for me. Thank you.
