### ISSUE TITLE
Darksky Forecast shows Snow Forecast in inch instead mm

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#47]
The DarkSky Forecast shows most of the values in Metric format except the predicted amount of snow, which is still in inch

Can this be changed?

Br,
Johannes

**Comment by ebnerjoh** [comment]
Hi, 

I have set to:
`            darksky_units = ca
            darksky_lang = de
`
ca should be: same as si, except that windSpeed and windGust are in kilometers per hour

But from your answer I expect it is an issue of DarkSky and not your skin.

Br,
Johannes

**Comment by poblabs** [comment]
Hmm, maybe. Can you attach your `public_html/json/darksky_forecast.json`? Or run it through https://jsonformatter.org/

Go to the bottom and sure the units are correct.

**Comment by ebnerjoh** [comment]
Yes, you are right. at the bottom I can see:

`"units":"ca"}`

And instead: "Snow: x inch" I can see "Schneefall: x cm"

Br,
Johannes

**Comment by ebnerjoh** [comment]
btw. This is the site I am talking:

[](https://wetter.familie-ebner.at)
[](https://wetter.familie-ebner.at/json/darksky_forecast.json)

**Comment by poblabs** [comment]
This is helpful. I will see if I can take a look at it in the next day or two.

**Comment by ebnerjoh** [comment]
Hi,

did you had time to check on this topic? I still have inch for the snow forecast, although all other values are in metric.

Br,
Johannes
