### ISSUE TITLE
Help Wanted - Incorrect Aeris Weather Forecast

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#470]
Hello Pat.
Since i switched to aeris weather I've found that data taken from the forecast endpoint doesn't match with forecast data that it is published in their website.
This is my forecast.json for today. 2PM GMT -3 Weather code is RW.

```
              "cloudsCoded": "FW",
              "weather": "Partly Cloudy with Light Rain Showers",
              "weatherCoded": [
                {
                  "timestamp": 1607162400,
                  "wx": ":VL:RW",
                  "dateTimeISO": "2020-12-05T07:00:00-03:00"
                }
              ],
              "weatherPrimary": "Rain Showers",
              "weatherPrimaryCoded": ":VL:RW",
              "icon": "rain.png",
```
This is forecast data taken from Aeris website and it matches with current conditions. Today is a sunny day.
![image](https://user-images.githubusercontent.com/4549674/101259321-f6825480-3706-11eb-99bc-ec01f41648eb.png)

Did you find similar problems for your location? I think I should try to open an issue in Aeris Weather. I also attached complete json file.
[forecast.json.txt](https://github.com/poblabs/weewx-belchertown/files/5647561/forecast.json.txt)

**Comment by poblabs** [comment]
Try disable or enable the METAR option in the forecast url in Belchertown.py

**Comment by HoracioDos** [comment]
Metar option is on in weewx.conf I will set it off and I'll report back if it helps other users.
`forecast_aeris_use_metar = 1`
Thanks for your quick answer.

**Comment by poblabs** [comment]
Oh I forgot I had it as option. Life has been busy :)

Yes try that

**Comment by HoracioDos** [comment]
I'm in contact with Tony from Aeris weather customer support. He asked me to provide demo page URL for the forecast request.
I sent him back that info and I also checked how the forecast request is done in belchertown.py. Both resquests are identical.
I'm still waiting for the new forecast request with metar option off

**Comment by HoracioDos** [comment]
Hello!
Aeris Weather customer support answered me that the difference in the forecast is based on the differences in latitude/longitude for their city centroid for Buenos Aires and the lat/lon  that I'm querying. I'm exactly 5.2 miles away from their centroid coodinates.
Forecast response for this centroid location is:
`"weatherPrimary":"Mostly Sunny","weatherPrimaryCoded":"::FW","icon":"fair.png`
At least it is not raining and it's not mostly sunny either.

I'm completely sure that the forecast for my location is wrong and Aeris Weather doesn't have that kind of granularity. Buenos aires is all flat, we don't have any kind of mountain or hills. They can't tell if it's going to rain 5 miles away from a given point. I don't want to rant here but I'll think later if I want to hard code centroid coordinates in belchertown.py if it offers a more accurate forecast or if I'll remove forecast completely.
I hope this can help someone else.

**Comment by HoracioDos** [comment]
I've made some changes in belchertown.py in forecast section. The idea is to get forecast based on location instead of coordinates. Location matches what Aeris weather calls centroid coordinates for a given city.

I defined a new keyword `forecast_location_based` and I recover already defined key station `location`.  

```
location = self.generator.config_dict['Station']['location']
forecast_location_based = self.generator.config_dict['Extras']['forecast_location_based']
```
then I added a new If else sentense to get forecast based on coordinates or based on location
```
if forecast_location_based == "0":
   forecast_url = "https://api.aerisapi.com/forecasts/%s,%s?&format=json&filter=day&limit=7&client_id=%s&client_secret=%s" % ( latitude, longitude, forecast_api_id, forecast_api_secret)
else:
   forecast_url = "https://api.aerisapi.com/forecasts/%s,%s?&format=json&filter=day&limit=7&client_id=%s&client_secret=%s" % ( location, forecast_api_id, forecast_api_secret)

```
I'll test this change and report back.

**Comment by HoracioDos** [comment]
Aeris weather forecast seems to match Google forecast and Meteored now (Spanish weather Service) for my region, I'll test this way to get the forecast for a while.
