### ISSUE TITLE
Keep windy from using location?

### ISSUE THREAD

**Issue by treaves** [poblabs/weewx-belchertown#473]
I've got over to Windy.com and created a custom link to embed, that includes my lat & lon.  However, windy still requests to use location information.  Does anyone know how to prevent this?

**Comment by bricebou** [comment]
I don't have this issue with this "radar_html" value in my `/etc/weewx/weewx.conf`:

```
[[Belchertown]]
        [[[Extras]]]
            radar_html = "<iframe width='650' height='450' src='https://embed.windy.com/embed2.html?lat=46.087&lon=1.475&detailLat=45.640&detailLon=1.501&width=650&height=450&zoom=11&level=surface&overlay=rain&product=ecmwf&menu=&message=true&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1' frameborder='0'></iframe>"
```

**Comment by treaves** [comment]
Nor do I when using your iframe; this is likely due to the country.  Would you try mine?

     <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=41.023&lon=-82.133&detailLat=41.023&detailLon=-82.133&width=650&height=450&zoom=9&level=surface&overlay=radar&product=radar&menu=&message=true&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe>

**Comment by bricebou** [comment]
Hum... my different browsers (Firefox, Chromium or Vivaldi under Linux) don't ask me anything, with my iframe or yours...

What browser are you using ?

**Comment by treaves** [comment]
Ah.  That could be it.  My phone/table/pc all use Safari.  Chrome does not seem to do this.  So the issue is that Windy.com is asking for the data (for some reason - tracking perhaps) and Safari's privacy policy requires approval; Chrome's does not.

**Comment by InToSSH** [comment]
I noticed the same problem, but I don't think it's about the browser. I am using Chrome and it was asking me for location aswell. What I found is that it is asking for location only if you set the overlay to "Radar, lightning" in the top right corner, then it will use the location and show the marker.
Looking at the iframes of the two of you I can see @treaves has "overlay=radar" in the link, but @bricebou has "overlay=rain", which doesn't ask for location.

**Comment by roe-dl** [comment]
I observed that on iPhone and iPad, but not elsewhere. But no message does not mean they do not request that information. It only means that the browser does not report.

**Comment by roe-dl** [comment]
I found out that the URL for embedding the Windy map contains the location twice, one to define the location of the map and one for the location of the small blue mark. If the value for the latter is missing within the URL, they ask for the location of the user. If that is not available the mark is set at the location where the IP address is located according to some geolocating service, whatever. I will try to change the URL, but it is deep Cheetah and JavaScript code, so I did not find out how to change by now.

**Comment by treaves** [comment]
Nice find!

**Comment by uajqq** [comment]
It still asks me for location every time on iOS systems even when the location is defined in both places. Here's the URL it's using:

```
https://embed.windy.com/embed2.html?lat=[xxx]&lon=[xxx]&zoom=6&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&detail=&detailLat=[xxx]&detailLon=[xxx]&metricWind=default&metricTemp=default&radarRange=-1
```

Android/desktop users can set it to automatically accept on a per-website basis, but I'm not aware of a way to make iOS accept it, besides automatically accepting on ALL websites (not ideal).

**Comment by gdt** [comment]
It seems like this is a question for windy tech support.   I see it as a problem for a website to embed something that asks users to send location.   It should certainly be possible to have the URL specify that it is not desired to query the user's location.

(I'm also surprised at the notion that Chrome sends location without explicit permission.)

**Comment by uajqq** [comment]
According to Windy administrator, the Radar layer will always ask for user location no matter what coordinates are set:
![image](https://user-images.githubusercontent.com/46248396/104029606-2e623900-5198-11eb-9ccf-3607ba668ee5.jpeg)

**Comment by roe-dl** [comment]
I don't think so. If you configure such iframes on their site you see how it works and which option is missing. The only problem, I encounter with that, is, that I do not understand the code in index.html.tmpl to change it.

**Comment by roe-dl** [comment]
Now I found out, where the setting of the iframe url resides: it is located within the belchertown.py file in the user directory (/usr/share/weewx/user/belchertown.py in my case). That's why I found nothing, if I searched the skin directory.

It is possible to change the url by putting a line "radar_html = '<iframe ....'" into weewx.conf or skin.conf, where you can insert the code you got from the configuration page on Windy.

@uajqq Now I think you are right. The code in belchertown.py sets both options for latitude and longitude ("lat" and "lon" as well as "detailLat" and "detailLon"), yet the mark in the map shows the location of the user, not that one of the station. So I have to correct my own statement half a day ago.

**Comment by poblabs** [comment]
You can put a pin on the map where your station is, but your user location "blip" icon will always be the geolocation of your device. 

This is all controlled by windy and not by Belchertown, so I think this issue can be closed.

**Comment by uajqq** [comment]
See my pull request #522. Adds the ability to use maps from Aeris Weather, which do not ask for location.
