### ISSUE TITLE
Can we get color graded graphs?

### ISSUE THREAD

**Issue by Distortionist** [poblabs/weewx-belchertown#474]
:bulb: **The Idea**

It would be awesome if we can set colors in graphs depending on their values, and have a color legend. For example have the temperatures color change from blue to red the hotter it gets.
Another example is Air Quality, it would be nice the color corresponds to the index, green, orange and red, and optionally make it gradually change as the values increase or decrease.

Air quality needs more attention in belchertown, not just the colors in the graph, maybe a dedicated section with a graphic, most people have no clue what 3.9 ug/m3 is.

**Comment by uajqq** [comment]
I added a pull request [here](https://github.com/poblabs/weewx-belchertown/pull/475)with color-coded current AQI data. My next project is to see if I can get a color-coded AQI graph working.

**Comment by Distortionist** [comment]
> I added a pull request [here](https://github.com/poblabs/weewx-belchertown/pull/475) with color-coded current AQI data. My next project is to see if I can get a color-coded AQI graph working.

Ill be honest, I am pretty new here and I can't understand what you are trying to tell me. I went there and see an error log. You mention there you have AQI data but no color from aeries weather. I have an air quality sensor and it works, I have the reading in Belchertown and a graph. My request is to enable graphs with color coding for the aqi sensor, and maybe a scale or something. No one knows what AQI 3 um/g is when they see it. You can label it AQI or call it Air Quality but still no one knows what 3 ug/m3 is, if it is clean or dirty know what I mean? Maybe we can have a scale on the bottom of the top left where the temperature is, if underneath it it said air quality, and then a little bar with an indicator showing where it is from good to bad, green to red. Just so people understand. The colored graphs is the final candy, it looks like it can be done in some charts like temperature or wind in the given examples.

**Comment by poblabs** [comment]
Maybe you can put what you want inside a custom hook? Have you checked out the readme? https://github.com/poblabs/weewx-belchertown#add-custom-content-to-the-front-page

**Comment by uajqq** [comment]
> I went there and see an error log. You mention there you have AQI data but no color from aeries weather. 
Please scroll down, in later commits to the pull request I added support for color coding.

> No one knows what AQI 3 ug/m3 is when they see it
AQI is an index calculated from readings of particulate matter in the air. It has no units. If you’re seeing ug/m3 or something similar, that’s not AQI. If you have an air quality sensor it should be able to report in AQI.

> My request is to enable graphs with color coding for the aqi sensor, and maybe a scale or something
I’ve been tinkering with something for that push request, but in the meantime you could add a custom chart using custom hooks, as documented in the readme by @poblabs.

**Comment by Distortionist** [comment]
> > I went there and see an error log. You mention there you have AQI data but no color from aeries weather.
> 
> Please scroll down, in later commits to the pull request I added support for color coding.
> 
> > No one knows what AQI 3 ug/m3 is when they see it
> 
> AQI is an index calculated from readings of particulate matter in the air. It has no units. If you’re seeing ug/m3 or something similar, that’s not AQI. If you have an air quality sensor it should be able to report in AQI.
> 
> > My request is to enable graphs with color coding for the aqi sensor, and maybe a scale or something
> 
> I’ve been tinkering with something for that pull request, but in the meantime you could add a custom chart using custom hooks, as documented in the readme by @poblabs.

I will try to use the hooks, I don't know http, it has been 20 years since I took a http course! I know enough though to MacGyver something what I want done usually so I will look into it. I will also try to understand what you have going on in the link you provided this weekend. I have been busy with work and have had little time to dedicate to this. As you can see I am not a scripter/programmer person at all and everything I am doing I am learning from ground up pretty much.

**Comment by uajqq** [comment]
I’ve updated my pull request  #475. You can now add a graph that shows current AQI, and it changes colors dynamically.

**Comment by Distortionist** [comment]
I'll check it out when I can!

**Comment by uajqq** [comment]
I closed my old pull request and opened this new one to clean up the history: #480

**Comment by poblabs** [comment]
This has been merged, thanks @uajqq !
