### ISSUE TITLE
measurement unit 'undefined'

### ISSUE THREAD

**Issue by quinntj** [poblabs/weewx-belchertown#476]
Hello,
How can I fix the missing/undefined measurement unit?

you can see it here: http://weather.battle4heaven.com/arvada/
under station observations, ground dew point (I'm using the dewpoint1 database field for this) also, Visibility will often show undefined, but sometimes show feet or miles.... 

any thoughts?

Thanks!

**Comment by ArendPWS** [comment]
Visibility displaying "undefined" as unit was something I experienced too. This was caused by (a)synchronous updating of the json files. My pull request #437 fixed this, but hasn't been implemented yet.

**Comment by poblabs** [comment]
Hi @ArendPWS  thanks for the pull request. your pull request has a lot of changes in it which is why I have not merged it yet. I think you may need to close your pull request and download the latest copy of Master, add your changes, and open a new pull request. Thanks!

**Comment by ArendPWS** [comment]
@poblabs The version I am currently using has evolved way to far to simply do another pull request. I sorted everything out in the previous mentioned pull request, but got no response. That's OK. But I stick to my version for now and maybe somewhere in the future the version will line up again.

**Comment by poblabs** [comment]
You could make a new branch on your GitHub, copy the necessary code to that
Branch then create a new pull request from that branch. As it is right now
I'm not able to merge your changes.

**Comment by ArendPWS** [comment]
@poblabs, I created a new branch and try to keep it in sync with your master. Don't have much time at the moment, but will try to add the async fix at some point. I have a question too: what is the meaning and purpose of the new file called .python-version?

**Comment by poblabs** [comment]
Good question on the .python-version. I think that was committed by mistake as it's not needed. Perhaps from one of the pull requests recently.

**Comment by uajqq** [comment]
Looks like it got merged as part of #485

**Comment by ArendPWS** [comment]
> Hello,
> How can I fix the missing/undefined measurement unit?
> 
> you can see it here: http://weather.battle4heaven.com/arvada/
> under station observations, ground dew point (I'm using the dewpoint1 database field for this) also, Visibility will often show undefined, but sometimes show feet or miles....
> 
> any thoughts?
> 
> Thanks!

@quinntj

The first problem with Visibility displaying undefined will be fixed with my PR #523.

The issue with the ground dew point showing no unit must be related to something missing in your configuration or perhaps requires a modification of your weewx_data.json. When my PR has been implemented it will be much easier to figure out what exactly is going on.

**Comment by ArendPWS** [comment]
@quinntj

The first problem you mentioned (Visibility unit showing undefined) should be solved now with my PR #533. If you want to try please download and install the unreleased master:

[https://github.com/poblabs/weewx-belchertown/archive/master.zip](https://github.com/poblabs/weewx-belchertown/archive/master.zip)
