### ISSUE TITLE
Add Free Software graphs

### ISSUE THREAD

**Issue by gdt** [poblabs/weewx-belchertown#481]
:bulb: **The Idea**
Highcharts is not Free Software, and thus this skin isn't really usable by people who limit their websites to pages consisting entirely of Free Software.  It would be really nice if there were a way to have graphs that didn't have a non-Free dependency, even if they didn't update from MQTT.   I was just starting to think again about using this, but stopped because I don't want to serve proprietary software.

:hammer: **Breaking Feature**
I'm not suggesting removing highcharts entirely, so this would be some sort of configuration to choose another graph approach.  Thus, there is no immediate compat issue.

I realize that the answer is probably ENOPATCH, but also that it's good for this issue to be in the tracker as it helps clarify the situation to people that don't understand already.

**Comment by gdt** [comment]
There's a list at https://github.com/fasouto/awesome-dataviz

**Comment by poblabs** [comment]
Great idea. Hopefully someone can help implement it.

**Comment by Stormtracker017** [comment]
It depends on your website: "Highcharts is free to use for personal projects, school websites, and non-profit organizations. For commercial purposes, Highcharts offers license packages."

**Comment by gdt** [comment]
While it may be used without payment, but it is never "Free Software", which was defined long ago by the Free Software Foundation: https://www.gnu.org/philosophy/free-sw.html

**Comment by poblabs** [comment]
I just came across this yesterday. I wonder if this is a viable replacement for the charts with something free and open source? https://apexcharts.com/

**Comment by gdt** [comment]
I hadn't heard of it, but it looks promising.   From my point of view, if I could run Bskin with just the basic graph of a few variables vs time, getting at least the functionality of Seasons, that would be great.   I don't really know how others feel of course.   I guess there is the wind rose, annual temp range chart, that are probably missing.

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
jas is using https://echarts.apache.org/en/index.html although I don't see analogs of the fancier graphs.

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Hey bot: the issue is still valid!

**Comment by gdt** [comment]
Actually it seems not "completed", but mis-closed by the bot, unless I missed something huge :-)
