### ISSUE TITLE
Missing Aeris alert type

### ISSUE THREAD

**Issue by dciarniello** [poblabs/weewx-belchertown#483]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

There is currently a Fog Advisory in my area that is being displayed as *undefined in effect until December 23, 2020 11:18 AM*

**Version of the skin you're using**
Belchertown 1.2

**To Reproduce**
Enable aeris forecast 
Have a Fog Advisory in effect

**Expected behavior**
Alert displayed as *Fog Advisory in effect until December 23, 2020 11:18 AM*

**Additional context**
The problem is that the alert type returned by Aeris is FO.Y which is missing from alert_dict in aeris_coded_alerts.  
This is most likely due to the fact that the Aeris documentation is incomplete in that it does not list FO.Y as an alert type on
https://www.aerisweather.com/support/docs/aeris-maps/reference/alert-types/ even though it is returned by the API.

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by uajqq** [comment]
See #484

**Comment by dciarniello** [comment]
Thanks for the quick fix.

Minor note about the fix.  I'm not sure if the label in skin.conf is supposed to reflect the value of the 'name' field in aeris response but if it does, then the label should be "Fog Advisory" not "Dense Fog Advisory".  Sorry, I should have been more explicit about that.

**Comment by uajqq** [comment]
Ah yes, sorry. I adjusted the wording
