### ISSUE TITLE
Beaufort scale

### ISSUE THREAD

**Issue by thagorastos** [poblabs/weewx-belchertown#494]
Hi everyone!

Quick question. Belchertown does not yet support the Beaufort scale for observations except for the wind rose chart, correct? Would it be easy to extend the Beaufort scale support so as to be able to present wind speed in this unit?

For some strange reason in Greece, everyone uses the Beaufort scale for wind speed!

Thank you all for providing this great skin! I love it and use it as primary for my school weather station project.

**Comment by uajqq** [comment]
I have the Beaufort scale working on Belchertown, and it seems like everything's being calculated correctly, but weewx is throwing some weird errors that I can't figure out, so I don't want to open a pull request until that gets resolved. Stay tuned (I opened an issue with weewx at (https://github.com/weewx/weewx/issues/629#issue-775104120)

**Comment by uajqq** [comment]
@thagorastos Okay, it was a confirmed bug with weewx. They fixed it right away, so I’ll put in my pull request here. Bear in mind to use it properly, you’ll have to be using the latest development version of weewx—the fix won’t be officially published until weewx 4.3. Belchertown should still work if you specify Beaufort as a scale, but you’ll have some errors on the standard weewx skin (specifically the wind vector plot).

**Comment by uajqq** [comment]
See #497

**Comment by Stormtracker017** [comment]
When live MQTT data is being published, is there away to display both speed and Beaufort scale in real time.

https://user-images.githubusercontent.com/48191231/103302913-bf842380-49d2-11eb-9198-8107a481de6e.mp4

**Comment by poblabs** [comment]
#497 has been merged. 

@Stormtracker017 Not sure. If the beaufort is in your MQTT payload, then probably a way to do it. You'll have to check the debug of the skin and see what's in your payload.

**Comment by uajqq** [comment]
> When live MQTT data is being published, is there away to display both speed and Beaufort scale in real time.

Working on this!

**Comment by Stormtracker017** [comment]
**@poblabs** It is not in the MQTT payload. **@uajqq**  I see you are working on this...thanks

**Comment by uajqq** [comment]
> **@poblabs** It is not in the MQTT payload. **@uajqq**  I see you are working on this...thanks

Can you do me a favor: in weewx.conf, make sure the following is present. If not, add it:
```
[StdWXCalculate]
    [[Calculations]]
          beaufort = prefer_hardware
```

After adding that line, does `beaufort_count` appear in your MQTT payload?

**Comment by Stormtracker017** [comment]
Added "beaufort = prefer_hardware" to [[Calculations]] in weewx.conf.  The beaufort_count now appears in the MQTT payload.

**Comment by uajqq** [comment]
All right, see if this works: #501

**Comment by Stormtracker017** [comment]
***********Update***************
So far, here is what I did:
Updated the three files
Added the following to the weewx file:
[[Belchertown]]
        skin = Belchertown
        HTML_ROOT = public_html
        enable = true
        beaufort_category = 1

Don't know if this would cause an issue, but the value is coming across as a float.  "beaufort_count": "0.0",

Now need to wait for some wind.

**Comment by uajqq** [comment]
> Don't know if this would cause an issue, but the value is coming across as a float. "beaufort_count": "0.0",
> 
> Now need to wait for some wind.

That's correct, it should be a float. The code should handle that correctly.

Is it working? Even with no wind you should see "calm."

**Comment by Stormtracker017** [comment]
Right now it is not showing "calm".  see attached.
![Beauford scale (mod)_12312020](https://user-images.githubusercontent.com/48191231/103431062-809fca80-4b98-11eb-965b-5b05ea98cfea.png)

**Comment by uajqq** [comment]
Can you post examples of your MQTT payloads?

**Comment by Stormtracker017** [comment]
I even cleared the cache and rebooted the RPI.  Attached is the example.

[MQTT example.txt](https://github.com/poblabs/weewx-belchertown/files/5758485/MQTT.example.txt)

**Comment by uajqq** [comment]
Just to check, is `beaufort_category = 1` set as follows:
```
[StdReport]
    [[Belchertown]]
        [[[Extras]]]
            beaufort_category = 1
```

The example you posted left out the "Extras" part--it has to be defined under that stanza.

**Comment by Stormtracker017** [comment]
Added [[[Extras]]] stanza to weewx.config.  Now "calm" does appear.  Is there a way to increase font size?

![Beauford scale (mod)_12312020](https://user-images.githubusercontent.com/48191231/103433593-d177e900-4bc1-11eb-8b83-17fc28dcad29.png)

**Comment by Stormtracker017** [comment]
*****Update****

Now you can display Beaufort Scale below the speed unit.

https://user-images.githubusercontent.com/48191231/103440574-c8643780-4c14-11eb-9fec-645e18708f5f.mp4

**Comment by uajqq** [comment]
> Is there a way to increase font size?

No built-in way—you’d have to edit the stylesheet or the code itself. The class is `.beaufort`.

**Comment by creas002** [comment]
> 
> 
> > Is there a way to increase font size?
> 
> No built-in way—you’d have to edit the stylesheet or the code itself. The class is `.beaufort`.

I increase the Beaufort scale and added color by : 

I modified my copy of the merged index.html.tmpl line 293 to `<td class="beaufort" colspan="4" style="color:limegreen;"></td>`

I modified my copy of the merged style.css line 1448 to `font-size:24px;`

**Comment by poblabs** [comment]
You could use the [custom.css option](https://github.com/poblabs/weewx-belchertown#custom-css) to save custom CSS styles. 

Is this issue set to be closed?

**Comment by creas002** [comment]
> 
> 
> You could use the [custom.css option](https://github.com/poblabs/weewx-belchertown#custom-css) to save custom CSS styles.
> 
> Is this issue set to be closed?

Excellent, Thanks for the suggestion to save to custom.css   It worked like a Champ! 

Many thanks for getting this update merged.
