### ISSUE TITLE
Air Quality - closest - does not work

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#498]
**Describe the bug**

Air quality by "closest" method does not work in belchertown.py (aqi_url = "https://api.aerisapi.com/airquality/closest?p=%s,%s&format=json&radius=50mi&limit=1&client_id=%s&client_secret=%s" % ( latitude, longitude, forecast_api_id, forecast_api_secret )
You can test it with api wizard https://www.aerisweather.com/wizard/api/options?endpoint=airquality&action=id

But "location" method is OK
Change in py file by:
aqi_url = "https://api.aerisapi.com/airquality/%s,%s?&format=json&client_id=%s&client_secret=%s" % ( latitude, longitude, forecast_api_id, forecast_api_secret )

**Version of the skin you're using**
Last release

**Comment by uajqq** [comment]
I'm actually getting just the opposite problem. The "closest" method is working for me right now in the master branch, but when I try to change the URL to "location," I get a "bad request" error even though that URL produces valid output when I put it into a browser. Trying to figure out why

**Comment by ddperso** [comment]
Strange....

**Comment by ddperso** [comment]
@uajqq 
Do you think that it's possible to store aqi in the database in order to generate a graph?
I don't know if it is difficult or not (I am not a high level programmer...)

**Comment by uajqq** [comment]
It is a little difficult. There are a few projects here on GitHub that could potentially help. I haven't looked into it much.

**Comment by HoracioDos** [comment]
Hello. I've haven't been applying commits since last year. Yesterday I applied all of them. 

AQI request doesn't work for my region.
```
weewx[1638] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was:list index out of range
The response from the Aeris AQI server was:
[{'success': True, 'error': {'code': 'warn_no_data', 'description': 'Valid request. No results available based on your query parameters.'}, 'response': []}]
The URL being used is: https://api.aerisapi.com/airquality/closest?p=-34.571900,-58.455700&format=json&radius=50mi&limit=1&client_id=myclientId&client_secret=mysecretid
```
So I changed AQI request to use my station location in belchertown.py and that works fine.

```
            if aqi_centroid_location == "0":
               aqi_url = (
                   "https://api.aerisapi.com/airquality/closest?p=%s,%s&format=json&radius=50mi&limit=1&client_id=%s&client_secret=%s"
                    % (latitude, longitude, forecast_api_id, forecast_api_secret)
               )
            else:
               aqi_url = (
                   "https://api.aerisapi.com/airquality/?p=%s&format=json&client_id=%s&client_secret=%s"
                    % (requests.utils.quote(centroid_location), forecast_api_id, forecast_api_secret)
               )
```
I have opened and closed an old issue talking about centroid coordinates meaning for Aeris weather and how it affects forecast requests too. https://github.com/poblabs/weewx-belchertown/issues/470#issuecomment-739423663
