### ISSUE TITLE
MQTT Authentication with ClientId, Username, and Password

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#499]
MQTT configuration parameters do not include clientId, username, and password. When I looked for an open MQTT broker in Europe (because of GDPR issues), I found one, but they do not allow anonymous subscription. You have to register a clientId-username-password tuple with them to connect. Could you enclose those values into the configuration?

**Comment by roe-dl** [comment]
I found an option at the mqtt provider to enable connections with random clientIds, as the Belchertown skin uses. So the issue focusses on username and password, only.

**Comment by roe-dl** [comment]
As there was no need to set a specific clientid any more, the task was much simpler, and I tried. I am by no means an expert to JavaScript, but I looked at the code around. I added some lines as the patch below shows. And I added definitions for "mqtt_websockets_username" and "mqtt_websockets_password". Fortunately it worked.

--- js/belchertown.js.tmpl.orig	2020-12-31 11:04:05.708568554 +0100
+++ js/belchertown.js.tmpl	2020-12-31 12:24:34.827520522 +0100
@@ -1351,6 +1351,10 @@
         useSSL: false,
         #end if
         reconnect: true,
+        #if $Extras.has_key("mqtt_websockets_username") and $Extras.has_key("mqtt_websockets_password")
+        userName:"$Extras.mqtt_websockets_username",
+        password:"$Extras.mqtt_websockets_password",
+        #end if
         onSuccess:onConnect,
         onFailure:onFailure
       }

**Comment by shortword** [comment]
I've submitted #641 (as noted above). I hope everything is in good shape for merge. If not feel free to reach out.

**Comment by shortword** [comment]
@poblabs Thanks for all of the work.
I see the bot marked this issue and the PR as stale, but I don't see anything preventing merge. (No conflicts, comments.) Please let me know if you have concerns with the PR I can help address.

**Comment by roe-dl** [comment]
Shall I send a PR for that?

**Comment by poblabs** [comment]
that would be helpful!
