### ISSUE TITLE
Errors after 0.6 install

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#5]
This error has appeared after the 0.6 upgrade from 0.5, not seen previously
Aug 31 12:00:24 raspberrypi weewx[21736]: Belchertown Extension: version 0.6
Aug 31 12:00:24 raspberrypi weewx[21736]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****  Module 'user.belchertown' has no attribute 'getAllStats' when searching for 'user.belchertown.getAllStats'
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****  Traceback (most recent call last):
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****      obj.start()
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****      self.run()
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 155, in run
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****      self.initExtensions(gen_dict[section_name])
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in initExtensions
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****      class_ = weeutil.weeutil._get_object(x)
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1140, in _get_object
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****      raise AttributeError("Module '%s' has no attribute '%s' when searching for '%s'" % (mod.__name__, part, module_class))
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****  AttributeError: Module 'user.belchertown' has no attribute 'getAllStats' when searching for 'user.belchertown.getAllStats'
Aug 31 12:00:24 raspberrypi weewx[21736]:         ****  Generator terminated

**Comment by 41south** [comment]
Fixed - missed a change in skin.conf as I was keeping my old skin.conf then copying it back over the new skin.conf after upgrade.

Is there a better way to keep all of the specific changes in skin.conf? I know some can go into weewx.conf but can it all go in there?

**Comment by poblabs** [comment]
Did you upgrade skin.conf? It's required

**Comment by 41south** [comment]
Crossed comments :) Happy to close this but still not sure of the best way to preserve customisation in skin.conf during upgrades. Was it just that line in the Cheetah generator that had changed?

**Comment by poblabs** [comment]
The changes I made were in reference to some code functions, and not options, so it was a change that would have had to take place anyways. I'm trying to make the skin a bit more optimized so there may be changes in the future. I'll try to point that out in the release notes.

**Comment by poblabs** [comment]
Fair warning that 0.7 will have changes in skin.conf :) 

I've consolidated almost everything in the `user/bin/belchertown.py` file into 1 class to try and optimize things.
