### ISSUE TITLE
Gust speed misaligned on small screen

### ISSUE THREAD

**Issue by dciarniello** [poblabs/weewx-belchertown#506]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

When the gust speed is 10 or above (km/h in my case but I assume that the issue would be the same for mph), it is misaligned on a small screen.  I discovered the issue on my phone but it can easily be reproduced by shrinking a browser window.  Please see the attached screenshot.

**Link to your website (IMPORTANT)**

**Version of the skin you're using**
Belchertown 1.2

**To Reproduce**

**Expected behavior**

**Screenshots**
![belchertown](https://user-images.githubusercontent.com/25410089/103464769-16e40580-4ceb-11eb-884a-201d8a6b45ac.png)

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by uajqq** [comment]
If you install #502, does that fix the issue?

**Comment by dciarniello** [comment]
Unfortunately, no, it doesn't.

Upon further investigation, it seems to be a Firefox-specific issue as Chrome on both desktop and phone render correctly.

For some reason, Firefox resizes the box from 58x36 to 58x66.  But there's a bit of an inconsistency in what Firefox is doing.  The box model in the inspector claims 58x36 with 0 padding and margins regardless of window size but span.curwindgust is given as 58x36 for a large window and 58x66 for a small window as can be seen on the new screenshots.
![belchertown58x36](https://user-images.githubusercontent.com/25410089/103466508-b0ff7a00-4cfa-11eb-9cbe-7ebb107af0aa.png)

![belchertown58x66](https://user-images.githubusercontent.com/25410089/103466513-b52b9780-4cfa-11eb-8914-94c9ce69316e.png)
