### ISSUE TITLE
Bug with new Beaufort category display if running weewx 4.1.1

### ISSUE THREAD

**Issue by James-76** [poblabs/weewx-belchertown#508]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

in index.html.tmpl

`jQuery(".beaufort").html( beaufort_cat( $current.windSpeed.beaufort.toString(addLabel=False) ) ); `

gives an error if you are running weewx 4.1.1 as I think $current.windSpeed.beaufort only comes along in v4.2 (http://weewx.com/docs/upgrading.htm#From_4.1_or_earlier) 

**Link to your website (IMPORTANT)**
 
https://blisteringbarnacles.co.uk/

**Version of the skin you're using**

Latest pull from today (3rd Jan)

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

In the short term I've worked around it by adding

```
            #if $Extras.has_key("beaufort_category") and $Extras.beaufort_category == '1'
            jQuery(".beaufort").html( beaufort_cat( $current.windSpeed.beaufort.toString(addLabel=False) ) );
            #end if
```

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by James-76** [comment]
Error message is 

Uncaught ReferenceError: $current is not defined
    <anonymous> https://blisteringbarnacles.co.uk/:125
    jQuery 2
        l
        c
blisteringbarnacles.co.uk:125:19

**Comment by uajqq** [comment]
Good point. I opened a pull request that is more backwards-compatible. #509

**Comment by James-76** [comment]
@uajqq, that fix works in the sense it isn't erroring any more.
