### ISSUE TITLE
Rain Value and Unit do not match at Current Value Display

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#510]
**Describe the bug**
I observed that for some time, but now I am sure: At the current values display the rain value is in Centimeter (cm), but the unit label is Millimeter (mm). The graph shows it right. 

It is independent of the device.

**Important note:** When I reload the page on a **slow** device, then first the right value of (actually) 2.0 is displayed, and a second later, when the MQTT connection is up, it changes to 0.2. I suspect the reason as described below in section "additional context"

It applies to the "pi" page, too.

**Link to your website (IMPORTANT)**
[https://www.woellsdorf-wetter.de](https://www.woellsdorf-wetter.de)

**Version of the skin you're using**
1.2

**To Reproduce**
It is enough to open the site on a rainy day. Maybe, it happens with European units, only.

**Expected behavior**
The actual total rain value at the time of the screenshots was 2.0 mm or 0.20 cm. So I expected the displayed value to be 2.0 for the unit of mm.

**Screenshots**
![image](https://user-images.githubusercontent.com/73126506/103484139-cb198500-4dec-11eb-90fa-6f9faa71434f.png)
![image](https://user-images.githubusercontent.com/73126506/103484152-df5d8200-4dec-11eb-83ec-fe024bac3f4b.png)

**Device Information (please complete the following information):**
 - Device: desktop
 - OS: macOS, iOS
 - Browser Safari
 - Version current

**Additional context**
The MQTT json data include the unit within the field name. Weewx offers 2 sets of European units, one is wind in m/s and rain in mm, and the other is wind in km/h and rain in cm. Unfortunately, in Germany the common units are km/h for wind and mm (or liter per square meter, what is the same value) for rain. For that reason I changed the defaults for reports in weewx.conf as shown below:

```
    [[Defaults]]
        [[[Units]]]
            # The following section sets what unit to use for each unit group.
            # NB: The unit is always in the singular. I.e., 'mile_per_hour',
            # NOT 'miles_per_hour'
            [[[[Groups]]]]
                group_altitude = meter    # Options are 'foot' or 'meter'
                group_degree_day = degree_C_day    # Options are 'degree_F_day'
                group_distance = km    # Options are 'mile' or 'km'
                group_pressure = mbar    # Options are 'inHg', 'mmHg', 'mbar', o
                group_rain = mm    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = mm_per_hour    # Options are 'inch_per_hour', '
                group_speed = km_per_hour    # Options are 'mile_per_hour', 'km_
                group_speed2 = km_per_hour2    # Options are 'mile_per_hour2', '
                group_temperature = degree_C    # Options are 'degree_F' or 'deg

```

As the MQTT driver of WeeWX is not part of the reports section, it sends the rain values in Centimeter (cm). So the problem may be that the values are used without considering the potentially different units for archive data set on one hand and MQTT data set on the other.

**HELP WANTED**
Unfortunately I cannot actually provide a patch.

**Comment by uajqq** [comment]
I think changing the units under [[MQTT]] should fix the issue— see here https://github.com/poblabs/weewx-belchertown#frequently-asked-questions

**Comment by James-76** [comment]
FYI My MQTT which displays in mm and mm_per_hour is as follows.    The unit_system is also likely to be set to METRIC which would put it in cm and cm_per_hour

```
    [[MQTT]]
        server_url = mqtt://xxxx:1883/
        topic = weather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        [[[inputs]]]
            [[[[dayRain]]]]
                name = dayRain_mm
                units = mm
            [[[[rainRate]]]]
                name = rainRate_mm_per_hour
                units = mm_per_hour
            [[[[windSpeed]]]]
                units = knot
```

**Comment by roe-dl** [comment]
Sorry for not reading the FAQ carefully.

Yes, with that changes to the MQTT section of weewx.conf the right values are displayed.

Nevertheless: Is observing the units an idea?

**Comment by roe-dl** [comment]
I forgot: Thanks for your help. 

@James-76 When I looked into the MQTT data I saw that there are more than those 2 rain values in the MQTT data. I found 5 of them. 

Additionally I found out: it is not really necessary to specify the name of the field as the new unit label is appended automatically. If I comment the names out the names within the MQTT data are the same.

```
        [[[inputs]]]
            [[[[rainRate]]]]
                #name = rainRate_mm_per_hour
                units = mm_per_hour
            [[[[rain]]]]
                #name = rain_mm
                units = mm
            [[[[hourRain]]]]
                #name = hourRain_mm
                units = mm
            [[[[rain24]]]]
                #name = rain24_mm
                units = mm
            [[[[dayRain]]]]
                #name = dayRain_mm
                units = mm

```

**Comment by James-76** [comment]
@roe-dl, thanks - I've removed the name entries in my configuration and yes everything is still good 👍
