### ISSUE TITLE
THSW Index Value

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#513]
:bulb: **The Idea**
I'd like to see the Davis THSW value able to be shown as apptemp

:hammer: **Breaking Feature**
I can't see this breaking any feature or flow.

**Comment by roe-dl** [comment]
There was a thread about this on Google groups: [Belchertown skin - Feels Like Temperature](https://groups.google.com/g/weewx-user/c/bBPEf6Ei84E)
