### ISSUE TITLE
Dont work Forecast and About dont update

### ISSUE THREAD

**Issue by sunbloquer** [poblabs/weewx-belchertown#515]
First sorry, English is not my first language and github I don't know how to use it very well.

**First step**
I have debugging activated but I don't know what to look at or how to look at it.

**Describe the bug**
I have seen a similar message Forecast not updating. Delete json / forecast.json and regenerate template but problem persists.

I have read all the documentation but I do not see a solution

**Link to your website (IMPORTANT)**
http://meteoquintes.dx.am

**Version of the skin you're using**
https://github.com/poblabs/weewx-belchertown/releases/download/weewx-belchertown-1.2/weewx-belchertown-release-1.2.tar.gz

by wget

`    # Forecast defaults
    forecast_enabled = 1
    forecast_provider = "aeris"
    forecast_api_id = "xxxxxxxx"
    forecast_api_secret = "xxxxxxxxxx"
    forecast_units = "ca"
    forecast_lang = "en"
    forecast_stale = 3540
    forecast_aeris_use_metar = 1
    forecast_alert_enabled = 0
    forecast_alert_limit = 1
    forecast_show_daily_forecast_link = 0
    forecast_daily_forecast_link = ""`

**Device Information (please complete the following information):**
 - Device:  desktop, mobile]
 - OS: Windows, Android
 - Browser e.g. Chrome
 - Version Versión 87.0.4280.88 (Build oficial) (64 bits)

If someone can tell me the steps to see the problem, if it is for permissions, or something

`drwxr-xr-x 2 root root   4096 ene  5 11:08 about
-rw-rw-r-- 1 root root   1549 ene  5 11:04 about.inc
-rw-rw-r-- 1 root root 128503 ene  4 14:57 belchertown-dark.min.css
-rw-rw-r-- 1 root root   5882 ene  4 14:57 celestial.inc
-rw-rw-r-- 1 root root   3638 ene  4 14:57 favicon.ico
-rw-rw-r-- 1 root root    964 ene  4 14:57 footer.html.tmpl
drwxr-xr-x 2 root root   4096 ene  4 14:57 graphs
-rw-rw-r-- 1 root root   9554 ene  4 14:57 graphs.conf.example
-rw-rw-r-- 1 root root  11392 ene  4 14:57 header.html.tmpl
drwxr-xr-x 2 root root   4096 ene  4 14:57 images
-rw-rw-r-- 1 root root  31882 ene  4 14:57 index.html.tmpl
drwxr-xr-x 2 root root   4096 ene  4 14:57 js
drwxr-xr-x 2 root root   4096 ene  4 14:57 json
-rw-rw-r-- 1 root root    813 ene  4 14:57 manifest.json.tmpl
drwxr-xr-x 2 root root   4096 ene  4 14:57 NOAA
-rw-rw-r-- 1 root root   1305 ene  4 14:57 page-header.inc
drwxr-xr-x 2 root root   4096 ene  4 14:57 pi
drwxr-xr-x 2 root root   4096 ene  4 14:57 records
-rw-rw-r-- 1 root root    359 ene  4 14:57 records.inc
-rw-rw-r-- 1 root root   1827 ene  4 14:57 records-table.inc.example
drwxr-xr-x 2 root root   4096 ene  4 14:57 reports
-rw-rw-r-- 1 root root     26 ene  4 14:57 robots.txt
-rw-rw-r-- 1 root root  38438 ene  5 11:35 skin.conf
-rw-r--r-- 1 root root  38050 ene  5 08:42 skin.conf.original
-rw-rw-r-- 1 root root  37688 ene  4 19:06 skin.conf.save
-rw-rw-r-- 1 root root  42857 ene  4 14:57 style.css`

**Comment by sunbloquer** [comment]
In the issue #512 https://github.com/poblabs/weewx-belchertown/issues/512#issue-777723569
in attached bt_conf of master.zip

            forecast_units = us
            **forecast_interval_hours = 24**
            forecast_lang = en

that reference does not appear

**Comment by michaelundwd** [comment]
@sunbloquer 
I know this issue is closed, but having looked at http://meteoquintes.dx.am now it is working, it is only displaying the 24hr interval forecast and no option buttons.  This happens if there is no forecast_interval_hours item in your skin.conf file.   If you want to be able to see the other forecast options, then include the forecast_interval_hours item in the conf file. the value can be set to 0, 1, 3 or 24. The forecast options are explained at the beginning of PR #455.
Michael
