### ISSUE TITLE
Social media buttons not working correctly

### ISSUE THREAD

**Issue by Distortionist** [poblabs/weewx-belchertown#516]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**Describe the bug**
The facebook_enabled = 1 option is not working. I don't see a facebook share link
The twitter_enabled = 1 option is working, but I don't get a graphical button, just a text button.

**Link to your website (IMPORTANT)**
http://livingstonecove.ca/

**Version of the skin you're using**
latest

**Expected behavior**
See blue facebook and twitter icons

**Screenshots**
![image](https://user-images.githubusercontent.com/72505233/103700989-a9023d00-4f7b-11eb-9a77-33ca5fc8d1d0.png)

**Comment by poblabs** [comment]
Everything seems fine to me for Facebook. 

For Twitter, did you finish configuring all the parameters?

![image](https://user-images.githubusercontent.com/3484775/103712915-fb962600-4f88-11eb-9516-a81b55a56eb8.png)

**Comment by Distortionist** [comment]
> Everything seems fine to me for Facebook.
> 
> For Twitter, did you finish configuring all the parameters?
> 
> ![image](https://user-images.githubusercontent.com/3484775/103712915-fb962600-4f88-11eb-9516-a81b55a56eb8.png)

No I did not fill out everything for twitter, but even without twitter, when I use facebook, I get no facebook icon. It is defined in skin.conf not weewx.conf.  If I comment out facebook_enabled, I get an error, so I have to have it as 0 or 1, so I know it is looking it up, but why its not including an icon I have no idea. I don't know why it shows for you. I bet you it is my pi-hole!!

**Comment by Distortionist** [comment]
Ok, it is Chromium Edge that does not display it. Sorry for the trouble I did not think of trying a different browser, but it works in Firefox, and Chrome. Not sure why Edge is blocking it. Firefox blocked it with a notification which let me enable it.

**Comment by Distortionist** [comment]
I closed it but I forgot to mention it doesn't work on cellphones :)
