### ISSUE TITLE
hassio - HiveMQ - MQTT websocket not connecting

### ISSUE THREAD

**Issue by etamtlosz** [poblabs/weewx-belchertown#52]
I'd like to use my hassio MQTT broker - HiveMQ - as a broker, but websocket won't connect.
weewx is publishing the messages to my broker, I can see them, but the skin is not connecting to ws.

broker weather/loop output looks like this:

{"cloudbase_meter": "1687.56046714", "outHumidity": "44.0", "pressure_mbar": "1014.56189238", "rain_cm": "0.0", "barometer_mbar": "1013.54597593", "dewpoint_C": "15.5", "windGust_kph": "16.5762432", "heatindex_C": "28.8888888889", "dayRain_cm": "0.0", "inDewpoint_C": "18.7788336375", "altimeter_mbar": "1014.86342821", "windchill_C": "28.8888888889", "appTemp_C": "28.2705842054", "outTemp_C": "28.8888888889", "humidex_C": "33.1062121375", "rain24_cm": "0.0", "hourRain_cm": "0.0", "inTemp_C": "30.3888888889", "windSpeed_kph": "12.2310144", "usUnits": "16.0", "UV": "10.0", "rainRate_cm_per_hour": "0.0", "dateTime": "1548892132.0", "windDir": "334.0", "inHumidity": "50.0", "radiation_Wpm2": "888.41"}

my config is:
[[MQTT]]
        server_url = mqtt://user:pass@192.168.2.10:1883/
        topic = weather
        unit_system = METRIC
        binding = loop, archive
        aggregation = aggregate
[[[Extras]]]
            mqtt_enabled = 1
            mqtt_host = 192.168.2.10
            mqtt_port = 1884
            mqtt_topic = weather/loop

HiveMQ config:

{
  "log_level": "info",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "ssl": false
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": false
  },
  "mqttusers": [
    {
      "username": "user",
      "password": "pass",
      "readonly": false,
      "topics": [
        "#"
      ]
    }
  ]
}

With all this, in the hassio component log I'm getting the following error, whenever I'm reloading the the website (weewx) in m browser:
1548892271: Socket error on client <unknown>, disconnecting.

**Comment by poblabs** [comment]
If your hassio addon doesn't support websockets, there's not much I can do. Websockets is a requirement.

**Comment by poblabs** [comment]
You can try [setting up your own mosquitto](https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/). 

Is your HiveMQ on hassio or in the cloud? Either way, you'd need the [websockets information ](https://github.com/poblabs/weewx-belchertown#mqtt-for-real-time-streaming-options)and add it to the [skin options](https://github.com/poblabs/weewx-belchertown#belchertown-skin-options).

**Comment by etamtlosz** [comment]
HiveMQ is on hassio, local.
As you can see, the websockets info is in my config, under extras.

**Comment by poblabs** [comment]
I use hassio, but I'm not using HiveMQ. I'm using the official Mosquitto add-on. But for my weather station, I ended up using another system and installing Mosquitto like in the link I added in my last post. 

If you figure out how to get websockets working, then just update skin options and restart weewx and wait for an archive interval.

**Comment by poblabs** [comment]
Sorry, I just saw this. This is wrong. 

```
[[MQTT]]
server_url = mqtt://user:pass@192.168.2.10:1883/
topic = weather
unit_system = METRIC
binding = loop, archive
aggregation = aggregate
[[[Extras]]]
mqtt_enabled = 1
mqtt_host = 192.168.2.10
mqtt_port = 1884
mqtt_topic = weather/loop
```


The extras go under the **skin options**, not the MQTT extension. 

Check out the links I sent you in the last reply.

**Comment by etamtlosz** [comment]
... and I'm still struggling with this.
I switched to MQTT Server & Web client (Community addon) on my hassio, hoping that I'll be able to keep my data locally, and not sending to some cloud server.

My addon settings look like this:
![2019-08-24 21_12_42-Window](https://user-images.githubusercontent.com/7436784/63635247-b84d5700-c6b4-11e9-8505-50d3007b6a51.png)

My weewx.conf looks like this:
```    [[MQTT]]
        server_url = mqtt://mqtt:pass@192.168.2.10:1883/
        topic = ivcweather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
```

while my skin.conf contains this:
```    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "192.168.2.10"
    mqtt_websockets_port = 1884
    mqtt_websockets_ssl = 0
    mqtt_websockets_topic = "ivcweather/loop"
```
What am I doing wrong?
