### ISSUE TITLE
Error aqi_color in belchertown.js

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#529]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

The sequence of aqi_color is not correct in belchertown.js
The right sequence is:

// Change the color of the aqi variable according to US-EPA standards
// (adjusted to match skin colors better)
function get_aqi_color( aqi, returnColor=false ) {
    if ( aqi >= 301 ) {
        var aqi_color = "#cc241d";
    } else if ( aqi >= 201 ) {
        var aqi_color = "#b16286";
    } else if ( aqi >= 151 ) {
        var aqi_color = "rgba(255,69,69,1)";
    } else if ( aqi >= 101 ) {
        var aqi_color = "rgba(255,127,0,1)";
    } else if ( aqi >= 51 ) {
        var aqi_color = "rgba(255,174,0,0.9)";
    } else if ( aqi < 51 ) {
        var aqi_color = "#71bc3c";
    }

(Sorry, but I don't know how to create a pull request)

**Link to your website (IMPORTANT)**

**Version of the skin you're using**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by uajqq** [comment]
Is the code throwing an error on your system or resulting in unexpected behavior? It's been working okay for me.

**Comment by uajqq** [comment]
I see the issue--I used to have those as separate "if" statements so it would proceed sequentially no matter what, but I accidentally changed them to "else if." Reversing the order is more elegant as you've pointed out. I've opened a pull request--thank you!
