### ISSUE TITLE
Eclipse Mosquitto 2.05

### ISSUE THREAD

**Issue by jomimota** [poblabs/weewx-belchertown#532]
Hi,

Since my Ubuntu server upgraded the Eclipse Mosquitto server to version 2.05, two or three days ago, that I can't connect (via ssl websocket) from the browser to my weewx website with version 1.2 of the skin.
Is the mqtt javascript client of skin compatible with this version of Eclipse Mosquitto?
Weewx continues to send messages without any problem.

Thanks in Advance.

Regards,

Jorge Mota

**Comment by gdt** [comment]
1) See the mqtt release notes.  I remember that it changed defaults to be localhost only until configured.

2) You didn't say that you had used OS commands to check what address the MQTT broker was listening on, or if you were able to manually connect to the port from a machine running the browser.

**Comment by jomimota** [comment]
Hi,

In the Eclipse Mosquitto server log I can see that a call is made in the port 9001 (wserver.jorgemota.pt) but the client don't connect as you can see in https://meteo.jorgemota.pt

Thanks.

**Comment by jomimota** [comment]
Hi,

With today upgrade of Eclipse Mosquitto Server the problem is solved.

Thank you.
