### ISSUE TITLE
Mosquitto problem. cant reach site on my local computers. Can only reach on my mobilephone?

### ISSUE THREAD

**Issue by RebeckaJohansson** [poblabs/weewx-belchertown#534]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

_**Answer: I cant even debug on my computers**_

**Describe the bug**

I have follow the descriptions för build my own broker. Everything is fine and also certbot and ssl without any problems.
My problem is i cant reach my site on my PC or my two Raspberry Pi 4 at all and only got ERR_CONNECTION_TIMED_OUT!

The strange is i on my mobilephone my site works perfect and connecting live without ant problems even with wifi on or off.

My ports are also open and i have also open DMZ for my IP but i still dont work to open my site on my computers!

My MQTT settings is those

Weewx.conf
 [[MQTT]]
        server_url = mqtt://Myweather:xxxxxxxx@localhost:1883/
        topic = weather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate

Belchertown skin.conf
MQTT Websockets defaults
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "myweatherserver.ddns.net"
    mqtt_websockets_port = 9001
    mqtt_websockets_ssl = 1
    mqtt_websockets_topic = "weather/loop"
    disconnect_live_website_visitor = 0

**Link to your website (IMPORTANT)**
http://myweatherserver.ddns.net

**Version of the skin you're using**
Belchertown Skin v1.2

**Screenshots**
![2021-01-18-075802_1682x992_scrot](https://user-images.githubusercontent.com/69727586/104883824-9fa6a680-5965-11eb-853e-1261ff46816c.png)

**Device Information (please complete the following information):**
 - Device: [Raspberry PI 4, 4GB ram with POE-hat attached] 
 - OS: [Rasbian]
 - Browser [Chromium] (Chrome on my other PC and mobile)
 - Version [Latest Rasbian via Raspberrypi homesite]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ArendPWS** [comment]
[[MQTT]]
server_url = mqtt://Myweather:xxxxxxxx@**localhost**:1883/

Maybe this works: try to replace localhost in the server_url setting with the ip address of the MQTT server.

**Comment by RebeckaJohansson** [comment]
> [[MQTT]]
> server_url = mqtt://Myweather:xxxxxxxx@**localhost**:1883/
> 
> Maybe this works: try to replace localhost in the server_url setting with the ip address of the MQTT server.

I tryed to write the local ip adress but still got the error connection. Its still only works on my mobile Phone. Very strange.

My mobile is on same wifi and it works but not on my computers that are in same wifi or cabel to same router. 
All ports are open to 80,443,8883 and 9001 and i try port open 1883 to.
Dont know what problem it could be.

**Comment by ArendPWS** [comment]
Just to make sure that you didn't use 127.0.0.1 (localhost) as ip address, here is what my MQTT config (partly) looks like:

    [[MQTT]]
        server_url = mqtt://xxxx:xxxx@192.168.178.9:1883/
        topic = weather
        unit_system = METRICWX
        binding = archive, loop
        aggregation = aggregate

As you can see i use the local (fixed) ip address of the device on which my MQTT broker is running.

Don't know if this is of any help.

**Comment by gary-hammer** [comment]
I haven't a suggestion, though I do have an observation.
Using Chrome or Edge works well on my site from any device (Windows, Linux, Android).
Using Firefox results in Failed connecting to the weather station from any device (Windows, Linux, Android).

I have looked at this periodically for over a year with no success.
Perhaps a different browser will result in a different outcome for you as well.

**Comment by RebeckaJohansson** [comment]
Still no success :(
i dont use the 127.0.0.1 adress 

I have tryed ip adress i have via my Eth0 that has ip 192.168.0.25 and also my Wlan0 adress 192.168.0.102
But i gott error message like this if i try them.




Raspi weewx[1865] DEBUG user.mqtt: Failed upload attempt 3: [Errno 111] Connection refused
Raspi weewx[1865] DEBUG user.mqtt: Failed upload attempt 3: [Errno 111] Connection refused
Raspi weewx[1865] DEBUG user.mqtt: Failed upload attempt 3: [Errno 111] Connection refused
Raspi weewx[1865] ERROR weewx.restx: MQTT: Failed to publish record 2021-01-19 08:22:05 CET (1611040925): Failed upload after 3 tries


All ports are open. My IP is also open on DMZ but it still only works on my mobile

**Comment by ArendPWS** [comment]
> I haven't a suggestion, though I do have an observation.
> Using Chrome or Edge works well on my site from any device (Windows, Linux, Android).
> Using Firefox results in Failed connecting to the weather station from any device (Windows, Linux, Android).
> 
> I have looked at this periodically for over a year with no success.
> Perhaps a different browser will result in a different outcome for you as well.

@gary-hammer

That's a weird issue, my site is working just fine using any browser/ OS combination (including Firefox).

**Comment by ArendPWS** [comment]
@RebeckaJohansson

What version of mosquitto are you using? I just noticed there is an open issue related to the latest release.

Issue #532

**Comment by RebeckaJohansson** [comment]
> @RebeckaJohansson
> 
> What version of mosquitto are you using? I just noticed there is an open issue related to the latest release.
> 
> Issue #532

I tryed to reinstall my whole raspberry pi 4 and followed all step by step again but still gott connection error on my computers. 

The version is MQTT v3.1/v3.1.1 Broker

Logs and everything give no errors and my ports are open. 
So must be a mqtt bug

**Comment by gary-hammer** [comment]
I'm running the same version and I have only my Firefox problem.
So, I'm going to attach my config files for your comparison.
[MQTTInfo.zip](https://github.com/poblabs/weewx-belchertown/files/5836511/MQTTInfo.zip)

**Comment by gary-hammer** [comment]
> > I haven't a suggestion, though I do have an observation.
> > Using Chrome or Edge works well on my site from any device (Windows, Linux, Android).
> > Using Firefox results in Failed connecting to the weather station from any device (Windows, Linux, Android).
> > I have looked at this periodically for over a year with no success.
> > Perhaps a different browser will result in a different outcome for you as well.
> 
> @gary-hammer
> 
> That's a weird issue, my site is working just fine using any browser/ OS combination (including Firefox).
Give it a try with your Firefox, maybe FF doesn't like hairpin NAT.

https://weather.ghammer.net

**Comment by ArendPWS** [comment]
> > @RebeckaJohansson
> > What version of mosquitto are you using? I just noticed there is an open issue related to the latest release.
> > Issue #532
> 
> I tryed to reinstall my whole raspberry pi 4 and followed all step by step again but still gott connection error on my computers.
> 
> The version is MQTT v3.1/v3.1.1 Broker
> 
> Logs and everything give no errors and my ports are open.
> So must be a mqtt bug

I am out of ideas now, maybe you want to share your issue on the WeeWX forum. Perhaps more people are having the same MQTT issues.

**Comment by ArendPWS** [comment]
> > > I haven't a suggestion, though I do have an observation.
> > > Using Chrome or Edge works well on my site from any device (Windows, Linux, Android).
> > > Using Firefox results in Failed connecting to the weather station from any device (Windows, Linux, Android).
> > > I have looked at this periodically for over a year with no success.
> > > Perhaps a different browser will result in a different outcome for you as well.
> > 
> > 
> > @gary-hammer
> > That's a weird issue, my site is working just fine using any browser/ OS combination (including Firefox).
> > Give it a try with your Firefox, maybe FF doesn't like hairpin NAT.
> 
> https://weather.ghammer.net

You are right, only Firefox gives a fail when connecting to your site. It must be related to your setup.

**Comment by ArendPWS** [comment]
@RebeckaJohansson

I noticed that I am now able to connect to your broker, but it only sends a message on archive interval.

**Comment by RebeckaJohansson** [comment]
> @RebeckaJohansson
> 
> I noticed that I am now able to connect to your broker, but it only sends a message on archive interval.



Strange.. I checked my log yesterday before i fall asleep and its publish to my mqtt and no weewx dont get me any errors and update my website too. 
I only have the problem that i cant reach my site on computer. But i can reach it on my mobile both public and local. 
Only i have noticed its that my Belchertown skin website stuck on connected and take time to connect. 

I dont know how to figuring out why you only see archive interval? 

I will take a look one more time on my configs. 
I can then show my setup here.

**Comment by flygpagen** [comment]
The only way I got mqtt to work was to use a qualified address instead of localhost or an IP. Both as server_url and websockets host. Worth a try.

**Comment by RebeckaJohansson** [comment]
I fixed it. I think the problem was that i have an switch between my main router and computer. So i had to connect to the wirless internet to so i have both direct internet and wirless internet on and it works now without problem so far 👍
