### ISSUE TITLE
Use LOOP1 and LOOP2 Data

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#537]
:bulb: **The Idea**
Davis logger can output LOOP1, LOOP2 or both.
LOOP2 has the better barometer/pressure values.
As the different LOOPs provide different values, it would be nice to be able to use both.
WeeWX has the ability to request and use both (loop_request = 3)
However, if you select that value, though the LOOP1 values are being retrieved, the battery status is not used in the skin.
Transmitter battery is shown as LOW and Console battery is shown as 0 V

Do you know why this would be so? Could be a WeeWX thing where it does not write the current$ values using only the available data, like for battery, but uses whatever is in any LOOP packet.

Attached is a chart of the different LOOP and data they provide.

:hammer: **Breaking Feature**
No known feature would break.

![Davis LOOP1 vs LOOP2](https://user-images.githubusercontent.com/12861605/104960745-d7800f00-59a2-11eb-8e06-c119a50c5780.jpg)

**Comment by poblabs** [comment]
The skin doesn't necessarily get the data from your console that's weewx's
job. So you would need to have the mqtt extension send that data to your
mqtt broker and then you can extend the skin to show those extra variables
that you want to show...

**Comment by gary-hammer** [comment]
I was not clear. I'm not talking about adding data or extending anything.
I am using both loops from the Vantage driver by setting loop_request = 3. Mainly for the accurate altimeter/barometer values from LOOP 2 while keeping the battery info from LOOP 1.

However, I did not clear cache in my browser after changing from LOOP 2 alone to using both LOOPs. LOOP 2 does not have the battery info of course and so, my about page had no info.

Refreshing the browser after setting loop_request = 3 does use the LOOP 2 values while showing the battery info.
To use both you need to set the LOOP 2 values you want as hardware in [StdWXCalculate] else you will get alternating values as the LOOPs do not have the same data for pressure, altimeter, and barometer.
