### ISSUE TITLE
Rcreating hook include files causes increasing memory usage

### ISSUE THREAD

**Issue by GarryALockyer** [poblabs/weewx-belchertown#539]
**First step**

I've done extensive troubleshooting including redesigning my extension from an extension dependent upon Belchertown to a skin independent service.  The only thing that stopped the memory usage increase was adding the 'raw' argument to the Cheetah 'include' directives in 'index.html.tmpl'.

**Describe the bug**

If the Belchertown "hook" include files are regenerated (such as during each WeeWX archive cycle) WeeWX memory usage increases with each archive cycle.

The problem is discussed at length in the WeeWX User Google group conversation "ERROR weewx.cheetahgenerator: **** MemoryError."  A WeeWX service extension to demonstrate the problem is included in a reply on Jan 17 at 12:04 PM.

**Link to your website (IMPORTANT)**

Station website: https://Lockyer.ca/OsoyooLakeNoethEast

Mem graphs: https://Lockyer.ca/OsoyoosLakeNorthEast/mem

**Version of the skin you're using**

1.2

**To Reproduce**
1. Install the WXFeedsMemoryTest extension.
2. Restart WeeWX.
3. Monitor WeeWX memory usage using an OS resource monitor and/or mem extension graphs.
4. Notice that WeeWX memory usage grows with each archive cycle.
5. Insert 'raw' argument in 'include' directives for the Belchertown include files in 'index.html.tmpl'.
6. Restart WeeWX.
7. Notice WeeWX memory usage stabilizes and does not continue to grow.

**Expected behavior**

WeeWX memory usage stabilizes - does not grow over time.

**Screenshots**

Not applicable.

**Device Information:

 - Deviced: Raspberry Pi 4 and Zero W
 - OSd: Raspberry Pi OS (latest) and Ubuntu Desktop 20.10 on R Pi 4, Raspberry Pi OS Lite (latest) on R Pi Zero W 
 - Browserd: Various - I mostly use Chrome/Chromium but all browsers behave the same.
 - Version: Of What? :^))

**Additional context**

The problem shows up when an include file is recreated.  If the include file is 'static' the problem does not exhibit.'

Bigger include files cause the problem to be more evident.  The original problem showed up after 3+ days of starting WeeWX.  Using larger include file can demonstrate the problem with a few minutes.

The problem can be avoided by inserting the 'raw' argument in Cheetah 'include' directives in 'index.html.tmpl'.  *MY* code does not need parsed include files but I'd prefer not to have to edit 'index.html. A setting to enable/disable "raw mode" would be acceptable but I think that ignores the root problem.

I believe the root problem is in the Cheetah generator.  In my opinion, it should not cause ever-increasing memory usage.  I suspect that the code section in Cheetah that parses an include file has a memory leak. 

**HELP WANTED**

I'll do a pull request if necessary but as my "fix" is "not optimal," I'll decline at this time.

**Comment by poblabs** [comment]
What are you placing in the hook file? The hook files are totally up to you and your content - perhaps you're trying to accomplish too much within the archive time span causing weewx to time out?

**Comment by GarryALockyer** [comment]
Thanks for your reply.

My service extension reads RSS feeds and generates standard HTML.  I don’t include any search list variables or items that Cheetah has to resolve.  I’ve validated all the HTML I generate using the W3C validator.

I don’t get any errors from WeeWX at all, even when I max out the number and content of feeds to aggravate the problem.  WeeWX doesn’t seem to care if my extension runs for less than 1 second or more than 30.  Much of the time my extension takes to generate inclkude files is time waiting to receive a feed, not the actual generation of HTML itself.

Again, no errors other than excessive and growing memory usage and that goes away if I insert ‘raw’ in the ‘#include’ directives.

Regards,

Garry Lockyer
C: +1.250.689.0686
H: +1.250.495.5343
E: Garry@Lockyer.ca

**Comment by vinceskahan** [comment]
Pat - the weewx-users discussion resulted in more data.  First, it's not Belchertown - I did a minimal standalone index.html that #include(d) the file from Garry's script and duplicated the problem with Belchertown not even present on the system.

Second, another weewx user came up with a slick workaround that mitigates the issue - see https://groups.google.com/g/weewx-user/c/mZ_uDL7cX1k for details

You can probably close this one as not your problem.

**Comment by poblabs** [comment]
> You can probably close this one as not your problem.

@vinceskahan I love it when it's not my problem!
