### ISSUE TITLE
Add the information for the percentage of cloud sight

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#545]
In my opinion, it would be interesting to insert the percentage of cloud cover as a recoverable variable from the Areis weather.
 On the site you can see https://wx.aerisweather.com/local/it/rome.
Can it be entered as the AQI and beaufort information was entered?
> ![Cattura](https://user-images.githubusercontent.com/72796407/105637424-cc7b2200-5e6d-11eb-9e1e-9fc8c25be67b.PNG)

For example, you could enter the cloud information below the min and max temperature
![Cattura](https://user-images.githubusercontent.com/72796407/105637753-537cca00-5e6f-11eb-8c12-93843e5c76b8.PNG)

_Originally posted by @fvirgola80 in https://github.com/poblabs/weewx-belchertown/issues/540#issuecomment-766395993_

**Comment by uajqq** [comment]
See #546

**Comment by fvirgola80** [comment]
Inserted the belchertown.py in the master.
Tested and worked with python 2
