### ISSUE TITLE
No recent earthquake data available!

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#547]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

from this afternoon the information on earthquakes is not available. debugging on site is active, but I don't understand what happened

**Link to your website (IMPORTANT)**
www.meteocivitavecchia.it

**Version of the skin you're using**
1.2

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2021-01-25-21-50-22-232_com.android.chrome.jpg](https://user-images.githubusercontent.com/72796407/105764559-6965ba00-5f57-11eb-8a48-f9622a9034e9.jpg)

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
Your forecast.json file is missing or unreadable within your HTML_ROOT/json folder. What error is in syslog or wee_reports?

**Comment by fvirgola80** [comment]
> Your earthquake.json file is missing or unreadable within your HTML_ROOT/json folder. What error is in syslog or wee_reports?
> 
> _EDIT_: I meant earthquake.json file

Hello Pat, I am attaching syslog, belchertown.py and skin.conf, I have not received errors in the wee_report

[syslog.zip](https://github.com/poblabs/weewx-belchertown/files/5871483/syslog.zip)
[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/5871484/belchertown.zip)
[skin.zip](https://github.com/poblabs/weewx-belchertown/files/5871485/skin.zip)

**Comment by uajqq** [comment]
Looks like this is yet another encoding error. I force-pushed an update to the unicode fix pull request. Hopefully that should fix the problem--though I still don't understand why it's happening in the first place, since the .encode() method is supposed to take care of this automatically.

**Comment by fvirgola80** [comment]
> Looks like this is yet another encoding error. I force-pushed an update to the unicode fix pull request. Hopefully that should fix the problem--though I still don't understand why it's happening in the first place, since the .encode() method is supposed to take care of this automatically.
Do I try to put this on? 3985de4

**Comment by uajqq** [comment]
Yes

**Comment by poblabs** [comment]
I have merged into master. Install from master and then restart weewx

**Comment by fvirgola80** [comment]
Good news guys, I entered the last belchertown.py published in the master and the wee_report did not give an error, I visualize the cloudiness correctly
www.meteocivitavecchia.it, but I note that the information on earthquakes is not there, it is possible that no dinners are the json file was created but it is 0 bytes

**Comment by uajqq** [comment]
Delete the earthquake.json file and try again. It's regenerated on a schedule so it won't be refreshed for a while.

**Comment by fvirgola80** [comment]
> Delete the earthquake.json file and try again. It's regenerated on a schedule so it won't be refreshed for a while.

Ok deleted
thanks a lot
if you see on the website www.meteocivitavecchia.it the AQI information gives it not available, it is not a problem with the belchertown but I opened a ticket from Aeris and they actually found problems with their servers that they will fix
thanks

**Comment by fvirgola80** [comment]
ok deleting the json file of the terremott now works again .. thank you very much close the post, 😉
