### ISSUE TITLE
can't bring up Belchertown: local variable 'cloud_cover' referenced before assignment 

### ISSUE THREAD

**Issue by jovo0911** [poblabs/weewx-belchertown#548]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
Skin didn't start up in a fresh installation 

**Link to your website (IMPORTANT)**
will not start up

**Version of the skin you're using**
master.zip 27 jan.
weewx 4.3.0 python3

**To Reproduce**

Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****  local variable 'cloud_cover' referenced before assignment
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      obj.start()
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      self.run()
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 149, in run
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 308, in generate
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      default_binding)
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 379, in _getSearchList
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2124, in get_extension_list
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****      "cloud_cover": cloud_cover,
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'cloud_cover' referenced before assignment
Jan 27 16:40:16 wetterpi weewx[14507] ERROR weewx.reportengine:         ****  Generator terminated
Jan 27 16:40:16 wetterpi weewx[14507] INFO weewx.reportengine: Copied 2 files to /var/www/weewx/

**Expected behavior**

makes no different if "aeris" is enable or disable

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by uajqq** [comment]
Can you delete forecast.json and earthquake.json and try to run wee_reports again?

**Comment by jovo0911** [comment]
Didn't have forecast and/or earthquake! 
is the "first" start after installation. I'll attach a 15 min logfile.
skin.conf is original means without any configuration 
weewx running in "simulator mode". I installed "Interceptor, Belchertown, MQTT, Wcloud"
change in weewx config is only for skin Belchertown.
[weewx.txt](https://github.com/poblabs/weewx-belchertown/files/5888430/weewx.txt)

**Comment by uajqq** [comment]
See if the new pull request that just got merged fixes the problem.

**Comment by jovo0911** [comment]
looks good - weewx is coming up without error message. 

thx for your help. I'll close the issue

**Comment by jovo0911** [comment]
solved by pull request #552 from uajqq/cloud_cover
