### ISSUE TITLE
Translating Aeris Weather Forecast Text to German

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#553]
I am not sure whether that topic is better marked as "bug" or "enhancement".

**Describe the bug**
The texts for the weather forecast are defined in skin.conf by lots of variables, that fall in 3 different sets, called "coverage", "intensity", and "weather". To build the forecast text, one text from each of the 3 sets are put together. That ist no problem in English, as the words do not change with usage. In german language adjectives change depending on the following noun. 

Example:
light rain = leichter Regen (with 'r' at the end)
light snow showers = leichte Schneeschauer (without 'r')
heavy thunderstorm = schweres Gewitter (with 's' at the end)

**Link to your website (IMPORTANT)**
I do not like to show that effect to the visitors of the website. So I test it with a second installation, that is not seen in the internet.

**Version of the skin you're using**
1.2

**To Reproduce**
Not difficult. See the documentation.

**Expected behavior**
I would like to have added the right character at the end of the adjectives depending on the gender of the following noun.

**Device Information (please complete the following information):**
 - Device: not depending on device
 - OS: not depending on OS
 - Browser not depending on browser
 - Version 1.2

**Additional context**
As Mark Twain correctly stated, every noun in german language has got a gender. No mark at the noun reveals that gender. You simply need to know. Depending on the gender the adjective before the noun is changed. There are characters added, and sometimes the central vowel changes, too.
And as that is not enough, the german equivalent to English "of", "von" ist considered bad language usage and has to be replaced by additional characters at the end of the noun. That applies to the "coverage" set of weather conditions.
And I can think of some other languages that have the same characteristics.

**Comment by poblabs** [comment]
The translation method is taken from Aeris' own website. 

https://www.aerisweather.com/support/docs/api/reference/weather-codes/

**Comment by roe-dl** [comment]
Yes, I understand this, but just concatenating the strings does not work for german language. That's my problem. It is similar to the problem you have between "foot" and "feet" in English, depending on the value.

**Comment by poblabs** [comment]
I'm not sure of another way around it as I am using their documentation for the internationalization. 

You're free to change the variables around, and modify the code as it suits you. 

You could even leave some variables empty and they won't show - so you could try to translate in the core translation variable. 

I'm not sure - sorry. Perhaps someone else has an idea

**Comment by jovo0911** [comment]
A very simple way ..... it's only the translation, no break the code
![weewx-4](https://user-images.githubusercontent.com/16666482/106316943-d639c680-626d-11eb-87b5-7976dc670fd0.png)

**Comment by areax99** [comment]
It is the same problem with the Italian language as well...

**Comment by roe-dl** [comment]
Within the [bootstrap skin](https://github.com/brewster76/fuzzy-archer/) they have a separate "language" directory, that includes a separate .conf file for each language. It is included by some key in skin.conf or weewx.conf. Would that be an idea for Belchertown skin, too?

**Comment by poblabs** [comment]
@roe-dl How would that work with Belchertown and AerisWeather? The weather codes from AerisWeather would still be the same...?

**Comment by roe-dl** [comment]
@poblabs Oh, may be, I mixed something up. But let me explain.

I saw that the bootstrap skin maintains some separate directory called "languages", that contains separate configuration files for each language. And it is *not* under that skin's directory but direct in the "skins" directory. So I thought that may be something more general that perhaps works for different skins. That was the first thought, when I saw that directory, and it was the reason, why I mentioned it above.

And indeed I would think separate language files could help to make localization easier. Especially, if I want to have two versions of the skin in parallel, one in English and one in local language.

So, regarding the Aeris codes. 

You see that in your language you have "meter" and "meters" or "foot" and "feet", and you need to reflect those differences in the configuration and the code. In german language, for example, units are always singular (except time units :-) ). 

The solution in this case is to have a list of the two words and to select them according to context.

We could think about a list value for those attributes (intensity codes), too. For the codes that are nouns we need to specify the index for the attributes to use. We could do so by appending a number, separated by a comma. So there would be a list, too.

What happens, when the index is missing: We could simply use the first attribute in the list, and so the behavior is as before. Existing configurations would work.

Some languages like french there is an additional issue: the position of the attribute. In English as well as in german the attribute comes before the noun. In french it is different. It depends of the length of the attribute word. Sometimes before, sometimes after the noun. That adds a step of complexity, but it could be specified within the line that defines the attribute name(s).

example how it could look like:
```
        forecast_intensity_code_VL      = "etwas" 
        forecast_intensity_code_L       = "leichte","leichter","leichtes"
        forecast_intensity_code_H       = "starke","starker","starkes"
        forecast_intensity_code_VH      = "schwere","schwerer","schweres"

        forecast_weather_code_A         = "Hagel",1
        forecast_weather_code_T         = "Gewitter",2
        forecast_weather_code_RW     = "Regenschauer",0
```
In german the word for code VL does not change, so only one is mentioned. For the weather codes, the index is appended. For code 'A' the second word in the list is to be used. For code T the third. For code RW the first. In which case '0' could be omitted. Method `get` could be used to get the intensity word with the first element as default value.

Does that sound reasonable?

**Comment by roe-dl** [comment]
I thought about localization again. And I would like to present a suggestion how to deal with that.

The problems I address:
- Localization involves changing lots of entries in skin.conf or weewx.conf.
- It is not possible to provide multiple localizations with the skin package.
- It is difficult to add pages to the Belchertown skin.

The solution:
- A `$locale` tag provides labels in localized versions.
- If no localized version of a label is available, the label text from skin.conf is used automatically.
- `$locale(tmpl=$page).nav` and `$locale(tmpl=$page).page_header` can replace those endless `#if` - `#else` constructs to get menu and page title. Add pages does not involve changing page_header.inc and header.html.tmpl any more. The extension puts `$page` and `nav` or `page_header` together and looks up the real tags `$nav_pagename` and `$pagename_page_header`
- Localized texts are saved to files like `lang/en.conf`, `lang/de.conf` etc. In weewx.conf in the section of the skin a new entry `lang_file` references the localization file to use. To change localization simply change that one entry instead of changing all the labels item by item.
- The localization file provides a special set of labels for each template. Using tags like `$locale(tmpl=$page).html_description` allows to have different description for each page without the need for `#if` - `#else`.
- With tags like `$locale(tag=$xxx)` it is possible to reference a tag that is set by some `#set` instruction.

This is done by a small SearchList extension. 

Because I do not know if you find that interesting, I put it into a separate file and did not include it in belchertown.py and I do not send a PR but attach the file here for discussion.

[skin_locale.py.txt](https://github.com/poblabs/weewx-belchertown/files/6216283/skin_locale.py.txt)

What do you think?
