### ISSUE TITLE
fails to load / generate reports if database has no entry i.e. new db

### ISSUE THREAD

**Issue by gwaitsi** [poblabs/weewx-belchertown#554]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

1) load sample data via the simulator. confirm skin is loaded and viewing sample data

2) delete the sdb and use wee_database --create then try to run wee_reports

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

If there is no sensor data (specifically Outside Temperature) wee_reports fails to generate

**Describe the bug**

**Link to your website (IMPORTANT)**
1.2

**Version of the skin you're using**

**To Reproduce**
1. Go to '...' delete .sdb 
2. Click on '....' run wee_database --create
3. Scroll down to '....' run wee_reports
_sudo wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 149, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 307, in generate
    searchList = self._getSearchList(encoding, timespan,
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 379, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 431, in get_extension_list
    at_outTemp_max_range_max_tuple = (at_outTemp_max_range_query[3], outTemp_unit, 'group_temperature')
TypeError: 'NoneType' object is not subscriptable_

**Expected behavior**

I would expect the report to still generate only with zero values

**Screenshots**

both Ubuntu and FreeBSD 

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
This is known behavior because you need data in your database in order to
generate a report...
