### ISSUE TITLE
General question: Is it necessary to use a belchertown-dark.css minified version?

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#555]
:bulb: **The Idea**

At the moment only the belchertown-dark.css is minified. I have some fixes/additions to share that need modifications of this file. In its minified form it is hard to read and makes the required changes harder to implement.

I wonder if it will have a large impact on performance to use a standard (non minified) version of the belchertown-dark css.

It would be still interesting to use minified versions (JS, CSS) when there were seperate development and release branches (minify all relevant JS and CSS when releasing a new master) but that is not the case anymore.

My question: is it ok to turn the current minified belchertown-dark into a standard version.

**Comment by poblabs** [comment]
It's a very large file so it's minified to be easier on mobile devices.
what you can do is add your changes to the end of the file where you can
see my changes for overrides. Or if your changes are just specific for you
you can use the custom.css file

**Comment by ArendPWS** [comment]
Thank you Pat. Making use of the three distinguished sections is something I didn't think of, but now I know how to keep things minified. As a reminder to myself:

1. Copy the section that needs to be modified.
2. Unminify
3. Modify
4. Minify
5. Replace the original CSS section with the modified code.

**Comment by poblabs** [comment]
what I've been doing is just unminifying the separate bottom section and
leaving the top section alone since that's the bulk of the dark mode.
Modify then re minify

**Comment by ArendPWS** [comment]
Thanks for your advice, I will apply this and post the relevant PRs at some point.

Have a nice weekend!
