### ISSUE TITLE
Master Update & Python Version Compatibility (follows#542 and #540)

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#565]
@uajqq 
I have raised this as a new issue, but it follows #542 that has been merged.

I have upgraded to weewx 4.4.0 with python2 and used the latest belchertown master.  I consistently get an error at line 2688 in belchertown.py see below:

I have checked belchertown.py against my previous working version, and the python 2/3 hack has been removed and not replaced by a sys.version_info() check on python version and subsequently fails with a UnicodeDedcode error.

I have re-inserted the original python 2/3 hack into the new version and the error disappears.  This is the same error that @fvirgola80 had in #540 .  

BTW Can anyone can help me upgrade python 2 to python 3 on my Pi?

Michael

Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****  'ascii' codec can't decode byte 0xc2 in position 13: ordinal not in range(128)
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****      obj.start()
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****      self.run()
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2668, in run
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****      yAxisLabel_config + " (" + unit_label.strip() + ")"
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13: ordinal not in range(128)
Feb  4 15:35:58 garagepi weewx[7060] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by fvirgola80** [comment]
Hi guys, I also upgraded to weewx 4.4.0 using python2 and got this message

 sudo ./wee_reports
Using the configuration file /home/weewx/weewx.conf
Generate forever
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 196, running
    obj.start ()
  File "/home/weewx/bin/weewx/reportengine.py", line 281, at the beginning
    self.run ()
  File "/home/weewx/bin/user/belchertown.py", line 2650, running
    yAxis_label = name + "(" + unit_label.strip () + ")"
UnicodeDecodeError: the "ascii" codec cannot decode byte 0xc3 in position 7: ordinal out of range (128)

belchetown.py is the last of the master.
I attach the syslog and the belchertown.py
[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/5931535/belchertown.zip)
[syslog.zip](https://github.com/poblabs/weewx-belchertown/files/5931538/syslog.zip)

**Comment by norecords** [comment]
@michaelundwd You should upgrade your distro, python 3 is the default version on latest OS

**Comment by michaelundwd** [comment]
@norecords 
Thanks for the link.  I would be moving from stretch to buster that they recommend is a clean install and not an update.  I was hoping for an update in stretch as I didn't really want to re-install my system from scratch.  I'm still struggling with Linux commands!  I can see how to upgrade python, but how do I get weewx to recognise it after I have set 3.8 as the default?
Michael

**Comment by norecords** [comment]
@michaelundwd I had no problems to upgrade from stretch to buster.. Anyway, if you have set Python 3 with update-alternatives you have nothing else to do

**Comment by michaelundwd** [comment]
@norecords 
OK thanks.  I will give it a try.
