### ISSUE TITLE
comma in credits option

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#567]
**Describe the bug**
If I use an option like that
`credits = "Datenbasis: Sächsisches Landesamt für Umwelt, Landwirtschaft und Geologie (LfULG)"`
in graphs.conf, then the string is displayed up to the comma, only. 

It is not the length of string. If the comma is removed, the complete string is displayed.

**Link to your website (IMPORTANT)**
[example (with comma removed)](https://www.woellsdorf-wetter.de/graphs/?graph=Hochwasser)

**Version of the skin you're using**
1.2

**To Reproduce**
1. insert the option shown above in graphs.conf
2. wait for the next archive interval
3. click reload button
4. look at the right bottom corner of the diagram

**Expected behavior**

**Device Information (please complete the following information):**
 - Device: desktop
 - OS: Linux
 - Browser Safari
 - Version WeeWX 4.4.0, Belchertown skin 1.2

**Additional context**
None

**HELP WANTED**
Oh, I am no expert.

**Comment by uajqq** [comment]
Try adding a backslash before the comma, like this:

`credits = "Datenbasis: Sächsisches Landesamt für Umwelt\, Landwirtschaft und Geologie (LfULG)"`

**Comment by norecords** [comment]
characters between double quotes will be rendered, so you have to use simple quotes like this:
`credits = 'Datenbasis: Sächsisches Landesamt für Umwelt\, Landwirtschaft und Geologie (LfULG)'`

**Comment by roe-dl** [comment]
I tried that one, and it worked. Thank you for sorting this out for me.

Sometimes it is not easy to find out, where the rules of Python, Java, or HTML apply.
