### ISSUE TITLE
Forecast does not display, javascript error found when using debug console

### ISSUE THREAD

**Issue by dkozinn** [poblabs/weewx-belchertown#570]
**First step**

I'm running a newer version of belchertown.py, but reverted to the current released version and see the same issue. I have validated that my Aeris ID & key are valid, and my station is showing as reporting to pwsweather.com and has the ability to use the API. This had been working previously, but at some point it stopped.

**Describe the bug**
The weather forecast does not display underneath "7 Day Forecast" on the home page. You can see this on my website.

**Link to your website (IMPORTANT)**

https://k2dbk.com/weather

**Version of the skin you're using**
1.2

**To Reproduce**
1. Go to https://k2dbk.com/weather
2. Note that forecast is missing

**Expected behavior**
Forecast should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/8498054/107857850-f1c0d780-6dfe-11eb-9c13-9a3240ec7c09.png)

**Device Information (please complete the following information):**
 - Device: Any (not device dependent)
 - OS:  Windows, IOS
 - Browser : Chrome, Safari,  Firefox
 - Version [e.g. 22]: Various

**Additional context**
There are no errors shown in the log (even with debug enabled), but I found this js error when I run with ?debug=1:

```
belchertown.js?1613240254:1121 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.update_forecast_data [as success] (belchertown.js?1613240254:1121)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
update_forecast_data @ belchertown.js?1613240254:1121
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
w.<computed> @ jquery.min.js:2
getJSON @ jquery.min.js:2
ajaxforecast @ belchertown.js?1613240254:473
setTimeout (async)
update_current_wx @ belchertown.js?1613240254:1406
onMessageArrived @ belchertown.js?1613240254:1390
d._receiveMessage @ paho-mqtt.min.js:54
d._receivePublish @ paho-mqtt.min.js:53
d._handleMessage @ paho-mqtt.min.js:49
d._on_socket_message @ paho-mqtt.min.js:43
(anonymous) @ paho-mqtt.min.js:17
```

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
Have you deleted your forecast.json and waited for an archive interval?

**Comment by dkozinn** [comment]
I did delete forecast.json. I've also restarted weewx, waited for it to archive, and I've run wee_reports both with weewx running and with it stopped (to rule out any issues with a file held open).

Latest version of that file is (obviously) available at https://k2dbk.com/weather/json/forecast.json

Am I possibly out of sync with some other file as I'm not running the packaged release at this point?

**Comment by poblabs** [comment]
Check troubleshooting guide in the readme and see what errors are in
console and syslog.

**Comment by dkozinn** [comment]
In the version that I'm running, the error is occurring on this line:
```for (i = 0; i < data["forecast"][0]["response"][0]["periods"].length; i++) {``` in belchertown.js (line 1121 in the last released version) but there is no "forecast", only forecast_1hr, forecast_3hr, and forecaset_24hr when I examine in the debugger.

I looked in forecast.json and the same three forecast_Xhr items are there. It looks like belchertown.js.tmpl has been updated extensively since the last packaged version, so I assume things have gotten out of sync.

I know I'm kind of on my own here, but  would putting the latest version of belchertown.js.tmpl into /etc/weewx/skins/Belchertown/js (and restarting) be enough to clear this up, or am I likely to keep running to issues? Is there a better way to do this?

Apologies because obviously I've shot myself in the foot, this isn't your fault.

**Comment by poblabs** [comment]
If you want to go back to version 1.2 you can download the zip file from
the releases link on the front page of the GitHub page. If you're mixing
the master download with 1.2 files then things will be out of sync.

Would I suggest you try is delete the skins belchertown folder and the bin
user belchertown.py file. Also delete all files from your public HTML that
has belchertown stuff.

Then re-download version 1.2, restart weewx and then try wee_reports or
wait for archive and it should all regenerate.

If you've made any customizations in skin.conf save a backup or move them
to weewx.conf

**Comment by dkozinn** [comment]
I've reset back to 1.2 and have just edited in my small change to the earthquake distance, so all is well now.  Thanks for your patience.
