### ISSUE TITLE
Aeris AQI

### ISSUE THREAD

**Issue by tlambertpdx** [poblabs/weewx-belchertown#571]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

weewx.reportengine is report generator is terminating when processing Aeris AQI

**Link to your website (IMPORTANT)**
tslllc.com/korsherw28/weewx/belchertown/index.html

**Version of the skin you're using**
weewx 4.4.0 and Belchertown 1.2

**To Reproduce**
Drop in most current version (as of 13-Feb-2021) of belchertown.py into /home/weewx/bin/user (after backing-up original belchertown.py that was in the general release package on 07-Feb-2021)

Validate the Aeris Client & Security are defined in weewx.conf  as well as the lat & long, plus the relevant aeris enabled flags are set to enabled.

Note;  NO CHANGES were made to the belchertown.py

Restart weewx -- sudo systemctl restart weewx

I also validated the Aeris URL resolves, by cut & paste from belchertown.py to browser then inserting the parameters used in weewx.conf -- the aeris api json does resolve.

**Expected behavior**

No errors in the weewx log file and ability to report current AQI based on Aeris information

**Screenshots**
Log File:

Feb 13 16:51:26 ziggy weewx[6330] INFO user.belchertown: version 1.2
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  'aqi'
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown.py", line 1486, in get_extension_list
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      aqi = data["aqi"][0]["response"][0]["periods"][0]["aqi"]
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  KeyError: 'aqi'
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      obj.start()
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      self.run()
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 150, in run
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 309, in generate
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      default_binding)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 385, in _getSearchList
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown.py", line 1494, in get_extension_list
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****      "The URL being used is:\n%s" % (error, data["aqi"], aqi_url)
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  KeyError: 'aqi'
Feb 13 16:51:26 ziggy weewx[6330] ERROR weewx.reportengine:         ****  Generator terminated
Feb 13 16:51:26 ziggy weewx[6330] INFO weewx.reportengine: Copied 37 files to /mnt/hood/weewx/public_html/belchertown

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6] - R Pi4
 - OS: [e.g. Windows, Android, iOS] Raspbian (latest)
 - Browser [e.g. Chrome, Safari] N/A
 - Version [e.g. 22] N/A

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

Reverted to original belchertown.py (that has been working) and issue resolved.

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by uajqq** [comment]
Can you delete forecast.json and run wee_reports again?

**Comment by tlambertpdx** [comment]
Uajqq,

I performed the following:

1. Stopped weewx
2. Dropped in the latest belchertown.py (after backing up the working version) to /home/weewx/bin/user
3. Dropped the forecast.json (backed it up too) in /home/weewx/public_html/belchertown/json, as well as on the public accessible site
4. Started weewx
5. Allowed weewx to run for 45 minutes:
a. Didn’t see any errors in the log
b. On my published site (as well as locally) the forecast was no longer showing
c. I verified a forecast.json was pushed to /home/weewx/public_html/belchertown/json (and verified it was being pushed to the published site too)
6. Stopped weewx, reverted belchertown.py to the back-up, Started weewx – resulting in the forecast being displayed on both the published site and locally

Regards,

Tim

**Comment by uajqq** [comment]
forecast.json is generated dynamically. Sometimes there are issues when an old version is present. I recommend deleting it entirely, and letting the skin regenerate it. That solves most issues with anything forecast-related (including AQI).

**Comment by tlambertpdx** [comment]
Uajqq,

Technically forecast.json was entirely deleted.   The backup was put on another server and the file on the weewx server was deleted (in fact I deleted any forecast.json on the server where weewx is running)


Regards,

Tim

**Comment by uajqq** [comment]
Can you set debug=1 in weewx.conf and post the logs through an update cycle?

**Comment by tlambertpdx** [comment]
uajqq,

I executed the same process, as previously shared after the suggestion to drop the forecast.json, this time with debug turned on.  Again, the weather forecast was no longer displaying, although a new forecast.json was generated -- either locally or on the published side.

Attached is the log file and the forecast.json. 

In the log, the forecast.json was downloaded at line 204.   The forecast.json was pushed via FTP to the public site at line 395.

[aeris-aqi-test-log.txt](https://github.com/poblabs/weewx-belchertown/files/5992351/aeris-aqi-test-log.txt)

[forecast.txt](https://github.com/poblabs/weewx-belchertown/files/5992370/forecast.txt)
