### ISSUE TITLE
Make it possible to translate the AQI label

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#572]
The AQI option works fine for here, but I would like to translate the label "AQI" into my local language. I can fix this myself but I would like to see it as an option for all users.

This would translate to something like AQI = Luchtkwaliteit (in dutch)

**Comment by ddperso** [comment]
Yes, it's a good idea to avoid a "hard" translation in html file.

**Comment by uajqq** [comment]
Latest pull request should allow that—give it a try

**Comment by ArendPWS** [comment]
> Latest pull request should allow that—give it a try

It works, thanks! 👍
