### ISSUE TITLE
Windy radar map iframe is gone

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#578]
I noticed that @poblabs made some changes to the code in belchertown.py.
Upgraded all relevant files to the latest versions as far as I can tell (1.3b1). Maybe something is still missing in skin.conf/weewx.conf but can't find what may cause this issue. Problem arose after replacing style.css with the latest (I guess).

Any suggestions are welcome, will keep testing.

Update:

The problem only seems to occur in dark mode.

**Comment by poblabs** [comment]
The iframe is gone all together? Hmm, still working for me. Have you tried a clear cache and force reload?

**Comment by ArendPWS** [comment]
As I wrote in my update it doesn't show up in dark mode. Light mode seems to work allright for all types of maps and options. Something blocking in dark mode?

**Comment by poblabs** [comment]
Not sure really. Both modes are working for me on my dev server. When you're in dark mode are there any errors in chrome console?

![image](https://user-images.githubusercontent.com/3484775/108120153-d5c36d00-706e-11eb-8bf6-25cc7bff803d.png)

**Comment by ArendPWS** [comment]
I don't see any console errors at the moment. I will have another look at it tomorrow, maybe some ideas will popup in the mean time. 😃

**Comment by poblabs** [comment]
Strange, I'm seeing this now too - broken in dark mode only with no errors.

**Comment by poblabs** [comment]
I pushed an update to this (I think). The changes I made to width/height did not affect the "broken" code. 

I'm not sure how dark radar html ever worked to be honest.

**Comment by ArendPWS** [comment]
With your latest updates everything regarding radarmap in dark mode is working again here. I was afraid my update on belchertown-dark.min.css had broken something (phew!).

**Comment by poblabs** [comment]
Great!
