### ISSUE TITLE
belchertown.py calls get_scalar without providing a record

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#583]
**First step**
Try to debug the skin yourself. 

Did so. That's why I can describe what happens.

**Describe the bug**
line 1191:
` current = weewx.tags.CurrentObj(db_lookup, station_obs_binding, current_stamp, self.generator.formatter, self.generator.converter)`
line 1217:
`obs_output = getattr(current, obs)`

Those lines result in calling get_scalar() method of XType extension. According to the [documentation](https://github.com/weewx/weewx/wiki/WeeWX-V4-user-defined-types#registering-your-subclass) the parameter "record" must not be None. But it is. 

That in turn results in some exception raised within one of the get_scalar() methods.

get_scalar() is to return a value for the given observation type and the timestamp provided within the record. If there is no record there is no timestamp. So which value to return? The documentation does not suggest to return the last available value. And I asked Tom Keffer, and he wrote that returning that last value is not really intended.

**Link to your website (IMPORTANT)**
[https://www.woellsdorf-wetter.de](https://www.woellsdorf-wetter.de)

**Version of the skin you're using**
1.2

**To Reproduce**
1. Install some XType extension that does not deal with record being None
2. Restart WeeWX
3. Observe the log and the error messages

**Expected behavior**
A valid record including dateTime and usUnits field should be provided.

**Device Information (please complete the following information):**
 - Device: not applicable
 - OS: Linux
 - Browser: not applicable
 - Version: 1.2

**Comment by ArendPWS** [comment]
@roe-dl,

Can you provide a link to the discussion with Tom Keffer?

**Comment by roe-dl** [comment]
[Link to the statement of Tom Keffer](https://groups.google.com/g/weewx-development/c/DVKoLKCCOTc/m/21fXQ8W_AwAJ)
[Link to the XType extension that got the problem](https://github.com/roe-dl/weewx-GTS)

**Comment by ArendPWS** [comment]
@roe-dl

The PR has already been merged in the 1.3b1 beta. If it works for you, would you be so kind to close this issue?

**Comment by roe-dl** [comment]
Unfortunately I did not test the Beta of Belchertown 1.3. Additionally, I included a work-around in my XType extension, that masks that issue. So I cannot try that easily.
