### ISSUE TITLE
gapsize * 1000 concatenates a string, does not multiply gapsize value

### ISSUE THREAD

**Issue by Mattk70** [poblabs/weewx-belchertown#584]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
Belchertown.py (as of commit 7d9113a) line 2336/7.

` if gapsize:
                    output[chart_group][plotname]["options"]["gapsize"] = gapsize * 1000`

The variable 'gapsize' here is a string, so *1000 concatenates the gapsize value 1000 times instead of multiplying by 1000. I haven't investigated the impact on highcharts - specifically when a small gapsize is required, however, the result is a bloated JSON file that is hard to debug for other issues.

**Link to your website (IMPORTANT)**
https://weather.mattkirkland.co.uk/belchertown-dev/ <- the aforementioned bug is not present on the site.

**Version of the skin you're using**
1.3b1 (though bug present in 1.2 release)

**To Reproduce**
Go to charts page, set debug=1 as command line parameter, and right click "inspect" using Google Chrome. Alternatively look at any chart group JSON file in /json directory

**Expected behavior**
Where gapsize is 300, gapsize * 1000 should result in 300000, not 300300300300300300300300300300300300300....

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
I am new to Github, and cannot locate a development branch in your repo, so stumped as to how to create a pull request. However, the desired result is obtained by substituting:

` if gapsize:
                    output[chart_group][plotname]["options"]["gapsize"] = int(gapsize) * 1000`

All the best,
Matt

**Comment by Mattk70** [comment]
Also, related to this, the previous stanza sets a default gapsize in millis which is then multiplied by 1000:

`                # gapsize has to be in milliseconds. Take the graphs.conf value
                # and multiply by 1000
                gapsize = plot_options.get(
                    "gapsize", 300000
                )  # Default to 5 minutes in millis`

A simple fix is to change this to seconds:

`                # gapsize has to be in milliseconds. Take the graphs.conf value
                # and multiply by 1000
                gapsize = plot_options.get(
                    "gapsize", 300
                )  # Default to 5 minutes in millis`

**Comment by ArendPWS** [comment]
@Mattk70,

Nice find, making these changes made the gaps show up again.

**Comment by poblabs** [comment]
Great find and thanks for your contribution! This has been merged into master

**Comment by Mattk70** [comment]
You're welcome, thanks Pat! Awesome skin by the way 🥇
