### ISSUE TITLE
Belchertown NOAA reports should use a 'utf8' encoding instead of 'strict_ascii'

### ISSUE THREAD

**Issue by gand07** [poblabs/weewx-belchertown#587]
Changes in skin.conf
[[[NOAA_month]]]
            encoding = **utf8**
            template = NOAA/NOAA-YYYY-MM.txt.tmpl
and 
[[[NOAA_year]]]
            encoding = **utf8**
            template = NOAA/NOAA-YYYY.txt.tmpl

This change causes some non-english characters to appear correctly

:Rgds
Gert

**Comment by ArendPWS** [comment]
@gand07,

You want utf8 to be the default? But it is already a configurable option....

**Comment by gand07** [comment]
Hi ArendPWS
Yes, I suggest UTF8 as default encoding for the NOAA templates. In WeeWX version 4.4, the default is utf8 for the NOAA templates. I did't know I could configure it. Each time I upgrade Belchetown, I have manually changed the NOAA templates to use utf8 in the skin.conf. If I forget, the danish chareacters are not displayed correctly.

Could You please point me in a direction how to configure the encoding in Belchertown? I have missed that.

Thanks for your help.

Rgds
Gert

**Comment by ArendPWS** [comment]
You can put essential Belchertown settings from skin.conf in WeeWX.conf, that way they will never be overwritten with a skin update. My way of updating the skin is totally different, just replacing the things I need/want so can't compare that with you. Here is an example of Belchertown settings I keep in WeeWX.conf at the moment (if you apply this, mind the number of square brackets):

    [[Belchertown]]
        skin = Belchertown
        enable = true
        HTML_ROOT = public_html/belchertown
        [[[Extras]]]
            # General Site Defaults
            belchertown_debug = 1
            belchertown_locale = auto
            theme = auto
            theme_toggle_enabled = 1
            site_title = ""
            logo_image = ""
            logo_image_dark = ""
            radar_html = ""
            radar_html_dark = ""
            radar_width = 650
            radar_height = 360
            radar_marker = 0
            aeris_map = 0
            almanac_extras = 1
            
            # Station Observations. Special observation rainWithRainRate combines Daily Rain with Rain Rate in 1 line
            station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, UV, cloudbase, cloud_cover, visibility
            
            # Manifest Settings for Mobile Phones
            manifest_name = My Weather Website
            manifest_short_name = MWW
            
            # Highcharts settings
            highcharts_enabled = 1
            graph_page_show_all_button = 1
            graph_page_default_graphgroup = today
            highcharts_homepage_graphgroup = homepage
            highcharts_decimal = auto
            highcharts_thousands = auto
            
            # MQTT Websockets defaults
            mqtt_websockets_enabled = 1
            #mqtt_websockets_host = ""
            mqtt_websockets_host = xxx.xxx.xxx
            mqtt_websockets_port = 9001
            mqtt_websockets_ssl = 0
            mqtt_websockets_topic = weather/loop
            disconnect_live_website_visitor = 300000
            
            # Show an alert if the page updated timestamp is older than expected with this setting. Does not apply to MQTT Websocket enabled websites
            # The late time threshold is defined in seconds. This should be greater than your archive_interval from weewx.conf.
            # Typically you would want this 2 or 3 times archive_interval
            show_last_updated_alert = 0
            last_updated_alert_threshold = 1800
            
            # If mqtt_websockets_enabled is set to 0, but want the page to full reload on an interval, specify this below in milliseconds. 300000 = 5 minutes
            webpage_autorefresh = 0
            
            # Image Reload Section.
            # Set reload_hook_images to 1 to enable, then set the number of *seconds* for each section to reload.
            # A value of -1 will disable reloading images in that section.
            # radar = the radar image if you used radar_html setting
            # asi = index_hook_after_station_info.inc
            # af = index_hook_after_forecast.inc
            # as = index_hook_after_snapshot.inc
            # ac = index_hook_after_charts.inc
            reload_hook_images = 0
            reload_images_radar = 300
            reload_images_hook_asi = -1
            reload_images_hook_af = -1
            reload_images_hook_as = -1
            reload_images_hook_ac = -1
            
            # Forecast defaults
            forecast_enabled = 1
            forecast_provider = aeris
            forecast_api_id = xxxxxxxxxxxxxxxxxxxxxxxxxxx
            forecast_api_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            forecast_units = si
            forecast_interval_hours = 1    # values are 0,1,3 or 24

            forecast_lang = nl
            forecast_stale = 3540
            forecast_aeris_use_metar = 1
            forecast_alert_enabled = 1
            forecast_alert_limit = 10
            forecast_show_daily_forecast_link = 0
            forecast_daily_forecast_link = ""

            forecast_dev_file = http://192.168.178.9/weewx/belchertown/json/Forecast_Dev_File.json

            # Air Quality Index (AQI) defaults
            aqi_enabled = 1
            aqi_location_enabled = 1

            # Beaufort wind scale defaults
            beaufort_category = 1

            # Earthquake defaults
            earthquake_enabled = 1
            earthquake_maxradiuskm = 2000
            earthquake_stale = 10740
            earthquake_server = USGS
            geonet_mmi = 4
            
            # Social Share Button Defaults. Define the text below under Labels
            facebook_enabled = 0
            twitter_enabled = 0
            social_share_html = http://yourwebsite
            
            # Google Analytics
            #googleAnalyticsId = UA-12345678-1
            
            # This is the display of the Pi Kiosk which is in the /pi folder
            pi_kiosk_bold = false
            pi_theme = auto
        
        ###############################################################################
        
        [[[Labels]]]
            # Labels used in this skin
            
            [[[[Generic]]]]
                # Generic labels, keyed by an observation type.
                # To change a label or translate it to your language
                # change the text after the equal sign.
                
                # Station Observation Table
                rainWithRainRate = Neerslag
        
        ###############################################################################
        
        [[[CheetahGenerator]]]
            # This section is used by the generator CheetahGenerator, and specifies
            # which files are to be generated from which template.
            
            search_list_extensions = user.belchertown.getData
            
            # Possible encodings are 'html_entities', 'utf8', or 'strict_ascii'
            encoding = html_entities
            
            [[[[SummaryByMonth]]]]
                # Reports that summarize "by month"
                [[[[[NOAA_month]]]]]
                    encoding = strict_ascii
                    template = NOAA/NOAA-YYYY-MM.txt.tmpl
            
            [[[[SummaryByYear]]]]
                # Reports that summarize "by year"
                [[[[[NOAA_year]]]]]
                    encoding = strict_ascii
                    template = NOAA/NOAA-YYYY.txt.tmpl
            
            [[[[ToDate]]]]
                # Reports that show statistics "to date", such as day-to-date,
                # week-to-date, month-to-date, etc.
                [[[[[weewx_data]]]]]
                    template = json/weewx_data.json.tmpl
            
            [[[[Belchertown]]]]
                template = js/belchertown.js.tmpl
                
                [[[[[home]]]]]
                    template = index.html.tmpl
                
                [[[[[about]]]]]
                    template = about/index.html.tmpl
                
                [[[[[graphs]]]]]
                    template = graphs/index.html.tmpl
                
                [[[[[records]]]]]
                    template = records/index.html.tmpl
                
                [[[[[reports]]]]]
                    template = reports/index.html.tmpl
                
                [[[[[pi]]]]]
                    template = pi/index.html.tmpl
                
                [[[[[manifest]]]]]
                    encoding = utf8
                    template = manifest.json.tmpl

**Comment by gand07** [comment]
Hi ArendPWS
Thanks for your prompt answer.

I have all the translation stuff in weewx.conf, but I missed the Cheetah part for the NOAA templates.
I'll try that.

Thanks
Gert

**Comment by poblabs** [comment]
> In WeeWX version 4.4, the default is utf8 for the NOAA templates. 

It might make sense to mirror what the Seasons skin is doing. I'll take a look at it - or if someone beats me to it with a Pull Request 😄

**Comment by ArendPWS** [comment]
> > In WeeWX version 4.4, the default is utf8 for the NOAA templates.
> 
> It might make sense to mirror what the Seasons skin is doing. I'll take a look at it - or if someone beats me to it with a Pull Request 😄

When I read this:

[https://groups.google.com/g/weewx-user/c/lQ-Q_9Zd04s/m/5Tpu5mamBQAJ](https://groups.google.com/g/weewx-user/c/lQ-Q_9Zd04s/m/5Tpu5mamBQAJ)

and this:

[https://github.com/weewx/weewx/commit/cb0d0e50362e84dd64a2b6755af40ee6ff8c9662](https://github.com/weewx/weewx/commit/cb0d0e50362e84dd64a2b6755af40ee6ff8c9662)

NOAA reports now default to normalized_ascii not utf8.

I am not sure normalized_ascii will work for Gert. This issue was also an eyeopener for me, my settings also needed to change to utf8 to display degree Celcius (°C) correctly in the reports.

**Comment by poblabs** [comment]
Wonder if utf will work for belchertown since most of the skin is utf

**Comment by ArendPWS** [comment]
@gand07,

I am curious what happens to your characters/language when you are using this configuration, could you test this? (only works in weewx 4.4.0 ofcourse).

            [[[[SummaryByMonth]]]]
                # Reports that summarize "by month"
                [[[[[NOAA_month]]]]]
                    encoding = normalized_ascii
                    template = NOAA/NOAA-YYYY-MM.txt.tmpl
            
            [[[[SummaryByYear]]]]
                # Reports that summarize "by year"
                [[[[[NOAA_year]]]]]
                    encoding = normalized_ascii
                    template = NOAA/NOAA-YYYY.txt.tmpl

As I understand there will be another encoding available in weewx 4.4.1 (cp1252). Perhaps that one will solve all your language related issues in NOAA reports?

**Comment by gand07** [comment]
Hi ArendPWS
**normalized_ascii** will not work. From the report:
**NAME: Vester Smarken, Bornholm**

With utf8:
**NAME: Vester Sømarken, Bornholm**
Whicj is correct.

When Tom announced WeeWx 4.4 he wrote:
_NOAA reports now use a 'utf8' encoding instead of 'strict_ascii'. This will only
affect new installations. Fixes issue #644._
https://groups.google.com/g/weewx-user/c/K6jYqj7Kn6o

In my case only utf8 is working

Gert

**Comment by gand07** [comment]
Merged
