### ISSUE TITLE
Use Weewx Daily Summaries for charts where "aggregate_interval" >= 1 day

### ISSUE THREAD

**Issue by Mattk70** [poblabs/weewx-belchertown#589]
:bulb: **The Idea**
Charts for a year or more can take a *long* time to render, especially when running weewx on a Pi, and with records going back several years, as I do. Adapting the sql_lookup statements to take advantage of daily summaries can *significantly* reduce the time these charts take to prepare. 

Naturally the `generate=<a long time>` options mitigate the impact somewhat, but that can be a pain when debugging.

:hammer: **Breaking Feature**
If implemented correctly, this feature should be transparent. New aggregation types (I have some, but that's for another time) will need to be mindful of the optimization going forward.

**HELP WANTED**
I have a working version for Mysql and hope that the sqllite section has been appropriately modified, but I have not tested it. I'll submit a pull request if you are interested and able to test the SQL lite implementation?

In case you're wondering, using the modulus excludes some (I think) edge cases where aggregate interval might be 36 hours or some other interval that is not a day or multiple thereof.

It looks like this.
(Note: I have also abstracted out the ORDER BY clause as it cuts out a lot of code repetition)

`         
 if isinstance(time_length, int):
                order_sql = " ORDER BY dateTime ASC"
            else:
                order_sql = ""
`

            elif driver == "weedb.mysql":
                # Use daily summaries where possible
                if (aggregate_interval >= 86400 and aggregate_interval % 86400 == 0) :  # 1 or more exact days
                    # Avg is a special case
                    if aggregate_type == "avg":
                        sql_lookup = 'SELECT FROM_UNIXTIME( dateTime, "%{0}" ) AS {1}, ' \
                                     'ROUND(SUM(wsum)/ SUM(count),2) as obs ' \
                                     'FROM archive_day_{2}  WHERE dateTime >= {3} AND dateTime <= {4} ' \
                                     'GROUP BY {1}{5};'.format(
                            strformat,
                            xAxis_groupby,
                            obs_lookup,
                            start_ts,
                            end_ts,
                            order_sql
                        )
                    else:
                        sql_lookup = 'SELECT FROM_UNIXTIME( dateTime, "%{0}" ) AS {1}, {2}({2}) as obs ' \
                                     'FROM archive_day_{3}  ' \
                                     'WHERE dateTime >= {4} AND dateTime <= {5} GROUP BY {1}{6};'.format(
                            strformat,
                            xAxis_groupby,
                            aggregate_type,
                            obs_lookup,
                            start_ts,
                            end_ts,
                            order_sql
                        )
                else:
                    sql_lookup = 'SELECT FROM_UNIXTIME( dateTime, "%{0}" ) AS {1}, ' \
                                 'IFNULL({2}({3}),0) as obs ' \
                                 'FROM archive WHERE dateTime >= {4} AND dateTime <= {5} GROUP BY {6}{7};'.format(
                        strformat,
                        xAxis_groupby,
                        aggregate_type,
                        obs_lookup,
                        start_ts,
                        end_ts,
                        xAxis_groupby,
                        order_sql
                    )

**Comment by poblabs** [comment]
Awesome! Looks good on the surface so I merged it in. Always happy to see performance improving updates!
