### ISSUE TITLE
Feature request - plot max radiation curve

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#59]
As per attached picture, plot the expected max radiation curve on the solar radiation graph. Great just for interest or for calibrating sensors. Optional maybe?
![screen shot 2019-02-09 at 11 16 05 am](https://user-images.githubusercontent.com/1725001/52509243-4d7a8800-2c5c-11e9-82c5-0fb3c96ca48c.png)

**Comment by poblabs** [comment]
Optional maybe. Where is this screenshot taken from? The weewx-highcharts extension? 

2 thoughts:

1. I don't know how to do this so I'd have to figure it out 😃 
2. I'm not showing the day/night colors on the X-axis. So would this be another option? 🤔

**Comment by 41south** [comment]
Yes agree optional. The screenshot is from the new default Weewx skin in 3.9.2.  (Seasons). I was only thinking about the curve, not the shading for day/night. That seems a little over the top :)

**Comment by poblabs** [comment]
Update on this. The Max Radiation observation does come from weewx, and it's calculated on every archive interval. This will be available in skin 1.0 as an observation to chart using the new chart system. 

[In the meantime, add `maxSolarRad` to your database by extending it like you would for apptemp, cloudbase, etc](https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database). That way the values are being saved sooner than later for your future charts. 

When skin 1.0 is released, the observation will be `maxSolarRad`.

**Comment by 41south** [comment]
That's brilliant, will do that asap, thanks for the update

**Comment by poblabs** [comment]
Charting for this will be supported in skin 1.0 as long as the database is extended.

**Comment by HoracioDos** [comment]
Hello Pat
Are maxSolarRad and "Theoretical Max Solar Radiation" the same? I have a huge difference between SolarRad and maxSolarRad. Do you know if weewx will be more accurate over time?
Thanks!

**Comment by poblabs** [comment]
Yes they are the same  I'm not aware of a solarRad observation. For
maxSolarRad to work you need the pyephem python library installed. This
could be why you're seeing something inaccurate.

**Comment by 41south** [comment]
MaxSolarRad is proving to be pretty accurate here.

Colin

**Comment by HoracioDos** [comment]
Hi Colin
Thanks for your answer. Perhaps it is due that I live inside the south atlantic anomaly. Lol!!
