### ISSUE TITLE
Records page DST issue

### ISSUE THREAD

**Issue by dciarniello** [poblabs/weewx-belchertown#594]
From comparing the records shown on the records page to the NOAA reports, I noticed that the time for records that occur when DST is in effect are off by an hour.  I've validated that the problem is there in both my deployment and belchertownweather.com.
For example, the belchertown weather records page shows the maximum temperature was 97.4F on July 1, 2018 at 3:11PM but the NOAA page for July 2018 shows that the max was at 16:11 (4:11PM).  
The issue also affects the temperature range records.  Note that the maximum temperature range is reported as April 20 but the NOAA reports show that it actually was April 21.  The date for 2021 maximum temperature range is, howeve, correct, presumably because it occurred during standard time.

**Comment by poblabs** [comment]
Thanks for bringing this up. 

The difference is NOAA is made by Python and uses the system time a little easier. 

The records page uses moment.js, and would have to be [refactored for a lot of true/false checks](https://stackoverflow.com/a/21918576/1177153).

**Comment by dciarniello** [comment]
It looks there is a simpler solution available and that is to use moment-timezone: https://momentjs.com/timezone/
With that, the utsOffset() call can be replaced with tz() which will handle DST automatically.
The only problem is that I haven't been able to figure out how to get the proper time zone names (e. g. America/Vancouver) using python.  I can easily get the time zone short names (e. g. PST) which seems to work but I'm not certain that would be good enough.  
I suppose that a skin.conf variable could be used with what python returns as a fallback.

**Comment by poblabs** [comment]
The pytz library can give you the timezone name but I'd rather not have another pre-requisite to install the skin. So perhaps a skin.conf option would be needed, and if that's blank or omitted in skin.conf, then we let moment.js use it's default settings (like what it's doing today)

Thoughts?

**Comment by dciarniello** [comment]
I had the same thought about pytz.
I've put together a proposed fix and created a PR.
