### ISSUE TITLE
Consecutive days with/without rain include days without/with rain

### ISSUE THREAD

**Issue by dciarniello** [poblabs/weewx-belchertown#595]
I was comparing the consecutive days with and without rain records to the NOAA reports and noticed that the first day of the consecutive days with rain did not actually have rain while the converse is the situation with consecutive days without rain.
The belchertownweather.com records page also exhibits the problem
According to that page, the most consecutive days with rain began October 25, 2020 but that day has 0.00 inches of rain in the NOAA report.  For consecutive days without rain, the records page gives December 24, 2017 but that day has 0.01 inches of rain in the NOAA report.

**Comment by poblabs** [comment]
The [calculations from the database are done here](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py#L846-L860). How do you suggest it's updated?

**Comment by dciarniello** [comment]
Hmmm...
Upon further inspection, it looks like the issue with consecutive days *with* rain is DST handling by moment.js.  Basically, the same prolem as for https://github.com/poblabs/weewx-belchertown/issues/594.  
That doesn't explain the consecutive days without rain issue, however, since in belchertown's case, the interval is in December when DST is not in effect.
On the surface it looks like the algorithm is good for consecutive days with rain but adds a day for consecutive days without rain.  I'll try to dig deeper when I get a chance and see if I can figure it out.

**Comment by dciarniello** [comment]
I figured out the problem.  It's not with the algorithm that you pointed me to but with the calculation of the start of the intervals in records/index.html.tmpl which has an off-by-one error.
I've created a pull request with the proposed fix.
