### ISSUE TITLE
Develop Wind Compass for airfield weather stations

### ISSUE THREAD

**Issue by flygpagen** [poblabs/weewx-belchertown#596]
:bulb: **The Idea**
For pilots the most important feature of a local weather station is the information about wind direction, speed & gust speed. The wind decides which runway is in use and for smaller aircraft the windspeed combined with the wind angle towards the runway may decide if a safe start (and landing) is possible. I propose a feature displaying the runway in the windDir.ordinal_compass as a backgound line in the correct direction, f. ex. 220/40 degrees to help deciding which runway to use when planning a flight.

:hammer: **Breaking Feature**
To further help pilots, calculations can be made on headwind and sidewind component figures. Small aircraft often have a maximum allowed side wind component. This can be programmed as per for example [this website](https://www.estt.se/vader/) (translated to English using Google Translate [here](https://translate.google.com/translate?sl=sv&tl=en&u=https://data.soderslattsfk.se/estt-weather/ww4.php)).

![weather_wind_ESTT](https://user-images.githubusercontent.com/48225951/108742674-3c95ca00-7538-11eb-906e-13393f34e889.JPG)

**HELP WANTED**
I can probably get the code for the example website feature, but I do not have the skills to develop the feature in Belchertown. Of course I have a weather station placed at my own airfield, see http://websrc.hlmfk.se/weewx

**Comment by flygpagen** [comment]
![image](https://user-images.githubusercontent.com/48225951/111880361-5a294880-89ab-11eb-948a-d97c7c6621e3.png)

I put in a solution using CSS. Would require an option in the config to set runway headings. I'll continue looking into if I can figure out how to make this work.

**Comment by norecords** [comment]
@flygpagen I've got a very first shot of code that you can try. I found a [calculator](https://www.experimentalaircraft.info/pwa/crosswinds.php) where I took the code for example. 
Edit belchertown.js.tmpl add at the end of the file:
```
function calcXwind(windDir, windspeed) {
  const runway = 22;
  windDir = parseFloat(windDir).toFixed(1);
  windspeed = parseFloat(windspeed).toFixed(1);
  // windspeed = windspeed / 1.852; // convert km/h to knots
  var lrxw = ""
  // console.log('windDir: ' + windDir + ' Windspeed (knots): ' + windspeed + ' Runway: ' + runway)
  let u = Math.abs(windDir - runway);
  const headwind = Math.round(Math.abs(windspeed * Math.sin(0.017453 * u))),
       crosswind = Math.round(windspeed * Math.cos(0.017453 * u));
  0 === u || 180 === u ? (lrxw = "") : (windDir > runway && windDir < runway + 180) || runway - 180 > windDir ? (lrxw = "right") : (windDir < runway || windDir > runway + 180) && (lrxw = "left")
  // console.log('Headwind: ' + headwind + ' Crosswind: ' + crosswind + ' Xwind Dir: ' + lrxw);
  jQuery(".active_lane").html(runway);
  jQuery(".headwind").html(headwind + unit_label_array["windSpeed"]);
  jQuery(".crosswind").html(Number.parseFloat(u).toFixed(0) + unit_label_array["windDir"] + ' @ ' + crosswind + unit_label_array["windSpeed"] + ' from ' + lrxw);

```
then find
```
    // Windspeed knots
    if (data.hasOwnProperty("windSpeed_knot")) {
        jQuery(".curwindspeed").html(parseFloat(parseFloat(data["windSpeed_knot"])).toLocaleString("$system_locale_js", {minimumFractionDigits: unit_rounding_array["windSpeed"], maximumFractionDigits: unit_rounding_array["windSpeed"]}));
    }
```
add after
```
    // Crosswind
    if (data.hasOwnProperty("windDir") && data.hasOwnProperty("windSpeed_knot")) {
              calcXwind(data["windDir"], data["windSpeed_knot"]);
    }
```
Save and exit.

Open index.html.tmpl and find
```
                            <table cellpadding="0" cellspacing="0">
                                <tbody>
                                    $station_obs_html
                                </tbody>
                            </table>
```
Modify to
```
                            <table cellpadding="0" cellspacing="0">
                                <tbody>
                                    $station_obs_html
                                    <tr>
                                        <td class="station-observations-label">Active Lane</td>
                                        <td class="active_lane"></td>
                                    </tr>
                                    <tr>
                                        <td class="station-observations-label">Headwind</td>
                                        <td class="headwind"></td>
                                    </tr>
                                    <tr>
                                        <td class="station-observations-label">Crosswind</td>
                                        <td class="crosswind"></td>
                                    </tr>
                                </tbody>
                            </table>
```
Save and exit, wait for next report or do wee_reports,
for the moment data will be shown after first mqtt payload in the station observation table.

**Comment by flygpagen** [comment]
Thank you so much, it works like a charm now that the {brackets} are in place! I will try to fit it under the windcompass and style it properly!

**Comment by norecords** [comment]
@flygpagen you can look what I'm doing now [here](https://meteo.correns.org/)
I'll push on my fork soon.

**Comment by norecords** [comment]
@flygpagen can you try with these commits over original files:
https://github.com/norecords/weewx-belchertown/commit/bbfa875a576f03c84d4ba1c27eee2e379451dffd#diff-6ad6bab24eeb34554e6e372d162736e9538f7aec36cc017eb1dbed026c7a614e
and
https://github.com/norecords/weewx-belchertown/commit/923b041fec96454df2778bdc0c2c7be1261e1b06#diff-6ad6bab24eeb34554e6e372d162736e9538f7aec36cc017eb1dbed026c7a614e

and give some feedbacks :)
![Screenshot_2021-03-27 Météo Correns - Station météorologique en temps réel](https://user-images.githubusercontent.com/12499787/112724447-b5ab8700-8f13-11eb-984e-aa6b61c55a14.png)

**Comment by norecords** [comment]
You can add this after to add Crosswind angle arrow on compass https://github.com/norecords/weewx-belchertown/commit/9aa9496aebb22d7d6258af5f0c7e92b5c49a9a69

![Screenshot_2021-03-28 Météo Correns - Station météorologique en temps réel](https://user-images.githubusercontent.com/12499787/112746127-42565380-8fad-11eb-82f4-0379040ba58d.png)

**Comment by flygpagen** [comment]
Will do!

**Comment by flygpagen** [comment]
I'm getting some strange results here using the supplied code. I'm not sure really if the usage is clear. Active runway is decided by the wind direction. The cross-wind-component does not really make sense to me right now but maybe I have to study the code more. 
![image](https://user-images.githubusercontent.com/48225951/112756736-d7297300-8fe6-11eb-8f7e-8bb129b845ac.png)

**Comment by norecords** [comment]
@flygpagen the [example site](https://data.soderslattsfk.se/estt-weather/ww4.php) you provide does exactly the same as I code here; 
the active runway never change whatever the wind direction is.. Here the green arrow is the Crosswind angle.
Do you have some code or a working example of the behavior you are looking for.

**Comment by flygpagen** [comment]
Hi! Active runway is always against the wind, so in this case 22 when winds are between 130 to 310 degrees, and 04 between 311 to 129. This is due to that you always start against the wind. But I think maybe I misunderstood the use of the green arrow, it is showing visually the degree of crosswind relative to the aircraft? :)

**Comment by norecords** [comment]
I was not sure if showing the crosswind angle on compass is pertinent and can be removed (however that's in the result of the calculator).
If I understand right we have to set existing runway on airfield (yours are 04 and 22) like now and active runway may change with the wind direction between these two runway.

**Comment by flygpagen** [comment]
I think it is clever but maybe unwise since it can be misleading to have two arrows on the compass. Textual representation of crosswind, component and headwind are enough really. During flight training a graph is used, like [this one](https://flighttrainingcenters.com/training-aids/private-pilot/cross-country/crosswind-component/) (not the best one but in english at least). You learn to gauge the approximate values by looking at the windsock by the runway.

**Comment by norecords** [comment]
@flygpagen look at the end of the [calculator](https://www.experimentalaircraft.info/pwa/crosswinds.php) I linked before.. :)

If you look at my [site](https://meteo.correns.org/), now I've the active lane calculated also.

**Comment by flygpagen** [comment]
I´m on it, sorry for late reply. Working... :)

**Comment by norecords** [comment]
Just see now after control that crosswind and headwind speeds are inverted.

**Comment by flygpagen** [comment]
![image](https://user-images.githubusercontent.com/48225951/113201890-5da1b700-926a-11eb-94cf-2d78ce87936c.png)
Looking at this, I get a feeling it should be Head 3 and Right 0, considering that the wind comes straight into runway with no crosswind and 3 knots headwind?

**Comment by norecords** [comment]
@flygpagen see that commit https://github.com/norecords/weewx-belchertown/commit/11f4a46566e7bef001a3ebe108228fa6ced37d50 to resolve inverted values, I'll have a look to your css

**Comment by flygpagen** [comment]
> @flygpagen and this commit [70b807e](https://github.com/poblabs/weewx-belchertown/commit/70b807e8e6c4a47e51c7fac315c5e840673f651d) for the font-size problem.
> Can you give feedback about the script on the PR #657
> Also can you prepare a text to introduce that feature (I think you have a better English than me :)) into the README in case that PR would be merged in the future or leave it as a receipt for people want to mods there template.

All is working fine! Well executed. Interpreting the code of the calculations is a bit above my knowledge, that is why I asked for help, but in comparison to other examples I have found I see no faults. :) 
I will do a text for the readme, I'll get back on that one. And a huge thank you @norecords for the work!

**Comment by norecords** [comment]
Thank you too, it's interesting and fun to dev.
You can add this commit https://github.com/poblabs/weewx-belchertown/pull/657/commits/711eeafbb2d9333642caed9992444f4e41a1cdf8 to have light / dark background color to current wind direction inside the compass.

**Comment by flygpagen** [comment]
Added all code and it still works like a charm! :)

**Comment by flygpagen** [comment]
@norecords Should I close this issue?

**Comment by norecords** [comment]
You can leave it open I think, as it's not merged and still fresh.

**Comment by norecords** [comment]
@flygpagen I see on your skin some css modification you can do if you can't truncate words like `Känns som`
![Screenshot_2021-04-11 ESFA, Hässleholm Weather Conditions](https://user-images.githubusercontent.com/12499787/114308043-c39c0300-9ae2-11eb-9570-95a105ef4ceb.png)
you may decrease the font size in style.css
```
.feelslike {
    text-align: center;
    font-size: 19px;
}
```
Also on mobile device the wind text need to be decrease to be compatible with small screens
![Screenshot_2021-04-11 ESFA, Hässleholm Weather Conditions(4)](https://user-images.githubusercontent.com/12499787/114308595-d0b9f180-9ae4-11eb-9d8d-71a6f6985548.png)

```
.windtext {
    font-size: 18px;
}
```
after these changes every screen view should be nicely displayed with your language text:
![Screenshot_2021-04-11 ESFA, Hässleholm Weather Conditions(5)](https://user-images.githubusercontent.com/12499787/114308983-f8f62000-9ae5-11eb-81f6-793b728b2d51.png)

**Comment by norecords** [comment]
Even better, decrease .feelslike on large screen and increase on small, and also decrease .windtext on small screen only:
https://github.com/poblabs/weewx-belchertown/blob/3839baa3fb5a94a40b4ca29235182e88d4867f62/skins/Belchertown/style.css#L1088-L1094
add after 
```
        .feelslike {
                font-size: 20px !important;
        }

        .windtext {
                font-size: 18px !important;
        }
```
and just edit this line
https://github.com/poblabs/weewx-belchertown/blob/3839baa3fb5a94a40b4ca29235182e88d4867f62/skins/Belchertown/style.css#L1499-L1502
```
.feelslike {
	text-align:center;
	font-size:19px;
}
```

**Comment by norecords** [comment]
@flygpagen could you apply this last change, also I've got map rendering that should interested you
[map of airports with Voronoï ](https://meteo.correns.org/maps/voronoi-fr.html)
and [Aeroways](https://wiki.openstreetmap.org/wiki/Aeroways)

**Comment by flygpagen** [comment]
Done! :)

**Comment by norecords** [comment]
@flygpagen Happy new year to you !
I'll rewrite this mod in a single file to be easy to include like we have done recently with the radar section.
Have a look here that may interest you !
https://github.com/poblabs/weewx-belchertown/issues/703
