### ISSUE TITLE
AQI doesn't update on the webpage unless you refresh the page

### ISSUE THREAD

**Issue by ms372591** [poblabs/weewx-belchertown#603]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
I've noticed since adding the AQI that it doesn't change unless you refresh the page. I'm not sure if that is how it is intended to work or if it is a bug. 

**Link to your website (IMPORTANT)**
https://belcampmdweather.tech/weewx/belchertown/

**Version of the skin you're using**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by poblabs** [comment]
You should upgrade to the latest master branch download, then restart weewx. This was resolved yesterday or the day before.
