### ISSUE TITLE
how to upgrade belchertown from 1.2 to 1.3

### ISSUE THREAD

**Issue by fvirgola80** [poblabs/weewx-belchertown#604]
:bulb: **The Idea**

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 

Hi guys, could you help me, I would like to know how to upgrade belchertown 1.2 version to 1.3b1 thank you so much
www.meteocivitavecchia.it

**Comment by poblabs** [comment]
It's easy. Grab the zip or tar file of the master branch. Example, here: https://github.com/poblabs/weewx-belchertown/archive/master.tar.gz

Then perform `wee_extension --install master.tar.gz` and it should upgrade for you. 

Always save a backup in case you need to go back
