### ISSUE TITLE
allow attribute on radar iframe to avoid warnings and errors

### ISSUE THREAD

**Issue by leotiger** [poblabs/weewx-belchertown#605]
1. With the advent of new cross-origin restrictions allowances need to be configured for iframe tags if these want to execute and access actions and data that may compromise security.
2. The belchertown skin adds an iframe that loads an interactive map from windy. The windy radar map uses actions that ask for accelerometer, geolocation and gyroscope data.
3. To allow this data transfer the belchertown skin should include the attribute '''allow="accelerometer;geolocation;gyroscope" changing the iframe html code on line 480f 
4. Probably it's a good idea to add a configuration parameter 

'''radar_html = '<iframe width="{}px" height="{}px" src="https://embed.windy.com/embed2.html?lat={}...'''

should be changed to 

'''radar_html = '<iframe allow="accelerometer;gyroscope;geolocation" width="{}px" height="{}px" src="https://embed.windy.com/embed2.html?lat={}...'''

thx a lot for this great skin...
u

**Comment by norecords** [comment]
As I can read [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy#browser_compatibility) not all browsers are supported for accelerometer and gyroscope parameters and still experimental

**Comment by leotiger** [comment]
True, but Windy asks for, and that's a great feature to have windy showing it's radar, and Chrome, as one of the most popular browsers, throws the errors and warnings. Just wanted to inform. I've changed that in the skin and simply wanted to share.
