### ISSUE TITLE
Starting Graph at Full Hour

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#608]
:bulb: **The Idea**
Is there an option to have the graph starting at a full hour? Like `start_at_midnight` does for the full day.

Example: Say, actual archive record time is 15:25. The chart is to show 24 hours, but shall start at a full hour. That would be 15:00 yesterday in this example.

Reason for that question: If you set `aggregate_interval=3600` the aggregation time span changes with every new record by 5 minutes.

The same applies for other aggregation intervals, such as 3 hours, which interval is often used in weather observation.

:hammer: **Breaking Feature**
No.

example graphs.conf snippet to illustrate the problem:
```
    [[chart3a]]
        time_length = hour_ago_to_now
        time_ago = 24
        title = rain
        yAxis_tickinterval=0.2
        [[[rain]]]
            observation_type=rain
            aggregate_type=sum
            aggregate_interval=3600
            type=column
            pointWidth=10
```

**Comment by poblabs** [comment]
The starting at midnight, starting at beginning of week, etc. are all functions native to weewx's core code. A starting at the top of the hour would have to be custom to Belchertown. I'll poke around at this over the next few days.

**Comment by roe-dl** [comment]
The standard graphs of WeeWX always start at a full hour. That's why there is no need for such a feature. But the Highcharts graphs can start at every time. So this is an issue.

**Comment by roe-dl** [comment]
@poblabs Could you think about it? For the rain graph it would be helpful.

**Comment by roe-dl** [comment]
See PR #713

**Comment by roe-dl** [comment]
Solved.
