### ISSUE TITLE
Is iPad CSS section still needed?

### ISSUE THREAD

**Issue by uajqq** [poblabs/weewx-belchertown#611]
I have low CSS literacy, but I note that my site looks much better on iPad when the iPad section in CSS is commented out. I assume this is because most new iPads have screen sizes comparable to (or better than) laptop computers. Is the iPad section needed at all in the CSS anymore?

**Comment by poblabs** [comment]
Good question. I do not own an iPad so I don't know those resolutions 😄 I guess we could comment it out, list it as a breaking change in the readme and see who brings it up as an issue and re-visit it?

**Comment by roe-dl** [comment]
On my iPad the skin looks terrible with the current CSS.

on top of the page:
![Screenshot1](https://user-images.githubusercontent.com/73126506/109432014-820b3900-7a09-11eb-9cd9-0a8748d07de1.png)

scrolled a litle bit:
![Screenshot2](https://user-images.githubusercontent.com/73126506/109432024-8d5e6480-7a09-11eb-9829-5dcd1fd4f80b.png)

**Comment by uajqq** [comment]
The problem is when the iPad is in landscape mode—things look better without the iPad CSS section in that case. In portrait, it looks the same whether or not iPad CSS is active.

**Comment by poblabs** [comment]
Oops, I mean breaking change in the `changelog`
