### ISSUE TITLE
AQI Translation lost. - Help Wanted

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#617]
Hello Pat.
AQI Translation is lost somewhere between 5ee644e and 90164db. Perhaps it is due to a1cd3a3455b6442255dddb2b033d6bd06e5fca4d
They were already in weewx.conf

```
                # Air Quality Index label defaults
                aqi_good = Bueno
                aqi_moderate = Moderado
                aqi_usg = Insalubre Grupos Sensibles    # Official wording: "unhealthy for sensitive groups"
                aqi_unhealthy = Insalubre
                aqi_very_unhealthy = Muy Insalubre
                aqi_hazardous = Peligroso
```
Thanks!

**Comment by norecords** [comment]
@HoracioDos you may follow this PR https://github.com/poblabs/weewx-belchertown/pull/610

**Comment by HoracioDos** [comment]
It work now! I guess that db8c734 fixed.
Thanks!
