### ISSUE TITLE
Missing Forecast and Current Weather icon

### ISSUE THREAD

**Issue by gand07** [poblabs/weewx-belchertown#618]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
Missing forcast and icon for current condition. In the log have these lines:

```
Mar  3 09:00:29 v220201144152132366 weewx[227043] INFO user.belchertown: New forecast file downloaded
Mar  3 09:00:29 v220201144152132366 weewx[227043] INFO user.belchertown: No cloud cover data from Aeris weather
Mar  3 09:00:29 v220201144152132366 weewx[227043] message repeated 10 times: [ INFO user.belchertown: No cloud cover data from Aeris weather]
```

**Link to your website (IMPORTANT)**
[http://billeder.de/](url)

**Version of the skin you're using**
1.3b1

**To Reproduce**
Open website

**Expected behavior**
See icon and forecast

**Screenshots**
Screeshot attached

**Device Information (please complete the following information):**
 - Device:Deskto, tablet
 - OS: Windows, Android
 - Browser Firefox

**Additional context**
forecast.json(txt) attached

![Forecast](https://user-images.githubusercontent.com/47734099/109784269-30320100-7c0b-11eb-90e6-7478951a1c11.jpg)
[forecast.txt](https://github.com/poblabs/weewx-belchertown/files/6074893/forecast.txt)

**Comment by norecords** [comment]
The forecast.json you share say that Wednesday 3 March 2021 08:00:29 GMT the query have no data for **current** weather  (I don't know why..) but have all the rest of queries success with data but not rendered by the template due to some statements that missing somewhere in case of error code: warn_no_data like I add in my PR for AQI data.
Maybe should all Aeris queries need this check

**Comment by gand07** [comment]
Hi
Thanks for looking.
When I upgraded to the latest version,, I got 11 of these errors for each archive cycle. 
```
weewx[24015] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
weewx[24015] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
```
I changed the radius to 200 mi and these errors went away. 

I have these settings:
aqi_enabled = 0
aqi_location_enabled = 0

But it seems that the AQI is astill beeing checked..

Rgds
Gert

**Comment by michaelundwd** [comment]
I had some interaction with Aeris with regard to the missing AQI data, where they pointed out that they were dependent on a number of suppliers for their data, over which they had no control.  
Your original forecast.json as supplied had no current data that subsequently causes belchertown.js.tmpl to come to a grinding halt in your browser.  (Uncaught TypeError: Cannot read property 'icon' of undefined)
Because of the unpredictable nature of the data we get from an external source, I agree with @norecords that we should check all Aeris data for warn_no_data so that weewx will continue gracefully rather than failing catastrophically as it does now.  He has made a good start with the aqi data checking that I had hoped to test before suggesting the same methods are applied elsewhere.

**Comment by gand07** [comment]
Hi
Thanks for the update to both of you.

Gert

**Comment by norecords** [comment]
@gand07 have you reached the maximum of api call ?

**Comment by norecords** [comment]
@gand07 you should delete json/forecast.json in weewx output directory to force new forecast query

**Comment by gand07** [comment]
@norecords Currently I have 651 hits remaining and I have just deleted forecast.json. Can I refresh the forcast or must I wait until the hour.
Gert

**Comment by norecords** [comment]
That will query new forecast on next report

**Comment by norecords** [comment]
@gand07 you have forecast back but still no current data
http://billeder.de/json/forecast.json
I saw you are on an island in Denmark look like Aeris have no data for your location
when I try this call 
`https://api.aerisapi.com/observations/closest?p=55.00780843457908,14.973713678063094&format=json&filter=allstations&limit=1&client_id=xxxx&client_secret=xxxx`
got no data ..

**Comment by norecords** [comment]
if you add &radius=100km parameter you get Malmo sturup Airport METAR

**Comment by norecords** [comment]
@gand07 If you have skill in code modification you can try this in belchertown.py
@ line # 1259
`"https://api.aerisapi.com/observations/%s,%s?&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

after that, delete json/forecast.json
then restart weewx
and wait for next report or do wee_reports

**Comment by gand07** [comment]
Done

**Comment by gand07** [comment]
I have this in the log
```
Mar  4 11:05:22 v220201144152132366 weewx[288753] INFO user.belchertown: No cloud cover data from Aeris weather
Mar  4 11:05:24 v220201144152132366 weewx[288753] message repeated 10 times: [ INFO user.belchertown: No cloud cover data from Aeris weather]
and line 1259 in Belchertown.py:
`"https://api.aerisapi.com/observations/%s,%s?&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`
```
Gert

**Comment by gand07** [comment]
Hi
I have just installed a Raspberry at my home to test the forecast. My cottage(billeder.de) is around 300 km from my home.
My home installation seems to work and using current the 
[forecast.txt](https://github.com/poblabs/weewx-belchertown/files/6082742/forecast.txt)
airport. I have attached the json(txt)
Gert

**Comment by gand07** [comment]
I'm using the same version of Belchertown on both systems.
Gert

**Comment by norecords** [comment]
Sorry should look like this
`"https://api.aerisapi.com/observations/closest? p=%s,%s&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

**Comment by gand07** [comment]
Updated Belchertown.py with:
`"https://api.aerisapi.com/observations/closest? p=%s,%s&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

Deleted .forecast.json and restarted weewx

**Comment by michaelundwd** [comment]
Your home forecast.json uses a different location to your cottage, confirming the results are location-dependent.  I assume that the problems at your cottage are recent and that it was giving data before.  If so, it confirms my point about Aeris dependency on external sources for its data, over which they have no control.  In his reply about AQI data, Aeris Support stated

"Thanks for the additional details!  It's likely that one of our data providers was experiencing an outage, in which case air quality data in that region would be unavailable when using the closest action.  While there is not much we can do about outages from our data sources, we may look into adding more providers in the future.  "

I will take a look at @norecords checks for AQI data and see how to make weewx behave more gracefully when it has no data.  Like Covid19, I think we will have to learn to live with warn_no_data!

**Comment by gand07** [comment]
@michaelundwd, Yes it has been working fine until 2-3 days ago. I'm just wondering why data is not picked up by a close metar, EKRN. At my home location aeris will pick EKCH giving the current condition
Gert

**Comment by norecords** [comment]
> Updated Belchertown.py with:
> `"https://api.aerisapi.com/observations/closest? p=%s,%s&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

there is no space between `closest?` and `p=%s,%s` see my edited replied

**Comment by gand07** [comment]
Updated with this:
`"https://api.aerisapi.com/observations/closest?p=%s,%s&radius=100km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

delete json/forecast.json
restart weewx

Gert

**Comment by michaelundwd** [comment]
I have just entered the co-ordinates for bornholm airport (metar EKRN) into  the Aeris API wizard, and it returns warn_no_data.  That is unlikely for an airport, but I suspect the Aeris data is not coming direct from there, but via an intermediary, who may have a problem.  I think this is an Aeris data issue, not a weewx one.

**Comment by norecords** [comment]
@gand07 try to change your latitude to 55.093 and longitude to 14.719 in your weewx.conf then delete forecast.json and restart weewx

**Comment by norecords** [comment]
that's Rønne coordinates

**Comment by norecords** [comment]
or you can have `55.009` and `14.973` but you have to set the radius to 150km
`"https://api.aerisapi.com/observations/closest?p=%s,%s&radius=150km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

**Comment by gand07** [comment]
Hi
Thanks for spending time here.
I have inserted the coordinate for EKRN and extended the radius to 150km and then 300km. Still no current data.
Gert

**Comment by michaelundwd** [comment]
What co-ordinates did you use for EKRN?  I tried 55.063, 14.761 in the Aeris api wizard and found Malmo at 105kms

**Comment by gand07** [comment]
Hi
In WeeWx I have this:
   ```
 # Latitude in decimal degrees. Negative for southern hemisphere
    latitude = 55.093
    # Longitude in decimal degrees. Negative for western hemisphere.
    longitude = 14.719
```
and the string in Belchertown.py:

`"https://api.aerisapi.com/observations/closest?p=%s,%s&radius=300km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`

Gert

**Comment by michaelundwd** [comment]
I have just put those parameters into the aeris api wizard

https://www.aerisweather.com/wizard/api/options?endpoint=observations&action=closest&options.loc.value=55.093%2C14.719&options.format=json&options.parameters.radius=25mi&options.parameters.filter=allstations&options.parameters.limit=10

and got this result - maybe they are back on line again.  Try clearing your forecast.json again to force a reload

[EKRN.txt](https://github.com/poblabs/weewx-belchertown/files/6083611/EKRN.txt)

**Comment by michaelundwd** [comment]
You can also type EKRN into the wizard instead of the co-ordinates - same result

**Comment by norecords** [comment]
just get back to initial query in belchertown.py
`"https://api.aerisapi.com/observations/%s,%s?&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`
data are back for your location but you will still warns for cloudbase as there are not present in json response...

**Comment by gand07** [comment]
Working, Working, Working
Thanks  a lot.

Still have this in the log:

```
Mar  4 13:45:27 v220201144152132366 weewx[291758] INFO user.belchertown: No cloud cover data from Aeris weather
Mar  4 13:45:28 v220201144152132366 weewx[291758] message repeated 10 times: [ INFO user.belchertown: No cloud cover data from Aeris weather]
```
Anything to do about that?

Gert

**Comment by michaelundwd** [comment]
It's there 11 times because belchertown.py is called 1 times by weewx every archive cycle.  This won't go away until the skin has a graceful way of checking for data items.
Pleased you are back on the air!
