### ISSUE TITLE
ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range

### ISSUE THREAD

**Issue by martenhinrichs** [poblabs/weewx-belchertown#624]
I updated to the latest master.zip (1.3b1) . And now the forecast section of the skin doesnt be generated. Failure is "ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range" In the forecast.json i see " "aqi": [{"success": true, "error": {"code": "warn_no_data", "description": "Valid request. No results available based on your query parameters."}" But when i browse "https://www.aerisweather.com/weather/local/de/rostock/forecast/2021/03/08" , airquality is available but only with "Source: CAMS" and no nearby stations.

And if i disable aqi the config it is ignored and forecast dont be generated.

https://gw.martenhinrichs.de/

**Comment by martenhinrichs** [comment]
Here are the forecast.json and weewx.conf

[config.zip](https://github.com/poblabs/weewx-belchertown/files/6100637/config.zip)

**Comment by michaelundwd** [comment]
This is the same error that was raised in #609 and addressed in PR #610, that has not yet been merged into the master.
However, given that weewx and the aeris aqi wizard are both returning warn_no_data, but the aeris website is showing a value for Rostock points to a data supply problem with aeris.  I suggest raising a support ticket with aeris to see what they have to say about the lack of data.  I have found them very responsive when I have raised issues.

**Comment by martenhinrichs** [comment]
Yes you are right. i have raised a ticket at aeris.

Location: 54.100700,12.085913

error
https://api.aerisapi.com/airquality/closest?p=54.100700,12.085913&format=json&radius=25mi&limit=10&client_id=17baXAXaKs4srKUmGmfo3&client_secret=e6KmPC3fF6YXgMckFTZv5MN9YFrUWDEBu9mbgmCu

{
    "success": true,
    "error": {
        "code": "warn_no_data",
        "description": "Valid request. No results available based on your query parameters."
    },
    "response": []
}

ok
https://api.aerisapi.com/airquality/54.100700,12.085913?&format=json&client_id=17baXAXaKs4srKUmGmfo3&client_secret=e6KmPC3fF6YXgMckFTZv5MN9YFrUWDEBu9mbgmCu

{
    "success": true,
    "error": null,
    "response": [
        {
            "id": null,
            "loc": {
                "lat": 54.1007,
                "long": 12.085913
            },
            "place": {
                "name": "rostock",
                "state": "mv",
                "country": "de"
            },
            "periods": [
                {
                    "dateTimeISO": "2021-03-08T13:00:00+01:00",
                    "timestamp": 1615204800,
                    "aqi": 32,
                    "category": "good",
                    "color": "00E400",
                    "method": "airnow",
                    "dominant": "o3",
                    "pollutants": [
                        {
                            "type": "o3",
                            "name": "ozone",
                            "valuePPB": 35,
                            "valueUGM3": 70,
                            "aqi": 32,
                            "category": "good",
                            "color": "00E400"
                        },
                        {
                            "type": "pm2.5",
                            "name": "particle matter (<2.5µm)",
                            "valuePPB": null,
                            "valueUGM3": 2.4,
                            "aqi": 10,
                            "category": "good",
                            "color": "00E400"
                        },
                        {
                            "type": "pm10",
                            "name": "particle matter (<10µm)",
                            "valuePPB": null,
                            "valueUGM3": 3.8,
                            "aqi": 3,
                            "category": "good",
                            "color": "00E400"
                        },
                        {
                            "type": "co",
                            "name": "carbon monoxide",
                            "valuePPB": 130,
                            "valueUGM3": 149,
                            "aqi": 1,
                            "category": "good",
                            "color": "00E400"
                        },
                        {
                            "type": "no2",
                            "name": "nitrogen dioxide",
                            "valuePPB": 2,
                            "valueUGM3": 3.76,
                            "aqi": 2,
                            "category": "good",
                            "color": "00E400"
                        },
                        {
                            "type": "so2",
                            "name": "sulfur dioxide",
                            "valuePPB": 1,
                            "valueUGM3": 3.668,
                            "aqi": 1,
                            "category": "good",
                            "color": "00E400"
                        }
                    ]
                }
            ],
            "profile": {
                "tz": "Europe/Berlin",
                "sources": [
                    {
                        "name": "CAMS"
                    }
                ],
                "stations": null
            }
        }
    ]
}

**Comment by martenhinrichs** [comment]
Hi ,

i created a ticket on aeris.this was the answer in my ticket.
#####
Thanks for reaching out to AerisWeather!  The closest action returns data from the nearest air quality station.  If none are nearby, then no data will be returned.  When querying by location as you did in your second example, the data is interpolated.  This is often the best option when checking locations that may not have an active air quality station nearby.

Please let me know if you have any follow up questions!  
Thanks,
Nate
AerisWeather Support Team
#####
If this is true, in my opinion it is better if we have the choice to get the AQI per switch in skin.conf.

example:

aqi_aeris_data_source = "nearby"

nearby= aeris api option for aqi (default - searches aqi station nearby location)
location=aeris api option  for aqi (data is interpolated, no nearby stations)

**Comment by michaelundwd** [comment]
I got  the following reply when I submitted a similar request a few days ago:

"It's likely that one of our data providers was experiencing an outage, in which case air quality data in that region would be unavailable when using the closest action.  While there is not much we can do about outages from our data sources, we may look into adding more providers in the future.  "

An alternative approach to your suggestion would be for the skin to try the nearby option first and if that fails to automatically try the location one.  The nearby option provides the location of the nearest sensor that some people display.  The location option provides the name of the place, in your case Rostock.

**Comment by norecords** [comment]
it's look like a problem with EEA source (European Environment Agency) that is used by OpenAQ and Aeris. There's no data available since yesterday midday.
OpenAQ still provide the last measurement but not Aeris that stuck with no data.

**Comment by norecords** [comment]
I add a graph on my [skin](https://meteo.correns.org/#qualite_air) to track OpenAQ / EEA data

**Comment by martenhinrichs** [comment]
@michaelundwd Yes your Suggestion is smarter. I reopened the ticket at aeris. i will see what they say. There are definetly aqi stations (from goverment) in my area. thanks

**Comment by norecords** [comment]
I'm still having no aqi data from aeris, neither for big city like Paris, or Marseille with the closet query..
When querying from OpenAQ have got only on record per day from state sensors (EEA) but have normal data from PurpleAir sources
