### ISSUE TITLE
Mqtt : display bug internal temperature

### ISSUE THREAD

**Issue by olpayras** [poblabs/weewx-belchertown#625]
607 / 5000
Résultats de traduction
Hello everybody,

After a long time of absence I installed the 1.2 skin and noticed a bug on the MQTT dynamic display.

The internal temperature changes to 0 ° C when the display is updated.

I initially thought of a sensor problem, but I see this problem on 2 different stations.

Here are the links:

https://meteo.payrastre.fr and https://puylaurens.payrastre.fr

You will see when connecting that the indoor temperature is ok then when updated by MQTT the value goes to 0. Also can be seen on this capture.

![Capture](https://user-images.githubusercontent.com/49792600/110477270-40525080-80e3-11eb-85c8-37ed85bd8f02.JPG)

If you have a solution, I'm interested.

Thank you in advance for your help.

Olivier.

**Comment by ArendPWS** [comment]
Did you do the right install? Your skin versions show Belchertown 1.2, but the sites you mention show elements of the unreleased master 1.3b1 (like AQI and the new forecast).

**Comment by olpayras** [comment]
Thanks for your reply.

I always custom Pat's Belchertown skin stable to my usage such I have customised Reports page, ReNaSS earthquake and last AQI. No more changes I didn't changed anything for weather forecast. On 1.2 we already can use Aeris forecast.

**Comment by ArendPWS** [comment]
> I always custom Pat's Belchertown skin stable to my usage such I have customised Reports page, ReNaSS earthquake #561 and last AQI issue #610 . No more changes I didn't changed anything for weather forecast. On 1.2 we already can use Aeris forecast.

Can't help you if you didn't do a proper install. Good luck.

**Comment by norecords** [comment]
Hi @olpayras long time haven't read you ;)
Can you enable Belchertown skin debug and look at Mqtt messages if value is right

**Comment by olpayras** [comment]
Hi @norecords,

Thanks for your reply. Yes it was a long time I haven't come here, cause a lot of work :(. Here's what I have in my debug console :

```
MQTT: {"pressure_mbar": "1001.0", "inTemp_C": "19.499999999999996", "inTempBatteryStatus": "0.0", "dateTime": "1615405848.0", "altimeter_mbar": "1022.5689473079897", "maxSolarRad_Wpm2": "0.0", "rainRate_mm_per_hour": "0.0", "hourRain_cm": "0.0", "rain24_cm": "0.0", "dayRain_mm": "0.0", "usUnits": "16.0"} belchertown.js:37:17
MQTT: {"dateTime": "1615405856.0", "maxSolarRad_Wpm2": "0.0", "rainRate_mm_per_hour": "0.0", "hourRain_cm": "0.0", "rain24_cm": "0.0", "dayRain_mm": "0.0", "usUnits": "16.0", "windSpeed_kph": "0.0", "windGust_kph": "0.0", "windBatteryStatus": "0.0"} belchertown.js:37:17
MQTT: {"dateTime": "1615405863.0", "maxSolarRad_Wpm2": "0.0", "rainRate_mm_per_hour": "0.0", "hourRain_cm": "0.0", "rain24_cm": "0.0", "dayRain_mm": "0.0", "usUnits": "16.0", "rain_total": "34.515", "rainBatteryStatus": "0.0", "rain_cm": "0.0"} belchertown.js:37:17
MQTT: {"dateTime": "1615405870.0", "maxSolarRad_Wpm2": "0.0", "rainRate_mm_per_hour": "0.0", "hourRain_cm": "0.0", "rain24_cm": "0.0", "dayRain_mm": "0.0", "usUnits": "16.0", "windSpeed_kph": "0.0", "windGust_kph": "0.0", "windBatteryStatus": "0.0"} belchertown.js:37:17

There are values in InTemp.
```

**Comment by ArendPWS** [comment]
@olpayras

Can you try the fix in PR #631?

**Comment by olpayras** [comment]
Thanks @ArendPWS 

Tried and approved :)

**Comment by ArendPWS** [comment]
Great! Can you give some feedback in the PR? That way Pat will know it's ok to merge. Thank you. 👍
