### ISSUE TITLE
Colour-coded record tables

### ISSUE THREAD

**Issue by jdb235** [poblabs/weewx-belchertown#629]
:bulb: **The Idea**

Firstly, I'm really enjoying the skin, great work! 

I'd quite like to enhance the records page by adding colour coded tables of month-by-month records, such as those seen [here](http://dajda.net/history.html). The code for this is already available as part of the fuzzy-archer skin [here](https://github.com/brewster76/fuzzy-archer/tree/master/bin/user) (historygenerator.py) but I'm not sure exactly how to incorporate it into my current Belchertown setup. How would I go about doing this? Is this something that could potentially be incorporated into a future release?

**Comment by poblabs** [comment]
This has been asked before and I think because of licensing it wasn't available - if memory serves me. You're welcome to add it yourself manually since the skin is open source

**Comment by rodolfozan** [comment]
This is relatively easy --> [coloured tables](https://station.wetter-beuren.de/archiv/). Copy historygnerator.py to your weewx-user directory or install the fuzzy archer skin and adjust your skin.conf accordingly.

**Comment by c0by85** [comment]
@rodolfozan Please explain a little more, looked at your site and find it quite suitable. How can I easily intigrate it to my page.

**Comment by rodolfozan** [comment]
@c0by85 
Install the fuzzy-archer skin.
Copy the content from the attached file to belcherown skin.conf.
Add "user.historygenerator.MyXSearch" to search_list_extensions Variable under [Cheetahgenerator] in belchertown skin.conf. 
`search_list_extensions = user.belchertown.getData, user.historygenerator.MyXSearch
[skin.conf.txt](https://github.com/poblabs/weewx-belchertown/files/6164182/skin.conf.txt)
Use the Variables in belchertown skin: 
`<h3>$BootstrapLabels.history_tables.max_temp</h3>
$max_temp_table `

**Comment by rodolfozan** [comment]
Install the fuzzy-archer skin.
Add the following Stanza to belcherown skin.conf.
`[BootstrapLabels]

    #
    # Labels specific to the Bootstrap template
    #

    [[headings]]
        front_page  = Wetter
        stats       = Historische Werte
        history     = Historie
        news        = News
        about       = About
        last_update = zuletzt aktualisiert am

    [[timespans]]
        day      = Letzte 24 Std.
        today    = Heute            # today = any time since midnight
        week     = Woche
        month    = Monat
        year     = Jahr
        ever     = Seit Beginn

    [[status]]
        latitude       = Latitude:
        longitude      = Longitude:
        altitude       = Altitude:
        station_uptime = Station uptime:
        server_uptime  = Server uptime:

    [[history_tables]]
        min_temp  = Minimum Temperatur
        max_temp  = Maximum Temperatur
        avg_temp  = Durchschnitt Temperatur
		avg_rh    = Durchschnitt Luftfeuchtigkeit
		max_wind_gust = Maximum Böen Geschwindigkeit
		max_wind  = Maximum Wind Geschwindigkeit
		dir_wind  = Wind Richtung
        rain      = Niederschlag
        rain_days = Regentage
        NOAA      = Archiv Daten

    [[minmax]]
        min = Min
        max = Max

############################################################################################

[HistoryReport]

    #
    # Settings for the HTML month/year colour coded summary table generator
    #

    # minvalues, maxvalues and colours and fontColours should contain the same number of elements.
    #
    # For example,  the [min_temp] example below, if the minimum temperature measured in
    # a month is between -50 and -10 (degC) then the cell will be shaded in html colour code #0029E5.
    #
    # colours = background colour
    # fontColours = foreground colour [optional, defaults to black if omitted]

    # Default is temperature scale
    minvalues = -50, -10, -5, 0,  5, 10, 15, 20, 25, 30, 35
    maxvalues = -10, -5,   0, 5, 10, 15, 20, 25, 30, 35, 60
    colours =   "#0029E5", "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
    fontColours =   "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF", "#FFFFFF"
    monthnames = Jan, Feb, Mär, Apr, Mai, Jun, Jul, Aug, Sep, Okt, Nov, Dez

    # Restrict the size of the table by ignoring everything before startdate
    # Specify in unix epoch time. e.g. 1325376000 is 1-Jan-2012
    #startdate = 1325376000

    # The Raspberry Pi typically takes 15+ seconds to calculate all the summaries with a few years of weather date.
    # refresh_interval is how often in minutes the tables are calculated.
    refresh_interval = 60

    [[min_temp]]
        obs_type = outTemp                 # obs_type can be any weewx reading
        aggregate_type = min               # Any of these: 'sum', 'count', 'avg', 'max', 'min'

        summary_column = true
        summary_heading = Min

    #
    # Can also use these aggregate_types:  'max_ge', 'max_le', 'min_le', 'sum_ge' to count days
    # where an observation is ge: greater of equalto, or le: lessthan or equal to a threshold value
    # To specify this threshold, use: aggregate_threshold = [value], [units]
    #
    # e.g Specify temperature threshold of 20C:  aggregate_threshold = 20, degree_C
    #

    [[max_temp]]
        obs_type = outTemp
        aggregate_type = max

        summary_column = true
        summary_heading = Max

    [[avg_temp]]
        obs_type = outTemp
        aggregate_type = avg

        summary_column = true
        summary_heading = Ds
		
	[[avg_rh]]
        obs_type = outHumidity
        aggregate_type = avg
		units = "%"
		minvalues = 10, 20, 30, 40, 50, 60, 70, 80, 90
		maxvalues = 20, 30, 40, 50, 60, 70, 80, 90, 100
		colours   =   "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D"
		fontColours =   "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF"

        summary_column = true
        summary_heading = Ds
		
	[[max_wind_gust]]
        obs_type = windGust
        aggregate_type = max
		units = "km/h"
		minvalues = 2, 8, 13, 21, 30, 41, 52, 63, 76, 89, 104
		maxvalues = 8, 13, 21, 30, 41, 52, 63, 76, 89, 104, 180
		colours   =   "#0029E5", "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
		fontColours =   "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF", "#FFFFFF"

        summary_column = true
        summary_heading = Max
		
	[[max_wind]]
        obs_type = windSpeed
        aggregate_type = max
		units = "km/h"
		minvalues = 2, 8, 13, 21, 30, 41, 52, 63, 76, 89, 104
		maxvalues = 8, 13, 21, 30, 41, 52, 63, 76, 89, 104, 180
		colours   =   "#0029E5", "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
		fontColours =   "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF", "#FFFFFF"

        summary_column = true
        summary_heading = Max
		
	[[dir_wind]]
        obs_type = windDir
        aggregate_type = avg
		units = "°"
		minvalues = 0, 45, 90, 135, 180, 225, 270, 315
		maxvalues = 45, 90, 135, 180, 225, 270, 315, 360
		colours   =   "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
		fontColours =   "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF", "#FFFFFF"

        summary_column = true
        summary_heading = Ds

    [[rain]]
        obs_type = rain
        aggregate_type = sum

        minvalues = 0, 2.5, 5.0, 7.5, 10.0, 15.0   # Override default temperature colour scheme with rain specific scale
        maxvalues = 2.5, 5.0, 7.5, 10.0, 15.0, 100.0
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total

    [[rain_days]]
        obs_type = rain
        units = Tage                        # Override default table units label
        aggregate_type = sum_ge
        aggregate_threshold = 1, mm
        minvalues = 0, 6, 12, 18, 24, 30   # Override default temperature colour scheme with rain specific scale
        maxvalues = 6, 12, 18, 24, 30, 50
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total


    [[NOAA]]
        #
        # Creates a table of links to NOAA reports with the tag $NOAA_table
        # Comment out [[NOAATable]] if you do not need this.
        #

        # Where to find the NOAA files and how they are named
        # Uses Python datetime convention (docs.python.org/2/library/datetime.html):
        # %Y = YYYY, %y = YY, %m = MM, etc.
        #
        year_filename = ../NOAA/NOAA-%Y.txt
        month_filename = ../NOAA/NOAA-%Y-%m.txt

`

Add "user.historygenerator.MyXSearch" to search_list_extensions Variable under [Cheetahgenerator] in belchertown skin.conf. 
`search_list_extensions = user.belchertown.getData, user.historygenerator.MyXSearch`

Use the Variables in belchertown skin: 
`<h3>$BootstrapLabels.history_tables.max_temp</h3>
$max_temp_table`

**Comment by jdb235** [comment]
Brilliant, thanks - I had been trying unsuccessfully to get it working for a few days but now I have. One question - currently the NOAA reports section of the new tables is pointing towards /records/NOAA/NOAA-YYYY-MM.txt when the files are actually located in /NOAA/NOAA-YYYY-MM.txt. Where is this defined/where do I change it?

**Comment by rodolfozan** [comment]
This can be adjusted under the [[NOAA]] Stanza:

year_filename = ../NOAA/NOAA-%Y.txt
month_filename = ../NOAA/NOAA-%Y-%m.txt

**Comment by jdb235** [comment]
Thanks, I thought I tried that but I must have got it slightly wrong!

**Comment by sally-woolrich** [comment]
I have the Bootstrap skin as well as Belchertown, and had to tweak the Python code to get the colour coding to work correctly.  Specifically I found that firstly I needed to modify the colours in the [[rain]] section to better cater for the amounts where I live in the UK, and I amended the code that coloured the summary cells for days of rain and for mm of rain so that the summary cells are not all the same colour.

        mult = 1
        if summary is True:
            if unit_type == "count":
                mult = 10
            if unit_type == "mm":
                mult = 5

        if value is not None:
            for c in cellColours:
#                if (unit_type == "mm" or unit_type == "count") and summary is True:
#                    txt2 = "          : value = {}, min = {}, max = {}, background = {}".format( value, c[0], c[1], c[2])
#                    log.info (txt2 )
                if (value >= (mult*float(c[0]))) and (value < (mult*float(c[1]))):
                    cellText += '" style="background-color:%s; color:%s"' % (c[2], c[3])
#                    if (unit_type == "mm" or unit_type == "count") and summary is True:
#                        log.info( "          :    Found" )
                    break

            formatted_value = format_string % value
            cellText += '> %s </div>\n' % formatted_value

        else:
            cellText += '">-</div>\n'

**Comment by James-76** [comment]
Thanks for this.  I use to use Bootstrap but liked the Belchertown layout and graphs.

I used these details to integrate his

**Comment by Sebeck81** [comment]
Hello,
 
I would also like to set up the tables for myself. I use weewx with the Belchertown skin. 

Unfortunately it doesn't quite work. Is it correct that I have to install fuzzy-archer first? I followed the instructions: 
 
https://github.com/poblabs/weewx-belchertown/issues/629
 
Unfortunately it didn't work. Do you have any tips for me?

For me it's just displayed on the page

$BootstrapLabels.history_tables.max_temp
 
Thank you very much and kind regards
Sebastian
