### ISSUE TITLE
PR #580 Broke InTemp Max/Min record

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#630]
Hello.
I have inTemp inside records table. It used to work fine until PR#580 e613319  Now style is mixed.
![image](https://user-images.githubusercontent.com/4549674/110865193-febbd400-82a1-11eb-9be6-4f0529e92329.png)
Thanks in advanced!

**Comment by ArendPWS** [comment]
@HoracioDos

Can you try the fix in PR #633?

**Comment by HoracioDos** [comment]
I'll try it tonight. We still have good weather. It is barbecue day!
Thanks!!

**Comment by HoracioDos** [comment]
Hello. I've applied this change and It works.
![image](https://user-images.githubusercontent.com/4549674/111169254-8c890f00-8581-11eb-9c8e-02a8ff7bc36a.png)
Thanks!
