### ISSUE TITLE
Observations not working: visibility and aqi (Aeris)

### ISSUE THREAD

**Issue by alexdelprete** [poblabs/weewx-belchertown#634]
Hello,

I upgraded to latest dev version (1.3b1) and reconfigured options in weewx.conf (there was a new section with all defaults so I made sure to "migrate" all my existing settings from 1.2), I had some minor problems with duplicate settings and some brackets from some options that I had to remove, but I guess with the final version things will be sorted out.

I use MQTT websockets, my lan mosquitto instance bridges the WF topic to a public broker, and belchertown pulls data from it, everything seems to be working fine also on that side with 1.3b1.

The only problem I noticed is that the observations "visibility" and aqi are not working, I'm using Aeris, and forecasts and other values are working ok (cloud_cover for example). I don't know what to look for in order to debug it, so I left debug on for now, in case you need to debug.

Thanks for any help on this, and thanks to Pat and other devs for this amazing skin. :)

Link to the site: https://www.iconoclasti.com/meteo/

Screenshot:
![image](https://user-images.githubusercontent.com/7027842/111030727-288d0c00-8404-11eb-9f5e-ffc26f4a16b6.png)

**Comment by ArendPWS** [comment]
The link you provided doesn't show the Belchertown skin.

**Comment by alexdelprete** [comment]
Sorry, link corrected.

**Comment by ArendPWS** [comment]
Do you have  forecast_aeris_use_metar = 1 in your skin.conf?

**Comment by norecords** [comment]
Take care that OVH cloud Data Center in Strasbourg burned in fire and Western Europe AQI is available sometimes !
take a look [here](https://www.eea.europa.eu/data-and-maps/explore-interactive-maps/up-to-date-air-quality-data) if your station is back but we have to wait fore some days that everything get back to the normal state

**Comment by norecords** [comment]
also AQI Data in Italy have very poor station data share with EEA, so you might change `aqi_url` in `belchertown.py` to 
```
            aqi_url = (
                "https://api.aerisapi.com/airquality/%s,%s?format=json&radius=20mi&limit=1&client_id=%s&client_secret=%s"
                % (latitude, longitude, forecast_api_id, forecast_api_secret)
            )
```
that will  use CAMS (Copernicus Atmosphere Monitoring Service) instead of closet official station.

**Comment by alexdelprete** [comment]
> Do you have forecast_aeris_use_metar = 1 in your skin.conf?

Yes.

![image](https://user-images.githubusercontent.com/7027842/111041068-ac5fec00-8436-11eb-8fad-bf20e44d6acb.png)

**Comment by alexdelprete** [comment]
> Take care that OVH cloud Data Center in Strasbourg burned in fire and Western Europe AQI is available sometimes !
> take a look [here](https://www.eea.europa.eu/data-and-maps/explore-interactive-maps/up-to-date-air-quality-data) if your station is back but we have to wait for some days that everything get back to the normal state
> [post](https://www.datacenterknowledge.com/ovh/ovh-races-restore-services-affected-data-center-fire)

But that wouldn't explain why the **visibility** observation is N/A too.

**Comment by alexdelprete** [comment]
I uninstalled Belchertown, and cleaned all config in weewx.conf.
Then I reinstalled it and reconfigured it from scratch.

Now **visibility** is working again, but not AQI. I'll disable it for now, will retry it in the official 1.3 version, once released.

@norecords: I tried the URL, but it didn't work.

![image](https://user-images.githubusercontent.com/7027842/111042966-2c3e8400-8440-11eb-9ace-33ee89ed4bf9.png)

**Comment by ArendPWS** [comment]
@norecords

> Take care that OVH cloud Data Center in Strasbourg burned in fire and Western Europe AQI is available sometimes !
> take a look [here](https://www.eea.europa.eu/data-and-maps/explore-interactive-maps/up-to-date-air-quality-data) if your station is back but we have to wait for some days that everything get back to the normal state
> [post](https://www.datacenterknowledge.com/ovh/ovh-races-restore-services-affected-data-center-fire)

Everything here (Station Enschede-Winkelhorst. / Netherlands) has been working like a charm over the last week, . 👍

**Comment by alexdelprete** [comment]
Now I also see AQI. I guess it's Aeris...I just needed to wait some time after the reinstallation.

![image](https://user-images.githubusercontent.com/7027842/111053316-28702900-8463-11eb-86d3-b4dc7cfe3340.png)

**Comment by norecords** [comment]
@alexdelprete I can see on your site that last earthquake is very far from your location, have you set `earthquake_maxradiuskm` in your skin.conf

**Comment by alexdelprete** [comment]
Yes, I like seeing what's going in the world. :)

**Comment by norecords** [comment]
^^

**Comment by ArendPWS** [comment]
@alexdelprete

Nice to read everything seems to be working for you. If this solved your problems would you be so kind to close this issue?

**Comment by alexdelprete** [comment]
Sorry, I forgot to close the issue. Will do it immediately.
