### ISSUE TITLE
How to fix my chart

### ISSUE THREAD

**Issue by c0by85** [poblabs/weewx-belchertown#635]
Hello, first of all thanks for the awesome WeeWx skin. I want to customize my chart, but can't find a proper way to do it. I've also found the problem [#187](https://github.com/poblabs/weewx-belchertown/issues/187). The mentioned possibilities do not work. I want my chart with the rain just like the one above from 00:00 to 23:59. No matter what I set it doesn't work.

![image](https://user-images.githubusercontent.com/25707747/111031042-eebd0500-8405-11eb-8601-a69817258cbf.png)

```
WeeWX version: 4.4.0
Belchertown Skin Version: 1.2
```

```
[[[chart3rain]]
title = Regenmenge Stunde
xAxis_groupby = hour
[[[rainTotal]]]
name = Regenmenge
type = column
```

I have also tried a separate `time_length = today`.

**Comment by roe-dl** [comment]
Do you want a line graph or a bar graph for rain?

**Comment by c0by85** [comment]
I want that the rain chart to end at 23:59 even if it is only 10:00. The wind chart is also always created from 00:00 - 23:59.

I hope this makes my request more understandable. The end of the rain chat must be 23:59 and not only until then where data exists.

![image](https://user-images.githubusercontent.com/25707747/111036610-54b68600-8420-11eb-9dee-abee4bff8599.png)

The rain chart shows the summed rainfall of an hour from the current day.

**Comment by ArendPWS** [comment]
@c0by85

I haven't been able to create the type of chart you request with any of the current Belchertown (pre)releases (1.2 and 1.3b1). However lately I have been experimenting with some new code for these type of charts and that gives me this result for today:

![neerslag (1)](https://user-images.githubusercontent.com/67259651/111133058-601dc480-857a-11eb-9018-05254eea9a8c.png)

Maybe it will be posible with a future release of Belchertown, @michaelundwd is also working on this type of charts so keep an :eye: on his progress.
