### ISSUE TITLE
AQI Guage Graph

### ISSUE THREAD

**Issue by ijg** [poblabs/weewx-belchertown#637]
This isn't a bug, nor a feature request.  I'm not sure where I should have posted it.

I'm trying to use the AQI information from the skin in a graph.  Can I somehow access the variable?  I'd like to create a guage graph, 1-500 with the current AQ color coded.  I can figure out most of it, but can't figure out how to get the variable since I don't believe it's stored in the database. (??)

And finally, the guage defaults to 100, am I correct that yAxis_Max=500 would be how I'd change that default?

Thank you..

Iain Grant
http://ajaxweather.com

**Comment by norecords** [comment]
This actually exist in the skin -> https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#aqi-chart

**Comment by ijg** [comment]
Thank you.  Perfect.
