### ISSUE TITLE
beaufort_category - weewx warning

### ISSUE THREAD

**Issue by alexdelprete** [poblabs/weewx-belchertown#638]
I enabled beaufort_category and I followed the instructions, adding this to weewx.conf:
beaufort = prefer_hardware under [StdWXCalculate][[Calculations]]

It's working fine, I see the category under the wind values, but in weewx log I see this warning:

> INFO weewx.wxxtypes: Type beaufort has been deprecated. Use unit beaufort instead.

I found this in weewx 4.2 upgrade notes: http://www.weewx.com/docs/upgrading.htm#Type_beaufort_deprecated

![image](https://user-images.githubusercontent.com/7027842/111053448-222e7c80-8464-11eb-99b3-ee9e9158f7ac.png)

I guess adding that line to weewx.conf is not needed anymore, but I preferred to ask here.

my site: https://www.iconoclasti.com/meteo/

**Comment by uajqq** [comment]
I left that in place to improve backwards compatibility -- many users are still on old versions of weewx, and since this error doesn't break anything, I figured it was safest to leave it alone.

**Comment by alexdelprete** [comment]
> I left that in place to improve backwards compatibility -- many users are still on old versions of weewx, and since this error doesn't break anything, I figured it was safest to leave it alone.

I understand your choice, makes sense. That means weewx > 4.2  don't need to add beaufort = prefer_hardware to the config, correct? So in the docs/notes it would be enough to specify that the line has to be added only if weewx < 4.2.

I'll remove the line, since I'm on 4.4. Thanks for the help.
