### ISSUE TITLE
Vigilance  / warning on Belchertown skin 

### ISSUE THREAD

**Issue by steflp** [poblabs/weewx-belchertown#639]
Hello, 
:bulb: I see this   Warning  'Vigilance jaune vent violent valable jusqu'au 14 mars 2021 16:00' on belchertown skin forked.
from  @norecords

**HELP WANTED**
I dont know how to do this  but I m interesting to implement it
How to do this  ?
Can someone help me ?
thanks

**Comment by norecords** [comment]
@steflp you need to adapt your skin.conf 
https://github.com/poblabs/weewx-belchertown/blob/82890bd37b97f27f06fbf7bbccf7c7e504624632/skins/Belchertown/skin.conf#L237-L242
```
        # General Forecast translations
...
        alert_in_effect             = valable jusqu'au
...
```

https://github.com/poblabs/weewx-belchertown/blob/82890bd37b97f27f06fbf7bbccf7c7e504624632/skins/Belchertown/skin.conf#L458-L514

```
        # Aeris European Alert Codes. From https://www.aerisweather.com/support/docs/aeris-maps/reference/alert-types/
        forecast_alert_code_AW_WI_MN        = "Minor Wind"
        forecast_alert_code_AW_WI_MD        = "Vigilance jaune vent violent"
        forecast_alert_code_AW_WI_SV        = "Vigilance orange vent violent"
        forecast_alert_code_AW_WI_EX        = "Vigilance rouge vent violent"
        forecast_alert_code_AW_SI_MN        = "Minor Snow/Ice"
        forecast_alert_code_AW_SI_MD        = "Vigilance jaune neige-verglas"
        forecast_alert_code_AW_SI_SV        = "Vigilance orange neige-verglas"
        forecast_alert_code_AW_SI_EX        = "Vigilance rouge neige-verglas"
        forecast_alert_code_AW_TS_MN        = "Minor Thunderstorm"
        forecast_alert_code_AW_TS_MD        = "Vigilance jaune orages"
        forecast_alert_code_AW_TS_SV        = "Vigilance orange orages"
        forecast_alert_code_AW_TS_EX        = "Vigilance rouge orages"
        forecast_alert_code_AW_LI_MN        = "Minor Lightning"
        forecast_alert_code_AW_LI_MD        = "Vigilance jaune foudre"
        forecast_alert_code_AW_LI_SV        = "Vigilance orange foudre"
        forecast_alert_code_AW_LI_EX        = "Vigilance rouge foudre"
        forecast_alert_code_AW_FG_MN        = "Minor Fog"
        forecast_alert_code_AW_FG_MD        = "Vigilance jaune brouillard"
        forecast_alert_code_AW_FG_SV        = "Vigilance orange brouillard"
        forecast_alert_code_AW_FG_EX        = "Vigilance rouge brouillard"
        forecast_alert_code_AW_HT_MN        = "Minor High Temperature"
        forecast_alert_code_AW_HT_MD        = "Vigilance jaune canicule"
        forecast_alert_code_AW_HT_SV        = "Vigilance orange canicule"
        forecast_alert_code_AW_HT_EX        = "Vigilance rouge canicule"
        forecast_alert_code_AW_LT_MN        = "Minor Low Temperature"
        forecast_alert_code_AW_LT_MD        = "Vigilance jaune grand froid"
        forecast_alert_code_AW_LT_SV        = "Vigilance orange grand froid"
        forecast_alert_code_AW_LT_EX        = "Vigilance rouge grand froid"
        forecast_alert_code_AW_CE_MN        = "Minor Coastal Event"
        forecast_alert_code_AW_CE_MD        = "Vigilance jaune vagues-submersion"
        forecast_alert_code_AW_CE_SV        = "Vigilance orange vagues-submersion"
        forecast_alert_code_AW_CE_EX        = "Vigilance rouge vagues-submersion"
        forecast_alert_code_AW_FR_MN        = "Minor Forest Fire"
        forecast_alert_code_AW_FR_MD        = "Moderate Forest Fire"
        forecast_alert_code_AW_FR_SV        = "Servere Forest Fire"
        forecast_alert_code_AW_FR_EX        = "Extreme Forest Fire"
        forecast_alert_code_AW_AV_MN        = "Minor Avalanche"
        forecast_alert_code_AW_AV_MD        = "Moderate Avalanche"
        forecast_alert_code_AW_AV_SV        = "Servere Avalanche"
        forecast_alert_code_AW_AV_EX        = "Extreme Avalanche"
        forecast_alert_code_AW_RA_MN        = "Minor Rainfall"
        forecast_alert_code_AW_RA_MD        = "Moderate Rainfall"
        forecast_alert_code_AW_RA_SV        = "Servere Rainfall"
        forecast_alert_code_AW_RA_EX        = "Extreme Rainfall"
        forecast_alert_code_AW_FL_MN        = "Minor Flooding"
        forecast_alert_code_AW_FL_MD        = "Vigilance jaune inondation"
        forecast_alert_code_AW_FL_SV        = "Vigilance orange inondation"
        forecast_alert_code_AW_FL_EX        = "Vigilance rouge inondation"
        forecast_alert_code_AW_RF_MN        = "Minor Rain Flooding"
        forecast_alert_code_AW_RF_MD        = "Vigilance jaune pluie-inondation"
        forecast_alert_code_AW_RF_SV        = "Vigilance orange pluie-inondation"
        forecast_alert_code_AW_RF_EX        = "Vigilance rouge pluie-inondation"
        forecast_alert_code_AW_UK_MN        = "Minor Unknown"
        forecast_alert_code_AW_UK_MD        = "Moderate Unknown"
        forecast_alert_code_AW_UK_SV        = "Servere Unknown"
        forecast_alert_code_AW_UK_EX        = "Extreme Unknown"
```

**Comment by ddperso** [comment]
My weewx.conf (or skin.conf) :

Translations in # Aeris European Alert Codes. From
https://www.aerisweather.com/support/docs/aeris-maps/reference/alert-types/
                forecast_alert_code_AW_WI_MN        = "Soyez attentif au
vent,"
                forecast_alert_code_AW_WI_MD        = "Soyez attentif au
vent,"
                forecast_alert_code_AW_WI_SV        = "Alerte au vent,"
                forecast_alert_code_AW_WI_EX        = "Alerte : rafales de
vent importantes,"
                forecast_alert_code_AW_SI_MN        = "Soyez attentif à la
neige et verglas,"
                forecast_alert_code_AW_SI_MD        = "Soyez attentif à la
neige et verglas,"
                forecast_alert_code_AW_SI_SV        = "Alerte à la neige et
verglas,"
                forecast_alert_code_AW_SI_EX        = "Alerte : neige et
verglas importants,"
                forecast_alert_code_AW_TS_MN        = "Soyez attentif aux
orages,"
                forecast_alert_code_AW_TS_MD        = "Soyez attentif aux
orages,"
                forecast_alert_code_AW_TS_SV        = "Alerte aux orages,"
                forecast_alert_code_AW_TS_EX        = "Alerte : risque
d'orages important,"
                etc.....

Translations in # General Forecast translations
                forecast_header              = "Prévisions
&nbsp;&nbsp;&nbsp;"
                daily_forecast               = Prévision du jour
                *alert_in_effect              = "alerte effective jusqu'au"*
                forecast_last_updated        = Dernière mise à jour le
                forecast_interval_caption    = "Intervalle de prévisions en
heures :"

Parameters in # Forecast defaults



* forecast_enabled = 1            forecast_provider = "aeris"
forecast_api_id = "xxxxxxxxxxxxxxxxxxx"            forecast_api_secret =
"xxxxxxxxxxxxxxxxxxxxxxxxx"*
            forecast_units = "ca"
            forecast_interval_hours = 0
           # values are 0,1,3 or 24
            forecast_lang = "fr"
            forecast_stale = 3540
            forecast_aeris_use_metar = 1
            *forecast_alert_enabled = 1*
            *forecast_alert_limit = 5                   (You can have 5
alerts)*
            forecast_show_daily_forecast_link = 0
            forecast_daily_forecast_link = ""

**Comment by ddperso** [comment]
sorry @norecords 
I haven't seen your answer...

**Comment by ddperso** [comment]
Sorry @norecords 

I didn't see your answer

**Comment by steflp** [comment]
Hello
 all this  are ok .. but 
 line 76  :  
`forecast_alert_enabled=1` 
was zero  ;-(

**Comment by norecords** [comment]
@ddperso no problem, yours was more pertinent has @steflp see `forecast_alert_enabled=1`
8)

**Comment by steflp** [comment]
in fact , Im not "alone"  .. ( cc @ddperso  ! 
Next is Ozone from aqi api  .... 
and river too  ... ( I live near "Quimperlé" , Finistere and  Laita river is often in alert mode)
have a nice day

**Comment by norecords** [comment]
@steflp you should close this issue if everything works for you.

**Comment by steflp** [comment]
oups  ! Ok  !
