### ISSUE TITLE
Wind gauge mapped to different observations

### ISSUE THREAD

**Issue by alexdelprete** [poblabs/weewx-belchertown#640]
I don't know if it's an enhancement request, maybe it's already doable with current functionalities but I don't know how to do it.

Basically, I want to map the wind gauge to different values. Currently, these are the sensors/values I have from my WeatherFlow Tempest:

>  **windSpeed** = wind_avg.ST-000xxxxx.obs_st
    **windDir** = wind_direction.ST-000xxxxx.obs_st
    **currentWindSpeed** = wind_speed.ST-000xxxxx.rapid_wind
    **currentWindDir** = wind_direction.ST-000xxxxx.rapid_wind

Right now, windSpeed and windDir are used, but I'd like to use currentWindSpeed and currentWindDir.

Can I configure belchertown to achieve this?

Thanks for any help.
https://www.iconoclasti.com/meteo/

**Comment by uajqq** [comment]
I'm not sure there's a way to configure that easily without delving into the code. You could adjust belchertown.js.tmpl to achieve that effect.

**Comment by alexdelprete** [comment]
So opening this as an enhancement request was the proper choice. Would it be hard to make that configurable?

Thanks a lot for the help.
