### ISSUE TITLE
Can't seem to switch to Metric for Forecasts.

### ISSUE THREAD

**Issue by ijg** [poblabs/weewx-belchertown#642]
I understand this was asked before, but the question was 'closed'.  Unfortunately the 2 links that may have had the information I need are now 404.

https://github.com/poblabs/weewx-belchertown/issues/312

Hello, I'm having the same issue with units. I've tried everything but the forecast keeps appearing in US. There are 2 links at the top of this thread that may have helped but they are both dead.

Thank you.

Ig.
www.ajaxweather.com

**Comment by norecords** [comment]
What have you tried ?
`forecast_units = ca` in skin.conf and delete json/forecast.json to force download new forecast. Wait for next report or manually do `wee_update`

**Comment by ijg** [comment]
Brilliant.  Worked like a charm.  I honestly thought I'd read everything possible to figure this out, but I certainly missed that one.

Thank you again!  Greatly appreciated.

**Comment by norecords** [comment]
Great,
you may close your issues if everything all right

**Comment by iiseppi** [comment]
> Ig.
> [www.ajaxweather.com](http://www.ajaxweather.com)

Sorry to hijack this, but could not find your email/contact anywhere. 
Can you share the page template you use in your records page? Would love to get those colourful min/max/ave temps table.

**Comment by c0by85** [comment]
@iiseppi look here [https://github.com/poblabs/weewx-belchertown/issues/629#issuecomment-801932363](https://github.com/poblabs/weewx-belchertown/issues/629#issuecomment-801932363)
