### ISSUE TITLE
How to fix my chart V2 // got 8 days on charts with time_length = weeks_ago

### ISSUE THREAD

**Issue by c0by85** [poblabs/weewx-belchertown#644]
Hello,

maybe someone can help me (again). My chart shows more data than it should. Last week (01.03. - 07.03.) the data was displayed correctly (i think so).

```
[lastweek]
time_length = weeks_ago
time_ago = 1
[...]
[[chart3rain]]
title = Regenmenge Tag
xAxis_groupby = day
xAxis_categories = 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'
[[[rainTotal]]]
name = Regenmenge
type = column
```

![image](https://user-images.githubusercontent.com/25707747/111295755-07b6f780-864c-11eb-978a-6db5d075e22a.png)

And here the chart again without the `xAxis_categories = 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'`.
The beginning and end of the week would be 08.03. - 14.03., the 15th already belongs to the next week.

![image](https://user-images.githubusercontent.com/25707747/111296861-426d5f80-864d-11eb-9204-f048c8d5f30d.png)

```
WeeWX version: 4.4.0
Belchertown Skin Version: 1.2
```

**Comment by c0by85** [comment]
Got it by myself... Workaround...

```
xAxis_groupby = day
xAxis_categories = 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So', 'Mo'
```

But time is longer than 1 week.

```
time_length = weeks_ago
time_ago = 1
```

**Comment by norecords** [comment]
@c0by85 can you reopen that issue and change (for example) the title to "got 8 days on charts with time_length = weeks_ago" and share your full graph.conf, I think that an issue that need to be resolved.

**Comment by c0by85** [comment]
@norecords done

graph.conf

```
# Global Chart Defaults
# These are fallback options that charts will use if an option is not defined. 
aggregate_type = None
time_length = 90000 # Last 25 hours
type = line
colors = "#7cb5ec, #b2df8a, #f7a35c, #8c6bb1, #dd3497, #e4d354, #268bd2, #f45b5b, #6a3d9a, #33a02c"
tooltip_date_format = "LLL"

[lastweek]
time_length = weeks_ago
time_ago = 1
[...]
[[chart3rain]]
title = Regenmenge Tag
xAxis_groupby = day
xAxis_categories = 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'
[[[rainTotal]]]
name = Regenmenge
type = column
```

**Comment by norecords** [comment]
I've tried this:
```
[lastweek]
    time_length = weeks_ago
    time_ago = 1
    show_button = true
    tooltip_date_format = "LLLL"
    aggregate_type = max
    aggregate_interval = 3600 # 1 hour
    gapsize = 3600000 # 1 hour in milliseconds

    [[outtemp]]
        title = Out temperature
         [[[outTemp]]]
             name = Out Temp
```
and lastweek.json stop at sunday 23:00
but if use `xAxis_groupby = day` like this:
```
[lastweek]
    time_length = weeks_ago
    time_ago = 1
    show_button = true
    tooltip_date_format = "LLLL"
    aggregate_type = max
    aggregate_interval = 3600 # 1 hour
    gapsize = 3600000 # 1 hour in milliseconds
    xAxis_groupby = day

    [[outtemp]]
        title = Out temperature
         [[[outTemp]]]
             name = Out Temp
```
I've got 8 values in series data like on screenshots

**Comment by norecords** [comment]
@c0by85 try this:
```
[lastweek]
    time_length = weeks_ago
    time_ago = 1
    show_button = true
    tooltip_date_format = "LLLL"
    aggregate_interval = 86400 # 24 hour
    gapsize = 86400000 # 24 hour in milliseconds
    aggregate_type = max
    type = column

    [[outtemp]]
        title = Rain last week
         [[[rain]]]
             name = rain
```
We have to set `aggregate_interval = 86400 # 24 hour`, `gapsize = 86400000 # 24 hour in milliseconds` and `aggregate_type = max`

**Comment by c0by85** [comment]
thx, looks better, but not when you group by day with an categorie.

```
xAxis_groupby = day
xAxis_categories = 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'
```

![image](https://user-images.githubusercontent.com/25707747/111868886-d48ea400-897c-11eb-9732-ed539c8de6d3.png)

**Comment by norecords** [comment]
you don't need to that, days are ever grouped and show date under columns

**Comment by c0by85** [comment]
that is correct. however, instead of the date, i would like to have the day of the week. how can i change this?

**Comment by norecords** [comment]
In Highcharts this can be done like this
```
    xAxis: {
      labels: {
        formatter: function() {
          return Highcharts.dateFormat('%a', this.value);
        }
      }
    }
```
but seems not implemented in Belchertown.

**Comment by norecords** [comment]
You should want to try this PR https://github.com/poblabs/weewx-belchertown/pull/650

**Comment by michaelundwd** [comment]
Which version of the belchertown skin are you using? 1.2 or 1.3b1?  There is a bug in the 1.3b1 version that may explain why you are getting an extra day at the end of your charts.  You could try my PR #649 that addresses this.

**Comment by norecords** [comment]
@michaelundwd I've tried on both version, anyway your PR #649 solved that issue!

**Comment by norecords** [comment]
@c0by85 you can add PR #649 to your setup and use the code of your first comment.

**Comment by c0by85** [comment]
@norecords Give me an hint to do this without crashing my customized stable 1.2. I could run 2 versions or?

Does it work with [Belchertown] and [Belchertowndev] maybe?
