### ISSUE TITLE
Issues displaying aqi and radiation observations

### ISSUE THREAD

**Issue by dgunnell** [poblabs/weewx-belchertown#648]
Running Weewx 4.4.0 with skin 1.2.  I added station_observations for pm2_5 and radiation.  Both new fields display correctly on web page load or refresh but as soon as there is an MQTT update the pm2_5 value changes to 32768 and the radiation number changes to something else.

Here is my weewx.conf entry for observations:

station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, pm2_5, radiation

I am using the extended weewx database schema and the aqi fields in the database are being populated by addon weewx-airlink which is based on the purple air addon.  The airlink version supports the Davis Airlink AQI module.

I have tried to debug this but I have not been able to find out why MQTT code is overwriting those fields

**Comment by ArendPWS** [comment]
Can you provide a link to your website so we can check your MQTT payload?

**Comment by dgunnell** [comment]
Yeah I forgot to include that:

www.gricewoodsweather.com

**Comment by ArendPWS** [comment]
Interesting, how many underscores can you put in an observation (with unit):

"pm1_0_microgram_per_meter_cubed": "0.0", "pm2_5_microgram_per_meter_cubed": "0.0", "pm2_5_aqi_aqi": "0.0", "pm2_5_aqi_color_aqi_color": "32768.0", "pm10_0_microgram_per_meter_cubed": "0.0", "pm1_0_1m_microgram_per_meter_cubed": "0.0", "pm2_5_1m_microgram_per_meter_cubed": "0.0", "pm10_0_1m_microgram_per_meter_cubed": "0.0", "pm2_5_1m_aqi_aqi": "0.0", "pm2_5_1m_aqi_color_aqi_color": "32768.0", "pm2_5_nowcast": "0.4816980000000002", "pm2_5_nowcast_aqi": "1.6666666666666667", "pm2_5_nowcast_aqi_color": "32768.0", "pm10_0_nowcast": "3.95"

Now we need to sort out which pm2_5 observation to use. But lets start with cursing at all those developers.

**Comment by ArendPWS** [comment]
@dgunnell,

Which pm2_5 do you have in mind to observe?

pm2_5_microgram_per_meter_cubed?

or

pm2_5_aqi_aqi?

or

pm2_5_1m_microgram_per_meter_cubed?

or

pm2_5_1m_aqi_aqi?

or

pm2_5_nowcast?

or

pm2_5_nowcast_aqi?

**Comment by dgunnell** [comment]
pm2_5_aqi_aqi

**Comment by ArendPWS** [comment]
Something is not quite right with your install or configuration. When I look at your weewx_data.json it shows no values for pm1_0, pm2_5 and pm10_0 in "unit_label". Installing weewx-airlink has added pm1_0_1m, pm2_5_1m and pm10_0_1m but they are also blank:

"pm10_0": "", "pm10_0_1m": "", "pm1_0": "", "pm1_0_1m": "", "pm2_5": "", "pm2_5_1m": ""

 pm1_0, pm2_5 and pm10_0 should at least show something like this example from my configuration:

"pm10_0": "\u00b5g/m\u00b3", "pm1_0": "\u00b5g/m\u00b3", "pm2_5": "\u00b5g/m\u00b3"

There are more issues, e.g. there is no entry for pm2_5_aqi which needs the "unit" aqi.

**Comment by ArendPWS** [comment]
@dgunnell,

At his point I can't help you any further. I get the impression that the weewx-airlink extension locks out Belchertown from retreiving the required pm unit_labels. Perhaps you should contact the developer of weewx-airlink about this or maybe someone else has some time to solve this for you. Below I give you the link to your weewx_data.json so you can check for yourself that the required pm unit_labels (used by MQTT for updating the observations) are missing.

[http://www.gricewoodsweather.com/json/weewx_data.json](http://www.gricewoodsweather.com/json/weewx_data.json)

I have created some improved code for sorting out the right observations from the MQTT payload. I am going to test this for a while. Maybe at some point I will create a PR for this improvement.

**Comment by ArendPWS** [comment]
@dgunnell,

I found this PR that was merged after the release of the 1.2 skin version you are currently using. Can you apply this PR yourself (or install/upgrade to 1.3b1)? This should probably fix the json issue.

PR #419

**Comment by dgunnell** [comment]
Upgraded to 1.3b1 only change I noticed was the µg/m³ is now being displayed correctly but on MQTT update still being overwritten with 32768 for the value field.  I noticed in the json for current for pm2_5 is correct even after MQTT updates.  I also had weather34 skin running for a console display and completely disabled that (removed all entries from weewx.conf) but didnt seem to make a difference.  There is a sample report from airlink code that can be accessed from http://www.gricewoodsweather.com/weewx/airlink/ and the airlink reports seem to be running fine.

**Comment by ArendPWS** [comment]
Solving your issue(s) requires a few steps. It is good to see the unit_labels are now (partially) correctly added to weewx_data.json. Next step will be to get the observation pm2_5_aqi into Belchertown (and weewx_data.json). The last and third step will require my updated code for sorting out the MQTT payload (as mentioned before, testing now). I will now try to figure out if and how we can add pm2_5_aqi into Belchertown.

**Comment by ArendPWS** [comment]
Can you change pm2_5 into pm1_0 so I can check some readings?
Like this:

station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, pm1_0, radiation

**Comment by ArendPWS** [comment]
You requested to observe pm2_5_aqi_aqi. This means the observation is an aqi index with unit label "AQI".

Follow these steps:

[1] Add this to your weewx.conf:

	[StdReport]
		
		[[Defaults]]
			
			[[[Units]]]
				
				# The following section sets what unit to use for each unit group.
				# NB: The unit is always in the singular. I.e., 'mile_per_hour',
				# NOT 'miles_per_hour'
				[[[[Groups]]]]
					
					air_quality_index = aqi
					air_quality_color = aqi_color
				
				# The following section sets the formatting for each type of unit.
				[[[[StringFormats]]]]
					
					aqi = %.0f
					aqi_color = %.0f

[2] Download and install this version of airlink.py. The original file has some non-critical issues regarding default_unit_label_dict. If everything is ok, I will create an PR.

[https://github.com/ArendPWS/weewx-airlink/blob/master/bin/user/airlink.py](https://github.com/ArendPWS/weewx-airlink/blob/master/bin/user/airlink.py)

[3] Download and install this version of belchertown.js.tmpl. Improves MQTT payload checking.
If everything is ok, I will create an PR.

[https://github.com/ArendPWS/weewx-belchertown/blob/testing/skins/Belchertown/js/belchertown.js.tmpl](https://github.com/ArendPWS/weewx-belchertown/blob/testing/skins/Belchertown/js/belchertown.js.tmpl)

[4] Change your station observations into this:

station_observations = barometer, dewpoint, outHumidity, rainWithRainRate, pm2_5_aqi, radiation

[5] Restart weewx and give some feedback on the results.

**Comment by dgunnell** [comment]
Ok I have been out all morning, I will make all those changes later today and let you know once its up and running.

**Comment by dgunnell** [comment]
I applied all the changes and its up and running.  Compared AQI number with my Davis Airlink weatherlink app and it matches.

**Comment by ArendPWS** [comment]
@dgunnell,

Thank you for the feedback. When you opened this issue you also mentioned something being not right with the radiation observation. Perhaps the behaviour you noticed is just the way WeeWX/Belchertown/MQTT works?

I will create a PR in the weewx-airlink repo to fix the issue mentioned earlier and create a PR for this skin to update belchertown.js.tmpl (maybe this will be interesting too for @olpayras).

**Comment by dgunnell** [comment]
radiation is now also being displayed correctly rather it be from page refresh or MQTT update.  Thanks for the efforts to fix this issue.
