### ISSUE TITLE
Earthquakes using ReNaSS 

### ISSUE THREAD

**Issue by sally-woolrich** [poblabs/weewx-belchertown#656]
Although the documentation suggests those of us in Europe can use ReNaSS as the earthquake server, the code doesn't exist at present - there is just the code for USGS and GeoNet. 

WeeWX is v4.4.0, skin is v1.2.

https://muchty-weather.org.uk/weather/belchertown/about/

```
            if self.generator.skin_dict['Extras']['earthquake_server'] == "USGS":
                earthquake_url = "http://earthquake.usgs.gov/fdsnws/event/1/query?limit=1&lat=%s&lon=%s&maxradiuskm=%s&format=geojson&nodata=204&minmag=2" % ( latitude, longitude, earthquake_maxradiuskm )
            elif self.generator.skin_dict['Extras']['earthquake_server'] == "GeoNet":
                earthquake_url = "https://api.geonet.org.nz/quake?MMI=4"
            earthquake_is_stale = False
```

Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**

**Link to your website (IMPORTANT)**

**Version of the skin you're using**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by steepleian** [comment]
Hi,
I am also UK based. I am using this service on the skin I maintain: -

https://www.emsc-csem.org/service/rss/rss.php?typ=emsc

You can see it working at https://claydonsweather.org.uk

There are popup links at the base of all the dashboard modules, the
earthquake module is bottom right. I have users on all continents and it
works in all locations from the feedback I get. Should be easy to
incorporate in the Belchertown skin as well.

Ian

**Comment by ddperso** [comment]
Included in last release v1.2b2

**Comment by norecords** [comment]
@sally-woolrich you have to use the latest dev by installing https://github.com/poblabs/weewx-belchertown/archive/refs/heads/master.zip 
or you can manually add this PR https://github.com/poblabs/weewx-belchertown/pull/602/files to your setup.

**Comment by sally-woolrich** [comment]
That's working fine now, thanks.

**Comment by norecords** [comment]
Good to know, thanks.
