### ISSUE TITLE
Earthquakes using BGS

### ISSUE THREAD

**Issue by sally-woolrich** [poblabs/weewx-belchertown#659]
:bulb: **The Idea**

I'm using the French earthquake server and it knows nothing about the UK.  I've looked at the one Claydons Weather uses, but what I really want is to be able to use the BGS, to get the UK information that's in an orange Alert banner on their website:

https://www.bgs.ac.uk/

To that end I've contacted them, hopefully they will be back soon with the necessary information.

:hammer: **Breaking Feature**

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by swfrx** [comment]
It would be very nice to be able to get BGS earthquake info in the skin
