### ISSUE TITLE
Feature Request - Provide an option for graphs on the Graphs page to be calendar based or rolling 

### ISSUE THREAD

**Issue by biltmorelaker** [poblabs/weewx-belchertown#66]
Provide an option for graphs on the Graphs page to be calendar based or rolling based either on pull down choice on the page or user specified variable (using tags, like “charts_day = today or rolling” and “charts_year = calendar or rolling”).

Currently the main page shows graphs since midnight, as does the Today choice on the Graphs page. The Week and Month choice on the Graphs page are the most recent 7 and 30 days respectively, while the Year choice is since Jan 1.

Users should be able to choose to display either the most recent 24 hours, 7 days, 30 days, 365 days (for day, week, month, year respectively) or since midnight, since beginning of week, beginning of month, beginning of year).

**Comment by poblabs** [comment]
This is now in place, set for 1.0 release. Can be tested now if you install the latest development branch. The option, and instructions are in the skin.conf under `time_length`

**Comment by poblabs** [comment]
This will be available in skin 1.0
