### ISSUE TITLE
Wrong observation type choosen from MQTT message

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#660]
**First step**
from skin.conf:
```
    station_observations = "barometer","dewpoint","outHumidity","rainWithRainRate","radiation","UV","dayET","GTS"
```
Please be aware of the last item in the list.

The created index.html contains:
```
<tr><td class='station-observations-label'>GTS</td><td><span class=GTS>253,4 Kd</span><!-- AJAX --></td></tr>
```

**Describe the bug**
After reload of the the page, the correct value for "GTS" is displayed, but after update by MQTT the value of "GTSdate" is displayed instead of "GTS". See screenshot below. 

**Link to your website (IMPORTANT)**
[Woellsdorf-Wetter](https://www.woellsdorf-wetter.de)

**Version of the skin you're using**
1.2

**To Reproduce**
In belchertown.js.tmpl in function update_current_wx(data), line 1779 says:
```
if (mqttdata.startsWith(thisElementClass)) {
```
As both observeration types "GTS" and "GTSdate" start with the same characters, `startsWith(thisElementClass)` chooses the wrong observation type in this case. It chooses "GTSdate" instead of "GTS". May be that depends on the order of the elements within the MQTT message, but that is outside control of the user.

**Expected behavior**
* using the value of "GTS" instead of "GTSdate" in this case
* comparing the observation type name up to the underscore in general 

**Screenshots**
<img width="325" alt="station_obs_html" src="https://user-images.githubusercontent.com/73126506/113281187-831fd680-92e5-11eb-9685-0f4299d79e90.png">

**Device Information (please complete the following information):**
 - Device: independent of device
 - OS: independent of OS
 - Browser independent of browser
 - Version 1.2

**Additional context**
None.

**HELP WANTED**
Unfortunately my knowledge of JavaScript is very limited.

**Comment by poblabs** [comment]
This isn't a bug of the skin, but rather you need to tell MQTT what observation to send using the custom MQTT extension overrides. Please check documentation of the MQTT extension for this.

**Comment by roe-dl** [comment]
I am not sure.

Indeed you can change the name of an observation type, but that seems to me like a work-around. And it can break other applications.

Always, if you have got several observation types with similar labels, then they will be mixed up. You cannot drop one of them, if you need them all.

I am by no means an expert for JavaScript, but I would think of replacing line 1779 of belchertown.js.tmpl by something like this:
```
var will_update = mqttdata.startsWith(thisElementClass+"_");
if (!will_update) will_update = mqttdata == thisElementClass;
if (will_update) {
```

I will check if that works with my installation.

**Comment by ArendPWS** [comment]
@poblabs, @roe-dl

I created PR #653 to solve this kind of issues.

**Comment by roe-dl** [comment]
I guess, because of that PR #653 we can close this issue.
