### ISSUE TITLE
Stuck at Connecting to Weather Station

### ISSUE THREAD

**Issue by Overcon** [poblabs/weewx-belchertown#663]
Hi,

I have been trying to get MQTT working with Weewx and the Belchertown skin for weeks and I am stuck. I thought I had everything working, but I can't get past the page sitting at connecting when trying to update the data. I will try and provide as much data as I can, but I am not a technical writer, so if you need anything to help me get this working just ask!

I am running Weewx 4.5.1 on a Raspberry Pi 4. I am using Ubuntu Server 20.04.
I have the Belchertown Skin and running the site on Apache2. I have the webpage running a signed SSL certificate.
I have a virtual server running Ubuntu 20.04 that has the MQTT service running.
Weewx is writing to MySQL on a separate Virtual server.

I followed your guide at https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/

**System information MQTT Server /etc/mosquitto/conf.d/myconfig.conf:**
persistence false

# mqtt
listener 1883
protocol mqtt

# websockets
listener 9001
protocol websockets

allow_anonymous true
password_file /etc/mosquitto/passwd

acl_file /etc/mosquitto/acl

**ACL file:**

# Allow anonymous access to the sys
topic read $SYS/#

# Allow anonymous to read weather
topic read weather/#

# weewx readwrite to the loop
user weewxmqttuser
topic weather/#

**Netstat results on MQTT server:**

sudo netstat -tulpn | grep 1883
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      757/mosquitto
tcp6       0      0 :::1883                 :::*                    LISTEN      757/mosquitto

sudo netstat -tulpn | grep 9001
tcp6       0      0 :::9001                 :::*                    LISTEN      757/mosquitto

**UFW Rules:**
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    Anywhere
[ 2] 80/tcp                     ALLOW IN    Anywhere
[ 3] 443/tcp                    ALLOW IN    Anywhere
[ 4] 8883/tcp                   ALLOW IN    Anywhere
[ 5] 9001/tcp                   ALLOW IN    Anywhere
[ 6] 1883                       ALLOW IN    Anywhere
[ 7] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
[ 8] 80/tcp (v6)                ALLOW IN    Anywhere (v6)
[ 9] 443/tcp (v6)               ALLOW IN    Anywhere (v6)
[10] 8883/tcp (v6)              ALLOW IN    Anywhere (v6)
[11] 9001/tcp (v6)              ALLOW IN    Anywhere (v6)
[12] 1883 (v6)                  ALLOW IN    Anywhere (v6)

**Firewall Rules from Router:**

  |   |   | WAN | TCP | * | * | WAN address | 1883 | 192.168.1.14 | 1883 | MQTT Protocol |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   | WAN | TCP | * | * | WAN address | 9001 | 192.168.1.14 | 9001 | Websocket |  
  |   |   | WAN | TCP | * | * | WAN address | 8883 | 192.168.1.14 | 8883 | MQTT Listener |  

**sudo tail -f /var/log/mosquitto/mosquitto.log**

1617572146: Opening ipv4 listen socket on port 1883.
1617572146: Opening ipv6 listen socket on port 1883.
1617572146: Opening websockets listen socket on port 9001.
1617572291: New connection from 192.168.1.12 on port 1883.
1617572291: New client connected from 192.168.1.12 as weewx_2d392566 (p2, c1, k60, u'weewxmqttuser').
1617572291: Client weewx_2d392566 disconnected.
1617572311: New connection from 192.168.1.12 on port 1883.
1617572311: New client connected from 192.168.1.12 as weewx_a7c2cafa (p2, c1, k60, u'weewxmqttuser').
1617572311: Client weewx_a7c2cafa disconnected.
1617572332: New connection from 192.168.1.12 on port 1883.
1617572332: New client connected from 192.168.1.12 as weewx_2d574dc3 (p2, c1, k60, u'weewxmqttuser').

**On the RBPI running weewx I see:**
Apr  4 15:16:16 weewx-pi weewx[2455] INFO weewx.restx: MQTT: Published record 2021-04-04 15:16:00 MDT (1617570960)

**On the Weewx PI, the config files:**

    [[MQTT]]
        server_url = mqtt://weewxmqttuser:PASSWORD@192.168.1.14:1883
        topic = weather
        unit_system = US
        binding = archive, loop
        aggregation = aggregate

    [[Belchertown]]
        skin = Belchertown
        HTML_ROOT = /var/www/maladomini.net/
        [[[Extras]]]
            earthquake_enabled = 1
            earthquake_server = USGS
            forecast_enabled = 1
            forecast_api_id = REDACTED
            forecast_api_secret = REDACTED
            googleAnalyticsId = REDACTED
        mqtt_websockets_host = "192.168.1.14"
        mqtt_websockets_port = 9001
        mqtt_websockets_enabled = 1
        mqtt_websockets_ssl = 0
        mqtt_websockets_topic = "weather/loop"
        disconnect_live_website_visitor = 1800000

[Engine]

    # The following section specifies which services should be run and in what order.
    [[Services]]
        prep_services = weewx.engine.StdTimeSynch
        data_services = ,
        process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate
        xtype_services = weewx.wxxtypes.StdWXXTypes, weewx.wxxtypes.StdPressureCooker, weewx.wxxtypes.StdRainRater, weewx.wxxtypes.StdDelta
        archive_services = weewx.engine.StdArchive
<.restx.StdWOW, weewx.restx.StdAWEKAS, user.mqtt.MQTT, user.owm.OpenWeatherMap, user.wcloud.WeatherCloud
        report_services = weewx.engine.StdPrint, weewx.engine.StdReport

**Syslog when I restart the Weewx Service:**

Apr  4 15:43:25 weewx-pi systemd[1]: Stopping LSB: weewx weather system...
Apr  4 15:43:25 weewx-pi weewx[2840]:  * Stopping weewx weather system weewx
Apr  4 15:43:25 weewx-pi weewx[2790] INFO __main__: Received signal TERM (15).
Apr  4 15:43:25 weewx-pi weewx[2790] INFO weewx.engine: Main loop exiting. Shutting engine down.
Apr  4 15:43:25 weewx-pi weewx[2790] INFO weewx.engine: Shutting down StdReport thread
Apr  4 15:43:26 weewx-pi weewx[2790] INFO user.gw1000: Gw1000Collector thread has been terminated
Apr  4 15:43:26 weewx-pi weewx[2790] INFO __main__: Terminating weewx version 4.5.1
Apr  4 15:43:30 weewx-pi weewx[2840]: .   ...done.
Apr  4 15:43:30 weewx-pi systemd[1]: weewx.service: Succeeded.
Apr  4 15:43:30 weewx-pi systemd[1]: Stopped LSB: weewx weather system.
Apr  4 15:43:30 weewx-pi systemd[1]: Starting LSB: weewx weather system...
Apr  4 15:43:30 weewx-pi weewx[2869]:  * Starting weewx weather system weewx
Apr  4 15:43:31 weewx-pi weewx[2880] INFO __main__: Initializing weewx version 4.5.1
Apr  4 15:43:31 weewx-pi weewx[2880] INFO __main__: Using Python 3.8.5 (default, Jan 27 2021, 15:41:15) #012[GCC 9.3.0]
Apr  4 15:43:31 weewx-pi weewx[2880] INFO __main__: Platform Linux-5.4.0-1032-raspi-aarch64-with-glibc2.29
Apr  4 15:43:31 weewx-pi weewx[2880] INFO __main__: Locale is 'C.UTF-8'
Apr  4 15:43:31 weewx-pi weewx[2880] INFO __main__: PID file is /var/run/weewx.pid
Apr  4 15:43:31 weewx-pi weewx[2883] INFO __main__: Using configuration file /home/weewx/weewx.conf
Apr  4 15:43:31 weewx-pi weewx[2883] INFO __main__: Debug is 0
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
Apr  4 15:43:31 weewx-pi weewx[2869]:    ...done.
Apr  4 15:43:31 weewx-pi systemd[1]: Started LSB: weewx weather system.
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: field map (Cut to reduce Clutter)
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: driver version is 0.3.1
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: GW1000 address is 192.168.1.7:45000
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: poll interval is 20 seconds
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: StdConvert target unit is 0x1
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Archive will use data binding wx_binding
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Record generation will be attempted in 'hardware'
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Using archive interval of 60 seconds (specified in weewx configuration)
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: StationRegistry: Station will be registered.
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: Wunderground-RF: Data for station KNMLOVIN14 will be posted
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: PWSWeather: Data for station PWSLOVNM1 will be posted
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: CWOP: Data for station FW9112 will be posted
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: WOW: Data for station [redacted key] will be posted
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: AWEKAS: Data will be uploaded for user [redacted]
**_Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.mqtt: service version is 0.23
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.mqtt: binding to ['archive', 'loop']
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.mqtt: topic is weather
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.mqtt: desired unit system is US
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.mqtt: data will be uploaded to mqtt://weewxmqttuser:xxx@192.168.1.14:1883_**
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.owm: service version is 0.9
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.owm: Data will be uploaded for tinkertown
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.wcloud: service version is 0.13
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.wcloud: Data will be uploaded for id=[redacted]
Apr  4 15:43:31 weewx-pi weewx[2883] INFO __main__: Starting up weewx version 4.5.1
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx'
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.manager: Starting backfill of daily summaries
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.manager: Daily summaries up to date
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.engine: Starting main packet loop.
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: Using 'rainyear' for rain total
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: skipping rain measurement of 0.0: no last rain
Apr  4 15:43:31 weewx-pi weewx[2883] INFO user.gw1000: Skipping lightning count of 0: no last count
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: MQTT: Published record 2021-04-04 15:43:31 MDT (1617572611)
Apr  4 15:43:31 weewx-pi weewx[2883] INFO weewx.restx: Wunderground-RF: Published record 2021-04-04 15:43:31 MDT (1617572611)

**Alas, all I see when I access the website is:**

My Station Weather Conditions
(Just a yellow dot) Connecting to weather station real-time data. Last Updated April 4, 2021, 3:50:00 PM

I would appreciate any help you can provide. I am not a master at Linux, but usually, I can follow guides and find the info on the internet somewhere, but I am stumped on getting this working. I know I am missing something, but I just can't figure it out.

Thank you!

I did a connection from a remote tester on port 9001 and it looks like I connect.

1617585978: New client connected from ::ffff:68.233.158.163 as clientId-K4vLZSaW47 (p1, c1, k60, u'weewxmqttuser').

**Comment by Overcon** [comment]
I was looking over debug mode and I noticed this message. 

Mixed Content: The page at 'https://maladomini.net/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.14:9001/mqtt'. This request has been blocked; this endpoint must be available over WSS.

I don't use LetsEncrypt.

Would you be able to tell me how to set up the MQTT with my signed certificate? Your guide only talks about LetsEncrypt. I think this is probably my issue.

**Comment by roe-dl** [comment]
You are right. If you get the website encrypted by https: you must access the MQTT broker encrypted, too. 'ws' means without encryption. 'wss' is with encryption. And, additionally, the web browser checks the certificate. So you need an "official" certifcate, or you install the certificate of your MQTT broker into your web browser. The latter works for you only, not for other people seeing your website. The certificate of your domain does not work for the MQTT broker if it has another name and/or domain.

**Comment by Overcon** [comment]
Hmm, I have been trying to find a guide to set it up with a CA-signed certificate, not much luck so far.

**Comment by roe-dl** [comment]
I did it that way, that I forwarded the message from the broker within my local network to an open broker outside in the Internet, that uses encryption.

Create a file `/etc/mosquitto/conf.d/mqq_eclipseprojects_io.conf`
```
# Bridge to mqtt.eclipseprojects.io
connection bridge-to-eclipse
address mqtt.eclipseprojects.io
topic "" out 0 weather/loop <xxxxxxxxx>/loop
```
where you replace `<xxxxxxxxx>` by an arbitrary string. 

The Belchertown skin config contains:
```
[StdReport]
    ...
    [[Belchertown]]
        ...
        [[[Extras]]]
            ...
            mqtt_websockets_enabled = 1
            mqtt_websockets_host = mqtt.eclipseprojects.io/mqtt
            mqtt_websockets_port = 443
            mqtt_websockets_ssl = 1
            mqtt_websockets_topic = <xxxxxxxxx>/loop
```
where `<xxxxxxxxx>` is the same arbitrary string as above.

Restart Mosquitto.

Please note that mqtt.eclipseprojects.io/mqtt is - strictly spoken - for test purposes, only. They sometimes use it to test new features or something, and then it does not work. But that are rare events. See their documentation for more details.

**Comment by Overcon** [comment]
I have tried a few guides and they all run similar, and yet don't work. This is even more difficult than enabling STUNNEL for Blue Iris.

All I get now is:

1617708378: Error: Unable to load CA certificates. Check cafile "/etc/mosquitto/certs/mosq_serv.key".
1617708378: OpenSSL Error[0]: error:0B084088:x509 certificate routines:X509_load_cert_crl_file:no certificate or crl found

I am pretty sure it isn't a Belchertown issue, though there is no place in the instruction to put a client key for mosquito, I have to assume it is not required since we are using the ACL method, but all the instructions on setting up SSL with mosquito mention a client key.

I am kind of surprised at the lack of guides for this and it's a bummer, I almost have everything working. I might have to revert to using LetsEncrypt to see if pats instructions work.

**Comment by roe-dl** [comment]
What I read from your log is, that you use a key for a certificate authority. 

There are 3 kinds of files: certificate, certificate authority (CA), and (private) key. They are different.

May be, you want to give it a try and switch of SSL in your own Mosquitto configuration and do as suggested before. If that works, you can go further.

**Comment by Overcon** [comment]
Yeah, I am in the process of removing SSL configurations from the webserver
to see if I can get it working without SSL. Once I get that working, move
to SSL if it is possible. I just don't get way all the tutorials I find to
explain how to generate signed SSL certificates, but Moquitto still fails
with errors reading the certificates. It seems to me that such a widely
used application would have more tutorials online.

A weird thing I was working on this morning while trying to do that is I
can delete every mosquito config file and the application still runs and
still tells me it has duplicate ports, I am thinking there is a default
install in Ubuntu or something that probably isn't helping but I can't find
it.


_________________
- Mitchell Tuckness

**Comment by flygpagen** [comment]
For whatever it is worth... I could in no way get the MQTT function to work as long as I used IP-numbers. The moment I entered addresses instead it started flowing. Have not delved further into this as it is above my knowledge but maybe it is worth a shot?

**Comment by Overcon** [comment]
I thought about that. I added an entry in the hosts file of the Weewx
server for the IP of the MQTT server, so I can ping it by name and entered
the name in the config file. The issue I was having last night while
working on it was not being able to get the Mosquitto application to run
with any certificate combination, it would just come up with the above
error of unable to locate an srl file after reading the server.key file.

If I can't get it to work without the SSL cert, I might try a paid service,
just to see if I can get it working at all, maybe glean some info from
their setup.


_________________
- Mitchell Tuckness

**Comment by flygpagen** [comment]
MQTT is not really a part of the Belchertown skin so perhaps try asking at WXforum.net or the Weewx [usergroup](https://groups.google.com/g/weewx-user). Sorry not to have any more help to give. I struggled a lot getting this to work but when doing the above it just started working and have ever since.

**Comment by Overcon** [comment]
Yeah, It's amazingly difficult, especially trying to do it slightly
different from his setup. I understand, I was just shooting in the dark :)
I did a post on the Wxforum, but no luck with replies so far.


_________________
- Mitchell Tuckness

**Comment by Overcon** [comment]
I got some help and was able to get it working. Amazingly difficult :)

1618313428: Sending CONNACK to weewx_ca82df09 (0, 0)
1618313428: Received PUBLISH from weewx_ca82df09 (d0, q0, r0, m0, 'weather/loop', ... (1263 bytes))
1618313428: Sending PUBLISH to website701008674 (d0, q0, r0, m0, 'weather/loop', ... (1263 bytes))
1618313428: _lws_change_pollfd: wsi 0x55cd205cccd0: fd 12 events 1 -> 5
1618313428: _lws_change_pollfd: wsi 0x55cd205cccd0: fd 12 events 5 -> 1
1618313428: lws_handle_POLLOUT_event: 0x55cd205cccd0: non mux: wsistate 0x20000117, ops ws
1618313428: lws_issue_raw: ssl_capable_write (1284) says 1284
1618313428: Client weewx_ca82df09 closed its connection.

**Comment by Overcon** [comment]
Just an FYI. In order to get this working with CRT's from a CA, not let's encrypt, I was able to run MQTT on a separate server and get Weewx talking to it over SSL.

I installed MQTT on the MQTT server:
_mosquitto_pub version 2.0.10 running on libmosquitto 2.0.10._

Then I copied the certificates I got from my CA. The same certificates I got when I got the cheapo positivessl to secure the weewx webpage running on Apache, including the private key file that was generated with openssl. I put those in the /etc/mosquitto/certs directory.

I also followed this guide to create the server keys for MQTT to use on the MQTT server:

[http://www.steves-internet-guide.com/mosquitto-tls/](url)

The _ca.crt_ is put in /etc/mosquitto/ca_certificates/
The _server.crt_ and the _server.key_ is put in /etc/mosquitto/certs

_openssl genrsa -out client.key 2048

openssl req -new -out client.csr -key client.key

openssl x509 -req -in server.csr
-extfile <(printf "subjectAltName=IP:XXX.XXX.XXX.XXX")
-CA ca.crt
-CAkey ca.key
-CAcreateserial -out server.crt
-days 3600

pass CA - XXXXXX_


I configured the ACL per the instructions in the Belchertown MQTT directions:
_# Allow anonymous access to the sys
# topic read $SYS/#

# Allow anonymous to read weather
topic read weather/#

# weewx readwrite to the loop
user XXXXXX
topic weather/#_

I created a password for the use specified in the acl file.

The MQTT config is put in /etc/mosquitto/conf.d and configured as: The logging statements are optional. I used them for testing.

_# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

allow_anonymous false
password_file /etc/mosquitto/passwd

log_type all
websockets_log_level 255

persistence true

bind_address 127.0.0.1

# MQTT over TLS/SSL
listener 8883 0.0.0.0
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
require_certificate true

# WebSockets over TLS/SSL
listener 9001 0.0.0.0
protocol websockets
cafile /etc/mosquitto/certs/domain.ca-bundle
keyfile /etc/mosquitto/certs/domain.key
certfile /etc/mosquitto/certs/domain.crt
require_certificate false
allow_anonymous true_

I then copied the client certificates over to the weewx server and put them in the /weewx/certs directory. 

I then removed all the MQTT statements in the Belchertown skin.conf file, or commented them out with #.

In the Weewx.conf file I put this configure under [StdRESTful]:

    _[[MQTT]]
        server_url = mqtt://weewxmqttuser:passwd@mqttserver:8883
        topic = weather
        unit_system = US
        binding = archive, loop
        aggregation = aggregate

        [[[tls]]]
            # CA certificates file (mandatory)
            ca_certs = /home/weewx/certs/ca.crt
            # PEM encoded client certificate file (optional)
            certfile = /home/weewx/certs/client.crt
            # private key file (optional)
            keyfile = /home/weewx/certs/client.key
            # Certificate requirements imposed on the broker (optional).
            #   Options are 'none', 'optional' or 'required'.
            #   Default is 'required'.
            cert_reqs = none
            # SSL/TLS protocol (optional).
            #   Options include sslv2, sslv23, sslv3, tls, tlsv1, tlsv11,
            #   tlsv12.
            #   Default is 'tlsv12'
            #   Not all options are supported by all systems.
            #   OpenSSL version till 1.0.0.h supports sslv2, sslv3 and tlsv1
            #   OpenSSL >= 1.0.1 supports tlsv11 and tlsv12
            #   OpenSSL >= 1.1.1 support TLSv1.3 (use tls_version = tls)
            #   Check your OpenSSL protocol support with:
            #   openssl s_client -help 2>&1  > /dev/null | egrep "\-(ssl|tls)[^a-z]"
            tls_version = tls_

Then I put this under the Belchertown section under [StdReport]:
        mqtt_websockets_host = "mqttserver"
        mqtt_websockets_port = 9001
        mqtt_websockets_enabled = 1
        mqtt_websockets_ssl = 1
        mqtt_websockets_topic = "weather/loop"
        disconnect_live_website_visitor = 1800000

For my setup, I also set up my firewall to allow access to the MQTT server and ports as needed. So far, it's working as intended.
