### ISSUE TITLE
Add option for override default lang of month in highcharts

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#664]
:bulb: **The Idea**
Add option in **skin.conf** for override default lang of month in highcharts.

:hammer: **Breaking Feature**
I changed manually **belchertown.js.tmpl** and added my locale definition of short month:
`Highcharts.setOptions({
    global: {
        //useUTC: false
        timezoneOffset: $highcharts_timezoneoffset
    },
    lang: {
        decimalPoint: "$highcharts_decimal",
        thousandsSep: "$highcharts_thousands",
        shortMonths: ['Gen', 'Feb', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Des']
    }
});
`

Thanks!

**Comment by ArendPWS** [comment]
@dtalens,

This has been already solved in the 1.3b1 with these changes using momentjs (but you can allways use your own definitions ofcourse):

	Highcharts.setOptions({
		global: {
			//useUTC: false
			timezoneOffset: $highcharts_timezoneoffset
		},
		lang: {
			months: moment.months(),
			shortMonths: moment.monthsShort(),
			weekdays: moment.weekdays(),
			shortWeekdays: moment.weekdaysShort(),
			decimalPoint: "$highcharts_decimal",
			thousandsSep: "$highcharts_thousands"
		}
	});

We really need a release of 1.3, otherwise old issues keep piling up.

**Comment by dtalens** [comment]
Ok, this solution is better. Thanks.
