### ISSUE TITLE
Missing labels in 1h 3h forecast

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#669]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
I I just upgraded from version 1.2 to version 1.3b1.
Missing date and time labels in 1h and 3h forecasts but 24h forecast is displayed correctly.

**Link to your website (IMPORTANT)**
https://meteopego.dtalens.com

**Version of the skin you're using**
1.3b1

**To Reproduce**

**Expected behavior**

**Screenshots**
1h Forecast
![image](https://user-images.githubusercontent.com/6631832/114315216-39619800-9afe-11eb-8f27-a0fb960da986.png)

3h Forecast
![image](https://user-images.githubusercontent.com/6631832/114315223-43839680-9afe-11eb-9f14-b6d13bc06f4a.png)

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser: Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by norecords** [comment]
Did you tried to delete forecast.json?

**Comment by dtalens** [comment]
Yes, I did

**Comment by norecords** [comment]
I see you use brackets inside your text translation like `[Poca intensitat]`, can you remove these extra brackets

**Comment by dtalens** [comment]
Done!

**Comment by norecords** [comment]
okay and do you have this time format in skin.conf or weewx.conf
` time_forecast_time                      = "ddd LT"`

**Comment by dtalens** [comment]
Thanks @norecords. I had added all new tags to the skin.conf file version 1.2 but had still left this one.

**Comment by norecords** [comment]
As you are in Latin language you add this https://github.com/poblabs/weewx-belchertown/pull/666 to upper case the first letter of snapshots dates.
