### ISSUE TITLE
No plot color in charts

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#671]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
If I try to add following options in one of chart of `graph.conf,` graphic stops showing colors, appears empty:
`        aggregate_type = avg
        aggregate_interval = 300
`
My archive_interval is 60 s in weewx and my `gapsize` is also 60 s. 

If I disable these options the chart is displayed correctly. These options worked well in version 1.2.

**Link to your website (IMPORTANT)**
https://meteopego.dtalens.com/graphs/

**Version of the skin you're using**
1.3b1

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6631832/114322987-72f8ca00-9b23-11eb-9c41-d77ad44a9e51.png)

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by dtalens** [comment]
I added `connectNulls = true` and it was fixed.

**Comment by c0by85** [comment]
Got the same issue. I added `connectNulls = true` and it was fixed too. 👍 

![image](https://user-images.githubusercontent.com/25707747/114920744-0daa1f00-9e2a-11eb-9515-2f39015b4c55.png)

**Comment by c0by85** [comment]
@dtalens i think you should reopen the issue.

**Comment by dtalens** [comment]
I tried it again and it seemed to work fine if I was just doing a reload but not if I was doing a full weewx restart.
