### ISSUE TITLE
Gauge using rainTotal - no units

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#674]
Version 1.3b1 of the skin with Weewx 4.4.0

I've set the rain chart type to gauge using rainTotal which works ok except there are no units displayed with the total in the middle of the gauge

Also the decimal points reduction (rounding) doesn't work - I'm trying to just get 1 decimal point not the 2 it has defaulted to.

I don't believe that the yAxis_softmin or _max work either. Any help appreciated.

[[chart3]]
        title = Rain since midnight
        type = gauge
        time_length = today
        [[[rainTotal]]]
            rounded = 1
            color = "#3495eb"
            yAxis_softmin = 0
            yAxis_softmax = 5
                [[[[numberFormat]]]]
                  decimals = 1
                  decimalPoint = "."

**Comment by James-76** [comment]
You may wish to be aware of #661 which I believe will fix your rounding issue.

**Comment by 41south** [comment]
Thanks James,that appears to be for the tool tips, does it also apply to
the displayed units in the middle of the gauge?

Colin

**Comment by James-76** [comment]
It is only a fix for tooltip.  It is a two line change so you can try it out.

James

**Comment by 41south** [comment]
Unfortunately the tooltip isn't my issue, that's working perfectly fine. Picture attached of the issue - no units in the middle of the gauge for [rainTotal]
![Screen Shot 2021-04-16 at 7 20 39 AM](https://user-images.githubusercontent.com/1725001/114926499-850c9c80-9e84-11eb-94e9-f8eb569cacc2.png)

**Comment by c0by85** [comment]
Same here...

![image](https://user-images.githubusercontent.com/25707747/114936917-60410680-9e3d-11eb-811d-7ff906c20b8f.png)

```
[test]
       title = Test
       show_button = false
       button_text = Test Ecke
       start_at_midnight = true
    [[exampleGauge1]]
        title = Example gauge chart
        type = gauge
        [[[outTemp]]]
            color = "#f7a35c"
[[exampleGauge]]
        title = Example gauge chart
        type = gauge
        [[[windGust]]]
                rounded = 1
                colors_enabled = 1
                color1_position = 3
                color1 = "#1278c8"
                color2_position = 7
                color2 = "#1fafdd"
                color3_position = 12
                color3 = "#71bc3c"
                color4_position = 20
                color4 = "#ffae00"
                color5_position = 30
                color5 = "#ff7f00"
                color6_position = 40
                color6 = "#ff4500"
                color7_position = 50
                color7 = "#9f00c5"
                yAxis_min = 0
                yAxis_max = 70
```

**Comment by 41south** [comment]
Anybody with any thoughts on this issue??
