### ISSUE TITLE
I can't believe my MQTT data

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#675]
I have just installed mqtt and after some minor configuration tweaks, it appeared to be working BUT...
1  The values displayed on my browser change every 2 or 3 seconds, whereas my weather station's loop interval is ~16 seconds.  How can the displayed data change that frequently?
2 I don't believe the values as they do not agree with the ones directly transmitted by my weather station.  
See  outTemp and winddir in the images below (Note some of the units are different). 
The browser view shows the max temp as 12.2, but the current temp is 14.4! 
I look out at my weather station and clearly the wind direction and speed are all wrong.
I have downloaded weewx.sdb and checked the values and they agree with the weather station values, so my stored data is not corrupt.

So whose data am I getting and who is getting mine?  Should I try another broker?
Any help gratefully received.
Michael

my weewx.conf settings
    [[MQTT]]
        server_url = //broker.emqx.io:1883 /
        topic = weather
        unit_system = METRIC
        aggregation = aggregate
        binding = loop

my skin.conf settings
    # MQTT Websockets defaults
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = //broker.emqx.io
    mqtt_websockets_port = 8083
    mqtt_websockets_ssl = 0
    mqtt_websockets_topic = "weather/loop"
    disconnect_live_website_visitor = 1800000

weatherstation data
![image](https://user-images.githubusercontent.com/45148992/114704219-4361e180-9d1e-11eb-83a4-226fad738c4b.png)

Browser data
![image](https://user-images.githubusercontent.com/45148992/114704339-68eeeb00-9d1e-11eb-8dd6-b7ac6a855f8b.png)

**Comment by poblabs** [comment]
Run weewx in manual mode and check what the LOOP packets are. The mqtt data
just echos the loop data.

**Comment by gdt** [comment]
You have configured a topic of "weather".   If you are the only one writing to that topic on that broker, that should be ok.   If you are using a public broker (which IMHO is not really a good idea), then you need to pick a topic that nobody else will use, like /weather/your.domain.name.

**Comment by michaelundwd** [comment]
@gdt Many thanks that fixed it for me and also solved the gap in my understanding about how mqtt brokers keep (or don't keep) message streams independent.  Networks were never my strong point.  emqx is indeed a public broker as I use it.
Michael
