### ISSUE TITLE
behavior of time_length seems to have changed after upgrade to weewx 4.5.1

### ISSUE THREAD

**Issue by silke-99** [poblabs/weewx-belchertown#679]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**Describe the bug**
I recently upgraded from weewx 4.4.0 to weewx 4.5.1. (Belchertown Skin version 1.2 was not changed, neither was the config.)

This seems to have changed the behavior of Belchertown charts with regards to handling of time_length.
Before the upgrade, using e.g. time_length = year will show the entire year until December including empty plot areas. (as described in the documentation)

Now, it shows only months with existing data (replicating year_to_now)

**Version of the skin you're using**
1.2

**To Reproduce**
move to new weewx version
(I did not try to downgrade weewx for verification, but it was the only change made to my weather setup recently)

**Expected behavior**
be able to generate full-year charts again for current year (= get back to behavior as described in documentation :-))

Just to provide my graph config, I'm using for example the weather radial described in the documentation (below). It used to show the entire year but now it doesn't.

You can check out the output [here (first chart)](http://artur.home.dyndns.org/graphs/?graph=year).

Thanks so much!

```
[year]
title = "Dieses Jahr"
show_button = true
button_text = "Jahr"
type = spline
time_length = year
tooltip_date_format = "dddd LL"
aggregate_type = max
aggregate_interval = 86400 # 1 day
gapsize = 86400 # 1 day in seconds

[[chart1]]
      title = Dieses Jahr
      css_class = "weatherRadial"
    [[[weatherRange]]]
        range_type = outTemp
            title = Temperatur
            area_display = 1
```

**Comment by silke-99** [comment]
Just to provide my graph config, I'm using  for example the weather radial described in the documentation.  It used to show the entire year but now it doesn't.

You can check out the output [here (first chart)](http://artur.home.dyndns.org/graphs/?graph=year).

[year]
    # Chart Timespan Defaults
    title = "Dieses Jahr"
    show_button = true
    button_text = "Jahr"
    type = spline
    time_length = year
    tooltip_date_format = "dddd LL"
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400 # 1 day in seconds

    [[chart1]]
          title = Dieses Jahr
          css_class = "weatherRadial"
        [[[weatherRange]]]
            range_type = outTemp
                title = Temperatur
                area_display = 1

**Comment by c0by85** [comment]
I think this is the same behaviour as in [https://github.com/poblabs/weewx-belchertown/issues/635](https://github.com/poblabs/weewx-belchertown/issues/635).
