### ISSUE TITLE
Sun & Moon additional info

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#68]
Hi.
It would be nice if day's length can be added to Sun & Moon panel. Example:
Light Hours: 12 h 54 m
Tomorrow will be 2 minutes 8 seconds shorter
Thanks!

**Comment by poblabs** [comment]
I'm struggling with where this can go. Adding another line to the Sun & Moon box would throw the design of the top info area out of alignment and the radar wouldn't fit. I'm also not sure if I'll have the "Tomorrow" information since this information is all dynamic from weewx.

**Comment by HoracioDos** [comment]
Hello Pat.
I imagined that it wouldn't be easy to change the layout. I was thinking that it might look like to the current data panel (Barometer, Visibility...) but it won't be so graphic like it is now. You can dismiss this request if it's to complex to solve. Perhaps it would be better to create some optional include file like (index_hook_after_something) in the future with some astronomical data if there's some traction to it. Feel free to do what you think it's best for your skin. Thanks for considering this request.

**Comment by poblabs** [comment]
Some good ideas HoracioDos. You could put the extra information into `index_hook_after_station_info.inc`. This will show it right below the top bar. You can put [all of the information in the weewx customization guide for Almanac](http://www.weewx.com/docs/customizing.htm#Almanac) into the .inc file and it will show up there.

**Comment by HoracioDos** [comment]
As far as I can remember old standard skin had an astronomical almanac. I didn't check new seasons skin yet, but I guess I could merge some code inside index_hook_after_station_info.inc. It won't be as good looking like the things you do but it should fit the needs. Thanks again.

**Comment by poblabs** [comment]
If you wanted, you could edit `skins/Belchertown/index.html.tmpl` and add those almanac $ tags to where you want them. the `inc` files make it easier, but it takes more effort to make them look good.

**Comment by HoracioDos** [comment]
Hello
Finally I did something in between. I removed Sun & Moon title from index.html.tmpl to make more space and I wanted to avoid changing radar image size. I think it looks better. Then I inserted a new hook file called index_hook_daylight_info.

I included this file into the sun & moon table as new records. I used a class attribute that already existed to format text. I should create a new one in style.css

I copied all calculations to this new file from celestial.inc file (seasons skin) to get daylight hours using built-in almanac tags and added two new records to the table. It would be more elegant to create a query to the darksky json file to get sunrise and sunset times and calculate daylight hours.This is how it looks like this now. 

Thanks to make me think new alternatives.
![daylight](https://user-images.githubusercontent.com/4549674/55190611-ecacfd80-517e-11e9-9445-65702fa08184.png)

**Comment by poblabs** [comment]
This looks pretty good! Even with "Sun & Moon" removed. I wonder if this should be in the skin?

**Comment by 41south** [comment]
If we were voting I like it as it is now 🙂

**Comment by poblabs** [comment]
I agree. I think I'll keep it as is for now. I'm glad Horacio was able to
find a way that worked for him

**Comment by HoracioDos** [comment]
Hello
This is other option keeping the Sun & Moon title. I made some changes in style.css 
```
.sunrise-set-image {
  /*    width:20px; */
        width:15px;
        margin-right:5px;
}

.sun-moon-title {
/*      font-size:25px; */
        font-size:25px;
        text-align:left;
/*      padding-bottom: 10px; */
        padding-bottom: 0px;
```
I resized radar image a little bit, not too much
`radar_html = <iframe width="650" height="400" src="https://embed.windy.com`

![daylight_v2](https://user-images.githubusercontent.com/4549674/55197583-cd6b9b80-5191-11e9-81a2-e4818a7fc5d1.png)

**Comment by HoracioDos** [comment]
As I'm still adding sensors to my old weather station and a new one is in customs, I'm using the simulator driver. Forget these strange temp values for my latitude.

**Comment by HoracioDos** [comment]
I can't find an easy way to keep Sun & Moon title and all other things aligned. I'll leave it as It was and I'll keep this issue closed. I added windrun value on the left panel. 
![daylight_v3](https://user-images.githubusercontent.com/4549674/55203350-c51f5a80-51a9-11e9-91ea-95f137c92adc.png)

**Comment by kadaan** [comment]
What about this?
![image](https://user-images.githubusercontent.com/1904898/124368270-5ea10680-dc14-11eb-8e3a-76150a7ec3b2.png)

**Comment by ddperso** [comment]
Good idea
Another way is to remove "More Info" and to put this info on "Sun & Moon"
Sun & Moon becomes a red link

**Comment by kadaan** [comment]
@ddperso I think one issue with that, is at the moment the "Sun & Moon" label is optional.

**Comment by kadaan** [comment]
What about this?
![image](https://user-images.githubusercontent.com/1904898/124392420-53001f00-dcaa-11eb-8278-008762746cc0.png)

**Comment by kadaan** [comment]
Or?
![image](https://user-images.githubusercontent.com/1904898/124392541-0ff27b80-dcab-11eb-980f-b3887f35c8d9.png)

**Comment by kadaan** [comment]
Or last option I've come up with
![image](https://user-images.githubusercontent.com/1904898/124392697-04538480-dcac-11eb-8424-604a4b87ac0f.png)

**Comment by ddperso** [comment]
Finally, I prefer "More Info" beside the title

**Comment by kadaan** [comment]
Makes sense.  This one is a little weird as the Sun & Moon label can be absent.  Having "More Info" up top will look weird in that case...

**Comment by kadaan** [comment]
This is how my final version looks
![image](https://user-images.githubusercontent.com/1904898/124397842-2b6b7f80-dcc7-11eb-8b5f-3f7fac26407c.png)
