### ISSUE TITLE
Error on ReportGenerator if using Earthquakedata from ReNaSS

### ISSUE THREAD

**Issue by Hubert2208** [poblabs/weewx-belchertown#680]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
If i use the Screen with earthquake_server = USGS, everything works fine.
if i use earthquake_server = ReNaSS i got the following error from report generator:
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  local variable 'earthquake_url' referenced before assignment
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown.py", line 1090, in get_extension_list
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      req = Request( earthquake_url, None, headers )
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'earthquake_url' referenced before assignment
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown.py", line 1102, in get_extension_list
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      command = 'curl -L --silent "%s"' % earthquake_url
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'earthquake_url' referenced before assignment
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      obj.start()
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      self.run()
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 150, in run
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 308, in generate
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      searchList = self._getSearchList(encoding, timespan,
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 385, in _getSearchList
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown.py", line 1108, in get_extension_list
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****      raise Warning( "Error downloading earthquake data using urllib2 and subprocess curl. Your software may need to be updated, or the URL is incorrect. You are trying to use URL: %s, and the error is: %s" % ( earthquake_url, error ) )
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'earthquake_url' referenced before assignment
Traceback (most recent call last):
  File "/home/weewx/bin/user/belchertown.py", line 1090, in get_extension_list
    req = Request( earthquake_url, None, headers )
UnboundLocalError: local variable 'earthquake_url' referenced before assignment
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/weewx/bin/user/belchertown.py", line 1102, in get_extension_list
    command = 'curl -L --silent "%s"' % earthquake_url
UnboundLocalError: local variable 'earthquake_url' referenced before assignment
Apr 27 12:10:54 weewx[19] ERROR weewx.reportengine:         ****  Generator terminated
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
    self.run()
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 308, in generate
    searchList = self._getSearchList(encoding, timespan,
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 385, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/home/weewx/bin/user/belchertown.py", line 1108, in get_extension_list
    raise Warning( "Error downloading earthquake data using urllib2 and subprocess curl. Your software may need to be updated, or the URL is incorrect. You are trying to use URL: %s, and the error is: %s" % ( earthquake_url, error ) )
UnboundLocalError: local variable 'earthquake_url' referenced before assignment

**Link to your website (IMPORTANT)**
https://www.familie-mayer.bayern/weewx/

**Version of the skin you're using**
1.2

**To Reproduce**
Place earthquake_server = ReNaSS in weewx.conf
look into weewx log after 5 minutes

**Expected behavior**
no errors in the log, fetch earthquake-data from ReNaSS-WebSite

**Screenshots**

**Device Information (please complete the following information):**
it's not a problem to display the data. It's a problem of fetching the data within weewx.
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by norecords** [comment]
@Hubert2208 this is not available on 1.2
you have to install the dev branch.

**Comment by norecords** [comment]
Off Topic:
Just see on your website that you use ssl, you will also need mqtt websocket on ssl to work together.

**Comment by Hubert2208** [comment]
Thanks for your answer. You are right. After install of the dev-Version everything works well.
Update via mqtt works actual only in the intranet. I run weewx and the mosquitto-server on a k3s-cluster. Acualy im looking how the ingress-controller (nginx) can sign the tcp-stream.
Thanks again for your help.
Greetings from bavaria, germany
