### ISSUE TITLE
Add support for color band in charts

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#682]
:bulb: **The Idea**
Would it be possible to add option to add color bands to charts?. I would like to add color bands to PM2.5 particle sensor chart to mark EAQI (European Air Quality Index) levels.

:hammer: **Breaking Feature**
In Highcharts documentation this option is available but I am unable to change the code to implement it. Can anyone help me?
[https://api.highcharts.com/highcharts/yAxis.plotBands.color](url)

![image](https://user-images.githubusercontent.com/6631832/117504506-d9d29d00-af82-11eb-9db3-a76a8783273b.png)

[https://jsfiddle.net/dtalens/9ty6ohpk/33/](https://jsfiddle.net/dtalens/9ty6ohpk/33/)

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by norecords** [comment]
@dtalens take a look at this [PR](https://github.com/poblabs/weewx-belchertown/pull/650/files)

you should try something like this:
(NOT TESTED)
Replace `xAxis_labels_formatter` by `yAxis_aqi_plotbands`
then
```
            // yAxis AQI plotbands color
            if (yAxis_aqi_plotbands.length >= 1) {
                options.yAxis = {
                    plotBands: [{
                        color: '#50f0e6',
                        from: 0,
                        to: 10,
                        id: 'Good'
                    },{
                        color: '#50ccaa',
                        from: 10,
                        to: 20,
                        id: 'Fair'
                    },{
                        color: '#f0e641',
                        from: 20,
                        to: 25,
                        id: 'Moderate'
                    },{
                        color: '#ff5050',
                        from: 25,
                        to: 50,
                        id: 'Poor'
                    },{
                        color: '#960032',
                        from: 50,
                        to: 75,
                        id: 'Very_Poor'
                    },{
                        color: '#960032',
                        from: 75,
                        to: 800,
                        id: 'Extremely_Poor'
                    }]
                }
            }
```
and in your graphs.conf
add `yAxis_aqi_plotbands = true` into your aqi section

**Comment by norecords** [comment]
Finally add this should work
after 
https://github.com/poblabs/weewx-belchertown/blob/3839baa3fb5a94a40b4ca29235182e88d4867f62/skins/Belchertown/js/belchertown.js.tmpl#L2356
Add
```
                // yAxis AQI plotbands color
                if (s.obsType == "marsPM25Chart") {
                    belchertown_debug('pm25 plotbands true');
                    options.yAxis[this_yAxis].plotBands = [{
                        color: '#50f0e6',
                        from: 0,
                        to: 10,
                        id: 'Good'
                    },{
                        color: '#50ccaa',
                        from: 10,
                        to: 20,
                        id: 'Fair'
                    },{
                        color: '#f0e641',
                        from: 20,
                        to: 25,
                        id: 'Moderate'
                    },{
                        color: '#ff5050',
                        from: 25,
                        to: 50,
                        id: 'Poor'
                    },{
                        color: '#960032',
                        from: 50,
                        to: 75,
                        id: 'Very_Poor'
                    },{
                        color: '#960032',
                        from: 75,
                        to: 800,
                        id: 'Extremely_Poor'
                    }];
                }
```
Replace `marsPM25Chart` by your pm25 observation.
see [live](https://meteo.correns.org/#mars_estaque).

**Comment by dtalens** [comment]
`                // yAxis AQI plotbands color
                if (s.obsType == "marsPM25Chart") {
                    belchertown_debug('pm25 plotbands true');
                    options.yAxis[this_yAxis].plotBands = [{
                        color: '#50f0e6',
                        from: 0,
                        to: 10,
                        id: 'Good'
                    },{
                        color: '#50ccaa',
                        from: 10,
                        to: 20,
                        id: 'Fair'
                    },{
                        color: '#f0e641',
                        from: 20,
                        to: 25,
                        id: 'Moderate'
                    },{
                        color: '#ff5050',
                        from: 25,
                        to: 50,
                        id: 'Poor'
                    },{
                        color: '#960032',
                        from: 50,
                        to: 75,
                        id: 'Very_Poor'
                    },{
                        color: '#7D2181',
                        from: 75,
                        to: 800,
                        id: 'Extremely_Poor'
                    }];
                }
`

Last colour code is repeated, html color is: `#7D2181` for EAQI Extremely Poor level.
Not working in black mode only in withe mode.

**Comment by norecords** [comment]
@dtalens yes I saw that's plotBands colors disappear when on dark mode, at this time I have no fix.

**Comment by norecords** [comment]
@dtalens the solution to work with dark mode just need to edit `belchertown-dark.min.css`
remove `,.dark .highcharts-plot-band`

**Comment by dtalens** [comment]
Thanks @norecords.

**Comment by norecords** [comment]
@dtalens I'm now using plot lines instead, 
https://github.com/poblabs/weewx-belchertown/blob/3839baa3fb5a94a40b4ca29235182e88d4867f62/skins/Belchertown/js/belchertown.js.tmpl#L2356
```
                // yAxis AQI PlotLines
                if (s.obsType == "myPM25Observation") {
                    belchertown_debug('yAxis plotLines true');

                    var yAxis_plotlines = [];

                    // PM25 EAQI (European Air Quality Index) levels, labels and belchertown's colors
                    const eaqi = [{
                        colors: "#71bc3c",
                        labels: "Good",
                        levels: 10
                    }, {
                        colors: "rgba(255,174,0,0.9)",
                        labels: "Fair",
                        levels: 20
                    }, {
                        colors: "rgba(255,127,0,1)",
                        labels: "Moderate",
                        levels: 25
                    }, {
                        colors: "rgba(255,69,69,1)",
                        labels: "Poor",
                        levels: 50
                    }, {
                        colors: "#b16286",
                        labels: "Very Poor",
                        levels: 75
                    }];

                    for (i = 0; i < eaqi.length; i++) {
                        yAxis_plotlines.push({
                            color: eaqi[i].colors,
                            value: eaqi[i].levels,
                            label: {
                                text: eaqi[i].labels,
                                x: 0,
                                y: 15,
                                style: {
                                    color: eaqi[i].colors,
                                    fontWeight: 'bold'
                                }
                            },
                            width: 3,
                            dashStyle: 'longdashdot',
                            zIndex : 3
                        });
                    }

                    // Add plotlines to yAxis options
                    options.yAxis[this_yAxis].plotLines = yAxis_plotlines;
                    belchertown_debug(yAxis_plotlines);
                }
```
![Screenshot_2021-05-12 Météo Correns - Station météorologique en temps réel](https://user-images.githubusercontent.com/12499787/117928314-ab92eb80-b2fb-11eb-8d8b-cd977c2f1b57.png)

**Comment by dtalens** [comment]
This solution is better, thanks!

**Comment by norecords** [comment]
You may renamed this issue "Add support for colored plotBands or plotLines on yAxis
