### ISSUE TITLE
Chart Looks

### ISSUE THREAD

**Issue by Overcon** [poblabs/weewx-belchertown#686]
Is there a reason my charts look different than the examples found on the Belchertown-Charts-Documentation page?

When I add:

    [[radialChartName]]
        title = Temperature Ranges for Past Year
        [[[weatherRange]]]
            range_type = outTemp
            area_display = 1

It doesn't look anything like the example on the page.

Mine:
![a](https://user-images.githubusercontent.com/8976670/118342832-798fae00-b4e2-11eb-9a92-7004a3bf99bb.JPG)

Charts Page:
![b](https://user-images.githubusercontent.com/8976670/118342843-890ef700-b4e2-11eb-9d25-4078a1a134fd.JPG)

**Comment by poblabs** [comment]
version of the skin?

**Comment by Overcon** [comment]
Version 1.2.

**Comment by poblabs** [comment]
pretty sure this was added in 1.3b1 which is the master branch currently.

**Comment by Overcon** [comment]
Ah, OK. I just did a fresh install a couple days ago, I thought it downloaded the latest version, but it looks like you have to do a little extra digging to get those versions. Let me update and check it afterwards. Thanks!

**Comment by Overcon** [comment]
That was it. Thanks! I thought for sure I had the latest version since I just did a fresh install.
