### ISSUE TITLE
Visitor Settings

### ISSUE THREAD

**Issue by Valinwolf** [poblabs/weewx-belchertown#687]
:bulb: **The Idea**

Not everyone like a light theme, not everyone likes a dark theme, and not everyone like a time-based theme. Likewise, not everyone uses metric and not everyone uses imperial, and some even use a combination of the two. As such, I would like to see the ability to have per-visitor settings using a local browser storage system such as `document.cookie`.

:hammer: **Breaking Feature**

Possibly, but with the existing MQTT update system I think it could be done simply with basic modifications. It could have an onload function that converts everything after page load. I have not delved into the code, so I do not know if this would be a breaking change or not.

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 
I would love to help with this, but I barely find time between classes and work to do much of anything these days.

**Comment by roe-dl** [comment]
Please consider the side effects regarding cookies. If you use cookies you have to display a legal disclaimer to the visitor saying what you save, which personal data you process etc. pp. 

Additionally, what I read from Google, may be, they ban cookies entirely some time.
