### ISSUE TITLE
Moon Phases

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#69]
Hello.
The skin shows Last Quarter for today (Feb 27) but according to Wunderground It should be Waning Crescent. Is it correct?
Thanks!

**Comment by poblabs** [comment]
Hello, this is not a skin website issue. 

To have accurate Moon Phases, you need the pyephem package installed.

Please see the [WeeWX Customization Guide ](http://www.weewx.com/docs/customizing.htm#Almanac) for more information. 

Without pyephem, weewx makes it's best guess.

**Comment by HoracioDos** [comment]
My mistake!!! Thanks again!

**Comment by poblabs** [comment]
You are welcome

**Comment by biltmorelaker** [comment]
Just for a little more information. I do have pyephem installed. Both weewx and WU show the moon at 39% visible. But weewx (presumably pyephem) is reporting that as "Last Quarter" and WU is reporting that as "Waning Crescent".

Based on a rudimentary search of the Internet, it looks like the change of moon phase from Last Quarter to Waning Crescent is around 40% visible. So, I expect that weewx will soon change the moon phase description to Waning Crescent as the visible percent continues to decrease.

**Comment by HoracioDos** [comment]
I asked the same question yesterday in weewx group. Main developer found some issues in moon phase calculation and made some fixes. Moon phases now change in UTC and calculation accuracy was improved.
