### ISSUE TITLE
Switch between languages

### ISSUE THREAD

**Issue by flewid** [poblabs/weewx-belchertown#691]
Is it possible to switch between languages with this theme?

What I would like to do is add a menu item for 'french' and when clicked, everything switches to french. And, on that side, the user sees 'english' and can flip back. 

Maybe a sub directory called /french/ would be simplest, and then just convert all the translations to french and publish two versions of the theme? I'm not sure if that is the right approach.

**Comment by roe-dl** [comment]
The upcoming WeeWX version 4.6 will come with enhanced language and localization support. It will then take some time that the skin authors adjust their skins to the new possibilities. So I guess you are little bit early with your question.

**Comment by flewid** [comment]
Oh great thank you. I'll just wait it out :)
