### ISSUE TITLE
Current weather icon not displayed

### ISSUE THREAD

**Issue by larsnsonsk** [poblabs/weewx-belchertown#692]
Hi,
the current icon (in the upper left area, left to the temperature) is not displayed.
I thought its’s something with the path, but the forecast icons are displayed correctly (and thats the same images).

I don't see any errors in the developer console, no "load error, not found..." etc.
It seems to be the whole div is empty.
Any idea ?

```
Debug: skin.conf belchertown_debug enabled
belchertown.js?1622907640:37 URL: Relative URL is: .
belchertown.js?1622907640:37 URL: Relative URL is: .
belchertown.js?1622907640:37 Theme: sessionStorage override in place.
belchertown.js?1622907640:37 Theme: Changing to light
belchertown.js?1622907640:37 Theme: logo_image is defined.
belchertown.js?1622907640:37 rotateThis: rotating to 299
belchertown.js?1622907640:37 URL: Relative URL is: .
belchertown.js?1622907640:37 Updating weewx data
belchertown.js?1622907640:37 Forecast: Provider is aeris
belchertown.js?1622907640:37 Forecast: Updating data
belchertown.js?1622907640:37 Forecast: icon from Aeris data is fair.png
belchertown.js?1622907640:37 URL: Relative URL is: .
belchertown.js?1622907640:37 Forecast: Belchertown icon is ./images/mostly-clear-day.png
7belchertown.js?1622907640:37 URL: Relative URL is: .
belchertown.js?1622907640:37 Forecast: Changing icon to ./images/mostly-clear-day.png
```

**Comment by norecords** [comment]
What's happen if you try to open the empty image by right click in your browser?

**Comment by s-s-s** [comment]
I have the same problem.
 WeeWX 4.5.1
  Belchertown 1.2
  https://wx.kkk29.keenetic.link/weewx/

**Comment by norecords** [comment]
@s-s-s with weewx 4.5.1 you should use the latest github version :
https://github.com/poblabs/weewx-belchertown#how-to-install-the-development-version

**Comment by s-s-s** [comment]
@norecords , and with the master version I had the same result and I went back to release 1.2

**Comment by norecords** [comment]
That's just because the forecast provider have no current data for your position, see at the end of https://wx.kkk29.keenetic.link/weewx/json/forecast.json
That's not really a Belchertown issue ..

**Comment by norecords** [comment]
@s-s-s Based on your location the first reachable Station is at 130km so you may have to iadd this value in belchertown.py
https://github.com/poblabs/weewx-belchertown/blob/8494935f82e873de2d063311c035ce930a8e207e/bin/user/belchertown.py#L1177
to
`"https://api.aerisapi.com/observations/%s,%s?radius=130km&format=json&filter=allstations&limit=1&client_id=%s&client_secret=%s"`
delete json/forecast.json in your webdir to force new download
and restart weewx

**Comment by s-s-s** [comment]
@norecords  Thanks. "radius=130km" worked :+1:  
However, this is too far away to be true in the sense of a forecast (

**Comment by WiggyToo** [comment]
Just to comment that after upgrading to the latest skin (1.3.1) recently I had this problem too, the forecast icon seemed OK on the home page (although drizzle.png seemed reluctant to load reliably) - but on all the other pages (about etc.) I just got the unknown.png icon.

I'm not sure exactly how I fixed it but a combination of turning the aeris API off in aeris, stoppping weewx, deleting forecast.josn, waiting, restartin aeris API, restarting weewx seemed to do the trick.

**Comment by WiggyToo** [comment]
It has come back now see report
https://github.com/poblabs/weewx-belchertown/issues/947
