### ISSUE TITLE
Time offset calculated is wrong when offset is not an integer

### ISSUE THREAD

**Issue by KasturiNagarWeather** [poblabs/weewx-belchertown#7]
Hi Pat,

As you pointed over mail, the below code calculates the offset:

 moment_js_stop_struct = time.localtime( time.time() )
 moment_js_utc_offset = (calendar.timegm(moment_js_stop_struct) - calendar.timegm(time.gmtime(time.mktime(moment_js_stop_struct))))/60/60 

The offset in seconds is 19800 which in minutes is 330.

When this is further divided by 60, the output gets rounded off to 5 instead of 5.5. Hence the time updated display when MQTT enabled is behind by 30 minutes.

Regards,
Praveen

**Comment by poblabs** [comment]
Yeah I guess I never thought of the half timezone offsets. The JS needs it in hours offset, so I might have to keep it in minutes, then let JS handle the conversion. Hmm. Going to have to test this one out on my lab.
