### ISSUE TITLE
Help Wanted - Weather Station Name location.

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#70]
Hello Pat.
I would like to locate the weather station name on the right of logo in the main page. Also I would be nice to avoid wrap text in records, reports, graphs and about pages. I've been toying with tmpl and style.css files without success. Would you please give some clue if it's not too much trouble. 
Thanks in advance
![graphs](https://user-images.githubusercontent.com/4549674/53682954-e9d30000-3cd9-11e9-944b-500dfc522298.png)
![ws name](https://user-images.githubusercontent.com/4549674/53682955-ea6b9680-3cd9-11e9-95af-0bd590469c54.png)

**Comment by poblabs** [comment]
Hi Horacio. To locate the weather station name to the right of logo, your best bet may be to use a logo file with the name there. Just like how you see on https://belchertownweather.com 

If you want to change the title on the pages you can look at these options

Does this help?


graphs_page_header | "Weather Observation Graphs" | The header text to show on the Graphs page
-- | -- | --
reports_page_header | "Weather Observation Reports" | The header text to show on the Reports page
records_page_header | "Weather Observation Records" | The header text to show on the Records page
about_page_header | "About This Site" | The header text to show on the About page

**Comment by HoracioDos** [comment]
> To locate the weather station name to the right of logo, your best bet may be to use a logo file with the name there

Hello Pat.
I guess you are right and logo should include WS name. It would need to much tweaking to do it in other way. I'll try one more time. Web design is not my thing.

> If you want to change the title on the pages you can look at these options

I already use these options. As you can see I've removed also current temp and its image from graph, reports and so on. I wanted to avoid text wrap too.

Thanks!

**Comment by HoracioDos** [comment]
Hello Pat.
I found how to avoid title wraping in Graphs, Records, Reports and About pages. I removed some class attribute from page-header.inc like this:

```
<div class="col-sm-5">
</div>
```

Now my page-header.inc looks like.

```
<div class="wx-stn-info-container">
    <div class="row">
            <div class="wx-stn-name">
                #if $page == "graphs"
                <h1>$Extras.graphs_page_header</h1>
                #else if $page == "records"
                <h1>$Extras.records_page_header</h1>
                #else if $page == "reports"
                <h1>$Extras.reports_page_header</h1>
                #else if $page == "records"
                <h1>$Extras.records_page_header</h1>
                #else if $page == "about"
                <h1>$Extras.about_page_header</h1>
                #end if
            </div>
    </div>
    <div class="clear"></div>
</div>

```
![Weather Records](https://user-images.githubusercontent.com/4549674/54202667-4d65e600-44af-11e9-8b48-ba6db9885cf0.png)
