### ISSUE TITLE
does not create forcast.json on clean install

### ISSUE THREAD

**Issue by krywenko** [poblabs/weewx-belchertown#704]
hi there I ran across a few bugs trying to install this
when setting up forecast with aeris id did not create forecast.json and then it complained the entire time it did not exist I manually created  it and then it would stop complaining about a non existent file
 also i was trying to use my darksky api key as  I am having issues with aeris

my issue is that  where do you put your darksky api
I tried  forecast_api_id = "darkskyapi"     the API key  is not added to the  darksky  link and it  fails 

also better suggestion then  aeris
would be  climacell, weatherapi or  visualcrossing

https://www.visualcrossing.com/weather-api
https://www.weatherapi.com/
https://developer.tomorrow.io/v3/reference#get-daily

**Comment by poblabs** [comment]
Feel free to submit a pull request for other weather providers.

What do the logs say? Check the readme for instructions on how to debug
items like this. Could be a permission issue or a malformed key. Or even
the wrong option value.

**Comment by krywenko** [comment]
log
 for forecast.json  

 can  not see it as permission issue is forecast is disable all is fine  when forecast is enabled then  one gets errors  - manually insert blank file called forecast.json the  complaints stop

Error writing forecast info to /var/www/html/json/forecast.json. Reason: [Errno 2] No such file or directory: u'/var/www/html/json/forecast.json'

as to darksy key issue
 
 https://api.darksky.net/forecast//51.429,-97.466?units=si&lang=en, and the error is: HTTP Error 400: Bad Request

the api is not being inserted into the the request

are you using a different   then  forecast_api_id = "darkskyapi"  for darksky api key

**Comment by poblabs** [comment]
Dark sky turned off their API when Apple bought them. Are you sure you have
a working API key still? That's the whole reason why we switched to
AerisWeather

**Comment by poblabs** [comment]
You could also go to the previous version 1.1 which has darksky native support. read the readme.md file for the correct skin.conf/weewx.conf options as they're different (and I don't remember them anymore)

https://github.com/poblabs/weewx-belchertown/releases/tag/weewx-belchertown-1.1

**Comment by krywenko** [comment]
yes  it still works -  it just not being inserted in to the request
https://api.darksky.net/forecast//51.429,-97.466?units=si&lang=en, and the error is: HTTP Error 400: Bad Request
https://api.darksky.net/forecast/DARKSKYAPIKEYSHOULDBEHERE/51.429,-97.466?units=si&lang=en

 I try the older version anything to know  or you can apply the install overtop of the newer  version

**Comment by poblabs** [comment]
I would delete the skins/Belchertown folder and also the bin/user/belchertown.py files. Install new skin, configure it, restart weewx and you should be good

**Comment by poblabs** [comment]
I guess before you do that - have you restarted weewx yet on the new version?

**Comment by krywenko** [comment]
yes  I restarted  after each change -- it was a clean install on a fresh pi runing debian-- it would seam the darksky handle ->  darksky_secret_key = " "  it does not throw error but no darksy forecast I will look through your code and see what different and perhaps  if I understand what you are doing  i will  make it work for  one of the api I mentioned above

**Comment by krywenko** [comment]
I can not find the  folder /bin/user  or skin/belchertown    where are those located

**Comment by poblabs** [comment]
Check bottom of this readme http://www.weewx.com/docs/debian.htm

**Comment by krywenko** [comment]
this worked easier    ---   wee_extension --uninstall=Belchertown  and it now working again   with 1.1   but I will still see if I can figure out  where  how to add different    weather api    I see how to download the json   - just to figure out where to process it

**Comment by krywenko** [comment]
for your info if you want  to modify darksky  it seams visualcrossing is almost directly compatible - I have not tried  I will try tomorrow

https://www.visualcrossing.com/resources/documentation/weather-api/how-to-replace-the-dark-sky-api/
couple little changes    to the url and to json title section names ie-- darksky (currently:)   visualcrossing (currentConditions:)

**Comment by krywenko** [comment]
for your info  i modified belchertown 1.1  for visual crossing  it works fine - though I disable "visibility" as  your code does not handle nul  values  I think I had to modify about 20 lines most of that was just update for the different json structure  . hardest part was tracking down the lines  as I was unfamiliar structure  and i gave myself a 16 day forecast which is nicer for me as 8 was not quite enough  sometimes for agricultural purpose

**Comment by earlthesquirrel** [comment]
FYI -- I experienced a similar thing.  By turning off forecast and running wee_reports then turning it back on, "seemed" to fix the issue.
