### ISSUE TITLE
Pi Kiosk with Bigger Screen

### ISSUE THREAD

**Issue by trobnc** [poblabs/weewx-belchertown#711]
I like the Pi page for dedicated console in a simplified view. My only gripe is that it's tailored to 3.5 inch display. I've recently purchased a 7 inch display and would like to tailor the Pi page to this screen. Would I just change the style.css after /* Custom Raspberry Pi Kiosk Page */ ? Are there other files that I'd need to alter to fit a 7 inch display? Thank you!

**Comment by CHAMLEX** [comment]
I was able to update the Pi page to a different screen size/resolution editing that CSS file so it would fit the resolution that I needed.

**Comment by cclarke99** [comment]
> I was able to update the Pi page to a different screen size/resolution editing that CSS file so it would fit the resolution that I needed.

@CHAMLEX can you share that CSS file with us?

**Comment by CHAMLEX** [comment]
Not a problem.  This is the css file that I used for the pi page. It should fit the an 800 x 480 screen resolution.  I think it does edit some of the files that the regular page however but I mainly intend to use the Pi page to replace an old weather sensor that I had in our living room that failed a few years back.
[style.css.zip](https://github.com/poblabs/weewx-belchertown/files/7290216/style.css.zip)
o
