### ISSUE TITLE
Possible issue with Windy (likely user error or stupidity)?

### ISSUE THREAD

**Issue by ChrisM510** [poblabs/weewx-belchertown#714]
I moved back in February, and changed everything for my weather station, and everything is working OK...except that the map for Windy looks a bit different than I was expecting.  My zoom correctly closes in on my station location in Cartersville, GA when clicking the "+" symbol, however, there is a blue dot with an arrow off to the right side of the map (see picture).  I was *expecting* that the dot was my location...but it obviously isn't over my location.  I see 3 possibilities: 1) I set something up incorrectly (most likely), 2) the blue dot doesn't mean what I think it means (Princess Bride option), or 3) there is a bug (highly unlikely, but I cannot rule it out). 

Can anyone shed some light?  TIA!

![image](https://user-images.githubusercontent.com/10404766/132580045-f0a607de-040e-4776-a4ed-2b17a8019aae.png)

**Comment by poblabs** [comment]
This is actually part of windy and how they use your mobile phone or
computers location if you allow it to put you on the map. So the center
zoom should be where you specified your station coordinates but the blue
dot is allegedly where your devices location is reporting.

**Comment by ChrisM510** [comment]
Oh! ok... so that would be where Comcast says I am... LOL

Thanks!
