### ISSUE TITLE
Future Feature Request - Add Auto-Reload option of image in custom content

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#72]
Instead of reloading the main page to update images (webcam snapshots), would be nice to just reload those images in the custom content.  Maybe make it an optional feature.

**Comment by poblabs** [comment]
I could apply the same logic in https://github.com/poblabs/weewx-belchertown/commit/655c773f6b7818be27bc72ff797a267adaadeba3 to this request. I'd probably only apply it to the custom content areas if they exist. Need to do some testing, then maybe next release for this one.

**Comment by poblabs** [comment]
@Stormtracker017 Are you using MQTT Websockets for live updates? 

Right now all of the content reloads are done through functions that occur when live updates are enabled. 

If live updates are disabled then the entire page itself needs to be reloaded anyways just to get updated weewx data. 

So based on the above, I think it makes sense to implement this request with the live updates section.

**Comment by poblabs** [comment]
This will be available in skin version 1.0
