### ISSUE TITLE
If aeris map = 1 windy map is gone and no aeris map shown

### ISSUE THREAD

**Issue by europacafe** [poblabs/weewx-belchertown#721]
**Describe the bug**

**Link to your website (IMPORTANT)**
https://bthofen.com/tempest

**Version of the skin you're using**
1.2b2

**To Reproduce**
In weewx.conf, if set aeris map = 0, the Windy animated shows as usual. But if aeris map=1, the frame displaying windy map is blank.

**Expected behavior**
As explained above

**Screenshots**

**Device Information (please complete the following information):**
 - Device: Windows 10 MS Edge Chromium, Ubuntu 20.04.3 Firefox, Android phone MS edge
 - Not tested on other devices/os.

**Additional context**

**Comment by meichthys** [comment]
I'm also seeing this.
