### ISSUE TITLE
skin version .9: ReferenceError: ajaxforecast is not defined

### ISSUE THREAD

**Issue by bellrichm** [poblabs/weewx-belchertown#73]
First, thanks for all your work. This is very impressive!
I've been experimenting with using it in a very custom environment. I installed it and got realtime update working before I enabled forecasts and got this stacktrace

(index):432 MQTT message indicates this is an archive interval.
(index):396 xxxxxxx mqtt Connection Lost: AMQJS0005E Internal error. Error Message: ajaxforecast is not defined, 
Stack trace: ReferenceError: ajaxforecast is not defined
    at update_current_wx (http://xxxxx.local/html/belchertown/:435:29)
    at k.onMessageArrived (http://xxxxx.local/html/belchertown/:402:13)
    at k._receiveMessage (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:517)
    at k._receivePublish (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:52:71)
    at k._handleMessage (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:47:379)
    at k._on_socket_message (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:43:8)
    at WebSocket.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js:19:132)

Once I configured forecasts, the error did go away. So, this is more of an  FYI. 
Rich

**Comment by poblabs** [comment]
Which version did you install? 0.9 or one of the release candidates from the master branch? It'll tell you in syslog when the skin report is being generated. 

I'm not entirely sure, but I wonder if https://github.com/poblabs/weewx-belchertown/commit/b9e0a70f46fd50805b40d3324309d4606f2bcd7f fixed this issue.

**Comment by bellrichm** [comment]
It’s 0.9. Again, just a heads up, my development environment is very customized.
I haven’t done any serious customization, so have limited knowledge, but was wondering if this might be the cause. Meaning, because I did not enable forecasts, the function is not included. But on receiving mqtt data it tries to invoke it.

        #if $Extras.has_key("forecast_enabled") and $Extras.forecast_enabled == '1'
        function ajaxforecast() {
            jQuery.getJSON("$forecast_json_url", update_forecast_data);
        };

Also, i’m up and running fine. So this is really a very low priority. But obviously I am happy to test/debug anything.
Thanks again for all your work. 
Rich

**Comment by poblabs** [comment]
I'm confused now. You're probably right, but a couple more questions. I know you have a custom env, but I want to try and test the scenario so I can fix it when I release 0.9.1. 

You had MQTT on, and forecasts off? Those *should* be independent of each other.

**Comment by bellrichm** [comment]
Yes, that is exactly what I had.  MQTT on and forecast off.
Let me know if I can help.

**Comment by poblabs** [comment]
Found it, thanks for the update!
