### ISSUE TITLE
jQuery UI is loaded, but is it really used?

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#736]
:bulb: **The Idea**
In `header.html.tmpl` I find a reference to jQuery-UI:
* line 79
  ```
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  ```
* line 100
  ```
  <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  ```

The Google website check listed it as problem.

I commented it out, and I found no difference in behavior.

So I guess it could be removed.

:hammer: **Breaking Feature**
None, I hope

**HELP WANTED**
I can send a PR if necessary.

**Comment by poblabs** [comment]
If I recall, jquery-ui is used for modal for the almanac popup

**Comment by roe-dl** [comment]
The almanac modal window works fine without jQery-UI. You can check it here:
[Website with jQuery-UI commented out](https://www.woellsdorf-wetter.de)

**Comment by roe-dl** [comment]
I checked the source code for the modal popups. The classes used there are defined in `bootstrap.min.css`.

**Comment by norecords** [comment]
@roe-dl thanks, that's 290kb less to load !

**Comment by roe-dl** [comment]
I just created a ZIP file containing all those files. You can download it by:
```
wget https://www.woellsdorf-wetter.de/lib.zip
```
