### ISSUE TITLE
Black theme and forest icon

### ISSUE THREAD

**Issue by uroh** [poblabs/weewx-belchertown#738]
I've problem with forecast (not forest  :-) ) icon and dark theme!
https://ibb.co/84LtdQ4

**Comment by michaelundwd** [comment]
Thanks for spotting this.  There is a problem with the sleet.png icon that I have corrected in the attached file below.
To try it,  copy it to the images file  .../skins/Belchertown/images, overwriting the existing sleet icon.  Restart weewx and the file should be copied your server. 
Please let me know it has solved your problem (if you still have a sleet forecast!) and I will issue a PR for @pob to merge.
Michael

![sleet](https://user-images.githubusercontent.com/45148992/144754301-e7a66319-a59e-4b52-a771-b882fa34919e.png)

**Comment by ms372591** [comment]
I copied it to the directory and restarted weewx and it still has a white
background on the dark theme.

**Comment by michaelundwd** [comment]
Are you able to check your server to see that the new image has been uploaded?  It will have today's date as the modify date.

**Comment by ms372591** [comment]
It has today's date all the others have 4/30/21

**Comment by michaelundwd** [comment]
Have you tried clearing the cache on your browser?
2 questions
1 what size is the file?
2 is your website publicly available so I can take a look?

**Comment by ms372591** [comment]
The cache refresh did it. Thanks for your help!.

**Comment by uroh** [comment]
I confirm, the image is perfect! Thanks @michaelundwd

**Comment by michaelundwd** [comment]
Oh dear.  Is this the same icon giving problems?
If so, can you answer my previous questions please?
