### ISSUE TITLE
weather iconography doesn't have transparent backgrounds

### ISSUE THREAD

**Issue by imzenreally** [poblabs/weewx-belchertown#742]
so in dark mode you have light wintry mix with a white square on the dark mode -

**Comment by James-76** [comment]
This was fixed in #738

James

**Comment by poblabs** [comment]
I don't think it was updated in the master branch though? I don't remember adding it or seeing a pull request?

**Comment by imzenreally** [comment]
i pulled from master yesterday and still see it on my site

**Comment by James-76** [comment]
True.  I can submit one next week if @michaelundwd has not by then.

James

**Comment by poblabs** [comment]
No worries, I'll update it in master shortly

**Comment by poblabs** [comment]
@imzenreally feel free to grab the latest master and verify it's updated

**Comment by imzenreally** [comment]
@poblabs thanks brother - i'll update when i have a free moment

**Comment by imzenreally** [comment]
hmmm - just pulled down master and i'm still seeing the non transparent icon

**Comment by poblabs** [comment]
You typically don't have to restart weewx, but restart weewx, and wait for an archive interval. Also clear your browser cache

**Comment by imzenreally** [comment]
i'll give that a shot

**Comment by imzenreally** [comment]
💥 that was the ticket

**Comment by poblabs** [comment]
Great, closing this since you're good to go

**Comment by michaelundwd** [comment]
Apologies to all for not fixing this sooner, and my thanks to @pb for fixing it.
Michael
