### ISSUE TITLE
Rendering issues on Android 10

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#745]
So I have a new Android 10 tablet and the skin doesn't seem to render correctly in landscape mode.

Android 9
![image](https://user-images.githubusercontent.com/1351910/147168279-c2a3a94b-ee86-4ed2-961f-4e121a97d6a5.png)

Android 10
![image](https://user-images.githubusercontent.com/1351910/147168298-80349bc0-753a-40b7-abac-06840f7b6de0.png)

**Comment by poblabs** [comment]
This is a css issue. Will need someone to work on it when they have time.

**Comment by sgrayban** [comment]
Ahh ok... got any pointers that I could look for? I'm not all that versed in css.
