### ISSUE TITLE
Errors in 0.9.1 upgrade

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#75]
Got this after the upgrade from 0.9

Mar 12 09:00:46 raspberrypi weewx[8691]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar 12 09:00:46 raspberrypi weewx[8691]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/js/highcharts-yearplots.js.tmpl
Mar 12 09:00:46 raspberrypi weewx[8691]: cheetahgenerator: **** Reason: cannot find 'system_locale_js'
Mar 12 09:00:46 raspberrypi weewx[8691]: ****  Traceback (most recent call last):
Mar 12 09:00:46 raspberrypi weewx[8691]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 330, in generate
Mar 12 09:00:46 raspberrypi weewx[8691]: ****      print >> _file, compiled_template
Mar 12 09:00:46 raspberrypi weewx[8691]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Mar 12 09:00:46 raspberrypi weewx[8691]: ****      rc = getattr(self, mainMethName)()
Mar 12 09:00:46 raspberrypi weewx[8691]: ****    File "cheetah__etc_weewx_skins_Belchertown_js_highcharts_yearplots_js_tmpl_1552334446_27_13840.py", line 86, in respond
Mar 12 09:00:46 raspberrypi weewx[8691]: ****  NotFound: cannot find 'system_locale_js'
Mar 12 09:00:47 raspberrypi weewx[8691]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar 12 09:00:47 raspberrypi weewx[8691]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/js/highcharts-dayplots.js.tmpl
Mar 12 09:00:47 raspberrypi weewx[8691]: cheetahgenerator: **** Reason: cannot find 'system_locale_js'
Mar 12 09:00:47 raspberrypi weewx[8691]: ****  Traceback (most recent call last):
Mar 12 09:00:47 raspberrypi weewx[8691]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 330, in generate
Mar 12 09:00:47 raspberrypi weewx[8691]: ****      print >> _file, compiled_template
Mar 12 09:00:47 raspberrypi weewx[8691]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Mar 12 09:00:47 raspberrypi weewx[8691]: ****      rc = getattr(self, mainMethName)()
Mar 12 09:00:47 raspberrypi weewx[8691]: ****    File "cheetah__etc_weewx_skins_Belchertown_js_highcharts_dayplots_js_tmpl_1552334447_1_38359.py", line 86, in respond
Mar 12 09:00:47 raspberrypi weewx[8691]: ****  NotFound: cannot find 'system_locale_js'
Mar 12 09:00:47 raspberrypi weewx[8691]: cheetahgenerator: Generated 4 files for report Belchertown in 12.59 seconds
Mar 12 09:00:47 raspberrypi weewx[8691]: copygenerator: copied 1 files to /var/www/html/weewx/belchertown

**Comment by biltmorelaker** [comment]
@41south Are you running WeeWX version 3.9.1?

**Comment by 41south** [comment]
No, 3.8.2 still but no issues with 0.9 on that.

**Comment by biltmorelaker** [comment]
@41south I know Pat made some changes to use locale for 0.91. Maybe that change wasn't back compatible with WeeWX 3.8.2. He did make changes to get 0.9 compatible with 3.8.2. We'll need to wait for him to check in.

**Comment by poblabs** [comment]
Looks like the error is related to this line missing in [user/bin/belchertown.py](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py#L85). Can you verify you see that in your install?

**Comment by 41south** [comment]
Confirmed that does exist

**Comment by poblabs** [comment]
Have you restarted weewx since installing? If the skin is looking for it, and it exists, then I'm thinking you haven't restarted weewx yet

**Comment by 41south** [comment]
Ah, shoot, rookie error! :) . Problem sorted, thanks (going for coffee now)

**Comment by tomdotorg** [comment]
I am having a related issue with the previous line:

https://github.com/poblabs/weewx-belchertown/blob/57618035bd6da988b7dc2d96c5ab04511d9d44a1/bin/user/belchertown.py#L85

If getdefaultlocale returns (None, None) (which it does on my generic Debian docker image), the following line fails because of the None.

I don't know how the downstream components react to having no locale set (do they do something or complain?), but I would love it if it were able to operate without a server-side locale being set.

**Comment by poblabs** [comment]
> I don't know how the downstream components react to having no locale set (do they do something or complain?), but I would love it if it were able to operate without a server-side locale being set.

I have this on my to-do list for 1.0. I had complaints about locale in a previous version so I stuffed this in there to accommodate - albeit not highly tested and surely not with a docker image. 

To be honest I'm not sure how I'll handle locale in future - as a user option that the user can set?

For your issue, try changing it to `system_locale_js = "en-US"` if you have an en-US locale expectations.

**Comment by poblabs** [comment]
@tomdotorg That last reply was for you - forgot to tag you

**Comment by tomdotorg** [comment]
@poblabs - thanks. I will patch the cached local copy I have (I use Docker to deploy) and go with that for now. Thanks. This is great software. Thank you for sharing it.
