### ISSUE TITLE
pi_theme = "auto" doesnt work

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#755]
I am on the latest Weewx and Belchertown-Version.

If I configure 
`pi_theme = "auto"`

then the webpage on the PI is not changing between light/dark-mode.

In the past it changed accordingly to the time when I restarted the PI, but only when I restart. Now it doesnt change at all and it stays with the "light" theme.

**Comment by poblabs** [comment]
try debug mode - what does it say for the expected theme in the debug console? it could be set to light manually

**Comment by ebnerjoh** [comment]
`belchertown_debug = 1` ?

Do I see the output then in weewx.log or somewhere else?

If I set it to "light" or "dark" then its working. Only the automated switch is not working.

**Comment by poblabs** [comment]
you would see it in the chrome developer tools console. this may be hard to see on the pi. 

on the pi, add this to the end of the url: `?theme=auto`

So if your pi is example: `192.168.0.100/pi`, you would use `192.168.0.100/pi?theme=auto`

This will reset any overrides that may be present. then see if it works this way

**Comment by ebnerjoh** [comment]
If I use `?theme=auto` either on the normal skin or the PI-Option, then it takes the theme from the time the pages was accesssed.

Eg. If I start the PI in the night, it starts with Dark-Theme. But then it stays there. If I restart the PI during noon, its starting in Light-Theme, but again it stays there.

**Comment by poblabs** [comment]
yes, theme auto resets the theme back to automatic. so if sun is up, it's light theme. if sun is down it's dark theme.

**Comment by ebnerjoh** [comment]
Hi, and this is not working for me.

I start the PI with "auto" in the night and it starts with the dark theme. But it stays there forever.
