### ISSUE TITLE
Â is inserted before the degree symbol on my site.

### ISSUE THREAD

**Issue by 18Scoobz** [poblabs/weewx-belchertown#758]
I just updated to the current master to use the tabbed radar section for a live camera.

Before setting that up noticed that I am getting a character added before the degree symbol.

I know it is a character set issue but, do not know how to fix.

https://bigbirdsnest.net/

**Comment by poblabs** [comment]
Never seen that before. Check your skin.conf or weewx.conf for that
character. If you find it you need to restart weewx for changes to take
place

**Comment by 18Scoobz** [comment]
found them

        degree_C          =  " Â°C"
        degree_F          =  " Â°F"
        degree_compass    =   Â°
