### ISSUE TITLE
Comma in MQTT Baro

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#76]
Found this comma in the baro reading after the update to 0.9.1
It's only on the live data, the static is fine underneath (before the live data kicks in) and so are the records

Barometer | 1,016.76 mbar

**Comment by poblabs** [comment]
That's because JavaScript is now treating it as a digit with a thousands separator. This is needed for those locales which use commas for the decimal (like Spain, Germany). 

I'll have to look to see if there's a way to handle the decimal locale (period or comma), and not treat the entire digit as thousands.

**Comment by 41south** [comment]
It sure looks strange. I don't think any country formats the barometer
reading like that do they?
I may drop back to 0.9 until you solve it :)

**Comment by poblabs** [comment]
Not that I know of. A silly JS thing I noticed recently. Only affects the
real time updates for locale.

Comma bothers you that much to downgrade? :)

**Comment by 41south** [comment]
I know it's a minor thing but it just looks wrong :) Minor OCD on my part
and 0.9 was working fine for me

**Comment by poblabs** [comment]
What's the normal formatting? I found a hack job of a way to achieve this while keeping the locale decimal separator in tact.

**Comment by poblabs** [comment]
To be honest, some of this stuff should be coming from the MQTT extension, instead of me doing hack-upon-hack-upon-hack to make it right. 🤔 Might have to submit an update to the MQTT extension instead - which would clean up a lot of this foolery.

**Comment by poblabs** [comment]
To confirm, it should be `1015.73` and NOT `1 015.73`

**Comment by 41south** [comment]
Yes that's it. The barometer graphs do it too when you hover over them, you
see 1 015.12 instead of 1015.12

**Comment by poblabs** [comment]
I'm thinking the MQTT extension needs an update to respect locale. Then the skin can go back to just "showing the data it's given", rather than trying to assume. This might be planned for the 1.0 skin release in a month or so.

**Comment by 41south** [comment]
That sounds sensible  :)

**Comment by poblabs** [comment]
No word from mwall on the update to MQTT. So I'll continue to try and support things like this. Goes against the "just show what you're given" idealology but right now I'm "working with what I've got" 😃 

This update fixes this issue by removing the grouping, or thousands separator, and appears to work in all locales.

**Comment by poblabs** [comment]
For future reference, in case I need it, this is how I'm accomplishing a lot of MQTT JavaScript number locale. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
