### ISSUE TITLE
Fail skin load in weewx 4.6.0

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#761]
**First step**
```
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****  invalid literal for int() with base 10: '%'
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****      obj.start()
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 378, in start
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****      self.run()
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2714, in run
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****      series_data = self.get_observation_data(
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 3726, in get_observation_data
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****      usage_round = int(
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****  ValueError: invalid literal for int() with base 10: '%'
Feb  6 07:41:24 minipc weewx[45742] ERROR weewx.reportengine:         ****  Generator terminated
```

**Describe the bug**
Load skin fail after update weewx version 4.6.0 but I kept my weew.conf file. 
I downgraded to previous version 4.5.1

**Link to your website (IMPORTANT)**
https://meteopego.com

**Version of the skin you're using**
1.3.1b

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by James-76** [comment]
Interesting - I just upgraded to 4.6.0 to see what would happen and it appears to be running fine on my website [https://blisteringbarnacles.co.uk/](url)

```
wget http://weewx.com/downloads/weewx-4.6.0.tar.gz
tar xvfz weewx-4.6.0.tar.gz
cd weewx-4.6.0
python3 ./setup.py build
sudo python3 ./setup.py install

/home/weewx# diff weewx.conf weewx.conf.20220208215340
26c26
< version = 4.6.0
---
> version = 4.5.1
```

I hate python debug as it seems to be terrible at giving useful information so I will admit I can't tell you why it is complaining.

**Comment by dtalens** [comment]
Please, can you paste [[Defaults]] section?, thanks.

**Comment by dtalens** [comment]
Hi, thanks. The isue comes from graph.conf file because if I use default graph.conf.example it does not give an error.

**Comment by James-76** [comment]
After slowly deleting sections, and using wee_reports to test it, it was started complaining when I added the following section back in under [homepage].  

I then commented out the [[[lighting_strike_count]]] section and then it started working.

This means that there is something about how you have defined lightning_strike_count into your setup or something has changed with the weewx code with how it is being worked out.

```
     [[llamps]]
	title = "Número i distància dels llamps"
        subtitle = "Podeu consultar més gràfics de llamps al següent <strong><a href="/graphs/?graph=llamps" style="color:#e5554e">enllaç</a></strong>"
        #time_length = year
        #aggregate_type = max
        #aggregate_interval = 86400 # 1 day
        #gapsize = 86400000
        type = column
	yAxis_label = ""
        [[[lightning_strike_count]]]
           name = "Número de llamps"
           stacking = normal
        [[[lightning_distance]]]
           name = "Distància llamps (km)"
           stacking = normal
```

**Comment by dtalens** [comment]
Thanks, if I remove [[lightning_strike_count]] from my graph.conf file it will work again. Now the question would be why does this happen?

**Comment by James-76** [comment]
The error is saying that it is getting back '%' rather than an integer when looking up the StringFormats

Sounds like the obs_group is not possibly correctly defined for lighting_strike_count?

What have you defined in extensions.py for lighting_strike_count, and what happens when you search for that in belchertown/skin.conf?

eg here is my example for sunshineHours

```
# grep sunshine /home/weewx/bin/user/extensions.py
weewx.units.obs_group_dict['sunshineHours'] = 'group_radiation'

# grep group_radiation skin.conf
        group_radiation    = watt_per_meter_squared

root@pi:/home/weewx/skins/Belchertown# grep watt_per_meter_squared skin.conf
        group_radiation    = watt_per_meter_squared
        watt_per_meter_squared = %.0f
        watt_per_meter_squared = " W/m²"
```

As you can see watt_per_meter_squared is defined under [[StringFormats]] as the stringFormat for sunshineHours.

**Comment by James-76** [comment]
gjr80 has commented on weewx-user which is similar to what you are seeing [https://groups.google.com/g/weewx-user/c/VfpSRxNQits](https://groups.google.com/g/weewx-user/c/VfpSRxNQits)

"I see now there have been some changes have been introduced in WeeWX v4.6.x to how default labelling and formatting of observation types is determined and it appears that group_energy/watt_hour may have fallen through the cracks. I think we can work around the issue in your case by adding some additional lines to user/extensions.py:

weewx.units.default_unit_format_dict['watt_hour'] = '%.1f'
weewx.units.default_unit_label_dict['watt_hour'] = u' Wh'

Again you will need to restart WeeWX for the changes to take effect and hopefully the first report cycle should add you missing units/formatting.

Gary"

**Comment by dtalens** [comment]
I added this code to the `extension.py` file but it still fails:
```
import weewx.units
weewx.units.obs_group_dict['lightning_strike_count'] = 'group_count'
weewx.units.default_unit_format_dict['lightning_strike_count'] = '%d'
weewx.units.default_unit_label_dict['lightning_strike_count'] = ""
```
