### ISSUE TITLE
Wrong datas reported by mqtt

### ISSUE THREAD

**Issue by Topex22** [poblabs/weewx-belchertown#772]
Hi all !

I'm searching the issue for weeks, but can't understand. You can see at [http://www.chevrerie-du-cap.com/meteo/](url) that the data of outTemp, wind direction,  and inTemp labelled "Salle de traite" are changing when the mqtt gets Connected and reports wrong data. 

I use the last versions of mosquitto via hivemq, weewx and belchertown 1.3b1.

Until now, I always managed to solve my issues by myself, but this time, it seems to be out of my abilities ! 😁

**Comment by poblabs** [comment]
This could be because your skin is set for metric, but mqtt is set for imperial? I can't see your site but I am guessing that could be the issue. Check the weewx-mqtt configuration to make sure it's the same units
