### ISSUE TITLE
New kiosk mode files not installed by wee_extension

### ISSUE THREAD

**Issue by captain-bodge** [poblabs/weewx-belchertown#790]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

N/A skin files are not installed

**Describe the bug**

When installing skin v1.3b2 from master, the kiosk files are present in the master.zip downloaded from GitHub but are not installed into /etc/weewx/skins/Belchertown directory

**Link to your website (IMPORTANT)**

N/A

**Version of the skin you're using**

1.3b2

**To Reproduce**
1 Download master.zip from github
2 install via sudo wee_extension —install master.zip
3 install completes OK, but kiosk.html.tmpl (and other kiosk files) are not in /etc/weewx/skins/Belchertown
4 other Belchertown files are present and work fine
5 unzipping and inspecting the contents of master.zip shows the kiosk.html.tmpl files have been downloaded from github correctly 

** Expected behavior**
Kiosk files should be present

**Screenshots**

N/A

**Device Information (please complete the following information):**
 Raspberry Pi 4
Raspbian 64bit Bullseye
Weewx 4.8.0

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ThePeePs** [comment]
this was my fault, as I forgot to update install.py, I just opened PR #791 to address this, so that both kiosk.html.tmpl and kiosk.css are installed.
