### ISSUE TITLE
Add option for animated weather icons

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#797]
I think we should add an option to have these animated options. They look great! https://github.com/basmilius/weather-icons

Full portfolio of icons are here: https://bas.dev/work/meteocons

There's options for filled and outline icons.

**Comment by dtalens** [comment]
if I change PNG original image for these new SVG animated images, these are not uploaded to web.

**Comment by dtalens** [comment]
I think the best way to implement this will be by adding lottie files, although it will be to add more javascript. I don't know what will be the best ...
