### ISSUE TITLE
No 'Clear' Icon 1.3b2

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#799]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
Installed and configured master (1.3b2)
Run and see the pages (index and kiosk)
The condition is Clear, but there is no icon.
Network tab from the browser F12 shows no request for this file.

**Link to your website (IMPORTANT)**
This is on my test server not accessible from outside.

**Version of the skin you're using**
1.3b2

**To Reproduce**
1. Go to 'your Belchertown webpage during daytime in clear conditions'
2. Click on 'nothing'
3. Scroll down to 'no scroll'

**Expected behavior**
Should have an icon for the condition

**Screenshots**
Screenshot attached.

**Device Information (please complete the following information):**
 - Device: Chromebook
 - OS: ChromeOS
 - Browser Chrome
 - Version 103.0.5060.114
![weewx-belchertown](https://user-images.githubusercontent.com/12861605/180191012-a170f059-de41-4600-a496-443326dee37f.png)

**Comment by poblabs** [comment]
It looks like it's trying to get clear-night.png which should exist. Whats the url to your site?

**Comment by gary-hammer** [comment]
I'm attaching a list of the files in the images directory.
This morning, it should show mist icon, but only have the text.
[btimg.txt](https://github.com/poblabs/weewx-belchertown/files/9166897/btimg.txt)

**Comment by poblabs** [comment]
It's a bit hard to troubleshoot this way. Are there any errors in the console tab of the F12 debugger?

**Comment by gary-hammer** [comment]
I understand, but it's a testing server with no outside connectivity.
There is only the highcharts warning about enabling accessibility in the console.
The network tab shows the file is present with 200 status .
Currently it is wanting clear-day.png
The other thing is that all images show in there respective places. Sun, moon, weather forecast icons.
This seems limited to just the current condition icon display.

**Comment by poblabs** [comment]
So the 200 means it's OK. I wonder if this is something to do with the size of your screen where the image is "pushed off to the side" or something. What's the resolution of your screen?

**Comment by gary-hammer** [comment]
I've tried on different devices from my phone to a 32" 4K monitor.

**Comment by michaelundwd** [comment]
A couple of thoughts:
Are there any errors in syslog?
What is the html for the current icon?  I'm currently showing
<div class="col-sm-6 current_obs_top">
          <img id="wxicon" src="./images/mostly-clear-day.png">
</div>

Michael
http://lordshipweather.uk

**Comment by michaelundwd** [comment]
Sorry the text did not show as I intended

                                    <div class="col-sm-6 current_obs_top">
                                        <img id="wxicon" src="./images/mostly-clear-day.png">
                                    </div>
More Q's
Do any of the current icons show correctly?
Are the image files correct - can you view them directly?

**Comment by gary-hammer** [comment]
> A couple of thoughts: Are there any errors in syslog? What is the html for the current icon? I'm currently showing
> 
> ![](./images/mostly-clear-day.png)
> Michael http://lordshipweather.uk

I see that you are running b1. That one doesn't show the issue.
To answer your questions, yes all the files are good. Yes, other places where icons are used in the skin show them.

**Comment by michaelundwd** [comment]
Can't see any changes from my version to 13b2 that would explain the issue.
Looks like I should delay updating to 13b2 until this is sorted;-)

**Comment by gary-hammer** [comment]
Don't know that it matters, but sources does not show a clear.png in the tree.
These don't appear to be forecast icons, seems like condition icins.
![Screenshot 2022-07-31 9 33 30 PM](https://user-images.githubusercontent.com/12861605/182056156-6629924c-3ea0-4c2f-b782-399258523fe2.png)

**Comment by gary-hammer** [comment]
> These are all valid forecast icons, except sunrise and sunset. You can see all the icons that could be called in aeris-icon-list.json.
> 
> What value do you have for "forecast_aeris_use_metar" in your skin.config? Line 1462 in belchertown.py states that # Non-metar responses do not contain these values. Set them to empty.
> 
> Is this the same value as your operational site?

Currently, the condition is Mist. There is no forecast for Mist, and the icon image just appeared in the images directory. It is of course, not displayed. Are these are also used as forecast icons, could be. I have no problem with the forecast being displayed.

**Comment by michaelundwd** [comment]
Did you check the value of forecast_aeris_use_metar in skin.conf?  If you not using a metar forecast (ie value = 0) then the current_obs_icon and hence wxicon is set to "" which will give you a blank instead of an icon.  The current conditions icon relies on the current observation being returned by a METAR station.  See the readme for the explanation.

The same icons are used throughout.

**Comment by gary-hammer** [comment]
The icon is present in the proper directory, it is called, it even has a 200 status.
It is not displayed though.
Looking in the skins.conf was my red herring.
That option was enabled there, but disabled in weewx.conf which I just had the presence of mind to look at and change.
Presto! Icon displayed.
Thanks for your persistence, digging, and last explanation.
Now I can roll b2 out to the production server as all is working as I expect.

**Comment by gary-hammer** [comment]
It was the metar not being set.

**Comment by gary-hammer** [comment]
As mentioned, it's on a test server. No access.
I'll check for that file.
