### ISSUE TITLE
Investigate adding air quality

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#80]
Potential source: https://www.airvisual.com/air-pollution-data-api

**Comment by 41south** [comment]
The WeatherDuino I use also has a stand-alone AQ "module". The data is reported on the main station console but not passed to Weewx at the moment because it's not a part of the Davis protocol it uses. I think though that some 'Extra Temp' recordings could be used to fudge that (they are just numbers after all) and then BT 1.0 will be able to graph it too :)

**Comment by captain-coredump** [comment]
May I put in my $0.02 and suggest that extending the WeeWX database schema to match what weewx-purpleair and weewx-aqi already use would be the better way to add this support?

-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by 41south** [comment]
Ah, yes indeed, good thinking :)

Do you have links to those?

**Comment by captain-coredump** [comment]
https://github.com/bakerkj/weewx-purpleair

https://github.com/jonathankoren/weewx-aqi

I'm not familiar with the air quality stuff, so there may be other schemas out there.....

**Comment by poblabs** [comment]
I'm not familiar with it either. This request came from someone on the user group. I am not sure where on the skin I can put it either since everything is in their rows right now. Their suggestion was when the earthquake is disabled then show air quality. But I know the request could come in to show both. 

Not sure I have much bandwidth right now to make this in for 1.0, but I'll leave it as a 1.0 milestone in case

**Comment by poblabs** [comment]
@41south You're right, if you extend the database schema to include air quality like in those extensions, then Belchertown 1.0 should be able to graph it. Just need to make sure the chart options are identical to the database column names.

**Comment by poblabs** [comment]
Closing since these extension seem to fit the requirement.

**Comment by 41south** [comment]
Yes I used FilePile which worked perfectly
