### ISSUE TITLE
Kiosk Mode Windy Map Broken

### ISSUE THREAD

**Issue by gary-hammer** [poblabs/weewx-belchertown#807]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
The Windy map is broken in kiosk mode.
Works in 'regular' mode.

**Link to your website (IMPORTANT)**
None.

**Version of the skin you're using**
1.3b2

**To Reproduce**
1. Go to 'kiosk mode'

**Expected behavior**
Windy map should be displayed as in the main page.

**Screenshots**
![kiosk-2](https://user-images.githubusercontent.com/12861605/182590738-4d944f92-e5af-4c2b-b05c-99ef2083d5d0.png)
![kiosk-1](https://user-images.githubusercontent.com/12861605/182590739-770f2622-be34-429c-aa37-a82d940c7365.png)

**Device Information (please complete the following information):**
 - Device: desktop, phone
 - OS: Windows, Android, ChomeOS
 - Browser Chrome
 - Version 103.0.5060.114

**Additional context**
This also shows a highcharts not defined error, see screenshot.

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by ThePeePs** [comment]
What is the URL that is being called for the windy map? (can be found under network tab of the browser debug window)
Also, the highcharts error can be ignored (thought I had resolved all of those) since no charts are displayed on the kiosk page.

**Comment by gary-hammer** [comment]
[http://lts.lan/belchertown/%3Ciframe%20width=](url)

Looks like its being cutoff.
It is in weewx.conf as:
radar_html_kiosk = <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=42.205&lon=-72.628&detailLat=42.205&detailLon=-72.628&width=650&height=450&zoom=10&level=surface&overlay=radar&product=radar&menu=&message=true&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1" frameborder="0"></iframe>

**Comment by ThePeePs** [comment]
ah, see, you only need to set `radar_html_kiosk` to be the URL, with out the rest of the iframe info, as the rest of the iframe options are built by [the script](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py#L512-L521).  I guess I didn't make that very clear in the README.

ie: `https://embed.windy.com/embed2.html?lat=42.205&lon=-72.628&detailLat=42.205&detailLon=-72.628&width=650&height=450&zoom=10&level=surface&overlay=radar&product=radar&menu=&message=true&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1`

**Comment by gary-hammer** [comment]
Right you are, works a treat now.
Thanks for the kiosk!
