### ISSUE TITLE
Create a wiki page on all the various ways to chart

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#81]
With pictures and corresponding screenshot examples. 

For example:

----
#### This is the supported method. 

Where we take a line chart, turn off line width and turn on markers. This emulates a scatter plot, and retains the information box when you hover. 

```
        [[[testwind]]]
            title = Wind Speed / Gust
            [[[[windGust]]]]
                zIndex = 1
                lineWidth = 0
                [[[[[marker]]]]]
                    enabled = true
                [[[[[states]]]]]
                    [[[[[[hover]]]]]]
                            lineWidthPlus = 0
            [[[[windSpeed]]]]
                zIndex = 2
```

![image](https://user-images.githubusercontent.com/3484775/54777845-97ef0d00-4be9-11e9-807f-a172834cfb44.png)

#### Non-preferred method. Please use the example above.

This puts a scatter plot on the line plot which will work, but your hover information box is not as seamless and user-friendly as the method above. 

```
[Charts]
    [[day]]
        [[[testwind]]]
            title = Wind Speed / Gust
            [[[[windGust]]]]
                type = scatter
            [[[[windSpeed]]]]
                zIndex = 1
```

![image](https://user-images.githubusercontent.com/3484775/54499452-75f34300-48e8-11e9-8780-6108f37927b4.png)

And here's what it would look like if you chose "area" as the type of chart for windSpeed. 

```
        [[[windchart]]]
            title = Wind Speed / Gust
            [[[[windGust]]]]
                type = scatter
            [[[[windSpeed]]]]
                type = area
                zIndex = 1

```

![image](https://user-images.githubusercontent.com/3484775/54499526-527cc800-48e9-11e9-85df-abb41f4ec167.png)

----

#### The supported method will be to use line-as-scatter plot. 

This is where you define a line's width to be 0 and markers enabled. Thus making it look like a scatter plot, but you get the treatment of the data tooltips seamlessly inline. For example, with this configuration below you can see that all 3 observations are in the hover information box. With a scatter chart this does not work (see below).

```
[Charts]
    [[day]]
        [[[chart2]]]
            title = Wind Speed and Direction
            yaxis_min = 0
            [[[[windDir]]]]
                color = "#4242B4"
                zIndex = 1
                yAxis = 1
                yaxis_max = 360
                lineWidth = 0
                [[[[[marker]]]]]
                    enabled = true
                [[[[[states]]]]]
                    [[[[[[hover]]]]]]
                            lineWidthPlus = 0
            [[[[windGust]]]]
            [[[[windSpeed]]]]
```

![image](https://user-images.githubusercontent.com/3484775/54776819-45acec80-4be7-11e9-8f63-088a00e2c62f.png)

#### #### Non-preferred method. Please use the example above.

This method will put a scatter plot into a line chart. While the chart will work and look like the below, the hover information box will only work if you specifically hover on top of the dots. 

For a cleaner chart and better experience, please use the example above (line-as-scatter plot)

```
[Charts]
    [[day]]
        [[[chart2]]]
            # The combined Wind Chart works best in this configuration
            title = Wind Speed and Direction
            yaxis_min = 0
            [[[[windDir]]]]
                yaxis_max = 360
                type = scatter
                color = "#4242B4"
                yAxis = 1
                zIndex = 1
            [[[[windGust]]]]
            [[[[windSpeed]]]]
                zIndex = 2
```

![image](https://user-images.githubusercontent.com/3484775/54499455-7e4b7e00-48e8-11e9-87bf-4b2312971b5c.png)

**Comment by poblabs** [comment]
Stacked column chart example: 

```
[stackedTest]
    show_button = true
    button_text = Lightning
    title = Lightning
    time_length = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000
    type = column

    [[chart1]]
        title = Lightning
        [[[lightning_strikes]]]
            name = Lightning
            stacking = normal
        [[[avg_distance]]]
            name = Average Distance
            stacking = normal
```


![image](https://user-images.githubusercontent.com/3484775/57575952-136b7e80-7423-11e9-9957-57bd737d4126.png)

**Comment by poblabs** [comment]
@biltmorelaker Fun fact: images pasted here (or any issue) can be re-used in the wiki by using the link generated by GitHub when you upload it. Could save on commits by having to play the assets game!

**Comment by biltmorelaker** [comment]
Ah. Good news. I didn't realize that! It should definitely be a help.
