### ISSUE TITLE
No more colored point in tooltip

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#812]
Hi, I just figured out that point colors in tooltip doesn't work anymore. I try on desktop and mobile and Firefox and Chrome, I have same results.
But it's still working on charts with custom css/tooltip like on radial or year range temperature.
![Capture d’écran de 2022-08-14 16-04-11](https://user-images.githubusercontent.com/12499787/184540810-f5e78834-86a9-45e9-82fd-6a7e58f61d81.png)
![Capture d’écran de 2022-08-14 16-04-40](https://user-images.githubusercontent.com/12499787/184540813-6c3b4f67-4fbc-427e-92f1-9db35ee1cb60.png)
No error or warn in dev console.
Maybe due to an Highcharts update, have to be investigated.

I had to downgrade to version 9.3.3 to make it work again without modifying the code.

See also this [jsfiddle](https://jsfiddle.net/sgax14vn/) I've opened.

**Comment by norecords** [comment]
After a thread opened on [stackoverflow](https://stackoverflow.com/questions/73409627/highcharts-series-color-doesnt-work-between-9-x-and-10-x-with-tooltip-formatter/73419186#73419186) I got an answer from Highcharts team who opened an issue that can you can track [here](https://github.com/highcharts/highcharts/issues/17627).
We have to use another quotation marks configuration to achieve the correct tooltip format.
I'll give a shot that weekend and have an PR asap.

**Comment by norecords** [comment]
I've build my own highcharts files from the master repo that fix lot's of issues.
You can download them here
https://meteo.correns.org/highcharts/10.2.0-commit-17634/highstock.js
https://meteo.correns.org/highcharts/10.2.0-commit-17634/highcharts-more.js
https://meteo.correns.org/highcharts/10.2.0-commit-17634/modules/exporting.js
https://meteo.correns.org/highcharts/10.2.0-commit-17634/modules/solid-gauge.js

**Comment by James-76** [comment]
This has also been fixed in the Aug release of the code.

![image](https://user-images.githubusercontent.com/59254774/187746265-06466ad4-509a-481c-88e3-5218b6996dac.png)

**Comment by poblabs** [comment]
Working for me too now
