### ISSUE TITLE
aggregation types defined by XTypes extensions are not supported for chart generation

### ISSUE THREAD

**Issue by Jterrettaz** [poblabs/weewx-belchertown#818]
The use of new aggregation types defined in XTypes extensions generate errors when used in chart definition.

For example, using `historical_min` and/or `historical_max` of the Xaggs extension ( https://github.com/tkeffer/weewx-xaggs ) with this chart definition :

```
[monthcharts]
         show_button = true
[[monthhistorical]]
         [[[min]]]
             label = min
             aggregate_type = historical_min
             aggregate_interval = day
             observation_type = outTemp
         [[[outTemp]]]
         [[[max]]]
            label = max
            aggregate_type = historical_max
            aggregate_interval = day
            observation_type = outTemp
```
The error is :
```
Traceback (most recent call last):
  File "/usr/share/weewx/user/belchertown.py", line 3742, in get_observation_data
    (time_start_vt, time_stop_vt, obs_vt) = weewx.xtypes.get_series(
  File "/usr/share/weewx/weewx/xtypes.py", line 116, in get_series
    raise weewx.UnknownType(msg)
weewx.UnknownType: 'outTemp' or 'historical_min'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
    self.run()
  File "/usr/share/weewx/user/belchertown.py", line 2764, in run
    series_data = self.get_observation_data(
  File "/usr/share/weewx/user/belchertown.py", line 3750, in get_observation_data
    raise Warning(
Warning: Error trying to use database binding wx_binding to graph observation outTemp. Error was: 'outTemp' or 'historical_min'.
```

These aggregation types are working when using the ImageGenerator of Weewx (Seasons skin) with the following chart definition : 
```
[[[monthhistorical]]]
         [[[[min]]]]
             label = min
             aggregate_type = historical_min
             aggregate_interval = day
             data_type = outTemp
         [[[[outTemp]]]]
         [[[[max]]]]
            label = max
            aggregate_type = historical_max
            aggregate_interval = day
            data_type = outTemp
```

**Comment by Jterrettaz** [comment]
After investigation, here are more details.
The aggregate type `historical_min` and `historical_max` require, for each day, that the timespan cover the whole day : timespan.start and timespan.stop should be midnight. 
With this new chart definition , including `start_at_midnight= true` : 
```
[[monthhistorical]]
        time_length = 2764800
         [[[min]]]
             label = min
             aggregate_type = historical_min
             aggregate_interval = day
             observation_type = outTemp
             start_at_midnight = true
         [[[outTemp]]]
            start_at_midnight = true
         aggregate_interval = day
         [[[max]]]
            label = max
            aggregate_type = historical_max
            aggregate_interval = day
            observation_type = outTemp
            start_at_midnight = true
```
there is unfortunately still an error with the last day. The timespan generated by the Belchertown skin for the last (current day) start at midnight en ends at the time of the last archive record and not at midnight, causing the error.

Using the Imagegenerator and the Season's skin definition shown above, the timespan of the last and current day is from midnight to midnight, and no error is generated.

**Comment by James-76** [comment]
Hi @Jterrettaz 

I can see the issue, but currently not sure the best way to resolve it, because there are differences on how imagegenerator.py (which is used by seasons) and belchertown.py works with TimeSpan to get a range of timestamps for the get_series queries.

I need to do some more playing here, but I'm not sure it will be a quick response.

Previously I introduced a insert_null_value_timestamps_to_end_ts function to handle xtypes behavior changes.

James

**Comment by Jterrettaz** [comment]
@James-76  : thanks for your reply.
Just an idea, but maybe adding of a new option such as `stop_at_midnight = true` that would force the end of the timespan at the end of the day may work
In that case, the use of both `start_at_midnight = true` and `stop_at_midnight = true` could be compatible with xtypes aggregation type that require a timespan covering a full day, from midnight to midnight.

**Comment by James-76** [comment]
Yes that does like a possible idea.

I'm still trying to go through imagegenerator.py and weeutil.py and really get my head around what Tom's code is doing and when and how it is setting the get_series query to stop at midnight.  I want to make sure I'm not duplicating the work of existing weewx functions

James

**Comment by roe-dl** [comment]
This is quite easy: To get `get_series` to stop at midnight you need to pass a timespan to that function that stops at midnight. The timespan is the 2nd parameter to `get_series`. 

So the task is to align the timespan to midnight before the call of `get_series` in `belchertown.py`.
