### ISSUE TITLE
incorrect rain data

### ISSUE THREAD

**Issue by areax99** [poblabs/weewx-belchertown#820]
Please don't delete these questions! They are asked for almost every problem: answering as below saves us time from asking them!

**First step**
Try debugging the skin yourself. If you can't figure it out, include the debugging information (text, screenshots, etc.). Check out this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

** Describe the bug **
When MQTT is used, the rainfall data in the central quadrant differs from the one reported below in the Snapshots section of today's weather recording

** Link to your website (IMPORTANT) **
https://meteoquadrivio.altervista.org/

** Version of the skin you are using **
ver 1.3b1

**Reproduce**

** Expected behavior **

** Screenshot **
![Schermata 2022-09-25 alle 19 37 00](https://user-images.githubusercontent.com/70453504/192157519-41a845d7-eeda-4120-9491-f1a6b3909a33.png)
![Schermata 2022-09-25 alle 19 38 24](https://user-images.githubusercontent.com/70453504/192157520-69386375-9e55-4d13-ac46-74db9bb6547f.png)

** Device Information (complete the following information): **
 - Device: Raspberry
 - Operating system: Raspberry OS
 - Chrome, Safari browser
 - Latest version

**Comment by areax99** [comment]
Problem solved. I hadn't set the unit of measure to 'mm' in the MQTT section

**Comment by michaelundwd** [comment]
I have the same problem as you.  In which file did you change the unit of measure to 'mm' please.

**Comment by James-76** [comment]
@michaelundwd; I'm guessing the weewx.conf as this is my entry which is working...

```
    [[MQTT]]
        server_url = mqtt://xxxxx@localhost:1883/
        topic = weather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        [[[inputs]]]
            [[[[dayRain]]]]
                units = mm
            [[[[rainRate]]]]
                units = mm_per_hour
            [[[[windSpeed]]]]
                units = knot
            [[[[windGust]]]]
                units = knot
```

**Comment by michaelundwd** [comment]
@James-76; Thanks for the listing.  I have copied the units into my weewx.conf and the mqtt rain data is now correct. It's been bugging me for a while, so it's nice to have it fixed.
Thanks
Michael
