### ISSUE TITLE
"Tired of using an old outdated MQTT client" error

### ISSUE THREAD

**Issue by jkumeboshi** [poblabs/weewx-belchertown#823]
**Describe the bug**
Suddenly the MQTT client of the station web page stopped working with "test.mosquitto.org" MQTT server.

```
MQTT: MQTT Connected. Subscribing. [belchertown.js:40:17](https://meteo.fedibox.com/js/belchertown.js?1664885078)
MQTT: Tired of using an old outdated MQTT client?
Try MyMQTT, the simple Message Queuing Telemetry Transport client for Android and iOS
[https://mymqtt.app?utm_source=mqtt&utm_medium=link&utm_campaign=mqtt](https://mymqtt.app/?utm_source=mqtt&utm_medium=link&utm_campaign=mqtt)

Have a nice day! [belchertown.js:40:17](https://meteo.fedibox.com/js/belchertown.js?1664885078)
MQTT: 2022-10-04T14:07:13+02:00: mqtt Connection Lost: AMQJS0005E Internal error. Error Message: JSON.parse: unexpected character at line 1 column 1 of the JSON data, Stack trace: No Error Stack Available
```

**Link to your website (IMPORTANT)**
https://meteo.fedibox.com/

**Version of the skin you're using**
last development from git repo

**To Reproduce**
just go to my website https://meteo.fedibox.com/?debug=true

**Device Information (please complete the following information):**
 - Device: desktop
 - OS: windows 10
 - Browser: Firefox and Chrome
 - Version: latest browser versions

**Comment by fvirgola80** [comment]
Hello,
i had your same problem the solution is to change the topic name in both wees.conf and skin.conf

**Comment by jkumeboshi** [comment]
@fvirgola80 thanks very much, I've changed the MQTT topic and now it works again
