### ISSUE TITLE
Language support in weewx 4.9.1

### ISSUE THREAD

**Issue by uroh** [poblabs/weewx-belchertown#830]
Hello,
in the last update of weewx v.4.9.1 the language support has been inserted in a modular way.
Specifically, in the "weewx.conf" configuration file there is an option called "lang = it". In my case this option determines the error below:
Cannot read localization file /etc/weewx/skins/Belchertown/lang/it.conf for report 'Belchertown': Config file not found: "/etc/weewx/skins/Belchertown/lang/it.conf"

In your opinion, is it possible to integrate the support also in the Belchertown theme?
ThankU

**Comment by norecords** [comment]
I'm also on weewx v.4.9.1, if you don't give that option `lang = ...` there's no error. It's maybe time to give Belchertown' template officials translations to fit the weewx's config !

**Comment by uroh** [comment]
watch my pull...
Add
```
[StdReport]
    [[Defaults]]
        lang = it
```

**Comment by norecords** [comment]
yes I saw it, but if you don't give that option, there's no error because we have translation in weewx.conf, or skin.conf... so at first we don't need `etc/weewx/skins/Belchertown/lang/--.conf`
Like I said it's maybe time to give Belchertown's template officials translations and files...

**Comment by roe-dl** [comment]
This kind of language support started in WeeWX version 4.6.

As a start for existing installations you can create an empty language file. Then, there is no error any more.

**Comment by roe-dl** [comment]
There were pull request to this issue. What about them?

**Comment by olpayras** [comment]
Thanks a lot @roe-dl 

@norecords : very interested in french translation, when you will have done it. ;)
