### ISSUE TITLE
Timestamp picture webcam

### ISSUE THREAD

**Issue by f4gqk** [poblabs/weewx-belchertown#844]
hello, 

I have a weather webcam that takes photos every 30 minutes, I would like to have on my photos, the timestamp with the temperature, humidity ....

how to do ???

Thanks

Mon site météo : www.meteo-guignes.fr

Sebastien

**Comment by norecords** [comment]
@f4gqk I do it in Python with [Wand](https://docs.wand-py.org/en/0.6.10/) and [ImageMagick](https://imagemagick.org/index.php), I load the weewx_data.json into my Python program.

**Comment by norecords** [comment]
@f4gqk I publish a piece of my python program on [gist](https://gist.github.com/norecords/17f1714d0e1ee60f27ae0c1c36882d02) that you could take a look

**Comment by f4gqk** [comment]
Thanks, I will test
