### ISSUE TITLE
canonical doesn't change on others pages

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#847]
Hi there, there is a canonical url problem.

https://github.com/poblabs/weewx-belchertown/blob/bc1614642ed7d5f45705f7fc22e8dab93eaab966/skins/Belchertown/header.html.tmpl#L59-L61

I suggest to change for
```
        #if $station.station_url and $page == "home"
        <link rel="canonical" href="$station.station_url" />
        #elif $station.station_url and $page != "home"
        <link rel="canonical" href="$station.station_url/$page" />
        #end if
```
and add `#set global $page = "NAME_OF_PAGE"` to every pages.

**Comment by roe-dl** [comment]
> and add #set global $page = "NAME_OF_PAGE" to every pages.

There is no need to do so, as WeeWX stets $page to the name of the actual page.

**Comment by norecords** [comment]
@roe-dl can you add this to a pull request, I think it should be fixed before next release!

**Comment by roe-dl** [comment]
Done. #848

**Comment by norecords** [comment]
That have been merge in 1.3 release
