### ISSUE TITLE
Page cut off

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#85]
Im sure this is some simple issue, but I have the skin in its own directory, as I was having issues with reporting so I wanted to seperate those. But on both mobile and standard websites the left part of the page is cut off. see attached. 
![Screen Shot 2019-03-24 at 8 18 41 PM](https://user-images.githubusercontent.com/13274298/54888350-e19e5880-4e72-11e9-9de9-1c38a2e977ab.png)
cant wait for the 1.0 release to add additional sensors!

**Comment by biltmorelaker** [comment]
@slvrscoobie, Did you set 

> belchertown_root_url = "http://your_full_website_url"

In the [[[Extras]]] stanza of weewx.conf? It needs to be the full url of your website (for instance mine is https://wx.kutzenco.com).

**Comment by poblabs** [comment]
@biltmorelaker's got it. Check out the requirements (and all of the options) for more help @slvrscoobie https://github.com/poblabs/weewx-belchertown#requirements

**Comment by slvrscoobie** [comment]
I'm running it locally. I have it set to my local ip. I'm not serving this
externally. Is that incorrect?

**Comment by poblabs** [comment]
@slvrscoobie No matter what you need to define `belchertown_root_url`. 

> You need to define your URL for the skin to work properly. The full URL to your website without a trailing slash. Example: http://yourwebsite.com or http://192.168.1.100. **Even if your website is on your LAN only, this needs to be enabled.**

In your case it would be belchertown_root_url = http://192.168.44.36/weewx`. Save and restart weewx.

**Comment by slvrscoobie** [comment]
Got it. The IP address threw me. I had 192.168.44.36, I changed to
http://192.168.44.36 and it worked. Thanks!
