### ISSUE TITLE
Windrose tooltip is under layer of cardinals points and the legend

### ISSUE THREAD

**Issue by norecords** [poblabs/weewx-belchertown#850]
That's the case on Firefox and Chrome, and both light or dark mode. I think that's just a z-index problem.
![Capture d’écran de 2022-12-20 21-41-39](https://user-images.githubusercontent.com/12499787/208763273-4640342f-b63b-4f9f-8929-1a65cf3bf26d.png)

**Comment by norecords** [comment]
Following that [topic](https://www.highcharts.com/forum/viewtopic.php?f=9&t=24976), setting [tooltip.outside](https://api.highcharts.com/highcharts/tooltip.outside) to `true` fix this issue.

https://github.com/poblabs/weewx-belchertown/blob/bc1614642ed7d5f45705f7fc22e8dab93eaab966/skins/Belchertown/js/belchertown.js.tmpl#L2468-L2473

```
                // Reset the tooltip
                options.tooltip = {}
                options.tooltip.outside = true;
                options.tooltip.shared = true;
                options.tooltip.valueSuffix = '%';
                options.tooltip.followPointer = true;
                options.tooltip.useHTML = true;
```

![Capture d’écran de 2022-12-21 09-20-51](https://user-images.githubusercontent.com/12499787/208855380-429caa4b-a75e-4cd1-b260-93293479a0e5.png)

**Comment by ddperso** [comment]
can you take this modification into account in the next version
Thanks

**Comment by norecords** [comment]
Hi @ddperso I'll open a  PR asap. Nice to read you again.
