### ISSUE TITLE
mqtt websockets userName and password not included as options for client.connect

### ISSUE THREAD

**Issue by mshoultz66** [poblabs/weewx-belchertown#852]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
debug indicated a failed connection to my MQTT websocket broker

**Describe the bug**

Skin fails to allow websites to make web sockets connections to MQTT brokers that require a username and password.

**Link to your website (IMPORTANT)**
https://backyardweather.org  (Note I was able to fix the issue, so doesn't show up on my website)

**Version of the skin you're using**
v1.2

**To Reproduce**
added MQTT websockets configuration to a server that requires SSL and username and password

**Expected behavior**

`**Screenshots**`
N/A

**Device Information (please complete the following information):**
N/A

**Additional context**
Add any other context about the problem here. Maybe a potential fix?
Modify belchertown.js.tmpl to include userName and password as client.connect options

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch! 
I'm just a hack and don't really know how to use github yet.  Below are the modifications I made to the belchertown.js.tmpl

`    var options = {
        #if $Extras.has_key("mqtt_websockets_ssl") and $Extras.mqtt_websockets_ssl == '1'
        useSSL: true,
        #else
        useSSL: false,
        #end if
        #if $Extras.has_key("mqtt_websockets_username")
        userName: "$Extras.mqtt_websockets_username",
        #end if
        #if $Extras.has_key("mqtt_websockets_password")
        password: "$Extras.mqtt_websockets_password",
        #end if
        reconnect: true,
        onSuccess:onConnect,
        onFailure:onFailure
      }`

**Comment by norecords** [comment]
It's all ready in use on 1.3b version, just install Belchertown skin from the master repo and you will get this option, and many more..

**Comment by mshoultz66** [comment]
I see that now.  Thanks for pointing it out.  I had only installed the released version.
