### ISSUE TITLE
Feature Request - Click on a Dark Sky forecast cell to open a corresponding detailed forecast

### ISSUE THREAD

**Issue by biltmorelaker** [poblabs/weewx-belchertown#86]
It would be valuable if clicking on one of the 8 table cells that show upcoming Dark Sky forecasts would open a web page for the detailed Dark Sky forecast corresponding to the appropriate location and day. 

Dark Sky forecast URLs specifying latitude, longitude and date look like this: [https://darksky.net/details/35.538,-82.642/2019-3-30/us12/en](url). So, it should be easy to generate a link that each cell could open to provide a corresponding Dark Sky web forecast.

**Comment by poblabs** [comment]
Initially I didn't want to do a modal overlay, but I think I might. It's not as aggressive as a blind forward off the site.

**Comment by poblabs** [comment]
Initially I wanted to do a modal overlay, and I'm still torn on that thought. Forwarding off-site is a bit aggressive, but their site would show the latest up-to-date information as opposed to the Belchertown skin with downloads updates every `x`* minutes. _(*site-owner defined timeframe)_

All of the data that I think you'd want is within the JSON that's downloaded. Example:

```
      {
        "time": 1553745600,
        "summary": "Mostly cloudy starting in the afternoon.",
        "icon": "partly-cloudy-night",
        "sunriseTime": 1553769607,
        "sunsetTime": 1553814678,
        "moonPhase": 0.76,
        "precipIntensity": 0.0003,
        "precipIntensityMax": 0.0029,
        "precipIntensityMaxTime": 1553828400,
        "precipProbability": 0.05,
        "precipType": "rain",
        "temperatureHigh": 53.73,
        "temperatureHighTime": 1553799600,
        "temperatureLow": 41.31,
        "temperatureLowTime": 1553857200,
        "apparentTemperatureHigh": 53.73,
        "apparentTemperatureHighTime": 1553799600,
        "apparentTemperatureLow": 36.04,
        "apparentTemperatureLowTime": 1553821200,
        "dewPoint": 25.74,
        "humidity": 0.59,
        "pressure": 1028.68,
        "windSpeed": 8.72,
        "windGust": 27,
        "windGustTime": 1553821200,
        "windBearing": 196,
        "cloudCover": 0.26,
        "uvIndex": 5,
        "uvIndexTime": 1553788800,
        "visibility": 10,
        "ozone": 365.07,
        "temperatureMin": 28.75,
        "temperatureMinTime": 1553763600,
        "temperatureMax": 53.73,
        "temperatureMaxTime": 1553799600,
        "apparentTemperatureMin": 23.2,
        "apparentTemperatureMinTime": 1553767200,
        "apparentTemperatureMax": 53.73,
        "apparentTemperatureMaxTime": 1553799600
      },
```

So I'm not sure if it makes sense for me to display this information (which I am already doing just without the `summary`), or just send you off to their website.

**Comment by biltmorelaker** [comment]
What I am thinking is clicking on the cell (or a link in the cell) which would open a new tab at the Darksky site, just like you open a new tab when you click on a weather alert. Once you are on that tab, you see how conditions are forecast to change throughout the day as well as hourly information on temp, wind, humidity, UV, etc. as you drag a line indicator across the day. In addition, the Darksky tab will show hourly predictions for temperature, precip probability, etc. See below.

Returning to Belchertown is as easy as closing the Darksky tab.

Maybe you can add a link at the bottom of each cell that says "Click for Full Forecast" or something similar.

![Annotation 2019-03-26 163905](https://user-images.githubusercontent.com/44727343/55031786-c0aa4480-4fe5-11e9-8192-0d36a626af76.png)
![Screenshot_2019-03-26 Dark Sky - Saturday, Mar 30th, 2019 - 398 Fennel Dun Circle, Enka Village, NC](https://user-images.githubusercontent.com/44727343/55031540-306bff80-4fe5-11e9-9b25-2b0c8890a6fc.png)

**Comment by biltmorelaker** [comment]
Thanks! This is perfect.
