### ISSUE TITLE
Strange chart bug when update

### ISSUE THREAD

**Issue by Topex22** [poblabs/weewx-belchertown#860]
Hello everyone and best wishes for the new year.

 This is what happens when I upgrade from belchertown.py v1.2 to belchertown.py v1.3

 ![This is an image](http://chevrerie.du.cap.chez-alice.fr/Bel_smooth.jpg)

 ![This is an image](http://chevrerie.du.cap.chez-alice.fr/Bel_scale.jpg)

 I absolutely don't understand why.

 Particularity: this is data that I added manually to the database.

 If you have an idea...

_Originally posted by @Topex22 in https://github.com/poblabs/weewx-belchertown/discussions/859_

**Comment by Brezentrager** [comment]
Same issue here after updating from 1.2b6 to 1.3

For some observations (e.g. humidity) the decimals get ignored in the plots.
