### ISSUE TITLE
Forecast not working

### ISSUE THREAD

**Issue by swfrx** [poblabs/weewx-belchertown#861]
I have created a new test WeeWx system with the latest versions of everything:

- Raspbian GNU/Linux 11 (bullseye)
- WeeWx 4.9.1
- Bechertown 1.2

I have set forecast_enable = 1 and put in my id & secret for Aeris.

forecast.json is generated, but there is no Forecast in the website, just the heading '7 Day Forecast' where it should be.  See:

https://test.muchty-weather.org.uk/belchertown/

The forecast.json looks OK.  I had to add '.txt.' to the end of the filename to get it to upload.

[forecast.json.txt](https://github.com/poblabs/weewx-belchertown/files/10467337/forecast.json.txt)

Any ideas?  I tried copying over the skin from my live Pi (from 2018 I think) and that happily displayed the forecast.  I notice the forecast.json from live - working - has a few additional items at the end:

`, "aqi": [{"success": true                 , "error": {"code": "warn_no_data", "description": "Valid request. No results available ba                 sed on your query parameters."}, "response": []}]}`

However the test system has parameters for AQI which didn't come in the skin.conf from my new installation.

**Comment by michaelundwd** [comment]
I've just tried your website https://test.muchty-weather.org.uk/belchertown/ and its showing the forecast just fine, timed at 14,25 hours.  Could this be a browser cache problem?

**Comment by swfrx** [comment]
So it is!  It must be, I feel a bit stupid now.  Thanks.

**Comment by swfrx** [comment]
No, it comes & goes.  At one point I thought it was OK when using the URL from outside my home, but not when using the Pi’s IPA.  This morning there is no forecast.  I’ve compared the source from the two pages in Notepad++.  I think this is the relevant part.  TEST is on the left, LIVE on the right.

The older version on LIVE was tedious at first, but I think that was the time to produce forecast.json.  It’s present & correct on TEST.  The only obvious difference between that & LIVE is the presence of some AQI information at the end of the LIVE file.


***@***.***

**Comment by swfrx** [comment]
OK pinned it down.  I used the 'Latest' link on the home page to get my skin, but that gets v1.2 instead of v1.3b2.

**Comment by swfrx** [comment]
I found master.zip on my live Pi, installed that, fixed the skin.conf and all is well.  I've made a comment about what to actually use in my notes about customising the skin, and I've saved master.zip along with the notes document, in a 'cloud',
