### ISSUE TITLE
Method of Only Logging MQTT Failures?

### ISSUE THREAD

**Issue by mikewren** [poblabs/weewx-belchertown#87]
I'm receiving the confirmatory lines in /var/log/syslog every other second that MQTT is happily doing its thing:

Mar 27 12:16:23 WebsterWxPi weewx[31144]: restx: MQTT: Published record 2019-03-27 12:16:23 EDT (1553703383)

This is occurring despite setting log_success = False in weewx.conf.

I'm running weewx on a raspberrypi and have /var/log mounted to a ramdisk to try and keep disk writes to a minimum, maintaining non-chatty syslog for me is a good thing.

Any guidance would be much appreciated - thanks for all your work on the skin, looking forward to the 1.0!  👍

**Comment by biltmorelaker** [comment]
@mikewren
Under the [[MQTT]] stanza enter

> log_success = False
> log_failure = True

**Comment by mikewren** [comment]
🤦‍♂️ That was really obvious, thanks for pointing it out. 

I incorrectly presumed the primary weewx logging statements would supersede.

**Comment by biltmorelaker** [comment]
Happy I could help. I make mistakes like that all the time 😉.

**Comment by poblabs** [comment]
Glad this worked! I spoke with mwall about this a while ago since he is the developer of the weewx-mqtt extension and I believe he has plans to release an update which honors the weewx logging statements as you would expect. 

I do not have any info on a release date on that, so I'm glad this is a work-around until then

**Comment by mikewren** [comment]
A brief mention of this in your MQTT guide may be worthwhile.

**Comment by poblabs** [comment]
In the readme i mention there that I'm not the developer of that extension.

But how to turn it off I can add since it seems to be working.
