### ISSUE TITLE
Air pressure drop alert in barometer graph

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#88]
It would be interesting if an air pressure drop alert can be added to the barometer graph, like a diamond or other symbol. When there is a pressure drop higher than a defined threshold (2 ~ 4hPa or more) over a period of 3 hours. It will allow to check how many severe drops accurred in a time period.

**Comment by poblabs** [comment]
Do you know if this information available through an API or within weewx or something? 

Remember, the skin reports "what it's given". It doesn't cache any information, so historical look-backs aren't supported within the skin. However if this data came from a weewx extension or darksky or something, then maybe this could be done?

**Comment by poblabs** [comment]
For example the Barometer trend arrow (up or down) comes from weewx and the built-in `$trend.barometer` tag.

**Comment by HoracioDos** [comment]
Hi Pat.
AFAIK $trend.barometer gives barometer's delta (for example -0.5 mbar or other positive o negative value) in the last 3 hours or for a user defined period. I wanted to know if you find useful to add some symbol in the barometer line graph (like a milestone in project management) when there's a severe pressure drop. (I don't know how hard in can be). In general, big pressure drops in short times are signs for a storm.
I also required some advice in weewx group about creating new labels to check if it rains everytime that a barometer alert occurs in a time period.
https://groups.google.com/forum/#!topic/weewx-user/3e_WBTfDglw
Thanks for your patience

**Comment by poblabs** [comment]
My point about `$trend.barometer` is that the skin is not generating that. It is showing the value of the observation it is provided. 

So to show something like a milestone in pressure drop, I would need a way to inject that data point into the JSON array (have a look at your website/json/day.json). I need to feed that data point into the chart from this array file. 

So like with `$trend.barometer`, maybe if there's a way to have this data so it's in a `$tag` with a `timestamp` then maybe it is possible to overlay it into the chart?

**Comment by HoracioDos** [comment]
I think I understand better now. you'll need some sort of alert tag with a pressure value and a timestamp to overlap that is not given by default. I understand that it's too much trouble for a small thing. I'll try to create my own tags and wait for v1 to see the new graphs capabilities. I'll close this request if you agree.

**Comment by poblabs** [comment]
Let's leave it open for a few days to see if someone replies to your forum post and if it's something we could use.

**Comment by bonjour81** [comment]
May I suggest a (maybe not so good) idea?
Would it  be possible to copy a range of the barometer curves, let's say last 3hours, to draw a red curve on top of the normal curve. 

This behaviour would be enabled only if negative $trend is high enough 

That would display a red highlighted curves on last 3h if trend is highly negative?


I guess it will be  a bit weird when selecting some points of the curves to show values (showing 2 times same value?)

**Comment by poblabs** [comment]
@HoracioDos I'm not sure we'll be able to do this. I haven't thought of a good way. I don't like showing the same value twice either. I'm going to close this as not implemented. If I come across something in the future we can look at it then.

**Comment by HoracioDos** [comment]
Hello Pat
Don't worry about it. I didn't invest too much time in that yet. When I have something to show we can talk about it again in the future.
Thanks!
