### ISSUE TITLE
Skin broken after Highcharts update

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#881]
Today suddenly no charts were shown any more. I looked around and found out that Highcharts just released a new version. I solved the problem as follows:

* Go to the [Highcharts changelog](https://www.highcharts.com/blog/changelog/).
* Download the version v10.3.3 there.
* Unpack the ZIP file
* Look for the files `exporting.js`, `highcharts-more.js`, `highstock.js`, and `solid-gauge.js`. They are in different sub-directories.
* On the computer running WeeWX create a path `lib/js/highcharts` within the Belchertown skin directory.
* Copy the files there.
* In `header.html.tmpl` replace
  ```
        <script type='text/javascript' src='//code.highcharts.com/stock/highstock.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/highcharts-more.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/modules/exporting.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/modules/solid-gauge.js'></script>
  ```
  by
  ```
        <script type='text/javascript' src='$relative_url/lib/js/highcharts/highstock.js'></script>
        <script type='text/javascript' src='$relative_url/lib/js/highcharts/highcharts-more.js'></script>
        <script type='text/javascript' src='$relative_url/lib/js/highcharts/exporting.js'></script>
        <script type='text/javascript' src='$relative_url/lib/js/highcharts/solid-gauge.js'></script>
  ```
* In `skin.conf` add `, lib/*` at the end of the `copy_once` line.
* Restart WeeWX

After that the charts should be there again. 

If you want to know why `lib/js/highcharts` see https://github.com/poblabs/weewx-belchertown/discussions/810

**Comment by James-76** [comment]
Thanks @roe-dl 

People can also work around this by just updating header.html.tmpl to download a specific version

```
        <script type='text/javascript' src='//code.highcharts.com/stock/10.3.3/highstock.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/highcharts-more.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/exporting.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/solid-gauge.js'></script>
```

James

**Comment by ArendPWS** [comment]
This fix worked for me:

Edit belchertown.js.tmpl

Find this line at the end of the file:

var chart = new Highcharts.chart(options);

Change chart in Highcharts.chart to uppercase like this:

var chart = new Highcharts.Chart(options);

Save and wait for WeeWX (cheetah) to generate a new set of files

Charts have a bit of a different look (especially fontsizes) in this new version of Highcharts, so perhaps that will require some tweaking.

**Comment by poblabs** [comment]
Does it make sense to specify the specific 10.3.3 version?

**Comment by ddperso** [comment]
No of course, it's a workaround.
Pat, your graphs on your site are OK, do you use Highcharts 11.0?

**Comment by 101jallen** [comment]
I used @James-76's solution since that makes sense to use the older version of Highcharts as a workaround for now. Seems to be functioning as it used to.

I will add you all are awesome for opening this thread, I would never have found a solution to this. Thank you!

**Comment by kacnje** [comment]
I'm in the same boat. I noticed the problem this morning and searched for what was going on. 
Can we just wait for the author's solution (and be without graphs in the meantime)? I'm asking because I don't have an easy access to my server (well it takes some time).

**Comment by James-76** [comment]
> Pat, your graphs on your site are OK, do you use Highcharts 11.0?

@ddperso, Pat has implemented my suggested quick fix/work around on his website - view-source:https://belchertownweather.com//

**Comment by roe-dl** [comment]
Why did I download the files of the old version and stored them to my web server? (Besides not knowing the paths @James-76 offered)
* It was some kind of a shock to me to see the web site without graphs today in the morning. What if I had no time to care about that situation? So the conclusion was: Never rely on other people's servers.
* I live in Europe. There is the GDPR around. That suggests to store the files on the own server, too. That's why I refered to discussion https://github.com/poblabs/weewx-belchertown/discussions/810

**Comment by pannetron** [comment]
Using @james-76's workaround, all good now on my end.

**Comment by vinceskahan** [comment]
@james-76's workaround definitely works, but I see the font differences.   I went with a slightly modified variant of @roe-dl's initial workaround since personally I like having all the pieces locally and not need to rely on any upstream servers whenever possible.

Personally I'd favor having Belchertown include all the pieces locally so you never need to rely on any upstream servers after the skin is installed.  I know there are plusses/minuses of that approach of course for security vs. supportability so it's a tough decision.

**Comment by roe-dl** [comment]
> Personally I'd favor having Belchertown include all the pieces locally so you never need to rely on any upstream servers after the skin is installed. 

I updated the ZIP file with all the external resources at https://www.woellsdorf-wetter.de/lib.zip It includes the Highcharts files now.

**Comment by gldickens3** [comment]
@James-76's workaround worked for me!

**Comment by msman0** [comment]
@roe-dl Thank you very much, it works also at my site.

**Comment by mrneutron42** [comment]
Also used @James-76 workaround.  Thanks!

**Comment by schematt** [comment]
@James-76  Thanks!

**Comment by ddperso** [comment]
@roe-dl <https://github.com/roe-dl> I totally agree with your method.
I tried to apply the changes in header.html.tmpl following #810, and I see
that I have other lines with a src=" external URL "

        <script type='text/javascript' src="//
ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type='text/javascript' src="//
cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js
"></script>
        <script type='text/javascript' src="
https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.33/moment-timezone-with-data.min.js
"></script>
 ...
        <script type='text/javascript' src="//
cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.1.0/paho-mqtt.min.js"></script>

Do I need to substitute these links with a local destination relative_url?

Thank's

**Comment by Geni0815** [comment]
@roe-dl  Vielen Dank, habe es auch lieber lokal .👍

**Comment by roe-dl** [comment]
@ddperso Yes, you have to replace those URL, too.

```
        <script type='text/javascript' src="$relative_url/lib/js/jquery.min.js"></script>
        <script type='text/javascript' src="$relative_url/lib/js/moment-with-locales.min.js"></script>
        <script type='text/javascript' src="$relative_url/lib/js/moment-timezone-with-data.min.js"></script>
```

`jquery-ui.min.js` is not required at all.

**Comment by RonV42** [comment]
Thanks @James-76 for the fix.  I did a reboot of my weewx and first thing I thought was when I migrated to proxmox for WeeWx I messed up something in the file transfer.

**Comment by seanford** [comment]
> This fix worked for me:
> 
> Edit belchertown.js.tmpl
> 
> Find this line at the end of the file:
> 
> var chart = new Highcharts.chart(options);
> 
> Change chart in Highcharts.chart to uppercase like this:
> 
> var chart = new Highcharts.Chart(options);
> 
> Save and wait for WeeWX (cheetah) to generate a new set of files
> 
> Charts have a bit of a different look (especially fontsizes) in this new version of Highcharts, so perhaps that will require some tweaking.



> This fix worked for me:
> 
> Edit belchertown.js.tmpl
> 
> Find this line at the end of the file:
> 
> var chart = new Highcharts.chart(options);
> 
> Change chart in Highcharts.chart to uppercase like this:
> 
> var chart = new Highcharts.Chart(options);
> 
> Save and wait for WeeWX (cheetah) to generate a new set of files
> 
> Charts have a bit of a different look (especially fontsizes) in this new version of Highcharts, so perhaps that will require some tweaking.

For those preferring to stick with Highchart v11 and use @ArendPWS fix, tryy this to get the font size to be closer to what it was:

In belchertown.js.tmpl, look for the following:

`Highcharts.setOptions({
    global: {
        //useUTC: false
        timezoneOffset: $highcharts_timezoneoffset
    },
    lang: {
        months: moment.months(),
        shortMonths: moment.monthsShort(),
        weekdays: moment.weekdays(),
        shortWeekdays: moment.weekdaysShort(),
        decimalPoint: "$highcharts_decimal",
        thousandsSep: "$highcharts_thousands"
    }
});`

and change it to:

`Highcharts.setOptions({
    global: {
        //useUTC: false
        timezoneOffset: $highcharts_timezoneoffset
    },
    lang: {
        months: moment.months(),
        shortMonths: moment.monthsShort(),
        weekdays: moment.weekdays(),
        shortWeekdays: moment.weekdaysShort(),
        decimalPoint: "$highcharts_decimal",
        thousandsSep: "$highcharts_thousands"
    },
    chart: {
        style: {
            fontSize: '0.9em'
        }
    }
});`

That gets it pretty close.

**Comment by tomdotorg** [comment]
also implemented @James-76 patch (thank you!!). I think the Highcharts version should be a config item or pinned to a specific Highcharts version. Ideally, it would be stored and packaged as part of the Belchertown distro, but I'd settle for not being subject to arbitrary breaking changes.

**Comment by ddperso** [comment]
I implement @roe-dl solution (which is the best solution to be
independent of external provider), but the lib directory is not copied
automatically to /var/www/html (I have added lib/* in skin.conf)
If I copy manually this directory, graphs are correct
Do you have an idea why?

Thank's

Le ven. 28 avr. 2023 à 13:19, Tom Mitchell ***@***.***> a
écrit :

**Comment by roe-dl** [comment]
It should work that way. Where is your `lib` directory situated? Could you show your `skin.conf`?

**Comment by ddperso** [comment]
lib directory is in /etc/weewx/skins/Belchertown/
Last lines of skin.conf:

###############################################################################

[CopyGenerator]

    # This section is used by the generator CopyGenerator

    # List of files to be copied only the first time the generator runs
    copy_once = favicon.ico, images/*, json/index.html, js/index.html,
js/responsive-menu.js, robots.txt, lib/*

    # List of files to be copied each time the generator runs
    copy_always = *.css


###############################################################################

#
# The list of generators that are to be run:
#
[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator,
weewx.reportengine.CopyGenerator, user.belchertown.HighchartsJsonGenerator

**Comment by roe-dl** [comment]
Is that one line or two lines at `copy_once`?

**Comment by ddperso** [comment]
1 line
I add just after robots.txt " lib/*"
If I remove all files in /var/www/html, after a few minutes new files are
displayed except lib directory

**Comment by ddperso** [comment]
I have made a mistake:
the copy_once has been included in weewx.conf, I have to add lib/* in
weewx.conf not in skin.conf
Sorry

**Comment by roe-dl** [comment]
Another thought. `copy_once` means it is copied only once after the start of WeeWX. If you want it copied without re-starting WeeWX you have to add it to the `copy_always` line.

**Comment by roe-dl** [comment]
Ah, ok. If you have a `copy_once` line in `weewx.conf` the `copy_once` line in `skin.conf` is not used.

**Comment by ddperso** [comment]
It's OK now
Thank's a lot

**Comment by earlthesquirrel** [comment]
Please let us know when there is a new release with this "updated" to whatever you settle on @poblabs.  I ended up chasing my tail a bit on this when the graphs disappeared... I ended up upgrading weewx and Belchertown skin to the latest versions (so not a total waste).  Then got caught on the empty forecast file (btw, turning off forecast and then turning it on after one wee_reports seems to fix that as well -- the empty file fix doesn't seem to work anymore... at least not for me...)

**Comment by bdruth** [comment]
Pushed a PR with one option that fixes this. Not as good as fixing-forward to v11, but it's a simple thing that gets everything working until someone has the bandwidth to look at v11 (and the font changes) in earnest.

**Comment by poblabs** [comment]
@bdruth thanks for the PR. I have release 1.3.1 to pin highcharts to version 10

https://github.com/poblabs/weewx-belchertown/releases/tag/weewx-belchertown-1.3.1

**Comment by ddperso** [comment]
The @roe-dl is a better solution...
When Highcharts10 will be discontinued, or disappeared, you will have the
same problem....

**Comment by James-76** [comment]
Whilst there are sensible arguments, it is also more effort currently for @poblabs, who has less time to spend on this currently as previously noted.

At the moment every Highcharts release since 2015 is online (both on the CDN and GitHub) so the risk of it disappearing is slim.

If somebody wants to package it up and upload it as a pull request then Pat may consider it, but at least the short term implemented does work. 

James

**Comment by kacnje** [comment]
I'm feeling like a great noob. 
I tried to update Belchertown skin as suggested on [https://github.com/poblabs/weewx-belchertown/releases/tag/weewx-belchertown-1.3.1](https://github.com/poblabs/weewx-belchertown/releases/tag/weewx-belchertown-1.3.1)

Download it and then run "wee_extension --install". But I always get:
```
Request to install '/home/pi/weewx-belchertown-release-1.3.1.tar.gz'
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 92, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 84, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 139, in install_extension
    raise InstallError("Extension '%s' not found." % extension_path)
weecfg.extension.InstallError: Extension '/home/pi/weewx-belchertown-release-1.3.1.tar.gz' not found.

```
I tried to be in the same folder, change the parameter with an absolute path, run as root, and change privileges ... but I always got the same error. I know the sun doesn't rise yet (early morning), but I still feel like a noob. 
Any idea?

**Comment by mrneutron42** [comment]
The missing charts problem is back on morning 5-9-2023.

**Comment by mrneutron42** [comment]
@James-76 
Why does only one of those lines have /stock/ in them?  
Should they all reference /stock/ ?
 
> ```
>         <script type='text/javascript' src='//code.highcharts.com/stock/10.3.3/highstock.js'></script>
>         <script type='text/javascript' src='//code.highcharts.com/10.3.3/highcharts-more.js'></script>
>         <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/exporting.js'></script>
>         <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/solid-gauge.js'></script>
> ```

**Comment by poblabs** [comment]
No, stock is reference to HighStock which is an "add-on" for HighCharts

**Comment by mrneutron42** [comment]
I note that the same code is available at:
https://code.highcharts.com/10.3.3/highcharts-more.js
https://code.highcharts.com/10.3.3/modules/exporting.js
https://code.highcharts.com/10.3.3//modules/solid-gauge.js
as well as
https://code.highcharts.com/stock/10.3.3/highcharts-more.js
https://code.highcharts.com/stock/10.3.3/modules/exporting.js
https://code.highcharts.com/stock/10.3.3//modules/solid-gauge.js
