### ISSUE TITLE
Missing Charts

### ISSUE THREAD

**Issue by Overcon** [poblabs/weewx-belchertown#886]
So I just noticed today, but it has probably been like this since 4/28; my charts are missing. I haven't made any changes server side. Does anyone know why they are missing and how to get them back? I updated to BT 1.3.1, and running Weewx 4.10.2 hoping those would resolve the issue, but no luck.

**Comment by WiggyToo** [comment]
I have the same issue - just noticed today - I'm on Belchertown Skin Version: 1.2 and have made no recent changes.

Site is here https://www.wiggytoo.co.uk/

It was working until recently but I can't say for sure when.

Tested with 3 browsers.

Any ideas?

**Comment by WiggyToo** [comment]
See this thread

https://github.com/poblabs/weewx-belchertown/issues/881

**Comment by Overcon** [comment]
Is there a step guide on how to update it?

**Comment by WiggyToo** [comment]
Hi, I scanned through the thread and related threads and followed these steps to go back to the old version of highcharts as a workaround. 

https://github.com/poblabs/weewx-belchertown/issues/881#issuecomment-1523289864

From @James-76 and it worked for me. 

Gav

**Comment by bctrainers** [comment]
It would appear the Highcharts library is primarily to blame. A major version change came with some significant changes; https://stackoverflow.com/questions/76111359/after-update-to-highcharts-js-today-we-get-highcharts-chart-is-not-a-constructor

What @WiggyToo posted would be the correct workaround/fix at this time.

**Comment by imzenreally** [comment]
@WiggyToo i just noticed my graphs are down as well and followed your post - appreciated - i also happened to take a peak at your site and like your graph layout - would you mind sharing your `graphs.conf`?

**Comment by WiggyToo** [comment]
@imzenreally 

Sure - here it is, although I think it came pretty much from the original skin install.
[graphs.zip](https://github.com/poblabs/weewx-belchertown/files/11497276/graphs.zip)

**Comment by imzenreally** [comment]
@WiggyToo very similar - you have the aggregate yearly averages which i like - perhaps the stock skin has been updated since i installed mine however many years ago -- regardless thanks

**Comment by Overcon** [comment]
I wasn't able to make any changes, other than updating WeeWx and the
Belcherton skin, but it has since started working again without any
modifications.

https://lovingtonweather.com


_________________
- Mitchell Tuckness

**Comment by swfrx** [comment]
> See this thread
> 
> #881

Specifically: https://github.com/poblabs/weewx-belchertown/issues/881#issuecomment-1523289864

`        <script type='text/javascript' src='//code.highcharts.com/stock/10.3.3/highstock.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/highcharts-more.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/exporting.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.3.3/modules/solid-gauge.js'></script>`

This has worked for me for now, but obviously in the longer term a better solution is needed.
