### ISSUE TITLE
Upgrading to 1.3 from 1.2

### ISSUE THREAD

**Issue by WiggyToo** [poblabs/weewx-belchertown#893]
### Discussed in https://github.com/poblabs/weewx-belchertown/discussions/888

<div type='discussions-op-text'>

<sup>Originally posted by **WiggyToo** May  9, 2023</sup>
Hi - I recently tried to move from 1.2 to 1.3 (and 1.3.1) - but the report generator threw some errors when trying to run the report for the Belchertown skin, it seemed to relate to Name issues but I had to revert to 1.2 as I ran out of time to investigate.

I want to have another go, are there are good debug tips for narrowing down what WEEWX is having a problem with?

Any advice gratefully received.

Thanks in advance,
Gav</div>

**Comment by swfrx** [comment]
I installed a new copy of weewx on my test RPi, worked my way through the skins there one at a time, when it came to Belchertown I amended weewx.conf and skin.conf  as necessary.

Note the current situation with Highcharts.
