### ISSUE TITLE
Issues with AppTemp In Records

### ISSUE THREAD

**Issue by KasturiNagarWeather** [poblabs/weewx-belchertown#9]
Hi Pat,

The apparent temperature high/low is not displayed properly in records page. The display is as below:

Highest Apparent Temperature | $year.appTemp.max | $year.appTemp.maxtime.format("%B %-d, %Y at %-I:%M %p") | $alltime.appTemp.maxtime.format("%B %-d, %Y at %-I:%M %p") °C | $alltime.appTemp.max
-- | -- | -- | -- | --
Lowest Apparent Temperature | $year.appTemp.min | $year.appTemp.mintime.format("%B %-d, %Y at %-I:%M %p") | $alltime.appTemp.mintime.format("%B %-d, %Y at %-I:%M %p") | $alltime.appTemp.min

Looks like some variable issue as the variable directly gets displayed on the page.

See same issue in Ghammer page also. So not an issue from my end

My page: http://bedi.co.in:15000/pc-aws/weather/belchertown/records/
GHammer page: https://ghammer.net/weather/records/

One is metric other imperial. So the issue is units independent.

Regards,
Praveen

**Comment by poblabs** [comment]
Have you extended the database to allow and calculate apparent temperature? [Check this part of the readme](https://github.com/poblabs/weewx-belchertown#general-options) under `show_apptemp` and you'll see the link on how to extend the database. 

Apparent temperature is not a default observation from weewx, so I am thinking you haven't enabled it.

**Comment by KasturiNagarWeather** [comment]
In mqtt broker i do see that apptenp has a value. So I assumed the database
would also have it. Is that not valid?

**Comment by poblabs** [comment]
Do you have appTemp in your archive database?

**Comment by KasturiNagarWeather** [comment]
You are right, I dont seem to have it. The steps to back calculate for past data and include look quite complex. I am disabling it for now. 

Also since appTemp includes wind speed and my wind speed is real time (every 2 seconds), the appTemp keeps fluctuation erratically.

**Comment by poblabs** [comment]
Yeah that's because it gets calculated every time the wind blows. This is standard practice since the apparent temperature can change between wind gusts (sometimes you may feel colder 1 minute than the next minute).
