### ISSUE TITLE
Additional graphs for extra sensors

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#90]
Hi, 
on the development skin 1.0 Im trying to add 2 graphs.
I added them to graphs.conf under /blechertown/graphs/ 
but I get the same old 4 graphs. 
here is my [day] graphs.conf
[day]
    # Chart Timespan Defaults
    time_length = today
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000 to get milliseconds. Standard is 5 minutes

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[dewpoint]]]
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
    
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
    [[chart5]]
	title = Inside
	type = spline
	[[[extraTemp5]]]
	[[[extraTemp7]]]
	[[[extraTemp2]]]
     [[chart6]]
	title = Freezers
	type = spline
	[[[extraTemp4]]]
	[[[extraTemp6]]]
	[[[extraTemp8]]]

**Comment by poblabs** [comment]
Hi the `graphs.conf` is created in the skins/Belchertown folder. You [can start by copying the `graphs.conf.example` to `graphs.conf` and making your changes](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#1-quick-start) there within graphs.conf. The graphs folder shouldn't have any files added to it.

**Comment by slvrscoobie** [comment]
that would explain why it was so hard to move the graphs.conf to the graphs folder? ;) 
Got it. Ill move it back.

**Comment by slvrscoobie** [comment]
ok, moved it back, now I get an error. 
Apr  6 19:54:01 raspberrypi weewx[21695]: sdr: MainThread: lines=['{"time" : "2019-04-06 23:53:52", "model" : "Fine Offset WH65B", "id" : 10, "temperature_C" : 13.900, "humidity" : 57, "wind_dir_deg" : 313, "wind_speed_ms" : 0.000, "gust_speed_ms" : 0.000, "rainfall_mm" : 338.074, "uv" : 2, "uvi" : 0, "light_lux" : 0.000, "battery" : "OK", "mic" : "CRC"}\n', '{"time" : "2019-04-06 23:53:54", "model" : "AmbientWeather-WH31E", "id" : 47, "channel" : 5, "battery" : "OK", "temperature_C" : 24.200, "humidity" : 38, "data" : "d400000000", "mic" : "CRC"}\n', '{"time" : 
Apr  6 19:54:27 raspberrypi weewx[21695]: sdr: MainThread: packet={'outTempBatteryStatus': 0, 'outHumidity': 57.0, 'light': 0.0, 'UV': 2.0, 'dateTime': 1554594864, 'windDir': 313.0, 'outTemp': 13.9, 'windSpeed': 0.0, 'rain_total': 338.074, 'usUnits': 17}
Apr  6 19:54:27 raspberrypi weewx[21695]: manager: Added record 2019-04-06 19:54:00 EDT (1554594840) to database 'weewx.sdb'
Apr  6 19:54:27 raspberrypi weewx[21695]: manager: Added record 2019-04-06 19:54:00 EDT (1554594840) to daily summary in 'weewx.sdb'
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Running reports for latest time in the database.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Report 'SeasonsReport' not enabled. Skipping.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Report 'MobileReport' not enabled. Skipping.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Report 'StandardReport' not enabled. Skipping.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Report 'NeoReport' not enabled. Skipping.
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Running report 'Belchertown'
Apr  6 19:54:28 raspberrypi weewx[21695]: reportengine: Found configuration file /etc/weewx/skins/Belchertown/skin.conf for report 'Belchertown'
Apr  6 19:54:28 raspberrypi weewx[21695]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown.getData']
Apr  6 19:54:28 raspberrypi weewx[21695]: manager: Daily summary version is 2.0
Apr  6 19:54:28 raspberrypi weewx[21695]: Belchertown Extension: New forecast file downloaded to /var/www/html/weewx/belchertown/json/darksky_forecast.json
Apr  6 19:54:30 raspberrypi weewx[21695]: cheetahgenerator: Generated 11 files for report Belchertown in 2.51 seconds
Apr  6 19:54:30 raspberrypi weewx[21695]: copygenerator: copied 2 files to /var/www/html/weewx/belchertown
Apr  6 19:54:30 raspberrypi weewx[21695]: manager: Daily summary version is 2.0
Apr  6 19:54:30 raspberrypi weewx[21695]: reportengine: Caught unrecoverable exception in generator 'user.belchertown.JsonGenerator'
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****  no such column: extraTemp5
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****  Traceback (most recent call last):
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      obj.start()
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      self.run()
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/user/belchertown.py", line 860, in run
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      output[chart_group][plotname]["series"][line_name]["data"] = self._getObservationData(observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length)
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/user/belchertown.py", line 1166, in _getObservationData
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      (time_start_vt, time_stop_vt, obs_vt) = self.db_lookup().getSqlVectors(TimeSpan(start_ts, end_ts), obs_lookup, aggregate_type, aggregate_interval)
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/weewx/manager.py", line 513, in getSqlVectors
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      aggregate_type, aggregate_interval)
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/weewx/manager.py", line 790, in _getSqlVectors
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      for _rec in _cursor.execute(sql_str, (startstamp, stopstamp)):
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****    File "/usr/share/weewx/weedb/sqlite.py", line 41, in guarded_fn
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****      raise weedb.NoColumnError(e)
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****  NoColumnError: no such column: extraTemp5
Apr  6 19:54:30 raspberrypi weewx[21695]:         ****  Generator terminated

but it is getting extraTemp5. 
"LOOP:   2019-04-06 19:54:59 EDT (1554594899) dateTime: 1554594899, extraTemp5: 75.56, maxSolarRad: None, rainRate: 0, usUnits: 1
"

**Comment by captain-coredump** [comment]
Stupid question - Did you extend the database schema to handle more than extraTemp1-3?  AFAIK, WeeWX will gladly read all kinds of LOOP data, but doesn't know where to stick it unless there's a corresponding field in the database schema...

-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by slvrscoobie** [comment]
Hmmmmmm i did not. 
Any advice on how to fix that? 
I did have them all (extraTemp1-8) showing up in the Seasons skin

**Comment by biltmorelaker** [comment]
Pat has the procedure on his wiki. [https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database](url)

**Comment by poblabs** [comment]
I think @captain-coredump is onto something. My database only has extraTemp1, 2 and 3. I have no idea how Seasons would show anything above that if it's not in your database.

**Comment by poblabs** [comment]
Just make sure you have backups. Then backup those backups 😃

**Comment by slvrscoobie** [comment]
Im still just setting up, so my backups arent too critical yet :)

**Comment by slvrscoobie** [comment]
It lives!! thanks guys!

**Comment by poblabs** [comment]
Awesome! Glad it's working 😃 Closing this for now, reopen it if you get stuck again.
