### ISSUE TITLE
Darksky language seems half supported?

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#91]
Hi !
I have set  darksky_lang either to en or fr but in both case it display the following:

1st day will be named "today" and following have french name "dim.", "lun." etc...( dim for dimanche = sunday, lun. for lundi = monday ....)
On the other hand, the weather description "rain", "partly cloudy" etc.. remain in english...

I tried both:```

darksky_lang = en
darksky_lang = "en"
```
or same with "fr"
(I have shorten forecast_stale to 60 and regenerate with wee_report to check this)

**Comment by poblabs** [comment]
There were some changes with locale in skin 0.9. If I recall, the DarkSky language is mostly for units, not the words for the days of the week. That's handled by moment.js (see below).

Can you paste the output of "locale" from your command line?

```
root@weewxlab:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

"Today" [will always be "Today"](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L365), but the other days should be in [your language based on the locale on your server](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L368).  

Is your site public?

**Comment by bonjour81** [comment]
Hi !

Other days are ok (in french), only "today" is in english (as it seems hardcoded, it's easy to change).
Then daily conditions like "rain", fog etc... are in english.
if needed, here is the output of my locale:
```
$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=

```

in the meantime, I also found that the weather condition is kind of "translated" inside the template here:
So it does not come directly from darksky neither :)
```
 var condition_text = "";
                switch ( data["daily"]["data"][i]["icon"] ) {
                    case "clear-day":
                        condition_text = "Clear";
                        break;
                    case "clear-night":
                        condition_text = "Clear";
                        break;
                    case "rain":
                        condition_text = "Rain";
                        break;
                    case "snow":
                        condition_text = "Snow";
                        break;
                    case "sleet":
                        condition_text = "Sleet";
                        break;
                    case "wind":
                        condition_text = "Windy";
                        break;
                    case "fog":
                        condition_text = "Fog";
                        break;
                    case "cloudy":
                        condition_text = "Overcast";
                        break;
                    case "partly-cloudy-day":
                        condition_text = "Partly Cloudy";
                        break;
                    case "partly-cloudy-night":
                        condition_text = "Clear"; // https://darksky.net/dev/docs/faq - So you can just treat partly-cloudy-night as an alia$
                        break;
                    case "hail":
                        condition_text = "Hail";
                        break;
                    case "thunderstorm":
                        condition_text = "Thunderstorm";
                        break;
                    case "tornado":
                        condition_text = "Tornado";
                        break;
                }

```
Now I'm not sure to understand the reason for the flag darksky_lang in weewx.conf ?

**Comment by poblabs** [comment]
Well, this is interesting. I also don't speak French 😄. The darksky lang was for the day names, but I guess I forgot the conditions. 

Condition names are tied to the image icon. So those are english. So I need to think about how to make this better - if there is a way. 

This will be something I have to add to my to do list. 

My to do list is rather long because this is my hobby, not my job. So I will keep this open and try to get to it

**Comment by poblabs** [comment]
Is your site public? If not please paste the section from darksky_forecast.json from daily. Like this. 

```
  "daily": {
    "summary": "Rain throughout the week, with high temperatures bottoming out at 52°F on Wednesday.",
    "icon": "rain",
    "data": [
      {
        "time": 1554523200,
        "summary": "Mostly cloudy until evening.",
        "icon": "partly-cloudy-day",
```

I use the `icon` to show Icon and small summary. I am thinking `icon` is in english?

**Comment by bonjour81** [comment]
The site is currently local (I work on a weather station I build myself...hehe same issue as you with hobby & to do list ;-) ).
Here is attached the json
[darksky_forecast.json.txt](https://github.com/poblabs/weewx-belchertown/files/3050993/darksky_forecast.json.txt)

I think the `icon` field is not translated, it's a keyword, not really a text. I would assume maybe only the `summary` field to be translated, but it seems in english the attached file (anyway this field is probably to long for the website)


The "switch/case" you used to build text from `icon` is easy to translate as a short term workaround, but In a more general way, I'm wondering how to manage a full translation of the skin ?
I mean: I can translate the text one by one on my side (already done for half of index.html), but do you think there is a smarter way to handle localisations ?

**Comment by bonjour81** [comment]
I think my previous darksky_forecast.json was done with "en" as  darksky_lang
See attached new file when  darksky_lang is set to fr.
As guessed, `summary` field is now in french :)
[darksky_forecast.json2.txt](https://github.com/poblabs/weewx-belchertown/files/3050995/darksky_forecast.json2.txt)

**Comment by poblabs** [comment]
[Translations](https://groups.google.com/d/msg/weewx-user/R0HygGOU5N8/ZBAIpxf_BgAJ) in weewx [are kind-of](https://github.com/weewx/weewx/issues/124#issuecomment-263137837) not really [supported](https://github.com/weewx/weewx/issues/124#issuecomment-263766365). I've taken Tom's guidance on not using gettext(). 

I suppose what I could do is make it a [label option](http://www.weewx.com/docs/customizing.htm#localization) that could be changed from within `weewx.conf` since there's only 13 of them.

I forgot I was using icon, not summary, for the summary. The DarkSky summary is too long so I needed a way to make it smaller.

**Comment by bonjour81** [comment]
It works if I just change `condition_text`
Like this :

```case "fog":
                        condition_text = "Brouillard";
                        break;```


But no need to add those 13 expressions to weewx.conf while the whole site is still in English ;)

**Comment by poblabs** [comment]
Adding labels to weewx.conf would allow it to survive upgrades. Otherwise you will make this change again in a few weeks when 1.0 is released and you choose to upgrade :)

**Comment by bonjour81** [comment]
But there might be a solution via github by forking your skin: I may be able to merge your upgrade with my translated files... But I'm a total noob in such things on github, got to learn :)

I agree adding labels would help, but It means not only those 13...
Here is attached a screenshot of a few translations I started. (I forget "visibility")
![Screenshot_20190407-010345](https://user-images.githubusercontent.com/24415431/55676250-72445200-58d1-11e9-8d69-ab4568c22781.jpg)

**Comment by poblabs** [comment]
I will have to verify later since I am not on my computer, but most of
those labels you translated could have been done within weewx.conf. See the
links I pasted above.

**Comment by poblabs** [comment]
Visibility would be a "14th" label since that also comes from dark sky.

All of the non-dark sky labels should be able to be translated from
weewx.conf. I will check later.

**Comment by poblabs** [comment]
Just checked, you're right. I hard-coded those labels. Don't know why I did that - noob mistake that I never cleaned up?

Ok, I have some work to do. I'll chip away at it when I can

**Comment by poblabs** [comment]
With that last commit there are 98 labels which can be modified (translated). I'm sure there are probably a couple more but these are the bulk of it. 

This will go in the 1.0 release.

**Comment by bonjour81** [comment]
Wow, you worked a lot while I was sleeping :)
I can try playing with your last development branch and see what happens
