### ISSUE TITLE
Things to put in Wiki for upgrade to 1.0

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#92]
I know @poblabs Pat has a bunch of stuff/notes for upgrading from 0.9.x to 1.0.x but thought I might start a list of questions or things to note. This can be closed when they get to the Wiki?

As well as removing all the Highcharts_Belchertown directory and files I assume for cleanup that references to those should be removed from Weewx.conf?

**Comment by 41south** [comment]
Going to add this as it's buried in another issue - I see it does cover my question above :)

Uninstall with the wee_extension --uninstall Belchertown command again. Run wee_extension --list to make sure weewx thinks it's gone.

Once done, manually check the skins folder for Belchertown and Highcharts_Belchertown. Delete any or both folder if they still exist.

Then go to your user/bin folder. Delete belchertown.py and delete belchertown_highchartsSearchX.py.

Then edit your weewx.conf and remove [[Belchertown]] and remove [[Highcharts_Belchertown]] skin sections from the report section.

Then when that is done, re-run your wget (because I just pushed another change), and install the zip file from wget.

**Comment by poblabs** [comment]
I have more testing to do, but the Release notes will go something like this:

# Upgrading
**Belchertown 1.0 has portions that have been completely rewritten. It is not recommended to upgrade from an older version to 1.0. Uninstall any old versions and install fresh.**

1. Backup your weewx.conf just in case. 
2. Uninstall Belchertown with the `wee_extension --uninstall Belchertown` command. Run `wee_extension --list` to make sure weewx thinks it's gone.
3. Manually check your `weewx/skins` folder for the `Belchertown` and `Highcharts_Belchertown` folders. Delete any or both folder if they still exist.
4. Then go to your `bin/user` folder and delete `belchertown.py` and delete `belchertown_highchartsSearchX.py` if they exist.
5. Then edit your weewx.conf and look for the `[StdReport]` section. Within that section remove `[[Belchertown]]` and remove `[[Highcharts_Belchertown]]` skin sections. Save your `[[Belchertown]]` Extras so you can put them back after you install 1.0.
6. Download the Belchertown 1.0 zip file and run `wee_extension --install weewx-belchertown-1.0.tar.gz`
7. Reconfigure your `[[Belchertown]]` Extras in weewx.conf, making sure `belchertown_root_url` is not missing.
8. Restart weewx and wait for an archive interval for the site to be generated.

**Comment by poblabs** [comment]
https://github.com/poblabs/weewx-belchertown/wiki/Upgrading-to-Belchertown-skin-1.0

**Comment by 41south** [comment]
I'll follow them when I do an upgrade today and add anything here that I find - thanks!

**Comment by 41south** [comment]
Ok first up, I wasn't sure which of the extras NOT to copy back so I left out only the lines relating to Highcharts.
# Enabled by default since majority of the theme is wrapped around $
            highcharts_enabled = 1
            highcharts_graph_1 = temperatureplot
            highcharts_graph_2 = barometerplot
            highcharts_graph_3 = windplot
            highcharts_graph_4 = winddirplot
            highcharts_graph_5 = rainplot
            highcharts_graph_6 = radiationplot
            highcharts_show_windchill = 0
            highcharts_show_heatindex = 0
            highcharts_show_apptemp = 1

I left in this ....

# If you've extended your weewx database to include the below, you $
            show_apptemp = 1
            show_windrun = 0
            show_cloudbase = 1

            # Default page headers
            graphs_page_header = Weather Observation Graphs
            records_page_header = Weather Observation Records
            reports_page_header = Weather Observation Reports
            about_page_header = About This Weather Station


On first run I have no charts etc on the home screen and no Windy map - investigating those but there are no errors being reported. Also the title says May Weather Station - not sure what I missed there

**Comment by 41south** [comment]
I also should have saved all of the Belchertown directory - whoops my bad, have lost all of the custom content

**Comment by 41south** [comment]
Ok I see there is a whole lot of combining of the old Extras and the new skin.conf to be done, in theory I should copy almost everything from skin.conf and put it under Extras??

**Comment by poblabs** [comment]
Yikes! Always have a backup 😞 I'll be sure to add that into step 1 in that wiki. If I recall, your about.inc was showing only the weewx and skin versions, which the new default one has as well. So hopefully it's an easy copy/paste to get you back to where you where. You did lose your lightning radar though. 

As for the highcharts options to keep you only need to keep `highcharts_enabled`, however it's `1` by default so you don't even really need that. For hints on what you may or may not want to override, check the skin.conf for all the options.

**Comment by poblabs** [comment]
Also if you're adding `.inc` files, you don't need to restart weewx - only a `wee_reports`. You only need to restart weewx when making changes to the belchertown.py, or weewx.conf or skin.conf files. Anything else in the skins folder can be updated without a weewx restart.

**Comment by 41south** [comment]
Windy sorted - copy paste error, graphs back. Yes all good with the other stuff too, not too much to sort, absolutely my bad on the backups, it was in the back of my mind to do and then just got fixated with following the steps :)
Now just need to go and sort how to put the solar chart back up and get App Temp showing without heat index and wind chill

**Comment by poblabs** [comment]
Yep, give the charts page a read over and suggest changes on anything that confuses you or needs more explanation. 

Removing heat index and windchill, and adding appTemp should be easy once you get started

**Comment by 41south** [comment]
Both the charts I wanted were there as examples so that was easy, anything new would take a bit of work though I think.
I added all the [[[units]]] etc back into weewx.conf too due to me using metric

**Comment by 41south** [comment]
Did the section to the left used to say "Today"? It looks a little out of whack with the "April 2019" to the right
![Screen Shot 2019-04-08 at 2 20 50 PM](https://user-images.githubusercontent.com/1725001/55694741-ad49a100-5a09-11e9-9bb5-5d7e4910e1cd.png)

**Comment by 41south** [comment]
Probably for the Charts Wiki, but just pop in a note about the behaviour of the rain graph with time periods less than a day. I'm pretty sure others will think like I did on that might work. It doesn't seem to affect any others (no calculations involved?)

**Comment by biltmorelaker** [comment]
@41south Currently in Section 7 - Tips is the following:

- Special rainTotal Observation Type:
The built in "rain" observation actually counts "bucket tips". The chart generated for this observation will show when the bucket tipped and that's all.
Using the special built in "rainTotal" observation - unique to Belchertown - will increment those bucket tips across the graph's time period, showing you the total rain for that time period.

Does that not cover the issue of how rain total is represented? Should it be made more explicit with an example describing what happens when rain scrolls to the left?

**Comment by 41south** [comment]
I think it would pay to, I certainly didn't understand how it worked from
that description

**Comment by biltmorelaker** [comment]
Will do! I'll expand that description.

**Comment by poblabs** [comment]
I've expanded the wiki to say this. If it needs editing, let me know - or if you want wiki access that can be accommodated too. Closing for now!

---

- Special rainTotal Observation Type:
The weewx archive type `"rain"` actually counts "bucket tips". That is, when the rain fills your rain collector and the bucket tips to count that rain measurement. The chart generated for `rain` will only show when the bucket tipped. It is not an aggregated total. Using the special built in **`"rainTotal"`** observation - unique to Belchertown - will increment those bucket tips across the graph's time period, showing you the **total rain calculation** for that time period.

**Comment by biltmorelaker** [comment]
I added one more line to the end of Pat's description to further clarify the fact that total rain does not include rain totals which precede the beginning of the time period of the graph.

---

- Special rainTotal Observation Type:
The weewx archive type `"rain"` actually counts "bucket tips". That is, when the rain fills your rain collector and the bucket tips to count that rain measurement. The chart generated for `rain` will only show when the bucket tipped. It is not an aggregated total. Using the special built in **`"rainTotal"`** observation - unique to Belchertown - will increment those bucket tips across the graph's time period, showing you the **total rain calculation** for that time period. This means that any calculated rain total which precedes the beginning of the graph time period will **not** be added to the rain total plotted on the graph.
