### ISSUE TITLE
Charts not displaying with error: chart_group is not defined

### ISSUE THREAD

**Issue by dseibel** [poblabs/weewx-belchertown#97]
Playing around with latest dev version and initially, charts seem to work fine, but after a short period of time the following error shows up in the web debug console.  This can happen on any and all of the today/week/month/year graphs. 

belchertown.js?1554838238:404 Uncaught ReferenceError: chart_group is not defined
    at Object.<anonymous> (belchertown.js?1554838238:404)
    at Function.each (jquery.min.js:2)
    at Object.success (belchertown.js?1554838238:370)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)

Seems to error out here:

          // Update moment.js locale format
            if ( chart_group == "day" ) {
                moment_format = "LLL";
            } else if ( chart_group == "month" || chart_group == "year" ) {
                moment_format = "dddd LL";
            } else {
                // Week charts and anything else undefined by a standard group
                moment_format = "LLLL";
            }

The graphs will eventually start displaying again (but I haven't noticed a correlation yet to when the archive interval runs), and then will fail with the same error.

**Comment by poblabs** [comment]
Interesting. That section is what updates the moment.js timestamp for the tooltip hover info. 

I haven't run across this on my site (which is running the development code). I've been keeping a close eye on it, too, with the JS Console open 24/7. 

Is your site public? 

What hardware are you running this on? (my thought is that maybe something is taking a long time to generate?)

**Comment by dseibel** [comment]
I was thinking maybe something with timing.  I have set your skin to load here: https://magpie.dantine.ca/weewx/stage/ to start playing around with it.  Right now it is running on a Raspberry PI model 2B

**Comment by poblabs** [comment]
Ok your site is helpful. I'm thinking timing too. Thinking the HTML `json` folder hasn't finished populating the chart data (all the `.json` files within that folder), and then the `ajaxweewx();` method fires while the json files haven't completed. 

How many graphs are you trying out? Looks like the standard 4 that it comes with?

I think there's a 30 second wait to allow for processing, maybe I need to make it longer - or a user option that can be tweaked in cases like this. 

But all of this said; you're not using MQTT updates and I'm seeing the charts fail. However I'm not that stack trace you're getting. So I'm still a bit confused. 

Your day.json passes a JSON test, so it's valid data. 

Can you turn on belchertown_debug in skin.conf and restart weewx?

![image](https://user-images.githubusercontent.com/3484775/55831090-5662cb00-5ae0-11e9-92bd-bd8db78d1ee7.png)

**Comment by dseibel** [comment]
I actually have it enabled, but restarting anyways.  Right now just trying to display the default graphs.  I think I have seen the error you are showing before, the error I listed you can probably see if you go to the graph page.

**Comment by poblabs** [comment]
The windy errors are from windy. I don't worry about those since I'm not
responsible for anything they can or can't do.

I'm mobile now will have to look later.

Earlier the debug was disabled so the restart should update that.

**Comment by poblabs** [comment]
Back now. Refreshed your site, and I'm not seeing any debug info. Your day.json is failing now though on a consumed energy reading. I'm assuming this is something you're changing (since thats not built into the theme)?


```
Parse error on line 42:
...ed Energy", "data": $consumedenergyDayjs
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by dseibel** [comment]
hmm that was my final goal but wanted to wait for version 1 before going through adding new charts 9I did have them working for some power info).  I thought I cleaned that up...  I have replaced that file with the included one now.  Still see the issue happening (if you cycle through the day/week/month/year buttons the error will come up).

I think debug should be on since I see these messages show up?

![2019-04-09_15-07-58](https://user-images.githubusercontent.com/8311761/55835858-26b0c480-5ada-11e9-8e00-3dd41735ff2a.png)

![image](https://user-images.githubusercontent.com/8311761/55835898-37f9d100-5ada-11e9-9af4-48812bbda681.png)

**Comment by poblabs** [comment]
Your site is back up, charts look fine until they get an update don't. What other customization have you done? Looks like you're trying to put all charts into 1 group?

Your day.json is rather large at 43,856 lines compared to mine at 10,303. 

Is your archive interval every 1 minute?

You have some customization that have gone haywire. 

Delete your graphs.conf and restart weewx and let it get stabilized for a few and see what happens. 

![image](https://user-images.githubusercontent.com/3484775/55835829-d857f180-5aea-11e9-990c-c382bb883443.png)

**Comment by dseibel** [comment]
Yes, interval is set to 1 min.  I will do as you suggest and see if ig stabilizes.  If not I will change the interval to 5 min to see if that helps.

**Comment by poblabs** [comment]
Those charts in the screenshot are supposed to be in chart groups. So either your `[]` brackets are off in graphs.conf, or something else is going on. 

Here's an example:

![image](https://user-images.githubusercontent.com/3484775/55836033-5a481a80-5aeb-11e9-8fb4-680120cb5119.png)

**Comment by poblabs** [comment]
The archive interval shouldn't matter - but it explains why you have so much data for the last 24 hours. 1 minute archive is extreme though. You'll have an enormous database by the end of your first month. 

http://www.weewx.com/docs/usersguide.htm#archive_interval

**Comment by poblabs** [comment]
Hmm this thought just hit me. 

Do you have the `Highcharts_Belchertown` skin installed on the same system? And configured in weewx.conf? That screenshot from above (the first one), looks like Belchertown 0.9.1 from the Highcharts_Belchertown skin. 

If you do, follow this set of instructions: https://github.com/poblabs/weewx-belchertown/wiki/Upgrading-to-Belchertown-skin-1.0

**Comment by dseibel** [comment]
Yes, I do, I will go through that info.  Sorry, I didn't see that, something I should have looked for...I will let you know!

**Comment by poblabs** [comment]
No problem! I just thought of that. I bet that's your problem - the day.json's are fighting with each other.

**Comment by dseibel** [comment]
So far so good.  Will check back tonight and close the issue.

thanks for your help!

**Comment by poblabs** [comment]
Sounds good. This was a learning one for me too to try and figure out why your day.json was looking strange. I've been so focused on 1.0 that I forgot what 0.9's formatting looked like 😄

**Comment by dseibel** [comment]
Looks good!  Looks to be mostly a RTFM issue, and your warning in the wiki is a good one, may need to point to this as something that can happen.
